### ISSUE TITLE
Missing cells when file misreports sheet range

### ISSUE THREAD

**Issue by Jeffery85** [SheetJS/sheetjs#1004]
I used same excel file to test in AngularJS + XLSX@0.8.0 and Angular 5 + XLSX@0.12.0.

In 0.12.0 version there is no record found in the worksheet. 

The code I used : 
```
         const reader = new FileReader();
         reader.readAsBinaryString(file);
         reader.onload = (evt: any) =>  {
         const data = evt.target.result;
         const workbook = XLSX.read(data, { type: 'binary' });
         const worksheet = workbook.Sheets[workbook.SheetNames[1]];
```
I debugged into both version, below are the observations:

**1.** Version **0.8.0** in function **parse_ws_xml**(data, opts, rels)
 
`var ridx = data.indexOf("<dimension");`  

got ridx = -1 , skip the below part:

```
        if (ridx > 0) {
            var ref = data.substr(ridx, 50).match(dimregex);
            if (ref != null)
                parse_ws_xml_dim(s, ref[1])
        }

```

s["!ref"] get the correct range:
```

        if (!s["!ref"] && refguess.e.c >= refguess.s.c && refguess.e.r >= refguess.s.r)
            s["!ref"] = encode_range(refguess);
```

**2.** Version **0.12.0** in function **parse_ws_xml**(data, opts, rels)

`var ridx = (data1.match(/<(?:\w*:)?dimension/)||{index:-1}).index;`

ridx = 380, run the below part, s["!ref"] get the default value (A1:AC1) which only contains the first line:
```
if(ridx > 0) {
		var ref = data1.slice(ridx,ridx+50).match(dimregex);
		if(ref) parse_ws_xml_dim(s, ref[1]);
	}
```

As s["!ref"] already got value, skip below part, the actual range will not be assigned.
```
	if(!s["!ref"] && refguess.e.c >= refguess.s.c && refguess.e.r >= refguess.s.r) 
            s["!ref"] = encode_range(refguess);
```

**Comment by reviewher** [comment]
@102397894 can you share a sample file?

**Comment by Jeffery85** [comment]
@reviewher 
The default dimension for the 2nd tab is <x:dimension ref="A1:AC1" />, upload it on http://oss.sheetjs.com/ just display the first line. 

However if I open this file and save it. The dimension comes to correct <x:dimension ref="A1:AC184" />.

**Comment by Jeffery85** [comment]
@reviewher here is the example file
[example.xlsx](https://github.com/SheetJS/js-xlsx/files/1746804/example.xlsx)

**Comment by SheetJSDev** [comment]
From the sheet2 xml:
```xml
  <x:dimension ref="A1:AC1"/>
```

The file is self-reporting the range as A1:AC1, and the parser honors that.  Excel recalculates the whole file by default.  We may change the default behavior at some point, but until then you can force a recalculation using the [`update_sheet_range` helper function](https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions#updating-worksheet-range)
