### ISSUE TITLE
Large Excel File Read Issue

### ISSUE THREAD

**Issue by Hirenp75** [SheetJS/sheetjs#1025]
Hi,
I have upload the 1059 kb size xlsx file.than try to convert in json format.it take the 3 mins.
Please give the proper solution.

**Comment by shibut12** [comment]
@Hirenp75 Can you share the code that you are using to upload and parse xlsx file? I have used sheetjs with worker process to parse really big excel file and never had to wait that longer.

**Comment by Hirenp75** [comment]
Hi,

I hope you doing well.

Gretting of day!!!!

Thanks for the quick response.

Right,Now i have Implement in my project.that code is not sharable due some
reason.so,first i want to make sample demo project same as my project
right.than i will share the code.

Thanks & Regards

Hiren Parejiya

On 8 Mar 2018 12:31 am, "Shibu" <notifications@github.com> wrote:

@Hirenp75 <https://github.com/hirenp75> Can you share the code that you are
using to upload and parse xlsx file? I have used sheetjs with worker
process to parse really big excel file and never had to wait that longer.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SheetJS/js-xlsx/issues/1025#issuecomment-371246861>,
or mute
the thread

**Comment by Hirenp75** [comment]
Resolved the Large Excel File Read Issue.

**Comment by begimai** [comment]
@Hirenp75 
how did you solve it? can you share with your code?

**Comment by Hirenp75** [comment]
Hi begimai,

i have refer the https://github.com/SheetJS/js-xlsx/tree/master/demos/angular link.

**Comment by begimai** [comment]
@Hirenp75 thank you

**Comment by sombek** [comment]
Is there any thing new about it?
To avoid the blocking I did the XLSX reading operation in a separate worker "other thread" so nothing blocks the main tread.
But now it takes around ~4 minutes to read a ~18MB file.
And crashes with ~100MB files 

We need a solutions please?
Any other libraries? Even if paid, just a good one with large data sets

**Comment by Hirenp75** [comment]
Hello there,

I just signed the petition "President of India: Campaign to Abolish Article
370" and wanted to see if you could help by adding your name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/8MCLvGgQ6v

Thanks!
Hiren

**Comment by MyAngularGit** [comment]
@sombek can you please share your code block or guide on how you implemented web worker for xlsx reading, because i'm getting error "Uncaught (in promise): ErrorEvent: {"isTrusted":true}".
Please help asap.

**Comment by reviewher** [comment]
There are many discussions on the topic of reading large files.  Closing in favor of #61  . Please follow the discussion there
