### ISSUE TITLE
I need to download large files, such as 100MB, and now only download 50MB browsers and crash

### ISSUE THREAD

**Issue by 125037225** [SheetJS/sheetjs#1038]
my code：
```
XLSX.write(workbook, {
      bookType: 'xlsx',
      bookSST:true,
      type: 'binary',
      compression:true
  }).then((content) => {
      let blobData = new Blob([tooArrayBufferView(content)], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
      saveAs(blobData, `${_this.fileName}.xlsx`)
  })
```

**Comment by SheetJSDev** [comment]
How large is the data set in question?  Also, are you sure you are using this library? (`XLSX.write` doesn't return a promise, it returns a binary string if `type` is set to `"binary"`)

**Comment by 125037225** [comment]
1. 
row=50000+,cow=45,and cell has style,like this:
let style = {
    font: {
      sz: 8,
      name: 'Microsoft YaHei',
    },
    border: {
      top: { style: 'thin', color: { rgb: '000000' } },
      right: { style: 'thin', color: { rgb: '000000' } },
      bottom: { style: 'thin', color: { rgb: '000000' } },
      left: { style: 'thin', color: { rgb: '000000' } }
    },
    alignment: {
      horizontal: 'center'
    }
  }
row=30000,the file is 49.9MB
2. 
type: 'binary'
3. XLSX.write doesn't return a promise
I change XLSX some code!

**Comment by anfasci** [comment]
what changes?

**Comment by Neldrick** [comment]
On my case , I use the library with react to write into file by chrome to let user download. However, the chrome browser crash and writefile didn't finished without any error

row 140,000  column : 25  

`XLSX.writeFile(workbook, 'out.xlsx', { bookType: 'xlsx', type: 'array', compression: true })`

any suggestion?

<img width="690" alt="Screenshot 2021-06-02 at 11 37 11 AM" src="https://user-images.githubusercontent.com/26188472/120420774-99a2e680-c397-11eb-9cf2-9ba49c71bb93.png">

**Comment by reviewher** [comment]
Combining the discussion with https://github.com/SheetJS/sheetjs/issues/77
