### ISSUE TITLE
Wrap text by column

### ISSUE THREAD

**Issue by john-yick** [SheetJS/sheetjs#1046]
Is there anyway to wrap text per column similar to excel?

![image](https://user-images.githubusercontent.com/17866270/37693826-3eeef4e2-2cfd-11e8-8af0-ef911e0a61d8.png)

**Comment by sgrogov** [comment]
Yes, specify cell style like that
```
cell.s = {
  alignment: {
    wrapText: '1', // any truthy value here
  },
};
```

**Comment by lujuliang** [comment]
Hey @sgrogov ， could you kindly told me how to add the style to merged cells or add the style to a range cells. thank you very much

**Comment by sgrogov** [comment]
Hi @lujuliang.

As far as I remember for merged cells you have to set your styles to the top left cell. But for borders styling you have to set styles to each cell just as if they were not merged.
And about range of cells just set styles to each cell.

Hope it's clear :)

**Comment by atljoseph** [comment]
```
cell.s = {
  alignment: {
    wrapText: '1', // any truthy value here
  },
};
```
Plain does not work.

Please provide a complete example, or documentation ...

Documentation on how to use your product EFFECTIVELY would be welcomed :)

**Comment by ugonnanwosu** [comment]
@lujuliang cell styling isn't supported in the core library. A fork exists with documentation for cell styles  [here](https://www.npmjs.com/package/xlsx-style#cell-styles

**Comment by macaranduba** [comment]
@ugonnanwosu Thanks for the pointer. Could you or any other colleague clarify if I should uninstall xlsx npm package before installing xlsx-style npm package?
Thanks!

**Comment by SheetJSDev** [comment]
This, along with other cell styling options, is provided in our [Pro builds](https://sheetjs.com/pro).  We may end up bringing all of that into the open source realm, but that will happen after a v1.0.0 release.

**Comment by atljoseph** [comment]
Are folks who pay also spared the pain and suffering of using your docs? Hope so. I just gave up and moved on with life.

**Comment by atljoseph** [comment]
That was the desired goal, right? To make people run away?
