### ISSUE TITLE
Hello, How can I apply conditions to autofilter in xlsx file?

### ISSUE THREAD

**Issue by kimjinyam** [SheetJS/sheetjs#1057]
Hello, I am noob of sheetJS.

I serached the autofilter apply.

----------
/* set AutoFilter range */
ws['!autofilter'] = { ref:"A1:D4" };
----------

but I can't found to apply conditions to autofilter in xlsx file.

I want apply conditions to use text, and get this sorted data.

Please help me someone. 
Thanks.

**Comment by reviewher** [comment]
closing in favor of #623 please follow up there
