### ISSUE TITLE
Updating a complex template

### ISSUE THREAD

**Issue by johnyesberg** [SheetJS/sheetjs#107]
I have a "Daily Report Template" xlsx workbook that contains charts and other complex formatting features. I'd like my nodejs code to populate some of the cells (on a "From Database" sheet) with data from a database. It feels a bit like trying to do a mail-merge in Word.

My code currently reads the Daily Report Template workbook, modifies some cells, and then writes (today's) Daily Report workbook. But charts and other formatting detail does not survive this round trip. 

In the long term, it would make sense to extend js-xlsx to parse all of the features. But I wonder if it makes sense to create the "From Database" sheet as I am currently, and then hacking around at the zip file level. I could make a new copy of the Daily Report Template, work out from the _rels which worksheets/sheet<n>.xml file is the "From Database" sheet, and replace that with the one from the file I've just written.

Do you think this approach might work? Do you think it might be useful for other people?

Thanks for your js-xlsx work!

**Comment by SheetJSDev** [comment]
In our [Pro builds](https://sheetjs.com/pro), we solve this problem with a special Template Editor build that just edits the content block without disrupting the rest of the data.  The approach is mostly incompatible with the object style used in this build.
