### ISSUE TITLE
Streams Support

### ISSUE THREAD

**Issue by jwerre** [SheetJS/sheetjs#1074]
I’m having trouble finding information about streaming an XLS. Is something like this possible with sheets.js:

```js
myDataStream
    .pipe( XLSX.stream() )
    .pipe( myWriteSteam )
```

**Comment by WazzaJB** [comment]
For anyone else who gets here looking to do the same, this works for me:

```javascript
    const { Readable } = require('stream');

    let binary = XLSX.write(wb, { type: 'buffer' });

    let stream = new Readable({
        read() {
            this.push(binary);
            this.push(null);
        }
    });

    stream.pipe(myWriteStream);
```

[Taken from a StackOverflow answer here](https://stackoverflow.com/questions/47089230/how-to-convert-buffer-to-stream-in-nodejs)

**Comment by SheetJSDev** [comment]
Most of the interesting formats cannot be parsed incrementally. https://github.com/SheetJS/sheetjs#streaming-read discusses it in more detail.

The readme gives an example of buffering the entire stream and passing to `XLSX.read`.

Writing can be implemented per-format and there are some stream utilities in `XLSX.stream` for writing CSV and HTML.  For formats that do not have a streaming write, @WazzaJB 's minimalist approach technically works
