### ISSUE TITLE
Identify table

### ISSUE THREAD

**Issue by grosch** [SheetJS/sheetjs#1075]
How do I tell the worksheet what the table name/range is so that I can use it in an 'f' definition?

**Comment by grosch** [comment]
![screen shot 2018-04-14 at 1 10 36 pm](https://user-images.githubusercontent.com/315966/38772158-3dd20bc6-3fe5-11e8-9dbf-c299b4914de7.png)

I want to be able to do something like this (shown when I printed out the value from doing an XLSX.read() call)...but of course not explicitly set the `v` value.

**Comment by SheetJSDev** [comment]
The implicit variables hinge on the presence of "Format as Table" tables which are a part of our [Pro offering](https://sheetjs.com/pro)
