### ISSUE TITLE
browser crash when data contain chinese data length more than 150K

### ISSUE THREAD

**Issue by llccing** [SheetJS/sheetjs#1076]
please help , this is [demo](https://jsfiddle.net/eywraw8t/44427/) 

browser: chrome  65.0.3325.181
OS: windows 7

**Comment by SheetJSDev** [comment]
@llccing The Chinese example runs in the same browser version on OSX (testing against a macbook pro) , generating a 18MB file!  If you see the crash symbol and click "wait", does it generate a file?

**Comment by llccing** [comment]
@SheetJSDev ,thanks for answer. if i click 'wait' , i will also crash.

**Comment by SheetJSDev** [comment]
I couldn't reproduce on windows using the same version.  It twice asked to wait, and after clicking both times it generated a file.

Can you try possibly running the same test from an incognito tab, or otherwise reinstalling chrome?

**Comment by llccing** [comment]
i test it on thinkpad t470 , but same problem

**Comment by reviewher** [comment]
Grouping with #77
