### ISSUE TITLE
Newline characters in cells of written workbooks

### ISSUE THREAD

**Issue by notatestuser** [SheetJS/sheetjs#108]
When values `v` of cells contain unix line endings `\n` they do not become line breaks in the corresponding cells of the written workbook. However, when the Windows carriage return newline combos `\r\n` are used Excel appears to properly break the lines when a cell containing them is double clicked (edited).

![screen shot 2014-09-11 at 11 44 40](https://cloud.githubusercontent.com/assets/1255926/4232062/49c1bd2a-3998-11e4-8dd1-6577a8391ff4.png)

So there appear to be two things to potentially address here:
1. Unix line endings `\n` do not become new lines at all in the written file
2. Windows line endings `\r\n` only become newlines in Excel when the cell is edited. This may be a shortfall in Excel for Mac 2011 and may not apply to the Windows version.

**Comment by tophsic** [comment]
Using booSST:true seemed to work for me when opening xlsx file on Linux and LibreOffice but didn't work on Excel on Win 10.

**Comment by dferer** [comment]
bookSST:true doesn't work for Excel on Mac (Office 365) either.

**Comment by reviewher** [comment]
@tophsic @dferer can you share either a code sample or a bad file generated by the library?

**Comment by lumio** [comment]
@reviewher [here](https://codepen.io/lumio/pen/PJNBjv) is a code example.

It works fine with macOS numbers. I didn't test it with LibreOffice yet. But Excel 15.17 under macOS ignores the line breaks at first, but adds them as soon as you double click on the cell.

**Comment by qqilihq** [comment]
Did someone find a workaround? We the same issue on Excel macOS and Excel Windows -- text is shown in a single line and changes on double click.

Apple Numbers shows the file correctly.

**Comment by zaddok** [comment]
I have the same problem. Did anyone find a workaround?

**Comment by fozcode** [comment]
I could only get this working correctly using the Pro edition where the saving of cell styles is supported. It needed: `\n` in the string value, `bookSST: true, cellStyles: true` in `XLSX.write`, and `cell.s = { alignment: { wrapText: true } }` in the cell style.

**Comment by SheetJSDev** [comment]
To summarize: merely placing a newline character is insufficient.  Excel requires the text wrapping style attribute to be applied to the cell, otherwise it is rendered like a whitespace character.  This is a part of our Pro builds.

@fozcode I don't believe `bookSST: true` is required, if you have a bad case email us.

**Comment by fozcode** [comment]
@SheetJSDev I've tested again and you are correct, `bookSST: true` is not required for Excel.

In LibreOffice a multi-line string is displayed on one line unless you set `bookSST: true`, which I guess is a LibreOffice bug. When you click into the cell the lines are then shown correctly.

**Comment by jefleponot** [comment]
it seems to not be correct tag in xlxs.js file :line 19974
			.replace(/\n/g, "**<text:line-break/>**")
instead of
                        .replace(/\n/g, "**</text:p><text:p>**")

**Comment by SheetJSDev** [comment]
@jefleponot Reviewing the spec http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html

`<table:table-cell>` (9.1.4) has `<text:p>` (5.1.3) children

`<text:line-break>` (6.1.5) is a valid child of `<text:p>`, which was originally interpreted to be a newline character.

You're proposing we create separate paragraphs for each logical line, which is fine but I'm curious why the line break doesn't work

**Comment by jefleponot** [comment]
Could I propose a PR ? Could you accept it ?

**Comment by jefleponot** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=43107

**Comment by lukaselmer** [comment]
> To summarize: merely placing a newline character is insufficient. Excel requires the text wrapping style attribute to be applied to the cell, otherwise it is rendered like a whitespace character. This is a part of our Pro builds.
> 
> @fozcode I don't believe `bookSST: true` is required, if you have a bad case email us.

@SheetJSDev is there a solution for the community edition?

**Comment by GusMartins499** [comment]
> a solution for the commu

same issue

**Comment by jdegger** [comment]
Anybody ever found a solution for community edition? We can not access the pro edition because we have not received replies yet when we reach out...

**Comment by binaryn3xus** [comment]
Why is something as simple as a newline behind a paywall (Pro)?

**Comment by kentmor** [comment]
Same issue

**Comment by KrunchMuffin** [comment]
😞

**Comment by vfa-tanna** [comment]
Add more VBA Code to resolve this
`wsSrc.Cells.WrapText = True`
