### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by rhanb** [SheetJS/sheetjs#1113]
Hi @SheetJSDev ,

First of all, thanks to the SheetJS team for your great work, this lib is a real time saver!

Although, I'm facing issues when dealing with big amount of data. 

### Context

I'm working for a telecom company, and they have a webapp allowing their customers to download some of the data about their SIM card's consumption, Devices etc.. So basically some of their data need to be exportable in CSV/XLS/XLSX. 

All the data is retrieved through HTTP calls on a REST API. To avoid any issue with the amount of data retrieved we decided to retrieve data recursively. Each call retrieve 500 rows of data.

js-xlsx: `0.12.11`

### Issue

We've got the issue with one of the company's customer whom wanted to export more than 40k rows of data. I reproduced the bug and I was watching the JS Heap Size Performance Monitor, I saw that there was no issues until I called the lib to build the CSV/XLS/XLSX file. Even though I'm retrieving data recursively I was calling the lib only when all the data was retrieved in a local basic `array`.

#### Simplified code:
```typescript
import { write, utils, readFile, read, writeFile, WritingOptions, WorkBook, WorkSheet } from 'xlsx';

localeData: any[] = [];

initDownload() {   
    this.getDataRecursively(0);
}

getDataRecursively(
    pageIndex: number,
    totalCount?: number) {  // totalCount being the number of total rows to retrieve.
      const shouldContinue: boolean = true | false; // condition to stop recursion, dummy version
     if (shouldContinue) {
          dataGetter(pageIndex)
                 .subscribe(response: any[]) {
                      this.localeData = [...this.localeData, ...response.body];
                      this.getDataRecursively(pageIndex++, response.headers['totalCount'];
                  }
     } else {
         this.endDownload();
     }
}

endDownload() {
     const workbook = utils.book_new();
     const worksheet = utils. json_to_sheet(this.localData);
     utils.book_append_sheet(workbook, worksheet);

     writeFile(workbook, 'test.xls');
}

```
!!! This is a simplified version of the original code !!! 

So my first thought was to fill the worksheet every time I'm retrieving 500 rows instead of using a local `array`. And the effect was positive, since the JS Heap Size was higher at every HTTP call and way more lower at the end since the worksheet was already filled. 

``` typescript
import { write, utils, readFile, read, writeFile, WritingOptions, WorkBook, WorkSheet } from 'xlsx';

initDownload() {
     const worksheet = utils.json_to_sheet([]);
        
    this.getDataRecursively(0, worksheet);
}

getDataRecursively(
    pageIndex: number,
    worksheet: WorkSheet
    totalCount?: number) {  // totalCount being the number of total rows to retrieve.
      const shouldContinue: boolean = true | false; // condition to stop recursion, dummy version
     if (shouldContinue) {
          dataGetter(pageIndex)
                 .subscribe(response: any[]) {
                      utils.sheet_add_json(worksheet, response.body);
                      this.getDataRecursively(pageIndex++, worksheet, response.headers['totalCount'];
                  }
     } else {
         this.endDownload(worksheet);
     }
}

endDownload(worksheet: WorkSheet) {
     const workbook = utils.book_new();
    utils.book_append_sheet(workbook, worksheet);

     writeFile(workbook, 'test.xls');
}
```

But since everything is computed on the client side, the performance depends also of the machine of the client. And unfortunately the bug still occurs for some of our customers and it comes directly from the `writeFile` function. The CPU is at 100% usage and the JS Heap Size goes up to 2go of RAM.

I saw several issues with this kind of problem but I didn't find any respond that could fix my issue.

Hope it's clear enough, please ask me more infromations if needed.

Cheers from France 🇫🇷 ,

@rhanb

**Comment by SheetJSDev** [comment]
The CPU spike isn't surprising because the whole operation is mostly CPU-bound.  The memory usage may or may not be unexpected since the expected file size is pretty large to begin with, and due to how most mobile APIs work we have to build the entire file in memory first.

Is it specifically the XLS output that is spiking memory?  Is the same thing happening with CSV or XLSX?  What devices are triggering this problem?

**Comment by rhanb** [comment]
@SheetJSDev we have this issue on desktop under the latest version of Chrome. We didn't even try on a mobile. 

For the format I'm not sure, I will test that on Monday! 

Thanks for your feedback 👍

**Comment by rhanb** [comment]
@SheetJSDev the issue doesn't occurs with a CSV format. One of our client actually doesn't have a huge JS Heap Size (750Mb), the crash comes from the CPU usage at 100%.

**Comment by sibelius** [comment]
maybe this could help

```
<--- Last few GCs --->

[18943:0x102802400]   221927 ms: Scavenge 1343.3 (1422.6) -> 1342.6 (1423.1) MB, 5.8 / 0.0 ms  (average mu = 0.214, current mu = 0.113) allocation failure
[18943:0x102802400]   221952 ms: Scavenge 1343.5 (1423.1) -> 1343.0 (1423.6) MB, 5.7 / 0.0 ms  (average mu = 0.214, current mu = 0.113) allocation failure
[18943:0x102802400]   222000 ms: Scavenge 1343.8 (1423.6) -> 1343.4 (1424.6) MB, 13.8 / 0.0 ms  (average mu = 0.214, current mu = 0.113) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2846208041bd]
    1: StubFrame [pc: 0x28462089856f]
Security context: 0xd5fb069e6c9 <JSObject>
    2: /* anonymous */ [0xd5fcf621f09] [/Users/sibelius/Dev/entria/app/app-server/node_modules/xlsx/dist/cpexcel.js:49] [bytecode=0xd5f1cf25659 offset=3511](this=0xd5f9ff5de19 <JSGlobal Object>)
    3: Object.<anonymous> [0xd5f18d6e0a1] [/Users/sibelius/Dev/entria/app/app-server/node_modules/xlsx/dist/...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100033c31 node::Abort() [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 2: 0x1000353ea node::FatalTryCatch::~FatalTryCatch() [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 3: 0x10019bc9a v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 4: 0x10056a072 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 5: 0x100569029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 6: 0x100566cb8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 7: 0x1005731fc v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 8: 0x10054174e v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 9: 0x1004ec39b v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
10: 0x1004ec246 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
11: 0x1004ec8ac v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastHoleyObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)3> >::AddImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
12: 0x100677248 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::ShouldThrow) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
13: 0x1007dfa09 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal
```

**Comment by wafs** [comment]
I'm also experiencing this issue. From my understanding, when the library is about to write the file it attempts to turn everything into one giant string and join them - before this moment they are all sitting as multiple strings/objects in memory and Node can handle that just fine.

In the source code you'll see this in many places as `<something>.join("")`. 

In some large datasets, replacing all the `.join("")` calls with a `for(const str of array){ outStr += str}` helped since the GC could clean up some of the litter, but then that too would start failing when there was just a huge amount of data to sift.

The only thing that would fix large data handling is streaming/batch writing, for example if the files were being written as they went, using the `fs.writeStream` API.
Alternatively: using `fs.write` in a loop in append mode, but this means instead of their files returning one fat string of all the rows, they should just return an array of all the rows with the string contents. 

Either way these are both very fixable in the short term by patching the source code with these changes but unsure what kind of breaking changes would occur.

**Comment by SheetJSDev** [comment]
@wafs https://bugs.chromium.org/p/v8/issues/detail?id=3175 , a bug affecting NodeJS and Chrome, is why arrays are used to build up strings.  7 years later the performance landscape has improved so we'd have to go back and see which approach is better.

**Comment by SheetJSDev** [comment]
@rhanb @sibelius please test again against the latest version and see if you can reproduce the issue.  There have been Chrome improvements when dealing with large objects.

@wafs please follow https://github.com/SheetJS/sheetjs/issues/77 for more details
