### ISSUE TITLE
how can i lock (make it read only) a specific column ? 

### ISSUE THREAD

**Issue by ebra100** [SheetJS/sheetjs#1126]

**Comment by tanakorn-mint** [comment]
Any update on this?

**Comment by ankurgupta325** [comment]
I am stuck at this too. Is it possible to lock whole column ? and how ?

**Comment by SheetJSDev** [comment]
Like most styling features, we offer this in our [Pro builds](https://sheetjs.com/pro)

For XLSX, the default is all cells locked.  To unlock a column, you would have to set a column style as well as styles for each cell in the column.  The last step is to protect the worksheet (which you can actually do here by setting the `!protect` key)

SYLK has the option to default to unprotected but the same principle applies
