### ISSUE TITLE
Angular 5 app breaks when using XLSX to export table to .xlsx file in prod build.

### ISSUE THREAD

**Issue by rakeshrnjn** [SheetJS/sheetjs#1128]
I'm trying to use xlsx package for exporting files from table to .xlsx file. It works on normal build but breaks on prod build in Angular 5.

                let sheetName;
		var tbl = document.getElementById(this.activeTab);
			/* generate worksheet */
		let ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(tbl, {raw:true});

		ws['!cols'] = [
			{wpx: 200}, // "characters"
			{wpx: 200}, // "pixels"
			{wpx: 200},
			{hidden: true} // hide column
		];

			/* generate workbook and add the worksheet */
		const wb: XLSX.WorkBook = XLSX.utils.book_new();
		XLSX.utils.book_append_sheet(wb, ws, sheetName);

			/* save to file */
		XLSX.writeFile(wb, this.fileName, {type: "base64"});`

Thanks

**Comment by reviewher** [comment]
What is the error message?  Can you share a sample project?

**Comment by SeregPie** [comment]
The new version 0.13 also breaks my app. Needed to downgrade to 0.12.13.

I'm usings an external library, that adds a function to XLSX.utils. This library is packed using rollup. My app is packed using webpack. Looks like there is an issue with `import default`.

**Comment by SheetJSDev** [comment]
@SeregPie @rakeshrnjn 0.13.0 now call the AMD `define` if available, so there may be some issue pertaining to 

I can't reproduce in angular 5 using [the demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2):

```
$ git clone https://github.com/SheetJS/js-xlsx/
$ cd js-xlsx/demos/angular2
$ npm install
$ npm install xlsx@0.13.0
$ npm start
```

AFAICT that build structure does not use rollup.

The [`rollup` demo appears to work too](https://github.com/SheetJS/js-xlsx/tree/master/demos/rollup).  The following commands make a node bundle and a browser bundle using rollup:

```
$ cd js-xlsx/demos/angular2
$ make init
$ npm install rollup-plugin-node-resolve rollup-plugin-commonjs
$ npm install xlsx@0.13.0
$ make
$ python -mSimpleHTTPServer
```

If you can share a small project, we can take a further look.

**Comment by rakeshrnjn** [comment]
@SheetJSDev use this [demo](https://github.com/rakeshrnjn/xlsx-js) to reproduce this issue.

It works fine when we serve using ng serve. but if we build in prod mode and serve the bundle file on any server then `<app-root></app-root>` tag is empty.

**Comment by SheetJSDev** [comment]
The demo works for me:

```
$ git clone https://github.com/rakeshrnjn/xlsx-js
$ cd xlsx-js/
$ npm install
$ npm run build
$ cd dist
$ python -mSimpleHTTPServer
```

Are there any errors in the console?  You have to serve the generated files from the dist directory.

**Comment by rakeshrnjn** [comment]
@SheetJSDev  Thanks for the replies. There are no errors in console, But we are still facing the issue with prod build. The problem is when we create the dev build and serve it on local server like xampp/wampp it works fine. 

When we create the prod build with the flag --prod and then deploy the files on some web server then the <app-root> tag becomes empty which indicates that our angular app was not getting bootstrapped. Though all the bundled files are present in the JSP which is served by the webserver, still the app does not get bootstrap.
This only happens if we use the XLSX methods/properties. If we just import and don't use any methods/properties it works fine.
Any suggestions... why the app is not getting bootstrapped?

**Comment by SheetJSDev** [comment]
@rakeshrnjn the `build` command in the `package.json` is running `ng build --prod` so if there were an obvious issue it would have shown up in the example.  Are you using a nonstandard angular configuration?  How are you reproducing the error using the linked demo?

**Comment by rakeshrnjn** [comment]
@SheetJSDev We deploy our bundled files on a webserver from where these files are accessed by embedded tomcat server.

what do you mean by nonstandard angular configuration?

whatever we have in the index.html file is served in jsp.
If we serve this demo on my local xampp server, it works fine.

**Comment by olishiz** [comment]
Hey any updates on this issue? I'm currently facing the same issue. 
My build artifact on Angular 9 unable to show data as intended.
Issue link -> https://github.com/SheetJS/sheetjs/issues/2357

**Comment by reviewher** [comment]
Since this works with the standard new ng project setups, we can only assume the issue lies with how Angular or your specific projects work with the library in prod mode.  This is unfortunately the type of issue that would require someone well-versed in Angular to diagnose.
