### ISSUE TITLE
Reading Data from Streams 

### ISSUE THREAD

**Issue by iweb1997** [SheetJS/sheetjs#1151]
I am trying to Read xlsx file Data in Streams . Below is my Code .

var fs = require('fs');
var XLSX = require('xlsx');
var streams = fs.createReadStream(__dirname + '/100264_30k.xlsx');

streams.on('data',function(chunk){            
    var wb =   XLSX.read(chunk, {type:"buffer"});
    console.log(wb);    
});

streams.on('end',function(){
    console.log('End reaches');
})

But When I Trying to console.log(wb) . It Gives Me a Error , Can't find end of central Zip. Please take a look at the following Image.

https://i.stack.imgur.com/XDv9N.png

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/#streaming-read You should concatenate the stream and read at the end:

```js
  var buffers = [];
  stream.on('data', function(data) { buffers.push(data); });
  stream.on('end', function() {
    var buffer = Buffer.concat(buffers);
    var wb = XLSX.read(buffer, {type:"buffer"});
    console.log(wb);
  });
```

**Comment by vuthinh0301** [comment]
@SheetJSDev i want to handle workbook chunk by chunk. Is there any way? 
How is its performance?

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/solutions/input#example-readable-streams read the "technical details" to understand why there is no streaming implementation out of the box, then look at the code samples for some ideas for how to handle streams
