### ISSUE TITLE
DataTable to Worksheet incorrect datetime parsing

### ISSUE THREAD

**Issue by trololog85** [SheetJS/sheetjs#1163]
I have a html table that is being converted to a worksheet with the following method:

XLSX.utils.table_to_sheet

On the rows of the datatable has this input: "InActive from 06/28/2018". Instead of taking the string literal, the code parse the date from the text and replace it into the column value. 

Column output value: 06/27/2018. Expected output: InActive from 06/28/2018.

**Comment by harbhub** [comment]
Try setting it to "raw: true" so that the Date isn't parsed.

**Comment by cdskill** [comment]
I need to know too, I have the same problem... Any solution ?

**Comment by bean5** [comment]
@trololog85 does this happen for you with CSV and XLSX file types? Did you attempt the advice from https://github.com/SheetJS/js-xlsx/issues/1163#issuecomment-401160686 ?

**Comment by bean5** [comment]
@harbhub I've tried `raw: true` without success. See also https://github.com/SheetJS/SheetJS.github.io/issues/14 .

**Comment by SheetJSDev** [comment]
`raw: true` has to be passed to `XLSX.read` to skip date parsing from CSV files.  Instead, the file will be broken up according to quoting logic and strings will be generated.
