### ISSUE TITLE
Removing empty column from row

### ISSUE THREAD

**Issue by dhirajkr2015** [SheetJS/sheetjs#1191]
Hi All,

When I am uploading the excel file to convert into JSON data.
I am facing the problem. Its removing the empty column which having value empty..
Please help me.

Regards,
Dhiraj

**Comment by DJeanCar** [comment]
I have the same issue, I am using **defval** like say the documentation and it does not work.

**Comment by BFASNicholasH** [comment]
We are also experiencing this issue.  When all rows have an empty value for a particular column, it is dropping said column.  We don't want to lose that column, we need to know that there is an empty value for that column.

**Comment by dhirajkr2015** [comment]
I have modified the code and working fine as expected. I will ccheck the code and let you know.

**Comment by BFASNicholasH** [comment]
> I have modified the code and working fine as expected. I will ccheck the code and let you know.

That would be great if you have a fix.  After you check the code, can you share the fix with us?  We'd like to get this working as well :)

**Comment by SheetJSDev** [comment]
When using the `sheet_to_json` utility, the `defval` option allows you to specify a default value and force the columns to appear.

If the column header is missing, it will be stored at a dedupe'd key starting with `__EMPTY`.

If you can share an example we can take a closer look.

**Comment by Reejesh-PK** [comment]
Make sure you are using the latest version of js from https://cdn.sheetjs.com/ (Read "how to use") and you can refer this https://github.com/SheetJS/sheetjs/issues/159#issuecomment-403228877
