### ISSUE TITLE
How to Read Large Excel Files?

### ISSUE THREAD

**Issue by chobo2** [SheetJS/sheetjs#1195]
Hi

However I can have some very large excel files that could contain 1 million rows.

I tested with 600K rows which is about 15mb excel file and my code is already crashing on localhost.

Is there away to stream it in? I know the documentation says they don't have any sort of streaming api but it talks about buffering?

```
     var reader = new FileReader();
        reader.onload = evt => {
          const bstr = evt.target.result;
          const wb = XLSX.read(bstr, { type: "binary" });
          const wsname = wb.SheetNames[0];
          const ws = wb.Sheets[wsname];
          const data = XLSX.utils.sheet_to_json(ws, { header: "A", defval: "" });
          });
        };
        reader.readAsBinaryString(this.file);
```

**Comment by aladinelkhalil** [comment]
I have the same problem

**Comment by danieler1981** [comment]
Has someone found a way to handle this scenario?

**Comment by reviewher** [comment]
There are many discussions on the topic of reading large files.  Closing in favor of #61  . Please follow the discussion there
