### ISSUE TITLE
How to add custom header and each column have own tooltip

### ISSUE THREAD

**Issue by anilmcmt** [SheetJS/sheetjs#1197]
How to add custom header and each column have own tooltip

**Comment by wu529778790** [comment]
I want to have a custom header in data not in header data

**Comment by SheetJSDev** [comment]
"tooltip": there is no tooltip property in Excel.  There are two ways to fake the effect:

1) "data validations" -- this is not currently supported in our open source offering and we are unsure of the timeline.  It will definitely not be part of the 1.0.0 release, which will primarily be focused on correctness of data processing.  We do offer it in the interim in our [Pro compendium](https://sheetjs.com/pro)

2) "hyperlinks" -- you can create a hyperlink on a cell back to itself, see the "Hyperlinks" section of the README for more details

"custom header": you would have to be more specific, but you can always modify the cell text directly.
