### ISSUE TITLE
When using SheetJS in an Angular4 project, the module is not resolving.

### ISSUE THREAD

**Issue by mattking4** [SheetJS/sheetjs#1203]
Hi,

I'm trying to use SheetJS in an Angular 4 project (derived from Angular Seed Advanced), and I can't get my SheetJS to work from a build (it does work from Gulp though).  I've followed guidance from previous Issues, culminating in the following:
https://gist.github.com/vinhboy/78c7b2a8efd866ea36d2109bd33e93af

The build process succeeds, but when I run it in a browser it crashes,  saying "Uncaught Module 150 not present."  Module "150" is an arbitrary string that's getting injected during my build process.  Here's the top of my component that uses SheetJS:

import * as FileSaver from 'file-saverjs';
import * as XLSX from 'xlsx';

'xlsx' is defined by index.d.ts in SheetJS' 'types' directory. During build this gets converted into:

var FileSaver=$__require("14f");
var XLSX=$__require("150");

The component itself is registered in the build with a function beginning:

$__System.registerDynamic("8d",["e","14f","150"],true,function($__require,exports,module) {

So, those two bits of code expect a module "150" to be defined, and that happens in this function (from xlsx.full.mins.js, and built into my app.js):
( function(e) {
    if ("object"==typeof exports&&"undefined"!=typeof module&&"undefined"==typeof DO_NOT_EXPORT_JSZIP) {
        module.exports=e();
    } else if("function"==typeof define&&define.amd&&"undefined"==typeof DO_NOT_EXPORT_JSZIP) {
        JSZipSync=e();
        define([],e);
    } else {
        var r;
        "undefined"!=typeof window?r=window:"undefined"!=typeof global?r=global:"undefined"!=typeof $&&$.global?r=$.global:"undefined"!=typeof self&&(r=self),r.JSZipSync=e();
    }
})

However, in the copy of this function that ends up in app.js, there is one change, the 'define' line now says:

define("150",[],e);

It is notable that the 'define' line can't be reached, since DO_NOT_EXPORT_JSZIP=true.  In the section of code that does execute, JSZipSync is attached to the browser window object, and nothing more.

So problem 1 is that there really is no module "150" present.  

As an experiment, I tried adding a 'define' line like the one above to the 'else' code path above, which made my application load in the browser.  However, now I am getting an error that says 'TypeError: XLSX.utils.table_to_book is not a function' when attempting to export a file.  So I added a console log on XLSX.utils, and found that while it was defined, it wasn't the utils of SheetJS, but was instead the utils of JSZipSync!

So problem 2 is that even if I modify the code to resolve the module definition, the module that gets assigned is JSZipSync.  This might not really be a problem if 1 is solvable.  I feel that this is a mistake somewhere in my project configuration, not an error in SheetJS.

Can anyone offer any guidance or insight on making this work with Angular 4, or where I've gone wrong?

Thanks,

 - Matt

**Comment by SheetJSDev** [comment]
Can you share a small project that reproduces the issue?

**Comment by mattking4** [comment]
I'm not certain how to make a small project exhibiting just that on the stack we're using... It's extremely modified from 'angular seed advanced' due to angular cli not functioning in our environment, and I'm not certain myself of how to make a skeletonized version of it that will run with only this module in it (I was given the stack by its former developers, but they can't figure our why xlsx won't work in it either).

I did notice today that in our seed.config.ts, 'xlsx' was linked directly to 'node_modules/xlsx/dist/xlsx.full.min.js', while all other modules were resolved to items in their root folders.  I changed this to 'node_modules/xlsx/xlsx.js', and now everything builds and runs correctly (no more missing module "150").  Below are the two references I changed in seed.config:

SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    paths: {
          [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
            --- lots truncated here ---
          'xlsx': 'node_modules/xlsx/xlsx.js'
     },
     packages: {
     }
};

SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    base: this.PROJECT_ROOT,
    packageConfigPaths: [
      join('node_modules', '*', 'package.json'),
      join('node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      [join(this.TMP_DIR, '*')]: `${this.TMP_DIR}/*`,
      '@angular/platform-browser/animations': 'node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js',
      '@angular/animations/browser': 'node_modules/@angular/animations/bundles/animations-browser.umd.js',
      '@angular/common/http': 'node_modules/@angular/common/bundles/common-http.umd.js',
      'tslib': 'node_modules/tslib/tslib.js',
      'rxjs/operators': 'node_modules/rxjs/operators/index.js',
      'dist/tmp/node_modules/*': 'dist/tmp/node_modules/*',
      'node_modules/*': 'node_modules/*',
      '*': 'node_modules/*'
    },
    packages: {
        --- lots truncated here ---
          'xlsx': {
               main: 'xlsx.js',
               defaultExtension: 'js'
           }
     }
};

However, I still get a crash when I try to export a workbook, saying 'jszip is not a constructor'.  This is the area causing the error:

        let wb = XLSX.utils.table_to_book(tables[0]);
        for (let i = 1; i < tables.length; i++) {
            let sheet = XLSX.utils.table_to_sheet(tables[i]);
            XLSX.utils.book_append_sheet(wb, sheet);
        }
        let wbout = XLSX.write(wb, { bookType: format, bookSST: true, type: 'binary' });

I've tried adding the jszip module to our project.json and seed.config, but that makes no difference.  Moving a copy of 'xlsx.full.min.js' from xlsx/dist to xlsx/ still results in the original missing module error.

So there's some difference between xlsx.full.min.js and xlsx.js that causes the former to not link correctly, but something in the one that does link correctly doesn't work with jszip... any ideas on loading the jszip module such that it will work?

**Comment by mattking4** [comment]
Alright, I found a solution!

Unfortunately, it involves modifying 'xlsx.full.min.js'.

Recall that in my first post, my build process was embedding a "150" in an (unreachable) 'define' function.  Yesterday I found that using 'xlsx.js' did not cause the build problem, but introduced other problems.  Well, 'xlsx.js' doesn't contain that 'define' function (nor any jszip code apparently).  So I removed the unreachable 'define' from 'xlsx.full.min.js'.  This is what I removed:

else if("function"==typeof define&&define.amd&&"undefined"==typeof DO_NOT_EXPORT_JSZIP) {
JSZipSync=e();
define([],e);
}

I've removed my project's direct dependency on jszip that I was experimenting with yesterday as well.

Everything is fully functional now on gulp and builds.  

Thoughts on this?  

Any problems with me moving forward with a modified version?

**Comment by SheetJSDev** [comment]
We're preparing a fix as part of a larger change, stay tuned

**Comment by mattking4** [comment]
Thanks!  Looking forward to anything you've got coming, this library has been a lifesaver.

**Comment by crhistianramirez** [comment]
Running into this as well. What's the status of this?

**Comment by sularome** [comment]
+1

**Comment by SheetJSDev** [comment]
A variant of the recommended fix has been added and it appears to work with the [`angular2` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/angular2) -- run `make angular4 && ng serve` to see it live with ng v4.4.7
