### ISSUE TITLE
How do I convert json into multiple sheets in excel file ?

### ISSUE THREAD

**Issue by bismoy2013** [SheetJS/sheetjs#1210]
Things that I'm looking for

- Export a big json structure into multiple sheets within an excel file
- Styling excel headers .
- Ignore any json key/property while exporting it to excel file.

**Comment by m26597** [comment]
Is there any problem if you export a 100M plus json to excel?

**Comment by HenryNovoa** [comment]
Here is a link on using multiple sheets:
https://lovemewithoutall.github.io/it/json-to-excel/

**Comment by bismoy2013** [comment]
@HenryNovoa it's a very old thread but thanks for responding
