### ISSUE TITLE
Buffer is not a constructor

### ISSUE THREAD

**Issue by cipci-s** [SheetJS/sheetjs#1215]
I have updated to angular 6 and node 8.11 and I have the following error:
ERROR Error: Uncaught (in promise): TypeError: Buffer is not a constructor
it is in file cpexcel.js 

    if(!Buffer.allocUnsafe) Buffer.allocUnsafe = function(n) { return new Buffer(n); };

**Comment by SheetJSDev** [comment]
@cipci-s can you share a small project to reproduce this?

**Comment by rasevise** [comment]
Is this situation resolved? I am still getting this issue.

**Comment by AsmaAshfaq219** [comment]
Is there any solution to this?

**Comment by AsmaAshfaq219** [comment]
I just resolved the issue,
The following script was used when I upgraded to 6x in my index.html file
<script>
        var global = global || window;
        var Buffer = Buffer || [];
        var process = process || {
            env: { DEBUG: undefined },
            version: []
        };
    </script>

Comment out 
//var Buffer = Buffer || [];

Works fine for me now

**Comment by ZachRHale** [comment]
@AsmaAshfaq219 Thanks for that!

**Comment by xxyyzz2050** [comment]
when I comment out //var Buffer..., I counter a new error: buffer nod defined
@AsmaAshfaq219

**Comment by SheetJSDev** [comment]
Angular 6 changed behaviors: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 i

@AsmaAshfaq219 's recommendation in https://github.com/SheetJS/sheetjs/issues/1215#issuecomment-447744879 makes sense in light of the underlying change
