### ISSUE TITLE
wrong parsed date on IE11 if string date value has a preceding space

### ISSUE THREAD

**Issue by pluederitz** [SheetJS/sheetjs#1221]
it('XLSX should parse date correctly also if value has a preceding space', function() {
      var wb = X.read(
      	'7,  2018-03-24',
	{cellDates: false, dateNF: 'yyyy-mm-dd', type:'string'}
      );
      var ws = wb.Sheets.Sheet1;
      var d = X.SSF.parse_date_code(ws.B1.v);
      assert(d.d === 24); // fails on IE11: 23
      assert(d.m === 3);
      assert(d.y === 2018);
      assert(ws.B1.w === '2018-03-24'); // fails on IE11: '2018-03-23'
    });

There is a branch with added test that fails on IE11:
branch: https://github.com/pluederitz/js-xlsx/tree/bug-date-parsing-ie11
added test: https://github.com/pluederitz/js-xlsx/blob/bug-date-parsing-ie11/test.js#L384-L399

to check:
> git clone https://github.com/pluederitz/js-xlsx.git
> checkout bug-date-parsing-ie11
> npm install
> make ctestserv
open browser (IE11) on http://127.0.0.1:8000

2nd suite `bug-reports` contains test `XLSX should parse date correctly also if value has a preceding space`

**Comment by SheetJSDev** [comment]
Thanks for doing this!  The test was added to the repo (4f154fd0fdb7cd5b4f31a96359a560ed72b0e544 credited to you) and the tests exposed a deeper date issue.  Closing issue in favor of a related date issue #1565
