### ISSUE TITLE
How to Sort using this library?

### ISSUE THREAD

**Issue by nitingautam** [SheetJS/sheetjs#1228]
Hello,

I am unable to locate in documentation Sort facility, is that available if yes how to use it?

**Comment by Pamasich** [comment]
Depends on what you mean by `sort`. If you mean sort the data, just do that before giving it to the library. If you mean to change the order of the columns, you can pass a `headers` parameter to specify the order if you use json as the data source. If you want to add those sort/filter icons to the document, use the worksheet's `!autosort` attribute with `{ref:[your range here]}`,

**Comment by bean5** [comment]
@nitingautam can we close this?
