### ISSUE TITLE
Application name metadata hardcoded to "SheetJS"

### ISSUE THREAD

**Issue by dpackage** [SheetJS/sheetjs#1231]
Is it possible to update this to allow dynamic control of Application property inside of write_ext_props? e.g. via opts or as an API call during creation of workbook object?

**Comment by SheetJSDev** [comment]
No love for the SheetJS name? 😦

It should be using `.Props.Application`.  Unfortunately that particular property is hardcoded, we'll add an option to override that in the next release.  In the interim, if you are targeting newer browsers or nodejs, you can use ES6 proxy to override the `Application`:

```js
var new_Application = "Microsoft Linux Excel";
var wb_props = wb.Props;
wb.Props = new Proxy(wb_props, {
	get: (o, p) => p == "Application" ? new_Application : o[p]
});
```

http://jsfiddle.net/0173zdkc/

**Comment by dpackage** [comment]
Thanks for the quick response and Proxy tip. Much love for SheetJS.  It's been a big help.

**Comment by SheetJSDev** [comment]
@dpackage if you'd like to contribute, https://github.com/SheetJS/js-xlsx/blob/master/bits/34_extprops.js#L98 is the line.  The original intention was to prevent roundtripping files from writing "Microsoft Excel" or "Microsoft Macintosh Excel".  It probably should explicitly check, something like

```js
if(!cp.Application || cp.Application.match(/Microsoft.*Excel/)) cp.Application = "SheetJS";
```

Feel free to send that as a PR.
