### ISSUE TITLE
Why the export function of js-xlsx ?

### ISSUE THREAD

**Issue by m26597** [SheetJS/sheetjs#1240]
Excuse me, why I didn't realise the export function by the next event :

exportInfo = () => {
    console.log("hello")
    const data = [
        [ "id",    "name", "value" ],
        [    1, "sheetjs",    7262 ],
        [    2, "js-xlsx",    6969 ]
      ];

    const worksheet = XLSX.utils.aoa_to_sheet(data);
    const newworkbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(newworkbook, worksheet, "SheetJS");

    console.log('export export')
  }

**Comment by m26597** [comment]
And after I add the : `XLSX.write(newworkbook, 'export.xlsx');`
the console shows : 
index.js:309482 Uncaught TypeError: Cannot set property 'General' of undefined
    at write_zip (index.js:309482)
    at write_zip_type (index.js:309726)
    at Object.writeSync [as write] (index.js:309828)
    at AnalysisResultTab1._this.exportData (AnalysisResultTab1.js:244)
    at Button._this.handleClick (

**Comment by SheetJSDev** [comment]
You probably meant to call `writeFile`:

```js
XLSX.writeFile(newworkbook, 'export.xlsx');
```
