### ISSUE TITLE
How to add a picture to a excel sheet cell?

### ISSUE THREAD

**Issue by AliceDreaming** [SheetJS/sheetjs#1242]
I have a html page which contains following information. I wan to export it to an excel file. There is an image on the html page, how can I add this image to the exported excel?
        <div class="td" *ngFor="let assetItem of childGroup?.assets">
          <span class="td-img">
            <img [src]="assetItem.icon" alt="">
          </span>
          <span>{{assetItem.brand}}</span>
          <span>{{assetItem.name}}</span>
          <span>{{assetItem.specification}}</span>
          <span>{{assetItem.series}}</span>
          <span>{{assetItem.amount | toFixed: 2}}</span>
          <span>{{assetItem.price | toFixed: 2}}</span>
          <span>{{assetItem.total | toFixed: 2}}</span>
          <span>{{assetItem.comments}}</span>
        </div>

**Comment by jfuenmayor96** [comment]
Did you solve this problem? @AliceDreaming

**Comment by SheetJSDev** [comment]
Image export is supported in our [Pro builds](https://sheetjs.com/pro)
