### ISSUE TITLE
My angular 5 app takes a long time to load for first time users, I need help to speed it up

### ISSUE THREAD

**Issue by Shanthi28Kakarla** [SheetJS/sheetjs#1247]
I am using XLSX and XLSX style to generate the excel file in my angular 5 app. Because of these packages my application size is going to 5 MB.. So its taking long to load. Need the solution.

**Comment by SudeendraG** [comment]
![image](https://user-images.githubusercontent.com/28787271/45116769-6a70d380-b171-11e8-85bc-e064de31b9b0.png)


please look into it . my Application usually loads less than 5 sec, after adding xlsx it was taking 40 seconds to load. any  fix ..??

**Comment by SudeendraG** [comment]
usually my application was loading less than 5 seconds, after adding xlsx package it was taking 40 seconds to load please look into it.

![image](https://user-images.githubusercontent.com/28787271/45117435-2da5dc00-b173-11e8-88b2-eb8d581f5753.png)

**Comment by bean5** [comment]
Did you include the minified or non-minified file to your project? I am not familiar with your packaging mechanism, but switching to the other file might help (example: from minified to non-minified).

**Comment by Tulasireddyv** [comment]
Please include PreloadAllModules in app routing 

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      useHash: true,
      enableTracing: false,
      **preloadingStrategy: PreloadAllModules**
    })
  ],
  exports: [RouterModule]

**Comment by reviewher** [comment]
Angular supports [dynamic imports using ES7 `import()`](https://angular.io/guide/lazy-loading-ngmodules), only pulling in the dependency when needed.

**Comment by SeniorChiefABLEUnit** [comment]
Sounds good
