### ISSUE TITLE
typings/browser/definitions/xlsx/xlsx.d.ts(250,17): error TS2304: Cannot find name 'object'

### ISSUE THREAD

**Issue by WineBewes** [SheetJS/sheetjs#1249]
Hi,
In my workplace, we use npm, jspm and TypeScript to develop in our comprehensive angularjs application. 
After installing xlsx, and adding the types to the file "typings.json", I run the command "npm i", but I got the error "typings/browser/definitions/xlsx/xlsx.d.ts(250,17): error TS2304: Cannot find name 'object'"

Looking at the code in node_modules\xlsx\types\index.d.ts, I see that the Workbook interface has a optional property "Custprops?" at line 247 of type "object".... Apparently, that is not a valid type. After I change it to "Object", the command "npm i" gives no error.

Now, that would not be a great deal if I run my application locally, but in a professional environment, in each stage of deployment, "npm i" is run on each build in each stage. So, in other than local environments, where I cannot change "object" to "Object", this will be a problem.

Can you fix that please ? Or is there any other way to solve this problem ?

Thanks !

Erwin Bauwens
developer
Belgium

**Comment by WineBewes** [comment]
we are using typescript 2.0.6... unfortunately, company policy prohibits me to share the project...

**Comment by WineBewes** [comment]
tried using typescript 2.2.0 and that works fine.... but other dependencies in project work only with 2.0.6...
Is there anything I can do to use the typings of XLSX with this earlier version ?
thanks

**Comment by SheetJSDev** [comment]
We'd accept a PR that changes `object` to `any` for [`Custprops`](https://github.com/SheetJS/sheetjs/blob/master/types/index.d.ts#L256)

**Comment by SheetJSDev** [comment]
Changed the type def and credited 66a9cc79ca18ea5979bdd4287950c40e01d983a0 to you
