### ISSUE TITLE
How to control all rows of a column (including no data) in text format

### ISSUE THREAD

**Issue by bestHandsome** [SheetJS/sheetjs#1254]
i want to set the formate of the row columns( include empty columns)  to '"text";
![image](https://user-images.githubusercontent.com/19648679/45006992-36d96080-b02e-11e8-8cca-1217c75e36e3.png)

**Comment by bean5** [comment]
Is this a snapshot of the demo at http://oss.sheetjs.com ? If so, you may want to file this issue at https://github.com/SheetJS/SheetJS.github.io/.

**Comment by bean5** [comment]
Is this a snapshot of the demo at http://oss.sheetjs.com ? If so, you may want to file this issue at https://github.com/SheetJS/SheetJS.github.io/.

**Comment by SheetJSDev** [comment]
For the existing cells, you can pass the option `ignoreEC` on export to avoid the "number as text" flags.

Setting the number format on cells in a column (that do not exist yet) requires setting a column style.  That is part of our [Pro builds](https://sheetjs.com/pro).  We cannot say when it will make its way here, but we want to finish core data processing for the v1.0.0 release before moving onto styles and other features
