### ISSUE TITLE
export txt file including chinese character encode error

### ISSUE THREAD

**Issue by hanrongliao** [SheetJS/sheetjs#1256]
i hope use this lib to export a txt file
When i use the `XLSX.write`  it return 
```
姓名	年龄	性别
小明	3	男
小红	7	女
```
but when i use `XLSX.writeFile`，i open the download file but error happen:
```
Ó
	t	'+
	3	7
¢	7	s
```
I hope that I have already made the problem clear.

**Comment by reviewher** [comment]
Is this on the server side (nodejs) or browser side?

**Comment by hanrongliao** [comment]
> Is this on the server side (nodejs) or browser side?

browser side

**Comment by SheetJSDev** [comment]
That looks like an encoding error with the program opening the file.  Test https://jsfiddle.net/gajr9nq3/ :

```js
var ws = XLSX.utils.aoa_to_sheet([
  ["姓名",	"年龄",	"性别"],
  ["小明",	    3,	"男"],
  ["小红",	    7,	"女"]
]);
var wb = XLSX.utils.book_new()
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue1256.txt");
```

Result is a tab-delimited file with the UTF8 BOM that Excel correctly processes:

```
00000000: fffe d359 0d54 0900 745e 849f 0900 2760  ...Y.T..t^....'`
00000010: 2b52 0a00 0f5c 0e66 0900 3300 0900 3775  +R...\.f..3...7u
00000020: 0a00 0f5c a27e 0900 3700 0900 7359 0a00  ...\.~..7...sY..
```
