### ISSUE TITLE
Can't read a specific cell value from xlsb file with SheetJS

### ISSUE THREAD

**Issue by AmineBENCHEIKHBRAHIM** [SheetJS/sheetjs#1261]
Hello, 

I am trying to read an .xlsb file with SheetJs and extract some values from certain cells. 

When I want to extract the cell value, I always get "undefined" as a response.

here is my code : 

var url = "test.xlsb";

var oReq = new XMLHttpRequest();
oReq.open("GET", url, true);
oReq.responseType = "arraybuffer";

oReq.onload = function(e) {
  var arraybuffer = oReq.response;

  /* convert data to binary string */
  var data = new Uint8Array(arraybuffer);
  var arr = new Array();
  for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
  var bstr = arr.join("");

  /* Call XLSX */
  var workbook = XLSX.read(bstr, {type:"binary"});

  /* DO SOMETHING WITH workbook HERE */
  var first_sheet_name = workbook.SheetNames[0];
  /* Get worksheet */
  var worksheet = workbook.Sheets[first_sheet_name];
  
var address_of_cell = 'A1';

/* Get worksheet */
var worksheet = workbook.Sheets[first_sheet_name];

/* Find desired cell */
var desired_cell = worksheet[address_of_cell];

/* Get the value */
var desired_value = (desired_cell ? desired_cell.v : undefined);
}

oReq.send();

Any help with that please ? 

Thanks,
Amine

**Comment by SheetJSDev** [comment]
Can you log `workbook` and verify that it is an object?

**Comment by reviewher** [comment]
Some writers were using ["Short" XLSB records](https://oss.sheetjs.com/notes/xlsb_short_records/).  Support was added recently, please try again with the latest version and report back
