### ISSUE TITLE
autofilter problem with Excel 2010

### ISSUE THREAD

**Issue by nitramL** [SheetJS/sheetjs#1262]
Hi,

I'm having trouble when setting the autofilter parameter.
The dropdown filter is present for the columns I specified in the range, but when using a filter (whatever the column) it either makes Excel to crah and close unexpectedly or do the filter as expected but in this case the dropdown filters disappear (for all the columns), so no possibility to filter again.
If I then close the Excel file, I can see a popup saying that something went wrong.
I'm using Excel 2010.

I have the same behaviour with the auto.xlsx output from your fiddle :
http://jsfiddle.net/sheetjs/8drvn0w3/

**Comment by reviewher** [comment]
Can't reproduce in Excel 2010 (screenshot attached).  What version are you using? (it's under File .. Help)
<img width="240" alt="issue1262" src="https://user-images.githubusercontent.com/24845478/45601019-fede0000-b9d3-11e8-9bec-2142c9c0acb9.png">
