### ISSUE TITLE
Trying to consume Date and 'Accounting' formats differently while parsing XLSX to JSON

### ISSUE THREAD

**Issue by satvirgrewal** [SheetJS/sheetjs#1265]
Hi

I have an excel sheet that contains dates in the data formatted as 'mm/dd/yy' and it also has Accounting format applied on few of the fields. Hence, the negative numbers are changed into (*number*) eg. -50 is formatted as (50).

The challenge that I face is, I need to consume the date in the same format as I have to show the same date to user for consistency. But for the (50) i.e. negative numbers, I wanna consume it as -50 and validate if it is a number or not.

If I set **'raw: true'** in 
XLSX.utils.sheet_to_json(worksheet, { raw: true});
The parser reads -50 correctly but it messes up the date because it reads the underlying integer depicting the date.

**cellDates:true** - It helped but then again it reads the date in a timestamp format which I dont need as changing it back to the original format of the date will be a pain. 

The output of the XLSX.read gives me : v=
'Sun Jul 01 2018 00:00:00 GMT-0500 (Central Daylight Time)' , w="7/1/18" for type dates. But when I use the XLSX.utils.sheet_to_json(); the ouput I receive takes the data from v and not from w.

Am I missing anything here? Is there any flag that can be used in the XLSX.utils.sheet_to_json() to have the value of w be set in the JSON that we get.

I tweaked the xlsx.js in the library. I edited the sheet_to_library function and added a if statement telling to consume the 'w' value if the datatype 't' =d.

if(val.t==='d'){
				 v = val.w;
			 }
			 else{
				v = val.v;
			 }

Kindly share your comments if I am missing any existing functionality of the parser or if there is an easier way to achieve the desired goal.

Best
Satvir

**Comment by ev45ive** [comment]
Same problem here. I have date formatted like 'DD-MM-YYYY' in excel. 
When i load it via `xlsx.utils.sheet_to_json`, it gets converted to: 
```
    "date": 42757,
```
I tried both:
```
xlsx.readFile( path, {
    cellNF: true,
    dateNF: "DD-MM-YYYY"
})
```
and it still displays number

This one loads dates as real Date objects into  cell's {v:Date}
```
xlsx.readFile( path, {
    cellDates: true
})
```
but then in JSON instead of formatted value (w,z) i get plain v converted to json

    "date": "2017-01-21T23:00:00.000Z",

Which is too much. It is not using Date.UTC, but local Date. Therefore its shifted for my local timezone.

I have accounting past data. I need only Date, without time and definetly without timezones.

How can i export to json using my formating for numbers and dates?

**Comment by ev45ive** [comment]
```
for (var cell, i = 2; (cell = sheet["B" + i]) && cell; i++) {
    delete cell.w;
    cell.z = "DD-MM-YYYY";
    xlsx.utils.format_cell(cell);
    // Overwrite value with formated one :<
  cell.v = cell.w;
}

**Comment by SheetJSDev** [comment]
#1310 is a similar issue.  The essence of the `sheet_to_json` function is simple enough to implement directly.

We may consider an option to `sheet_to_json` that would allow you to control the value.  If this is of interest, `make_json_row` can be changed as follows:

```diff
	var isempty = true;
+	var use_get_value = !!o.get_value;
	var row/*:any*/ = (header === 1) ? [] : {};

...

		}
-		var v = val.v;
+		var v = use_get_value ? o.get_value(val, hdr[C]) : val.v;
		switch(val.t){

...

			} else {
-				row[hdr[C]] = raw || (o.rawNumbers && val.t == "n") ? v : format_cell(val,v,o);
+				row[hdr[C]] = use_get_value || raw || (o.rawNumbers && val.t == "n") ? v : format_cell(val,v,o);
			}
```

The callback would be specified as the `get_value` option.  With this implementation, the callback would be called with the cell object and the expected header name.

**Comment by Lonli-Lokli** [comment]
I cannot agree with 
`The essence of the sheet_to_json function is simple enough to implement directly.`

I copied all the functiaonlity from this helper and it taks A LOT of other functions. Why there is no any formatting rules for sheet_to_json  helper?

**Comment by reviewher** [comment]
@Lonli-Lokli most of the formatting happens in the parse step.  https://docs.sheetjs.com/#common-spreadsheet-format start from the example there.

As for the original question, pass the options `cellNF: true` to recover the original formats, then just do a loop yourself. The formatted text will be placed in the `w` field.  For example, with a real file in NodeJS:

```js
var wb = XLSX.readFile(path, { cellNF: true, cellText: false });
// var wb = XLSX.read(u8, { cellNF: true, cellText: false, type: "array" }); // for Uint8Array

var ws = wb.Sheets[wb.SheetNames[0]];

var range = XLSX.utils.decode_range(ws["!ref"]);
var aoa_of_data = [];
for(var R = range.s.r; R <= range.e.r; ++R) {
  aoa_of_data[R] = [];
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var cell_address = {c:C, r:R};
    var cell_ref = XLSX.utils.encode_cell(cell_address);
    var cell = ws[cell_ref];
    if(!cell) continue;
    aoa_of_data[R][C] = [cell.v, cell.w || XLSX.utils.format_cell(cell), cell.z]; // value, formatted text, number format
  }
}
```

This thing will give you an array of arrays of triplets `[raw_value, formatted_value, number_format]`
