### ISSUE TITLE
Library is changing date formats (and losing data) in CSVs but not in XLSX files

### ISSUE THREAD

**Issue by bean5** [SheetJS/sheetjs#1277]
See https://github.com/SheetJS/SheetJS.github.io/issues/14 for details. I apologize if I should have filed that here instead!

**Comment by Dave3of5** [comment]
Also seen this myself with datetimes in UK format it somehow moves between USA and UK date format in CSV files only very weird.

**Comment by reviewher** [comment]
Everything currently goes through the `Date` constructor, which is extremely aggressive in Chrome.  You can see this by trying in your console:

```js
new Date("This is not a Date 1") // Mon Jan 01 2001 00:00:00 GMT-0500 (Eastern Standard Time)
```

Grouping into #1300
