### ISSUE TITLE
XLSX.utils.sheet_to_json: Option to ignore hidden rows/columns

### ISSUE THREAD

**Issue by jlouie** [SheetJS/sheetjs#1280]
Is there an option that can be set to ignore hidden rows or cells when using the `XLSX.utils.sheet_to_json` method?

I have an Excel spreadsheet that has hidden rows and calling `XLSX.utils.sheet_to_json` returns all the rows (great!) but it would be equally great to have an option to ignore hidden rows similar to the `display: true` option for `XLSX.utils.table_to_sheet`.

**Comment by leoclipet** [comment]
Any news on that?

**Comment by imir-hoxha** [comment]
any solution for this?

**Comment by reviewher** [comment]
[0270784](https://github.com/SheetJS/sheetjs/commit/02707848ad3fa7713db4d7864cb80f4616d0b360)
