### ISSUE TITLE
Worksheet Style is not working

### ISSUE THREAD

**Issue by sagarikadas91** [SheetJS/sheetjs#1281]
I have added this code for style in worksheet. But it is not working. Kindly help me out.

for (const key in worksheet) {

            if (key[0] === '!') { continue; }
            worksheet[key].s = {
                border: {
                    top: { style: 'thin', color: { auto: 1 } }
                }, font: {
                    sz: 40,
                    color: '#0066ff',
                    bold: true
                }, fill: {
                    bgColor: '#0066ff'
                }, alignment: {
                    wrapText: true
                }
            };
        }

**Comment by happy0088** [comment]
same here . none of the styles are reflecting in the downloaded excel . On cell.v is working and not cell cell.s

**Comment by mim-Armand** [comment]
I think these features are available only on the pro 💵version ( according to #1268 )

**Comment by SheetJSDev** [comment]
Worksheet styling is supported in our [Pro builds](https://sheetjs.com/pro)
