### ISSUE TITLE
Translate this document into Chinese

### ISSUE THREAD

**Issue by rockboom** [SheetJS/sheetjs#1284]
Hello, I want to translate this  document into Chinese. And this is my github [https://github.com/ROCKBOOM/SheetJS-docs-zh-CN](https://github.com/ROCKBOOM/SheetJS-docs-zh-CN). It's not finish yet, just parts of this document. But I need to get your consent before I can continue this. If you disagree, I will delete this repository. Thank you so much!

**Comment by SheetJSDev** [comment]
I don't personally understand the Chinese, but this is awesome!  Let us know if anything doesn't make sense or if you need any assistance.

**Comment by rockboom** [comment]
@SheetJSDev Hi, I've finished this job to translate doc into Chinese, and this is Simplified Chinese repo [https://github.com/rockboom/SheetJS-docs-zh-CN](https://github.com/rockboom/SheetJS-docs-zh-CN). Maybe you can post this repo in doc, let more people know powerful Sheetjs and use it .

**Comment by SheetJSDev** [comment]
This is beyond amazing @rockboom !  We can probably add a line at the top of the readme.  How should it look?

Also, please send an email to hello@sheetjs.com for some other stuff

**Comment by rockboom** [comment]
@SheetJSDev Wonderful! You can add a line at the top of the readme.

**Comment by birdycn** [comment]
厉害，致敬！

**Comment by reviewher** [comment]
Linked in the README
