### ISSUE TITLE
Efficient way to read metadata in big files?

### ISSUE THREAD

**Issue by arkhyu** [SheetJS/sheetjs#1288]
Hello,
 I am trying to use  js-xlsx to extract some information about n excel ile, concretely the number and name of existing sheets in a workbook.

This code works fine for small excels, but I noticed that with big files of more than 100.000 rows it can take more than a half a minute to get the results:

`const wb: XLSX.WorkBook = XLSX.read(bstr, {type: 'binary'});

        let numberOfSheets: number = wb.SheetNames.length;
        
        for ( let i = 0; i < numberOfSheets; i++)
        {
          const wsname: string = wb.SheetNames[i];

          console.log(`Sheet name: ${wsname}`);
        }`
I guess this happens because the read _XLSX.read_ instruction parses the whole excel file extracting information about its sheets columns, and also the content of those columns.

Given that I only need the names of the style sheets, there is a way to query the excel only for the metadata instead of parsing the whole file? Query only about the data structure and not the content of the file ?

Thanks.

**Comment by reviewher** [comment]
If you just need the name of worksheets, pass the option `bookSheets: true`.  If you just need the first row, pass the option `sheetRows: 1`
