### ISSUE TITLE
Help changing date format options (dateNF) with sheet_to_csv?

### ISSUE THREAD

**Issue by BrennonTWilliams** [SheetJS/sheetjs#1292]
I'm using XLSX.utils.sheet_to_csv() to turn an Excel file into a csv. Since the default dateNF value is 14 mm/dd/yy, I need to change it to 22, or mm/dd/yy hh:mm, as the docs state.

I've tried this a few ways, like:
`XLSX.utils.sheet_to_csv(worksheet, { dateNF: 'm/d/yy h:mm'});`
`XLSX.utils.sheet_to_csv(worksheet, { dateNF: 'FMT 22'});`
`XLSX.utils.sheet_to_csv(worksheet, { dateNF: '22'});`
`XLSX.utils.sheet_to_csv(worksheet, { dateNF: 22});`

None seem to do the trick, it stays in #14 format. What am I doing wrong?

**Comment by funduck** [comment]
check this https://github.com/SheetJS/js-xlsx/issues/718

**Comment by SheetJSDev** [comment]
When reading the workbook or worksheet, pass the option `cellDates: true`.  Without that, the raw numbers are passed and `dateNF` will not apply

**Comment by TechBoyy6** [comment]
@SheetJSDev sir, I am getting the data using ms officejs add-in api. then i perform 
`.aoa_to_sheet(excelData, { cellDates: true });`
`.sheet_to_csv(ws, { dateNF: "YYYY" - "MM" - "DD" });`

👆 doesnt work.

My question is, since i am not reading can i convert the dates using the XLSX package?
