### ISSUE TITLE
Issue when I use table_to_sheet. I have: ERROR Error: Bad range (0): A1:A0

### ISSUE THREAD

**Issue by NicoleObando** [SheetJS/sheetjs#1294]
I'm using angular 6 and I'm trying to export my <mat-table> to excel but when the code try to write the file my app present this error:  ERROR Error: Bad range (0): A1:A0
I'm using this line:
const ws: XLSX.WorkSheet=XLSX.utils.table_to_sheet(this.table.nativeElement);
But if I send a simple json with XLSX.utils.json_to_sheet my app works great. The trouble if that my JSON contains crude data.

**Comment by geo-dev-cr** [comment]
I had exactly the same issue, follow the next steps, maybe could work.

1. Pay attention to div table wrapper, MUST to be:
   `<div #TABLE> <mat-table>....</mat-table></div>`
2. Then change 
   `<mat-header-row *matHeaderRowDef ......>...</mat-header-row> <!-- TO --> `
   `<tr mat-header-row *matHeaderRowDef...>...</tr>`
2.1 Then change the next row def 
   `<mat-row *matRowDef...></mat-row> <!-- TO -->`
   `<tr mat-row *matRowDef..></tr>`

PD: If you lost some styles add this:
` tr.mat-header-row, tr.mat-row {`
    `   display: flex;`
`}`

Hope this can help you.

**Comment by SheetJSDev** [comment]
@NicoleObando @geo-dev-cr can you share an example table triggering this issue?

**Comment by lsuchocki** [comment]
Another:
https://stackoverflow.com/questions/50970632/how-to-export-excel-file-from-angular-material-5-mat-table-angular-material-tab/51157054

Changing from "mat-header-row" to "tr mat-header-row" breaks styles and formatting for me, even when the "display: flex" lines are added to the stylesheet.

**Comment by CPRmichel** [comment]
For me it worked without changing the `<mat-table` to `<table mat-table`. My styling was the same after that using Angular 7.

**Comment by patilNik** [comment]
It works for me but can anyone tell how to hide one of the columns to export.
In my table, there is also an edit button with this method edit section also added to an excel sheet.
Please Suggest.

**Comment by geo-dev-cr** [comment]
Hi devs, I have found the solution by using the native angular components. 

HTML
`<mat-table #TABLE></mat-table>`;

TS
`@ViewChild('TABLE') table: any;`

download()
`this.table._elementRef.nativeElement`

It is just the way to initialize our viewChild from ElementRef to any our DOM reference and then access the native element. 

Based on: https://github.com/angular/material2/issues/3922#issuecomment-292137996 

Hope it helps!

**Comment by NishantMadkikar** [comment]
I'm using angular 5 and I'm trying to export my to excel but when the code try to write the file my app present this Error: Uncaught (in promise): Error: Bad range (0): A1:c4
 i am using this line:=
 XLSX.utils.book_append_sheet(wb, ws, ws_name);
      XLSX.writeFile(wb, rajan+ '.xlsx');

**Comment by bsarkadi** [comment]
Is there a way to make xslx able to interpret the Angular 5+ format (mat-table)?
Reverting to the old HTML table creates a lot of styling issues.

**Comment by reviewher** [comment]
A) use the same underlying data source and lift to a worksheet using `json_to_sheet`

B) use `nativeElement` to extract the table DOM element and lift to a worksheet using `table_to_sheet`
