### ISSUE TITLE
Large File - Browser Crash due to out of memory exception 

### ISSUE THREAD

**Issue by HusseinElsayed** [SheetJS/sheetjs#1295]
I'm using the component in production environment and we received complains from customers trying to process large files ... 

- 45.5 MB Size 
- 300,000 Rows
- 22 Columns

in order to isolate the problem from my code , I tried processing the same file in your Demo page http://oss.sheetjs.com/ ... The browser crashed due to an out of memory exception

**Comment by eason123deng** [comment]
In my case, it didn't crash the browser, but the live demo returned an empty JSON object when I fed an excel file of 140MB

**Comment by adminphdcommy** [comment]
I having the same issue. 

Crashed at 10 column file, but survive in 5 column file.

Rows: 500k+ (target was 1mil)
Column: 10
File size in xlsx: 250MB
File size in CSV with compression: 15MB

Is this subject to user PC spec?

**Comment by Noitidart** [comment]
Anyone resolved this issue?

**Comment by reviewher** [comment]
There are many discussions on the topic of reading large files.  Closing in favor of #61  . Please follow the discussion there
