### ISSUE TITLE
Can not export the other cells of the table because of pagination

### ISSUE THREAD

**Issue by ReemAlmuhimeed** [SheetJS/sheetjs#1298]
when I export my html table to an excel sheet using "table_to_book" it only returns the first part of the table which is in the first page. any idea of how I can get all table rows that are paginated ?

**Comment by Mansteinr** [comment]
I also encountered this problem, I do not know how to deal with it.

**Comment by selvait90** [comment]
I have faced the same issue.

**Comment by gamerboy** [comment]
Hi.
You can use the **json_to_sheet** function instead of **table_to_book**.

```javaScript
const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(this.dataSource.data);
const wb: XLSX.WorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
const filename = 'Report_' + moment().format('YYYYMMDD-HHmmss') + '.xlsx';
XLSX.writeFile(wb, filename);
```

It will export the full dataset, not only the first page.

**Comment by CenkCamkiran** [comment]
> Hi.
> You can use the **json_to_sheet** function instead of **table_to_book**.
> 
> ```js
> const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(this.dataSource.data);
> const wb: XLSX.WorkBook = XLSX.utils.book_new();
> XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
> const filename = 'Report_' + moment().format('YYYYMMDD-HHmmss') + '.xlsx';
> XLSX.writeFile(wb, filename);
> ```
> 
> It will export the full dataset, not only the first page.

Thank you for sample code

**Comment by reviewher** [comment]
Most table pagination libraries make most of the data inaccessible through normal means.  As @gamerboy pointed out, converting the underlying raw data source is the best option

**Comment by JosephKithome** [comment]
You saved my career.Thanks!!
