### ISSUE TITLE
Border Color

### ISSUE THREAD

**Issue by varunsree** [SheetJS/sheetjs#1306]
Is any way to change the border color. 
     const borderRight = { right: { style: 'thin', color: { auto: 1 } } }
The above case the output looks  like black border on the right side (cell). I want to change and place different border colour for each cells. Is it possible to change border colour?

**Comment by happy0088** [comment]
HI , are you able to apply any other kind of styles to the cell like bold , or color? If yes , what is the node module you are using and the node version?

**Comment by mim-Armand** [comment]
@happy0088 I think these features are available only on the pro 💵version ( according to #1268 )

**Comment by oniej** [comment]
https://stackoverflow.com/questions/50110595/how-to-add-cell-border-to-sheetjs-xlsx-generated-file

**Comment by SheetJSDev** [comment]
Cell Styling, including border styles, are a feature of our [Pro builds](https://sheetjs.com/pro)
