### ISSUE TITLE
cannot get formatted date while still using raw values of other data types

### ISSUE THREAD

**Issue by wahleede** [SheetJS/sheetjs#1310]
Hey, I`m currently working on a project that requires me to parse through an excel file and collect the information stored within to do other stuff with it. 

After using cell dates and formatting the date to mm/dd/yyyy format, I'm forced to use the non-raw values of other columns that are being parsed that aren't dates. For example, one column is storing account numbers (e.g 61395015190). Because it is no longer getting the raw value, that account number is showing up as 6.13595E7, in scientific notation. Is there a way in which I can use this formatted date without having to compromise on the other values? 

Edit: expanding on this, the complete number is stored in the .v field while the formatted date in the .w field. Is it possible for me to use the .w field for dates and .v field for everything else when using the sheet_to_json command?

**Comment by SheetJSDev** [comment]
For the greatest flexibility, you can walk the worksheet directly.  `sheet_to_json` does a pretty straightforward row-major-order walk of the worksheet.  The loop structure would be:

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
var headers = [], addr = "", out = [];
// create header array
for(var C = range.s.c; C <= range.e.c; ++C) {
  addr = XLSX.utils.encode_cell({r:range.s.r, c:C});
  if(!ws[addr]) headers.push("Column " + (C - range.s.c + 1));
  else headers.push(ws[addr].w || ws[addr].v || "Column " + (C - range.s.c + 1));
}
// process data
for(var R = range.s.r; R <= range.e.r; ++R) {
  var row = {};
  for(var C = range.s.c + 1; C <= range.e.c; ++C) {
    var addr = XLSX.utils.encode_cell({r:R, c:C});
    if(!ws[addr]) continue; // skip non-existent cells
    row[headers[C - range.s.c]] = ws[addr].t == "d" ? ws[addr].v : ws[addr].w; // put your logic here
  }
  out.push(row);
}
```
