### ISSUE TITLE
cell style is not working in XLSX module

### ISSUE THREAD

**Issue by happy0088** [SheetJS/sheetjs#1313]
Hi am trying to export my data(json) into an excel sheet using XLSX  , only value is getting set using cell.v but styles are not getting set using cell.s . Below is the code snippet .

Node version - v8.11.1
NPM version - 5.6.0

const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
  const workbook: XLSX.WorkBook = { Sheets: { 'Report': worksheet }, SheetNames: 'REPORT' };
  
worksheet['A1'].v='test value';
worksheet['A1'].s = {fill:{fgColor: {rgb:"86BC25"}}};
const data: Blob = new Blob([buffer], {type: EXCEL_TYPE});
   FileSaver.saveAs(data, fileName  + new  Date().getTime() + EXCEL_EXTENSION);

Kindly let me know if anything is missing here .

Also, i tried replacing XLSX with XLSX-populate , but it says xlsx-populate not found .

**Comment by qi521123456** [comment]
me too

**Comment by Froschkoenig84** [comment]
But this fork doesn't support the...
`var ws = XLSX.utils.aoa_to_sheet(ws_data);`
so it's nice and easier to create an array-scheme like this...
![array-scheme](https://user-images.githubusercontent.com/49907406/56578643-6abdc200-65ce-11e9-8d3d-cb0b3250fafd.jpg)

**Comment by Aijunwei** [comment]
me too

**Comment by TimVN** [comment]
For anyone wondering in the future. Styling cells is a pro feature of SheetJS.

**Comment by SheetJSDev** [comment]
Cell styling is something we offer in our [Pro builds](https://sheetjs.com/pro) and may offer in the open source at some point.

**Comment by PoolFlamingo** [comment]
Free styles on XLSX: [xlsx-js-style](https://github.com/gitbrent/xlsx-js-style)
