### ISSUE TITLE
Read a xlsx file protected with password

### ISSUE THREAD

**Issue by mmurillo96** [SheetJS/sheetjs#1314]
Hello,
I try this:
var workbook = XLSX.read(e.target.result, {type : 'binary', password:'xxxxxx', WTF: true});
And receive this:
'Encryption scheme unsupported'

is this feature already implemented?
I wish i could be able to read a XLSX file protected by password!
If there is something that could be done to solve this please let me know.

To be more expecific there is a XLSX file that i neet to read, inside this file i have more then one sheet the point is the sheet that i whant to read is no protected is there any whay to ignore the others sheet? I think this way o could avoid the protect password

thks

_Originally posted by @mmurillo96 in https://github.com/SheetJS/js-xlsx/issues/774#issuecomment-431085445_

**Comment by wahleede** [comment]
You can't read a password protected file at this time

**Comment by nakshay** [comment]
Is this feature added now?

**Comment by hdwatts** [comment]
Would appreciate an update on this issue if one can be provided

**Comment by nakshay** [comment]
@hdwatts , I think you can directly read password protected sheets without any extra configuration.
at least I am able to do it.

**Comment by ghf1990525** [comment]
@nakshay 
Can you tell me how to achieve it?
thks

**Comment by nakshay** [comment]
> @nakshay
> Can you tell me how to achieve it?
> thks

```
var xlsx= require('xlsx');
const serialNumber= Number(xlsx.utils.sheet_to_csv('SheetName'));
```

Above code is not stopping me to read serial number from protected sheet, although I have protected this sheet from  java code and not accessible from workbook.

Below is code snippet of java code.
```
sheetObj.protectSheet("password");
cellObj.setCellStyle(lockedCellStyle);
workbook.setSheetVisibility(workbook.getSheetIndex("SheetName"),SheetVisibility.VERY_HIDDEN);
```

**Comment by SheetJSDev** [comment]
XLSX encryption is supported in our [Pro Crypto component](https://sheetjs.com/pro) -- we don't know when or if it will be made available in our open source build
