### ISSUE TITLE
Partial import of functions

### ISSUE THREAD

**Issue by emprove** [SheetJS/sheetjs#1315]
import XLSX from 'xlsx'
this adds ALL of the package functions. About 200-300kb gzipped. I only need json_to_sheet and writeFile. Is it possible?

**Comment by GreggOD** [comment]
I second this. I'm going to jump on this and say I also need a way to access an error and success callback.

I'm no pro at modules and requires but I see something to this effect. All in one package to avoid installing a million packages. But functionality separately importable.
```
// XLSX is core functionality - like reading the file
let XLSX = require('xlsx/core');
// then bind the functionality you want
XLSX.to_json = require('xlsx/sheet_to_json');

// also error and success functionality like
XLSX.error(function(error){
// handle error here
})
```

then for my component I can do something like:
```
<uploader @error="handleError()" @success="rowsToTable()" />
```

**Comment by MackYoel** [comment]
This should be in documentation, I think.

**Comment by VictorSholomickiy** [comment]
Hi, I have the same issue and in the documentation, I can find any information about how to stop importing all file and start to use just part of it. Any ideas?

**Comment by reviewher** [comment]
The modern approach is ES Modules with bundler tree shaking.  @SheetJSDev [pushed something](https://github.com/SheetJS/sheetjs/blob/master/xlsx.mjs) and it should be ready whenever the next version is released
