### ISSUE TITLE
Stub cells do not include a style when they should

### ISSUE THREAD

**Issue by xprnio** [SheetJS/sheetjs#1316]
I have an Excel spreadsheet with cells that all have a background fill. Some of those cells have text, some are empty.
When reading the file with styles and stubs enabled, the cells that are empty (stub type cells) do not contain styling information, even though in Numbers (macOS equivalent of Excel) they are filled. 

Code for reading the file:
```typescript
const workbook: xlsx.WorkBook = xlsx.readFile("/path/to/spreadsheet.xlsx", {
    cellStyles: true,
    sheetStubs: true,
});
const sheet: xlsx.Sheet = workbook.Sheets[workbook.SheetNames[0]];

Object.keys(sheet)
    .filter((key: string) => !key.startsWith('!'))
    .map((key: string) => sheet[key])
    .filter((cell: xlsx.CellObject) => cell.t === 'z')
    .forEach((cell: xlsx.CellObject) => console.log(cell));
```

All the objects that snipped logs are exactly the same, regardless of whether the cell has a background fill or not:
```javascript
{t: 'z'}
```
Whereas for other cells it includes them:
```javascript
{ 
  t: 's',
  v: 'Text',
  r: '<t>Text</t>',
  h: 'Text',
  w: 'Text',
  s: { 
    patternType: 'solid',
    fgColor: { rgb: 'CCCCCC' },
    bgColor: { rgb: 'CCCCCC' }
  }
}
```

I saw [a similar issue](https://github.com/SheetJS/js-xlsx/issues/524), so I am aware that the Pro version (presumably) handles this correctly (or at least better).
My issue is that, seeing as basic style parsing is supported in the Open Source version already (`fgColor` and `bgColor`), it doesn't seem to make much sense (for me at least) that js-xlsx only parses the background fill for cells which are not empty. Intuitively I'd assume that if it supports background fill parsing, that it wouldn't leave some cells out.
Is this intended, or is it just a bug?

**Comment by xprnio** [comment]
I found the [PR that implemented the existing functionality](https://github.com/SheetJS/js-xlsx/pull/66), but I didn't notice any column type checks or anything there, which leads me to assume that there's some intermediary process that either filters out the stub cells and then parses the fills, or that the stubs are generated after everything else is parsed.

**Comment by SheetJSDev** [comment]
6c0ada179027f58db2b5c5f0aa6f3ecaef7224aa
