### ISSUE TITLE
Get digital signature

### ISSUE THREAD

**Issue by rsoladana** [SheetJS/sheetjs#1323]
Hello everyone, I'm trying to get the digital signature on a sign excel file (xlsm extension), I had review all the object returned but I can't find it, Anyone know how can I approach this?

Thanks in advance

**Comment by SheetJSDev** [comment]
Digital signatures are not currently supported.  They are supported in some of our [Pro builds](https://sheetjs.com/pro) and may eventually make their way to the open source, but it will definitely be after v1.0.0
