### ISSUE TITLE
How to edit an excel file?

### ISSUE THREAD

**Issue by Vishal1419** [SheetJS/sheetjs#1328]
I am reading data from dbf file and trying to save it in an existing templated excel file.

Here is my code:

```
const XLSX = require('xlsx');

const add_cell_to_sheet = (worksheet, address, value) => {
	/* cell object */
    const cell = {t:'?', v:value};

    /* assign type */
    if(typeof value == "string") cell.t = 's'; // string
    else if(typeof value == "number") cell.t = 'n'; // number
    else if(value === true || value === false) cell.t = 'b'; // boolean
    else if(value instanceof Date) cell.t = 'd';
    else if(value === null) cell.t = 'z';
    else throw new Error("cannot store value");

    /* add to worksheet, overwriting a cell if it exists */
    worksheet[address] = cell;

    /* find the cell range */
    const range = XLSX.utils.decode_range(worksheet['!ref']);
    const addr = XLSX.utils.decode_cell(address);

    /* extend the range to include the new cell */
    if(range.s.c > addr.c) range.s.c = addr.c;
    if(range.s.r > addr.r) range.s.r = addr.r;
    if(range.e.c < addr.c) range.e.c = addr.c;
    if(range.e.r < addr.r) range.e.r = addr.r;

    /* update range */
    worksheet['!ref'] = XLSX.utils.encode_range(range);
}

const workbook = XLSX.readFile('D:/test.xlsx');
worksheet = workbook.Sheets['b2b'];

add_cell_to_sheet(worksheet, 'A5', 'hello1');
add_cell_to_sheet(worksheet, 'B5', 'hello2');
add_cell_to_sheet(worksheet, 'A6', 'hello3');
add_cell_to_sheet(worksheet, 'B6', 'hello4');
add_cell_to_sheet(worksheet, 'A7', 'hello5');
add_cell_to_sheet(worksheet, 'B7', 'hello6');

XLSX.write(workbook);
```

When this code executes, I get an error on last line:

![error](https://user-images.githubusercontent.com/19953475/47619572-7015d600-da9d-11e8-805f-b1d4ce7cf29f.jpg)

**Comment by Vishal1419** [comment]
@dandv why downvote?  If you know the answer then post it here.

**Comment by norisurgit** [comment]
I would suggest this workaround:

const XLSX = require("xlsx")

const pathToExcelFile = `path/to/file.xlsx` // path to excel file

let workbook = XLSX.readFile(pathToExcelFile) // reads original file
let SheetName = workbook.SheetNames[0] //get first sheet in file

console.log(workbook.Sheets[SheetName]['A1'].v) // outputs : Old Value

let newWorkBook = workbook // create new workbook
newWorkBook.Sheets[SheetName]['A1'].v = "New Value" // assign new value
newWorkBook.Sheets[SheetName]['B1'].v = "Also New Value" // assign new value
// ....

XLSX.writeFile(newWorkBook,pathToExcelFile) // write the same file with new values
console.log(newWorkBook.Sheets[SheetName]['A1'].v) // outputs :  New Value
console.log(newWorkBook.Sheets[SheetName]['B1'].v) // outputs : Also New Value

**Comment by SheetJSDev** [comment]
`XLSX.write` needs to know what you want to generate.  You need to pass an options object that, at minimum, includes:

- `bookType` identifying the type of file you want to generate.  If you want an XLSX file, set `bookType` to `"xlsx"`
- `type` indicating the output type.  For example, `"binary"` generates binary strings while `"array"` generates an array of unsigned bytes
