### ISSUE TITLE
XLSX.utils.table_to_book Can't parse Currency

### ISSUE THREAD

**Issue by uastephen45** [SheetJS/sheetjs#1334]
I am doing XLSX.utils.table_to_book(document.getElementById(table), { sheet: "Sheet JS", raw: false }); however, one of my columns contains USD but is being read as General type. How can we keep it as currency?

**Comment by SheetJSDev** [comment]
`raw: false` always returns strings.  Even if you set `raw: true` there's no attempt to process currencies.  If you have control over the source table, we can add a backdoor to pass through the raw value / number format as attributes of the TD element

**Comment by reviewher** [comment]
The alluded backdoor is `data-t="n" data-z="$0.00" data-v="1234.56"` where `data-v` is the actual value
