### ISSUE TITLE
Date parsing problem, bug with time when exporting xls

### ISSUE THREAD

**Issue by Ant248** [SheetJS/sheetjs#1335]
Ok this is nothing major but bizarre none the less.

I am sending dates in the format of "d-mmm-yy" everything works great except some cells also contain a time:
![bug](https://user-images.githubusercontent.com/23380077/47802838-145f7d00-dd29-11e8-9eba-d4602ada691b.jpg)

I've tried setting a time with your method "d-mmm-yy hh:mm" however those cells that have added time seem to have the time i set minus one hour.

Is there any way to force it to ignore time? or round down the excel date number?

Many thanks

**Comment by SheetJSDev** [comment]
You can set the number format of cells using the `.z` property of the cell object:

```js
ws["A4"].z = "d-mmm-yy";
```

What are you starting from (data object, existing file) and what are you generating (XLSX, CSV, ...)?

**Comment by Ant248** [comment]
Thanks for your speedy reply.
I am feeding it an array of objects using the json_to_sheet, then looping thru the keys to set the correct reformatting as follows:

function downloadXLS(arg, name){
/* make the worksheet */
var ws = XLSX.utils.json_to_sheet(arg);
/* add to workbook */
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Snapshot",{bookType:'xlsx', type:'binary', cellDates: true});
for (key in wb.Sheets["Snapshot"]){
  var a = wb.Sheets["Snapshot"];
  var n = key.replace(/\D/g,'');
  var x = key.replace(/[0-9]/g, '');
  if (key === "!ref"){
    wb.Sheets["Snapshot"][key] = "A1:H182";
  } else if (n !== "1"){
    if (x === "A"){
      var o = a[key];
      var v = o.v;
      var newO = {"t": "d", "v": v, "z": "d-mmm-yy"};
      console.log(newO);
      wb.Sheets["Snapshot"][key] = newO;
    } else{
      var o = a[key];
      var v = o.v;
      var newO = {"t": "n", "v": v*1, "z": "0.00"};
      wb.Sheets["Snapshot"][key] = newO;
    }
  }
}
var fileName = name + '.xls';
/* generate an XLSX file */
XLSX.writeFile(wb, fileName);
}

This will give me still give occasional time stamp in some cells when i try set a time the cells that are effected seems to have the time i set minus 1 hour ;S

**Comment by reviewher** [comment]
Cells will show a time in the top bar when it is not midnight of the time.  As the underlying date mechanics changed since this issue was raised, please test against the latest version and report back
