### ISSUE TITLE
cell.s is not working

### ISSUE THREAD

**Issue by akuze1985** [SheetJS/sheetjs#1342]
@SheetJSDev I should use cell.s to set cell style, but found it not working, so i don't known how to solve this problem. can you give me a suggestion. thanks

**Comment by bhavinshiroya1994** [comment]
@Hangoro-Yang 

i found same issue

**Comment by HaoPengZheng** [comment]
also

**Comment by SheetJSDev** [comment]
For supported styling features, you have to pass the option `cellStyles: true` on write.

More general styling is available in our [Pro builds](https://sheetjs.com/pro)
