### ISSUE TITLE
cell.s not present when cell has no content

### ISSUE THREAD

**Issue by jeffsenn** [SheetJS/sheetjs#1344]
If a cell is formatted, but otherwise empty, the cell will not exist in the parsed sheet and therefore it does not have an inspectable 'cell.s'  For example, this is crucial for parsing sheets that have formatting (e.g. background color) that indicate required cells to fill out in a form.

Please tell me there is some feature I'm missing to correct this problem.

**Comment by SheetJSDev** [comment]
6c0ada179027f58db2b5c5f0aa6f3ecaef7224aa
