### ISSUE TITLE
Formatting time-only cells

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/sheetjs#1345]
My users shoulud be able to upload excel sheets that contain columns with time values.
So e.g. 06:43:15, with the format hh:mm:ss
However, when I upload the sheet, my time cells are from the type "number" and the value gets set as "456178923". (when I check row.v)
When the upload is done, the cells value is "19000100". Really don'T know whats going on there.
How can I check if it's a time-value so that I can reformat it before uploading?

**Comment by sonjadeissenboeck** [comment]
Is there nobody that can help?

**Comment by maxdeepfield** [comment]
any update on this?

**Comment by SheetJSDev** [comment]
Pass the option `cellNF: true` or read the formatted string.  Without `cellNF`, the `v` property will be populated with the raw timestamp which may include a day component (the value can represent `2021-09-17 06:43:15`).  With `cellNF: true`, the fact that the cell format is "hh:mm:ss" will be preserved and downstream functions will properly apply formats

https://github.com/SheetJS/sheetjs/issues/1381 is a related issue from ODS which illustrates the same general problem
