### ISSUE TITLE
I export excel  with comment , excel comment window  always open!

### ISSUE THREAD

**Issue by luzhiy123** [SheetJS/sheetjs#1350]
Hi, we are using xlsx@v0.14.0.
You say xlsx@v0.13.0 fixed it.
It's still there between 0.13.0 and 0.14.0

**Comment by dylan-shao** [comment]
same issue here, 0.14.0, the excel comment always open:
![image](https://user-images.githubusercontent.com/12180221/98922360-52452d80-250d-11eb-8472-7b0a03393680.png)

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs#cell-comments

To mark a comment as normally hidden, set the `hidden` property:

```js
if(!ws.A1.c) ws.A1.c = [];
ws.A1.c.push({a:"SheetJS", t:"This comment is visible"});

if(!ws.A2.c) ws.A2.c = [];
ws.A2.c.hidden = true;
ws.A2.c.push({a:"SheetJS", t:"This comment will be hidden"});
```
