### ISSUE TITLE
How set left column fixed ?

### ISSUE THREAD

**Issue by ericklodion** [SheetJS/sheetjs#1351]
**My code:**

`var data = [
       ['01/02/2018', 2, 3],
       ['02/02/2018', 2, 3],
       ['03/02/2018', 2, 3]
];

var wb = XLSX.utils.book_new();
var ws = XLSX.utils.aoa_to_sheet(data, { cellDates: true });
XLSX.utils.book_append_sheet(wb, ws, ws_name);
`

**How set left column fixed ?** Ty

**Comment by yejing2017** [comment]
+1

**Comment by reviewher** [comment]
`aoa_to_sheet` won't try to parse strings as dates.  You have to convert them manually:

```js
var ws = XLSX.utils.aoa_to_sheet(data.map(r => [new Date(r[0])].concat(r.slice(1))), { cellDates: true });
```

**Comment by awaism551** [comment]
> `aoa_to_sheet` won't try to parse strings as dates. You have to convert them manually:
> 
> ```js
> var ws = XLSX.utils.aoa_to_sheet(data.map(r => [new Date(r[0])].concat(r.slice(1))), { cellDates: true });
> ```

@reviewher This doesn't work, question was to set left column fixed while others will scroll which this code doesn't do
