### ISSUE TITLE
how to use v or w in sheet_to_json

### ISSUE THREAD

**Issue by Zhou-Bill** [SheetJS/sheetjs#1352]

**Comment by skobak** [comment]
Seems like you can't, because sheet_to_json turn Sheet cell object with .h .c params to plain value in JSON

**Comment by SheetJSDev** [comment]
By default, `sheet_to_json` uses the raw `v` values in cell objects.  With the option `false`, the formatted text `w` property is used.  These are simple objects, so you can make your own logic by simply walking the worksheet.  https://github.com/SheetJS/sheetjs/blob/master/bits/90_utils.js#L45 is the actual code.
