### ISSUE TITLE
How to use this library in google appscript and convert 2d array to xlsx?

### ISSUE THREAD

**Issue by srv6100** [SheetJS/sheetjs#1355]
Hi,
I am trying to generate xlsx sheet using google appscript using sheetjs. could you please teel me a proper way to use this?
as whenever i am using xlsx.full.min throwing JSZIPSYNC error 
![appscript2](https://user-images.githubusercontent.com/45064500/48544478-ababff00-e8e9-11e8-9a82-32f8edaff933.PNG)

and when i am using xlsx.min it is showing error like: 
![appscript](https://user-images.githubusercontent.com/45064500/48544525-c3838300-e8e9-11e8-9079-1a35e28840c5.PNG)

spreadsheet is not an option to me as it has cell limitation. Only xlsx is what i need

**Comment by SheetJSDev** [comment]
The outer structure of the library was changed such that the `xlsx.full.min.js` script should "just work".  https://tanaikech.github.io/2020/10/12/retrieving-all-values-from-all-sheets-from-url-of-2pacx-of-web-published-google-spreadsheet-using-google-apps-script-and-javascript/ is an example which appears to use the standalone script directly
