### ISSUE TITLE
Unnecessary format in styles.xml

### ISSUE THREAD

**Issue by ivanfryda** [SheetJS/sheetjs#1357]
In the styles.xml file of the Excel file there is the following element:

`<numFmt numFmtId="56" formatCode="&quot;上午/下午 &quot;hh&quot;時&quot;mm&quot;分&quot;ss&quot;秒 &quot;"/>`

This appears always as default, without me ever specifying any special formatting. Why is so?

**Comment by SheetJSDev** [comment]
Originally it was to work around a specific quirk in Excel (there are default formats not properly specified in the official documentation), but it currently exists to ensure a `numFmts` block is actually written.
