### ISSUE TITLE
Cell format not working after applying styles

### ISSUE THREAD

**Issue by DineshThangella** [SheetJS/sheetjs#1359]
I have to export an excel sheet through my angular app. So I am using js-xlsx and xlsx-style modules. I would like to format the cells as I required but am not able to. 
I have the sample in stackblitz [https://stackblitz.com/edit/angular-xukeq2](Sample)

Some one provide me the solution. Thanks

**Comment by bhavinshiroya1994** [comment]
@DineshThangella 

any update style issue ?
 i found same issue.

**Comment by SheetJSDev** [comment]
Styling is a feature of our [Pro builds](https://sheetjs.com/pro)
