### ISSUE TITLE
sheet_add_json with origin: -1 leaves gap from bottom of worksheet

### ISSUE THREAD

**Issue by dandv** [SheetJS/sheetjs#1364]
I'm seeing strange behavior with the following code:

```js
const XLSX = require('xlsx');

const wb = XLSX.utils.book_new();

const ws = XLSX.utils.json_to_sheet([
  { Product: 'p2', Qty: 2 },
]);

XLSX.utils.sheet_add_json(ws,
  [
    { Product: 'p3', Qty: 3 },
    { Product: 'p4', Qty: 4 },
    { Product: 'p5', Qty: 5 },
    { Product: 'p6', Qty: 6 },
    { Product: 'p7', Qty: 7 },
    { Product: 'p8', Qty: 8 },
  ],
  {
    header: ['Product', 'Qty'],
    skipHeader: true,
    origin: -1,  // append to bottom of worksheet starting on first column
  }
);


XLSX.utils.book_append_sheet(wb, ws, 'Bug sheet');

XLSX.writeFile(wb, 'bug.ods');
```

I expected `p3`...`p8` to be placed on rows 3 ... 8, but they ended up on rows 6 ... 11 (in LibreCalc at least).

![image](https://user-images.githubusercontent.com/33569/48968235-6353a780-efa1-11e8-98f0-3b5ed52b8eea.png)

I'm on 0.14.1. What might be going on?

**Comment by dandv** [comment]
Did some more digging. Looks like if the JSON array has N >= 4 elements, the library inserts N - 3 empty rows, if the existing worksheet has 2 rows.

**Comment by SheetJSDev** [comment]
The logical error is in https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L193-L199 : when `origin: -1` is specified and the number of rows inserted exceeds the number of rows in the file, it is added twice.

It would probably be simpler to proactively wraparound by checking if `_R < 0` in https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L186 and just adding the number of rows in the worksheet.  This would also handle cases like -2 for the penultimate row.

**Comment by dandv** [comment]
Thanks for confirming and looking forward to the fix!

**Comment by dandv** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=66589915)](https://www.bountysource.com/issues/66589915-sheet_add_json-with-origin-1-leaves-gap-from-bottom-of-worksheet?utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by dongido001** [comment]
Made a pull request that solves the issue #1463 @dandv

**Comment by dandv** [comment]
Yay! First time I'm about to award a bounty, after years of using BountySource :)

@SheetJSDev, can you please test and merge if everything checks out?

**Comment by dandv** [comment]
Hey @SheetJSDev, ping :)

**Comment by dandv** [comment]
Here's a 2020 ping!

**Comment by fabiooshiro** [comment]
workaround with the advantage of rewriting new columns title if your object has new properties
```
let arrayObjects = XLSX.utils.sheet_to_json(dataSheet);
arrayObjects.push(formValues);
XLSX.utils.sheet_add_json(dataSheet, arrayObjects);
```

**Comment by dandv** [comment]
Greetings from 2021 :exclamation:

**Comment by SheetJSDev** [comment]
This was fixed in a slightly different way (by updating the anchor row) in v0.16.0:

```diff
-		if(_R == -1) { _R = range.e.r + 1; range.e.r = _R + js.length - 1 + offset; }
+		if(_R == -1) { _R = _range.e.r + 1; range.e.r = _R + js.length - 1 + offset; }
```

That said, the bounty should be awarded to @dongido001 in recognition of the effort.
