### ISSUE TITLE
Cells merged using "Keep the contents of the hidden cells" option breaks cell coordinates

### ISSUE THREAD

**Issue by kachkaev** [SheetJS/sheetjs#1365]
Steps to reproduce:

1. Using LibreOffice, create a simple spreadsheet file called `cells-unmerged.ods`:  
  <img width="394" alt="cells-unmerged" src="https://user-images.githubusercontent.com/608862/48983349-ac147900-f0e5-11e8-9f0c-2e861a76dfea.png">

2. Merge two cells in each section using each of the three merge options:  
  <img width="425" alt="merge-options" src="https://user-images.githubusercontent.com/608862/48983363-d8c89080-f0e5-11e8-98fa-4f07cd123dae.png">

3. Save the resulting file as `cells-merged.ods`  
  <img width="396" alt="cells-merged" src="https://user-images.githubusercontent.com/608862/48983390-58565f80-f0e6-11e8-871a-60f92541420a.png">

4. Drop the file to https://oss.sheetjs.com/ and observe data in incorrect columns on row 7 (merged using _Keep the contents of the hidden cells_ option)  
  <img width="1056" alt="screenshot 2018-11-25 at 19 16 20" src="https://user-images.githubusercontent.com/608862/48983435-a79c9000-f0e6-11e8-8e63-6686a94cd59e.png">

_[Download both `cells-unmerged.ods` and `cells-merged.ods` as a zip archive](https://github.com/SheetJS/js-xlsx/files/2613401/cells-merge-experiment.zip) to simplify reproduction_

LibreOffice details:
```
Version: 6.1.3.2
Build ID: 86daf60bf00efa86ad547e59e09d6bb77c699acb
CPU threads: 8; OS: Mac OS X 10.14.1; UI render: default; 
Locale: en-GB (en_GB.UTF-8); Calc: group threaded
```

**Comment by reviewher** [comment]
The current view shows B7 and C7 at the right place.  The xlsx cli tool generated the attached XLSX which looks correct:

```
xlsx --dev --all --xlsx ~/Downloads/cells-merge-experiment/cells-merged.ods
```

[cells-merged.ods.xlsx](https://github.com/SheetJS/sheetjs/files/7149070/cells-merged.ods.xlsx)
