### ISSUE TITLE
IE11 reading/converting dates strangely...

### ISSUE THREAD

**Issue by timinterweb** [SheetJS/sheetjs#1366]
Reading a CSV, a date cell of '13/11/2018' is being parsed as '43476' in IE11. Comes through fine and as expected in other modern browsers.

This is how I'm reading the data:
`data = XLSX.utils.sheet_to_json(worksheet, { raw: true, header:1 });
console.log(data);`

Any help would be greatly appreciated. This js library is amazing.

Thanks!

**Comment by denmarkdavis** [comment]
Update:

It's being converted in IE as an excel date serial number. Another issue is that if I calculate the date from this number, then it outputs the incorrect date.

It's worth noting that I can't change the format of the original CSV...

Thanks

**Comment by SheetJSDev** [comment]
pass `cellDates: true` when reading the original CSV to preserve the date.
