### ISSUE TITLE
how to freeze the first line?

### ISSUE THREAD

**Issue by veto64** [SheetJS/sheetjs#1371]
how to freeze the first line like i do in python
worksheet.freeze_panes(1, 1) # # Freeze the first row and column

**Comment by Valeriy-Burlaka** [comment]
@SheetJSDev , any chance that this feature will become available anytime soon?

**Comment by SheetJSDev** [comment]
In the interest of trying to reach a v1.0.0, we are focusing on data.  Embellishments like freezing rows and columns are definitely of interest, but not before the milestone.  In the interim, we do offer this as part of our [Pro offering](https://sheetjs.com/pro)

**Comment by NoelToy** [comment]
Hi @SheetJSDev I would like to know if **SheetJS** has the feature to **freeze the columns** while we do an excel export? I have gone through the documentation but didn't find anything specific to column freezing. It would be **helpful if you can give some clarity on this**.

**Comment by NoelToy** [comment]
Hi @SheetJSDev I would like to know if **SheetJS** has the feature to **freeze the columns** while we do an excel export? I have gone through the documentation but didn't anything specific to column freezing. It would be **helpful if you can give a clarity on this**.
