### ISSUE TITLE
Type d is generated even without cellDates: true for ODS files

### ISSUE THREAD

**Issue by dandv** [SheetJS/sheetjs#1374]
https://docs.sheetjs.com/#data-types states

> Type `d` is the Date type, generated only when the option `cellDates` is passed.

This piece of code suggests that the Date time is generated even without that option, if the output file is `ods`:

```js
const XLSX = require('xlsx');

const wb = XLSX.utils.book_new();

const ws = XLSX.utils.json_to_sheet([]);

XLSX.utils.book_append_sheet(wb, ws, 'Bug sheet');

ws.A1 = { t: 'd', v: new Date('2018-11-30T23:30:00Z') };

XLSX.writeFile(wb, 'date.ods');
```

The output file contains

    <table:table-cell office:value-type="date" office:date-value="2018-11-30T23:30:00.000Z" table:style-name="ce1">
      <text:p>2018-11-30T23:30:00.000Z</text:p>
    </table:table-cell>

**Comment by dandv** [comment]
Saw at https://docs.sheetjs.com/#writing-options

> `cellDates` only applies to XLSX output

Perhaps worth repeating that in the [Data Types](https://docs.sheetjs.com/#data-types) section?

**Comment by SheetJSDev** [comment]
Situation is described below.  If you think the README is missing something, please send a PR with the recommended changes:

**ODS**

ODS has a native date type, with `office:value-type="date"`.

When reading a date cell, `cellDates` is used to determine whether a proper Date object or a datecode number is generated.

When writing a date, SheetJS will ignore the `cellDates` property and generate a proper ODS date.

**XLS / XLSB**

XLS / XLSB do not have a native date type.  It is always numbers with a format that uses date tokens.

When reading a cell, the number format is checked.  If the format looks like a date, `cellDates` determines whether a Date or Number cell is generated.

When writing a date, SheetJS will ignore the `cellDates` property and write a Number cell.  If a date format is not specified, the default format 14 will be used.

**XLSX**

XLSX supports the XLS-style format codes (`t="n"`)as well as a date type (`t="d"`).  Note that the date type ignores the timezone metadata, so it has the same problems as date codes)

When reading a date cell, `cellDates` determines whether a Date or Number cell is generated.

When reading a number cell, the number format is checked.  If the format looks like a date, `cellDates` determines whether a Date or Number cell is generated.

When writing a date, SheetJS will check the `cellDates` property to determine whether to write a Date cell or a Number cell
