### ISSUE TITLE
0.14.1 - has issue with skipping header

### ISSUE THREAD

**Issue by pravink** [SheetJS/sheetjs#1382]
0.14.1 - has issue with skipping header

in 0.14.0 - I used below line of code to skip the headers in XSLX
  XLSX.stream.to_json(worksheet, {raw:true,header:1})     

but 0.14.1 version doesn't work with skipping headers.

**Comment by SheetJSDev** [comment]
The 0.14.0 behavior was incorrect.

For 0.14.1+ the following snippet returns a stream of arrays starting from the second row:

```js
var stream = XLSX.stream.to_json(worksheet, {
  raw: true, // use raw values
  header: 1, // array of arrays instead of objects
  range: 1, // skip 1 row (start on Excel row 2 = SheetJS row 1)
});
```
