### ISSUE TITLE
Is it possible to parse excel files partially

### ISSUE THREAD

**Issue by eason123deng** [SheetJS/sheetjs#1383]
Hi there, when I tried to import a large excel file (140MB), XLSX returned an empty object. However, all I need is the `range of the table` and the `first say 20 rows of data`. Is it possible to obtain these information without parsing the entire file?

related to several issues: #412, #61, #1295, #1195, #1025, #792
Update: I was able to open the file with Excel, so this problem is likely due to file size
Update: An example of such file is https://drive.google.com/file/d/14uZZY56lXN34MGwx30HZ8cryW_9AzdnV/view?usp=sharing

**Comment by varunsharma27** [comment]
As per Docs:
The most common and interesting formats (XLS, XLSX/M, XLSB, ODS) are ultimately ZIP or CFB containers of files. Neither format puts the directory structure at the beginning of the file: ZIP files place the Central Directory records at the end of the logical file, while CFB files can place the storage info anywhere in the file! As a result, to properly handle these formats, a streaming function would have to buffer the entire file before commencing. That belies the expectations of streaming, so we do not provide any streaming read API.

**Comment by SheetJSDev** [comment]
`sheetRows: 20` is the literal answer, but it doesn't actually address the issue of large files.  #61  is an early discussion on the matter
