### ISSUE TITLE
Cannot Resolve Modules When Building

### ISSUE THREAD

**Issue by tharper1977** [SheetJS/sheetjs#1389]
I am having an issue with something that supposedly has been fixed.  I am using "js-xlsx": "^0.8.22", in my application and get the build issue below:  

> PS src\Web\ClientApp> ng build
> 
> Date: 2018-12-18T17:25:59.412Z
> Hash: 696d2b9b7a2622f2a129
> Time: 20448ms
> chunk {main} main.js, main.js.map (main) 1.31 MB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 228 kB [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 180 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 7.82 MB [initial] [rendered]
> 
> WARNING in ./node_modules/js-xlsx/ods.js
> Module not found: Error: Can't resolve '../xlsx' in 'src\Web\ClientApp\node_modules\js-xlsx'
> 
> WARNING in ./node_modules/js-xlsx/xlsx.js
> Module not found: Error: Can't resolve 'crypto' in 'src\Web\ClientApp\node_modules\js-xlsx'
> 
> ERROR in ./node_modules/js-xlsx/xlsx.js
> Module not found: Error: Can't resolve 'fs' in 'src\Web\ClientApp\node_modules\js-xlsx'
> ERROR in ./node_modules/js-xlsx/ods.js
> Module not found: Error: Can't resolve 'fs' in 'src\Web\ClientApp\node_modules\js-xlsx'
> ERROR in ./node_modules/js-xlsx/ods.js
> Module not found: Error: Can't resolve 'xlsx' in 'src\Web\ClientApp\node_modules\js-xlsx'

I have searched for a resolution, but it appears to have been fixed. 
- https://github.com/SheetJS/js-xlsx/issues/467.  
- https://github.com/SheetJS/js-xlsx/issues/585

I do not have a webpack.config file in my application.

**Comment by rtlly** [comment]
I have the same problem with you? so, do you find the solution. if you do, can you help me solve this ,thank you. 

> I am having an issue with something that supposedly has been fixed. I am using "js-xlsx": "^0.8.22", in my application and get the build issue below:
> 
> > PS src\Web\ClientApp> ng build
> > Date: 2018-12-18T17:25:59.412Z
> > Hash: 696d2b9b7a2622f2a129
> > Time: 20448ms
> > chunk {main} main.js, main.js.map (main) 1.31 MB [initial] [rendered]
> > chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 228 kB [initial] [rendered]
> > chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
> > chunk {styles} styles.js, styles.js.map (styles) 180 kB [initial] [rendered]
> > chunk {vendor} vendor.js, vendor.js.map (vendor) 7.82 MB [initial] [rendered]
> > WARNING in ./node_modules/js-xlsx/ods.js
> > Module not found: Error: Can't resolve '../xlsx' in 'src\Web\ClientApp\node_modules\js-xlsx'
> > WARNING in ./node_modules/js-xlsx/xlsx.js
> > Module not found: Error: Can't resolve 'crypto' in 'src\Web\ClientApp\node_modules\js-xlsx'
> > ERROR in ./node_modules/js-xlsx/xlsx.js
> > Module not found: Error: Can't resolve 'fs' in 'src\Web\ClientApp\node_modules\js-xlsx'
> > ERROR in ./node_modules/js-xlsx/ods.js
> > Module not found: Error: Can't resolve 'fs' in 'src\Web\ClientApp\node_modules\js-xlsx'
> > ERROR in ./node_modules/js-xlsx/ods.js
> > Module not found: Error: Can't resolve 'xlsx' in 'src\Web\ClientApp\node_modules\js-xlsx'
> 
> I have searched for a resolution, but it appears to have been fixed.
> 
> * #467.
> * #585
> 
> I do not have a webpack.config file in my application.

**Comment by SheetJSDev** [comment]
This was fixed by adding some options to package.json.  For more detailed info, check the [webpack demo](https://github.com/SheetJS/sheetjs/tree/master/demos/webpack) and the [angular demo](https://github.com/SheetJS/sheetjs/tree/master/demos/angular2)
