### ISSUE TITLE
I tried to change the "value" but it's not working in IE10, it works on chrome. Can anybody help me?

### ISSUE THREAD

**Issue by DanielCM23** [SheetJS/sheetjs#1393]
I tried to change the "value" but it's not working in IE10, it works on chrome. Can anybody help me?

_Originally posted by @SheetJSDev in https://github.com/SheetJS/js-xlsx/issues/1102#issuecomment-388201128_

**Comment by reviewher** [comment]
[Based on this thread](https://stackoverflow.com/questions/9011644/how-to-reset-clear-file-input) it seems that IE requires you to tear down the element (remove the file input element and add a new one to the DOM) or reset the entire form (calling `reset()` on the form that contains the file input element)
