### ISSUE TITLE
Accessing Cell data Dynamically

### ISSUE THREAD

**Issue by rohitmore1995** [SheetJS/sheetjs#1395]
I want to Display excel file's first column in drop-down and when we select option from drop-down then I want to display the corresponding data from excel file

**Comment by rohitmore1995** [comment]
<!doctype html>
<html>
<head>
<title>Excel to JSON Demo</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" name="viewport"/>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="xlsx.full.min.js"></script>
</head>
<body>

<label>Add Equipments:</label><select id="mySelect" name="Equipment" class="country">
							<option value="">Select Name</option>
						</select>
						
						<div class="clear"></div>
						<div id="Mydiv"style="float:left;"> "A3:E3" rage values are=  </div></br>
						<div id="Mydiv1" style="float:left;">Inchprice1</div>
						<div id="Mydiv2" style="float:left;">Unitprice1</div>
<script>

var url = "test.xlsx";
var oReq = new XMLHttpRequest();
oReq.open("GET", url, true);
oReq.responseType = "arraybuffer";

oReq.onload = function(e) {
  var arraybuffer = oReq.response;

 
  var data = new Uint8Array(arraybuffer);
  var arr = new Array();
  for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
  var bstr = arr.join("");
  var workbook = XLSX.read(bstr, {type:"binary"});
  var first_sheet_name = workbook.SheetNames[0];
  var worksheet = workbook.Sheets[first_sheet_name];
  console.log(XLSX.utils.sheet_to_json(worksheet,{raw:true}));//convert data into JSON
  var range = XLSX.utils.decode_range(worksheet['!ref']);
  for(var R = range.s.r; R <= range.e.r; ++R) {
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var cell_address = {c:C, r:R};
    /* if an A1-style address is needed, encode the address */
    var cell_ref = XLSX.utils.encode_cell(cell_address);
	console.log(cell_address)
	console.log(C.v)
	
  }
}
  
  var variable=XLSX.utils.sheet_to_json(worksheet,{raw:true});
 var i;
for (var i = 0; i < variable.length; i++)
 {
		$("#mySelect").append("<option value='"+variable[i].Price+"'>"+variable[i].Price+"</option>" );
		console.log(variable[i].Price)
}
}
oReq.send();
</script>
</body>
</html>
..this My code...below is my test.xlsx file..
[test.xlsx](https://github.com/SheetJS/js-xlsx/files/2706641/test.xlsx)

**Comment by reviewher** [comment]
https://codesandbox.io/s/compassionate-shannon-igrsg?file=/index.html

Key part:

```js
	var variable = XLSX.utils.sheet_to_json(worksheet, { raw: true });
	var i;
	for (var i = 0; i < variable.length; i++) {
		$("#mySelect").append("<option value='" + i + "'>" + variable[i].Price + "</option>");
	}
	$("#mySelect").on("change", function(e) {
		var sel = $("option:selected", this);
		var idx = sel.val();
		console.log(idx);
		console.log(variable[idx]);
		$("#Mydiv1").html(variable[idx].InchSize);
		$("#Mydiv2").html(variable[idx].UnitPrice);
	});
```

<details><summary>Full code</summary>

```html
<!doctype html>
<html>
<head>
<title>Excel to JSON Demo</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" name="viewport"/>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://unpkg.com/xlsx"></script>
</head>
<body>

<label>Add Equipments:</label><select id="mySelect" name="Equipment" class="country">
							<option value="">Select Name</option>
						</select>
						
						<div class="clear"></div>
						<div id="Mydiv"style="float:left;"> "A3:E3" rage values are=  </div></br>
						<div id="Mydiv1" style="float:left;">Inchprice1</div>
						<div id="Mydiv2" style="float:left;">Unitprice1</div>
<script>

var url = "issue1395.xlsx";
var oReq = new XMLHttpRequest();
oReq.open("GET", url, true);
oReq.responseType = "arraybuffer";

oReq.onload = function (e) {
  var arraybuffer = oReq.response;
  var workbook = XLSX.read(arraybuffer, { type: "array" });
  var first_sheet_name = workbook.SheetNames[0];
  var worksheet = workbook.Sheets[first_sheet_name];
  console.log(XLSX.utils.sheet_to_json(worksheet, { raw: true }));//convert data into JSON
  var range = XLSX.utils.decode_range(worksheet['!ref']);
  for (var R = range.s.r; R <= range.e.r; ++R) {
    for (var C = range.s.c; C <= range.e.c; ++C) {
      var cell_address = { c: C, r: R };
      /* if an A1-style address is needed, encode the address */
      var cell_ref = XLSX.utils.encode_cell(cell_address);
      console.log(cell_address)
      console.log(C.v)

    }
  }

  var variable = XLSX.utils.sheet_to_json(worksheet, { raw: true });
  var i;
  for (var i = 0; i < variable.length; i++) {
    $("#mySelect").append("<option value='" + i + "'>" + variable[i].Price + "</option>");
	}
	$("#mySelect").on("change", function(e) {
		var sel = $("option:selected", this);
		var idx = sel.val();
		console.log(idx);
		console.log(variable[idx]);
		$("#Mydiv1").html(variable[idx].InchSize);
		$("#Mydiv2").html(variable[idx].UnitPrice);
	});
}
oReq.send();
</script>
</body>
</html>
```

</details>
