### ISSUE TITLE
XLSX : Make BOLD Header : Using Angular 4

### ISSUE THREAD

**Issue by profile4vaibhav** [SheetJS/sheetjs#1403]
Hello Team,

I am using XLSX library to export my multiple grids into one single excel file with the help of Angular 4.
I want to make the Headers of the excel BOLD, I tried it but didn't find a way.
So can u just tell me how do i do that, or do we need a paid version of XLSX to achieve this.

**Comment by bhavinshiroya1994** [comment]
@profile4vaibhav 

same problem, please tell me anyone answer

**Comment by Alian248** [comment]
？？？发自我的华为手机-------- 原始邮件 --------主题：Re: [SheetJS/js-xlsx] XLSX : Make BOLD Header : Using Angular 4 (#1403)发件人：bhavinshiroya1994 收件人：SheetJS/js-xlsx 抄送：Subscribed @profile4vaibhav
same problem, please tell me anyone answer

**Comment by curiousalok** [comment]
same problem.If anyone has solution to this please do share .

**Comment by tayyabxatti** [comment]
i used this for loop to get to the headers :

for(var C = range.s.r; C <= range.e.r; ++C) {
        var address = XLSX.utils.encode_col(C) + "1"; // <-- first row, column number C
        if(!ws[address]) continue;
        debugger
        
        // ws[address].s=ws[address].s={
				// 	font:{
				// 		bold:true
        	// }};
        ws[address].v=ws[address].v.bold(); 
      }

this results in headers values as <b>value</b> I just need to encode it somehow which I am facing difficulty achieving

**Comment by SheetJSDev** [comment]
Bold and other text and cell styling are covered in our [Pro builds](https://sheetjs.com/pro)
