### ISSUE TITLE
Is there a way to read only 1 worksheet from workbook?

### ISSUE THREAD

**Issue by reachhimanshujaswal** [SheetJS/sheetjs#1406]
I have a workbook with a lot of worksheets but i only need to parse 1 single sheet. I want to reduce the total time taken by XLSX.read function. 

I am using booksheets and bookprops options to read workbooks's metadata and then want to read only 1 worksheet using that metadata.
_**var workbook = XLSX.readFile('1546891304230_1373_2.xlsx',{bookSheets:true,bookProps:true});
var sheetname = workbook.SheetNames.sort()[0];**_

I couldn't find any function in documentation which can achieve that. Is it possible?

**Comment by cogud0908** [comment]
Have you solved it?

**Comment by reachhimanshujaswal** [comment]
I couldn't solved it.

SheetJS Team, Any solution for this problem?

**Comment by ryan-d-williams** [comment]
For anyone still looking: you can accomplish this with the `sheets` property of the `readFile` function. It's listed in the properties section [here](https://github.com/SheetJS/sheetjs#parsing-options)

`
var workbook = XLSX.readFile(filename,{sheets: ['sheet1','shee2']});
`

**Comment by SheetJSDev** [comment]
The `sheets` option to `read` and `readFile` was added in version 0.15.5 -- please update
