### ISSUE TITLE
How to Merge Header Cell ?

### ISSUE THREAD

**Issue by dhanidwiputra** [SheetJS/sheetjs#1418]
Hello everyone, is there any way to make export just like this ?

<img width="551" alt="screen shot 2019-01-29 at 11 35 55" src="https://user-images.githubusercontent.com/25683843/51884514-20a3b680-23ba-11e9-8024-fa2070aa5d44.png">

Is this possible to do it?

Thanks a lot for your time.

**Comment by bhavinshiroya1994** [comment]
how to add style in header row ?

**Comment by guoxiaodong** [comment]
the same question

**Comment by lanxuexing** [comment]
It's exciting.

**Comment by ryuchaehwa** [comment]
Did you solve it out? I need to do this as well ...

**Comment by unime-world** [comment]
Same question

**Comment by GusMartins499** [comment]
> Hello everyone, is there any way to make export just like this ?
> 
> <img alt="screen shot 2019-01-29 at 11 35 55" width="551" src="https://user-images.githubusercontent.com/25683843/51884514-20a3b680-23ba-11e9-8024-fa2070aa5d44.png">
> 
> Is this possible to do it?
> 
> Thanks a lot for your time.

same issue

**Comment by SheetJSDev** [comment]
Merging cells is a matter of setting the `!merges` key of the worksheet.  https://github.com/SheetJS/sheetjs/issues/416#issuecomment-286932882 is an example.

Styling like borders and bold are covered in our [Pro builds](https://sheetjs.com/pro)
