### ISSUE TITLE
XLS data cannot be read, but XLSX can be read

### ISSUE THREAD

**Issue by hxd19960509** [SheetJS/sheetjs#1420]
readExcel (e) {
      var files = e.target.files

      var fileReader = new FileReader()
      fileReader.onload = function (ev) {
        try {
          var data = ev.target.result
          var workbook = XLSX.read(data, {
            type: 'binary'
          })
          
          var persons = []
        } catch (e) {
          return
        }

        var fromTo = ''

        for (var sheet in workbook.Sheets) {
          if (workbook.Sheets.hasOwnProperty(sheet)) {
            fromTo = workbook.Sheets[sheet]['!ref']
            console.log(fromTo)
            persons = persons.concat(XLSX.utils.sheet_to_json(workbook.Sheets[sheet]))
            break 
          }
        }

        console.log(persons)
      }

      fileReader.readAsBinaryString(files[0])
    },

**Comment by hxd19960509** [comment]
import '../../assets/js/xlsx.core.min.js'
import XLSX from 'xlsx'

**Comment by hxd19960509** [comment]
error message:Cannot read property 'decode' of undefined

**Comment by hxd19960509** [comment]
![image](https://user-images.githubusercontent.com/46509401/51972254-f505f680-24b5-11e9-8b10-e12f7cd10d6a.png)

**Comment by hxd19960509** [comment]
Upstairs,Error reading XLS file

**Comment by reviewher** [comment]
Use `xlsx.full.min.js`.  XLS needs the codepage dependency.  XLSX does not
