### ISSUE TITLE
Exported table doesn't include array values as cell

### ISSUE THREAD

**Issue by gadzhimari** [SheetJS/sheetjs#1423]
I tried to export to xlsx file, from js object, but in my structure some cell has values as arrays. And in final xlsx this cell are empty.

```
export function exportFile(data, filename) {
  const header = Object.keys(data[0]);
  const worksheet = xlsx.utils.json_to_sheet(data, { header });
  const workbook = xlsx.utils.book_new();
	xlsx.utils.book_append_sheet(workbook, worksheet, "SheetJS");
  xlsx.writeFile(workbook, filename)
}
```

Here the original [data structure](https://repl.it/@gadzhimari/ThornyHumbleDoom), the produced [worksheet](https://repl.it/@gadzhimari/CaninePepperyTelephones) and [workbook](https://repl.it/@gadzhimari/PleasingExhaustedProperties)

**Comment by nimatullah** [comment]
I have the same issue

**Comment by Jacobo4** [comment]
same :s

**Comment by reviewher** [comment]
`json_to_sheet` looks for simple values that can be translated to Excel.  Explicitly convert the arrays to strings:

```js
const fixedData = usersData.map(row => Object.fromEntries(Object.entries(row).map(([k,v]) => ([k, Array.isArray(v) ? v.join(",") : v]))))
```
