### ISSUE TITLE
table_to_sheet， original character: " 083 - 5" is " 5 - 1 - 1983" displayed in EXCEL after export

### ISSUE THREAD

**Issue by coolio125186** [SheetJS/sheetjs#1431]
The original character: " 083 - 5" is " 5 - 1 - 1983" displayed in EXCEL after export, and the content after setting the cell to text format is " 30437". I don't want to be changed. What should I do?
I know that setting [raw:ture] can retain the original characters, but in this way, the number types in the table will also be converted into character types, which is not what I want.

**Comment by reviewher** [comment]
Chrome/NodeJS think `"083-5"` is the date `May 01 1983`.  Closing in favor of #1300
