### ISSUE TITLE
Importing not working on downloaded worksheets.  

### ISSUE THREAD

**Issue by davimdantas** [SheetJS/sheetjs#1440]
I think the problem is related to this one: 
https://github.com/SheetJS/js-xlsx/issues/470

When importing downloaded files I got no data, but just by opening on excel and saving it the problem is solved.

[Files to test](https://drive.google.com/drive/folders/1QFHQe1tOz0f5xK0h04xLU2-c8pA5SoHe?usp=sharing)

The behavior can be checked here:
https://oss.sheetjs.com/js-xlsx/

**Comment by SheetJSDev** [comment]
The file is misreporting the range.  To see that, http://sheetjs.com/cfb-editor/ is a browser-based tool for inspecting the archives.  Click and drag the unsaved file, then click "xl/worksheets/sheet1.xml" and click "View as Text" to see the raw data.  The file's reported range is A1:A15 -- look for the "dimensions" tag:

```xml
  <dimension ref="A1:A15"></dimension>
```

**Comment by davimdantas** [comment]
Thank you, for your reply. 
So there's no way around this other than opening and saving the file manually ?

**Comment by reviewher** [comment]
Until the parser is changed to recalculate the range, use `update_sheet_range` from https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions#updating-worksheet-range
