### ISSUE TITLE
Image is not display on .xlsx file

### ISSUE THREAD

**Issue by JigneshPatel04** [SheetJS/sheetjs#1441]
Hello,  

I am working on angular project . I am using code as below
import * as XLSX from 'xlsx';

buttonClick() {
    const ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(this.table.nativeElement); // converts a DOM TABLE element to a worksheet
    const wb: XLSX.WorkBook = XLSX.utils.book_new();   
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    const date = new Date();
    const fileName =
      report.xlsx;
    /* save to file */
    XLSX.writeFile(wb, fileName);
  }

HTML , I have used table but in image part I have used this type.
<img alt="" src="https://www.w3schools.com/html/pic_html5.gif">

I have created .xlsx file and other text and numbers are display but image is not display on .xlsx file.
Any one know ?

**Comment by SheetJSDev** [comment]
Image support is included in our [Pro builds](https://sheetjs.com/pro)
