### ISSUE TITLE
the method XLSX.utils.sheet_to_txt is writing a random Asian Language character

### ISSUE THREAD

**Issue by Bandito11** [SheetJS/sheetjs#1443]
XLSX.utils.sheet_to_txt

Using the above mention method it writes a random Asian Language character in the first row. It doesn't when converting to CSV or XLSX.

![file](https://user-images.githubusercontent.com/9807561/53691344-3a863f80-3d52-11e9-9fa2-ad6d35e9d92a.jpeg)

**Comment by sevencai** [comment]
I got the same problem when using `sheet_to_txt `

**Comment by BergerMarcin** [comment]
I got similar issue (only lets say less critical then from Bandito11): **loosing or changing Polish special characters, even adding characters to the first cell. I could not set UTF-8 to be applied**. 
It is peculiar that json parsing **XLSX.utils.sheet_to_json** works OK but for my case is much much less convenient (I will not explain here why) 

See my case the same sample to compare (I am using XLSX to import translation form translation company):
1. **XLSX.utils.sheet_to_txt sample:**
ÿþtext_key      pl      en
passwordReset.change-password   Zmiana HasBa    Change Password
passwordReset.password  HasBo   Password
passwordReset.confirmPassword   Potwierdz HasBo Confirm Password
passwordReset.confirm   Zatwierdz       Let's Go
passwordReset.invalidEmail      BBdny email     Invalid email
passwordReset.invalidLogIn      BBdny email lub hasBo   Invalid login or password
faq.start.slogan        Pozwól mi Pomóc!        Let me Help you!
faq.start.headline      Czsto Zadawane Pytania ... & Odpowiedzi.        Frequently Asked Questions (FAQ) ... & Answers.

2. **XLSX.utils.sheet_to_json sample**:
[
  {
    text_key: 'passwordReset.change-password',
    pl: 'Zmiana Hasła',
    en: 'Change Password'
  },
  { text_key: 'passwordReset.password', pl: 'Hasło', en: 'Password' },
  {
    text_key: 'passwordReset.confirmPassword',
    pl: 'Potwierdź Hasło',
    en: 'Confirm Password'
  },
  {
    text_key: 'passwordReset.confirm',
    pl: 'Zatwierdź',
    en: "Let's Go"
  },
  {
    text_key: 'passwordReset.invalidEmail',
    pl: 'Błędny email',
    en: 'Invalid email'
  },
  {
    text_key: 'passwordReset.invalidLogIn',
    pl: 'Błędny email lub hasło',
    en: 'Invalid login or password'
  },
  {
    text_key: 'faq.start.slogan',
    pl: 'Pozwól mi Pomóc!',
    en: 'Let me Help you!'
  },
  {
    text_key: 'faq.start.headline',
    pl: 'Często Zadawane Pytania ... & Odpowiedzi.',
    en: 'Frequently Asked Questions (FAQ) ... & Answers.'
  }
]

**Comment by SheetJSDev** [comment]
If the goal is to manipulate the result from JS or the DOM (either putting the result in an element or passing the text to other functions), pass the option `type: string`:

```js
var result = XLSX.utils.sheet_to_txt(worksheet, { type: "string" });
```

Without it, if the codepage library is available (nodejs, standalone `xlsx.full.min.js` script), the result is converted to UTF-16LE and a BOM is prepended

**Comment by BergerMarcin** [comment]
WORKS PERFECT! :+1:

I could only say for other people that I was only added that parameter `{type: 'string'}` @ reading file to workbook what was not enough:
```const workBookXLSXContentFile = XLSX.readFile(filenameIn, {type: 'string', sheets: FILENAME_IN.split('.')[0]});```
