### ISSUE TITLE
how to function run ?

### ISSUE THREAD

**Issue by MedinaGitHub** [SheetJS/sheetjs#1444]
if i get a data, for example A1 = 1 and A2 = 2 and A3 = SUM(A1,A2)

if i change A1 for 100, then, the result of A3 is 3 =/ no 102.

**Comment by fabiooshiro** [comment]
try the lib [xlsx-calc](https://github.com/fabiooshiro/xlsx-calc/blob/master/README.md) 
🙏

**Comment by SheetJSDev** [comment]
We offer formula recalculation and general express evaluation as a component in our [Pro compendium](https://sheetjs.com/pro) -- inquire by email for more details.
