### ISSUE TITLE
took second row as a header and now empty cell is not coming in sheet_to_json object

### ISSUE THREAD

**Issue by Hardik-1204** [SheetJS/sheetjs#1446]
XL_row_object = XLSX.utils.sheet_to_json(workbook.Sheets[sSheet1Name],{range:1},{
		    	 blankRows: false,
		         defval: '',
		     });

I want empty cell should include with enroll_no=""; like this .. Help me

**Comment by reviewher** [comment]
The two options objects should be combined into one block e.g.

```js
var range = XLSX.utils.decode_range(workbook.Sheets[sSheet1Name]["!ref"]);
range.s.r++;
XL_row_object = XLSX.utils.sheet_to_json(workbook.Sheets[sSheet1Name],{
  range:range,
  blankRows: false,
  defval: '',
});
```
