### ISSUE TITLE
nested object and array 

### ISSUE THREAD

**Issue by velishojuvinaykumar** [SheetJS/sheetjs#1449]
@kawanet  @session  @jimjin  @hmalphettes ![image](https://user-images.githubusercontent.com/15623893/53941698-d0b5bf00-40de-11e9-9875-a03eaab0a23f.png)

@cthielen @kawanet @kawanet @jimjin @hmalphettes  i am unable to write to excel in the below json format could anyone please help me out.

[
{
company:"abc",
companyId:"abc01",
companyStatus:"Active",
employeeDetails:[
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"}
]
},
company:"abc",
companyId:"abc01",
companyStatus:"Active",
employeeDetails:[
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"}
]
},
company:"abc",
companyId:"abc01",
companyStatus:"Active",
employeeDetails:[
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"}
]
},
company:"abc",
companyId:"abc01",
companyStatus:"Active",
employeeDetails:[
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"},
		{name:"abc",role:"test"}
]
},
]

**Comment by AyushG25** [comment]
I also faced the same problem. It wont be able to convert nested/complex JSON structure to excel. I tried to use aoa_to_sheet but that also didn't work (made the tab unresponsive with no error). You can use jsonexport package and convert your json data to csv format.

**Comment by reviewher** [comment]
Use `aoa_to_sheet` to extract the data in an array of arrays, then write your own function to massage the raw data into the format you like.
