### ISSUE TITLE
生成的html能保持excel树结构吗

### ISSUE THREAD

**Issue by chengqinghuanyu** [SheetJS/sheetjs#1452]
我有excel左侧有很多层级可以伸缩如下展示：
![image](https://user-images.githubusercontent.com/7715231/54120527-e1459c80-4432-11e9-8312-af8557240b13.png)

![image](https://user-images.githubusercontent.com/7715231/54120544-f3273f80-4432-11e9-8961-801d8a66f0a2.png)
我想把excel的树结构在生成时也展示出来，怎么展示？

**Comment by chengqinghuanyu** [comment]
使用sheet_to_table生成为html的table的形式，也能伸缩展示，不知道哪些数据是树形结构的。

**Comment by chengqinghuanyu** [comment]
![image](https://user-images.githubusercontent.com/7715231/54120763-8496b180-4433-11e9-80b4-4598bc330511.png)
我尝试使用
![image](https://user-images.githubusercontent.com/7715231/54120780-9710eb00-4433-11e9-9b80-2f028792f835.png)
结果语法错误。希望能得到社区的支持，谢谢。

**Comment by chengqinghuanyu** [comment]
我用的是
![image](https://user-images.githubusercontent.com/7715231/54120998-43eb6800-4434-11e9-9fe3-03f63c4eb7c6.png)
![image](https://user-images.githubusercontent.com/7715231/54121013-4cdc3980-4434-11e9-937f-0c2016bac713.png)
数据源是
![image](https://user-images.githubusercontent.com/7715231/54121043-5cf41900-4434-11e9-9d6d-6b9dba0e872f.png)
类似这种数据但是层级是展示不出来的。

**Comment by SheetJSDev** [comment]
There's no natural way of representing the outline level in HTML.  If you can propose an option, we can investigate further
