### ISSUE TITLE
XLSX.read() error

### ISSUE THREAD

**Issue by YaoKaiPeng** [SheetJS/sheetjs#1455]
I need to read the data in the excel file, convert it to json, and format the date data.But I encountered an error in the process

code:

```
const wb = XLSX.read(file, {
  type: 'binary',
  cellHTML: false,
  cellDates: true,
  cellStyles: true,
  cellNF: false,
  cellText: false,
  WTF: true,
})
let xlsxData = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {
  defval: '',
  dateNF: 'YYYY-MM-DD HH:MM:SS',
  raw: false,
})
````

file:
>
title            | content             | date
--               | --                       | --
this is title  | this is content   | 2019年3月15日

error:
![image](https://user-images.githubusercontent.com/13029889/54413558-1868c600-4731-11e9-9d25-c406a411260d.png)
![image](https://user-images.githubusercontent.com/13029889/54413570-21f22e00-4731-11e9-9f3d-fff2892d8ab4.png)

**Comment by SheetJSDev** [comment]
That's coming from the reader, which likely means there's a missing or misunderstood format.  Can you share the original Excel file?  If it is confidential, feel free to email dev at sheetjs dot com with the file

**Comment by YaoKaiPeng** [comment]
[test.xlsx](https://github.com/SheetJS/js-xlsx/files/3021714/test.xlsx)

@SheetJSDev

**Comment by YaoKaiPeng** [comment]
> That's coming from the reader, which likely means there's a missing or misunderstood format. Can you share the original Excel file? If it is confidential, feel free to email dev at sheetjs dot com with the file

**Comment by SheetJSDev** [comment]
That error comes from the formats.  The custom number formats in your file are: (pipes added for clarification)

```
|_ * #,##0_ ;_ * \-#,##0_ ;_ * "-"_ ;_ @_ |
|_ "￥"* #,##0_ ;_ "￥"* \-#,##0_ ;_ "￥"* "-"_ ;_ @_ |
|_ * #,##0.00_ ;_ * \-#,##0.00_ ;_ * "-"??_ ;_ @_ |
|_ "￥"* #,##0.00_ ;_ "￥"* \-#,##0.00_ ;_ "￥"* "-"??_ ;_ @_ |
```

In the current version (0.16.2) every format works, and you can verify this with:

```js
var XLSX = require("xlsx");
var wb = XLSX.readFile("test.xlsx");
[41,42,43,44].map(idx => [12345,-12345,0,"abc"].map(v => XLSX.SSF.format(wb.SSF[idx],v)))
```

The results are:

```
[
  [ ' 12,345 ', ' -12,345 ', ' - ', ' abc ' ],
  [ ' ￥12,345 ', ' ￥-12,345 ', ' ￥- ', ' abc ' ],
  [ ' 12,345.00 ', ' -12,345.00 ', ' -   ', ' abc ' ],
  [ ' ￥12,345.00 ', ' ￥-12,345.00 ', ' ￥-   ', ' abc ' ]
]
```
