### ISSUE TITLE
Readme: Symbol for supported formats is *red* -> missleading

### ISSUE THREAD

**Issue by htgoebel** [SheetJS/sheetjs#1462]
The :o: symbol used to indicate supported formats is red. But red means: no, which makes the symbol irritating. Also in the raw test, this reads `:o:`, which might mean an unchecked form field.

Please choose a differed symbol, e.g. :ok:, :+1:, :heavy_check_mark:, :white_check_mark:, :ballot_box_with_check:

BTW: for unsupported you could use :heavy_multiplication_x:, :x: (which in the raw text might be understood as an checked form field), or :o: (which is red :-)

**Comment by SheetJSDev** [comment]
Wanted to find a single letter symbol to make the plain markdown table consistent.  Options are :a: :b: :m: :o: :v: :x: -- looking at these, the :v: looks pretty good.  Thoughts?

**Comment by htgoebel** [comment]
What about a simple, boring, old-style "yes" and "no"?

**Comment by reviewher** [comment]
Switched to unicode heavy checkmark ✔ 07c354cecf6b3a0fa95ee9273420c369f483d292
