### ISSUE TITLE
Converting string to date while exporting as xlsx

### ISSUE THREAD

**Issue by bikas-kumar** [SheetJS/sheetjs#1467]
Hi,

while exporting the table data into excel sheet the table data getting modified automatically.
Ex. Table is having data as '6/7' but in the excel it is coming like '6/7/2001'.
please let me know what is the issue and how i can fix it.

Thanks,
Bikas

**Comment by MrZhouZh** [comment]
I have the same problem. Have you solved it?

**Comment by bikas-kumar** [comment]
Not yet.

**Comment by MrZhouZh** [comment]
I have solved it. use 'raw'

**Comment by bikas-kumar** [comment]
Can you please send me the sample code?

**Comment by MrZhouZh** [comment]
`
wb = XLSX.utils.table_to_book(document.getElementById(domId), { raw: true });
`

**Comment by bikas-kumar** [comment]
Thanks @MrZhouZh

**Comment by MrZhouZh** [comment]
You are welcome! I am writing this way to format all the cells. If you need to format, you can use 'dateNF'.

**Comment by reviewher** [comment]
Seems the issue is resolved
