### ISSUE TITLE
How to display an header and its row values as the last column contents using SheetJS

### ISSUE THREAD

**Issue by DivyaArun1985** [SheetJS/sheetjs#1475]
I have exported json to excel using XLSX.utils.sheet_to_json and the output has headers in the below order

![image](https://user-images.githubusercontent.com/49437516/55795757-1f8fb380-5ae6-11e9-81d8-32463ae30ba1.png)

I would like to display 'Total' and its contents as the last column. How can I achieve that?

Please note that I cannot order all the columns as some columns are dynamic and varies from one situation to another. For the common ones, I have already added header order. My requirement is to display the below headers first, then the dynamic ones followed by total. Total should always be in the end.

const headerInfo = ['Event Type', 'Start Date', 'End Date', 'Duration Name']; const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json, { header: headerInfo });

Please help

**Comment by SheetJSDev** [comment]
Scan the keys of the incoming data:

```js
const headerInfo = ['Event Type', 'Start Date', 'End Date', 'Duration Name'];

json.forEach(row => {
  Object.keys(row).forEach(k => {
    if(!headerInfo.includes(k) && k != "Total") headerInfo.push(k); 
  });
});
headerInfo.push("Total");

const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json, { header: headerInfo });
```
