### ISSUE TITLE
writeFile won't force a download (AngularJS, Chrome 73)

### ISSUE THREAD

**Issue by aroncal** [SheetJS/sheetjs#1479]
Trying to force a download from an AngularJS App (1.5.3) with writeFile inside a component when a button is clicked, just following the example in the demo page:
https://github.com/SheetJS/js-xlsx/tree/master/demos/angular
nothing happens, neither errors are printed. This is happening on Desktop Chrome v73.

On the contrary, if I use "write" to get the base64 encoded string and send it via email with a plugin, it'll work just fine from the compiled App on the phone.

**Comment by SheetJSDev** [comment]
@aroncal does the console show anything?  If not, can you test http://sheetjs.com/demos/table.html ?

**Comment by aroncal** [comment]
The console shows nothing.
The demo you linked works fine, but there is a difference, I'm doing it with `json_to_sheet`, like this:
```
...
var ws = XLSX.utils.json_to_sheet(records);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, sheetName);
XLSX.writeFile(wb, 'test.xlsx');
```
`records`is a flat array of Objects, all with the same keys, and the values vary from strings to integers and dates.
If I do it with 'write' and use the obtained base64 string to send en attachment in an email it works fine.
I see in the demo page that there some imports like 'FileSaver' and 'Blob', but those are only for IE, right? I'm using latest stable Chrome...

**Comment by dangfan** [comment]
I met the same issue. Nothing is shown in the console.

**Comment by SheetJSDev** [comment]
These are probably browser /device specific issues.  Please let us know what browser versions and devices you are using, then we can try to reproduce
