### ISSUE TITLE
v怎么用呢

### ISSUE THREAD

**Issue by fuyufuyu** [SheetJS/sheetjs#1488]
var wb = {
			SheetNames: ['mySheet'],
			Sheets: {
				'mySheet': Object.assign({}, output, {
					'!ref': ref,
					A2: { t: 'n', v: 1000 }
				})
			}
		};
v是原始值，我希望就是针对我导出表格的那个传入值进行处理，但是不传入v导出的excel中没有写入v的那一列就会消失，所以v保留传入值，应该传什么呢？

**Comment by Samicelus** [comment]
```
A2: {t:'s',v:''}
```

**Comment by reviewher** [comment]
Please restate the question in English and we will reopen the issue.
