### ISSUE TITLE
Wrong data format in exported Excel

### ISSUE THREAD

**Issue by mvicens** [SheetJS/sheetjs#1490]
I want to export a table with dates and numbers that are wrote in Spanish language (non-English format); and getting a correct Excel data is impossible. Only works fine from default format.

I was trying it in many ways and it seems undevelopable. [Here](https://codepen.io/anon/pen/GLPawx) is a live example.

**Comment by SheetJSDev** [comment]
use the TD attributes `data-t data-v data-z` to manually override the parsing logic.  `data-t` is a workaround for the type (`data-t="n"` for number, `data-t="s"` for string, `data-t="d"` for date). `data-v` is a workaround for the actual value, and data-z is a workaround for the number

**Comment by mvicens** [comment]
[It does not work](https://jsfiddle.net/w0eqr5L1/): results the same.

**Comment by SheetJSDev** [comment]
Sincere apologies for confusion.  In our [Pro builds](https://sheetjs.com/pro) we also aliased the `data-` prefix because a customer had issues with the W3C validator.  Using `t` and `v` work with the open source build: https://jsfiddle.net/v9724ydw/

**Comment by mvicens** [comment]
Numbers now works. And, for dates, there was a missing [fix](https://jsfiddle.net/k7h1antx/) to the passed value: it is required ISO format without time.

Nice! Thank you very much! 😃

However, a last little detail (and sorry for my perfectionism): In the exported file, Excel detects cell format of numbers as general instead of numeric (the expected one). With dates, it is right.

**Comment by SheetJSDev** [comment]
`z` attribute to override the number format.

.

We'd accept a PR to support `data-t` / `data-v` / `data-z` in the DOM reader and the HTML export.  They are read in the following lines (code should read the bare as well as the `data-` versions:

`t`: https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L168

```diff
-			var _t/*:string*/ = elt.getAttribute("t") || "";
+			var _t/*:string*/ = elt.getAttribute("data-t") || elt.getAttribute("t") || "";
```

`v`: https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L158

`z`: https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L159

They are written in the following lines.  They should be changed to write `data-` version:

`t`: https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L83

```diff
-			sp.t = cell && cell.t || 'z';
+			sp["data-t"] = cell && cell.t || 'z';
```

`v` and `z`: https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L86

**Comment by mvicens** [comment]
I have checked that dates is well displayed but stores cell internal data with time. Changing separator "-" to "/", solutions this. [Here](https://jsfiddle.net/gqj3o4rk/) is the improve.

Regarding numbers, I do not achieve it. Please, can you send me the online demo edited to view it?

**Comment by SheetJSDev** [comment]
You have to use the en-US symbols for the thousands separator (",") and the decimal point(".").  For your data, try `#,##0.##`:

```
<td t="n" v="{{item.number}}" z="#,##0.##">{{item.number | number}}</td>
```

**Comment by mvicens** [comment]
[Resolved](https://jsfiddle.net/kg38mces/)! Although the format appears as custom, not number. Thank you!
