### ISSUE TITLE
Xsl import not display images using sheet_to_json

### ISSUE THREAD

**Issue by LekshmiEmd** [SheetJS/sheetjs#1492]
Images not shown when getting excel data via sheet_to_json. Can we have any solution on this?

**Comment by diegoazh** [comment]
same issue here

**Comment by SheetJSDev** [comment]
`sheet_to_json` only deals with raw data.  Images don't make sense in context.

For general image import/export we offer that in our [Pro builds](https://sheetjs.com/pro)
