### ISSUE TITLE
Fail on creating ws and wb

### ISSUE THREAD

**Issue by richardnassar-external** [SheetJS/sheetjs#1505]
I'm trying to create a worksheet with 800 000 records, but with that amount of records it's unable to create it. I was able to create max of 350 000 records. Is there a way where I can create more records ?

**Comment by MobackAdarshPB** [comment]
Same here with 89450 rows and 111 columns.

**Comment by SheetJSDev** [comment]
JS engine limits are non-obvious and change even between browser updates, so it is hard to give a more general statement.  When trying to write, disabling compression and setting `dense: true` helps in NodeJS and Chrome.
