### ISSUE TITLE
Problem with datetime columns

### ISSUE THREAD

**Issue by bellotti92** [SheetJS/sheetjs#1507]
Hello guys. 

I noticed that when using **XLSX.json_to_sheet** and **XLSX.writeFile**. 

So, searching in the "Issues" i've found some answers who could solve my problem. I tried to use 
"options.worksheet: {dateNF: "dd/mm/yyyy hh:mm:ss", cellDates: true}" but no success.

**Original date: 14/05/2019 14:55:13 ( dd/mm/yyyy hh:mm:ss ) 
XLSX date: 14/05/2019 11:54:13 ( dd/mm/yyyy hh:mm:ss  losin -3 hours)** 

Can someone help me to resolve it?

**Comment by reviewher** [comment]
Dates were overhauled a while ago, please update and test:

```js
var d = new Date(2019,4,14,14,55,13,0);
var ws = XLSX.utils.json_to_sheet([[d]]);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue1507.xlsx");
```
