### ISSUE TITLE
XLSX.utils.table_to_book not preserving hyperlinks

### ISSUE THREAD

**Issue by KobyO** [SheetJS/sheetjs#1509]
I'm trying to save an HTML table to excel using `XLSX.utils.table_to_book()`. However, hyperlinks in the table are getting converted to raw text. How can I preserve the hyperlinks?

**Comment by morgenweck** [comment]
I have the same question

**Comment by kamilml** [comment]
same

**Comment by kamilml** [comment]
same...

I am using `l` but it isn't working
```javascript
{ wch: 30, l: { Target: "https://myurl.com/asd" } }
```

**Comment by SheetJSDev** [comment]
18ce6212c44c1d558a47410112e9bfecec27f44d
