### ISSUE TITLE
Phone numbers are formatted strangely

### ISSUE THREAD

**Issue by OscarGodson** [SheetJS/sheetjs#1510]
I have a simple sheet like this (example file attached):

First Name | Last Name | Phone Number | State
-- | -- | -- | --
Michael | Jordan | (555) 567-8900 | NC

I get this back though: 

```js
{v: 5555678900, t: "n", w: "5555678900-5555678900"}
```

Any ideas and is there a way to prevent this without forcing no formatting?

[a1_test.xlsx](https://github.com/SheetJS/js-xlsx/files/3185716/a1_test.xlsx)

**Comment by OscarGodson** [comment]
Curious if anyone has any work arounds at least for this?

**Comment by SheetJSDev** [comment]
This was fixed in the [number format library](https://github.com/SheetJS/ssf) but we haven't updated it here yet

**Comment by OscarGodson** [comment]
Do you have an example of how I'd integrate that? I understand how I'd use that if it didn't go through SheetJS but it seems like it goes into sheets and comes back out wrong so I'm not sure where to inject the number format library code into that process.

**Comment by OscarGodson** [comment]
I believe this is fixed. Can you confirm? I've been trying new versions since originally reported and it seems like it's working!

**Comment by SheetJSDev** [comment]
Yes this was fixed in 0.16.3
