### ISSUE TITLE
 XLSX.read(binary, { type: 'binary' }); takes long time.

### ISSUE THREAD

**Issue by nakshay** [SheetJS/sheetjs#1511]
I am creating workbook object from using below method, where binary is in the form of string, it takes ~9 sec for 2.5k rows and 10 columns, data in each cell is also small.

const wb: XLSX.WorkBook = XLSX.read(binary, { type: 'binary' });

Is there any alternative to create workbook object? can the speed be improved by any mean?

**Comment by MyAngularGit** [comment]
Even i'm facing same issue, page becomes unresponsive.
Please suggest good options.

**Comment by rajatjasuja23** [comment]
Any progress on this?

**Comment by SheetJSDev** [comment]
If you can share a file we can take a closer look.

In modern browsers and nodejs, you can try getting the data as an ArrayBuffer or Uint8Array or Buffer and call `XLSX.read(buf, { type: 'array' })`
