### ISSUE TITLE
Worksheet range not working

### ISSUE THREAD

**Issue by brunomarram** [SheetJS/sheetjs#1513]
I'm having a problem when I send a sheet to your demo. Basically, some columns of data were ignored and thats important columns of my file. I'll give an exemple.

Here is the file when i upload then without any modifications:

And here is the file when i upload then with an character in the last column of first row:

Note that the last columns not be in the first print.

Please help me, i really want to solve this fast!!

**Comment by SheetJSDev** [comment]
Can you share both files?

**Comment by brunomarram** [comment]
off course, this is the first file:
[Balancete de Verificação mês 01-2017 M.A.I.S software de resultados Ltda.XLSX](https://github.com/SheetJS/js-xlsx/files/3213983/Balancete.de.Verificacao.mes.01-2017.M.A.I.S.software.de.resultados.Ltda.XLSX)

and this is the seccond file:
[Balancete de Verificação mês 01-2017 M.A.I.S software de resultados Ltda.xlsx](https://github.com/SheetJS/js-xlsx/files/3213982/Balancete.de.Verificacao.mes.01-2017.M.A.I.S.software.de.resultados.Ltda.xlsx)

**Comment by SheetJSDev** [comment]
Most likely the reported range was incorrect.  In general you can use [`update_sheet_range`](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions) to correct for the range.
