### ISSUE TITLE
Export Excel with Big Data Around 200000 from json

### ISSUE THREAD

**Issue by alfradias** [SheetJS/sheetjs#1518]
I'm newbie in js-xlsx, i want to export data from json to excel with data 72 column and 200000 rows. When export data more than 20000 chrome was crash.

This my code for export excel

const EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
const EXCEL_EXTENSION = '.xlsx';

public exportAsExcelFile(json: any[], excelFileName: string): void {
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
    const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
    const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    this.saveAsExcelFile(excelBuffer, excelFileName);
  }
  
  private saveAsExcelFile(buffer: any, fileName: string): void {
    const data: Blob = new Blob([buffer], { type: EXCEL_TYPE });
    FileSaver.saveAs(data, fileName + '_' + new Date().getTime() + EXCEL_EXTENSION);
  }

Can someone help me, the best code to export excel with big data?

**Comment by jimmywarting** [comment]
I'm no expert with js-xlsx. but if you can get a readable stream from xlsx you can pipe it to the disk using [streamSaver](https://github.com/jimmywarting/StreamSaver.js)

**Comment by reviewher** [comment]
Grouping large file write issues into #77
