### ISSUE TITLE
change excel format as Text using XLSX

### ISSUE THREAD

**Issue by KhalsaSarav** [SheetJS/sheetjs#1523]
i have issue when i create excel file i want to concert all file and all columns into text or set format text
in this module we have a option Cell Object int this there is a proper t set to ‘s’(Text) but example not given that how to set .
Please Check the concern

**Comment by SheetJSDev** [comment]
If you want to set the format to "Text" rather than "General", set the property `z: "@"` on the text cells (`t: "s"`).  The `z` field is the "number format" and setting the format to `@` treats the value like text.
