### ISSUE TITLE
Support hiding cells when using table_to_book()

### ISSUE THREAD

**Issue by krojew** [SheetJS/sheetjs#1528]
Currently table_to_book() checks the cell visibility to determine if it should be skipped. There are uses cases when a cell should be visible in the browser, but hidden from export. It would be great if such cell could be marked (e.g. by a class) for being ignored.

**Comment by SheetJSDev** [comment]
You can programmatically hide rows in a worksheet by setting the hidden property of the row object: https://docs.sheetjs.com/#row-properties

**Comment by krojew** [comment]
@SheetJSDev yes but you need to do it after the fact, while it would be both easier and faster to do it during the conversion from a table.

**Comment by SheetJSDev** [comment]
Sure, this could be supported as a data-attribute attached to the TR element

**Comment by ChaseHardin** [comment]
I would have to agree that a data-attribute would be extremely helpful! I'm in a scenario where I have a column with an icon + text. It's downloading to the excel file with icon css + text. Having an attribute that I could put on my icon to hide it from the parser would be ideal.

**Comment by SheetJSDev** [comment]
The attribute `data-v=""` suppresses cells in the DOM walker
