### ISSUE TITLE
Uncaught TypeError: Cannot read property 'writeFileSync' of undefined

### ISSUE THREAD

**Issue by NhatL** [SheetJS/sheetjs#153]
Getting this error when I try and export an array to an excel file. The workbook is valid as doing console.log(wb) will allow me to see the workbook layout.

All I'm doing is

XLSX.writeFile(wb, 'sheetjs.xlsx');

**Comment by ryangallen** [comment]
What did you see NhatL?
https://xkcd.com/979/

**Comment by SheetJSDev** [comment]
@ryangallen @NhatL `writeFile` only works in a context where `require` is defined and `require('fs')` returns an object with a function `writeFileSync`.  nodejs is one such context.  The `write` function should be used in browser contexts.  It allows you to control the output type (including base64 and binary strings).  The README has an example showing how to work with the (now deprecated) [FileSaver interface](http://www.w3.org/TR/file-writer-api/#the-filesaver-interface):

```
/* bookType can be 'xlsx' or 'xlsm' or 'xlsb' */
var wopts = { bookType:'xlsx', bookSST:false, type:'binary' };

var wbout = XLSX.write(workbook,wopts);

function s2ab(s) {
  var buf = new ArrayBuffer(s.length);
  var view = new Uint8Array(buf);
  for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
  return buf;
}

/* the saveAs call downloads a file on the local machine */
saveAs(new Blob([s2ab(wbout)],{type:""}), "test.xlsx")
```

**Comment by NhatL** [comment]
@ryangallen I ended up just using the Microsoft XML Format (https://en.wikipedia.org/wiki/Microsoft_Office_XML_formats) and outputting a xlsx file like that. Worked fine for my case.

**Comment by ryangallen** [comment]
Figured it out. Thank you for the responses.

**Comment by elmawardy** [comment]
i tried SheetJSDev's solution and it worked for me ,just include the Filesaver.js https://github.com/eligrey/FileSaver.js/


`   var wb = {};
    wb.Sheets = {};
    wb.SheetNames = [];
    /* bookType can be 'xlsx' or 'xlsm' or 'xlsb' */
    var wopts = { bookType: 'xlsx', bookSST: false, type: 'binary' };

    var ws = { '!ref': "A1:F220" };
    ws.A1 = { h: "test", r: "<t>test</t>", t: "s", v: "test", w: "test" }

    wb.SheetNames.push('testSheet');
    wb.Sheets['testSheet'] = ws;

    var wbout = XLSX.write(wb, wopts);

    function s2ab(s) {
        var buf = new ArrayBuffer(s.length);
        var view = new Uint8Array(buf);
        for (var i = 0; i != s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
        return buf;
    }

    var currentdate = new Date();
    var datetime = currentdate.getDate() + "/"
                    + (currentdate.getMonth() + 1) + "/"
                    + currentdate.getFullYear();


    saveAs(new Blob([s2ab(wbout)], { type: "" }), "test.xlsx");`
