### ISSUE TITLE
how to append the data to the pre-existing xlsx file

### ISSUE THREAD

**Issue by ShubhamProgrammer** [SheetJS/sheetjs#1535]
problem is with this that on appending the data another time the column name also append into the file , how can i solve this . data  i am taking is in buffer(ws) 
i am iterating the data in the loop and appended on the file.

![Screenshot from 2019-06-13 15-49-52](https://user-images.githubusercontent.com/39419355/59425569-d6185900-8df3-11e9-8c3d-16c481b75f06.png)
 
fs.appendFile(fileName , data,(err)=>{
        if(err){
      return            
        }else{
          console.log('data appended ');
        }
       })

**Comment by SheetJSDev** [comment]
If your data is an array of arrays, you can just call

```js
XLSX.utils.sheet_add_aoa(ws, data, {origin: -1})
```

If you are dealing with row objects, you should first determine the correct order in which keys would be written to the worksheet (say `header` is an array of string keys), then call 
```js
XLSX.utils.sheet_add_json(ws, data, {origin: -1, skipHeader: true, header: header})
```
