### ISSUE TITLE
How to insert rows at the start of a sheet , do not replace data ?

### ISSUE THREAD

**Issue by jonnyshao** [SheetJS/sheetjs#1539]
I am doing
```
const wb = XLSX.utils.table_to_book(document.getElementById('table'))
XLSX.utils.sheet_add_json(wb.Sheets.Sheet1,[rowData],{origin:0})
XLSX.writeFile(wb,'report.xlsx')
```
but work it is replace data.

**Comment by jonnyshao** [comment]
thankful

**Comment by kanatBektursyn** [comment]
Have you found an answer?

**Comment by reviewher** [comment]
To insert rows, you need to move the cells down.  https://github.com/SheetJS/sheetjs/issues/413#issuecomment-456979011 has a sketch for the basic operations

**Comment by kanatBektursyn** [comment]
That is the solution for his case. I was doing the right thing from the first moment.

Found out solution for me was to unbound newly created sheet from any size constraints with:

> `let ws = xlsx.utils.json_to_sheet([{}], {
	    header: ["id", "message", "billing_id"],
	    skipHeader: true
    });`

> `ws[!ref] = "A1:"`
