### ISSUE TITLE
Number with decimal parsed incorrectly

### ISSUE THREAD

**Issue by t-zander** [SheetJS/sheetjs#1543]
I am using in with angular 6.

In xlsx file I have decimal like _9.97_ 
It uses a formula. It looks like this
http://prntscr.com/o4dp5m

For some reason just this column is parsed incorrectly.
Please compare original xlsx and results

9.97    10.564383561643835
0.02    0.6136986301369863
-0.05   0.5397260273972603
-0.05   0.5397260273972603
0.27    0.8684931506849315
...

I could understand first one, but others looks very weird.
May you give any ideas why it may happen and how to fix it? Thanks

**Comment by reviewher** [comment]
If you can share a sample file, we can reopen the issue and take a closer look.
