### ISSUE TITLE
Can I sheet_add_aoa not rewriting the actual data?

### ISSUE THREAD

**Issue by Naryck** [SheetJS/sheetjs#1547]
Problem is in rewriting the data row. I need to make a sheet with couple of merged columns on top of the document. So, I thought it will be better to - first of all - make a document as usual, with header row, and only then add top row which is also a header, but with merges. Something like:
....... car .......... | ......... stuff ........ |
year | model |  color | wheels |

so, I've already made everything starting from 2nd row (in this case year, model, etc) and thousands of rows of data with formulas. Now I want to make a final touch and add the top row with merges, but it overwrites my header row (in this case year, model, etc). And if I try to add 2 rows with both headers, it overwrites first data row. 

Can this be fixed any how?

**Comment by Naryck** [comment]
Also I can't convert it to JSON array, remove last element and convert it back to sheet - all the formulas, for some reason, are gone after this operation

**Comment by SheetJSDev** [comment]
The data for merges are held in the upper-left corner of the merge range.  Skip the intervening indices.  In your example, A1:B1 and C1:D1 are merged, so rewriting the header should skip the B column:

```js
XLSX.utils.sheet_add_aoa(ws, [
  [
    "A1",
    , // skip B1
    "C1"
  ]
], { origin: A1 });
```

This will not disrupt the merge structure and you will have rewritten the headers
