### ISSUE TITLE
Unix Epoch Time to Date

### ISSUE THREAD

**Issue by Arlind-Prosperoware** [SheetJS/sheetjs#1550]
I have some cells that show time in Unix Epoch Format. Im writing this formulae `"unixEpochTime/(24*60*30)+DATE(1970;1;1)"` to convert the Unix time to normal date and also resetting the cell type to "d" but after completion, when trying to open the file it says it's corruped and it needs to be repaired.
After opening the "repaired" version I have to manually go to that cell > Format Cell > Date > select a date type to show the actual date.

**Comment by SheetJSDev** [comment]
If you can share an example file we can take a closer look.  The most likely error source is the function call.  Excel transparently localizes formulae but stores the en-US form in the files.  `DATE(1970;1;1)` should be `DATE(1970,1,1)` since en-US Excel uses commas to separate arguments.
