### ISSUE TITLE
['!cols'] is undefined

### ISSUE THREAD

**Issue by fripso** [SheetJS/sheetjs#1560]
I am trying to modify XLS files and keeping the visibility values for columns. 

I am using ^0.14.3 inside a web worker with Angular ^8.0.0. 

However, whenever I read an XLS file, `['!cols']` is not defined in the worksheet object, even though there are hidden columns in the file. So it is impossible for me to retrieve the 'hidden' values for the columns.

Am I missing something? `!ref` and `!margins` are there.

Here's the web worker code:
```
/// <reference lib="webworker" />

declare function importScripts(...urls: string[]): void;

declare function postMessage(message: any): any;

declare const XLSX: any;

addEventListener('message', ({ data }) => {

    let str = `${data.window.protocol}//path/to/xlsx.full.min.js`;

    importScripts(str);

    const xls = XLSX.read(data.file, { type: 'array' });

    const sheet = xls.Sheets[xls.SheetNames[0]];

    console.log(sheet['!cols']);    // returns undefined

    // (...)

    postMessage(xls);

});

```

Below function sits in a service and spins up a `Worker` for every file from a `FileList`

```
loadXLS(files: FileList, values: {}, loc: string) {
        Array.from(files).forEach(file => {
            const worker = new Worker('../excel.worker.ts', {
                type: 'module'
            });
            const reader: FileReader = new FileReader();
            reader.readAsArrayBuffer(file);
            reader.onloadend = (e: any) => {
                worker.onmessage = ({ data }) => {
                    XLSX.writeFile(data, file.name);
                };
                worker.postMessage({ file: new Uint8Array(e.target.result), locale: loc, val: values, window: this.inputWindow });
            };
        });
    }
```

Here's a branch that provides an implementation example: https://github.com/fripso/kupshred/tree/missingcols

**Comment by reviewher** [comment]
It should always be present in XLS if a column is hidden.  Can you share a sample file?

**Comment by fripso** [comment]
[hidden.xlsx](https://github.com/SheetJS/js-xlsx/files/3395937/hidden.xlsx)

This file has a hidden column B.

![hidden](https://user-images.githubusercontent.com/44230346/61276891-3f9fd480-a7b1-11e9-8bc3-089dceff1035.png)

    console.log(xls.Sheets[xls.Sheetnames[0]]);
Console returns:

    !margins: {left: 0.7, right: 0.7, top: 0.75, bottom: 0.75, header: 0.3, …},
    !ref: "A1:C1",
    A1: {t: "s", v: "Alpha", r: "<t>Alpha</t>", h: "Alpha", w: "Alpha"},
    B1: {t: "s", v: "Beta", r: "<t>Beta</t>", h: "Beta", w: "Beta"},
    C1: {t: "s", v: "Charlie", r: "<t>Charlie</t>", h: "Charlie", w: "Charlie"}

**Comment by cjl-df** [comment]
i also have encountered this porplem.  how to fixed it

**Comment by cjl-df** [comment]
@fripso i have the same proplem;

1.  first,['!cols'] is not defined;seconde.
2. The range is also wrong,onley have one row data.the second and the third row is missing.

![1577347630(1)](https://user-images.githubusercontent.com/3387329/71466467-9860a800-27fa-11ea-8c8d-71e45e041c3d.png)

![1577347662(1)](https://user-images.githubusercontent.com/3387329/71466468-98f93e80-27fa-11ea-8ea6-9c265e2f270a.png)

**Comment by cjl-df** [comment]
i have fixed the second problem.it it because the read the file data by Uint8Array. but the ["!cols"] is still undifined

**Comment by cjl-df** [comment]
![image](https://user-images.githubusercontent.com/3387329/71507306-0a9ac080-28bf-11ea-87cf-7f69a3e7c2c2.png)

i tryed this , and the problem fiexed

**Comment by SheetJSDev** [comment]
@fripso for XLSX format, `cellStyles: true` must be set to extract column metadata.

@cjl-df "range is wrong" is almost always an issue in the file.  XLS has a Dimension record and XLSX also has a way of specifying range, so the reader will set the range based on what that file reports (even if cells exist outside).  We'd be glad to take a look at a sample file if you can share one

**Comment by cjl-df** [comment]
![image](https://user-images.githubusercontent.com/3387329/71566198-98a9bd80-2af0-11ea-92a9-d65a67de5dc9.png)

but how to decide the font style
