### ISSUE TITLE
Add rows to existing excel using javscript

### ISSUE THREAD

**Issue by Deep13** [SheetJS/sheetjs#1563]
I have a requirement where i need to use an excel file and add rows to it and then save it with all the initial formattings intact . XLSX.readFile() gives an error as i am trying it in browser. what else can i use instead for my requirement.

**Comment by harbhub** [comment]
The formatting (styling such as cell border) is only available in the Pro version.  More information on acquiring access to the Pro version can be found here:

http://sheetjs.com/pro

If you don't use the Pro version, then you can still read the Excel file data, add a row to it, and write a new Excel file.  The formatting will be lost in the process, but you will have the new row data appear where expected in the spreadsheet.  Again, if you wish to preserve the formatting, then you will need the Pro version.

**Comment by alemarcha** [comment]
> The formatting (styling such as cell border) is only available in the Pro version. More information on acquiring access to the Pro version can be found here:
> 
> http://sheetjs.com/pro
> 
> If you don't use the Pro version, then you can still read the Excel file data, add a row to it, and write a new Excel file. The formatting will be lost in the process, but you will have the new row data appear where expected in the spreadsheet. Again, if you wish to preserve the formatting, then you will need the Pro version.

How can I do read the Excel file data, add a row to it, and save Excel file?

**Comment by SheetJSDev** [comment]
There is a specific [Pro build](https://sheetjs.com/pro) for editing existing files, but using our community edition you can use `sheet_add_aoa` or `sheet_add_json` with the option `origin: -1`.  To read in the data, you cannot use `XLSX.readFile` in the browser (it leverages node's filesystem support) but you can download a file using `XHR` or `fetch`.  There are numerous examples in the README and in the [demos](https://github.com/SheetJS/sheetjs/tree/master/demos)
