### ISSUE TITLE
Draw circle in a cell 

### ISSUE THREAD

**Issue by TranBaVinhSon** [SheetJS/sheetjs#1568]
Hi, thanks for great package, I have a question about how to draw circle inside a cell or over the value of sell, for example:

Input:
<img width="266" alt="Screen Shot 2019-07-18 at 12 20 54" src="https://user-images.githubusercontent.com/12994069/61426791-98f53880-a956-11e9-893f-945bfcfbcab8.png">
Expect out:
<img width="263" alt="Screen Shot 2019-07-18 at 12 21 26" src="https://user-images.githubusercontent.com/12994069/61426792-98f53880-a956-11e9-9be1-da25150b8c44.png">
Any advice is welcome 👍

**Comment by reviewher** [comment]
Can you share the file for "Expect out"?  Is that a custom font or a diagram?

**Comment by TranBaVinhSon** [comment]
@reviewher Thanks for your reply. I created "Expect out" file for showing only (its a custom font), Actually, there isn't "expect out" file. But basically, I want to draw a circle inside a cell :
1. Get value from a cell, "make a circle" around value and update cell. (cell's value might be a number, character or string)
or
2. Just draw a circle inside a cell: `cell.drawCircle()`
Any help is welcome, thanks in advance 👍

**Comment by TranBaVinhSon** [comment]
For example, I want to put a circle around `昭 5` or a circle inside the cell of `昭 5`, is that possible ?
<img width="167" alt="Screen Shot 2019-07-22 at 12 32 15" src="https://user-images.githubusercontent.com/12994069/61606269-63b55700-ac84-11e9-95de-ef0f65d494b3.png">

**Comment by SheetJSDev** [comment]
If you can produce an excel file with the desired effect, we can take a closer look.
