### ISSUE TITLE
How to read and add new column in excel from angular 4,5,6,7

### ISSUE THREAD

**Issue by dattatrayw** [SheetJS/sheetjs#1570]
I am using this library in my angular 7 application where I am reading data from excel and showing it on UI. Now I want to add one new column name like "feedback" in same excel from angular and want to add data in new added column on specific location. let's say I have user info in excel and want to add feedback from front end against user Id 100.

**Comment by SheetJSDev** [comment]
`XLSX.utils.sheet_add_aoa` and `sheet_add_json` will let you add to the worksheet.  To figure out which column you need, `XLSX.utils.decode_range(ws["!ref"]).e.c + 1`
