### ISSUE TITLE
No result on running XLSX.readFile

### ISSUE THREAD

**Issue by bkr32** [SheetJS/sheetjs#1575]
Hey all, 
just started using XLSX and so far i'ts working great on my node based CLI project,
i've tried porting the functionality over to firebase function to handle it all on the cloud.

problem i'm running into is reading data from my cloud storage,
my function gets the file path and passes it as so

`  const book = XLSX.readFile(tempLocalFile);
  console.log('book data is:', book);`
Output: `{ SheetNames: [ 'Sheet1' ], Sheets: { Sheet1: {} } }`

`const book = XLSX.read(tempLocalFile);
  console.log('book data is:', book);`
`{ SheetNames: [ 'Sheet1' ],
  Sheets: { Sheet1: { A1: [Object], '!ref': 'A1' } } }`

is there something i'm missing or doing wrong thanks

**Comment by SheetJSDev** [comment]
You can pass the option `WTF:1` to the read function:

```js
const book = XLSX.read(tempLocalFile, {WTF:1});
```

which should give a more meaningful error message

**Comment by SheetJSDev** [comment]
Please update to the latest version and follow up if the issue persists.
