### ISSUE TITLE
Date from .txt with DD-MM-YYYY format turn to YY-MM-YYDD

### ISSUE THREAD

**Issue by jbmontecristo** [SheetJS/sheetjs#1576]
Hi.
I have an issue when I do conversion from a txt file to sheetJS. With this specific date format dd-mm-yyyy (with dash between numbers and not slash)  my result is yy-mm-yydd. 
For exemple 26-07-2019 become 19-07-2026.
I don't know if this have been already reported.

**Comment by gcarpi** [comment]
Did you find a solution?

**Comment by jbmontecristo** [comment]
> Did you find a solution?

Not yet

**Comment by reviewher** [comment]
`Date.parse("26-07-2019")` is `NaN` so this error is weird.  If you have a sample file, please share it.
