### ISSUE TITLE
xlsx to nested JSON

### ISSUE THREAD

**Issue by nicolasgirado** [SheetJS/sheetjs#1591]
Is it possible to read a xlsx file and convert it to a nested JSON?  (i'm using node.js)

For example, this table:

**Name**	| **City** 		| **Country**
Jon	        | New York 	| USA
Jon	        | Kansas	        | USA
Peter 	| Nevada	        | USA

to this JSON:

```json
{
   "Name": "Jon",
   "Addresses": [
              {"City": "New York", "Country": "USA"},
              {"City": "Kansas", "Country": "USA"}
           ]
},
{
   "Name": "Peter",
   "Addresses": [
              {"City": "Nevada", "Country": "USA"}
	  ]
}
```

**Comment by RandomFractals** [comment]
how would xlsx or any other library know how you'd like to nest your flat md data in exported json properties?

You can try to mock it up with Data Preview 🈸 vscode extension that supports xlsx files loading, md tables parsing and save as json + grouping :) 

https://github.com/RandomFractals/vscode-data-preview

**Comment by RandomFractals** [comment]
otherwise, just transform the json you get from xlsx sheet to json to the structure you prefer looping over json array records and adding/modifying/deleting flat data object properties. should be aesy custom forEach loop :)

**Comment by RandomFractals** [comment]
@nicolasgirado see I handle it in my `excel.data.provider` for example and just add your json transform structure as needed :) 

https://github.com/RandomFractals/vscode-data-preview/blob/master/src/data.providers/excel.data.provider.ts

**Comment by ahmad-reza619** [comment]
well it's pretty good example, but i can't really understand this (sorry, just a beginner programmer lol) @RandomFractals , i have a multinested js object and i don't know how to transform it

**Comment by RandomFractals** [comment]
@ahmad-reza619  see `saveData()` to convert json to one of the supported Excel data formats with xlsx-js library and write it to disk with nodejs fs (file system api): https://github.com/RandomFractals/vscode-data-preview/blob/master/src/data.providers/excel.data.provider.ts#L108

**Comment by ahmad-reza619** [comment]
OK thanks for explanation 👍 @RandomFractals

**Comment by reviewher** [comment]
As @RandomFractals discussed, there's no simple general solution but you can always massage the output of `sheet_to_json` e.g.

```js
var wb = XLSX.readFile("file.xlsx");
var data = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
var result = data.reduce((acc, row) => {
  var target = acc.find(x => x.Name == row.Name);
  if(!target) acc.push((target = {Name: row.Name, Addresses: [] }));
  target.Addresses.push({City: row.City, Country: row.Country});
}, []);
```
