### ISSUE TITLE
readFile returns sheets empty despite a sheetName: parser fails for the firts rows that are one big cell

### ISSUE THREAD

**Issue by stcursi** [SheetJS/sheetjs#1593]
As I wrote, the parser fails during the reading (readFile without options) because the first 14 rows are a single big cell ( I can't delete these rows manually because the excel is programmatically downloaded with an url ). 

this is the result: 

{
  "Directory": {
    "workbooks": [
      "/workbook.xml"
    ],
    "sheets": [
      "/xl/worksheets/data.xml"
    ],
  
  "Workbook": {
    *******
  "Props": {
    "**Worksheets**": 1,
    "**SheetNames**": [
      "Data"
    ]
  },
  "Custprops": {},
  "Deps": {},
  "Sheets": {},
  "SheetNames": [
    "Data"
  ],
  "Strings": [],
  "Styles": {
    *******
  },
}

as you can see there is a sheetName ( Data ) but not the content ( Sheets {} is empty ). I tried with an excel without the first 14 rows and everything went well. 

How can I avoid the first lines ? 

Thanks

**Comment by SheetJSDev** [comment]
That looks like a failed parse, can you read with the option `WTF: 1` and see if an error is thrown?

**Comment by stcursi** [comment]
> That looks like a failed parse, can you read with the option `WTF: 1` and see if an error is thrown?

This is the error thrown with wtf : 1 

Message: "unrecognized <workbookView/> in workbook",

stack: "Error: unrecognized <workbookView/> in workbook
    at xml_wb (.../node_modules/xlsx/xlsx.js:13475:41)
    at String.replace (<anonymous>)
    at parse_wb_xml (..../node_modules/xlsx/xlsx.js:13337:7)
    at parse_wb (.../node_modules/xlsx/xlsx.js:13852:9)
    at parse_zip (...node_modules/xlsx/xlsx.js:18581:11)
    at read_zip (.../node_modules/xlsx/xlsx.js:18866:9)
    at readSync (.../node_modules/xlsx/xlsx.js:18931:69)
    at Object.readFileSync (.../node_modules/xlsx/xlsx.js:18945:9)
    at Object.readFile [as parseExcelGeneral] (.../server/utils/excelManager.js:218:33)
    at parseExcelGeneral (.../server/utils/googleApiManager.js:283:54)"

**Comment by stcursi** [comment]
I can add more clues ... Now I saw that if I open and close ( with saving it ) manually, after that xlsx can read clearly the data sheet.

**Comment by SheetJSDev** [comment]
Can you check what version you're running?  `console.log(XLSX.version)`.  If it's the latest (0.15.0) please share that offending file, feel free to email us directly if you don't want to share publicly.

**Comment by stcursi** [comment]
No I'm using the version 12.x.x

**Comment by ac3ju** [comment]
Did you find ?

**Comment by schemacs** [comment]
@SheetJSDev 
```js
const XLSX = require('xlsx');
const workSheet = XLSX.read(fs.readFileSync("/tmp/large.xlsx"), {})
console.log(Object.keys(workSheet.Sheets), workSheet.SheetNames);
```

The same xlsx file(~ 39M) works on `Node v12.20.0/xlsx@0.17.0`
```
[ 'sheet1' ] [ 'sheet1' ]
```

fails on Node v8.4.0/xlsx@0.17.0
```
[] [ 'sheet1' ]
```

[Here](https://github.com/mgcrea/node-xlsx/blob/b85dcc863a46bd8004169ad72626516407004dbc/src/index.js#L8) is an example calling `Object.keys(workSheet.Sheets)`.

**Comment by SheetJSDev** [comment]
@stcursi @juliengloria  The original error regarding `workbookView` was resolved in 0.12.11

@schemacs  NodeJS versions around 8.3.0 had massive performance issues, which would explain why it is failing.  https://github.com/nodejs/node/issues/18218 is a longer discussion and links to the V8 bug tracker https://bugs.chromium.org/p/v8/issues/detail?id=7326

**Comment by AprilTong** [comment]
It says:
RangeError: Array buffer allocation failed

and the file is only 5kb.

**Comment by SheetJSDev** [comment]
Best guess is that it uses ZIP64 extensions (see #2766).  Try updating to the latest version (https://docs.sheetjs.com/docs/getting-started/#installation).  If the issue still persists, please share the file

**Comment by AprilTong** [comment]
The version I am using is 0.18.5. 
It says:
RangeError: Array buffer allocation failed

The error file is:

[默认值_20221019143043.xlsx](https://github.com/SheetJS/sheetjs/files/9818194/_20221019143043.xlsx)

**Comment by SheetJSDev** [comment]
This works in 0.18.12.  You can test with https://oss.sheetjs.com/

You will need to update.  Follow the instructions https://docs.sheetjs.com/docs/getting-started/#installation

**Comment by AprilTong** [comment]
I tried it successfully, thank you, looking forward to publishing to npm soon.

**Comment by AprilTong** [comment]
> This works in 0.18.12. You can test with https://oss.sheetjs.com/
> 
> You will need to update. Follow the instructions https://docs.sheetjs.com/docs/getting-started/#installation

I tried it successfully, thank you, looking forward to publishing to npm soon.

**Comment by jonathan-wondereur** [comment]
Any news on when 0.18.12 will be published to NPM?
