### ISSUE TITLE
Reading a few excel rows takes so much time

### ISSUE THREAD

**Issue by devkarim** [SheetJS/sheetjs#1604]
Greetings,

I've run against an issue where the reading operation takes so much time even though the excel file contains only a few rows. I'm building a Photoshop project or in other words, a Photoshop script but it seems Photoshop gets frozen/stuck forever whenever it tries to read the file. I'm using the demo stated on the main page.

```javascript
#include "./xlsx.extendscript.js"

var workbook = XLSX.readFile('whateverpath');
var first_sheet_name = workbook.SheetNames[0];
var first_worksheet = workbook.Sheets[first_sheet_name];
var data = XLSX.utils.sheet_to_json(first_worksheet, {header:1});

$.writeln(data)
```

Excel file: [TestInput.xlsx](https://github.com/SheetJS/js-xlsx/files/3512460/TestInput.xlsx)

Any clue?

**Comment by A1rPun** [comment]
You have to [pay](http://sheetjs.com/pro) for 'performance enhancements'.

**Comment by SheetJSDev** [comment]
What version of photoshop are you using and are you testing against the latest build?

**Comment by devkarim** [comment]
> What version of photoshop are you using and are you testing against the latest build?

Photoshop CS6. Yes, I'm testing with the latest build. By the way, it doesn't have anything to do with Photoshop since I used ExtendTool just to make sure it's not a Photoshop issue and it wasn't the issue like I guessed.

**Comment by reviewher** [comment]
Extreme compression

```
$ unzip -lvv TestInput.xlsx 
Archive:  TestInput.xlsx
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     718  Defl:N      238  67% 08-17-2019 21:47 9a349a85  _rels/.rels
     752  Defl:N      376  50% 08-17-2019 21:47 696a5802  docProps/core.xml
     410  Defl:N      258  37% 08-17-2019 21:47 5250c343  docProps/app.xml
     939  Defl:N      321  66% 08-17-2019 21:47 1ba9b439  docProps/custom.xml
    7411  Defl:N     1021  86% 08-17-2019 21:47 ece7405e  xl/styles.xml
     880  Defl:N      507  42% 08-17-2019 21:47 5c8f9a34  xl/workbook.xml
    1581  Defl:N      582  63% 08-17-2019 21:47 5e352553  xl/sharedStrings.xml
     549  Defl:N      210  62% 08-17-2019 21:47 7af9f04f  xl/_rels/workbook.xml.rels
    1492  Defl:N      353  76% 08-17-2019 21:47 faac49a7  [Content_Types].xml
  693495  Defl:N    23621  97% 08-17-2019 21:47 5cc8266f  xl/worksheets/sheet1.xml
--------          -------  ---                            -------
  708227            27487  96%                            10 files
```

693K compressed down to 23K

**Comment by reviewher** [comment]
ExtendScript just can't handle large arrays or large strings.  Try:

```extendscript
var out = [1,2,3,4,5,6];
for(var i = 0; i < 700000; ++i) {
    out[i+6] = out[i];
    if((i % 1000) == 0) $.writeln(i);
}
```

Even after setting `$.memCache = 1024*1024*1024*2` ExtendScript slows down after 100K and basically stops after 250K.
