### ISSUE TITLE
How to use XLSX to download nested forms

### ISSUE THREAD

**Issue by ISBN9527** [SheetJS/sheetjs#1605]
![image](https://user-images.githubusercontent.com/30942709/63400350-0ee13980-c406-11e9-9904-9e8758081832.png)

- this is nested forms,How do I download this nested subtable？Please give advice or comments

**Comment by wangchong19940101** [comment]
@SheetJSDev

**Comment by SheetJSDev** [comment]
Nested tables are not supported in Excel, and there's no natural way of representing a nested HTML table like that within a grid. If you can share an example Excel file we can take a closer look.
