### ISSUE TITLE
Add Data Preview 🈸 vscode extension to xlsx ecosystem demos in docs

### ISSUE THREAD

**Issue by RandomFractals** [SheetJS/sheetjs#1607]
since I am using your library for all the Excel data files loading, transforming and saving, and I believe other developers can use that data tool in code IDE utilizing your library or check out the source code behind for loading and saving different Excel data files with it:

https://github.com/RandomFractals/vscode-data-preview#data-preview--files-loading-details

Perhaps add it under **Platforms and Integrations** list section or create new IDE Tools category in your docs:

https://github.com/SheetJS/js-xlsx#js-ecosystem-demos

Let me know if you need more info.

Data Preview 🈸 repo: https://github.com/RandomFractals/vscode-data-preview

VSCode Marketplace link: https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview

P.S.: 👀 my `excel.data.provider` impl. for the nitty gritty details: 

https://github.com/RandomFractals/vscode-data-preview/blob/master/src/data.providers/excel.data.provider.ts

any comments on how to improve that api or `Excel` data files loading & saving you support would be much appreciated! 🤗

P.P.S.: I think most devs using your library can probably just grab that data provider implementation and plop it in their nodejs webapps. Part of the reason I've decided to make that data ext. in the 1st place too.

**Comment by SheetJSDev** [comment]
Awesome idea!  Each of those demos consists of a small writeup (README.md) and a small example.  The writeup covers the integration logic between the library and the application.  The [`chrome`](https://github.com/SheetJS/js-xlsx/tree/master/demos/chrome) example is a good starting point for understanding what we try to do with the demos.

It would probably make the most sense to add a general `Visual Studio Code` demo.  Ideally the demo in the repo should show the bare minimum to read and/or write files (whichever is easier), but that's not necessary as long as a README explains what is necessary at a high level.

We'd accept a PR with a simple `demos/vscode/README.md` that mentions vscode extensions have access to the filesystem via the `fs` module (are there any special permissions required? Chrome extensions require you to request `downloads` permission) and you can simply read/write Buffers.  Link to your entry in the marketplace as well as your repo.

PS: do you have an opencollective or other way to accept donations?

**Comment by RandomFractals** [comment]
will send you a PR with a separate md. on that ext.

In process of setting up some donations pages for it :)

https://github.com/RandomFractals/vscode-data-preview/issues/118

happy to hear you like our works utilizing your lib so far! 

🚀🚀🚀

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/tree/master/demos/showcase
