### ISSUE TITLE
missing new line character when parsing xlsx-files

### ISSUE THREAD

**Issue by BarSah** [SheetJS/sheetjs#1609]
After some updates of browsers (Chrome 75, Firefox 68) all cells data is not separated by new line character( chr(10) when parsing xlsx-files. All cells data is in one line.
Example: L4='CityB5='1. streetL5='buildingB6='floorC6='aptmt

Meanwile in Chrome 68 all works fine:
L4='City
B5='street
L5='building
B6='floor
C6='aptmt

**Comment by SheetJSDev** [comment]
`sheet_to_formulae` (née `get_formulae`) always returned an array of lines. Likely Chrome/Firefox changed how arrays are printed in the console.
