### ISSUE TITLE
Cannot parse excel in IE 10 and IE 11

### ISSUE THREAD

**Issue by sylfree9999** [SheetJS/sheetjs#1620]
I've tested the page: https://sheetjs.com/sexql/index.html

When in IE(both 11 and 10), the page will throw Network Error. I don't know why this happens. This page works fine in chrome.
<img width="714" alt="Snipaste_2019-09-12_11-59-27" src="https://user-images.githubusercontent.com/15099465/64753161-cb857100-d554-11e9-9dae-3a6260619ff5.png">

**Comment by tommypeterz** [comment]
I don't even get that far as an error message in IE11...

The page works fine in Chrome here as well, but in IE11 it just hangs after drag-dropping the file.

**Comment by tommypeterz** [comment]
Can be something with the file opening itself, for instance file save in https://sheetjs.com/demos/table.html works as well in IE11.

**Comment by SheetJSDev** [comment]
That error is in the web worker script on the line

```js
importScripts('//unpkg.com/xlsx/dist/xlsx.full.min.js');
```

It was most likely an issue with SSL certs or something that caused the request to fail.  Local testing suggests it is working properly.
