### ISSUE TITLE
[0.15.1] - sheet_to_json no longer correctly converts dates to JS dates

### ISSUE THREAD

**Issue by spradlin-dev** [SheetJS/sheetjs#1623]
We upgraded to 0.15.1 to get the minified version of xlsx into our build, but immediately tests started failing. When parsing an excel file to JSON, XLSX used to return the date string "01/01/18", but now returns the corresponding Excel date number `43101`.

 Eventually we determined that XLSX.utils.sheet_to_json was parsing dates as their excel date value.  `01/01/18` is now parsed as `43101`, which, when converted to a date, it is assumed as unix time of `43101`, so 43,101 seconds after Midnight, January 1, 1970.

We have had to revert back to 0.13.5 to get our thousands of tests passing again.

**Comment by g6ling** [comment]
You can use `new Date(1000*60*60*24*(43101-25569))`. I don't know where 25569 from. but this works

**Comment by SheetJSDev** [comment]
@spradlin-dev yes the `raw` default flipped in 0.15.0

@g6ling JS `0` date is the unix epoch (January 1 1970) but Excel's `0` date is January 1 1900 (hence the need to subtract the 70 years).  The other confounding factor is [1900 leap year bug](https://en.wikipedia.org/wiki/Leap_year_problem#Occurrences) which affects February 29 1900 (Excel thinks it exists but JS does not)
