### ISSUE TITLE
Don't support 'charCodeAt' method  in IE11

### ISSUE THREAD

**Issue by hengchengfei** [SheetJS/sheetjs#1624]
I had added the shim.js as follows:
```js
<script src="shim.js"></script>
<script src="jszip.js"></script>
<script src="xlsx.js"></script>
```

<img width="282" alt="1" src="https://user-images.githubusercontent.com/3182964/64921388-453b8a00-d7f5-11e9-94a5-05758f35d000.png">
<img width="516" alt="2" src="https://user-images.githubusercontent.com/3182964/64921390-4c629800-d7f5-11e9-864a-9282a832c121.png">

**Comment by SheetJSDev** [comment]
Do you see the same error when using the full build https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.full.min.js ? If so, can you share more (are you trying to read or write? can you show a stack trace?)

**Comment by stanleyxu2005** [comment]
Dear all, 

I have the same error here. It turns out binary string is not converted correctly.

Here is my current workaround. Hope it helps.
```
        const bytes = new Uint8Array(e.target.result)
        let bstr = ''
        bytes.forEach((byte) => {
          bstr += String.fromCharCode(byte)
        })
```

**Comment by SheetJSDev** [comment]
Use the bundled browser script.  Please reopen if the issue persists using that script instead:

```js
<script src="shim.min.js"></script>
<script src="xlsx.full.min.js"></script>
```
