### ISSUE TITLE
Reading a list of CSV files will result in a blank line

### ISSUE THREAD

**Issue by sliently** [SheetJS/sheetjs#1625]
Reading a list of CSV files will result in a blank line
funtion 
```
xlsx.read(buffer, {
       type: 'binary',
       raw: true
}
```

**Comment by SheetJSDev** [comment]
Can you share what `buffer` actually is?  Is it a string?  when type is `binary` the input is expected to be a string whose character codes are between 0 and 255

**Comment by reviewher** [comment]
Please follow up with some more details and we can reopen
