### ISSUE TITLE
Issue with reading a single column csv

### ISSUE THREAD

**Issue by kirupakaranh-opex** [SheetJS/sheetjs#1629]
While reading a csv file, if the csv file contains a single column and if the header contains more than 10 characters with space, the column is split into two.

For eg:
If column name is "sepal length", it is read as ["sepal leng", "th"]
~On examining your code, I found that function prn_to_aoa_str defined in xlsx.js to be cause of this issue.~

Edit: I was wrong. If the file doesn't have tabs or comma, file is read as a prn file. Can you add any delimiter option for csv?

**Comment by sachingoel** [comment]
I'm also facing the same issue. :(

**Comment by SheetJSDev** [comment]
This should have been fixed in the latest version (the PRN processing is disabled).  Please confirm you are using a version above "0.16.2"

**Comment by sachingoel** [comment]
Thanks.
It is fixed in latest version :)
