### ISSUE TITLE
XLSX.read method not giving the proper xsl object while sending the base 64 string

### ISSUE THREAD

**Issue by kantmani4** [SheetJS/sheetjs#1631]
@SheetJSDev :

Hi Team , 

I have used your method:

XLSX.read and passed base 64 string . In the response it is not parsing properly and giving worng data.

Below is the code:
<input type="file" name ="file" onChange={(e)=>this.onChange(e)}/>

 onChange(e) {
var files = e.target.files;
var reader = new FileReader();
reader.readAsDataURL(files[0]);
reader.onload=(e)=>{
    const workbook = XLSX.read(e.target.result, { type: "base64" });
console.log(workbook);
}

Test.xlsx : I have uploaded 
Base64 : I have converted into base 64 string
ParsedError.docs:  It contains screenshot after the parsing. It seems your method is not working as expected. Can you please help me what I am doing wrong.

[Test.xlsx](https://github.com/SheetJS/js-xlsx/files/3628627/Test.xlsx)
[Bae64.txt](https://github.com/SheetJS/js-xlsx/files/3628629/Bae64.txt)
[ParsedError.docx](https://github.com/SheetJS/js-xlsx/files/3628635/ParsedError.docx)

**Comment by reviewher** [comment]
Strip out the data header with

```js
const data = e.target.result;
const workbook = XLSX.read(data.slice(data.indexOf(",")+1), { type: "base64" });
```
