### ISSUE TITLE
Content was lost 

### ISSUE THREAD

**Issue by jiangsongnian** [SheetJS/sheetjs#1634]
the table (code) is :    

<table id="formats-table">
        <thead>
        <tr>
            <th rowspan="2"><div><span>Name</span></div></th>
            <th colspan="2">detail</th>
            <th rowspan="2">Salary</th>
        </tr>
        <tr>
            <th>Position</th>
            <th>Age</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Thor Walton</td>
            <td>Regional Director</td>
            <td>45</td>
            <td>$98,540</td>
        </tr>
        <tr>
            <td>Travis Clarke</td>
            <td>Software Engineer</td>
            <td>30</td>
            <td>$275,000</td>
        </tr>
        <tr>
            <td>Suki Burks</td>
            <td>Office Manager</td>
            <td>22</td>
            <td>$67,670</td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <td class="disabled"></td>
            <td class="disabled"></td>
            <td class="disabled"></td>
            <th>$441,210</th>
        </tr>
        </tfoot>
    </table>

when export table to .xlsx,  the cell(3,2) is empty! It's wrong , it ought to 'Age'.

![Screenshot_2019-09-21 Formats](https://user-images.githubusercontent.com/10644819/65368110-d9cb3f80-dc6e-11e9-913e-60027c56b917.png)
<img width="350" alt="2019-09-21_125455" src="https://user-images.githubusercontent.com/10644819/65368154-c076c300-dc6f-11e9-80a2-50a9dcf7b1a1.png">

**Comment by reviewher** [comment]
This must have been fixed at some point, please upgrade to the latest version.  Both the raw html string (`XLSX.read`) and the table (`XLSX.utils.table_to_book`) generate the correct shape including the "Age" field
