### ISSUE TITLE
error happened when open exported table with Mutiple row Header 

### ISSUE THREAD

**Issue by jiangsongnian** [SheetJS/sheetjs#1635]
hi team:
when I user exporttable to export table to xlsx, I found a error : 
the table (code) is:
<table id="formats-table">
        <thead>
        <tr>
            <th rowspan="4" colspan="1">A</th>
            <th rowspan="1" colspan="4">A</th>
            <th rowspan="1" colspan="4">I</th>
        </tr>
        <tr>
            <th rowspan="3" colspan="1">C</th>
            <th rowspan="1" colspan="3">D</th>
            <th rowspan="1" colspan="1">J</th>
            <th rowspan="1" colspan="3">K</th>
        </tr>
        <tr>
            <th rowspan="2" colspan="1">E</th>
            <th rowspan="1" colspan="1">F</th>
            <th rowspan="2" colspan="1">H</th>
            <th rowspan="1" colspan="1">L</th>
            <th rowspan="2" colspan="1">M</th>
            <th rowspan="1" colspan="1">N</th>
            <th rowspan="1" colspan="1">O</th>
        </tr>
        <tr>
            <th rowspan="1" colspan="1">G</th>
            <th rowspan="1" colspan="1">P</th>
            <th rowspan="1" colspan="2">Q</th>
        </tr>
        </thead>
        <tbody>
        <tr>
			<td>1</td>
			<td>2</td>
			<td>3</td>
			<td>4</td>
			<td>5</td>
			<td>6</td>
			<td>7</td>
			<td>8</td>
			<td>9</td>
        </tr>
        <tr>
			<td>11</td>
			<td>22</td>
			<td>33</td>
			<td>44</td>
			<td>55</td>
			<td>66</td>
			<td>77</td>
			<td>88</td>
			<td>99</td>
		</tr>
        <tr>
			<td>R1</td>
			<td>R2</td>
			<td>R3</td>
			<td>R4</td>
			<td>R5</td>
			<td>R6</td>
			<td>R7</td>
			<td>R8</td>
			<td>R9</td>
		</tr>
       </tbody>
    </table>
<img width="474" alt="1" src="https://user-images.githubusercontent.com/10644819/65368935-8d393180-dc79-11e9-8bcd-fc0c89e2f0dd.png">

export to xlsx, no error happened ,  but when open the xlsx file , error happened .
tips excel will repair the file， after the file was repaired and opend , 
content is:
<img width="333" alt="2" src="https://user-images.githubusercontent.com/10644819/65368938-91fde580-dc79-11e9-8879-7bb6c172b008.png">

some cell mergered was wrong!
<img width="583" alt="4" src="https://user-images.githubusercontent.com/10644819/65368956-c1145700-dc79-11e9-895c-a353708984a5.png">

<img width="549" alt="5" src="https://user-images.githubusercontent.com/10644819/65368984-63343f00-dc7a-11e9-8e97-4206d9993c66.png">

After modified the error content merger content in BB.xlsx\xl\worksheets\sheet1,the xlsx file opened without error ,but the content is still wrong!

<img width="561" alt="3" src="https://user-images.githubusercontent.com/10644819/65369075-5e23bf80-dc7b-11e9-92a9-6ce9978997f4.png">

**Comment by reviewher** [comment]
This was fixed at some point, demo https://jsfiddle.net/mw70zktg/
