### ISSUE TITLE
cannot open 2 line xlsx in Excel 365

### ISSUE THREAD

**Issue by mariomuja** [SheetJS/sheetjs#1641]
I cannot open a simple 2 line xlsx in 

Excel 365 MSO 16.0.11929.20288 64 bit 

I created the XLSX using these lines of Typescript:

        const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(**json**);
        const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
        const buffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'buffer' });
        const readable = this.getReadable(buffer);

The buffer is converted to a Readable using these lines:
  
    // transform a buffer to a stream
    private getReadable(buffer: Buffer): Readable {
        const readable = new Readable();
      
        readable.push(buffer);
        readable.push(null);
      
        return readable;
    }

Then the stream is sent back to the client (Postman in my case) using this line:
 
   readable.pipe(res);

When I save the resulting response in Postman to a file, then Excel shows the following message on file open:

"We found a problem with some content in file.xlsx. Do you want us to try to recover as much as we can? If you trust the source of the workbook, click yes."

How can I avoid this and create the file so that Excel can open it?

If I replace 'xlsx' in the code above with 'xlsb', then Excel can open the binary file without the warning. The problem only occurs with XLSX file type.

It is strange that XLSX.utils.json_to_sheet does not accept a string with JSON content (e.g. created with JSON.stringify). The method only accepts an array but no JSON content - therefore I find the name of the method misleading - it is not transforming JSON to a sheet, but it transforms an array to a sheet, right?

Thanks a lot for your help!
Mario

**json** looks as follows:

[ [ 'object_id',
    'name',
    'column_id',
    'system_type_id',
    'user_type_id',
    'max_length',
    'precision',
    'scale',
    'is_nullable',
    'is_ansi_padded',
    'is_rowguidcol',
    'is_identity',
    'is_computed',
    'is_filestream',
    'is_replicated',
    'is_non_sql_subscribed',
    'is_merge_published',
    'is_dts_replicated',
    'is_x005F_xml_document',
    'xml_collection_id',
    'default_object_id',
    'rule_object_id',
    'is_sparse',
    'is_column_set',
    'generated_always_type',
    'generated_always_type_desc',
    'is_hidden',
    'is_masked' ],
  [ '3',
    'rsid',
    '1',
    '127',
    '127',
    '8',
    '19',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    '0',
    'NOT_APPLICABLE',
    '0',
    '0' ] ]

**Comment by SheetJSDev** [comment]
Can you share the generated XLSX file (the one that is causing problems)?

**Comment by reviewher** [comment]
It's most likely an integration issue.  Please reopen if you can share the file.
