### ISSUE TITLE
table_to_book handling with decimals and raw data.

### ISSUE THREAD

**Issue by jardsticsay** [SheetJS/sheetjs#1647]
Is it possible to export the table to excel retaining the raw data value and converting cell value up to two decimal values.
Like this one in photo:
![image](https://user-images.githubusercontent.com/36289597/65955640-30105d80-e47b-11e9-9f85-00ed619a96ba.png)

**Comment by reviewher** [comment]
Set the `data-z` property of the cell to `0.00` in order to force the number format.  `data-v` is a bypass to store the raw numeric value and `data-t` for type:

```html
<td data-z="0.00" data-v="1373.68" data-t="n">1373.68</td>
```
