### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by hdshariati** [SheetJS/sheetjs#1649]
I'm wondering about correct sorting in Persian. in most situation you must rewrite a function to sort base on persian alphabet (because of conflict with arabic).
how and where did you handle this method?

**Comment by SheetJSDev** [comment]
No part of the library requires sorting according to the Persian or any other alphabet.  The only spec-mandated sorting is for the red-black tree construction in CFB (BIFF8 XLS container format) and that sort is based on the code points, not by alphabet.
