### ISSUE TITLE
Specify delimiter when parsing CSV document

### ISSUE THREAD

**Issue by asaheba93** [SheetJS/sheetjs#1651]
- Specify record and field separators to support multi-character delimiters for parsing CSV and text documents.
- Ex: Delimiter can be a few characters such as "~|~" (tab, pipe, tab)

**Comment by Corchoneitor** [comment]
+1

**Comment by Fabiomad85** [comment]
any update?

**Comment by SheetJSDev** [comment]
Pass the `FS` option to `read` or `readFile` in 0.17.4:  https://jsfiddle.net/yen3q60o/1/

```js
const csv = "1,2|3,4\t5,6|7,8\nEOF";
const doit = (str, delim) => {
	var ws = XLSX.read(str, {type: "string", FS: delim, raw: true}).Sheets.Sheet1;
	console.log(ws["A1"].v);
};

[",", "|", "\t"].forEach(c => doit(csv, c));
```

The output is:

```
1
1,2
1,2|3,4
```
