### ISSUE TITLE
when use sheet_to_json,  how to ingore formula cells  if there's no value set

### ISSUE THREAD

**Issue by xiaoxiongzi** [SheetJS/sheetjs#1654]

**Comment by still1107** [comment]
您好，很冒昧的在这里向您请教问题，我想要导出xlsx，其实有一个数据是百分数，我想要导出excel中的格式类型是百分数，不知道应该怎么写，期待您的回复。

**Comment by SheetJSDev** [comment]
If no value is set (undefined), `sheet_to_json` will skip the cell (even if the cell has a formula)

@still1107 If you are asking about percentage format, set the `z` property of the cell objects to `0%` for integer percentage and `0.00%` for 2 decimal places
