### ISSUE TITLE
how to read the styles

### ISSUE THREAD

**Issue by zhouzefei** [SheetJS/sheetjs#1658]
Excuse me!  How to read the styles in the json? I want to render it on the web. Thanks!

![image](https://user-images.githubusercontent.com/8566935/67202863-3b342900-f43c-11e9-813e-39c2fd6466c6.png)
![image](https://user-images.githubusercontent.com/8566935/67198059-bc85be80-f430-11e9-96ba-e4c0eb5d567c.png)

**Comment by MelvinVermeer** [comment]
To read the styling you'll need the PRO version of this library. If you have that you can tell the API to read the styling when parsing the workbook. Here is an example (nodejs) :

```javascript
const fileName = 'Book1.xlsx'; // Excel file with styling

const options = {
  cellStyles: true,
};

const filePath = path.join(process.cwd(), fileName);
const workbook = XLSX.readFile(filePath, options);
```

When working with the workbook object every cell contains a `.s` property that hold information about the styling.

**Comment by SheetJSDev** [comment]
Cell styling is part of our Pro offering, see https://sheetjs.com/pro for more info
