### ISSUE TITLE
Excel cannot change cell (number) format for new sheet

### ISSUE THREAD

**Issue by marmz** [SheetJS/sheetjs#1662]
When i **modify XLS file** in JS, then open with program (with Excel or LibreOffice Calc), number formats are changed back to US default, instead my original file had:

`ThousandSeparator: '.'` and  `DecimalSeparator: ','` .

In addition, *nor Excel or LibreOffice Calc can change my cell formats* anymore! :(
But the file is not protected or read-only, i can change values, save file, or copy all data to a new document, but **no way** of changing (number) formats.

**Comment by SheetJSDev** [comment]
Can you share the original and modified files?  Also what are your current computer locale settings?

**Comment by marmz** [comment]
Sure!  :) 

Here  the SOURCES:
1. https://drive.google.com/file/d/14SI9E2dhzqknoQ3pTV_BbgEsICdp7RI5/view?usp=drivesdk
2. https://drive.google.com/file/d/14_CqjolZhr02b-ElcajO9KeudRBSeL4v/view?usp=drivesdk

Here  the RESULT:
- https://drive.google.com/file/d/14epDz5oMAfqfnC1p1X2VmnMMUu-w-0OC/view?usp=drivesdk

As you can see, the first two files have formats most like `#.##0,00`, but when merged numbers seem to fall back to standard `#,##0.00`.
I tried to set format programmatically before saving back result file, but no way :(
Same happens if I try to change format after creating the file, using Excel or similar.. 
XLS or XLSX makes no difference in this issue.
I am offering a prize in beers (or what you like most) for anyone who has a solution to this.. I SWEAR IT 😅

**Comment by SheetJSDev** [comment]
The first two files have standard US "#,##0.00" format.  Here's google sheets preview of the first file:

![](https://i.imgur.com/Udo7lSp.png)

To see the actual formats in the file, you can make the following change to 
[`/bits/76_xls.js` and rebuild](https://github.com/SheetJS/sheetjs/blob/master/bits/76_xls.js):

```diff
@@ -497,6 +497,7 @@ function parse_workbook(blob, options/*:ParseOpts*/)/*:Workbook*/ {
                                        sst = val;
                                } break;
                                case 'Format': { /* val = [id, fmt] */
+                                       console.log(val);
                                        if(opts.biff == 4) {
                                                BIFF2FmtTable[BIFF2Fmt++] = val[1];
                                                for(var b4idx = 0; b4idx < BIFF2Fmt + 163; ++b4idx) if(SSF._table[b4idx] == val[1]) break;
```

Then you will see the actual formats in the file:

```js
[ 5, '"$"#,##0_);("$"#,##0)' ]
[ 6, '"$"#,##0_);[Red]("$"#,##0)' ]
[ 7, '"$"#,##0.00_);("$"#,##0.00)' ]
[ 8, '"$"#,##0.00_);[Red]("$"#,##0.00)' ]
[ 42, '_(* #,##0_);_(* (#,##0);_(* "-"_);_(@_)' ]
[ 41, '_("$"* #,##0_);_("$"* (#,##0);_("$"* "-"_);_(@_)' ]
[ 44, '_(* #,##0.00_);_(* (#,##0.00);_(* "-"??_);_(@_)' ]
[ 43, '_("$"* #,##0.00_);_("$"* (#,##0.00);_("$"* "-"??_);_(@_)' ]
```

Notice how all of them are spelled out with US-style separators?  That's because Excel interprets them with a specific locale.

How did you view the original file?  What version of Excel and what are the locale settings on your computer?

**Comment by SheetJSDev** [comment]
The locale, time zone and other metadata from the last user to save the file are not stored in the XLS file.  The only optional info is country code (stored in the Country record) but that is insufficient to determine the row and field separators.

As a result, Excel and Calc's behavior depend on the system of the user opening the file.  It is not tunable by the software writing the XLS file.
