### ISSUE TITLE
Blank cell is not getting fetched while reading the filie using xlsx.read().

### ISSUE THREAD

**Issue by UI5Training** [SheetJS/sheetjs#1664]

**Comment by UI5Training** [comment]
I need an urgent help on this.
Please help.

**Comment by SheetJSDev** [comment]
the option is `sheetStubs: true`.  What are you expecting to see for the empty cells?

**Comment by UI5Training** [comment]
Hi, 
I want that while reading the data from excel, the blank cell index must be read. It is skipping those cells. I even tried with sheetStubs: true but the situation remains the same.

**Comment by SheetJSDev** [comment]
Can you share a sample file and the value you are trying to get?

**Comment by UI5Training** [comment]
[Schedule 1_EN (1).xlsx](https://github.com/SheetJS/sheetjs/files/3802999/Schedule.1_EN.1.xlsx)
Please find the attached Excel file.
In the excel I have added two records and kept the first column blank for both the records.
So, while reading the excel file, it skips cells A2 and A3.

**Comment by SheetJSDev** [comment]
Thanks for sharing.

"Blank cell" has a specific meaning: cells that are specified in the file but have no value or type metadata.

Your file doesn't specify anything for those cells.  Here's the xml for row 2:

```xml
    <row r="2" spans="1:4" x14ac:dyDescent="0.25">
      <c r="B2" s="2">
        <v>213</v>
      </c>
      <c r="C2" s="2">
        <v>123</v>
      </c>
    </row>
```

For that reason we don't generate cells for those objects.

If you want to make a loop and add them back in:

```js
var ws = workbook.Sheets["Sheet1"];
/* get range */
var ref = XLSX.utils.decode_range(ws);
/* create empty cells */
for(var i = 1; i <= ref.e.r; ++i) {
  var addr = "A" + i;
  if(!ws[addr]) ws[addr] = {t:"z"}; // or {t:"s", v:""} if you want empty string
}
```

**Comment by UI5Training** [comment]
Hi,

Thanks for the solution.
It is working for me.
But what if I want to add empty cells for which the cell index is not known to me? I mean I don't know whether the user will keep the A column as blank or C and also these number of columns vary for different scenarios in my application. So, how can I make this statement var addr = "A" + i; dynamic.

**Comment by UI5Training** [comment]
Hi,
Thanks for the solution.
It is working for me.
But what if I want to add empty cells for which the cell index is not known to me? I mean I don't know whether the user will keep the A column as blank or C and also these number of columns vary for different scenarios in my application. So, how can I make this statement var addr = "A" + i; dynamic.


Sagar Bansal
Associate Consultant

Mobile: +91-8285069369
www.invenio-solutions.com
