### ISSUE TITLE
table表中的input框导出Excel内容为空

### ISSUE THREAD

**Issue by zhaoyuan-1224** [SheetJS/sheetjs#1666]
将table表中含有input导出excel后input内容为空！！
求问 如何解决

**Comment by bukaopuer** [comment]
你好，我没有听明白您的问题。还有，您是怎么找的我的邮箱的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhaoyuan-1224"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 上午10:02
收件人:&nbsp;"SheetJS/sheetjs"<sheetjs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SheetJS/sheetjs] table表中的input框导出Excel内容为空 (#1666)




将table表中含有input导出excel后input内容为空！！
 求问 如何解决

**Comment by bukaopuer** [comment]
将所有的数据收取成一个对象。再导出，曲线救国

**Comment by SheetJSDev** [comment]
Can you ask the question in English?
