### ISSUE TITLE
Issue Related to importing xls file

### ISSUE THREAD

**Issue by Harsh-baghel** [SheetJS/sheetjs#1667]
I am importing the xls file data is comming fine but if the xls file contain image in the cell then image is not displaying instead of image it is showing blank space.How i can fix this issue can u give any suggestion. Refer the screenshot.
This is after importing the data blank cell value--
![image](https://user-images.githubusercontent.com/54663901/68099681-acb6b180-fee9-11e9-96e3-a78b2f33b4c3.png)

This is original one--- 
![image](https://user-images.githubusercontent.com/54663901/68099693-bdffbe00-fee9-11e9-9d1e-254befdf6580.png)

**Comment by SheetJSDev** [comment]
Image support is part of our Pro offering, see https://sheetjs.com/pro for more info
