### ISSUE TITLE
I want to download xls file

### ISSUE THREAD

**Issue by Harsh-baghel** [SheetJS/sheetjs#1668]
I import one xls file now i did some changes in the sheet and after that i want to download as excel.Then how can i download the xls file

**Comment by SheetJSDev** [comment]
the `writeFile` helper function will trigger a download if you are in a web browser OR write to a file in NodeJS

**Comment by Harsh-baghel** [comment]
> `writeFile`

How i call this one can u give any example. And it will take all the tab info also

**Comment by SheetJSDev** [comment]
https://sheetjs.com/demos/table live demo, basically does:

```js
/* create workbook */
var elt = document.getElementById('data-table');
var wb = XLSX.utils.table_to_book(elt, {sheet:"Sheet JS"});
/* write file */
XLSX.writeFile(wb, 'SheetJSTableExport.xls');
```

**Comment by Harsh-baghel** [comment]
> https://sheetjs.com/demos/table live demo, basically does:
> 
> ```js
> /* create workbook */
> var elt = document.getElementById('data-table');
> var wb = XLSX.utils.table_to_book(elt, {sheet:"Sheet JS"});
> /* write file */
> XLSX.writeFile(wb, 'SheetJSTableExport.xls');
> ```

This is working but it is createing new xls file and due to this again header and side view are displaying and all the tab information are displaying in same tab. Is there any way to dowanload the file how i was viewing the file. Refer the image
![image](https://user-images.githubusercontent.com/54663901/68104827-936e2f00-ff02-11e9-8fe0-a1eeb6d5857d.png)

**Comment by Harsh-baghel** [comment]
> https://sheetjs.com/demos/table live demo, basically does:
> 
> ```js
> /* create workbook */
> var elt = document.getElementById('data-table');
> var wb = XLSX.utils.table_to_book(elt, {sheet:"Sheet JS"});
> /* write file */
> XLSX.writeFile(wb, 'SheetJSTableExport.xls');
> ```
This is working but it is createing new xls file and due to this again A,B,C D etc and 1,2,3,4... are displaying and all the tab information are displaying in same tab.Refer the screenshot.
![image](https://user-images.githubusercontent.com/54663901/68200050-1ff11e00-ffe5-11e9-9d66-f23f3a65136c.png)
