### ISSUE TITLE
Extra rows are being considered while decoding the range.

### ISSUE THREAD

**Issue by UI5Training** [SheetJS/sheetjs#1670]
Hi,

[Schedule 4_EN.xlsx](https://github.com/SheetJS/sheetjs/files/3805435/Schedule.4_EN.xlsx)

After execution of the following statement : var range = XLSX.utils.decode_range(sheet['!ref']); , I am getting range.e.r as 1312 whereas I have filled only two rows. Could anyone please explain how can I count the numbers of rows only in which the data is filled and not the extra rows.

Thanks

**Comment by UI5Training** [comment]
Hi,

Can someone please help me out with this? This has been a blocker for my application.

Please Help.

**Comment by edcalderin** [comment]
I got same issue, I was uploading a xlsx file with 5 rows, then I edited cause I wanted upload only 2 rows (I erased manually the others cells) but I was getting a json object with empty propertys of those old rows.

**Comment by jannolii** [comment]
Have the same issue. XLSX file with 5 rows and 15 columns but ref! is defined as A1:AMJ1048576. XLSX.utils.sheet_to_json() executes until app runs out of memory :(

**Comment by 9bin08** [comment]
Hi,
I looked at your example excel file and it looks like you're working on parsing the same excel file as me. In my case, it was a case where I wanted to import an Excel file as a column rather than a row and put it in an array. I was able to solve it this way. I hope my code helps!

`const file = event.target.files[0];
      const reader = new FileReader();
      reader.onload = () => {
        const data = reader.result;
        const workBook = XLSX.read(data, { type: "binary" });
        workBook.SheetNames.forEach(sheetName => {
          const row = XLSX.utils.sheet_to_json(workBook.Sheets[sheetName], {
            header: 1
          });
          
          const result = row.filter(el => el.length > 0);

          this.xlsxData = row.slice(1, result.length);

          this.xlsxData.map((obj, id, key) => {
          // number of rows
            for (let i = 0; i < 5; i++) {
              if (obj[i]) {
                this.categoryStock.push(
                  Object.assign({
                    in your code: obj[i]
                  })
                );
              }
            }
          });
        });
      };
`

**Comment by SheetJSDev** [comment]
There are stub cells in later rows.  For example row 431 XML is

```xml
    <row r="431" spans="1:6" customFormat="1" x14ac:dyDescent="0.25">
      <c r="A431" s="2"/>
      <c r="B431" s="2"/>
      <c r="C431" s="2"/>
      <c r="D431" s="2"/>
      <c r="E431" s="2"/>
      <c r="F431" s="3"/>
    </row>
```

If you want to count the rows that have data, @9bin08 has the right idea (scan the worksheet for the rows of interest).

@jannolii That is a different issue, please follow #1601 for updates

**Comment by Nairolf92** [comment]
Hello,

It seems that I'm having the same issue.
The worksheet I'm having trouble with is only composed of 5 rows. 
However it seems that they that are hundred of thousands of empty rows/cells.
I've found a workaround to clean the spreadsheet manually using [](https://www.libreofficehelp.com/how-to-delete-blank-rows-in-libreoffice-calc-sheet/
However, I can't find another way to it programmatically 

![image](https://user-images.githubusercontent.com/14052972/215734543-8bf8c23a-d12b-4152-a6d4-58ed208390ba.png)

**Comment by SheetJSDev** [comment]
The range is `A1:D1048576`.  You can programmatically write back by editing the worksheet range `.e.r` key and then setting the worksheet range in reverse:

```js
worksheetRange.e.r = 4; // SheetJS 4 = Excel 5
worksheet["!ref"] = XLSX.utils.encode_range(worksheetRange);
```

The more general question is in issue #1601
