### ISSUE TITLE
blankrow does not exist in type 'json2sheetsopts'

### ISSUE THREAD

**Issue by joecollett** [SheetJS/sheetjs#1671]
![image](https://user-images.githubusercontent.com/13499326/68226691-6006cf80-ffea-11e9-9218-4f4bdf540241.png)

I'm trying to remove blank rows but I'm getting the above error?

Currently on angular version 8.0.3 and xlsx ^0.14.5

Any ideas?

**Comment by joecollett** [comment]
Sorry see my issue blankrows doesnt exist on jsontosheet. Is there anyway to remove the spaces on the excel form?

**Comment by har1smazlan** [comment]
i have blankrows on my excel sheet but not on my csv if anyone has any input I'm all ears

**Comment by reviewher** [comment]
`blankrows` is supported in `sheet_to_csv` and `sheet_to_json`.  README says it is not supported in `json_to_sheet`
