### ISSUE TITLE
sheet_to_csv dateNF and Timezone issues

### ISSUE THREAD

**Issue by nsorin** [SheetJS/sheetjs#1672]
Hello,
I am having difficulties converting XLS files containing local dates/times to CSV.

The main issue I am running into is that I cannot export date/times as they are in the original XLS file.

When reading, if I do not explicitely set ```cellText``` to ```false``` and cellDates to ```true```, the ```dateNF``` option is ignored in the output. From what I understand, this is more or less expected (although the documentation is not very clear in that regard, I found most of my information in closed issues).

Even then, there are still issues:
- When parsing the XLS file, js-xlsx converts all date times to UTC (The original dates are CET). This means that if I set the export format with ```dateNF``` to something like 'YYYY"-"MM"-"DD HH":"mm":"ss', input and output will be different (with a 1-2h difference, depending on winter/summer time). I did not find any way to prevent (or revert) this conversion.
- Alternatively, I could use the ISO 8601 format so the timezone information is present in the output. I couldn't find a way to define it in ```dateNF``` though. 'YYYY"-"MM"-"DD"T"HH":"mm":"ss"."SSSZ' does not work and falls back to default.

Generally speaking, I find the documentation concerning date formatting seriously lacking. There should be at least a list of supported shorthands (like YYYY, MM, DD, etc.) and something about the necessity of using double quotes in some cases.

As a side note, I find it weird that the standard date format is MM/DD/YYYY, a format that is only used in the US (as far as I know) and is not standard anywhere else. Shouldn't the default format be something universal like ISO 8601?

**Comment by nsorin** [comment]
I managed to solve my problem by forcing the local timezone to UTC in a .env file (using dotenv to load it). Since I am using it only for a very small node app which does nothing more than convert a XLS to CSV, this works (only on Unix systems though).

However, I still think there should be a way to set the timezone when reading and writing files and more documentation regarding dates in general.

**Comment by SheetJSDev** [comment]
If any of this is unclear or missing from the README, please send a PR with clarifying comments:

Overall, Excel does not have a true date type.  It stores date codes (which are offsets from a timezone-dependent epoch) and special number format specifiers like `d` and `m` tell Excel to interpret the numbers as dates.

"export date/times as they are in the original XLS file."  Set `cellDates: false, cellNF: false` on read. 
 `cellNF` forces the persistence of the actual number formats.

"js-xlsx converts all date times to UTC": the generated dates will be correct for your timezone.  JS dates do not intrinsically attach a timezone.

"ISO8601": strings are automatically lifted back to dates and interpreted.  For round-tripping it is best to stick to the raw date codes.

"documentation concerning date formatting": There's definitely some assumption of experience with Excel.  We'd be amenable to a small note about how Excel date formats work.

"standard date format": in a number of places, en-US locale is assumed.  Format code 14 (written as `m/d/yy`) should be interpreted as a localized default date format, and SheetJS uses the en-US default.
