### ISSUE TITLE
json_to_sheet method does not work properly

### ISSUE THREAD

**Issue by fureweb-com** [SheetJS/sheetjs#1675]
When calling the `json_to_sheet` method through XLSX.util, the header is not generated if the cells in the row containing the first data except the header are empty.

If trying with below file, I can see the all headers properly.
http://fureweb.com/success.xlsx

But if trying with below file, I cannot see the all headers properly. Because the `D2` cell was empty. 
http://fureweb.com/fail.xlsx

https://github.com/SheetJS/sheetjs/blob/master/xlsx.js#L20807

When giving the header name as the value of cell `D1`, it seems that if the value of `D2` is empty, it treats val as undefined so that the header is not added as a row.

When creating the header I wonder why need to check if the value of the next cell exists.

I personally think that if the data passed in exists, it should consistently generate the value of the header even if all the values are empty.

How do you think about this issue?

**Comment by SheetJSDev** [comment]
To be sure, the following data generates your fail case:

```js
[
  {header1: "A1", header2: "A2", header3: "A3"},
  {header1: "B1", header2: "B2", header3: "B3", iWantSeeThisHeader: "B4"}
]
```

If you want to force a specific header order, there's a `header` option.

What exactly are you trying to do?

**Comment by SheetJSDev** [comment]
This behavior was fixed.  `json_to_sheet` generates headers at the end and it includes new fields that aren't in the first row.  #2139 has a longer discussion
