### ISSUE TITLE
crash in XLSX.read

### ISSUE THREAD

**Issue by cyrfer** [SheetJS/sheetjs#1676]
I can't seem to do the simplest parse with your library. I'm looking for a hello world example that works.

I always get a crash here:

```javascript
  function bstrify(data) {
    return !data.match(/[^\x00-\x7F]/) ? data : utf8write(data);
  }
```

with error
`data.match is not a function`

which probably comes from the use I've seen in examples for `Uint8Array`.

Here is my code

```
const sheetToModel = d => d

const onLoadedData = resolve => e => {
  console.log('loaded')
  const data = new Uint8Array(e.target.result) // also tried `data = e.target.result`
  const workbook = XLSX.read(data, {type: 'string'})  // also tried `binary`
  const sheets = workbook.SheetNames.reduce(parseSheets(workbook), {})

  console.log('onLoadedData', sheets)
  resolve(sheetToModel(sheets))
};

const onLoadedError = reject => (er) => {
  console.log('onLoadedError', er)
  reject(er)
}

export const loadFile = (file) => {
  const reader = new FileReader();

  return new Promise((resolve, reject) => {
    reader.onload = onLoadedData(resolve)
    reader.onerror = onLoadedError(reject)
    reader.readAsBinaryString(file);  // also tried `readAsArrayBuffer`
  })
}
```

If I use `data = e.target.result` instead, then I get this error:

`Error: End of data reached (data length = 12463, asked index = 564380160). Corrupted zip ?
`

I'm attaching a file to test with.
[regular-dubsheet-2024779.xlsx](https://github.com/SheetJS/sheetjs/files/3839126/regular-dubsheet-2024779.xlsx)

**Comment by SheetJSDev** [comment]
use `readAsArrayBuffer` in the `loadFile` callback and set the type to `"array"` in the `read` call.

In https://github.com/SheetJS/sheetjs#parsing-workbooks expand the section "Browser drag-and-drop" to see an example
