### ISSUE TITLE
How to =ROUND(cell_address; 0) value?

### ISSUE THREAD

**Issue by b-mi** [SheetJS/sheetjs#1678]
How to use =ROUND() function for rounding numeric value?

**Comment by fabiooshiro** [comment]
I think
`workbook.Sheets.Sheet1.A1.f = "ROUND(B2,0)"`

**Comment by SheetJSDev** [comment]
Even though European versions of Excel use a semicolon to separate arguments, the underlying files still use commas.  @fabiooshiro 's comment shows the correct way to assign the formula
