### ISSUE TITLE
Sheets property of workbook is empty

### ISSUE THREAD

**Issue by stiliqn-angelov** [SheetJS/sheetjs#1679]
Hi,
I had a problem with parsing an excel I generated in the following condition:

- user downloads the file in "untrustworthy" folder which enables the protected view of Excel
- user opens the file clicks on "Enable editting" and saves. Also there needs to be a function that errored (example division by zero because he didn't fill in values)
- user tries import the file back into the system but the parse fails
I can dig up the specific error line with WTF but I think it's better to give and example so I am attaching two files. One before "Enable editting" is clicked and one after.
[before break.xlsx](https://github.com/SheetJS/sheetjs/files/3847171/before.break.xlsx)
[after break.xlsx](https://github.com/SheetJS/sheetjs/files/3847174/after.break.xlsx)

If you need any additional info I will try to help out.

**Comment by SheetJSDev** [comment]
Can you be more specific about the error?

Against version 0.15.3 (the latest one), the "before" file can be read correctly in NodeJS:

```
$ xlsx before.break.xlsx 
Price offer
Service column,[str_Survey_product_list_example_first_column_name],[str_Survey_product_list_example_second_column_name],[str_Survey_product_list_example_third_column_name],[str_Survey_product_list_example_fourth_column_name],[str_Survey_product_list_default_column],Text Supplier,Number Dec 2 Supplier,Number Int supplier,formula,currency,number dec 4 supplier
95,558,559,560,561,562,563,564,565,566,567,568
599,[str_Survey_fake_product] 1,100,,,1,,,,,1,
600,[str_Survey_fake_product] 2,200,,,2,,,,,2,
601,[str_Survey_fake_product] 3,300,,,3,,,,,3,
602,,400,,,4,,,,,4,
603,,500,,,5,,,,,5,
604,,600,,,6,,,,,6,
605,,3333,,,234.33,,,,,,
606,,45,,,444.11,,,,,,
607,,3,,,,,,,,,
608,,3,,,,,,,,,
609,,3,,,,,,,,,
610,,,,,,,,,,,
611,,,,,,,,,,,
951,,,,,,,,,,,
952,,,,,,,,,,,
```

If you're asking about why the values are incorrect, there's an issue with an unrecognized character in the number format.

If you're asking why the error values don't show up, the file doesn't include them.  They are cells that have specified formula but no value.

The after file appears to be correct:

```
$ xlsx after.break.xlsx 
Price offer
Service column,[str_Survey_product_list_example_first_column_name],[str_Survey_product_list_example_second_column_name],[str_Survey_product_list_example_third_column_name],[str_Survey_product_list_example_fourth_column_name],[str_Survey_product_list_default_column],Text Supplier,Number Dec 2 Supplier,Number Int supplier,formula,currency,number dec 4 supplier
95,558,559,560,561,562,563,564,565,566,567,568
599,[str_Survey_fake_product] 1,100,,100.00 лв.,1.00 лв.,,,,0.00 лв.,1 лв.,
600,[str_Survey_fake_product] 2,200,,200.00 лв.,2.00 лв.,,,,0.00 лв.,2 лв.,
601,[str_Survey_fake_product] 3,300,,300.00 лв.,3.00 лв.,,,,0.00 лв.,3 лв.,
602,,400,,400.00 лв.,4.00 лв.,,,,0.00 лв.,4 лв.,
603,,500,,500.00 лв.,5.00 лв.,,,,0.00 лв.,5 лв.,
604,,600,,600.00 лв.,6.00 лв.,,,,0.00 лв.,6 лв.,
605,,3333,,3333.00 лв.,234.33 лв.,,,,#DIV/0!,,
606,,45,,45.00 лв.,444.11 лв.,,,,#DIV/0!,,
607,,3,,3.00 лв.,,,,,#DIV/0!,,
608,,3,,3.00 лв.,,,,,#DIV/0!,,
609,,3,,3.00 лв.,,,,,#DIV/0!,,
610,,,,0.00 лв.,,,,,#DIV/0!,,
611,,,,0.00 лв.,,,,,#DIV/0!,,
951,,,,0.00 лв.,,,,,#DIV/0!,,
952,,,,0.00 лв.,,,,,#DIV/0!,,
```

Looking at the number formats, the before file has the following incorrect format:

```
0.00 лв\.
```

The after file correctly escapes the characters:

```
0.00\ \л\в\.
```

**Comment by stiliqn-angelov** [comment]
I was using 0.15.1 in a browser. I am guessing the latest version fixes the issue. When I have the time I will test that.
