### ISSUE TITLE
Getting the spreadsheet filename on drag and drop

### ISSUE THREAD

**Issue by LusiusDark** [SheetJS/sheetjs#1680]
I noticed your demo programs (https://oss.sheetjs.com/) allow a drag and drop but they don't display the name of the spreadsheet file that was dragged and dropped. The filename is only available if the user selects the sheet using the "Choose File" button. Is there a way to get the filename of the spreadsheet dragged and dropped into the sheetjs demo app? This is a very appealing feature.

**Comment by SheetJSDev** [comment]
The filename you see when submitting a file comes from the `value` property of the `input` element.  To get the filename from a dragged file, look at the `name` property of the `File` object.  Copying the README example of drag-and-drop:

```js
function handleDrop(e) {
  e.stopPropagation(); e.preventDefault();
  var files = e.dataTransfer.files, f = files[0];
  /* !! AT THIS POINT, f.name is the file name !! */
  var reader = new FileReader();
  reader.onload = function(e) {
    var data = new Uint8Array(e.target.result);
    var workbook = XLSX.read(data, {type: 'array'});

    /* DO SOMETHING WITH workbook HERE */
  };
  reader.readAsArrayBuffer(f);
}
drop_dom_element.addEventListener('drop', handleDrop, false);
```
