### ISSUE TITLE
Get Cell Column data

### ISSUE THREAD

**Issue by Wolfleader101** [SheetJS/sheetjs#1681]
Hello,

I can't find an easy way to find all cells that start with 'ABC' and then get their column data.

Basically the header row could contain cells that are 'ABC3435' or 'ABC935783' or 'ABC_24329'

I need to only get those cells and their data column data.

**Comment by Wolfleader101** [comment]
Found workaround

**Comment by caiquejjx** [comment]
I need the same thing as you, what u used to do that?

**Comment by reviewher** [comment]
```js
var range = XLSX.utils.decode_range(ws["!ref"]);
range.s.c = range.e.c = XLSX.utils.decode_col("ABC"); // replace ABC with the name of the column you want, or use a number
var data = XLSX.utils.sheet_to_json(ws, {header:1, range:XLSX.utils.encode_range(range)});
```
