### ISSUE TITLE
Export to CSV File where the merged cell are not displayed in each row

### ISSUE THREAD

**Issue by joonhoe1337** [SheetJS/sheetjs#1682]
Hi, The demo that is provided in this link [(https://sheetjs.com/demos/modify.html)]  allow user to test on the Export result. I tried to export it as CSV format and I have uploaded a custom excel sheet with a merge cell and I was expecting the merge cell data will be displayed on each row when i open the CSV file with notepad but it does not. 

![image](https://user-images.githubusercontent.com/9324132/69225517-849da280-0bb9-11ea-9112-c1a0571319b8.png)

On the screenshot, I was expecting the Named to be displayed on each row but it does not. Is there any way to make it happen?

**Comment by SergioEnrique** [comment]
were you able to solve it?

**Comment by SheetJSDev** [comment]
CSV has no natural representation of "merged cells".  If you really want to repeat it, you can walk the merge range and repeat the cell object:

```js
ws["!merges"].map(merge => typeof merge == 'string' ? XLSX.utils.decode_range(merge) : merge).forEach(merge => {
  var anchor = ws[XLSX.utils.encode_cell(merge.s);
  for(var R = merge.s.r; R <= merge.e.r; ++R) {
    for(var C = merge.s.c; C <= merge.e.c; ++C) {
      ws[XLSX.utils.encode_cell({r:R,c:C})] = anchor;
    }
  }
});
ws["!merges"] = [];
```

This breaks the entire merge structure and forces repeating the cell across every column and row of the merge.  It will take your example of

<table><tr>
<td rowspan="6">Named</td>
<td>Apple</td><td>Orange</td></tr>
<tr><td>Apple</td><td>Orange</td></tr>
<tr><td>Apple</td><td>Orange</td></tr>
<tr><td>Apple</td><td>Orange</td></tr>
<tr><td>Apple</td><td>Orange</td></tr>
<tr><td>Apple</td><td>Orange</td></tr>
</table>

and effectively convert it to 

<table>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
<tr><td>Named</td><td>Apple</td><td>Orange</td></tr>
</table>
