### ISSUE TITLE
preserve type and number format for empty cells

### ISSUE THREAD

**Issue by pieterprovoost** [SheetJS/sheetjs#1691]
Is there any way to preserve `t` and `z` (number format) for empty cells when reading a sheet? I tried `sheetStubs` but that results in `{t: "z"}` for all empty cells, even the one that are formatted as a number in Excel.

**Comment by aimergenge** [comment]
same issue

**Comment by SheetJSDev** [comment]
Happy Holidays! pass the `cellNF` option

**Comment by aimergenge** [comment]
@SheetJSDev wait wait ...

I passed the `cellNF` option

while there are some cells working:
![image](https://user-images.githubusercontent.com/13799160/71332210-5d4b4400-2570-11ea-9e14-e9270d2be473.png)


other cells not:
![image](https://user-images.githubusercontent.com/13799160/71332198-4f95be80-2570-11ea-9795-17516622477d.png)

But If I open the file in Office, I can inspect the cell and see its type is percentage
