### ISSUE TITLE
Read protected view vs unprotected view

### ISSUE THREAD

**Issue by Dams591** [SheetJS/sheetjs#1696]
Hi guys,
I'm using a third party app that creates a xlsx and i'm trying to read it to convert it into json (or html)
the third party app generates a xlsx which has protected view, if I use the file 
[PivotGrid_Protected.xlsx](https://github.com/SheetJS/sheetjs/files/3902237/PivotGrid_Protected.xlsx)
here
https://oss.sheetjs.com/sheetjs/

All I got is germany but my table has a lot more !
If i open the xlsx in excel enable editing, save the file it will work.

Please find my files
[PivotGrid_Protected.xlsx](https://github.com/SheetJS/sheetjs/files/3902237/PivotGrid_Protected.xlsx)
[PivotGrid_UnProtected.xlsx](https://github.com/SheetJS/sheetjs/files/3902238/PivotGrid_UnProtected.xlsx)

How can I get all the values of a protected file ? or even better removed protected view using sheetjs ? I have the xlsx file in a blob.
Thank you,

**Comment by SheetJSDev** [comment]
The third party app is reporting the worksheet dimensions as A1:C1:

```xml
  <dimension ref="A1:C1"/>
```

The cell data is still available, and you can use the [`update_sheet_range` function from the wiki](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions) to recalculate the range

**Comment by alxxjs-sudo** [comment]
Hi @Dams591, were you able to make it work using the suggested fix or have you found another way to deal with this? Suggested fix did not do the job for me.

cc @SheetJSDev
