### ISSUE TITLE
Number and date datatype issues

### ISSUE THREAD

**Issue by reshmi-manamal** [SheetJS/sheetjs#1698]
Hi, I use the formatting for number and date fields and it works fine. Also, when I select the cell it shows correct data type. But there are issues - number field does not have all characteristics of it. It is not right aligned and does not honor custom settings. For example, the decimal should be comma when the excel is opened in the computers from certain countries. It does not happen.

Is it possible to apply these custom settings though sheetJS?

I use aoa_to_sheet utility and here is my code that performs formatting (kotlin).
private fun applyFormattingToWorkSheet(rowCount: Int, workSheet: dynamic, xlsx: dynamic) {

    data class CellObject(val r: Int, val c: Int)
    data class RangeObject(val start: CellObject, val end: CellObject)

    val numberFormat = "0.00"
    val numberRange = RangeObject(CellObject(1, 3), CellObject(rowCount, 4))
    for (row in numberRange.start.r..numberRange.end.r) {
        for (column in numberRange.start.c..numberRange.end.c) {
            val cell = workSheet[xlsx.utils.encode_cell(CellObject(row, column))]
            cell.z = numberFormat
        }
    }

    val dateFormat = "DD-MM-YY"
    val dateRange = RangeObject(CellObject(1, 1), CellObject(rowCount, 2))
    for (row in dateRange.start.r..dateRange.end.r) {
        for (column in dateRange.start.c..dateRange.end.c) {
            val cell = workSheet[xlsx.utils.encode_cell(CellObject(row, column))]
            cell.z = dateFormat
        }
    }
}

**Comment by SheetJSDev** [comment]
The thousands separator and decimal point are computer regional settings.  There is nothing we can write in an XLSX or XLS or XLSB file that will force Excel to use en-US or de-DE or zh-CN or any other locale.

Setting the `z` field tells Excel what format we wish to apply.  As of the writing of this comment, that is all we can do.  If Microsoft adds special record metadata to Excel for overriding the locale, then it can be implemented here.
