### ISSUE TITLE
XLSX with Rollup fails with "readFile is not exported"

### ISSUE THREAD

**Issue by CodeTroopers** [SheetJS/sheetjs#1700]
I try to use xlsx with rollup.js to build an azure pipeline extension.

I reproduce with small steps :
### Installation
```
npm install xlsx --save
npm install rollup --save-dev
npm install @rollup/plugin-node-resolve --save-dev
npm install rollup-plugin-commonjs --save-dev
```
### Rollup configuration
```
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from '@rollup/plugin-node-resolve';

export default {
	input: "index.js",
	output: {
		dir: "output",
		format: "cjs"
	},
	plugins: [
		nodeResolve(),
		commonjs(),
	]
};
```
### Source: index.js
```
import * as xlsx from 'xlsx';

const workbook = xlsx.readFile('');

export default workbook;
```
### Build
rollup -c

### Output

> index.js → output...
> (!) Missing exports
> https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
> index.js
> readFile is not exported by node_modules\xlsx\xlsx.js

**Comment by SheetJSDev** [comment]
The [`rollup` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/rollup) passes a few options to the node resolve plugin, specifically the `module: false` option to tell rollup it isn't an ES module:

```js
	plugins: [
		resolve({
			module: false,
			browser: true,
		}),
		commonjs()
	],
```

Can you try that option?

**Comment by CodeTroopers** [comment]
@SheetJSDev : `module: false` is deprecated

I tried with :
```
	plugins: [
		nodeResolve({
			mainFields: ['browser']
		}),
		commonjs(),
	]
```
but have the same error...

**Comment by CodeTroopers** [comment]
Ok, I didn't see that named export can be defined like this :
```
	plugins: [
		nodeResolve(),
		commonjs({
			namedExports: {
				'xlsx': ['readFile']
			}
		}),
	]
```
It works, thank you!

**Comment by SheetJSDev** [comment]
Out of curiosity, does `mainFields: [ "main" ]` work?

In any case, we'd accept a PR that updates the rollup demo with the required options

**Comment by CodeTroopers** [comment]
`mainFields: [ "main" ]` didn't work in my case.

But I realized my import was incorrect. I imported `xlsx` as a namespace instead of import a default export:
`import * as xlsx from 'xlsx'`
vs
`import xlsx from 'xlsx'`

with the good import, `rollup` work with:
```
	plugins: [
		nodeResolve(),
		commonjs(),
	]
```

So your rollup demo is perfect!
