### ISSUE TITLE
export to excel :- "We found a problem with some content in ".xls""

### ISSUE THREAD

**Issue by jmonfu** [SheetJS/sheetjs#1704]
Dear All, 

I have some code that is exporting some data to Excel and I have a hyperlink that is also being displayed in the stylesheet.  

```
            let urlLink = {
                f: 'HYPERLINK("' + item.ProjectUrl + '", "' + item.ProjectUrl + '")',
                t: 'n',
                v: item.ProjectUrl
            };

```

The problem is that when I try to open the xls file I get the following message:-

We found a problem with some content in ".xls".  Do you want us to try to recover as much as we can?  If you trust this source of this workbook click Yes.

![excelProb1](https://user-images.githubusercontent.com/163650/70919268-dacafd80-2020-11ea-894a-cebcc2046c05.png)

Is this possible to remove by some code?

Thanks for your help and time

**Comment by reviewher** [comment]
You're setting a string, so make the type of the cell `s`:

```
            let urlLink = {
                f: 'HYPERLINK("' + item.ProjectUrl + '", "' + item.ProjectUrl + '")',
                t: 's',
                v: item.ProjectUrl
            };


```

**Comment by jmonfu** [comment]
thanks that solved the problem!

**Comment by jmonfu** [comment]
Can I also ask what I can do for this, since this is a date and I am getting the popup again:-

      ```
      let insertedOn = {
                f: moment(item.InsertedOn).local().format(excelDateFormat),
                t: 'd',
                v: moment(item.InsertedOn).local().format(excelDateFormat)
            };

```
