### ISSUE TITLE
Formatting date to dd-mm-yy when exporting

### ISSUE THREAD

**Issue by TimVN** [SheetJS/sheetjs#1706]
I'm trying to get it to show the date in dd-mm-yy in both the worksheet as in the bar at the top in Excel.

```
ws[key].t = "d";
ws[key].v = date;
ws[key].z = "dd-mm-yy";
```

```date``` is a Javascript date-object.

This almost works. It does show the correct format in the cells, but not at the top. It adds the time, and it randomly switches between AM/PM it seems.

I have set ```dateNF``` to dd-mm-yy as well, and set ```cellDates``` to true to no avail.

How do I get it to show the date in the same format in both places? I have tried everything.

**Comment by SheetJSDev** [comment]
If you are talking about the formula bar, that is unaffected by the number format.  You can verify this in Excel by entering a date in the cell and changing the number format.  Irrespective of the format, Excel still shows the same locale-dependent date (for en-US it shows `m/d/yy` or `m/d/yy H:MM:SS AM/PM`)
