### ISSUE TITLE
Can't set a new value into an empty cell

### ISSUE THREAD

**Issue by AlexanderChusov** [SheetJS/sheetjs#1708]
The following code doesn't modify A1 cell if A1 cell is empty in the input.xlsx file:

`        const xlsx = require('xlsx');`
`        let workbook = xlsx.readFile('d:/input.xlsx');`
        
`        // get first sheet`
`        const worksheet = workbook.Sheets[workbook.SheetNames[0]];`
        
`        // modify value in A1`
`        if (!worksheet['A1'])`
`            worksheet['A1'] = {};`
`        worksheet['A1'].t = 's';`
`        worksheet['A1'].v = 'value';`
        
`        // write to new file`
`        xlsx.writeFile(workbook, 'd:/output.xlsx');`

However, if A1 cell is not empty in the input.xlsx file then it is working as expected by setting 'value' into the A1 cell.

**Comment by SheetJSDev** [comment]
`A1` is outside the known range.  Grab the `update_sheet_range` function from https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions#updating-worksheet-range
