### ISSUE TITLE
Functions for number is not working in Excel , how to export as number instead of text?

### ISSUE THREAD

**Issue by goxr3plus** [SheetJS/sheetjs#1709]
I am having the below :

``` JAVASCRIPT
{text: convertToCurrency(number) }

const convertNumberToCurrency = (value) => {
      return new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" }).format(value).slice(0, -1)
}

```

We are having problems with Excel , the functions for number is not working with the above .

Do you have any recomendations :) ?

**Comment by fabiooshiro** [comment]
try to write your cell like
A1: {v:123, t: "n"}
where n is the type number and 124 is the value
🙏

**Comment by goxr3plus** [comment]
Thank you so much, i will try :)

**Comment by SheetJSDev** [comment]
To be more specific, the cell object should have the type "n" for number, "v" should be the numeric value, and "z" should be the number format according to Excel.  Generally you use something like "$#,##0.00" for dollars.

To find the specific style you need, set it in a sample file in Excel, then save the file and parse with SheetJS using the option `cellNF: true`, then inspect the cell object for that cell.
