### ISSUE TITLE
Workbook spits json, but sheet_to_json gives empty array

### ISSUE THREAD

**Issue by a2441918** [SheetJS/sheetjs#1710]
[Reports (4).xlsx](https://github.com/SheetJS/sheetjs/files/3991100/Reports.4.xlsx)

Hi, I want to convert this excel file to an array of objects, and for some reason even in sheet.js demos I get only the headers. Can someone advice me on this?

https://oss.sheetjs.com/

https://oss.sheetjs.com/sheetjs/

In both these, the files return me only headers.

I get an empty array when I use the below function.

	handleUpload = (evt) => {
		const selectedFile = evt.target.files[0];
		const reader = new FileReader();
		reader.onload = (event)  => {
			const data = event.target.result;
			const workbook = XLSX.read(data, {
				type: 'binary'
			});
			console.log('workbook', workbook)
			workbook.SheetNames.forEach(sheetName => {
				console.log('sheetName', sheetName)

				const xlRowObject = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]);
				console.log(xlRowObject)
			})
		};
		reader.onerror = (event) => {
			console.error(`File could not be read! Code ${event.target.error.code}`);
		};
		reader.readAsBinaryString(selectedFile);
	}

Please advice.

**Comment by myfonj** [comment]
XLSX thinks that "!ref" range in your sheet is just on the first columns (`"A1:E1"`) (IDK why)
https://oss.sheetjs.com/sheetjs/
```
global_wb.Sheets[global_wb.SheetNames[0]]["!ref"] // "A1:E1"
```
so all `XLSX.utils.sheet_to_*` will implicitly honor this range.

I don't know the reason this sheet has this range or how it could happen: saving this document unmodified resets this to `"A1:E6"` for me. So I think it might be some glitch in export or corruption of file, perhaps (?)

You can manually set that range and subsequent calls will behave as expected
```
global_wb.Sheets[global_wb.SheetNames[0]]["!ref"] = "A1:E6";
XLSX.utils.sheet_to_csv(global_wb.Sheets[global_wb.SheetNames[0]]);
// gives
"State,FY,Quarter,Numer of Grants,Total Amount Awarded
Alabama,2018,4,1,\"$247,551.00 \"
Alabama,2019,3,5,\"$1,732,820.00 \"
Alaska,2019,2,1,\"$986,123.00 \"
Alaska,2019,3,30,\"$3,066,610.00 \"
Alaska,2019,4,1,\"$345,761.00 \"
"
```
or for `.._to_json` you can specify `range` as a property of second argument `XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{range:"A1:E6"});`.

**Comment by SheetJSDev** [comment]
@myfonj summarized the situation well.  This file is most likely an export from a non-Excel utility and cheated with the worksheet dimension.

The file reports the range of the first worksheet as A1:E1.  The reported range shows up in the worksheet XML.  If you go to https://oss.sheetjs.com/cfb-editor/ , drag-drop the file, look at `xl/worksheets/sheet1.xml` and "view as text" you'll see the reported range in the "dimension" record:

<img width="214" alt="dimension" src="https://user-images.githubusercontent.com/6070939/71710576-e8c3a100-2dca-11ea-92a9-5c9bbc7f28c5.png">

[The `update_sheet_range` function in the wiki](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions) shows a way to recalculate the worksheet range.
