### ISSUE TITLE
Google chrome crash when upload more than 19,121kb file

### ISSUE THREAD

**Issue by ShefaliM2** [SheetJS/sheetjs#1714]
When xlxs.read 6lakhs record file i.e. 19,121kb file chrome crashes
 example: when XLSX.read(bytes, { 'type': 'array' }) line start execution after some seconds chrome crashed in angular 8
my code:- 
reader.onload = function(e: any) {
      const bytes = new Uint8Array(e.target.result);
      const workbook = XLSX.read(bytes, { 'type': 'array' });
      const sheet_name_list = workbook.SheetNames;
      self.fileResponse = XLSX.utils.sheet_to_json(workbook.Sheets[sheet_name_list['0']], { 'header': 1 });
    };
    reader.onerror = function(e: any) {
      self.showLoader = false;
    };
    reader.onabort = function(e: any) {
      self.showLoader = false;
    };
    reader.readAsArrayBuffer(uploadedFile);

**Comment by sion005** [comment]
Did you managed to resolve this issue? I'm having the same problem with a 16,371 xlsx file.

**Comment by SheetJSDev** [comment]
Please share the files in question (send to hello@sheetjs.com) and we can reopen the issue.
