### ISSUE TITLE
Named cell reference causes the string "undefined" to be output in the ODS file

### ISSUE THREAD

**Issue by dandv** [SheetJS/sheetjs#1717]
```js
const XLSX = require('xlsx');

const wb = XLSX.utils.book_new();

const ws = XLSX.utils.json_to_sheet([]);

XLSX.utils.book_append_sheet(wb, ws, 'Bug sheet');

ws.A1 = { t: 's', f: 'square' };

XLSX.writeFile(wb, 'formula.ods');
```

The resulting .ODS file contains:

    <table:table-cell table:formula="of:=square" office:value-type="string"><text:p>undefined</text:p></table:table-cell>

Not sure what `<text:p>` is (probably a placeholder?), but it should simply be omitted in this case.

Adding a `v: ''` to the cell object outputs an empty `<text:p></text:p>`.

    <table:table-cell table:formula="of:=square" office:value-type="string"><text:p></text:p></table:table-cell>

That, again, should be omitted, or optimized to `<text:p/>`.

**Comment by SheetJSDev** [comment]
This is actually an issue with a string cell that has no value.  The fix is pretty straightforward (feel free to submit a PR): https://github.com/SheetJS/sheetjs/blob/master/bits/81_writeods.js#L81

```diff
-						textp = cell.v;
+						textp = cell.v == null ? "" : cell.v;
```
