### ISSUE TITLE
After saving new xlsm file, unable to open it. FIle corrupted error

### ISSUE THREAD

**Issue by mobile-instagram** [SheetJS/sheetjs#1718]
Hi
I am having a xlsm file, i am reading it and saving it as a new file. On opening getting error in MS Excel 2013 - **The Workbook cannot be opened or repaired  by Microsoft Excel because it is corrupt**

My code is -

`let wb = XLSX.readFile("./a.XLSM", {bookVBA:true});`
`XLSX.writeFile(wb,` "newpage.XLSM");`

I tried reading this new file but the macros are not implemented and i am getting same old value in new file

My code is -

`let wb = XLSX.readFile("./a.XLSM", {bookVBA:true});`
      `const first_sheet_name = wb.SheetNames[2];`
      `const worksheet = wb.Sheets[first_sheet_name];`
      `let desired_cell = worksheet['G3'];`
      `desired_cell.v = 400000;`
      `desired_cell.w = '400000';`
      `XLSX.writeFile(wb, "newpage.XLSM"); `
      `let wbNew = XLSX.readFile("./newpage.XLSM", {bookVBA:true});`
      `const first_sheet_name_new = wbNew.SheetNames[4];`
      `const worksheetNew = wbNew.Sheets[first_sheet_name_new ];`
      `let desired_celll = worksheetNew['D25'];`
      `console.log(desired_celll);`  

Getting same old value in console. New excel file is not doing calculation on the basis of new input 40000.

**Comment by SheetJSDev** [comment]
To force the VBA blob to be written, pass the option `bookVBA: true` on write:

```js
XLSX.writeFile(wb, "newpage.xlsm", {bookVBA: true});`
```

If you can share the generated file, we can take a closer look

**Comment by mobile-instagram** [comment]
> To force the VBA blob to be written, pass the option `bookVBA: true` on write:
> 
> ```js
> XLSX.writeFile(wb, "newpage.xlsm", {bookVBA: true});`
> ```
> 
> If you can share the generated file, we can take a closer look

Still i am facing same issue.
I cannot share that excel file.

**Comment by SheetJSDev** [comment]
Without the file, it is hard to say what the error is.  Please update to the latest version, and if the error still persists please consider sending the file to hello@sheetjs.com

**Comment by yogesh9716** [comment]
Hi @SheetJSDev 
I am using SheetJs to update my XLSX sheet, I need help, My existing Xlsx has 15 sheets, when I am updating any value in any sheet coloring of all the sheet got removed , so how I can over come with this issue.
any help is appreciated.
