### ISSUE TITLE
no output for empty cell

### ISSUE THREAD

**Issue by pdontula** [SheetJS/sheetjs#1720]
I am using js sheet. The empty cell is not getting populated in the json object including the header. I need that information also if a column is not entered. Here is my code:
 workbook.SheetNames.forEach((sheetName) => {
let XL_row_object = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {defval:""});
console.log( JSON.stringify(XL_row_object ));
}

**Comment by Colin-Whelan** [comment]
Having the same issue, the headers are there but empty cells are completely omitted instead of being ''

**Comment by burakkp** [comment]
Hi @pdontula 
Did you find any solution for this? I have same issue.

**Comment by burakkp** [comment]
> Hi @pdontula
> Did you find any solution for this? I have same issue.

I solved this pronlem with this => XLSX.readFile('file', {sheetStubs:true})

**Comment by reviewher** [comment]
As @burakkp mentioned, empty cells are not generated normally.  You have to pass the option `sheetStubs: true`.  See https://docs.sheetjs.com/#data-types note about Type `z`
