### ISSUE TITLE
Linebreak for table_to_sheet

### ISSUE THREAD

**Issue by jasonchuah4** [SheetJS/sheetjs#1721]
Hi guys,

I search the net high and low but couldn't find a solution to have line break in Excel after exporting from HTML Table.

My snippets of HTML table looks as below:
`<td>Value 1 <br /> Value 2\r\n Value 3 &#10;</td>`

I've tried 3 different approaches which is `<br />`, `\r\n` and `&#10;` but none of them work. How do I overcome this issue?

Thanks.

**Comment by SheetJSDev** [comment]
To force line breaks to render properly, "Wrap Text" has to be set.  This is a styling option that is not supported in our open source build.  Our Pro Compendium includes support for it -- https://sheetjs.com/pro for more info.
