### ISSUE TITLE
Data inconsistency in Excel 

### ISSUE THREAD

**Issue by Veeramani05** [SheetJS/sheetjs#1724]
I am trying to export data from table in angular 6.
For a simple table it is exporting exact in the UI.
But in the following kind of code is exporting inconsistency data.

Table
-----
`
<table id="EnquiryTable1" #ExcelTable1 class="table table-bordered table-hover" border=1>
      <tr style="background-color: #cccccc;">
          <td colspan="2" class="row-center bold">
              Current Allocation
          </td>
          <td colspan="3" class="row-center bold">
              Supplementary Approval
          </td>
          <td colspan="3" class="row-center bold">
              Partial Cancellation
          </td>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td colspan="2" align="center">
              <table width="100%" style="
              width: 100%;
              border: solid 1px #eae3e3 !important;
          ">
                  <thead>
                      <tr>
                          <td class="bold row-center">
                              Fund
                          </td>
                          <td class="bold row-center">
                              Amount
                          </td>
                      </tr>
                      <tr *ngFor="let itemData of pagedItems1;" style="background-color: #fff;">
                          <td class="row-center">
                              {{itemData?.fundCode}}
                          </td>
                          <td class="row-right">
                              {{itemData?.currAllocationAmt | amount:'2.2-2'}}
                          </td>
                      </tr> 
                  </thead>
              </table>
          </td>

          <td colspan="3" class="row-center" align="center">
              <table width="100%" style="
              width: 100%;
              border: solid 1px #eae3e3 !important;
          ">
                  <thead>
                      <tr>
                          <td class="bold row-center">
                              Fund
                          </td>
                          <td class="bold row-center">
                              Date
                          </td>
                          <td class="bold row-center">
                              Amount
                          </td>
                      </tr>
                      <tr *ngFor="let itemData of pagedItems1;" style="background-color: #fff;">
                          <td class="row-center">
                              {{itemData?.fundCode}}
                          </td>
                          <td class="row-center">
                              {{itemData?.fundDate | date: "dd/MMM/yyyy"}}
                          </td>
                          <td class="row-right">
                              {{itemData?.amountApproved | amount:'2.2-2'}}
                          </td>
                      </tr> 
                  </thead>
              </table>
          </td> 
          <td colspan="3" class="row-center" align="center">
              <table width="100%" style="
              width: 100%;
              border: solid 1px #eae3e3 !important;
          ">
                  <thead>
                      <tr>
                          <td class="bold row-center">
                              Fund
                          </td>
                          <td class="bold row-center">
                              Date
                          </td>
                          <td class="bold row-center">
                              Amount
                          </td>
                      </tr>
                      <tr *ngFor="let itemData of pagedItems1;" style="background-color: #fff;">
                          <td class="row-center">
                              {{itemData?.fundCode}}
                          </td>
                          <td class="row-center">
                              {{itemData?.fundDate| date: "dd/MMM/yyyy"}}
                          </td>
                          <td class="row-right">
                              {{itemData?.cancellationAmt | amount:'2.2-2'}}
                          </td>
                      </tr> 
                  </thead>
              </table>
          </td>
      </tr>
  </tbody>
</table>
![input](https://user-images.githubusercontent.com/47449982/72331353-128b9a80-36de-11ea-8580-e86eecfa0694.png)
[output.xlsx](https://github.com/SheetJS/sheetjs/files/4058356/output.xlsx)

`

**Comment by SheetJSDev** [comment]
It looks like you are using tables within TD elements.  Excel has no natural representation of nested tables, and the SheetJS parsers don't really handle nested tables well.  If you can propose an Excel equivalent of the nested table, we'll consider how to map those
