### ISSUE TITLE
Reading date from excel gives incorrect output

### ISSUE THREAD

**Issue by techvaib** [SheetJS/sheetjs#1725]
I am trying to read an excel file and converting it to array/json.
The issue is that the date I am passing in file is read incorrectly and is just off by 10 seconds leading to an incorrect date.
Ex : The date in my file is **10th April, 2018** but the output which i get in date format is **Mon Apr 09 2018 23:59:50 GMT+0530 (India Standard Time)** (off by 10 seconds leading to one date less than the actual date).

I have tried with multiple combinations of passing parameters from the below parameters 

`oWorkBook = XLSX.read(bFileData, {
						type: "binary",
						cellDates: true,
						cellStyles: true,
						dateNF: 'mm-dd-yy',
						cellText: false
					});`

`var stroa = XLSX.utils.sheet_to_row_object_array(oWorkBook.Sheets[sSheetName], {
					raw: true
				});`
Let me know if I am doing something in an incorrect way.

[OutboundShipment.xlsx](https://github.com/SheetJS/sheetjs/files/4063048/OutboundShipment.xlsx)
![Incorrect Date](https://user-images.githubusercontent.com/59905492/72405033-72854e00-377d-11ea-8505-3a40ff755a56.png)

Thanks,
Vaibhav

**Comment by SansDK** [comment]
Same issue here. I don't have Microsoft Excel, but I tested this with 

1. Google Sheets -> export to .xlsx
2. Google Sheets -> export to .ods
3. LibreOffice Calc -> export to .ods

This issue only seems to happen in case 1 for some reason.

**Comment by techvaib** [comment]
@lev-cx


Agree that Date conversion depends on local time zone but where are the 10 seconds getting lost leading to an incorrect date.....

**Comment by reviewher** [comment]
Similar error: https://github.com/SheetJS/sheetjs/issues/2304

It's a bug in V8 node and chrome https://bugs.chromium.org/p/v8/issues/detail?id=7863

Closing in favor of https://github.com/SheetJS/sheetjs/issues/1565
