### ISSUE TITLE
o.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by BjoernRave** [SheetJS/sheetjs#1726]
When trying to call `XLSX.utils.json_to_sheet()` I get the following error: `o.hasOwnPropert is not a function`

This most likely related to [this issue](https://github.com/FormidableLabs/urql/pull/343).

**Comment by SheetJSDev** [comment]
That's hilarious and disturbing.  The referenced PR changed `o.hasOwnProperty` to `Object.prototype.hasOwnProperty.call(o, key)` -- we'll look into making the same changes throughout the code
