### ISSUE TITLE
Can we read data Column Wise in XLSX File using SheetJs?

### ISSUE THREAD

**Issue by danifaiz** [SheetJS/sheetjs#1729]

**Comment by SheetJSDev** [comment]
Data is stored row-wise in most formats (Some of the older formats are column-wise but all contemporary formats are row-wise).

You can convert a worksheet to an array of arrays using `sheet_to_json` with the option `header:1` and transpose it for column-wise access.  See https://github.com/SheetJS/sheetjs/issues/1085#issuecomment-384472147 for an example:

```js
var tpose = [];
for(var i = 0; i < data.length; ++i) {
  for(var j = 0; j < data[i].length; ++j) {
    if(!tpose[j]) tpose[j] = [];
    tpose[j][i] = data[i][j];
  }
}
```

**Comment by danifaiz** [comment]
Thanks a lot for the response!! , transpose solution works great! Earlier I tried iterating through column first and then in the inner loop for rows, so it also worked out.

function readColumnWiseData(range,ws){
    var columnWiseData = [];
    for(var C = range.s.c; C <= range.e.c; ++C) {
        columnWiseData[C] = [];
        for(var R = range.s.r; R <= range.e.r; ++R) {

            var cellref = XLSX.utils.encode_cell({c:C, r:R}); // construct A1 reference for cell
            if(!ws[cellref]) continue; // if cell doesn't exist, move on
            var cell = ws[cellref];
            columnWiseData[C].push(cell.v);

        };
    }
    return columnWiseData;
}

const wb = XLSX.read(bstr, {type:'binary'});
const wsname = wb.SheetNames[0];
const ws = wb.Sheets[wsname];
var range = XLSX.utils.decode_range(ws['!ref']); // get the range
var columnWiseData = readColumnWiseData(range,ws);
