### ISSUE TITLE
Can we Read Password Protected excel sheet File using XLSX ?

### ISSUE THREAD

**Issue by studylohar** [SheetJS/sheetjs#1732]
Hi i m new for the react native app development and i trying to read the password protected excel sheet file content and load all excel data to the sqlite database. so please any one can help me in this case???.

**Comment by SheetJSDev** [comment]
Reading password-protected XLSX files is a component we offer in our Pro builds but not our Community edition, https://sheetjs.com/pro more info

**Comment by studylohar** [comment]
is there any other component to achieve this kind of requirements? 
can you please suggest any other alternative solutions?

**Comment by miccoh1994** [comment]
Hi @SheetJSDev, I actually want the pro license for this use case, I am still waiting for a response from your team .....

**Comment by gpremo-re** [comment]
@miccoh1994 Just curious how long did it take for you to receive a response from the pro@sheetjs.com email? I am also in need of the pro license for this exact use case.

**Comment by miccoh1994** [comment]
@gpremo-re 

I think it took a very long time, I ended up using xlsx-populate instead. Which luckily handled all the functionality that I needed.

**Comment by sadidarhamar** [comment]
@miccoh1994 may i see how you do it with react-native ? because when i use it i get multiple error like **Unable to resolve module crypto** in \node_modules\xlsx-populate\lib\Encryptor.js also **Unable to resolve module fs** in \node_modules\xlsx-populate\lib\Workbook.js:

**Comment by miccoh1994** [comment]
@sadidarhamar I used it on the backend.
