### ISSUE TITLE
[Enhancement] Chrome 80 open link instead of download blob file

### ISSUE THREAD

**Issue by OverkillTV** [SheetJS/sheetjs#1735]
I'm using Chrome v80 and it opens a new tab with the "blob:<guid>" in the url instead of download the blob file when hitting the "XLSX.writeFile" line of code.

Maybe Google changes something in Chrome v80. Anyone has solution/workaround for this ?

**Comment by SheetJSDev** [comment]
Cannot reproduce using "Version 80.0.3987.106 (Official Build) (64-bit)" on https://sheetjs.com/demos/table -- can you test if that page works without opening a new tab?

**Comment by OverkillTV** [comment]
Yeah that demo is working correctly for me.
I'm using v0.15.1 in my code maybe that is the reason. I'll try npm update it to latest.

Thanks,
