### ISSUE TITLE
Non-mini xlsx.js missing "Root Entry" removal for proper ZIP parsing

### ISSUE THREAD

**Issue by shliama** [SheetJS/sheetjs#1736]
There is a difference in `safegetzipfile` method between [xlsx.js](https://github.com/SheetJS/sheetjs/blob/a81bb78f18960053a03bb3350f31ea54d28245be/xlsx.js#L2810) & [xlsx.mini.js](https://github.com/SheetJS/sheetjs/blob/a81bb78f18960053a03bb3350f31ea54d28245be/xlsx.mini.js#L2789).

One is missing `replace(/^Root Entry[\/]/,"")` so I get this error "Cannot find file [Content_Types].xml in zip" every time trying to read a XLSX file 🤷‍♂️

**Comment by SheetJSDev** [comment]
Thanks for reporting (and for the amusing commentary elsewhere :)

The xlsx.js script was not intended to be used on its own -- there are browser builds in the dist/ folder, and nodejs does something different that avoids the problem.

In particular, the mini build uses [cfb](https://github.com/SheetJS/js-cfb) for zip processing while the "full" build uses a modified jszip and assumes it exists.  The CFB library presents a zip file like an OLE blob, with an implied root folder "Root Entry" even though it doesn't exist in the zip archive.

Fortunately there's an easy patch.  The fix should be applied to https://github.com/SheetJS/sheetjs/blob/master/bits/21_ziputils.js#L32 :

```diff
-		var n = k[i].toLowerCase();
+		var n = (zip.FullPaths ? k[i].replace(/^Root Entry[\/]/,"") : k[i]).toLowerCase();
```

**Comment by muslumzaric** [comment]
https://reklamajans.websites.co.in/update/google-reklam-ajansi-hizmetinizde/308177

**Comment by muslumzaric** [comment]
google reklam ajansı

**Comment by tommy7420** [comment]
erinn tjernagel

**Comment by Alebat** [comment]
When will it be published?

**Comment by szilardd** [comment]
I'm trying to develop a new functionality (excel taskpane add-in) and was also trying to use `xlsx.js` in a browser and got a corruption error when opening the xlsx file. 

If you include the `jszip.js` script before `xlsx.js` it works.

```
<script src="jszip.js"></script>
<script src="xlsx.js"></script>
```

**Comment by SheetJSDev** [comment]
@szilardd `make dist` generates all of the standalone browser files.  After doing so, `dist/xlsx.full.min.js` is the desired script.

**Comment by reviewher** [comment]
ef4aec8796c72dc891b619edcd3ef24dde4829d6
