### ISSUE TITLE
Editing workbook

### ISSUE THREAD

**Issue by fthdgn68** [SheetJS/sheetjs#1738]
Hi, I have a problem. I searched but I didn't find anything related my problem. I used FileReader() to upload excel file. It is working. There is no problem here. Later I modified excel and workbook. If I want to download modified excel, I can. But I want to upload to server after modifying. How can I do?

**Comment by SheetJSDev** [comment]
`XLSX.write` can generate an array of bytes or a binary string, which you can upload using standard browser techniques (XHR, FormData, etc).

The [`xhr` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/xhr) shows examples of both uploading and downloading using various APIs and libraries
