### ISSUE TITLE
PRN not defined in xlsx.mini.js

### ISSUE THREAD

**Issue by andwilr** [SheetJS/sheetjs#1760]
When uploading a CSV using xlsx.mini.js I get an error message:

> Uncaught ReferenceError: PRN is not defined

Looking through the code, PRN is used but not defined. What is PRN? Is it supposed to be defined in xlsx.mini.js and just missing (bug), or is there something else I should be loading before xlsx.mini.js for it to work?

Here are the instances expecting PRN.to_workbook to exist:

https://github.com/SheetJS/sheetjs/blob/a81bb78f18960053a03bb3350f31ea54d28245be/xlsx.mini.js#L7939

https://github.com/SheetJS/sheetjs/blob/a81bb78f18960053a03bb3350f31ea54d28245be/xlsx.mini.js#L7968-L7969

**Comment by mingdongtu** [comment]
you can choose diffrent version of the xlsx-sheet (https://cdnjs.com/libraries/xlsx)

**Comment by chenxeed** [comment]
@mingdongtu I've tried the latest version `v0.16.2` and it's still not working. Was it working for you?

Try to use this CSV for example: 
[username.zip](https://github.com/SheetJS/sheetjs/files/4785014/username.zip)


I've made a PR #1908 to help resolve this, but the PR seems not getting any response. :(

**Comment by SheetJSDev** [comment]
@chenxeed 's PR was merged and we've made a few releases since then.
