### ISSUE TITLE
Wrong Value Cell

### ISSUE THREAD

**Issue by LutfiArdiansyah** [SheetJS/sheetjs#1764]
I will take value in cell, when I take value in cell. the value that I get is not appropriate. Please help.

![image](https://user-images.githubusercontent.com/37618863/74944324-72393c00-5428-11ea-8a3d-9664e3deb866.png)

after xlsx read
"A887":{"t":"s","v":"ARC0008.0146"},"B887":{"t":"s","v":"F004"},**"C887":{"t":"n","v":37623.00013888889,"w":"1/2/03"}**,"D887":{"t":"s","v":"ZARC"},"E887":{"t":"s","v":"ARC0008"},"F887":{"t":"s","v":"LE"}

**Comment by SheetJSDev** [comment]
That looks super weird, can you share the file?  If you don't want to make it public, feel free to email dev@sheetjs.com

**Comment by reviewher** [comment]
Same as #2196 :

```js
> new Date("SHOWER SCREEN TOWER 1,2,3")
< Thu Jan 02 2003 00:00:00 GMT-0500 (Eastern Standard Time)
```
