### ISSUE TITLE
sorting rows of xlsx based on one column

### ISSUE THREAD

**Issue by priya0412** [SheetJS/sheetjs#1766]
How to sort the rows in xlsx based on column "Bill Dt" using the sheet js library
[sample.xlsx](https://github.com/SheetJS/sheetjs/files/4232075/sample.xlsx)

**Comment by hshahul** [comment]
Hi,
How you added the style for the excel? can you provide the sample guidance

**Comment by SheetJSDev** [comment]
You can manually perform a sort of the data in JS.  The easiest flow is to convert the data to an array of arrays or array of objects (using `sheet_to_json`), perform a data sort in JS, then write the data back (using `sheet_add_aoa` or `sheet_add_json`).

It's also possible, as long as the cells don't have formulae whose interpretation will change, to just shuffle around keys.  For example, to swap cells D3 and D4: `var cell = ws["D3"]; ws["D3"] = ws["D4"]; ws["D4"] = cell;`
