### ISSUE TITLE
Double value is  not properly converted to json

### ISSUE THREAD

**Issue by roshnitriveni** [SheetJS/sheetjs#1775]
[Book1.xlsx](https://github.com/SheetJS/sheetjs/files/4265274/Book1.xlsx)

While trying to get json for file uploaded getting unnecessary roundings 

![image](https://user-images.githubusercontent.com/61348743/75511452-47e11300-5a14-11ea-93ea-758340a63542.png)

**Comment by SheetJSDev** [comment]
Those are the formatted text values.  To get those text values, pass the option `raw: false` to `sheet_to_json`.

**Comment by roshnitriveni** [comment]
@SheetJSDev 
It is not formatted, you can check in excel Book1.
I am importing Excel to get JSON result, raw: false would not work.
Herein attached excel, my input value is 0.222 so it should give me 0.222 in JSON also


if in excel my input value is 0.2219999999999998 
I ant output  0.2219999999999998  in JSON too, which will not work if I use raw: false

**Comment by roshnitriveni** [comment]
@SheetJSDev 
Please review my last comment, and provide your feedback.

**Comment by znh0503** [comment]
how resolve
