### ISSUE TITLE
XLSX.stream.to_json doesn't ends when a blank row is the last row in Excel sheet.

### ISSUE THREAD

**Issue by rohandhamapurkar** [SheetJS/sheetjs#1779]
### sheetjs/bits/97_node.js
```
		stream._read = function() {
 			if(R > r.e.r) return stream.push(null);
			while(R <= r.e.r) {
				//if ((rowinfo[R-1]||{}).hidden) continue;
				var row = make_json_row(sheet, r, R, cols, header, hdr, dense, o);
				++R;
				if((row.isempty === false) || (header === 1 ? o.blankrows !== false : !!o.blankrows)) {
					stream.push(row.row);
					break;
				}
			}
		};
		return stream;
```

Hi @SheetJSDev !

This piece of code has the ```R > r.e.r``` checking outside of the loop but when a blank row is inserted at the end of a given sheet then the ```if((row.isempty === false) || (header === 1 ? o.blankrows !== false : !!o.blankrows)) ``` condition inside of the while loop isn't executed and the stream does not end.

Ill be submitting a pull request for the same for a fix for this issue that I have found.
Please verify and merge the changes as soon as possible as I am using this library in production in my system.

**Comment by highflying** [comment]
I'm seeing the same issue, for now I'm having to specify the range to skip processing the blank lines at the end.

**Comment by rohandhamapurkar** [comment]
@highflying can you please elaborate more when you say 
"specify the range to skip processing the blank lines"

**Comment by highflying** [comment]
> @highflying can you please elaborate more when you say
> "specify the range to skip processing the blank lines"

I know the range of the sheet that has data in it, so I am specifying it manually, e.g.

```
  const stream = XLSX.stream.to_json(sheet, {
    range: "A1:BN3",
  });
```

When doing this the `end` event gets emitted, without it no `end` event happens.

**Comment by rohandhamapurkar** [comment]
Oh makes sense thanks a lot.
Please do make this change live soon I use this in production.
Thanks again for your response.

**Comment by ev45ive** [comment]
Ok. If i have many files with variable number of rows and I want to stream it as those are big files.

How do I end the stream then?

**Comment by rohandhamapurkar** [comment]
> Ok. If i have many files with variable number of rows and I want to stream it as those are big files.
> 
> How do I end the stream then?
@ev45ive 
Every worksheet object has "!range" property which can be passed in to the ```XLSX.stream.to_json``` function and you can do it dynamically.

**Comment by ev45ive** [comment]
WIth range option stream still seams not to end
```
const filePath = path.join(__dirname, '..',  "data", fileName)

const workbook = xlsx.readFile(filePath, {
  cellDates: true,
});
const sheetName = workbook.SheetNames[0];
const sheet = workbook.Sheets[sheetName];

const stream = xlsx.stream.to_json(sheet, {
  range: sheet['!range'] // added per your comment and don't see any change :-( 
}) 

// This one emits all records
stream.on('data', console.log)

// This never emits "end"
stream.on('end', () => console.log('end'))
```

**Comment by ev45ive** [comment]
@highflying  this is interesting. When I use sheet['!ref'] ( which is "A1:O252" ) stream doesn't end.
```
const stream = xlsx.stream.to_json(sheet, {
  range: sheet['!ref'] // :"A1:O252"
})
```
but when I make it LESS THAN that (by one or more) then it works fine. gets all results and ends stream
```
const stream = xlsx.stream.to_json(sheet, {
  range: "A1:O251"  // sheet['!ref'] minus one row
})
```
Seems like a bug to me, unless I miss something

**Comment by SheetJSDev** [comment]
What version of node are you testing against and can you share the file?

**Comment by ev45ive** [comment]
```
const range = sheet['!ref']!
const stream = xlsx.stream.to_json(sheet, {
  range: range.slice(0, -1) + (parseInt(range.slice(-1)) - 1)
})
``` 
:-O 
node -v
v12.16.2
"xlsx": "^0.16.0"

Here is file (removed private data, left jsut amounts and dates)
[zakup — kopia.xlsx](https://github.com/SheetJS/sheetjs/files/4678628/zakup.kopia.xlsx)

Now i see there are totals in row 252. But it should still produce messed up record and then end or error instead of silently failing, right?

**Comment by ev45ive** [comment]
updated to 0.16.1 . The same issue

```
const stream = xlsx.stream.to_json(sheet, {
  range: sheet['!ref'] 
})
```
stream never ends or errors after last row (totals - see file included above)

**Comment by mpgo13** [comment]
I'm having the same issue. I noticed that setting `blankrows: true` will emit the end event. Here my reproducible problem:

```js
const xlsx = require('xlsx');
const workbook = xlsx.utils.book_new();
const worksheet = xlsx.utils.json_to_sheet([
  {
    a: '1',
    b: '2',
  },
  {},
  {
    a: '11',
    b: '22',
  },
  {},
  {},
]);
xlsx.utils.book_append_sheet(workbook, worksheet);

const stream = xlsx.stream.to_json(workbook.Sheets[workbook.SheetNames[0]], {
  //blankrows: true, // WORKS with blankrows = true
  header: ['a', 'b'],
});

let closed = false;

stream.on('data', console.log);
stream.on('close', () => console.log('CLOSE'));
stream.on('end', err => {
  console.log('END', err);

  closed = true;
});

// for the event loop
const interval = setInterval(() => {
  if (closed) {
    clearInterval(interval);
  }
}, 100);

```

**Comment by SheetJSDev** [comment]
Can someone check if the following patch fixes the problem (and if so, please feel free to send a PR):

https://github.com/SheetJS/sheetjs/blob/master/bits/97_node.js#L111-L112

```diff
                stream._read = function() {
-                       if(R > r.e.r) return stream.push(null);
                        while(R <= r.e.r) {
                                //if ((rowinfo[R-1]||{}).hidden) continue;
                                var row = make_json_row(sheet, r, R, cols, header, hdr, dense, o);
                                ++R;
                                if((row.isempty === false) || (header === 1 ? o.blankrows !== false : !!o.blankrows)) {
                                        stream.push(row.row);
-                                       break;
+                                       return;
                                }
                        }
+                       return stream.push(null); // <-- ADD THIS LINE
                };
                return stream;
        };
```

The most obvious guess is that in object mode, Readable streams are always expected to push a value.  The `null`, which would trigger the end of stream, would not be pushed by the function if the last row is empty AND blank rows are skipped.
