### ISSUE TITLE
use defval then it read many invalid row data

### ISSUE THREAD

**Issue by EY5740** [SheetJS/sheetjs#1781]
`XLSX.utils.sheet_to_json(worksheet, { blankrows: true, defval: null })`
use **defval** , then read Blank and invalid data !

**Comment by reviewher** [comment]
`XLSX.utils.sheet_to_json(worksheet)` skips blank rows and does not insert any default values.

`XLSX.utils.sheet_to_json(worksheet, { blankrows: true })` does not skip blank rows and does not insert any default values.  Blank rows will be `{}`

`XLSX.utils.sheet_to_json(worksheet, { blankrows: true, defval: null })` does not skip blank rows and fills default values.  Blank rows will be filled with the default value.

The current behavior makes sense.  If you think the behavior is wrong, explain what you expect it to do and we can reopen the issue.
