### ISSUE TITLE
encoding problem in Hebrew language

### ISSUE THREAD

**Issue by BaruchHeroApps** [SheetJS/sheetjs#1783]
router.get('/xlsx', async (request,  response) => {
    var xlsFile = fs.readFileSync('./uploads/temp/excel.xlsx');
    var html = XLSX.read(xlsFile, { type:'buffer' });
    const finalFile = XLSX.write(html, { type: 'binary', bookType: 'html' });
    response.send(finalFile);
});

Response:
<table>
		<tr>
			<td t="z" id="sjs-B1"></td>
			<td t="z" id="sjs-C1"></td>
			<td t="z" id="sjs-D1"></td>
			<td t="z" id="sjs-E1"></td>
			<td t="z" id="sjs-F1"></td>
		</tr>
		<tr>
			<td t="s" id="sjs-B2">×××¢×</td>
			<td t="s" id="sjs-C2">××©×××</td>
			<td t="s" id="sjs-D2" xml:space="preserve">××¢×¨××ª </td>
			<td t="s" id="sjs-E2">×ª××¨×× ×××¦××¢</td>
			<td t="s" id="sjs-F2">×××¦×¢</td>
		</tr>
		<tr>
			<td rowspan="8" t="s" id="sjs-B3">×¢× ×¤×¨×¡×× ×××××</td>
			<td t="s" id="sjs-C3">×××§×© ××× ×× ×××©××× ××ª ××¢×××¨ ×¢× ×× ×××××¨ ××××××
				×©××××× ××××× ××× ×× ××ª×</td>
			<td t="s" id="sjs-D3">×× ××©×× ××¦××¨× ××××× ×× ×××¤×¡××</td>
			<td t="z" id="sjs-E3"></td>
			<td t="z" id="sjs-F3"></td>
		</tr>
		<tr>

**Comment by SheetJSDev** [comment]
Try exporting with type `'string'` or type `'buffer'`.

If those don't work, can you share the original file?

**Comment by BaruchHeroApps** [comment]
> Try exporting with type `'string'` or type `'buffer'`.
> 
> If those don't work, can you share the original file?

Thanks it's work with 'string' but I dont get the original style....so this package can't help me...Thanks :)
