### ISSUE TITLE
Missing data when reading a file

### ISSUE THREAD

**Issue by tristansokol** [SheetJS/sheetjs#1787]
Hello and thank you for your open source work!

I am reading in a `.xlsx` and everything was going great util I wasn't able to read cell B8. Digging into it deeper, it looks like the worksheet is missing some seemingly random values. For example it seems to parse C8 which seems identical to me, but not B. This is also true for some other cells, for example all of row 9 in not in the worksheet object. 

Any ideas as to what I am missing? Happy to share the file privately, I'd rather not post it online though. 

```
//console.log(worksheet)
        ...
        A8: {
          t: 's',
          v: '2501 Beacon Hill',
          r: '<t>2501 Beacon Hill</t>',
          h: '2501 Beacon Hill',
          w: '2501 Beacon Hill'
        },
        C8: { t: 'n', v: 1242.7550200803212, w: '1,242.76' },
        ...
```
![image](https://user-images.githubusercontent.com/867661/76034503-bafef380-5f04-11ea-9007-e0c2b3e02448.png)
`"xlsx": "^0.15.5"`

**Comment by tristansokol** [comment]
Thank you, just sent.

**Comment by SheetJSDev** [comment]
Basically, the file had a formula set but no data, so the parser was unable to extract a value. 
 https://github.com/SheetJS/sheetjs/issues/1657 is an issue with the same root cause
