### ISSUE TITLE
Date and Month are swiped when use cellDates

### ISSUE THREAD

**Issue by jrizani** [SheetJS/sheetjs#1788]
I have date 04/03/2020 with format dd/mm/yyyy in excel, and I use it to my javascript:
```javascript
var workbook = XLSX.read(data, {
                        type: 'binary',
                        cellDates: true,
                    });
```
and use it to convert to json:
```json
XLSX.utils.sheet_to_json(workSheet);
```

but I got 03/04/2020 in the result. How can I insert excel date format before it convert?

**Comment by SystemParadox** [comment]
By default SheetJS follows Excel behaviour, which is to aggressively try to intepret strings into numbers and dates. When it does so, it always uses the stupid US date format.

You can set `raw: true` to prevent this, which should help if you're importing a CSV file or you've got dates in cells with a type of string.

**Comment by SheetJSDev** [comment]
Strings are parsed as dates using the JS Date parsing facilities.  They for the most part default to en-US, but the spec says:

> in general, the value produced by Date.parse is implementation-defined when given any String value that does not conform to the Date Time String Format

Short of a special date parser (which may happen in the future) or rollout of the new `Temporal` API, @SystemParadox spelled out the best approach: just use `raw: true` and post-process the text.

**Comment by paymaan73** [comment]
let body = XLSX.read(buffer, { type: 'buffer', cellDates: false, raw: true });

    let wb = body.Sheets[body.SheetNames[0]];

    let toJson: object[] = XLSX.utils.sheet_to_json(wb, {
      blankrows: false,
      defval: '',
      raw: false, 
      dateNF: 'dd/mm/yyyy' 
    });
