### ISSUE TITLE
[Question] How can I get width/height of a cell ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [SheetJS/sheetjs#1789]
Thanks for great package. I read through README but found no way to get `width/height` of a cell ?
So is this possible to get `width/height` of a cell by `sheetjs` ?
Or how can I get width of a specific column and height of specific row ?
```js
var width = cell.w;
var height = cell.h;
```

**Comment by SheetJSDev** [comment]
Width/height are properties of the column / row respectively.   You need to inspect those properties:

- Row Height https://docs.sheetjs.com/#row-properties
- Column Width https://docs.sheetjs.com/#column-properties

**Comment by TranBaVinhSon** [comment]
@SheetJSDev Thanks for the quick response. But I have another problem that how I can get the `RowInfo` and `ColInfo` object from a cell ? (because I want to get width/height of a cell)
```js
var address = "A1";

/* Get worksheet */
var worksheet = workbook.Sheets[sheetName];

/* Find desired cell */
var cell = worksheet[address];

var rowInfo = cell.rowInfo(); // how can I do that
```

I try to access RowInfo and ColInfo from worksheet same as on README, but it returns `undefined`
```js
var rows = worksheet[!"rows"]
```
What I am missing? 
Hope to hear from you soon.

**Comment by TranBaVinhSon** [comment]
@SheetJSDev Could you take a look at my question? Many thanks!

**Comment by SheetJSDev** [comment]
```js
var addr = XLSX.utils.decode_cell(address);
if(worksheet["!rows"] && worksheet["!rows"][addr.r]) row_height = worksheet["!rows"][addr.r].hpx;
if(worksheet["!cols"] && worksheet["!cols"][addr.c]) column_width = worksheet["!cols"][addr.r].wpx;
```

**Comment by TranBaVinhSon** [comment]
@SheetJSDev Thanks for the quick response again. But `worksheet["!rows"]` and `worksheet["! cols"]` always return `undefined` .
Do I need to change anything in my excel file ?

This is my excel file: [test.xlsx](https://github.com/SheetJS/sheetjs/files/4304791/test.xlsx)

**Comment by TranBaVinhSon** [comment]
@SheetJSDev Could you take a look at my comment ? Thanks in advance!

**Comment by TranBaVinhSon** [comment]
@SheetJSDev I finally figured out `cellStyles` option but the column's width I get by sheetjs is totally different from the actual width of column in excel file 
https://github.com/SheetJS/sheetjs/issues/591#issuecomment-289469196
