### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' | after "yarn add xlsx"

### ISSUE THREAD

**Issue by sharpapp-mareklanduch** [SheetJS/sheetjs#1790]
Hi

I'm using yarn so I run "yarn add xlsx". I didn't do any imports just yarn add xlsx and I've got this error.
![image](https://user-images.githubusercontent.com/5566853/76083089-0ff64480-5fad-11ea-8bb4-83320fd57fc5.png)
Page cannot load. 
Compilation is successful 
![image](https://user-images.githubusercontent.com/5566853/76083048-f7862a00-5fac-11ea-9fa7-30451b3f5cd1.png)

I found out that when I'll do:
npm install xlsx
yarn install

then everything is working just fine, so I developed something simple and deployed my project on linux docker without "npm install xlsx" and it's also working there.
I am suspicious that maybe something wrong with the file system or fs library?

Anybody had similar problem?

**Comment by SheetJSDev** [comment]
This looks like an issue with yarn.  Raise an issue with them  https://github.com/yarnpkg/yarn and reopen the issue if we have to do something with the xlsx module.

**Comment by sharpapp-mareklanduch** [comment]
@SheetJSDev 
I've got new information.  If you'll do "yarn add xlsx" and then "yarn start" it'll work but if you'll checkout branch when xlsx is in package.json and then do "yarn install" then it's not working or if you'll do "yarn install" after you did "yarn add xlsx" it will also fail.

I can see this warnings when doing yarn install
![image](https://user-images.githubusercontent.com/5566853/76316630-3254ce80-62db-11ea-91c9-ecabdaf04464.png)

So in my package.json I changed
    "react-scripts": "^3.4.0", 
to ~3.3.1 with no luck and then to 3.2.0  and it's **WORKING**

@SheetJSDev could you reopen issue? So it's not working with newer version of react-scripts?
