### ISSUE TITLE
Why isn't there a BUY option for Pro Version?

### ISSUE THREAD

**Issue by djrobby** [SheetJS/sheetjs#1794]
As per the title. It seems odd in 2020 that you wouldn't simply have a BUY NOW link on your site for the Pro version? I understand that you might want to price it differently for every customer but...considering you guys are JS experts, isn't that logic something you can easily implement? Why the friction of emailing?

**Comment by SheetJSDev** [comment]
In our experience, people use ~10% of excel's features, but everyone uses a different 10%.  There are many "pet features" which turn out to be incredibly complex.

For example, the cloud Microsoft Forms offering (as part of Office 365) just stores a pointer to a form in the XLSX export, so we have no programmatic way of getting the underlying results.  Excel shows the result in the UI, but doesn't actually save the result in the file.  Most of our users are not deep experts in the file formats and may not understand that situation (honestly, we didn't know this happened until a current customer asked us about it)

Asking people to email first is more about us ensuring that SheetJS software can solve the problem.   Many customers started by asking if it were possible to replicate a certain file, or preserve a complex file when making changes, or recalculate part of a workbook.  They don't necessarily know the full details of what they're using (oftentimes the files are coming from third party sources) and don't have the deep file format experience required to dig in and determine what they need, so the presence of a complex form wouldn't really help.  The "friction of email" allows us an opportunity to discuss the exact problems.

PS: many of our customers are teams at government/military agencies or corporations.  Some have specific requirements like verifying that we are based in the United States and that the legal entity is owned by US citizens.  That's a conversation best conducted over email or a phone call.

**Comment by djrobby** [comment]
So, what's the price and how do I buy it? All I wanted to do was convert an HTML table to XLSX and along the way, style the cells, columns & rows to application requirements. Thanks to Github issue #913 and alike, I learned (from your comments) that this was only available in the "Pro compendium".

PS: We work with the government too and have been since 2006. They verified our company's official address of incorporation/operation and governing body's citizenship via https://sam.gov, not by emailing us.
