### ISSUE TITLE
XLSX - Apply cell style

### ISSUE THREAD

**Issue by MUTHUKUMAR73737** [SheetJS/sheetjs#1795]
I want to apply style for cell(eg- text in bold). But it's not working for me.

code - **workbook.Sheets['worksheet1'].A1.s = { font: {bold: true } };**

Can anyone pls help me on this?

**Comment by imir-hoxha** [comment]
try if this helps: 
var ws_data = [['hello']];
var ws = XLSX.utils.aoa_to_sheet(ws_data);
 ws['A1'].s =  {font: {
        name: 'Arial',
        sz: 12,
        color: { rgb: "#FF000000" },
        bold: true,
        italic: false,
        underline: false
      }}

**Comment by MUTHUKUMAR73737** [comment]
> try if this helps:
> var ws_data = [['hello']];
> var ws = XLSX.utils.aoa_to_sheet(ws_data);
> ws['A1'].s = {font: {
> name: 'Arial',
> sz: 12,
> color: { rgb: "#FF000000" },
> bold: true,
> italic: false,
> underline: false
> }}

@imir-hoxha - Not able to export with cell styling.  I am using xlsx(version - 0.14.1). Is there any option to implement cell styling without xlsx pro version?

**Comment by imir-hoxha** [comment]
use this: https://github.com/soldemuth/js-xlsx. it's another branch

**Comment by SheetJSDev** [comment]
We don't know when / if it will be added to the open source build, but it's definitely a post-1.0 feature
