### ISSUE TITLE
Unrecognized tag: Numberformat|Workbook,false|Styles,false

### ISSUE THREAD

**Issue by panraj01** [SheetJS/sheetjs#1800]
Why i try to read an old xls file, i get this error. I tried to update the xml string to update the Numberformat to "NumberFormat" but then it failed in next HTML tag.  Can you please look. Also, the live demo at sheetJS also not able to parse thru the file. let me know if you need more info.

**Comment by SheetJSDev** [comment]
Can you share the file?  If you can't do it publicly, feel free to email dev@sheetjs.com
