### ISSUE TITLE
Bug in function fuzzydate(s), dist/xlsx.js 

### ISSUE THREAD

**Issue by Microsxema** [SheetJS/sheetjs#1802]
```
function fuzzydate(s) {
	var o = new Date(s), n = new Date(NaN);
	var y = o.getYear(), m = o.getMonth(), d = o.getDate();
	if(isNaN(d)) return n;
	if(y < 0 || y > 8099) return n;
	if((m > 0 || d > 1) && y != 101) return o;
	if(s.toLowerCase().match(/jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec/)) return o;
	if(s.match(/[^-0-9:,\/\\]/)) return n;
        return o;
}
```
In the line where "if((m > 0 || d > 1) && y != 101) return o;" variable "m" (Month in Date) beggining with zero.
True variant "if((m >= 0 || d > 1) && y != 101) return o;"

If the month is January, then the data will not be determined correctly

**Comment by SheetJSDev** [comment]
Chrome is very aggressive in date parsing:

```js
// this is Jan 3 2001 according to Chrome:
new Date("Although the rest of the world switched to TypeScript, Jane still uses ECMAScript 3")
```

There are other bad cases where `m = 0`, hence the case.  If you have a sample input that you think is incorrect, share it and we'll revisit

**Comment by Microsxema** [comment]
Im working in Node js (if it is important). 
Try this data here: DateTime;01.01.2019 -> month is the number in the cell (this is important)!

As a result, in "console log" January is defined as a string: {t: "s", v: "01.01.2019"}.
When the rest of the months are fine: {t: "s", v: "01.01.2019"}
{t: "n", v: 43468.00019675926, w: "2019-03-01 00:00:17"}
{t: "n", v: 43469.00019675926, w: "2019-04-01 00:00:17"}
{t: "n", v: 43470.00019675926, w: "2019-05-01 00:00:17"}

Look file: https://github.com/Microsxema/Bag-In-SheetJS
