### ISSUE TITLE
Cannot find file [Content_Types].xml in zip

### ISSUE THREAD

**Issue by sion005** [SheetJS/sheetjs#1803]
Greetings. I've been using your library to read xls files with no issues. However when I try to read any xlsx file, I get the following error:

Uncaught (in promise) Error: Cannot find file [Content_Types].xml in zip
    at getzipfile (xlsx.js:2822)
    at getzipstr (xlsx.js:2833)
    at parse_zip (xlsx.js:20373)
    at read_zip (xlsx.js:20707)
    at Object.readSync [as read] (xlsx.js:20773)

I've tried to use different files, even changed the extension to .zip to confirm the existence of the [Content_Types].xml. Any ideas on how to fix this issue?
Here is how I'm doing to the reading:

```
return new Promise((resolve, reject) => {
     fileReader.onerror = () => {
          fileReader.abort();
          reject(new Error("Error"));
    };

    fileReader.onload = () => {
          resolve(fileReader.result);
    };

   fileReader.readAsBinaryString(file);      
})
.then(r => { return read(r, {type: 'binary'}); })
```

**Comment by SheetJSDev** [comment]
It looks like you might be using the `xlsx.min.js` file directly.  If you are using a script tag, can you reference `xlsx.full.min.js` from the dist directory?

**Comment by Afellman** [comment]
Got the same using the npm package and requiring via node.

**Comment by SheetJSDev** [comment]
That's odd, can you share a sample file and how you are reading the file (`readFile`, receiving a Buffer in http.server, etc)?

**Comment by Afellman** [comment]
oops, I realized the .xlsx file was corrupted. My bad. Seems fine now

**Comment by SheetJSDev** [comment]
@sion005 if you can share a file we'll take a closer look

**Comment by asherccohen** [comment]
Hi, I'm getting this error too while working on a feature to merge multiple .xlsx files together.

I'm reading with the file reader API and my approach is to first concat the ArrayBuffers then read the whole buffer to generate a sheet.

Something like this:

https://codesandbox.io/s/interesting-pine-sjj71

I have added two excel files to try. Also notice that this works perfectly for csv files, infact I have attached two csv files to test too.

Is the logic to concatenate buffers somehow breaking the excel files?

**Comment by sion005** [comment]
> Hi, I'm getting this error too while working on a feature to merge multiple .xlsx files together.
> 
> I'm reading with the file reader API and my approach is to first concat the ArrayBuffers then read the whole buffer to generate a sheet.
> 
> Something like this:
> 
> https://codesandbox.io/s/interesting-pine-sjj71
> 
> I have added two excel files to try. Also notice that this works perfectly for csv files, infact I have attached two csv files to test too.
> 
> Is the logic to concatenate buffers somehow breaking the excel files?

I managed to figure out the problem later. I do not remember witch function was causing it, so you will need to do some debug, but one of the functions of the xlsx.js it's incorrect and it's causing the bug. You can find the correct version on the xlsx.mini.js. Just paste the correct version over the incorrect one and it will fix the issue.

**Comment by harshini66** [comment]
resolved by integrating xlsx.full.min.js instead of xlsx.min.js
