### ISSUE TITLE
Linebreak for json_to_sheet

### ISSUE THREAD

**Issue by IsaacEB1** [SheetJS/sheetjs#1807]
Hi! I'm trying to perform a linebreak in some cells for an specific column, I'm not sure if this is supported by the community edition, so I'm asking if it is or it is only for Premium versions.
Thanks!

**Comment by SheetJSDev** [comment]
By default Excel renders newline characters as a space.  The option to force a newline to be rendered as a separate line is controlled by "Wrap Text" option, which is a style on the cells and is covered in our Pro builds

**Comment by samiksha-syn** [comment]
@IsaacEB1 @SheetJSDev 
Can you please add line of code to implement this
I am trying for long time
kindly help
