### ISSUE TITLE
Uncaught ReferenceError: cptable is not defined (Electron)

### ISSUE THREAD

**Issue by cooperfrench95** [SheetJS/sheetjs#1808]
## Issue

I am facing an issue when building a Vue.js electron application created with [vue-cli electron builder](https://github.com/nklayman/vue-cli-plugin-electron-builder) plugin.

The app runs fine in development mode but when I run `vue-cli-service electron:build --mode production` it compiles and builds fine, but upon opening the built application I get a white screen when opening the app and the following error in the console:

```
Uncaught ReferenceError: cptable is not defined
    at index.js:13356
    at Object.<anonymous> (index.js:13352)
    at Object.<anonymous> (index.js:30368)
    at n (index.js:30)
    at Object.<anonymous> (index.js:1940)
    at n (index.js:30)
    at Object.<anonymous> (index.js:1892)
    at n (index.js:30)
    at Object.<anonymous> (index.js:2106)
    at Object.<anonymous> (index.js:2156)
```

Looking at the source, the culprit is here:
![image](https://user-images.githubusercontent.com/44951144/77134084-819bbb80-6aa0-11ea-8153-fb6acb930552.png)

This error does not happen when running the app as a regular webapp in the browser. XLSX is installed via NPM.

## Versions

Vue 2.6.11
Electron 6.0.0
vue-cli-plugin-electron-builder 1.4.6
XLSX: 0.15.6

**Comment by SheetJSDev** [comment]
Thanks for sharing!  Not familiar with vue-cli-plugin-electron-builder, can you create a small sample project so that we can clone and take a look?

PS: The screenshot suggests that XLSX version 0.9.13 is being pulled.

**Comment by cooperfrench95** [comment]
@SheetJSDev It looks like it is an issue with another repo, `vue-xlsx-table` which has the older version of xlsx as a dependency.
