### ISSUE TITLE
Bug in function fuzzydate(s), dist/xlsx.js 

### ISSUE THREAD

**Issue by Microsxema** [SheetJS/sheetjs#1809]
Im working in Node js (if it is important).
Try this data here: DateTime;01.01.2019 -> month is the number in the cell (this is important)!

As a result, in "console log" January is defined as a string: {t: "s", v: "01.01.2019"}.
When the rest of the months are fine: {t: "s", v: "01.01.2019"}
{t: "n", v: 43468.00019675926, w: "2019-03-01 00:00:17"}
{t: "n", v: 43469.00019675926, w: "2019-04-01 00:00:17"}
{t: "n", v: 43470.00019675926, w: "2019-05-01 00:00:17"}

Look file: https://github.com/Microsxema/Bag-In-SheetJS

**Comment by reviewher** [comment]
Grouping into #1300
