### ISSUE TITLE
File is corrupt after download on Lighting Component (Aura)

### ISSUE THREAD

**Issue by viviramji** [SheetJS/sheetjs#1810]
Greetings,

I'm a salesforce developer and need to export some data into XLSX, after I followed these steps [Issue 1445](https://github.com/SheetJS/sheetjs/issues/1445)  I get the XLSX file but it's corrupt only when I use it in a lighting component. 

I replicate this example [from freakyjolly](https://www.freakyjolly.com/create-and-download-xsl-excel-from-json-response-data-in-webpage/) on [Play Code](https://playcode.io/518431) and  file was downloaded correctly using  XLSX.writeFile(...) and FileSaver Lib, both work perfectly on Play Code but in Lighting context it looks like something is wrong at the end.

I debug all the process of exporting on Chrome and wb and ws are OK the problem is when I will call XLSX.writeFile(...) it looks like lighting is locking sheetsFiles or something like that, I used both FileSaver and XLSX.writeFile(...).

Here is my helper function

```javascript
handleJsonToExcel: function(component){
        var createXLSLFormatObj = [],
            HEADERS = [...],
            data = JSON.parse(JSON.stringify(component.get('v.jsonData')));
        console.table(data);
        
        /* File Name */
        var filename = "fileName.xlsx";
        
        /* Sheet Name */
        var ws_name = "sheet1";
        
        if (typeof console !== 'undefined') console.log(new Date());
        var wb = XLSX.utils.book_new(),
            ws = XLSX.utils.json_to_sheet(data);
        
        /* Add worksheet to workbook */
        XLSX.utils.book_append_sheet(wb, ws, ws_name);
        
        /* Write workbook and Download */
        if (typeof console !== 'undefined') console.log(new Date());
        XLSX.writeFile(wb, filename);
        if (typeof console !== 'undefined') console.log(new Date());             
    },
```
Add this change on Static Resource xlsx.js

`var XLSX = {};
window.XLSX = XLSX;`

Thanks.

**Comment by SheetJSDev** [comment]
There might be an issue with the functions that actually force the download, can you test by generating a base64 string?

```js
var b64 = XLSX.writeFile(wb, {bookType: "xlsx", type: "base64"});
console.log(b64);
```

Then try decoding it locally and see if the file is valid.

**Comment by viviramji** [comment]
```javascript
 XLSX.writeFile(wb, filename);
var b64 = XLSX.writeFile(wb, {bookType: "xlsx", type: "base64"}); <-error
console.log(b64);
```

I got this exception:

`Uncaught Error in $A.getCallback() [o.file.lastIndexOf is not a function]`
`Callback failed: apex://className/ACTION$exportData`

This is doc where error occurs:
https://myOrg.lightning.force.com/resource/.../XLSX on line 20851 : 32

Do I need another lib or am I doing the wrong way?

**Comment by SheetJSDev** [comment]
That should have been

```
var b64 = XLSX.write(wb, {bookType: "xlsx", type: "base64"}); // use write, not writeFile
```

**Comment by viviramji** [comment]
Hi! 

After a couple of minutes of trying to decode b64 to xlsx 😅 I did it but I compare both b64 from playCode (works perfectly) 
Pre view:
`...AF9yZWxzLy5yZWxzUEsBAhQACgAAAAAA+Vl0UNA/ZN0tAgAALQIAABoAAAAAAAAAAAAAAAAAG68AAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzUEsFBgAAAAAJAAkAPgIAAICxAAAAAA==
`
and lighting cmp (nor work)
Pre view:
`...AAAAAAAAO2Lqj2SBwAAkgcAABMAAAAAAAAAAAAAAAAAPS4AAFtDb250ZW50X1R5cGVzXS54bWxQSwUGAAAAAAkACQA+AgAAADYAAAAA`

On PlayCode the b64 string was larger than lightning I'm using the same json data.

Any other advice?

**Comment by SheetJSDev** [comment]
Thanks for looking into this!  Can you check if it affects other formats?  Using your original writeFile code, try writing with filenames:

- `test.xls` (BIFF8 XLS)
- `test.xlsb` (XLSB)
- `test.xml` (SpreadsheetML)
- `test.csv` (CSV)
- `test.htm` (HTML)

Are they all corrupt?

**Comment by viviramji** [comment]
Hi!
```javascript
handleJsonToExcel: function(component){
        var createXLSLFormatObj = [],
            filename = 'datos.xlsx',
            ws_name = 'freakySheet',
            HEADERS = [...],
            data = JSON.parse(JSON.stringify(component.get('v.jsonData')));
        
        if (typeof console !== 'undefined') console.log(new Date());
        var wb = XLSX.utils.book_new(),
            ws = XLSX.utils.json_to_sheet(data);
        
        /* Add worksheet to workbook */
        XLSX.utils.book_append_sheet(wb, ws, ws_name);
        
        /* Write workbook and Download */
        if (typeof console !== 'undefined') console.log(new Date());
        //XLSX.writeFile(wb, filename);
        var b64 = XLSX.write(wb, {bookType: "xls", type: "base64"});
        console.log(b64);
        if (typeof console !== 'undefined') console.log(new Date());             
    },
```
I used `xls` and it worked the `b64` to `xls`, how can I auto download without passing b64 to binary and so, using fileSaver? or can I just change extension file to xls and use

`XLSX.writeFile(wb, filename);`

thanks.

**Comment by viviramji** [comment]
Hi!!! 

I thanks a lot guys I solved using this

***This works for me***
```javascript
handleJsonToExcel: function(component){
        var createXLSLFormatObj = [],
            HEADERS = [...],
            data = JSON.parse(JSON.stringify(component.get('v.jsonData')));
        console.table(data);
        
        /* File Name */
        var filename = "fileName.xls"; //change extension
        
        /* Sheet Name */
        var ws_name = "sheet1";
        
        if (typeof console !== 'undefined') console.log(new Date());
        var wb = XLSX.utils.book_new(),
            ws = XLSX.utils.json_to_sheet(data);
        
        /* Add worksheet to workbook */
        XLSX.utils.book_append_sheet(wb, ws, ws_name);
        
        /* Write workbook and Download */
        if (typeof console !== 'undefined') console.log(new Date());
        XLSX.writeFile(wb, filename);
        if (typeof console !== 'undefined') console.log(new Date());             
    },
```

**Comment by viviramji** [comment]
Hi!!! 

I thanks a lot guys I solved using this

***This works for me***
```javascript
handleJsonToExcel: function(component){
        var createXLSLFormatObj = [],
            HEADERS = [...],
            data = JSON.parse(JSON.stringify(component.get('v.jsonData')));
        console.table(data);
        
        /* File Name */
        var filename = "fileName.xls"; //change extension
        
        /* Sheet Name */
        var ws_name = "sheet1";
        
        if (typeof console !== 'undefined') console.log(new Date());
        var wb = XLSX.utils.book_new(),
            ws = XLSX.utils.json_to_sheet(data);
        
        /* Add worksheet to workbook */
        XLSX.utils.book_append_sheet(wb, ws, ws_name);
        
        /* Write workbook and Download */
        if (typeof console !== 'undefined') console.log(new Date());
        XLSX.writeFile(wb, filename);
        if (typeof console !== 'undefined') console.log(new Date());             
    },
```

Thanks again, 
Cheers!

**Comment by SheetJSDev** [comment]
Obviously XLSX should also work, if it's not that's an issue somewhere.  Is there a reproducible environment to test this?

**Comment by viviramji** [comment]
Of Course, 
All the time I've been testing it in a sandbox org. I can set up a clean PlayGround Salesforce Dev Org.

*Thanks*.

**Comment by mrveress** [comment]
Guys, just fyi
If you want to have xlsx in LWC/Aura - you also need to load script that called 'jszip' before xlsx.js.
This is the cause why you will have corrupted xlsx.
