### ISSUE TITLE
Cell raw value is different than the actual value

### ISSUE THREAD

**Issue by lsborg** [SheetJS/sheetjs#1814]
Thanks for this great tool! 

I noticed that a cell value differs from the actual value in the spreadsheet. Here is the parsed content of cell C172 from **NTN-B Principal 150515** spreadsheet (the actual value is 0.0324): 

```
  C172: 
   { ixfe: 64,
     XF: { ifnt: 0, ifmt: 10, flags: 1, fStyle: 0, data: undefined },
     v: 0.032400000000000005,
     t: 'n',
     w: '3.24%' },
```

And [here](https://drive.google.com/file/d/0B2JuS0a1c4KVUlN3clgzMUttRHc/edit?usp=sharing) is the excel file.

**Comment by SheetJSDev** [comment]
To ensure the linked files are not lost, we've added a special note in https://oss.sheetjs.com/notes/lobugs/ including the test artifacts
