### ISSUE TITLE
how to make all cells of a given column have the same type?

### ISSUE THREAD

**Issue by sibelius** [SheetJS/sheetjs#1882]
I'm following this code https://github.com/SheetJS/sheetjs/issues/885#issuecomment-344484741

My usecase is to generate a template excel with only headers to be used as an import for new users

I'd like to have some collums to be of type Date, so they will properly parsed after user fill the template

this is my current approach:

- generate sheet from given json, we don't have any data, just header
```jsx
const ws = XLSX.utils.json_to_sheet([], { header: Object.values(columns) });
```

- generate same cells in given collums with proper type (1000 rows with Date type)
```jsx
const DATATYPE_ROWS = 1000;

export const getCellsWithDataTypes = (v, dataTypes) => {
  const column = v[0];

  // generate from 2 to 1000
  const wsData = [...Array(DATATYPE_ROWS).keys()].reduce((acc, i) => {
    const key = `${column}${2 + i}`;

    return {
      ...acc,
      [key]: {
        t: dataTypes[v],
        v: ' ',
      },
    };
  }, {});

  return wsData;
};
```

I've also tried to use the code from https://github.com/SheetJS/sheetjs/issues/885#issuecomment-344484741

```jsx
export const formatRange = (ws, C: string, fmt: string) => {
  const range = XLSX.utils.decode_range(ws['!ref']);

  for (let i = range.s.r + 1; i <= range.e.r; ++i) {
    /* find the data cell (range.s.r + 1 skips the header row of the worksheet) */
    const ref = XLSX.utils.encode_cell({ r: i, c: C });

    /* if the particular row did not contain data for the column, the cell will not be generated */
    if (!ws[ref]) continue;
    /* `.t == "n"` for number cells */
    if (ws[ref].t !== 'n') continue;
    /* assign the `.z` number format */
    ws[ref].z = fmt;
  }
};
```

neither of them worked well

I think I'm missing to modify the `!ref`

**Comment by SheetJSDev** [comment]
Please follow #1339 for more updates
