### ISSUE TITLE
feature request: camelCase naming everywhere

### ISSUE THREAD

**Issue by alexey2baranov** [SheetJS/sheetjs#1884]
What is the reason for that naming?
```js
XLSX.utils.sheet_to_csv
workbook.SheetNames[0]
```

**Comment by SheetJSDev** [comment]
SheetJS is a very old library by modern JS standards, and we have tried hard not to break backwards compatibility without very careful consideration.

snake_case in methods and PascalCase in properties were early decisions based on our C experience, while camelCase like `writeFile` were chosen to mirror the NodeJS equivalent name.  In hindsight, it would have made more sense to use camelCase everywhere.

Modifying the core schema is not easy and it would make sense to group all of the related changes together in one release (for example, with modern browsers an array of arrays is easier to optimize than the large object).  However, adding function aliases is easy.  We'd accept a PR for adding aliases for the API function names (e.g. XLSX.utils.sheetToCsv aliasing `sheet_to_csv`).
