### ISSUE TITLE
Detect download or export of excel file completed

### ISSUE THREAD

**Issue by eafiontzi** [SheetJS/sheetjs#1886]
Hello, I am using sheetjs to export a json file and download an excel file like this:

`XLSX.writeFile(workbook, 'test')`

Is there a way to detect that the file is successfully exported (writeFile is complete) or that the download has finished? The `writeFile` function returns a blob with a URI, can I use that somehow?

Thanks in advance for the reply

**Comment by SheetJSDev** [comment]
Unfortunately no :( the approach used in modern browsers is to create a link with a download attribute and trigger the click event.  The last time I looked at it, the browser didn't give any feedback when the download was completed.
