### ISSUE TITLE
First uploaded file parses but next uploaded file does not parse

### ISSUE THREAD

**Issue by DavidKHahn** [SheetJS/sheetjs#1892]
Hello,

I'm trying to parse xlsx files into my database after uploading with multer.  The first file uploaded has no issue being parsed and uploaded into SQL after initial server start but problem arises with the succeeding files coming in afterwards.

**Main problem**: new files after first not being parsed after uploading the first file.

My current code set up for the parsing looks like this:

```
export async function insertDbfHeader(headerPath: string, tableName: string) {
  const mySQLPool = getMySqlPool(databaseName);
  const connection = await mySQLPool.getConnection();
  const workbook = XLSX.readFile(path.resolve(__dirname, headerPath), { cellDates: true });
  const sheet_name_list = workbook.SheetNames;
  const xlData = XLSX.utils.sheet_to_json(workbook.Sheets[sheet_name_list[0]]);

  for (let i = 0; i < xlData.length; i++) {
    const rowObject: any = xlData[i];
    const values = Object.values(rowObject);
    let date = moment(new Date(values[0] as any)).format("YYYY/MM/DD");

    let savekey: any = values[20];
    savekey = parseInt(savekey);

    let ac_desc1 = values[5];
    let ac_desc2 = values[6];
    let cp_desc1 = values[10];
    let cp_desc2 = values[11];
    let cp_desc3 = values[12];
    let facility = values[22];

    const query = `INSERT INTO ${tableName} (AC_DESC1, AC_DESC2, CP_DESC1, CP_DESC2, CP_DESC3, SAVEKEY, FACILITY, DATE)  SELECT * FROM (SELECT  '${ac_desc1}' as v1, '${ac_desc2}' as v2, '${cp_desc1}' as v3, '${cp_desc2}' as v4, '${cp_desc3}' as v5, '${savekey}' as v6, '${facility}' as v7, '${date}' as v8 ) AS tmp WHERE NOT EXISTS (SELECT AC_DESC1, AC_DESC2, CP_DESC1, CP_DESC2, CP_DESC3, SAVEKEY, FACILITY, DATE FROM ${tableName} WHERE SAVEKEY = '${savekey}' AND AC_DESC1='${ac_desc1}' AND AC_DESC2='${ac_desc2}') LIMIT 1`;

    connection.query(query, (error, result) => {
      if (error) {
        console.error(error);
        return result;
      }
    });
  }
```

Any guidance would be greatly appreciated.  I've been stuck on this for too long.

**Comment by SheetJSDev** [comment]
A SheetJS Pro customer recently had a similar issue (with `express-fileupload`).  After some digging and verification using checksums, we concluded that some part of the backend process was not preserving the data.  Is there a way to refactor the server so that you are passing raw buffers through the service?  If so, try doing an MD5 or SHA1 of the raw data and see if it is exactly what you submitted in the first place.

But to verify for yourself that this isn't a SheetJS issue, try grabbing a handful of sample files and make a small node test script that reads all of the files:

```js
var files = [
  "file1.xlsx",
  "file2.xls",
  "file3.xlsb",
  ...
];

files.forEach(fname => {
  const workbook = XLSX.readFile(path.resolve(__dirname, fname), { cellDates: true });
  const sheet_name_list = workbook.SheetNames;
  const xlData = XLSX.utils.sheet_to_json(workbook.Sheets[sheet_name_list[0]]);

  for (let i = 0; i < xlData.length; i++) {
    const rowObject: any = xlData[i];
    const values = Object.values(rowObject);
    let date = moment(new Date(values[0] as any)).format("YYYY/MM/DD");

    let savekey: any = values[20];
    savekey = parseInt(savekey);

    let ac_desc1 = values[5];
    let ac_desc2 = values[6];
    let cp_desc1 = values[10];
    let cp_desc2 = values[11];
    let cp_desc3 = values[12];
    let facility = values[22];

    const query = `INSERT INTO ${tableName} (AC_DESC1, AC_DESC2, CP_DESC1, CP_DESC2, CP_DESC3, SAVEKEY, FACILITY, DATE)  SELECT * FROM (SELECT  '${ac_desc1}' as v1, '${ac_desc2}' as v2, '${cp_desc1}' as v3, '${cp_desc2}' as v4, '${cp_desc3}' as v5, '${savekey}' as v6, '${facility}' as v7, '${date}' as v8 ) AS tmp WHERE NOT EXISTS (SELECT AC_DESC1, AC_DESC2, CP_DESC1, CP_DESC2, CP_DESC3, SAVEKEY, FACILITY, DATE FROM ${tableName} WHERE SAVEKEY = '${savekey}' AND AC_DESC1='${ac_desc1}' AND AC_DESC2='${ac_desc2}') LIMIT 1`;
    console.log(query); // <<--- log the query
  }
});
```

**Comment by DavidKHahn** [comment]
Hi SheetJSDev, 

I have checked the console.log and it seems to run correctly the first time after initial server load but not the ones afterwards.  

"Is there a way to refactor the server so that you are passing raw buffers through the service?"

I have refactored my code using AWS S3 using their signedURLs while using createStream():

```
var params = {
        Bucket: "",
        Key: ""
    };

    var file = s3.getObject(params).createReadStream();
    var buffers = [];

    file.on('data', function (data) {
        buffers.push(data);
    });

    file.on('end', function () {
        var buffer = Buffer.concat(buffers);
        var workbook = xlsx.parse(buffer);
        console.log("workbook", workbook)
    });
```

The main concern now is that my SQL 'query' to insert does not listen to accept only new rows of information with this package whereas previously it was working in that manner.

Any help would be greatly appreciated.

**Comment by SheetJSDev** [comment]
As is always the case, you have to test each part of the process

Log the queries, are they valid SQL queries for your database?  If not, pick a bad query and see where the issue lies.

**Comment by DavidKHahn** [comment]
Yes my query sends in the parsed data into mySQL but with each new upload the old info gets added as well as the new data leaving me with duplicates.  I'm currently trying to avoid this and insert only the newest rows coming in from each uploaded file.

**Comment by DavidKHahn** [comment]
I figured it out it was definitely a SQL table structure set up and query method issue. Thanks for your help SheetJSDev!
