### ISSUE TITLE
Unable to read style and so on information by xxx.xls file! xlsx file is ok!

### ISSUE THREAD

**Issue by kunnetcn** [SheetJS/sheetjs#1893]
We have got sheetjs pro verison authorization,and when i tried to read excel information such as style,border,size,background color and so on informations, I can't get correct result from xxx.xls version excel.but if i change the file to xxx.xlsx,i can get those informations.Is there something difference between xls and xlsx?what should i do,if i want to get the detail information from xls file?

**Comment by SheetJSDev** [comment]
send an email to pro@sheetjs.com
