### ISSUE TITLE
Vue.js read excel

### ISSUE THREAD

**Issue by 1shaked** [SheetJS/sheetjs#1896]
i tried to read the excel files with vue.js but u can once i read the file the memory start to sky rocket like 5 gb ram and i the excel file is feairly small pls help need to convert the file to json
The vue method to handle the excel file i tried all the type option i saw in the documintation but all send me diffrent errors.

base64: "TypeError: input.replace is not a function"
binary: "TypeError: x.charCodeAt is not a function"
string: "TypeError: data.match is not a function"
array: is the one that cause the memory to get into 5gb

```
displayFile: function (event) {
      // console.log(event.target.files[0])
      // const file = event.target.files[0]
      // const workbook = XLSX.read(file, {
      //   type: 'string'
      // })
      // console.log(workbook, workbook.SheetNames)

      // const res = XLSX.read(file)
      // console.log(res)
      // const res = XLSX.read(this.file)
      // console.log(res)
      console.log(this.file)
      this.file.text().then(text => {
        const fileType = this.file.type
        console.log(fileType)
        // this.PropceseMethod(this.file, fileType)
      })
      const reader = new FileReader()
      reader.onload = (data) => {
        console.log('HERE')
        console.log(data)
        const workbook = XLSX.read(data, {
          type: 'buffer'
        })
        console.log(workbook)
        workbook.SheetNames.forEach(function (sheetName) {
          console.log(sheetName)
          console.log(workbook.Sheets[sheetName])
          // Here is your object
          const XLRowObject = XLSX.utils.sheet_to_row_object_array(workbook.Sheets[sheetName])
          console.log(XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]))
          console.log(XLRowObject)
          const jsonObject = JSON.stringify(XLRowObject)
          console.log(jsonObject)
        })
      }
      reader.onerror = function (ex) {
        console.log(ex)
      }
      reader.readAsText(this.file)
    }

````

the actual temeplate i tried two things
````
<v-file-input
    v-on:change="displayFile($event)"
    v-model="file">
    </v-file-input>
    <input type="file" name="xlfile" id="xlf" v-on:change="displayFile($event)" />
```` 

both way did the same thing
when i use buffer it is working but return XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]) return [] like all the method and the rset of the functions

**Comment by ryuchaehwa** [comment]
@1shaked Hey, I'm using vuejs as well. I'm facing the same issue here. Did you get it work?

**Comment by 1shaked** [comment]
yes i will send you the code.
first is the file function which will get the files from the event and take only the first sheet;
`
_change (evt) {
      const files = evt.target.files
      if (files && files[0]) this._file(files[0])
    }
` 
the input file
`
<input type='file' class='form-control' id='file' :accept='SheetJSFT' @change='_change' />
`
the _file process function,
`
_file (file) {
      /* Boilerplate to set up FileReader */
      const reader = new FileReader()
      reader.onload = (e) => {
        /* Parse data */
        const bstr = e.target.result
        const wb = XLSX.read(bstr, { type: 'binary' })
        /* Get first worksheet */
        const wsname = wb.SheetNames[0]
        const ws = wb.Sheets[wsname]
        /* Convert array of arrays */
        const data = XLSX.utils.sheet_to_json(ws, { header: 1 })
        /* Update state */
        this.data = data
        const header = data.shift()

        const tbl = []
        for (let rowNum = 0; rowNum < data.length; rowNum++) {
          const row = data[rowNum]
          const objToAdd = {}
          for (let colNumber = 0; colNumber < header.length; colNumber++) {
            objToAdd[header[colNumber]] = row[colNumber]
          }
          tbl.push(objToAdd)
        }
        console.log(tbl)
      }
      reader.readAsBinaryString(file)
    }
`
the loop is just for me to wxtract the data but the main thing that cause of the problom is the **reader.readAsBinaryString(file)** and the make sure _const bstr = e.target.result
        const wb = XLSX.read(bstr, { type: 'binary' })_ . and there is some demos in this repo on how to do this. 
i will look in the repo and send you the exmple.
