### ISSUE TITLE
Date read incorrectly

### ISSUE THREAD

**Issue by veginati** [SheetJS/sheetjs#1899]
3/8/2020  5:01:00 AM is read as 3/8/2020  5:00:50 AM Indian Standard Time. There is an issue while reading the date from India timezone.

**Comment by veginati** [comment]
- 
[Test.xlsx](https://github.com/SheetJS/sheetjs/files/4471545/Test.xlsx)
Use the attachment for testing purpose, losing 10 seconds on each timestamp.

**Comment by razvanmp** [comment]
@SheetJSDev important issue!
Same problem in my case with GMT+3 timezone, where 24 seconds are lost. In my case the import of date data type is a must, so if this problem won't be solved quickly, I'll have to change the library used for this functionality. I updated to the last 0.16 version and nothing changed. Any thoughts?

**Comment by flaushi** [comment]
related https://github.com/SheetJS/sheetjs/issues/2196

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/issues/2304#issuecomment-916707320

Please follow https://github.com/SheetJS/sheetjs/issues/1565 for updates
