### ISSUE TITLE
I use XLSX module in Nodejs code, read xls file,out data is encode that i cant read

### ISSUE THREAD

**Issue by laizezhong** [SheetJS/sheetjs#1901]
'¹ñÔ±¼òÃû': 'ÍøÁª¸¶¿î½»Ò×·¢Æð¹ñ   ',
    '½»Ò×¹ñÔ±ºÅ': 9880204,
    '½è´û·½Ïò': '½è¼Ç',
    'Ö§¸¶¹¤¾ßÀàÐÍ': '000112-ÈËÃñ±Ò·ÇÏÖ³®ÒøÐÐ¿¨POS',²Æ¸¶Í¨-°¢ÜÇ¿¾¼¦×¦',
    'ATM±àºÅ': 17679000,
    '½»Ò×Ê±¼ä': '17:54:26',
    '½»Ò×ºóÕË»§Óà¶î': 6877.32,
    '±êÊ¶': '·ñ',
    'ÒøÐÐ¿¨ÀàÐÍ': 10,

My code is:
`const path = require('path');
const XLSX = require('xlsx');

let wb = XLSX.readFile(path.resolve(filePath));
let ws = wb.Sheets[sheet];
result = XLSX.utils.sheet_to_json(ws, {blankrows: blankrows, raw: raw});
`

how to resolve it?

**Comment by SheetJSDev** [comment]
you probably need to set the correct codepage.  Can you share the original XLS file and a screenshot of what Excel thinks the data is?

**Comment by laizezhong** [comment]
> you probably need to set the correct codepage. Can you share the original XLS file and a screenshot of what Excel thinks the data is?

[http://note.youdao.com/noteshare?id=fbb851710d81bdc35f244441357c737a&sub=A9525A6D9FFB4A9BB3190DD1AFDB7C09](url)
use Sheet1

**Comment by laizezhong** [comment]
you can use this file
[](https://drive.google.com/file/d/12_xhf8wlj5YbCkQfhwj4uDzEfUh2ZM6p/view)

**Comment by laizezhong** [comment]
i want to get chinese-simple data and show right,

**Comment by laizezhong** [comment]
or may be ,you can use this file
[http://note.youdao.com/noteshare?id=fbb851710d81bdc35f244441357c737a&sub=A9525A6D9FFB4A9BB3190DD1AFDB7C09](url)

**Comment by laizezhong** [comment]
> you probably need to set the correct codepage. Can you share the original XLS file and a screenshot of what Excel thinks the data is?

let wb = XLSX.readFile(path.resolve(filePath), {codepage: 65001});
I used codepage with the case in magic ,but it can not work anywhere
  var magic = {
    "1200":"utf16le",
    "1201":"utf16be",
    "12000":"utf32le",
    "12001":"utf32be",
    "16969":"utf64le",
    "20127":"ascii",
    "65000":"utf7",
    "65001":"utf8"
  };

**Comment by mela93** [comment]
大佬你这个问提解决了吗？ @laizezhong

**Comment by laizezhong** [comment]
> 大佬你这个问提解决了吗？ @laizezhong 

我用格式转换做了，转xlsx就没问题，这开发说的，用codepage写编码，都试过了，没啥用

**Comment by jiaoyuwu** [comment]
> 
大佬 怎么转换的 手动转换么 还是使用XLSX自带的转换方法

**Comment by SeniorChiefABLEUnit** [comment]
Set original code page tonight for configure for Sunday download. I have 2 original p.p., south KO, from 97. DD

**Comment by SeniorChiefABLEUnit** [comment]
Alles ok
die Arbeit aus dem ursprünglichen Geschichtsbericht beendet für 
2,5 
Übergang von TR1CIA3rdO 2 HSE2R/DSecret
Focused -Diligent- Prepared-NONMove -Riversotime- GeographyLib
Prfekt ,Y, PAMS - Update on reconfigure
Canadien Si Understood
