### ISSUE TITLE
Append data to the file without parsing the whole file.

### ISSUE THREAD

**Issue by varun2410** [SheetJS/sheetjs#1903]
I have a requirement where I need to write **33 Million rows X 15 columns**. The data amount may increase in the future. When I am creating a sheet object, after adding about **525000** rows in the sheet object, nodejs runs out of memory. So I am looking for a way where I can append to the workbook and sheet without opening the excel file. I am processing about 700 rows at a time.
Any help is greatly appreciated.

**Comment by SheetJSDev** [comment]
In theory, the library could extract the XLSX file to the filesystem and use standard filesystem ops to modify the worksheet XML.  That approach is neat but would be nodejs-specific and is better suited to a dedicated script.  If this is of interest, feel free to reach out to hello@sheetjs.com
