### ISSUE TITLE
How to export to excel with merge some column?

### ISSUE THREAD

**Issue by duccadhv1** [SheetJS/sheetjs#1917]
I want export json to excel with format merge some column look like image
<img width="408" alt="Screen Shot 2020-04-23 at 18 16 34" src="https://user-images.githubusercontent.com/13740139/80093555-e611d500-858e-11ea-89e9-2a62dc80d51a.png">
pls help me how can i do that.
thank all.

**Comment by SheetJSDev** [comment]
Merges are stored in the `!merges` key of the worksheet object.  See https://github.com/SheetJS/sheetjs/issues/964#issuecomment-359823907 for an example
