### ISSUE TITLE
XLSX.utils.sheet_to_json() taking long time

### ISSUE THREAD

**Issue by sachingoel** [SheetJS/sheetjs#1921]
I have used xlsx module for reading from excel file and parsing the data into json objects . It is working fine with normal excel (.xlsx ) file . But if some rows from the file are deleted and its upload again , the API slowed down . After some logging I have figured it out that , xlsx.util.sheet_to_json() function is taking longer time than normal .

**Comment by lfreneda** [comment]
@sachingoel I'm facing the same issue, did you fixed?

**Comment by apitts** [comment]
I am experiencing the same issue. It takes about 3 seconds for sheet_to_json() to complete for a simple sheet with about 20 cells populated. This is after that sheet has been edited using LibreOffice Calc. I have tested and confirmed on the current version - 0.16.8.

**Comment by SheetJSDev** [comment]
Can you share a file?  It's possible the file reports a very large range.  If the reported worksheet range is A1:F1048576 then `sheet_to_json` could be very slow

**Comment by apitts** [comment]
Thanks @SheetJSDev! Please find an example Excel file attached. 
[sheetjs_example.xlsx](https://github.com/SheetJS/sheetjs/files/6145196/sheetjs_example.xlsx)

**Comment by stanleyawang** [comment]
I am also experiencing the same issue .... the initial xlsx file that was edited in Windows was fine, but after I edited it using LibreOffice Calc, the sheets_to_json and sheet_to_row_object_array functions took a long time to execute ..

**Comment by pabloiea1995** [comment]
experiencing the same issue, as well after editing the file with LibreOffice Calc

**Comment by uditgogoi** [comment]
I am also facing same issue. Have anyone found any solution yet ?

**Comment by Sergio-P** [comment]
Any progress on this? It is really frustrating to wait a long time for just a simple excel

**Comment by stanleyawang** [comment]
this is a manual solution that is far from the ideal but could help ...
You can try manually deleting the rows even if they are empty in libreofficecalc and xlsx will properly read only the populated rows and not the empty rows ...

**Comment by leo-buneev** [comment]
Found quite simple workaround - limit !ref after opening worksheet:

```javascript
worksheet['!ref'] = getDataRange(worksheet)
parsedData = xlsx.utils.sheet_to_json(ws)

function getDataRange(data) {
  const dataWithValues = _.pickBy(data, (value, key) => !!value.v)
  const cellNamesWithValues = _.keys(dataWithValues)
  const cellsWithValues = cellNamesWithValues.map(cell => xlsx.utils.decode_cell(cell))
  const maxRow = _.max(cellsWithValues.map(cell => cell.r))
  const maxColumn = _.max(cellsWithValues.map(cell => cell.c))
  const lastCellName = xlsx.utils.encode_cell({ c: maxColumn, r: maxRow })
  return `A1:${lastCellName}`
}
```

**Comment by ayoub96anbara** [comment]
I have the same issue when I'm using LibreOffice but when I'm using windows office the problem does not appear.

**Comment by SheetJSDev** [comment]
The file shared by @apitts has an extremely large reported range:

```xml
  <dimension ref="A1:C1048576"/>
```

@stanleyawang from your description, it's probably the same issue.

At some point the parser will disregard the dimension record since that has caused issues.  In the interim, [`update_sheet_range`](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions#updating-worksheet-range) performs a similar calculation to @leo-buneev 's proposal

**Comment by CLOUGH** [comment]
> Found quite simple workaround - limit !ref after opening worksheet:
> 
> ```js
> worksheet['!ref'] = getDataRange(worksheet)
> parsedData = xlsx.utils.sheet_to_json(worksheet)
> 
> function getDataRange(data) {
>   const dataWithValues = _.pickBy(data, (value, key) => !!value.v)
>   const cellNamesWithValues = _.keys(dataWithValues)
>   const cellsWithValues = cellNamesWithValues.map(cell => xlsx.utils.decode_cell(cell))
>   const maxRow = _.max(cellsWithValues.map(cell => cell.r))
>   const maxColumn = _.max(cellsWithValues.map(cell => cell.c))
>   const lastCellName = xlsx.utils.encode_cell({ c: maxColumn, r: maxRow })
>   return `A1:${lastCellName}`
> }
> ```

If I could give you a hug I would. This literally saved me

**Comment by Airknstone** [comment]
I had a performance issue as well, I noticed it after converting the excel file to csv wherein the csv had thousands of empty values. a quick fix I found was using the dense option and setting it to true, 
It sped up my read time from 17000ms to 2000ms
Dense Mode
The dense option (supported in read, readFile and aoa_to_sheet) creates worksheet objects that use arrays of arrays under the hood:

var dense_wb = XLSX.read(ab, {dense: true});

var dense_sheet = XLSX.utils.aoa_to_sheet(aoa, {dense: true});  // or sheet_to_json
https://docs.sheetjs.com/docs/demos/stream#dense-mode
