### ISSUE TITLE
[RFC] Split out the CLI into a separate package

### ISSUE THREAD

**Issue by stof** [SheetJS/sheetjs#1922]
Currently, some of the dependencies of this package are related to its CLI tool (which is not even mentioned in the readme AFAICT). These dependencies (`commander` and `exit-on-epipe` at least) are unnecessary for projects using the library. To reduce the install footprint, what do you think about splitting the CLI into a separate package (that can then be installed only when you actually need it) ?

Note that to actually benefit from the smaller install footprint, this should also be done in other packages you maintain (`crc-32`, `adler-32`, `cfb` and `codepage`), as they also include their own CLI with these dependencies (btw, currently, this forces the install of 2 different versions of `commander` due to `xlsx` using an older version than `codepage`)

**Comment by SheetJSDev** [comment]
It's buried in the README: https://github.com/SheetJS/sheetjs#parsing-and-writing-examples

> The node version installs a command line tool xlsx which can read spreadsheet files and output the contents in various formats. The source is available at xlsx.njs in the bin directory.

That said, this is a reasonable idea.  Should the CLI be split off (a module like `xlsx-cli`) or should the library move (so the main `xlsx` module would be a reexport of something like `xlsx-lib`)

**Comment by stof** [comment]
Well, I don't have an opinion on the option you select. I'm fine if I have to replace `xlsx` with `xlsx-lib` (or whatever the name you choose) in my project to benefit from that.
However, looking at the npm ecosystem, I think it is more common to have a `-cli` separate package for the CLI, when the CLI is not the main use case of the library.

**Comment by fanglee101** [comment]
[b]https://icq.im/AoLGnKtUsQZKGmUTjTA

https://t.me/chinadebitbank


This is arqidarknet from

torre,zorldcard, market pro,

I sell first hand pos data,atm datas,resellers welcome,
usable pos,atm 

bank logs,email access,password
RDP
hack bibbles
Cvv=address
eu-usa-asia


minimum order is  10pieces 

no test for new clients* consideration could be consider on basis.

[/b]


![photo_2021-10-06_08-41-11](https://user-images.githubusercontent.com/92568711/137447583-ab3de13e-a8e9-432a-939d-29add8adbb0b.jpg)

**Comment by reviewher** [comment]
c1f5f04

**Comment by jtheletter** [comment]
How do we file issues for the CLI fork?
