### ISSUE TITLE
xlsb file reading keeps running without giving any error or result

### ISSUE THREAD

**Issue by sreenadhtg** [SheetJS/sheetjs#1923]
I was trying to parse a xlsb file but script keeps running on and not getting any error as well as result. xlsb file has 65k rows. following is the code

```
const workbook = XLSX.readFile('./s.xlsb');
  const range = XLSX.utils.decode_range(workbook.Sheets[workbook.SheetNames[0]]["!ref"]);
  let sheet = workbook.Sheets['DB'];
  const cell = sheet[XLSX.utils.encode_cell({ r: 50000, c: 5 })];
```

Script is working fine when i tried to get first few rows as follows.

```
const workbook = XLSX.readFile('./s.xlsb',{ sheetRows: 500 });
  const range = XLSX.utils.decode_range(workbook.Sheets[workbook.SheetNames[0]]["!ref"]);
  let sheet = workbook.Sheets['DB'];
  const cell = sheet[XLSX.utils.encode_cell({ r: 400, c: 5 })];
```

**Comment by SheetJSDev** [comment]
We can take a closer look if you can share that file, send an email to hello@sheetjs.com

**Comment by erikvullings** [comment]
I had the same problem using a 30Mb xlsb file containing pivot data, but I had a look at the bin folder, which worked, debugged it, and found out that they open the files using two additional parameters:

```js
XLSX.readFile(inputFile, { dense: true, cellFormula: false })
```

Maybe this works for you too?

**Comment by SheetJSDev** [comment]
@erikvullings it's more likely that `cellFormula: false` was the key.  This would suggest there's some case the formula stringifier is not properly handling.  We'd love to take a closer look if you can share a sample file.  send to hello@sheetjs.com

@sreenadhtg without looking at the actual file it is hard to say what happened.  But likely there's some infinite loop tied to the formula stringification, so try `cellFormula: false` and please report back your results.  We can always reopen the issue
