### ISSUE TITLE
XLSX.read is not a function

### ISSUE THREAD

**Issue by rowletleaf** [SheetJS/sheetjs#1924]
I’m working on a local web page which uploads excel file to run some codes and export it out a result excel file in a single html and java file.

However I ran into issues with XLSX.read function was not found while XLSX.utils.book_new function is working.

The reason why I mention XLSX.utils.book_new is that I tried testing out using XLSX.core.min.js with XLSX.full.min.js but while playing with different version and using both or single file each time, only 1 of the function work while the other was not found.

Html Script Tag

<script lang="javascript" src="Java/jquery-2.1.4.min.js"></script>
	<script lang="javascript" src="Java/FileSaver.min.js"></script>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.15.6/xlsx.full.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.15.6/xls.core.min.js"></script>

	<script lang="javascript" src="testExcel.js"></script>

**Comment by SheetJSDev** [comment]
You should only need the `xlsx.full.min.js` script.  As a small example, https://jsfiddle.net/fa4tq2yk/ loads https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.15.6/xlsx.full.min.js and runs

```js
var wb1 = XLSX.utils.book_new();
var wb2 = XLSX.read("abc,def\nghi,jkl", {type: "string"});
XLSX.utils.book_append_sheet(wb1, wb2.Sheets.Sheet1, "Sheet1");
XLSX.writeFile(wb2, "issue1924.xlsx");
```

Both `read` and `new` are working.

It's probably an issue with your HTML, check your JS console if there are any other issues
