### ISSUE TITLE
Restrict save & save as function in xlsx

### ISSUE THREAD

**Issue by ajju123** [SheetJS/sheetjs#1925]
How we restrict save & save as function in xlsx in angular 8?

**Comment by SheetJSDev** [comment]
File save related functions are only used in `writeFile`.  Using `write` directly can generate typed arrays (which you can then upload to an endpoint).

There's no way to control exactly what the browser will do.  No standard API for downloading files exists (Years ago there was a proposal for a File Writer API https://www.w3.org/TR/2012/WD-file-writer-api-20120417/ but that never gained traction), so we try a few different techniques and the browser decides what to do.  [`write_dl`](https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L11) is the relevant code
