### ISSUE TITLE
Maintain Styling format from existing file

### ISSUE THREAD

**Issue by adesm** [SheetJS/sheetjs#1926]
I have an excel file which its content contains some styles, such as merged cell, bolded text, aligned cell. 

I read the file using `XLSX.readFile` and get sheetname by 
```
 const guideSheetName = templateWorkbook.SheetNames[0]
 const guideWorkSheet = templateWorkbook.Sheets[guideSheetName]
```

then I created new Workbook and append the sheet to this workbook
`XLSX.utils.book_append_sheet(newExcel, guideWorkSheet, 'Sheet1')`

but when i saved the file, styling format gone. I just have unformatted worksheet. there are no styles, such as merged cell, bolded tex, aligned cell as well as previous excel file

Ho can I maintain the formating style from previous workbook to new workbook?

**Comment by SheetJSDev** [comment]
This is currently in the purview of our Pro builds, see https://sheetjs.com/pro for more info
