### ISSUE TITLE
Time interval format in Excel

### ISSUE THREAD

**Issue by popiolek** [SheetJS/sheetjs#1931]
I'm trying to write a time in format: "05:45:34" to a xlsx output file. Normally in Excel such cell is interpreted as time and Excel is able to perform operations on it (e.g. `SUM`).  Example of such file in attachment.

Trying few hours now I'm not able to create such cell with SheetJS. I've tried `.t = 'n'`, `.z = 'gg:mm:ss'` but nothing helped. I've even tried to read a xlsx file and write it again without changes, but it doesn't work. You can see the example below on JSFiddle, after uploading the test file there and downloading it values formatting is lost.

I'm not sure if that's an error, or lack of some function, or my lack of SheetJS knowledge. Is there any way to create cell with such value that works with Excel?

Demo: https://jsfiddle.net/gwa61kj0/

Test file: [test.xlsx](https://github.com/SheetJS/sheetjs/files/4570958/test.xlsx)

**Comment by SheetJSDev** [comment]
Your locale will display `gg:mm:ss` but it's actually stored in the file using the en-US `h:mm:ss` or `[h]:mm:ss` (those are actually built-in table indices 21 and 46).
