### ISSUE TITLE
Error save xlsx ,last column formatting loss

### ISSUE THREAD

**Issue by carlorama** [SheetJS/sheetjs#1932]
Hi, I have a problem with the XLSX.write function.I have a datasheet formatted with columns of different types (e.g. string, numeric and date) but when I insert it to the XLSX.write function, the last column loses the formatting and it becomes string, also when I open it with the relative program, it warns me of a loss of data, I checked the object in debug and it has no anomalies.
this is code for save:
const fileExcelOutput = XLSX.write(fileExcel, { type: "buffer", bookType: "xlsx", cellDates: true});
                function s2ab(s) {
                    var buf = new ArrayBuffer(s.length);
                    var view = new Uint8Array(buf);
                    for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                    return buf;
                }
                    saveAs(new Blob([s2ab(fileExcelOutput)], { type: "buffer" }), fileName);
I have not understood where the problem is. thanks for support

**Comment by SheetJSDev** [comment]
To tell where it's coming from, can you inspect a sample cell from your code and see if it is correct?  For example, if cell B3 of worksheet "Sheet1" is Text but you expect it to be a Number, then console.log(fileExcel.Sheets["Sheet1"]["B3"]) and see if the `t` property is "s" or "n".  If it is "s", then your data source is the issue (the library will not automatically parse values if you are using `aoa_to_sheet` or certain other utilities)
