### ISSUE TITLE
how can i set the export coding format shift-jis

### ISSUE THREAD

**Issue by chenjianeng0201** [SheetJS/sheetjs#1933]

**Comment by SheetJSDev** [comment]
The option is not currently exposed.  ShiftJIS is codepage 932 and ultimately we need to add that as an option to sheet_to_csv.

To make it work right now, generate the CSV using sheet_to_csv, then use https://github.com/SheetJS/js-codepage directly.  For example in NodeJS, the `cptable` global is automatically leaked so you can just:

```js
var XLSX = require("xlsx");

/* generate starting worksheet, simple "csv" encoded in UTF8 */
var original = "ワークシート";
var wb = XLSX.read(original, {type: "string"});

/* get utf-8 encoded csv */
var out = XLSX.utils.sheet_to_csv(wb.Sheets.Sheet1, {type: "string"});

/* convert */
var bytes = cptable.utils.encode(932, out, "buf");
```

`bytes` will be a buffer with bytes `<Buffer 83 8f 81 5b 83 4e 83 56 81 5b 83 67 0a>`, which appears to be correct according to the `iconv` tool

**Comment by chenjianeng0201** [comment]
> tool

thanks，i'll try it
