### ISSUE TITLE
Append to a spreadsheet and write to the same file

### ISSUE THREAD

**Issue by cu0ngpitt** [SheetJS/sheetjs#1934]
I've been trying to append a new row of data to the same spreadsheet but cannot seem to get it to work right. Excel keeps telling me "there is a problem with the content". It works fine when i create a new workbook but that's not the option I need. i need to be able to append a new row of info to the same excel file.

```
  const filePath = __dirname + '/../models/new.xlsx';
   var wb = XLSX.readFile(filePath);

  createExcel(wb) => {

  var ws_name = wb.SheetNames[0],
        ws = wb.Sheets[ws_name];

    var ws_data = [
      ["Test Name", "test Data", "Data abc"]
    ];

    XLSX.utils.sheet_add_aoa(ws, ws_data, {origin:-1});

    XLSX.writeFile(wb, __dirname + "/../models/new.xlsx");
  }
```

**Comment by SheetJSDev** [comment]
Did you mean to write `XLSX.utils.sheet_add_aoa(ws, ws_data, {origin:-1}); `?  If you can share the starting file we can take a closer look

**Comment by cu0ngpitt** [comment]
Oops yes that was a typo. It should have been `ws_data`, I updated my post. The starting file was simply a blank workbook I created to test my code so there is no data in it.

**Comment by SheetJSDev** [comment]
If you can share the original file, we can take a closer look (feel free to email hello@sheetjs.com).  Without it, all we can recommend is to update to the latest version and try again.
