### ISSUE TITLE
Typescript: ParsingOptions wrong type

### ISSUE THREAD

**Issue by dude333** [SheetJS/sheetjs#1935]
Intefaces **ParsingOptions** and **WritingOptions**  `type` are implemented incorrectly, it should have been set as `type?: string;`. But instead it was configured with the actual values it can receive (and not the type, that is a string).

https://github.com/SheetJS/sheetjs/blob/91f8c467041afd8071fb3a777ce38c389c4e6bdf/types/index.d.ts#L131

https://github.com/SheetJS/sheetjs/blob/91f8c467041afd8071fb3a777ce38c389c4e6bdf/types/index.d.ts#L205

Instead of:

    type?: string;

Reproduced at https://repl.it/repls/DarkmagentaMoralAutomatedinformationsystem

**Comment by SheetJSDev** [comment]
What exactly is the error here?  The intention is to typecheck the actual values.

This will pass the TS checker:

```typescript
XLSX.read("abc,def\nghi,jkl", {
  type: "string"
});
```

This will fail:

```typescript
XLSX.read("abc,def\nghi,jkl", {
  type: "string2"
});
```

When the type of a variable is a list of strings, it will inspect the value and error if you didn't pass one of the enumerated values.

**Comment by dude333** [comment]
Hey, thanks for the prompt response. I've double checked it and I missed to directly specify the variable type, my bad.

Instead of:

    const config = {
      type: "base64",
    };

I should've used:

    const config: xlsx.WritingOptions = {
      type: "base64",
    };

Thanks.

**Comment by SheetJSDev** [comment]
One of the neat things about enumerating values is the little popup in VSCode

<img width="431" alt="Screen Shot 2020-05-06 at 5 36 54 PM" src="https://user-images.githubusercontent.com/6070939/81230945-63dad500-8fc0-11ea-8e68-8f75383f1098.png">
