### ISSUE TITLE
'xlxs@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by PrashantMohan9** [SheetJS/sheetjs#1936]
Logs of the terminal:

C:\Users\Home\Documents\Angular\my-first-app>npm install xlxs --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/xlxs - Not found
npm ERR! 404 
npm ERR! 404  'xlxs@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by SheetJSDev** [comment]
package name is `xlsx`, you misspelled it

**Comment by PrashantMohan9** [comment]
Thanks for the response and extremely sorry for asking such a silly question.
