### ISSUE TITLE
Good evening everyone :-)

### ISSUE THREAD

**Issue by Lasticot88** [SheetJS/sheetjs#1941]
### Good evening everyone from France, 

i started to learn by myself javascript, searching hundreds of usefull topics forum (**thanks you community!** ) but today i'm **blocked**, and i can't found the solution.

- i'm trying to **filter values** from many objects, that i just converted from **xlsx** thanks **sheetJS**. I converted sucessfull, but i tried many ways to filter it.

- Should i do like a normal object in JS? Because the console said me that it's not an object. But it's seems that SheetJS Array did "multiple" object when he got converted from **Excel-File**;
 (object 1: **Age**=Mike33, **size**=1.80
(object 2: **Age**=Sara31, **size**=1.70
(object 3: **Age**=Arnold33, **size**=1.82

(Actually objects SheetJS gave names to object 
"1 "
"2 "
"3 "
"4 "

**(there is 38000 objects lol)**

-->"The technical" issue is that i'm trying to search **One-Value-Age-that-we-want-to-Search** (Age)(in all objects 1-38000), match with which **size** (in all objects 1-38000)
For example, i would like to know how tall is, all guys with the "value age /filter 33" (i know it's look like stupid, but i got the original excel with 38 000 lines, and it's impossible to separate manually this "cells A" about characters+Age in 38 000 lines. **I think it's better to use a filter ignoring command NaN no?.**
So actually i got:

- **cell A: XYZ+ numbersAge**, 

- **cell B: Size.** 

And i only want to filter by numbers. I dont need the names Mike, Sara, Arnold. Just age, and get which "Size" (in the cell B excel).

.

### So i'm using this code for that: 
(what is your opinion) Thanks you!

// open head

     <script src="xlsx.full.min.js"></script>    

// close head

//body open

    //script
      var url = "FILE-EXCEL.xlsx";

      /* set up async GET request */
      var req = new XMLHttpRequest();
      req.open("GET", url, true);
      req.responseType = "arraybuffer";

      req.onload = function(e) {
        var data = new Uint8Array(req.response);
        var workbook = XLSX.read(data, {type:"array"});

        /* DO SOMETHING WITH workbook HERE */
        let first_sheet_name = workbook.SheetNames[0];

        /* Get worksheet */
        var worksheet = workbook.Sheets[first_sheet_name];
  
  
        scores= object.values(worksheet);
        passing = scores.filter(function(val) {return val=33}); 
        /*about the "33", i would like to know which value B (Size) "match" searching in the 38000 lines of the B cells of my excel :/ */
        /* i think, i should create a function, that will search the "number input box" to the B cells. I get confuse it's start to be hard haha */
      }
  
      req.send();

    //script close
    

  //body close

</html>`

**Comment by SheetJSDev** [comment]
This is obviously a more general JS question, and you'll find better help at a dedicated resource like [##javascript on freenode IRC](https://webchat.freenode.net/?channels=#javascript), but to answer the immediate question, use `sheet_to_json` to generate an array of objects (one for each row):

```js
var scores = XLSX.utils.sheet_to_json(worksheet, {raw: true});
```

Each key in the object corresponds to a column in the worksheet.  If cell A1="Age", then each object will have an Age key if there's data in the corresponding cell in column A.

Suppose C1="Val" is the value you want to filter for, then just filter:

```js
var passing = scores.filter(function(row) { return row.Val == 33; }); 
```

Now you can look at all of the sizes in the passing array.  For example, supposing you wanted the average age:

```js
var average_size = passing.reduce(function(avg, row, idx) { return (avg * idx + row.Age) / (idx + 1); }, 0);
```
