### ISSUE TITLE
sheet_to_json working with excel date and number columns

### ISSUE THREAD

**Issue by josemvalente** [SheetJS/sheetjs#1942]
Hi JS-XLSX team and community,

I am using "readFile" to look into user worksheets, and "sheet_to_json" to generate JSON object to send to a REST API.

My questions resides on the Date and Number formats, I use the options:
- cellDates: true, in the "readFile" in order to use the date string;
- raw: true, in the "sheet_to_json" in order to have the original values (mainly number formats);
- dateNF: "mm/dd/yyyy", in the "sheet_to_json" in order trye to format the date output string;

Looking in to the output:
- The date ouput format is always in the form "EntityStatusDate: "2000-11-30T00:00:45.000Z"", and not in "mm/dd/yyyy";
- The numbers output is what I expected, except when I have an excel column with format "Text" and the value is a number. The "sheet_to_json" returns a number and not a string as expected. It seems the function, does not take into account the excel column format.
I receive a object "SeniorityType: 999" and I expected  "SeniorityType: "999" ", because the column "SeniorityType" in the excel as format "Text";

Thanks guys
José Valente

**Comment by nandctl** [comment]
I have the similar situation.

**Comment by SheetJSDev** [comment]
Without seeing the original file it is hard to say.  So if you can share the original file we can take a closer look.  General notes:

- Excel number format "Text" does not change the fact that the underlying value is in fact a number.  As a result, the raw value will be a number.  To contrast, a number written as text (e.g. typing `'123` in the formula bar) is stored as text.
- Raw value of dates that are captured as Date objects (cellDates: true) will be an unformatted Date object.  When stringifying dates, the result will be an ISO8601 string like you see.

You can post-process the result to convert it the way you like e.g.

```js
var data = XLSX.utils.sheet_to_json(...);
var fixed_data = data.map(r => {
  var o = Object.assign({}, r);

  // number -> string
  if(o.SeniorityType != null) o.SeniorityType = String(o.SeniorityType); 

  // date -> mm/dd/yyyy
  Object.entries(o).forEach(([k,v]) => {
    if(v && v instanceof Date) o[k] = `${(v.getMonth()+1).padStart(2,"0")}/${v.getDate().padStart(2,"0")}/${v.getFullYear()}`;
  });
});
```
