### ISSUE TITLE
Cannot format currency 

### ISSUE THREAD

**Issue by Evelvety** [SheetJS/sheetjs#1944]
Hi, I try to format numbers  in excel with two decimals, but I get
![image](https://user-images.githubusercontent.com/61932989/81918725-2933f680-95d7-11ea-8e62-2c58df7cfd37.png)

I try these formats $0.0 $0.00 and '$#,###.00'.

The former works best but it removes the last decimal

78001.33 -> $78001.3

The second one works fine only for some numbers

78,001.30 -> ########
3.50 -> $3.50
40.00 -> $40.00

The last one doesn't work at all

This is what I do:
![image](https://user-images.githubusercontent.com/61932989/81919758-88ded180-95d8-11ea-83ad-1b180f3c57de.png)

Also, I try to handle the percent format and I get similar issues.

**Comment by SheetJSDev** [comment]
Excel draws hash symbols when the generated text doesn't fit in the column space.  Try increasing the column width using the column properties

PS: For cell type `n` you are expected to pass numbers in cell values
