### ISSUE TITLE
Export CSS Div Table to xlsx

### ISSUE THREAD

**Issue by sallos** [SheetJS/sheetjs#1946]
Hi,

it is possible to export a Table like this

`      <div id="divTable" class="divTable" style="border: 1px solid #000;">
        <div class="divTableBody">
          <div class="divTableRow" id="anfang">
            <div class="divTableCell">1</div>
            <div class="divTableCell">2</div>
            <div class="divTableCell">3</div>
            <div class="divTableCell">4</div>
            <div class="divTableCell">5</div>
            <div class="divTableCell">6</div>
            <div class="divTableCell">7</div>
            <div class="divTableCell">8</div>
            <div class="divTableCell">9</div>
            <div class="divTableCell">10</div>
            <div class="divTableCell">11</div>
          </div>
        </div>`

or it has to a <td> <tr> table?

**Comment by SheetJSDev** [comment]
You can write your own function.  The utility functions aren't particularly clever, they just loop through the cells in the worksheet and generate output.  As part of our Pro version, we've built a renderer using CSS to position HTML DIV elements.
