### ISSUE TITLE
setting language for a cell

### ISSUE THREAD

**Issue by Mhmdasfak** [SheetJS/sheetjs#1947]
I am Trying To Do Number Formatting For A Selected Columns It Works But I Need Them To Be In A Different Language Format(EN-US) 
`		        var wb = XLSX.utils.table_to_book(document.getElementById('example'), {sheet:"Sheet JS"});
			var colNum = ['E','F','G','H','I','J','K','L','M','N','O']; //decode_col converts Excel col name to an integer for col #
			var fmt = '#,##0.00'; // or '"$"#,##0.00_);[Red]\\("$"#,##0.00\\)' or any Excel number format

 			const ws = wb.Sheets[wb.SheetNames[0]];
			/* get worksheet range */
			var range = XLSX.utils.decode_range(ws['!ref']);
			for(var i = range.s.r + 1; i <= range.e.r; ++i) {
				for(var columnIndex=0;columnIndex<colNum.length;columnIndex++)
					{
			  /* find the data cell (range.s.r + 1 skips the header row of the worksheet) */
			  var ref = XLSX.utils.encode_cell({r:i, c:columnDec(colNum[columnIndex])});
			  /* if the particular row did not contain data for the column, the cell will not be generated */
			  if(!ws[ref]) continue;
			  /* `.t == "n"` for number cells */
			  if(ws[ref].t != 'n') continue;
			  /* assign the `.z` number format */
			  console.log(ws[ref]);
			  ws[ref].z = fmt;
			  }
			}
`		function columnDec(text)
		{
		return XLSX.utils.decode_col(text)
		}

**Comment by SheetJSDev** [comment]
There is no per-cell language setting in Excel.

For locale settings you can use number formats with expressions like `[$-409]` for en-US or `[$-804]` for zh-CN.  [`MS-LCID` section 2.2](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/63d3d639-7fd2-4afb-abbe-0d5b5551eef8) has a list of locale IDs you can use.
