### ISSUE TITLE
Change width setting Automatic to 1 page

### ISSUE THREAD

**Issue by varunsree** [SheetJS/sheetjs#1948]
Is any option for setup xlsx width Automatic to 1 page, Now it is set Automatically by default. How can I change? Thanks
![xlsx-set-property](https://user-images.githubusercontent.com/6636865/82051457-831be580-96d7-11ea-8ef5-e820ffb04fb9.jpg)

**Comment by SheetJSDev** [comment]
Print settings are supported in our [Pro builds](https://sheetjs.com/pro)
