### ISSUE TITLE
Repaired workbook warning appearing when file is not created in MS Excel

### ISSUE THREAD

**Issue by miguelvasques** [SheetJS/sheetjs#1949]
Hi guys!
I am using this library to manipulate spreadsheets but I noticed that in some cases when opening the workbook in MS Excel the repaired workbook warning appeared and I have no idea why.
I am building a server side app using node v8.15.0, using the following script:
```
var XLSX = require('xlsx');

var origin = async function(filename) {
  var wb = XLSX.readFile(filename);

  await XLSX.writeFile(wb, './testRes.xlsx');
}

origin('./test.xlsx');
```
I built a simple workbook which consisted of 2 lines and 4 columns. The three different scenarios that I used to test my script were:
1 - Create this workbook using MS Excel, running the script and the resulting file can be open without any warnings;
Input File:  [inputMSExcel.xlsx](https://github.com/SheetJS/sheetjs/files/4635851/inputMSExcel.xlsx)
Output File: [outputMSExcel.xlsx](https://github.com/SheetJS/sheetjs/files/4635858/outputMSExcel.xlsx)

2 - Create this workbook using Libre Office, running the script and the resulting file has warnings;
Input File: [inputLibre.xlsx](https://github.com/SheetJS/sheetjs/files/4635866/inputLibre.xlsx)
Output File: [outputLibre.xlsx](https://github.com/SheetJS/sheetjs/files/4635882/outputLibre.xlsx)

3 - Create this workbook using Office365 Excel,  running the script and the resulting file has warnings.
Input File: [inputOffice.xlsx](https://github.com/SheetJS/sheetjs/files/4635890/inputOffice.xlsx)
Output File: [outputOffice.xlsx](https://github.com/SheetJS/sheetjs/files/4635893/outputOffice.xlsx)

Does this happen to you?

**Comment by SheetJSDev** [comment]
The outputLibre file has a blank DocSecurity tag which was addressed in https://github.com/SheetJS/sheetjs/commit/0ac53360b236a8c677d14cf0f51904be8a359e17 but we haven't released a new version since that commit.  We'll do that shortly

**Comment by SheetJSDev** [comment]
0.16.1 has the fix, please do an update and reopen the issue if you are still facing problems
