### ISSUE TITLE
Data with quotes is read incorrectly (multiple Excel rows turn into one)

### ISSUE THREAD

**Issue by dilizarov** [SheetJS/sheetjs#1950]
The below screenshot is my example data in Excel

<img width="254" alt="Screen Shot 2020-05-15 at 4 35 01 PM" src="https://user-images.githubusercontent.com/3807722/82104004-10f0d400-96ca-11ea-9949-47f7123e79b4.png">

I select the 3 rows and copy them (CTRL + C). I then paste it into my browser for XLSX to pick it up.

Browser receives the following string from the copy and paste:

`"\"this is one row\r\nthis is a second row\r\nthis is a third row\""`

Assume the following example:

```ts
import { read, utils } from "xlsx";

const data = "\"this is one row\r\nthis is a second row\r\nthis is a third row\"";
const separator = "sep=\t\n"; //Excel separates columns with \t

const wb = read(`${separator}${data}`, { type: "string" });
const json = utils.sheet_to_json(wb.Sheets.Sheet1, { header: 1, raw: true, defval: "" });

console.log(json) //=> [["this is one row\nthis is a second row\nthis is a third row"]]

// Expectation: json should be [["\"this is one row"], ["this is a second row"], ["this is a third row\""]
```

Originally, I was using the Papaparse project for my parsing needs and while it worked for the most part (and surprisingly for this string), it didn't always work with Excel parsing because Excel does not follow the RFC 4180.

https://github.com/SheetJS/sheetjs/issues/489 helped out and I assumed that this library would be able to handle quotations when reading data from Excel.

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/issues/1943#issuecomment-628133350 fix should work, if it does feel free to send that as a PR

**Comment by dilizarov** [comment]
@SheetJSDev Unfortunately, I still get the same output. I don't think the problem has to do with the separator line.

**Comment by SheetJSDev** [comment]
Sorry I misread your question.

This is a known issue with Excel's copy.  https://github.com/warpech/sheetclip/issues/3#issuecomment-16153406 longer discussion from 2013.  The correct encoding should have been

```
"""this is one row"
this is a second row
"this is a third row"""
```

If you're trying to extract the correct thing from copy-paste, read the HTML clipboard instead: http://output.jsbin.com/uwuvan/5 is a jsbin showing how to do it with event.clipboardData

**Comment by dilizarov** [comment]
Hmm. The data in the HTML does seem appropriate. I suppose I just need to parse the html table instead and make the array. In which case, I might not need this library.

**Comment by SheetJSDev** [comment]
You can also parse the HTML string directly using XLSX.read (it's one of the supported formats :)  In any case, this probably needs a separate mode flag (it conflicts with how Excel parses the text if it was in a file)

**Comment by dilizarov** [comment]
Oh, interesting. It seems parsing the HTML just... works? Nice! I think this could work well.

If there is no "text/html", I'll just fallback to assuming the "text/plain" is a CSV following RFC 4180.

Does the `read` also properly parse that? Or should I rely on Papaparse for that one?

If XLSX.read supports it, then my solution might be as simple as something like: 

```ts
const data = clipboard.getData("text/html") || clipboard.getData("text/plain")
const wb = XLSX.read(data, { type: "string" })
const output = XLSX.utils.sheet_to_json(wb.Sheets.Sheet1, { header: 1, raw: true, defval: "" })
```

**Comment by SheetJSDev** [comment]
Ideally everything just "works", the original motivation was to have one function to "read" data (see https://github.com/sheetjs/sheetjs#philosophy :)

yes the read function supports both.  There are a few ways we differ from the RFC (for example, files starting with "ID" will first be interpreted as SYLK, in accordance with excel).

**Comment by dilizarov** [comment]
I did find a peculiar case, where my output was:

`[["That񳼯td>"],["That's"]]`

<img width="80" alt="Screen Shot 2020-05-15 at 7 48 51 PM" src="https://user-images.githubusercontent.com/3807722/82108697-21627800-96e5-11ea-8b11-14beef540ad3.png">

That is what caused it. If you look carefully (and I'm honestly not sure how I even caused this), the top one uses the `’` character, whose charCode is 8217, which is the broken row in my output.

The bottom one that works fine uses `'`, charCode is 39.

It seems like the unwanted character messes up the table parsing somehow.

**Comment by reviewher** [comment]
The referenced PR has been merged.  Marking as closed.  Please reopen if the issue persists.
