### ISSUE TITLE
xlsx.readFile() ,The first time it returns correctly, the next time it returns empty

### ISSUE THREAD

**Issue by zhanglaifu** [SheetJS/sheetjs#1951]
I use xlxs.readFile to read my Excel,Data can be returned normally using readFile when the project is started, but subsequent readFile often gets empty。In addition, my project is the node project.
<img width="741" alt="微信截图_20200518112430" src="https://user-images.githubusercontent.com/37335105/82171753-de79ed80-98fa-11ea-81e7-684d4d0f2b27.png">
Please give me a hand！thank you

**Comment by SheetJSDev** [comment]
Is the file written at that point?  You can check by logging `fs.statSync(file_path)`.  This has come up before and usually ends up being a timing issue in your setup.

Also: XLSX.readFile is not async, you don't need to await?

**Comment by zhanglaifu** [comment]
> Is the file written at that point? You can check by logging `fs.statSync(file_path)`. This has come up before and usually ends up being a timing issue in your setup.
> 
> Also: XLSX.readFile is not async, you don't need to await?

i try to console(fs.statsSync)，and i get the response 
<img width="734" alt="微信截图_20200518114032" src="https://user-images.githubusercontent.com/37335105/82172380-90fe8000-98fc-11ea-93f0-8eca4d7e3ef9.png">

**Comment by SheetJSDev** [comment]
`size: 0` at that point suggests the starting file is empty.  This is most likely an issue with other libraries you are using.  Are you sure that the file is supposed to have contents at that point?

**Comment by zhanglaifu** [comment]
> `size: 0` at that point suggests the starting file is empty. This is most likely an issue with other libraries you are using. Are you sure that the file is supposed to have contents at that point?
My process is to pass excel in the front end, then write excel to a file in node, and then use XLSX to read the data in the file. I'm pretty sure my file isn't empty.
Sometimes I cannot parse out the file when I upload it for the first time. When writing to the file, I use await to wait for the file to be written and listen to the finish event written by the file

**Comment by zhanglaifu** [comment]
> `size: 0` at that point suggests the starting file is empty. This is most likely an issue with other libraries you are using. Are you sure that the file is supposed to have contents at that point?

thank you!Because I encapsulated the interface for file upload, I used reader.on("close") in the promise returned by the interface to listen for the data stream to stop, and then executed xlsx.readfile. I changed the reader to writer, and the problem was solved
<img width="697" alt="微信截图_20200518143739" src="https://user-images.githubusercontent.com/37335105/82181459-26a60980-9915-11ea-8081-9c0823590b42.png">
