### ISSUE TITLE
how to merge the column 

### ISSUE THREAD

**Issue by Calvin1121** [SheetJS/sheetjs#1956]
![image](https://user-images.githubusercontent.com/31435496/82419371-e24f7080-9ab0-11ea-9917-bcb9e8a25227.png)
I wanna export the data to excel, and I can merge the rows but i need merge the columns, as i marked in the pic. please help me, thx

**Comment by rajubushanam** [comment]
@Calvin1121 - Did u find a solution to this?

**Comment by Calvin1121** [comment]
> @Calvin1121 - Did u find a solution to this?

yep~ the plugin provides an api for merging the columns. For example:['A1:J1', 'A2:B2', 'C2:E2', 'F2:G2', 'H2:J2', 'A4:A6']. but it's to diffcult to solve the data and map the merged array. so I asked for help from the backend to do this.

**Comment by SheetJSDev** [comment]
The "!merges" key of the worksheet can be an array of the ranges you want to merge.  See https://github.com/SheetJS/sheetjs/issues/416#issuecomment-286932882 for an example
