### ISSUE TITLE
getting full date while using dateNF: "dd/mm/yyyy"

### ISSUE THREAD

**Issue by vickyksingh** [SheetJS/sheetjs#1957]
Hello Team,

i'm passing date in 04/29/2023 format from excel sheet but it is providing full Date.

Please someone help me 
const workbook = XLSX.read(data, {
            type: "array",
            cellDates: true,
            dateNF: "dd/mm/yyyy",
            raw: false
            
          });

output:
{t: "d", v: Fri Apr 28 2023 23:59:50 GMT+0530 (India Standard Time), w: "04/29/2023"}

**Comment by Marianne00** [comment]
i experienced the same thing.. i used moment as a workaround 

```
excelData.forEach(item => {
    if(!isNaN(new Date(item.Date_Birth).getTime())) {
        moment(item.Date_Birth).format('YYYY-MM-DD') !== 'Invalid date' ? item.Date_Birth = moment(item.Date_Birth).format('YYYY-MM-DD') : item.Date_Birth = item.Date_Birth
    } 
})
```

**Comment by vickyksingh** [comment]
@Marianne00 thank you
