### ISSUE TITLE
Passing empty file with a custom range breaks my app

### ISSUE THREAD

**Issue by Marianne00** [SheetJS/sheetjs#1958]
Hi guys, do you have idea on what condition can I wrap my code below?

```
var range = XLSX.utils.decode_range(
  workbook.Sheets[first_sheet_name]['!ref']
);
range.s.c = 0; 
range.e.c = 8; 
var new_range = XLSX.utils.encode_range(range);

var excelData =  XLSX.utils.sheet_to_json(worksheet, {
  raw: true,
  defval: null,
  dateNF: 'yyyy-mm-dd',
  range: new_range,
});
```

It breaks when I upload an empty file.. the error happens when Im assigning a custom range

**Comment by SheetJSDev** [comment]
Without seeing the original file, it is hard to say what the issue is.  The obvious guard is to check `range.e.r - range.s.r >= 1`.  If you can share the file, we can reopen and look into it further
