### ISSUE TITLE
Trouble to place images in the 2nd tab in the xlsx

### ISSUE THREAD

**Issue by varunsree** [SheetJS/sheetjs#1961]
I am generated xlsx report with 2 tabs, also I place an image in the 2 tabs - The first tab contains the image but Tab2 not. Checked the worksheet and found that both the pages contain images section. but I don't know why the image does not appear in tab2.  Please provide me a solution for this.

 Thanks

**Comment by anfasci** [comment]
Which version you are used?

**Comment by varunsree** [comment]
@anfasci  Version 0.10.2

**Comment by SheetJSDev** [comment]
Images are not currently supported in our open source build, but are an option as part of our [Pro offering](https://sheetjs.com/pro)
