### ISSUE TITLE
Writing Excel - Need the top row of extracted excel to be bold

### ISSUE THREAD

**Issue by ishanjain2801** [SheetJS/sheetjs#1962]
Hi, I am trying to export my table data into excel file. Getting the data correct, but I want to bold my top row, tried everything, but got no success. Need help if anyone is having any idea. Thanks in advance.

Here is the code snippet for the export function I am using:
exportexcel(): void 
    {
      var wscols = [
        {wpx: 150}, // "pixels"
        {wpx: 150}, // "pixels"
        {wpx: 150}, // "pixels"
        {wpx: 150}, // "pixels"
      ];
      /* At 96 PPI, 1 pt = 1 px */
      var wsrows = [
        // {hpx: 16, t:'s'}, // "pixels"
      ];
       /* table id is passed over here */   
       let element = document.getElementById('excel-table'); 
       const ws: XLSX.WorkSheet =XLSX.utils.table_to_sheet(element);

       /* generate workbook and add the worksheet */
       const wb: XLSX.WorkBook = XLSX.utils.book_new();
       XLSX.utils.book_append_sheet(wb, ws, 'Pending_Data');
       ws['!cols'] = wscols;
      //  Bold a cell;
       ws['A1'].s = {font:{sz:14, bold:true}};

       /* save to file */
       XLSX.writeFile(wb, this.fileName, {
        cellStyles: true
    });
			
    }
}
**Output Excel Screenshot:**
![image](https://user-images.githubusercontent.com/55733931/82572556-266e6e00-9ba2-11ea-95f1-901b2ea3e10c.png)

**Comment by SheetJSDev** [comment]
Cell Styling is a feature in our [Pro builds](https://sheetjs.com/pro) but out of scope for the open source build (which is focused on data processing)
