### ISSUE TITLE
Problem in cell computation

### ISSUE THREAD

**Issue by jchapelle** [SheetJS/sheetjs#1963]
I have created a repl project in order to illustrate my issue
https://repl.it/@JeanChapelle/IntentTerribleSdk

You have to be patient bwhen going to the repl (it is a bit slow)

When executed, you will see that some cells are not properly computed.

**Comment by SheetJSDev** [comment]
Computing the results of formula expressions in JS is not supported in this library.  As part of our [Pro offering](https://sheetjs.com/pro), we have a formula calculator capable of refreshing the workbook values
