### ISSUE TITLE
Build process (dist folder)

### ISSUE THREAD

**Issue by szilardd** [SheetJS/sheetjs#1964]
I implemented a change - added support for this:

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

If it is something generic and might be useful for others, I could open a PR to be reviewed.

Until then I would like to create a fork and publish to npm to test, but I'm not sure how to build the project to the `dist` folder (mainly how to re-generate `xlsx.full.min.js`). 

Any help would be appreciated related to publishing the project to npm. Thanks

**Comment by SheetJSDev** [comment]
`make dist` builds the files in the `dist` directory.  You probably need to install `@sheetjs/uglify-js` globally
