### ISSUE TITLE
value "49.03-" in csv leads to crazy result

### ISSUE THREAD

**Issue by flaushi** [SheetJS/sheetjs#1966]
I am reading a CSV file, with following minimal example:

```
var wb = XLSX.read("bla\n5.5\nheyho\n49.03\n-49.03\n49.01-\n49.02-\n49.03-\n49.04-", {type: 'string'})
    var list:anyObject[] = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
    console.log(list)
```
which gives the following output:
```
console.log
    [
      { bla: 5.5 },
      { bla: 'heyho' },
      { bla: 49.03 },
      { bla: -49.03 },
      { bla: '49.01-' },
      { bla: 54455.041666666664 },
      { bla: 54483.041666666664 },
      { bla: 54514 }
    ]
``` 
why is this number

**Comment by SheetJSDev** [comment]
Those numbers are actually date codes.  V8 (chrome/node) is super aggressive in date parsing, as you can verify by running `new Date('49.02-')` in your browser console.

To suppress this behavior, pass `raw: true` when you parse:

```js
var wb = XLSX.read("bla\n5.5\nheyho\n49.03\n-49.03\n49.01-\n49.02-\n49.03-\n49.04-", {type: 'string'});
```

Excel is similarly aggressive in date parsing as discussed in studies like https://doi.org/10.1186/s13059-016-1044-7

**Comment by flaushi** [comment]
https://github.com/SheetJS/sheetjs/issues/2196
