### ISSUE TITLE
Excel crashes when printing XLS from https://sheetjs.com/demo/table.html

### ISSUE THREAD

**Issue by lwinsor** [SheetJS/sheetjs#1967]
Steps to produce the problem:
1. From https://sheetjs.com/demo/table.html click [Export to XLS!]
2. For comparison, export XLSX and XLSB too.
3. Open the file in **Excel 365**. In Excel, click [Enable Editing].
4. Ctrl-P to print. ** CRASH **
OR
1. From https://sheetjs.com/demo/table.html click [Export to XLS!]
2. Open the file in **Excel 2010**. Excel title bar shows 'compatibility mode'.
4. Ctrl-P to print. ** CRASH **

The same process does NOT crash if I choose XLSX or XLSB.

The problem details from Excel show fault module mso20win32client.dll for Excel 365 or MSVCR90.dll for Excel 2010.
 
Many thanks!

Bug seen on:
Windows 7, Chrome, Excel 365
Windows 7, Chrome Excel 2010 32-bit

**Comment by lwinsor** [comment]
Also seen on Windows 10.

**Comment by zzfzfz** [comment]
the same bug.
Excel crashes when printing XLS 
Is there any solution？@lwinsor @SheetJSDev

**Comment by SheetJSDev** [comment]
One-line fix (feel free to send a PR): https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L248

```diff
-	if(b8 && _WB.Views) write_biff_rec(ba, "Window2", write_Window2(_WB.Views[0]));
+	if(b8) write_biff_rec(ba, "Window2", write_Window2((_WB.Views||[])[0]));
```

**Comment by zzfzfz** [comment]
it work for me.Thanks @SheetJSDev

**Comment by SheetJSDev** [comment]
0.16.8 update added the fix.  the XLS file exported by the page does not cause Excel to crash when printing.
