### ISSUE TITLE
How to set header row manually when json_to_sheet

### ISSUE THREAD

**Issue by ryuchaehwa** [SheetJS/sheetjs#1968]
Hey, I'm trying to export an excel file using json_to_sheet().
I have 5 different tables and I need to export them in 1 sheet. but I can't set the headers' rows for each table. Any solutions?

**Comment by SheetJSDev** [comment]
`aoa_to_sheet` and `json_to_sheet` create new worksheets; `sheet_add_aoa` and `sheet_add_json` add to an existing worksheet
