### ISSUE TITLE
split cell into rows

### ISSUE THREAD

**Issue by peppeg85** [SheetJS/sheetjs#1970]
hello, is there a way to split a cell into multiple rows, now i use 

```XLSX.utils.table_to_book(table,` {raw: true});```

 for example i have table with divs inside a td, is there a way to create more rows for each td inside the same cell?

**Comment by SheetJSDev** [comment]
DIVs within a table won't map to multiple lines.  If you really need more rows, set the rowspan of the element you want to export:

```html
<table>
  <tr>
    <td rowspan="2">A1:A2</td>
    <td>B1</td>
  </tr>
  <tr>
    <td>B2</td>
  </tr>
</table>
```
