### ISSUE TITLE
We found a problem with some content in the "fileName"

### ISSUE THREAD

**Issue by stabishali8** [SheetJS/sheetjs#1971]
We are installing xlsx in our typescript project with file-saver library and place the index.d.ts file from node_modules/xlsx to node_modules/@types/xlsx and resolve the CFB and SSF dependency through place these folder into node_modules/@types/xlsx also install file-saver.
create the simple example in test.js separate project with below code:

```
const XLSX=require('xlsx');
let wb= XLSX.utils.book_new();

let data=[
    ['hello','world'],
    [12,112]
];

let s1=XLSX.utils.aoa_to_sheet(data);

XLSX.utils.book_append_sheet(wb,s1,'Test Sheet');

XLSX.writeFile(wb,'./TEST.xlsx');`

but in typescript project we have written the same code below

`import * as XLSX from 'xlsx';
import 'file-saver';

export default class Export{

    public static _export(){
        let wb= XLSX.utils.book_new();

        let data=[
            ['hello','world'],
            [12,34]
        ];

        let s1=XLSX.utils.aoa_to_sheet(data);

        XLSX.utils.book_append_sheet(wb,s1,'Test Sheet');

        XLSX.writeFile(wb,'./TEST.xls');
    }
}
```

that generate file but not open with we found a problem with some content in the "fileName" error.

**Comment by SheetJSDev** [comment]
Can you test the export without importing `file-saver`?  Are you running in the browser or nodejs? 
 Also, is this an angular project or your own custom configuration?

**Comment by stabishali8** [comment]
Yes, I'm running without import `file-saver`  but its not running. I'm running in browser that not working while i'm creating a test node project that working , it is not angular project.

**Comment by reviewher** [comment]
Your first example used 

```js
XLSX.writeFile(wb,'./TEST.xlsx');`
```

Second example

```
        XLSX.writeFile(wb,'./TEST.xls');
```

Try writing the file as XLSX in your app

**Comment by reviewher** [comment]
Without `saveAs` I was able to reproduce this issue on codesandbox.  It seems to come from https://github.com/jvilk/BrowserFS and differences between how the shimmed buffer works and how NodeJS buffers actually work.  If possible, disable the browser shim for Buffer
