### ISSUE TITLE
How can I convert excel file to HTML with sheet JS with all the formatting?

### ISSUE THREAD

**Issue by Shaiwal** [SheetJS/sheetjs#1972]
Hi, I am looking for a solution where excel can be converted into webpage/HTML with all formatting in excel like font, background color, images etc.
How can this be done? 
Also, how can I read only not hidden sheets in a workbook?
Currently, I am using this:
 XLSX.write(wb,{sheet:'Introduction', type:'buffer',bookType:'html'});

**Comment by SheetJSDev** [comment]
This is a feature of our [Pro builds](https://sheetjs.com/pro)
