### ISSUE TITLE
aoa_to_sheet escapes column named ID

### ISSUE THREAD

**Issue by akoskm** [SheetJS/sheetjs#1973]
I'm using two following snippet to generate a one-line CSV or XLS document:

```
  const ws = XLSX.utils.aoa_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'SheetJS');
  contents = XLSX.write(wb, { type: 'buffer', bookType: type });
```

It looks like a column named ID is always wrapped with "" no matter what. Here are some example input and generated output with the above code:
## 1
input:
```
[[ 'ID', 'name' ]]
```
output:
```
"ID",name
```
## 2
input:
```
[[ 'name', 'age' ]]
```
output:
```
name,age
```
## 3
input:
```
[[ 'name', 'age', 'ID' ]]
```
output:
```
name,age,"ID"
```

**Comment by SheetJSDev** [comment]
There's an Excel format called ["Symbolic Link (SLK)"](https://en.wikipedia.org/wiki/SYmbolic_LinK_(SYLK)).  Excel still supports it on read and on write.  SYLK files start with `ID`, and a CSV file that starts with ID will be parsed as SYLK by Excel (and you oftentimes see an error if you try to open it), so we proactively "fix the issue" by wrapping a column named `ID` in double quotes.

The KB article was taken down, but https://web.archive.org/web/20150407135254/http://support.microsoft.com/en-us/kb/323626 is an archive of the MS support page about that issue

**Comment by akoskm** [comment]
Thank you. 🙇
