### ISSUE TITLE
v0.16 changelog

### ISSUE THREAD

**Issue by marcoValkyriweb** [SheetJS/sheetjs#1974]
Hi,

would it be possible to get the change log for v0.16 and v0.16.1?

I also can't seem to find a tag relating to it or a release.

![image](https://user-images.githubusercontent.com/34270069/83485058-828c9880-a4a6-11ea-865a-8243e9e91398.png)

Kind regards,
Marco

**Comment by SheetJSDev** [comment]
Each commit labeled as "version bump" is exactly what we push to `npm` (but we'll go back and add a tag)

Between 0.16.0 and 0.16.1:

- skip empty custom property tags if no data is present (fixes issue with DocSecurity)
- HTML output add raw value, type, number format
- DOM parse look for `v` / `t` / `z` attributes when determining value
- double quotes in properties escaped using `_x0022_`
- changed AMD structure to satisfy NetSuite and other non-compliant RequireJS implementations
- `encode_cell` and `decode_cell` do not rely on `encode_col` / `decode_col`

**Comment by SheetJSDev** [comment]
tags have been added:

- `v0.16.0` -> 257d4e6db2444ce1a0be814c1c352423f4aba7b5
- `v0.16.1` -> baea1798cf825a2cc8b1365cb7818605a8d4f464
