### ISSUE TITLE
date filter in the excel is not working when I use XLSX.utils.json_to_sheet(res).

### ISSUE THREAD

**Issue by Ashab31** [SheetJS/sheetjs#1978]
I am not able to filter the date column when I use **XLSX.utils.json_to_sheet(response)**. I can only filter based on all the dates, but the actual behavior should be according to year and according to the months. Can anybody help asap. 
<img width="605" alt="dateFilterIssue" src="https://user-images.githubusercontent.com/25655534/83746943-7ad31c80-a67d-11ea-8faf-5e84934c17f8.png">

**Comment by QuattroEngenharia** [comment]
I'm having the same problem! Did you find the solution? @Ashab31

**Comment by SheetJSDev** [comment]
That looks like the column is text.  `json_to_sheet` does not automatically convert text-containing-dates into numeric or date cells -- they are still text.  You need to go back and convert strings to dates:

```js
var fixed_data = response.map(row => Object.assign({}, row, {Request: new Date(row.Request)}));
var ws = XLSX.utils.json_to_sheet(fixed_data);
```
