### ISSUE TITLE
Questions About Cell Display

### ISSUE THREAD

**Issue by calioto** [SheetJS/sheetjs#1979]
I have two questions.
1) Is it possible to have a new line in a cell if the html table the data is exported from represents the data on two separate lines with div tags? The table on the web shows multiple entries in a single cell, but the export shrinks it to a single line. I have attached a pic.
![spreadsheet](https://user-images.githubusercontent.com/29551362/83802605-a996c600-a670-11ea-90eb-69af9150b3d7.PNG)
![web](https://user-images.githubusercontent.com/29551362/83802606-aa2f5c80-a670-11ea-9dd7-4a3681ead097.PNG)

2) Is it possible to have the "Word wrap" attribute of the cell set to true by default?

Thanks in advance for your time.

~ Christopher

**Comment by calioto** [comment]
I was able to solve my first question on my own. However, after looking at the documentation and doing many tests, I can't get the word wrap to work. I have this in my code:
`    for (rowIndex = range.s.r; rowIndex <= range.e.r; rowIndex++) {
      for (colIndex = range.s.c; colIndex <= range.e.c; colIndex++) {
        if (rowIndex > 0 && colIndex > 1) {
          cellRef = XLSX.utils.encode_cell({c: colIndex, r: rowIndex});
          currentCell = ws[cellRef];
          ws[cellRef] = {t: ws[cellRef].t, v: ws[cellRef].v.replace('|', '\n'), s: {alignment: {wrapText: true}}};
          console.log(ws[cellRef]);
        }
      }
    }
`
This snippet will parse through my table, replace | with newline and **should** mark the cell to use word wrap, but that isn't being done. Can anyone help? Thanks.

~ Christopher

**Comment by SheetJSDev** [comment]
Styling features are part of our [Pro Basic build](https://sheetjs.com/pro) and not currently included in our open source software
