### ISSUE TITLE
Electron Demo "Click here to select a file" does not load file properly.

### ISSUE THREAD

**Issue by ianjennings** [SheetJS/sheetjs#1981]
When clicking on the button highlighted in red, the file prompt shows but the UI does not respond to the selected file.

The functionality highlighted in green works properly.

![image](https://user-images.githubusercontent.com/318295/83813413-e8357c00-a682-11ea-88db-d52761aea555.png)

Tested with the example xlsx files [here](https://file-examples.com/index.php/sample-documents-download/sample-xls-download/).

**Comment by SheetJSDev** [comment]
This is related to an API change somewhere between 1.7.5 and 9.

https://github.com/SheetJS/sheetjs/blob/master/demos/electron/index.js#L68 the code uses `electron.dialog.showOpenDialog` and grabs the result.

The current version returns a promise https://www.electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options

However 1.7.5 returned an array of strings https://github.com/electron/electron/blob/v1.7.5/docs/api/dialog.md

The easiest thing might be to change the call to [`showOpenDialogSync`](https://www.electronjs.org/docs/api/dialog#dialogshowopendialogsyncbrowserwindow-options), adding a proper guard for the case that the dialog is canceled.
