### ISSUE TITLE
version 0.16 question

### ISSUE THREAD

**Issue by sibelius** [SheetJS/sheetjs#1982]
> Date handling changed

what exactly changed?

**Comment by SheetJSDev** [comment]
Date -> Date code:

```
base date = 12/30/1899 0:00:00 in the current locale

old behavior: code = date - (base date - base TZ offset + current TZ offset)

new behavior: code = date - (base date - base TZ offset + TZ offset of date)
```

Date Code -> Date adjusted for consistency 

This is still not 100% correct (thanks to weird fractional artifacts in timezones like Asia/Hong_Kong)

**Comment by sibelius** [comment]
Tks
