### ISSUE TITLE
XLSX.read  miss cell 

### ISSUE THREAD

**Issue by 136323000** [SheetJS/sheetjs#1983]
I have a csv like this：

data
1
2

I  use following code to read it 
var reader = new FileReader();
	reader.onload = function (e) {
	var data = new Uint8Array(e.target.result);
	var workbook = XLSX.read(data, { type: 'array' });
	console.log(workbook)
	};
	reader.readAsArrayBuffer(file);

When I console.log(workbook)  I expect  get data like this:
Sheet1:
!ref: "A1:A3"
A1: {v: "data", t: "s"}
A2: {v: 1, t: "n"}
A3: {v: 2, t: "n"}

But I got the following data
Sheet1:
!ref: "A1:A5"
A1: {v: "data", t: "s"}
A3: {v: 1, t: "n"}
A5: {v: 2, t: "n"}

Why?? where is A2? Why miss A2?

**Comment by SheetJSDev** [comment]
Can you share the bytes of the file?  `console.log(data)` just before the `XLSX.read` call, expand the console so you can see the numbers, and take a screenshot

**Comment by 136323000** [comment]
> Can you share the bytes of the file? `console.log(data)` just before the `XLSX.read` call, expand the console so you can see the numbers, and take a screenshot

<body>
  <input type="file" class="excelFile" id="excelFile">
  <input type="button" value="go" class="go">
  <script src="./jquery.js"></script>
  <script src="./xlsx.core.min.js"></script>
  <script>
    
    $('.go').click(()=>{
      file = $('.excelFile')[0].files[0]
      var reader = new FileReader();
      reader.onload = function (e) {
        var data = new Uint8Array(e.target.result);
        var workbook = XLSX.read(data, { type: 'array' });
        console.log(workbook)
      };
      reader.readAsArrayBuffer(file);
    })
    
  </script>
</body>

**Comment by 136323000** [comment]
<body>
  <input type="file" class="excelFile" id="excelFile">
  <input type="button" value="go" class="go">
  <script src="./jquery.js"></script>
  <script src="./xlsx.core.min.js"></script>
  <script>
    
    $('.go').click(()=>{
      file = $('.excelFile')[0].files[0]
      var reader = new FileReader();
      reader.onload = function (e) {
        var data = new Uint8Array(e.target.result);
        var workbook = XLSX.read(data, { type: 'array' });
        console.log(workbook)
      };
      reader.readAsArrayBuffer(file);
    })
    
  </script>
</body>

**Comment by 136323000** [comment]
<body>
  <input type="file" class="excelFile" id="excelFile">
  <input type="button" value="go" class="go">
  <script src="./jquery.js"></script>

  <script src="./xlsx.core.min.js"></script>

  <script>
    
    $('.go').click(()=>{
      file = $('.excelFile')[0].files[0]
      var reader = new FileReader();
      reader.onload = function (e) {
        var data = new Uint8Array(e.target.result);
        var workbook = XLSX.read(data, { type: 'array' });
        console.log(workbook)
      };
      reader.readAsArrayBuffer(file);
    })
    
  </script>
</body>

**Comment by 136323000** [comment]
<input type="file" class="excelFile" id="excelFile">
  <input type="button" value="go" class="go">
  <script src="./jquery.js"></script>
  <script src="./xlsx.core.min.js"></script>
  <script>
    
    $('.go').click(()=>{
      file = $('.excelFile')[0].files[0]
      var reader = new FileReader();
      reader.onload = function (e) {
        var data = new Uint8Array(e.target.result);
        var workbook = XLSX.read(data, { type: 'array' });
        console.log(workbook)
      };
      reader.readAsArrayBuffer(file);
    })
    
  </script>

**Comment by 136323000** [comment]
![image](https://user-images.githubusercontent.com/49808133/83830949-f2a25500-a718-11ea-9cfd-ec03815a9392.png)

**Comment by 136323000** [comment]
> 您可以共享文件的字节吗？ `console.log(data)`在`XLSX.read`通话之前，展开控制台，以便您可以看到号码并截图


[WWW.zip](https://github.com/SheetJS/sheetjs/files/4733623/WWW.zip)

**Comment by 136323000** [comment]
![image](https://user-images.githubusercontent.com/49808133/83831211-7fe5a980-a719-11ea-9ede-5e18fd5722b2.png)
![image](https://user-images.githubusercontent.com/49808133/83831224-870cb780-a719-11ea-9ab7-ecbb2965f91a.png)

**Comment by 136323000** [comment]
this is my codeThank you very much
[WWW.zip](https://github.com/SheetJS/sheetjs/files/4733650/WWW.zip)

**Comment by SheetJSDev** [comment]
This has the same root cause as #1976 , and #1977 should fix the issue

**Comment by 136323000** [comment]
> This has the same root cause as #1976 , and #1977 should fix the issue

ok thankyou verymuch
