### ISSUE TITLE
I get this error "'default' is not exported by ./node_modules/xlsx/xlsx.js, imported by ./src/services/XLSX.service.ts"

### ISSUE THREAD

**Issue by Bandito11** [SheetJS/sheetjs#1984]
```
 ./src/services/XLSX.service.ts, line 1, column 7
'default' is not exported by ./node_modules/xlsx/xlsx.js, imported by ./src/services/XLSX.service.ts

```
The reason this happens is that the index.d.ts doesn't have a default exported variable.

**Comment by SheetJSDev** [comment]
You most likely will need the glob import form

```ts
import * as XLSX from 'xlsx'
```

**Comment by Bandito11** [comment]
Hi

I tried doing this but had no luck. I think it is a warning message from Rollup because everything works as expected though.

Thanks!
Esteban Morales

________________________________

**Comment by SheetJSDev** [comment]
To be sure, this is not an ES6 module, so you might need `rollup-plugin-commonjs` and `rollup-plugin-node-resolve` (see https://github.com/SheetJS/sheetjs/tree/master/demos/rollup#required-plugins for an old demo when we were testing)

**Comment by Bandito11** [comment]
Awesome

I will tried this when I get back home and see if it works, thanks.

Esteban Morales
________________________________
