### ISSUE TITLE
xlsx read file not giving any error on providing corrupted file

### ISSUE THREAD

**Issue by adityapatil123** [SheetJS/sheetjs#1985]
I tried reading corrupted xlsx file, but it is not giving any error
My code:
```const reader = new FileReader();
 reader.onload = (evt) => {
      /* Parse data */
      const bstr = evt.target.result;
      const wb = XLSX.read(bstr, {
        type: "binary", 
        sheetRows: no_of_rows,
        WTF: true,
      });
      console.log(wb);
 }
 reader.onerror = (resp) => {
      console.log(resp);
 };
 reader.readAsBinaryString(file);
```

I've attached one corrupted file
[corrupted.xlsx](https://github.com/SheetJS/sheetjs/files/4744296/corrupted.xlsx)

**Comment by SheetJSDev** [comment]
Locally this shows an error:

```
			switch(state[state.length-1][0]) {
			                            ^

TypeError: Cannot read property '0' of undefined
```

You can see the same error on https://oss.sheetjs.com/sheetjs/ when submitting your file:

<img width="266" alt="" src="https://user-images.githubusercontent.com/6070939/90344478-3dc5c780-dfe8-11ea-877c-07636ea6ee21.png">

Are you sure that file was being read properly?
