### ISSUE TITLE
Error with usage of Input Type "string" with FileReader.readAsText

### ISSUE THREAD

**Issue by adrai** [SheetJS/sheetjs#1986]
I need to use the FileReader.readAsText api..
How does it work? I tried with [Input Type](https://github.com/SheetJS/sheetjs#input-type) "string", but this results in this error: **"End of data reached (data length = 13384, asked index = 21505). Corrupted zip ?"**
![image](https://user-images.githubusercontent.com/1086194/84014921-5e83f800-a97b-11ea-94e6-daa309e18a5a.png)

Here you see a codesandbox example: https://codesandbox.io/s/sheetjs-example-cwwzv?file=/src/SheetRead.js

FileReader.readAsBinaryString works, but I only have the output of FileReader.readAsText 😢

Any help is welcome. 🙏

**Comment by SheetJSDev** [comment]
You can't use `readAsText` as it corrupts binary strings that don't map neatly to UCS2 or UTF8 text.  If you don't have access to `readAsBinaryString` you can also use `readAsArrayBuffer`.
