### ISSUE TITLE
When i pass Buffer in read Function I will get this Error

### ISSUE THREAD

**Issue by vibh1103** [SheetJS/sheetjs#1987]
![Screenshot from 2020-06-08 15-43-00](https://user-images.githubusercontent.com/37906533/84019496-fa732b00-a99e-11ea-966b-59215498c853.png)

**Comment by SheetJSDev** [comment]
Can you share the part of the code that's reading the file, the actual object you are passing to read and a snippet of code that includes the read call?  It looks like you're passing a buffer but specifying `type: "base64"`

**Comment by SheetJSDev** [comment]
(we can reopen once you follow up)
