### ISSUE TITLE
Excel file not loading unless I save it on my pc  first

### ISSUE THREAD

**Issue by Leccho** [SheetJS/sheetjs#1988]
I have this excel file wich is produce by an other app wich is not mine.

I download this file and then upload it to my application (angular 9). This will give me a workbook but there is no sheets in it. If I open and save the same file, this will open and work as expected.

Now I don't want to have to pass trought this step. I don't know if that's a bug or a security mesure, but if it's a security mesure I would like to know how to bypass it.

Here you can see my code:

```typescript
public onFileChange(e: any): void {
    this.fileContent = [];
    let workBook = null;
    let jsonData = null;
    const reader = new FileReader();
    const file = e.target.files[0];
    if (!file) {
      return;
    }
    reader.onload = (event) => {
          const data = reader.result;
          workBook = XLSX.read(data, { type: 'binary' });
          console.log(workBook);
          jsonData = workBook.SheetNames.reduce((initial, name) => {
            const sheet = workBook.Sheets[name];
            initial[name] = XLSX.utils.sheet_to_json(sheet, { header: 1 });
            return initial;
          }, {});
          jsonData = jsonData.Sheet1;
          console.log(jsonData);
          jsonData = jsonData.slice(3);
          jsonData.forEach((t: any) => {
            ...
          });
          this.saveFile();
        };
        reader.readAsBinaryString(file);
  }
```

**Comment by Leccho** [comment]
It would seems that the file dosen't have any sheet in it and by opening and saving it, I create a sheet wich is then usable. I would like to know if it is possible to create that sheet without having to open it manually to save it.

**Comment by SheetJSDev** [comment]
Can you share the file @Leccho ?

**Comment by Leccho** [comment]
No there's sensible information in it and since it's not my program, I can't produce a dummy.

**Comment by Leccho** [comment]
File without presaving it:
Sheets {}
SheetNames []
Strings (172) [{.........

File after opening in excel, save and close:
Sheets {Sheet1: {.............}} (contain all rows)
SheetNames ["Sheet1"]
Strings (172) [{.........

**Comment by SheetJSDev** [comment]
There's probably some sort of parse error.  Can you read the file with the option `WTF: 1`:

```js
          workBook = XLSX.read(data, { type: 'binary', WTF:1 });
```

A bunch of errors are silently ignored by default, the `WTF` option forces them to be thrown

**Comment by Leccho** [comment]
I guess my question would be could I create that Sheet1 programmatically ?

**Comment by Leccho** [comment]
No error is raised. I feel like what should be done is creating this sheet programmatically just as if I openned the file and saved it myself. Is there a way to do such thing ?

**Comment by Leccho** [comment]
Well I don't think this is a SheetJS issue so I'm gonna close this.
