### ISSUE TITLE
when the data is too large，how to append to the "ws"

### ISSUE THREAD

**Issue by x8q7** [SheetJS/sheetjs#1989]
When the amount of data is large, the memory crashes

**Comment by Noitidart** [comment]
Were you able to solve this?

**Comment by kireeti123** [comment]
We face the same issue.

**Comment by Noitidart** [comment]
Any solutions?

**Comment by kireeti123** [comment]
We could able to get to alternative options but not solution to the issue.
But these may not be a solution to you if you are not dealing with raw text
data.

1. We started passing only a chunk of data to convert into a sheet. That
way we are showing multiple sheets on the same excel sheet.

2nd options, we are first converting our Jason data to a sheet object by
passing multiple chunks. Once each sheet object we are getting then we are
converting that to a CSV. After that, we are appending a carriage return at
the end of each CSV text string.  Once we are done with the conversion,
reading that string text and writing it into a . csv file. As we are mostly
dealing with text data only, we were not only able to get the data into a
CSV file and also keeping the file size 3x times less than the .xlsx file.
This is giving us an option to download more data.

Regards,
Krishna

**Comment by x8q7** [comment]
> Were you able to solve this?
I use another package "xlsx", it's very nice

**Comment by x8q7** [comment]
I use another package "xlsx", it's very nice
@kireeti123 @Noitidart

**Comment by Noitidart** [comment]
@x8q7 can you please share your technique with that xlsx package?

**Comment by x8q7** [comment]
https://www.npmjs.com/package/xlsx

**Comment by x8q7** [comment]
https://www.npmjs.com/package/xlsx
@Noitidart

**Comment by x8q7** [comment]
it suport stream append to sheet
@Noitidart

**Comment by Noitidart** [comment]
Thank you!

**Comment by x8q7** [comment]
u are wellcome！

**Comment by x8q7** [comment]
> @x8q7 can you please share your technique with that xlsx package?

Sorry i said wrong，please use this
https://github.com/exceljs/exceljs

@Noitidart

**Comment by Noitidart** [comment]
Thank you @x8q7 !
