### ISSUE TITLE
use nested json object to create multiple table in excel single sheet

### ISSUE THREAD

**Issue by damchothinley** [SheetJS/sheetjs#1990]
Can anyone here please help me solve the problem at the link below. I have tried for the last couple of hours and couldn't find a solution or any idea.
https://stackoverflow.com/questions/62294696/use-nested-json-object-to-create-multiple-table

**Comment by karthik22061993** [comment]
Hi  damchothinley  I have similiar issue I want to write this JSON to excel
{ "name": "John", "class": 1, "address" : [ { "street": "12th Cross" , "City": "London" } ] }

Later when I read back I want to get same JSON from excel file
