### ISSUE TITLE
Grouped column title not displaying correctly on download

### ISSUE THREAD

**Issue by millamanjko** [SheetJS/sheetjs#1991]
I'm using tabulator and when I download a xlsx file the title of the column 'Progress' goes behind the first merged column 'Name', I tried everything I could find but with no success. Does anyone have a solution for this?

Working fiddle:
https://jsfiddle.net/millamanjko/qxk4fbam/4/

**Comment by millamanjko** [comment]
Just in case anyone else may still need a solution I found one, adding the documentProcessing function I can edit the content of the cells and "correct" the behavior:

https://jsfiddle.net/millamanjko/qxk4fbam/54

`$("#download-xlsx1").click(function() {
  table1.download("xlsx", "data.xlsx", {
    documentProcessing: function(workbook) {
      //workbook - sheetJS workbook object

      var ws_name = workbook.SheetNames[0];
      var ws = workbook.Sheets[ws_name];

      // Removes the text from cell A2
      ws["A2"] = {
        t: 's', // <-- t: 's' indicates the cell is a text cell
        v: "" // <-- v holds the value
      };

      // Changes the text from cell B2
      ws["B2"] = {
        t: 's', // <-- t: 's' indicates the cell is a text cell
        v: "Progress" // <-- v holds the value
      };

      return workbook;
    },
  });
});`

**Comment by SheetJSDev** [comment]
This was a tabulator bug which appears to have been fixed in the latest version.  You can verify by removing the tabulator resources in the fiddle (which use 4.2.7) and use the latest versions of the css and js (4.9.3)
