### ISSUE TITLE
I need to do a template, modify it and save it, but..

### ISSUE THREAD

**Issue by agulencina96** [SheetJS/sheetjs#1992]
First at all sorry for my english, im not a native speaker :c
Basically I have an array of objects that represent the column titles and the values ​​of each row, and I need to put a title and two images in the header before putting all the data in the array.

I was thinking that I could have a template with the header already assembled, and then add my entire array underneath that header, but I can't find a way to do it.

This is the way that i use to export the xlsx file, json is the final array... i need to puto the header on my "json"

`async generateExcel(json: any[], excelFileName: string) {
    if (json != null) {
      const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
      const workbook: XLSX.WorkBook = {
        Sheets: { data: worksheet },
        SheetNames: ["data"],
      };
      const excelBuffer: any = XLSX.write(workbook, {
        bookType: "xlsx",
        type: "array",
      });
      this.saveAsExcelFile(excelBuffer, excelFileName);
    } else {
      this.msg.error("NO HAY DATOS PARA EXPORTAR");
    }
  `}

Thank you!

**Comment by SheetJSDev** [comment]
One of the components in our [Pro compendium](https://sheetjs.com/pro) lets you preserve the original file structure and surgically modify the data.  It's so far outside of the core data processing goals of the open source project that we are not likely to add it.
