### ISSUE TITLE
Can't get worksheet from binary string that starts with 4 or more tabs

### ISSUE THREAD

**Issue by ivansg44** [SheetJS/sheetjs#1993]
`XLSX.read('\t\t\t', {type: 'binary'})` returns a workbook with one worksheet.

`XLSX.read('\t\t\t\t', {type: 'binary'})` returns a workbook with no worksheets.

**Comment by tehnuge** [comment]
@SheetJSDev How should we parse as DBF? If to_workbook returned  `{ SheetNames: [], Sheets: {} }`, could we assume that it is not a DBF? Also, would it make sense to throw the error [here](https://github.com/SheetJS/sheetjs/blob/5c1296a46d584a47059e6fbc758201f32ef55ed7/bits/40_harb.js#L210) in the DBF to_workbook function instead?

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/blob/master/bits/40_harb.js#L74 this is the list of supported versions.  So maybe the best thing to do is:

1) add an array with all of the cases from that switch block ( `[0x02, 0x03, ...]` ) just before the `dbf_to_aoa` function definition.  Call it something like `DBF_SUPPORTED_VERSIONS`

2) Make sure DBF exposes it by adding a key to https://github.com/SheetJS/sheetjs/blob/master/bits/40_harb.js#L311, something like `versions: DBF_SUPPORTED_VERSIONS`

3) in https://github.com/SheetJS/sheetjs/blob/master/bits/87_read.js#L98, check if the first value is a valid version number.  The new if statement would be something like

```js
	if(DBF.versions.indexOf(n[0]) > -1 && n[2] <= 12 && n[3] <= 31) return DBF.to_workbook(d, o);
```

I think that would address this particular issue
