### ISSUE TITLE
export .xls file error

### ISSUE THREAD

**Issue by jyuns** [SheetJS/sheetjs#1995]
Dear All,

When i open .xls(Excel 97-2003) file and update, then exporting to just same type with .xls.
But when i opened it. alert come throw like screenshot

![image](https://user-images.githubusercontent.com/58207884/84349688-cd1ebb00-abf2-11ea-88dd-7f319a243b56.png)

I have some code that is exporting .xls file. 
`XLSX.write(workbook, this.files[x].path, {
bookType:'xlsx', type:'binary'}`

is there any type that supports versions Excel 97-2003?

Thanks for your help and time

**Comment by SheetJSDev** [comment]
You probably meant `XLSX.writeFile`.

Can you share the bad file?  If you can't do it publicly, email us.

If you want to generate an `xls` file, using `XLSX.writeFile` just specify a filename with the `xls` extension.  If you are using `XLSX.write` set the option `bookType: 'xls'`

**Comment by jyuns** [comment]
> F

Yep. Right `XLSX.writeFile`!

Can i share you with the bad file? where is ur email address?

**Comment by SheetJSDev** [comment]
hello@sheetjs.com works

**Comment by jyuns** [comment]
Thx a lot!!!
