### ISSUE TITLE
Cannot read special characters

### ISSUE THREAD

**Issue by hungdev** [SheetJS/sheetjs#1996]
Hi. Thanks for your work.
I have a problem with special characters in csv file.
With cell value are: ość, chào cưng, số học ... it can not read, it shows `os___`,  and `cho c_ng`,
Could you tell me how to keep original format.
Here is my file: https://drive.google.com/file/d/16hpgli5ZOzSsEob4_14Q2WDBDtFEFiJU/view?usp=sharing
and here is my code:
https://stackblitz.com/edit/react-excel-to-json-parser?file=ExcelReader.js

Thanks!

**Comment by hungdev** [comment]
@SheetJSDev can you check it for me?

**Comment by ViniciusFXavier** [comment]
Same problem here

**Comment by hungdev** [comment]
@ViniciusFXavier so i changed to https://github.com/nzambello/react-csv-reader
If you want, you can try it =)))

**Comment by SheetJSDev** [comment]
Can't access the file @hungdev but most likely you're specifying a UTF-8 file without the BOM.  Without the BOM, Excel defaults to the local codepage.  To force UTF-8 treatment, [pass the option `codepage: 65001` to read or readFile](https://docs.sheetjs.com/#parsing-options)

**Comment by Dshah-bb** [comment]
@SheetJSDev Can you please let me know what should be done in case of write to UTF-8 with BOM? Below is the sample of the code I am using
`this.workBookCreator.setReport(report);
        this.workBookCreator.setTranslations(translations);
        this.workBookCreator.setReportMetadata(reportMetadata);
        this.workBookCreator.setColumnsToIncludeInReport(columnsToIncludeInReport);
        this.workBookCreator.setTypeHints(typeHints);
        this.workBookCreator.setCustomFields(customFields);

        let workbook: WorkBook = this.workBookCreator.getWorkbook(workBookName);

        return this.xlsxModule.write(workbook, {
            bookType: 'csv',
            type: "string"
        });`

When I try to open this file in Excel it is not considering UTF-8 and the special characters are broken
