### ISSUE TITLE
stylesheet and alignment not apply in excel

### ISSUE THREAD

**Issue by ajju123** [SheetJS/sheetjs#1997]
I am using xlsx and xlsx-style in angular, styles are not reflecting in excel. code is 
 const range = StyleUtils.decode_range(ws['!ref']);
    for(let R = range.s.r+1; R <= range.e.r; ++R) {
      const refNum = StyleUtils.encode_cell({c:11, r:R});
      this.setTextFmt(refNum,ws);
    }
  private setTextFmt(cell: StyleCellObject,ws:any){
    if(ws[cell]){
      ws[cell].t = 's';
      ws[cell].s =  {
                          font: { name: 'Abadi', sz: 10, bold: true },
                         alignment: { wrapText: true, vertical: 'center', horizontal: 'center' }
                         };
     }
  }

**Comment by SheetJSDev** [comment]
Styles like cell alignment and font properties are not included here but are part of our [Pro builds](https://sheetjs.com/pro)
