### ISSUE TITLE
Documentation for xlsx.mini.min.js ?

### ISSUE THREAD

**Issue by sheffieldnick** [SheetJS/sheetjs#1999]
Could some brief documentation be added for the mini build of the library please? Which features/file formats it supports. Thanks

**Comment by sheffieldnick** [comment]
So far I've found xlsx.mini.js can read .xlsx, .dbf, .dif, .slk, .xlsm and .xlsx formats. It doesn't support reading .xls, .ods or .fods. Don't know about other formats, or about writing support.

**Comment by SheetJSDev** [comment]
The mini build includes a subset of the bits.  Comparing to the full build:

- codepage library skipped (no support for XLS encodings)
- XLSX compression option not currently available (full uses a forked jszip; mini uses the cfb library for zip support)
- no support for XLSB / XLS / Lotus 1-2-3 / ODS / SpreadsheetML 2003
- node stream utils removed
