### ISSUE TITLE
Is there any limit something that string length per cell in .xls(Excel 97-2003)?

### ISSUE THREAD

**Issue by jyuns** [SheetJS/sheetjs#2006]
Hi. everyone.

When i update my .xls file with Sheetjs, the file was corrupted. cause string length.

I take almost 30,000 length per cell. anyway.

but, when i take file that have maybe 3,000 length per cell. everything Ok.

could u help me?

**Comment by SheetJSDev** [comment]
Excel enforces a limit of `32767` characters in a cell.  Can you give an example of text that is being truncated?  (SST continue records, which allow for a table size beyond 8000 characters, was merged relatively recently)
