### ISSUE TITLE
Parses deleted rows

### ISSUE THREAD

**Issue by alexeychikk** [SheetJS/sheetjs#2007]
I have the following excel file:
[deleted_example.xlsx](https://github.com/SheetJS/sheetjs/files/4785712/deleted_example.xlsx)
If you open it you should see that is has only one row with data. But calling 
```ts
const wb = XLSX.readFile("deleted_example.xlsx");
const rows = XLSX.utils.sheet_to_json(wb.Sheets["Feuil1"], {
      header: "A",
      raw: false,
      blankrows: true,
    }); 
```
 returns 23 rows **with data** (127 total) that **was deleted** before.

**Comment by garrettluu** [comment]
Hi! I opened your file and discovered that there were some rows with height 0 that have data in them, which would explain this behavior
