### ISSUE TITLE
Does sheetjs provide write content to txt file?

### ISSUE THREAD

**Issue by fayeah** [SheetJS/sheetjs#2012]
sheetjs seems only support sheet related parse/format, ect. Does sheetjs provide write content to txt file like writeFile in nodejs?

**Comment by reviewher** [comment]
Yes, using `writeFile` you can specify a filename with a `".csv"` extension for CSV or a `".txt"` for Unicode (UTF-16) text.

The supported file extensions are listed in the table at https://docs.sheetjs.com/#supported-output-formats
