### ISSUE TITLE
How do I save data using `json_to_sheet` to save formulas?

### ISSUE THREAD

**Issue by ScottChapman** [SheetJS/sheetjs#2017]
So I am creating a bunch of JSON objects I am saving to a sheet. One of the fields should actually be a forumla, specifically I am wanting to create a hyperlink (`=HYPERLINK("<url>","<Display>")).

How does one do that exactly? My objects currently look like:
```json
{
     "company": "google",
     "home": "=HYPERLINK('https://www.google.com','Google')",
}

**Comment by SheetJSDev** [comment]
You can pass cell objects to `json_to_sheet` directly:

```js
var cell = { t:"s", v:"Google" }; // string cell with value "Google"
var data = [
  { company: "google", home: cell } // the "home" key is the cell object
]
var ws = XLSX.utils.json_to_sheet(data, { header: ["company", "home"] } ); // worksheet
```

There are two ways to specify the hyperlink:

A) actual cell hyperlink: see https://docs.sheetjs.com/#hyperlinks for an explanation

```js
var cell = {
  t: "s",
  v: "Google",
  l: { Target: "https://www.google.com", Tooltip: "Not SheetJS :(" } // Target is the URL, optionally specify Tooltip
};
```

B) HYPERLINK formula

Mirroring what you intended to do:

```js
var cell = { t:"s", v:"Google", f: "HYPERLINK('https://www.google.com','Google')" }; // cell with formula, no = prefix
```

**Comment by igorbrasileiro** [comment]
Hello @SheetJSDev , I was trying to add this formula `TEXT(SUM(DATEVALUE("01/21/2020"),TIMEVALUE("09:20:05"),settings!B1/24),"DD/MM/YYYY hh:mm:ss")` but my xls file show a blank cell.

```ts
const row = { A: { t: 's',  f: 'TEXT(SUM(DATEVALUE("01/21/2020"),TIMEVALUE("09:20:05"),settings!B1/24),"DD/MM/YYYY hh:mm:ss")' } }

const ws = XLSX.utils.json_to_sheet([row], { header: ['A'] })
const ws2 = XLSX.utils.json_to_sheet(
    [{ A: 'timezone offset', B: -timezone }],
    { skipHeader: true, header: ['A', 'B'] }
  )

XLSX.utils.book_append_sheet(book, ws, SHEET_NAME) // book already exists
XLSX.utils.book_append_sheet(book, ws2, SETTINGS_SHEET_NAME)
```

**Comment by SheetJSDev** [comment]
XLS / XLSB do not support writing formulae at the moment.

**Comment by szikszail** [comment]
Hi, @SheetJSDev is it planned to add support for writing formulae in XLSB, in the near future?
