### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by piniu** [SheetJS/sheetjs#2022]
Getting this error when trying to read xlsx file (86MB) also tried to stream and buffer but getting the same error. Any idea or direction?
`
                const XLSX = require('xlsx');
                let filePath = data.filePath;

                const readable = fs.createReadStream(filePath);

                function process_RS(stream, callback) {
                    var buffers = [];
                    stream.on("data", function (data) {
                        buffers.push(data);
                    });
                    stream.on("end", function () {
                        let buffer = Buffer.concat(buffers);
                        const workbook = XLSX.read(buffer, { type: "buffer", WTF: true });
                        const sheetNames = workbook.SheetNames;
                        const worksheet = workbook.Sheets[sheetNames[0]];
                        const result = XLSX.utils.sheet_to_json(worksheet);
                        callback(result);
                    });
`

**Comment by SheetJSDev** [comment]
To be sure, is the `read` failing or the `sheet_to_json` call?  NodeJS `ERR_STRING_TOO_LONG` is governed by `kMaxLength` in v8 https://github.com/nodejs/node/blob/master/deps/v8/include/v8.h#L2957 which is ~256 MB or ~512MB depending on `size_t`

**Comment by piniu** [comment]
sheet_to_json is failing 
thanks

**Comment by SheetJSDev** [comment]
This is an issue with NodeJS and a hard limit on the size of the resulting output.

`XLSX.stream.to_json` should be used in node. It creates an object-mode stream:

```js
/* to_json returns an object-mode stream */
var stream = XLSX.stream.to_json(worksheet, {raw:true});

/* the following stream converts JS objects to text via JSON.stringify */
var conv = new Transform({writableObjectMode:true});
conv._transform = function(obj, e, cb){ cb(null, JSON.stringify(obj) + "\n"); };

stream.pipe(conv); conv.pipe(process.stdout);
```

**Comment by iRoachie** [comment]
Hey guys, i have this exact problem but it fails at `XLSX.read(data)`
