### ISSUE TITLE
Can't use style to export data using aoa_to_sheet

### ISSUE THREAD

**Issue by yoozat** [SheetJS/sheetjs#2032]
hello ,
I need generate an excel using my data to be like this : 
![sheet](https://user-images.githubusercontent.com/26425552/85964166-7fef6700-b9b0-11ea-8519-7aa12be22b79.PNG)

it is possible to do this using aoa_to_sheet and use style to make color

**Comment by SheetJSDev** [comment]
Cell and text styling are currently features in our [Pro builds](http://sheetjs.com/pro) and we do not know when/if they will be folded into the open source build.
