### ISSUE TITLE
Using sheetjs to export excel, when the number of rows of data exceeds 5W, there are only dozens of exported data, and there is no problem with the data.

### ISSUE THREAD

**Issue by daisy0123** [SheetJS/sheetjs#2035]
Using sheetjs to export excel, when the number of rows of data exceeds 5W, there are only dozens of exported data, and there is no problem with the data.Please help me

**Comment by crimson968** [comment]
I had the same problem.

**Comment by reviewher** [comment]
If you mean "5 million", the excel formats have a hard limit well below that: https://github.com/sheetjs/sheetjs/#file-formats

| Format                                    | Last Cell  | Max Cols | Max Rows |
|:------------------------------------------|:-----------|---------:|---------:|
| Excel 2007+ XML Formats (XLSX/XLSM)       | XFD1048576 |    16384 |  1048576 |
| Excel 2007+ Binary Format (XLSB BIFF12)   | XFD1048576 |    16384 |  1048576 |
| Excel 97-2004 (XLS BIFF8)                 | IV65536    |      256 |    65536 |
| Excel 5.0/95 (XLS BIFF5)                  | IV16384    |      256 |    16384 |
| Excel 2.0/2.1 (XLS BIFF2)                 | IV16384    |      256 |    16384 |

For more detailed help, please share a file and we can reopen the issue

**Comment by Jun-Ao** [comment]
I had the same problem.(5W === 50000)

**Comment by SheetJSDev** [comment]
Verify the worksheet range (the `!ref` property of the worksheet object) is correct.  If it is, please raise a new issue
