### ISSUE TITLE
Weird chars being generated

### ISSUE THREAD

**Issue by ldsenow** [SheetJS/sheetjs#2037]
Hi there,

I am using the lib in one of my Vue projects with i18n enabled. I have encountered an issue with weird characters generated in the bundle file if I have non-English translation in Vue file. I looked at the file encoding, it becomes ANSI not UTF-8. The bundle file will be fine if I remove the xlsx lib. Not sure if it is the issue of combination of webpack + i18n + xlsx.

Anyone experienced this issue at all?

**Comment by SheetJSDev** [comment]
"Weird Characters" is coming from other libraries (codepage in specific, since Excel uses a pre-unicode scheme for encoding we have to ship a bunch of these tables).  You should be able to set the encoding type to get back reasonable results.

**Comment by ldsenow** [comment]
I meant the bundle output was weird. The file becomes ANSI encoding and all my translations are just unreadable. Not sure why webpack considers to use ANSI encoding for this output file only. All other files are UTF-8. The content is already polluted so regardless how i set the content-type or charset in html and just wont work. 

I have also asked the same question in webpack repo and see if anything comes back useful.

**Comment by SheetJSDev** [comment]
Let me clarify this: there are a few places where the weird characters are coming from:

- [js-codepage](https://github.com/SheetJS/js-codepage/blob/master/dist/cpexcel.full.js#L18), one of the dependencies of this project, pulls in a whole bunch of unicode characters. Here is an example line:

```js
D[129] = "����������������������������������������������������������������　、。，．・：；？！゛゜´｀¨＾￣＿ヽヾゝゞ〃仝々〆〇ー―‐／＼～∥｜…‥‘’“”（）〔〕［］｛｝〈〉《》「」『』【】＋－±×�÷＝≠＜＞≦≧∞∴♂♀°′″℃￥＄￠￡％＃＆＊＠§☆★○●◎◇◆□■△▲▽▼※〒→←↑↓〓�����������∈∋⊆⊇⊂⊃∪∩��������∧∨￢⇒⇔∀∃�����������∠⊥⌒∂∇≡≒≪≫√∽∝∵∫∬�������Å‰♯♭♪†‡¶����◯���".split("");
```

We end up shipping these mapping tables for XLS read support

- [ssf](https://github.com/SheetJS/ssf/blob/master/ssf.flow.js#L73) embeds some UTF-8 characters in a few places, including:

```js
	t[56]= '"上午/下午 "hh"時"mm"分"ss"秒 "';
```


The codepage tables would more than double in size if we tried passing unicode codepoints.  For example, the arabic percent sign U+066A is 6 bytes when escaped ("\\u066A".length == 6) but 2 bytes in UTF-8 (`0xD9 0xAA`).

If these are not properly being passed back, there's a possibility you aren't using UTF-8 encoding in your host.

**Comment by reviewher** [comment]
The fact that webpack closed issues like https://github.com/webpack/webpack/issues/1035 due to age suggests it's still an ongoing webpack issue.  If webpack is doing the right thing, please feel free to reopen the issue.
