### ISSUE TITLE
[newbie]Only getting one sheet and wrong name.

### ISSUE THREAD

**Issue by alucard87pl** [SheetJS/sheetjs#2043]
`people.xlsx` has four (`4`) sheets in it.

```javascript
var wb = XLSX.read("./people.xlsx")
console.log(wb.SheetNames.length)
console.log(wb.SheetNames.toString())
```
Result:
1
Sheet1

What am I doing wrong or not doing?

**Comment by SheetJSDev** [comment]
You probably meant to call `XLSX.readFile`.  `XLSX.read` interprets that as a plaintext file

**Comment by NareshShetty** [comment]
> `people.xlsx` has four (`4`) sheets in it.
> 
> ```js
> var wb = XLSX.read("./people.xlsx")
> console.log(wb.SheetNames.length)
> console.log(wb.SheetNames.toString())
> ```
> 
> Result:
> 1
> Sheet1
> 
> What am I doing wrong or not doing?

I am also facing same issue. How did you resolve? 
With `XLSX.readFile`  I am getting this error - _`fs.readFileSync is not a function`

**Comment by EliasPh** [comment]
I am also facing this issue with node.js

` xlsx.readFile("pathToFile)"` has this as a result:

`{"SheetNames":["Sheet1"],"Sheets":{"Sheet1":{"!ref":"A1"}}}`

How to i await the whole file?
