### ISSUE TITLE
Write XLSX directly into file system in electron not possible without save-as-prompt?

### ISSUE THREAD

**Issue by muehlensiepen** [SheetJS/sheetjs#2044]
Hi,

i tried using XLSX.write in combination with fs.writeFileSync -> didnt work the XLSX is corrupted after writing it.
I also tried using XLSX.writeFile because i read that it uses fs.writeFileSync. But then im using it like this:
const DATABASE_PATH ('assets/db/excelfile.xlsx');

XLSX.writeFile(workbook, DATABASE_PATH); 
it promped a "save as dialog" and converts filePath-slashes into "_" so it uses assets_db_excelfile.xlsx as a filename instead of a path for direct saving on the filesystem.

I don't need a "saveAs"-dialog because I got electron as environment and could save the file directly.
Any ideas? Didn't find anything after hours of searching.

regards

**Comment by muehlensiepen** [comment]
![grafik](https://user-images.githubusercontent.com/51904148/86473226-ce01c300-bd40-11ea-93b4-7b745457625c.png)

**Comment by srijonsaha** [comment]
Hi as far as `XLSX.writeFile` is concerned it doesn't open a 'Save As' dialog. It would be an Electron function opening the dialog. Are you calling `showSaveDialog` or similar Electron function in your code before you `XLSX.writeFile`?

For `XLSX.write` -> `fs.writeFileSync`, I'm able to do it in Electron using this:
```javascript
const data = XLSX.write(wb, {type: 'buffer'});
fs.writeFileSync(filePath, data);
```

**Comment by muehlensiepen** [comment]
Hi, I dont call a saveAsDialog at this context, but in another (shouldnt have impact here).

here is the Service function I use to read the xlsx, manipulate and rewrite it (I use buffer type for reading and writing), hope that will give you some more information:

`readonly DATABASE_PATH = 'database/materialDatabase.xlsx';`
`  updateMaterialList(materialInput, favouriteCheckState) {
    this.file = fs.readFileSync(this.DATABASE_PATH);
    let workbook = XLSX.read(this.file, { type: 'buffer' });
    const rowObject = XLSX.utils.sheet_to_json(workbook.Sheets.Tabelle1) as Material[];
    rowObject.forEach((element, i) => {

      const elementMaterialName = _.get(element, 'materialName');
      const materialInputMaterialName = _.get(materialInput, 'materialName');
      const elementWinType = _.get(element, 'winType');
      const materialInputWinType = _.get(materialInput, 'winType');

      if (elementMaterialName.toString() === materialInputMaterialName.toString() && elementWinType.toString() === materialInputWinType.toString()) {
        if (favouriteCheckState) {
          rowObject[i].favourite = 'J';
        } else {
          rowObject[i].favourite = 'N';
        }
      }
    });
    workbook.Sheets.Tabelle1 = XLSX.utils.json_to_sheet(rowObject);
    const data = XLSX.write(workbook, { type: 'buffer' });
    fs.writeFileSync(this.DATABASE_PATH, data);
  }`

if I check the xlsx-file after writing it back its corrupted.

Still if I use:
`XLSX.writeFile(workbook, this.DATABASE_PATH);`
instead of XLSX.write

a prompt shows up.

**Comment by SheetJSDev** [comment]
@muehlensiepen can you share the corrupted file?  That may be an issue unrelated to electron

**Comment by muehlensiepen** [comment]
[materialDatabase _corrupted.xlsx](https://github.com/SheetJS/sheetjs/files/4883606/materialDatabase._corrupted.xlsx)

sure. :)

**Comment by SheetJSDev** [comment]
That is certainly corrupted.  To be sure this is a binary corruption issue, can you try exporting with

```js
    const data = XLSX.write(workbook, { type: 'buffer', bookType: 'csv' });
    fs.writeFileSync(this.DATABASE_PATH + ".csv", data);
```

Then try `bookType: "xlml"` (and write with a .xml extension and open with Excel).

Both are plaintext formats so we'll get a better sense for the nature of the corruption

**Comment by muehlensiepen** [comment]
I exported it as csv and xml, both files are in this zip:
[materialDatabase.zip](https://github.com/SheetJS/sheetjs/files/4883901/materialDatabase.zip)
excel won't open the .xml file

**Comment by muehlensiepen** [comment]
Hi, any news? I havent made progress yet. :/

regards

**Comment by SheetJSDev** [comment]
Are you sure the XML is correct?  It looks like a bunch of numbers, as if an array was written instead of a true nodejs buffer

```
60,63,120,109,108,32,118,101,114,115,105,111,
```

**Comment by SheetJSDev** [comment]
This is most likely an issue with electron or how you are using it, please follow up with them first
