### ISSUE TITLE
Cannot find reason as to high memory consumption when comparing with oss.sheetjs.com

### ISSUE THREAD

**Issue by pnoyens** [SheetJS/sheetjs#2048]
Hi there!

I've successfully integrated this brilliant package in one of my web applications. For this I want to shout out a big thank you to all the developers! It has been of great use in one of my projects.

However, after playing a bit with multiple XLSX and CSV files, I've noticed a weird situation and cannot seem to get a grip on it. Let me explain; when loading in a 95MB XLSX file on the open demo (https://oss.sheetjs.com), memory consumption is steady and maxes out at about 1.3 GB, which is already a lot but after reading the online discussions on this topic _(again lots of credit to @SheetJSDev for explaining how XLSXs are effectively ZIP files containing multiple XML files that can - when decompressed - increase the size by a factor of 10+)_ I understand this is entirely normal and already heavily optimised. 

But... After all my attempts to keep the memory usage as low as possible with the exact same XLSX file and the exact same version of the xlsx package (0.16.3), reading the file quickly climbs to a whopping 20GB of memory usage.

Things I've tried already:

- Extract the package from my Webpack bundle (now gets loaded on-demand by web worker via importScripts, as is done in the sheetjsw.js web worker script in the oss.sheetjs.com page repo)
- Fetching the library from unpkg now, so no longer importing it via package.json (working with xlsx.full.min.js)
- Changed reading type from ArrayBuffer to Binary (readAsBinaryString)
- As mentioned I've put all processing by the xlsx package in a separate web worker thread
- Tried in several modern browsers

If anyone can help me find out the reason for this massive difference in memory consumption in my own solution vs. oss.sheetjs.com with no noticeable difference in source or usage, it would be highly appreciated!

**Comment by SheetJSDev** [comment]
That's certainly unexpected!  Just as a sanity check, can you clone try cloning that site (it's hosted on github pages https://github.com/SheetJS/SheetJS.github.io/ ) and seeing if you run into memory issues locally?

**Comment by pnoyens** [comment]
Just set up a local web server using that repo and getting the same results as using the online version. ..

**Comment by pnoyens** [comment]
I'm using the package inside a React project, I wonder if that adds some overhead to it and causes the memory to spike

**Comment by SheetJSDev** [comment]
There are many moving parts here.  It is hard to give general advice without a reproduction project, but it would help to know exactly which command is triggering the spike.  For example, is the transpiled worker script making a copy of the message before sending to the main thread?  If you can share a project or do some more digging, we can reopen the issue.
