### ISSUE TITLE
How to set a common data type for all cell without a loop

### ISSUE THREAD

**Issue by damchothinley** [SheetJS/sheetjs#2056]
Hello Admin,

Thank you for the great tool and examples. Today I want to ask a question about formatting a cell. 
So far the examples I have seen using a loop and formatting each cell. 
But I would to set it  either by selecting a range or with a sheet. Is there any method to do that? 
I would be very grateful and Thank you in advance.!

**Comment by SheetJSDev** [comment]
Assuming you are starting with a cell range string, like "B2:C4", you can use `decode_range` to recover the bounds:

```js
var range_string = "B2:C4";
var range = XLSX.utils.decode_range(range_string);

for(var R = range.s.r; R <= range.e.r; ++R) {
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var addr = XLSX.utils.encode_cell({r:R, c:C});
    var cell = ws[addr];
    if(!cell) continue;
    // do something with cell here
  }
}
```

At a low level, the loop concept is unavoidable.  We could add some helper functions, but this is simple and straightforward
