### ISSUE TITLE
ie11 xls 转xlsx问题

### ISSUE THREAD

**Issue by Beful** [SheetJS/sheetjs#2058]
```
var XLSX = require('xlsx');
var oldFile= XLSX.readFile('./test.xls');
XLSX.writeFile(oldFile, './test.xlsx');
```

利用js-xlsx包，可以在NodeJs环境中进行xls到xlsx的转换，非常简单，示例代码如下：
先安装依赖npm install xlsx

这个不好使，有没有什么方便的方法，ie11使用，或者有个小例子demo ！！

ie报错堆栈溢出，谷歌浏览器没事

**Comment by SheetJSDev** [comment]
阅读文档: https://github.com/SheetJS/sheetjs#parsing-workbooks

> `readFile` is only available in server environments. Browsers have no API for reading arbitrary files given a path, so another strategy must be used.

者有个小例子 :) https://github.com/SheetJS/sheetjs/tree/master/demos/oldie
