### ISSUE TITLE
json_to_sheet generates <c r="A2"><v>NaN<v></c> when json attribute is NaN

### ISSUE THREAD

**Issue by Ognian** [SheetJS/sheetjs#2059]
this leads to Excel having "a problem to open the file...."

I'm pasting the error xml (in german) here so that it is searchable...

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Reparaturergebnis speichern in 628d56aa-dd13-48e0-92b6-7102561477661.xml</logFileName><summary>Fehler in Datei '/Users/ogi/Downloads/628d56aa-dd13-48e0-92b6-710256147766.xlsx'</summary><repairedRecords summary="Die folgenden Reparaturen wurden durchgeführt:_x000d__x000a__x000d__x000a_"><repairedRecord>Reparierte Datensätze: Zellinformationen von /xl/worksheets/sheet1.xml-Part</repairedRecord></repairedRecords></recoveryLog>
```

xlsx 0.16.3
on nodejs 14.4.0

A workaround is to filter the null values.
BUT actually such entries should be prevented by the writer....

Thanks
Ognian

**Comment by SheetJSDev** [comment]
What was the original data?  The main way you'd end up with a NaN is if you manually fed a NaN value like `XLSX.utils.json_to_sheet([{a:1, b:NaN}])`

**Comment by Ognian** [comment]
Ok actually there are 2 different problems:
1. @SheetJSDev yes when you manually feed NaN (and yes I do that) you end up with NaN in the .xlsx. When this happens the .xlsx makes problems when it is open with excel. I'm not sure wich error value should be added instead (#NV?) but the way it is at the moment doesn't look correct to me

2. Adding intentional null values makes also a problem ( I'm quite sure that it leads to the same NaN when the original data is null)

I'm doing this because I'm exporting from a DB where NaN and null are legitime values. At the moment I'm replacing them to strings, but this is only a workaround... I need something more general so that importing the export would also work. I haven't tried yet, but I think that xlsx. error values could be the way to go.

**Comment by SheetJSDev** [comment]
Are you sure that adding intentional null values is eliciting the issue?  For example:

```js
var ws = XLSX.utils.json_to_sheet( [ { a: 1, b: null } ] );
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "null.xlsx", { sheetStubs: true });
```

The generated `null.xlsx` is a valid file.  Even a cursory read of https://github.com/SheetJS/sheetjs/blob/master/bits/90_utils.js#L205 should convince you that a null value is translated to a "stub cell" `{t:"z", v:null}` which is not serialized by default.


As for the `NaN` case, Excel does not have a natural representation of NaN (It doesn't support the full set of IEEE754 values).  `#NUM!` might be the best choice here, represented in SheetJS as `{ t: "e", v: 0x24 }`

**Comment by Ognian** [comment]
@SheetJSDev this took longer to properly sort it out, since indeed there where additional errors on my side.
This is what I found out so far:

- when we have a null value and we have shared strings (`bookSST: true` ) #NV as a shared string is generated:
`<si><t>#NV</t></si>`
- when `bookSST: false` a null value is ALSO a string `<c r="Q2" t="str"><v>#NV</v></c>`

my actual flow is:
```
        const flattened = preprocessed.map(e => flattenObject(e))
        const ws = XLSX.utils.json_to_sheet(flattened)
        const wb = XLSX.utils.book_new()
        XLSX.utils.book_append_sheet(wb, ws, 'export')

        if (!wb.Props) wb.Props = {}
        wb.Props.Title = `xxx`
        wb.Props.Subject = `xxx`
        wb.Props.Author = `xxx`
        wb.Props.CreatedDate = new Date()

        /* generate buffer */
        const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', bookSST: false })

```
preprocessed is the array of plain JSON Objects
flatten is basically:
```
    const flattenObject = (obj, prefix = '') =>
      Object.keys(obj).reduce((acc, k) => {
        const pre = prefix.length ? `${prefix}.` : ''
        if (obj[k] !== null && typeof obj[k] === 'object') Object.assign(acc, flattenObject(obj[k], pre + k))
        else acc[pre + k] = obj[k]
        return acc
      }, {})
```
and I'm posting the source of flattenObject since the check with typeof is tricky in the null case (and this was one of the errors on my side...)

So I see here 3 things to be solved:
1. I agree with you that #NUM! would be the best for NaN, and I think that this should happen in sheetsjs
2. json_to_sheet should get a new flatten option, where it performs the flattenObject function from above (provided something tested would greatly reduce error probability when using sheetjs)
3. we should find out why null is #NV! as string and not as you expect the #NV! error...

**Comment by SheetJSDev** [comment]
1. agreed

2. it's doable outside of the library, so I'm not sure if it's needed.

3. `#NV!` is not an Excel error in en-US -- do you know what the english form is?  Try creating a file with that error and saving as .xls, then we can inspect that file to see what the error actually is.

Just to be sure, are you *absolutely sure* that `null` is eliciting this error?  It looks like you're passing the string `"#NV!"`

**Comment by Ognian** [comment]
@SheetJSDev sorry, yes you are right! Indeed null is `{t:"z" v:null}` and it is NOT serialized. I was looking in the generated xml and overlooked that it is missing which is correct!

for the second point: I think that it would raise the "quick positive experience" with this lib, but it is up to you...

**Comment by reviewher** [comment]
The second part is better discussed in a separate issue

**Comment by Ognian** [comment]
@reviewher I saw that this issue is closed now, so the NaN issue should be fixed now,  but I couldn't find out where/how and in which version it is/will be fixed...
