### ISSUE TITLE
$ symbol not show in excel

### ISSUE THREAD

**Issue by chaxul** [SheetJS/sheetjs#2061]
Hello, 

I am trying to export table data to excel from angular. At the export excel I am not able to get $ symbol. But I am able to get all other currency symbol. if Anyone has idea can you help me on this. 

Thanks.

**Comment by SheetJSDev** [comment]
It's being matched as a number but the currency format is not currently deduced.

You can skip numeric parsing altogether by setting the option raw: false in `table_to_book` or `table_to_sheet`.

**Comment by chaxul** [comment]
Hello,

If possible can you share example how I can set raw: false in table_to_sheet.

Thanks.

**Comment by SheetJSDev** [comment]
It should be `raw: true`:

```js
var elt = document.getElementById('data-table'); // elt is a DOM element
var ws = XLSX.utils.table_to_sheet(elt, {raw: true}); // all values will be strings 
```

**Comment by chaxul** [comment]
Thank you for the help. this example works for me. Thank You so much.
