### ISSUE TITLE
Conversion of JS date value to number date is not precise on Chrome

### ISSUE THREAD

**Issue by blikblum** [SheetJS/sheetjs#2062]
Functions like `XLSX.utils.sheet_add_json` converts JS date values to excel number dates ([OLE Automation date](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tooadate?view=netcore-3.1)) using [datenum](https://github.com/SheetJS/sheetjs/blob/master/bits/20_jsutils.js#L35).

The conversion is not correct on Chrome. The converted value is a few seconds less than the passed date. On Firefox works correctly.

As an example look at this [pen](https://codepen.io/blikblum/pen/GRoYGVj?editors=1011).

It copies `datenum` implementation and try to convert 'Jun 05 2020 00:00:00', writing the result to console. On Firefox the returned value is correct (43987) just like [C# implementation](https://dotnetfiddle.net/KOrVve). But in Chrome or Chrome based like new Edge, returns 43986.9999537037.

The difference from Chrome to Firefox is `basedate.getTimezoneOffset()`. On Firefox returns an fractional number (in my case 154.06666666666666) while Chrome return an integer number (154).

Using [this implementation](https://stackoverflow.com/a/36187178/5724645) fixes it.

I'm willing to create a PR but could not find where to add tests for `datenum`. If some one guide me where to add such tests i can create a PR.

Important to test for cases like https://github.com/SheetJS/sheetjs/issues/1332

Probably https://github.com/SheetJS/sheetjs/issues/1890 is caused by this issue

**Comment by SheetJSDev** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=7863 known bug with Chromium.

Sadly year 1900 (which marks the zero point for dates in Excel) happens to be the only relevant year with issues.  You can test this in node by invoking with the `TZ` environment variable:

```
$ env TZ=Asia/Shanghai node
```

```js
(function (date) {
    var timezoneOffset = date.getTimezoneOffset() / (60 * 24);
    var msDateObj = (date.getTime() / 86400000) + (25569 - timezoneOffset);
    return msDateObj;
})(new Date(1900,1,1,0,0,0,0)) // 32.99950231481489
```

Maybe it's better to break 1900 than break today

**Comment by blikblum** [comment]
> Maybe it's better to break 1900 than break today

Did you already decided what to do?

I can help with the patch with deems necessary

**Comment by SheetJSDev** [comment]
Moving discussion to https://github.com/SheetJS/sheetjs/issues/1565
