### ISSUE TITLE
Change Page Layout Size?

### ISSUE THREAD

**Issue by Catacomba** [SheetJS/sheetjs#2064]
Is it possible to change the Page layout > Size property?
In excel you can change the layout size ( aka. paper size), but I cannot seem to find such an option in the library. 
![APB45RdjSK](https://user-images.githubusercontent.com/24373776/87941679-c742b200-ca9b-11ea-9158-fdb1d1b62201.png)

**Comment by SheetJSDev** [comment]
Not currently in our open source build, but we offer the full set of Print options in our [Pro offering](https://sheetjs.com/pro)
