### ISSUE TITLE
Sort sheets before exporting worbook

### ISSUE THREAD

**Issue by Marange** [SheetJS/sheetjs#2065]
Hello and first thanks for this amazing work!

My issue is simple, is there any way to sort the sheets of the workbook? I've looked elsewhere. 

My problem is because I'm creating a book with multiple sheets and a "Master sheeet". I run a loop to create all the sheets and after they are done, I take the info put it in the Master and add the Master to the book. I'm currently working with around 400 sheets in total. I've tried running a VBA macro on Excel, but I've not found any solution to sort my 400 sheets in a reasonable time.

I've looked into wb.sheets object in the console, but ironically they are alphabetically sorted there. I'm currently working in a function to try sort wb.sheets. I'm asking here because I don't want to reinvent the wheel.

Any help will be really appreciated!

**Comment by SheetJSDev** [comment]
The worksheet order is determined by the `wb.SheetNames` array.

Your best bet is to create the workbook, create a stub master sheet and add it to the workbook (so it appears first), then in your loop use [`XLSX.utils.sheet_add_aoa`](https://docs.sheetjs.com/#array-of-arrays-input) to append data to the master ws.  For example:

```js
/* create workbook */
var wb = XLSX.utils.book_new();

/* add master sheet */
var master_ws = XLSX.utils.aoa_to_sheet([["a","b"]]);
XLSX.utils.book_append_sheet(wb, master_ws, "Master Sheet");

/* in your loop ... */
["test1", "test2", "test3"].forEach((name, idx) => {
  /* create worksheet, add to workbook */
  var ws = XLSX.utils.aoa_to_sheet([[name]]);
  XLSX.utils.book_append_sheet(wb, ws, name);

  /* append to master sheet */
  XLSX.utils.sheet_add_aoa(master_ws, [[name, idx]], { origin: -1 });
});

/* write file */
XLSX.writeFile(wb, "test.xlsx");
```

**Comment by Marange** [comment]
Thanks a lot. Exactly what I needed!
