### ISSUE TITLE
Dealing with empty fields in rows.

### ISSUE THREAD

**Issue by ypcaptain96** [SheetJS/sheetjs#2067]
When using Sheet_to_json, i want to find the number of rows which have even a single empty field within them.
For eg, out of the 5 rows, if i have empty field in row 3 and 4, then i can find the total count of rows with empty fields within them.
[Book2.xlsx](https://github.com/SheetJS/sheetjs/files/4952045/Book2.xlsx)

For the attached file, it shows that 2 rows have empty fields within them.

**Comment by SheetJSDev** [comment]
Using NodeJS to read the data:

```js
var XLSX = require("xlsx");
var wb = XLSX.readFile("Book2.xlsx");
var ws = wb.Sheets.Sheet1;
var aoa = XLSX.utils.sheet_to_json(ws, {header:1})
var cnt = aoa.slice(1).reduce((acc, row) => acc + +!!aoa[0].some((val, idx) => !row.hasOwnProperty(idx)), 0)
```

**Comment by ypcaptain96** [comment]
When i try to integrate this with my function, it gives me an error that "**Operator '+' cannot be applied to types 'unknown' and 'number'** "

My code for reference: 
  addFile(event) {
    this.file = event.target.files[0];
    const fileReader = new FileReader();
    fileReader.readAsArrayBuffer(this.file);
    fileReader.onload = (e) => {
      this.arrayBuffer = fileReader.result;
      const data = new Uint8Array(this.arrayBuffer);
      const arr = new Array();
      for (let i = 0; i !== data.length; ++i) { arr[i] = String.fromCharCode(data[i]); }
      const bstr = arr.join('');
      const workbook = XLSX.read(bstr, { type: 'binary' });
      const firstSheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[firstSheetName];
      console.log(XLSX.utils.sheet_to_json(worksheet, { raw: true, defval: '', blankrows: false }));
      const aoa = XLSX.utils.sheet_to_json(worksheet, { raw: true, defval: '', blankrows: false });
      const cnt = aoa.slice(1).reduce((acc, row) => acc + +!!aoa[0].some((val, idx) => !row.hasOwnProperty(idx)), 0);
      this.fileList = [];
      console.log(this.file);
      console.log(cnt);
      console.log(this.fileList);
    };
  }
