### ISSUE TITLE
Java Demo Issue

### ISSUE THREAD

**Issue by LightDvlpr** [SheetJS/sheetjs#2071]
when running make rhinojs fails due to a missing cp command

```
cp rhino/buildGradle/libs/rhino*.jar rhino.jar
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
make: *** [rhino.jar] Error 64
```

Issue was resolved by manually copying one of the jars

`cp rhino/buildGradle/libs/rhino-1.7.13-SNAPSHOT.jar rhino.jar`

**Comment by SheetJSDev** [comment]
Running the test locally, I see three `jar` files generated in the build process.

It probably would suffice to change that line (https://github.com/SheetJS/sheetjs/blob/master/demos/altjs/Makefile#L57) to

```bash
cp rhino/buildGradle/libs/rhino-1*.jar rhino.jar
```
