### ISSUE TITLE
Open local server file in Angular 

### ISSUE THREAD

**Issue by jonatmoy** [SheetJS/sheetjs#2074]
hello i want to open a file present on my angular server but all example import files directly, i can't find any way to directly read my file, do you have a solution?

Thank you in advance.

![image](https://user-images.githubusercontent.com/34139071/88677041-1bc5dd00-d0ed-11ea-9911-b81beb9fbbc9.png)

**Comment by jonatmoy** [comment]
```var url = "https://oss.sheetjs.com/test_files/formula_stress_test.xlsx";
        var req = new XMLHttpRequest();
        req.open("GET", url, true);
        req.responseType = "arraybuffer";


        req.onload = (e: any) => {
            /* read workbook */
            var data = new Uint8Array(req.response);
            var wb = XLSX.read(data, { type: "array" });```

**Comment by SheetJSDev** [comment]
You can also use `fetch`.  There's also probably a way to get angular to bundle the binary asset (similar to webpack's file-loader or url-loader)

**Comment by gotexis** [comment]
@SheetJSDev I too believe that would be possible but have been failing to do that...

Wonder if anyone have an example
