### ISSUE TITLE
Unknown Namespace: 

### ISSUE THREAD

**Issue by Beful** [SheetJS/sheetjs#2075]
Uncaught Error: Unknown Namespace: 
    at Xlsx.js:21598
    at of (Xlsx.js:21600)
    at hf (Xlsx.js:21973)
    at Object.pf [as read] (Xlsx.js:22087)
    at XMLHttpRequest.r.onload (Xlsx.js:1828)

![image](https://user-images.githubusercontent.com/56426292/89098244-4b8c2200-d418-11ea-8622-8f02ff667498.png)
![image](https://user-images.githubusercontent.com/56426292/89098246-52b33000-d418-11ea-91bf-cc0cb70ed9b8.png)

**Comment by SheetJSDev** [comment]
Can you share a sample file?  The check is https://github.com/SheetJS/sheetjs/blob/master/bits/30_ctype.js#L220 which may not even be necessary if Excel doesn't require the namespace for `[Content_Types].xml`

**Comment by Beful** [comment]
```javascript
var nContainer = document.getElementById('container')
var xlsx = new Plus.Xlsx(nContainer)
xlsx.readFile("/200.xlsx");
```

**Comment by SheetJSDev** [comment]
Can you share that 200.xlsx file?

**Comment by Beful** [comment]
可以

**Comment by Beful** [comment]
![image](https://user-images.githubusercontent.com/56426292/89137525-f3196980-d56a-11ea-894e-815e01451433.png)

又报这个错

**Comment by Beful** [comment]
[建筑.xlsx](https://github.com/SheetJS/sheetjs/files/5013397/default.xlsx)

**Comment by SheetJSDev** [comment]
谢谢!

Feel free to submit a patch.  The change is in `bits/22_xmlutils.js`:

```diff
--- a/bits/22_xmlutils.js
+++ b/bits/22_xmlutils.js
@@ -1,6 +1,6 @@
 var XML_HEADER = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n';
 var attregexg=/([^"\s?>\/]+)\s*=\s*((?:")([^"]*)(?:")|(?:')([^']*)(?:')|([^'">\s]+))/g;
-var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s?[\/\?]?>/g;
+var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s*[\/\?]?>/mg;
 
 if(!(XML_HEADER.match(tagregex))) tagregex = /<[^>]*>/g;
 var nsregex=/<\w*:/, nsregex2 = /<(\/?)\w+:/;
```

This is a problem with how we are parsing XML tags.  There is a CRLF newline sequence within the root tag, just before the closing `>`:

```
00000000: 3c3f 786d 6c20 7665 7273 696f 6e3d 2231  <?xml version="1
00000010: 2e30 2220 656e 636f 6469 6e67 3d22 5554  .0" encoding="UT
00000020: 462d 3822 2073 7461 6e64 616c 6f6e 653d  F-8" standalone=
00000030: 2279 6573 223f 3e0d 3c54 7970 6573 2078  "yes"?>.<Types x
00000040: 6d6c 6e73 3d22 6874 7470 3a2f 2f73 6368  mlns="http://sch
00000050: 656d 6173 2e6f 7065 6e78 6d6c 666f 726d  emas.openxmlform
00000060: 6174 732e 6f72 672f 7061 636b 6167 652f  ats.org/package/
00000070: 3230 3036 2f63 6f6e 7465 6e74 2d74 7970  2006/content-typ
00000080: 6573 2220 0d0a 3e0d 3c44 6566 6175 6c74  es" ..>.<Default
                    ::::
```

The proposed fix changes the RegExp to use the `/m` flag and changes the penultimate check to match any number of whitespace characters.

**Comment by Beful** [comment]
![image](https://user-images.githubusercontent.com/56426292/89141407-25c95f00-d577-11ea-9c06-d7ac0366c2c7.png)

I，m read 虚拟目录 ，请求链接，是不是不支持

**Comment by keithpan** [comment]
@SheetJSDev  
![image](https://user-images.githubusercontent.com/49436849/102171759-3a791480-3ed2-11eb-8cd6-5b5b69319ada.png)
this commit is different from the above reply and the latest version is invalid, can you help me?

**Comment by SheetJSDev** [comment]
@keithpan does it work if you change the modifier near the end as follows:

```diff
-var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s?[\/\?]?>/mg;
+var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s*[\/\?]?>/mg;
                                                                                                ^
```

The caret is marking the modifier that changed.  originally it matches up to one whitespace character and the change lets it match any number

**Comment by keithpan** [comment]
> @keithpan does it work if you change the modifier near the end as follows:
> 
> ```diff
> -var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s?[\/\?]?>/mg;
> +var tagregex=/<[\/\?]?[a-zA-Z0-9:_-]+(?:\s+[^"\s?>\/]+\s*=\s*(?:"[^"]*"|'[^']*'|[^'">\s=]+))*\s*[\/\?]?>/mg;
>                                                                                                 ^
> ```
> 
> The caret is marking the modifier that changed. originally it matches up to one whitespace character and the change lets it match any number

@SheetJSDev 
why does the latest version not have this change?

**Comment by ansarikhurshid786** [comment]
I am facing same issue when i publish web server. it is working on local server.
