### ISSUE TITLE
nested objects in json_to_sheet

### ISSUE THREAD

**Issue by reviewher** [SheetJS/sheetjs#2076]
Currently nested objects are not handled in `json_to_sheet`.  Example:

```js
var data = [
  {
    abc: {
      def: 1,
      ghi: {
        jkl: 2,
        mno: 3
      }
    }
  }
];
var ws = XLSX.utils.json_to_sheet(data, {header: []});
```

Questions:

- How should the keys be ordered?
- What headers should be written to the worksheet?
- How is the array form of the `header` parameter parsed and interpreted?

ping @Ognian this is a continuation of a part of #2059

**Comment by Ognian** [comment]
In my case data could be even more complex. Not only nested objects but also arrays of nested objects etc...
```
var data = [
  {
    abc: {
      def: 1,
      ghi: [
       {
        jkl: 2,
        mno: 3
      },
      {
        jkl: 4,
        per: 5
      }]
    }
  }
];
```
The only way to represent this into a tables row is by flattening the json document
The answers of your questions from what I found out until now are:

ad ordering: providing an external array of key's, like it is now is still needed, BUT this must be extended for the case where the flatten object contains arrays:
i.e. for the above data the flatten representation is:
`abc.def abc.ghi.0.jkl abc.ghi.0.mno abc.ghi.1.jkl abc.ghi.1.per`
the array we should / could provide for ordering naming the columns is
`[abc.def, abc.ghi.0.jkl, abc.ghi.0.mno, abc.ghi.0.per ]`
the important point is that with array's we can only provide a "prototype" for all the columns associated with array index 0 but the actual serialiser has to apply this order for all rows in the flatten array...

ad what headers: at the moment I'm exporting with 2 rows of headers the first is a "human title", the second is the dotted path of the flatten object

ad parsing: At the moment there are the following restrictions:
- a dot is only used for separating object keys, therefore json documents are not allowed to have attributes (key's) with a dot
(if this gets a problem we shall handle it the same way like it can be handled in mongodb, where $ and . is not allowed in attributes... (https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name))
- attributes containing only numbers 0-9 are array Indizes  

hope this shows some of the hard edge cases...

**Comment by SheetJSDev** [comment]
It's probably better to encourage people to use a dedicated library like [`flat`](https://www.npmjs.com/package/flat) to flatten objects rather than integrate the logic into `json_to_sheet`

**Comment by aryanbhatt-0501** [comment]
after using flat do we need to format again ? because I am getting just two rows of data on the excel which is not what it should look like.
