### ISSUE TITLE
Null worksheet when creating an empty worksheet with header using json_to_sheet

### ISSUE THREAD

**Issue by sporsherbaire** [SheetJS/sheetjs#2077]
Since version 0.16.5, th following code returns a null worksheet:
`XLSX.utils.json_to_sheet([], {header: columns})`

Is it now working as it is wanted? If so, how could we create an empty worksheet? In my case it is expected that sometimes the data is an empty array. And an empty worksheet only with headers is expected.

**Comment by SheetJSDev** [comment]
`XLSX.utils.aoa_to_sheet([columns])` should be the preferred approach in general.

That said, https://github.com/SheetJS/sheetjs/blob/master/bits/90_utils.js#L182 is the offending line and can be removed -- there was no intention to change the behavior in this case

**Comment by SheetJSDev** [comment]
closed by 2c5a863420edcd821016c0ab607b0dcc0023d9f2
