### ISSUE TITLE
Export XLSX and format cells

### ISSUE THREAD

**Issue by likemike90** [SheetJS/sheetjs#2079]
Hello Guys ,

i have a problem with exporting an HTML Table to xlsx . When i convert it, and all is working my time in Column H1, is shown as 715 instead of 0715 . is there an Solution for this ?

my code so far is - > 
        <script lang="javascript" src="js/xlsx.full.min.js"></script>
        <script lang="javascript" src="js/FileSaver.js"></script>

`                var wb = XLSX.utils.table_to_book(document.getElementById('covid19'), {sheet:"ESA1450"});
                var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});

                function s2ab(s) {
        
                                var buf = new ArrayBuffer(s.length);
                                var view = new Uint8Array(buf);
                                for (var i=0; i<s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                                return buf;
                }

         

                $("#button-a").click(function(){
                saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), '<?php echo $xlsxfile; ?>');
                });`

Thanks for your Support !

**Comment by SheetJSDev** [comment]
The value parser thinks you intended to put the number 715.  You can pass the option `raw: true` to recover the raw text "0715".
