### ISSUE TITLE
CSV export breaks on carriage-return (\r)

### ISSUE THREAD

**Issue by paul4156** [SheetJS/sheetjs#2080]
Carriage-return is not wrapped with double quotes in CSV export.

* xlsx version: 0.16.5
* node version: 12.13.0
* macOS: 10.15.6

Testing code:
```js
const data = [{
    column1: 'value1\r',
    column2: 'value2'}];

const XLSX = require('xlsx');
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(data));
XLSX.writeFile(wb, 'test.csv', { bookType: 'csv' });
```

Result (`test.csv`):
```csv
column1,column2
value1
,value2
```

Expected behaviour:
```csv
column1,column2
"value1
",value2
```

**Comment by SheetJSDev** [comment]
SheetJS is consistent with Excel here.  To create a `\r` in excel, you can use `CHAR(7)` (codepages 1252 and 10000 both use the ASCII block so there's no weird cross-platform issue).

 Make a new workbook and set:

- A1: type `column1` and hit enter
- B1: type `column2` and hit enter
- A2: set to `="value1"&CHAR(7)`
- B2: type `value2` and hit enter

Now if you save this worksheet as UTF-8 CSV, you'll see the following results.  Outputs are piped to `xxd` so you can see the raw bytes.

Excel 2019 for Windows:

```
00000000: efbb bf63 6f6c 756d 6e31 2c63 6f6c 756d  ...column1,colum
00000010: 6e32 0d0a 7661 6c75 6531 072c 7661 6c75  n2..value1.,valu
00000020: 6532 0d0a                                e2..
```

Excel 2019 for Mac:

```
00000000: efbb bf63 6f6c 756d 6e31 2c63 6f6c 756d  ...column1,colum
00000010: 6e32 0d0a 7661 6c75 6531 072c 7661 6c75  n2..value1.,valu
00000020: 6532                                     e2
```

Neither flavor of Excel adds double quotes.

Note that SheetJS will wrap fields if your record separator includes `\r`.  For example:

```js
var ws = XLSX.utils.json_to_sheet(data);
XLSX.utils.sheet_to_csv(ws, {RS:"\n"});   // 'column1,column2\nvalue1\r,value2\n'
XLSX.utils.sheet_to_csv(ws, {RS:"\r\n"}); // 'column1,column2\r\n"value1\r",value2\r\n'
```
