### ISSUE TITLE
IF and ISNUMBER in formula

### ISSUE THREAD

**Issue by Joserbala** [SheetJS/sheetjs#2084]
Hi!

I'm trying to use formulas in my project with SheetJS and I'm running into problems. Next, you can find the formulas I am trying to apply:
`f: "IF(" + mColumnCell + ">0;" + sColumnCell + "/" + mColumnCell + ";\"-\")"`
and
`"IF(AND(ISNUMBER(" + nColumnCell + ");ISNUMBER(" + tColumnCell + ");" + nColumnCell + ">0;" + tColumnCell + ">0);" + nColumnCell + "*" + tColumnCell + ";\"-\")"`

xColumnCell are cells in string format obtained from `XLSX.utils.encode_cell()`, for example:
`nColumnCell = XLSX.utils.encode_cell({ c: 13 /* N Column */, r: currentRow - 1 })` (currentRow is a number and it is the row where the cell with formula will be written).

`IF`, `AND` and `ISNUMBER` will cause an exception when opening the XLSX file and the formula won't appear in the desired cell, but `SUM` is not giving me problems. Am I missing something?

**Comment by SheetJSDev** [comment]
The file formats expect the `en_US` form for the formula expressions.  In particular, you have to use commas to separate function arguments.  Try

```js
f: "IF(" + mColumnCell + ">0," + sColumnCell + "/" + mColumnCell + ",\"-\")"
```

**Comment by Joserbala** [comment]
Wow, that was quick and easy! Thank you so much! I was going to get crazy over this.

**Comment by SheetJSDev** [comment]
It gets even crazier: Excel formula names are also localized (but stored as `en_US` in the file)!  For example, French excel uses `SOMME` instead of `SUM`

**Comment by Joserbala** [comment]
I use the Spanish version of Excel and in Spanish `SUM` is `SUMA`, `AND` is `Y`, `ISNUMBER` is `ISNUMERO` or `IF` is `SI`. I managed to get to know that I had to translate the names of the operations to English but I would never have thought that I would have to change a `;` for a `,`. I wish formulas were standardized across the different languages.
