### ISSUE TITLE
Please^ help! Set new value in cell and re init document with xlsx formila 

### ISSUE THREAD

**Issue by ddivitay** [SheetJS/sheetjs#2086]
Hello. NICE WORK!!!! Thanks!

var worksheet = workbook.Sheets[first_sheet_name];
worksheet.A1 = { v: 1000 }

HOW re init all formulas after set new value?

const wbout = XLSX.write(workbook, { type:'buffer' });

const workbook2 = XLSX.read(wbout);

worksheet.A1 === 1000 but xlsx formulas not compile new values ((((

**Comment by SheetJSDev** [comment]
If you make the change, then Excel will recalculate on open.  If you want to recalculate in JS, our [Pro offering](https://sheetjs.com/pro) has a component for updating the actual values (it's a implementation of a formula calculator similar to how Excel processes formulae)
