### ISSUE TITLE
How to start parsing excel sheet from specific row number?

### ISSUE THREAD

**Issue by raahul1912** [SheetJS/sheetjs#2090]
![image](https://user-images.githubusercontent.com/14999097/91072964-ecf14700-e657-11ea-817f-9af1e588383c.png)

I want to start reading from row number 20. But I don't find any property to do that from parsing excel.

Looking for solution :)

**Comment by MohatmaIslam2018** [comment]
I have the same issue :(

**Comment by 1025431504** [comment]
> 我想从第20行开始阅读。但是我没有任何属性可以通过解析excel来做到这一点。
![image](https://user-images.githubusercontent.com/48747641/93752638-89940e00-fc31-11ea-8ebc-9c00b450ae02.png)
range:19

**Comment by 1025431504** [comment]
![image](https://user-images.githubusercontent.com/48747641/93752726-a4ff1900-fc31-11ea-8649-ce8813ee7c9d.png)
## range:19 可以设置

**Comment by raahul1912** [comment]
@1025431504 let me try with this :)

**Comment by reviewher** [comment]
Expanding on @1025431504 's answer, you can either pass the starting row index or reshape the range with:

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
range.s.r = 19; // "row 20" in excel
var new_range = XLSX.utils.encode_range(range);
```
