### ISSUE TITLE
How to append rows from multiple files to the same sheet?

### ISSUE THREAD

**Issue by mcv** [SheetJS/sheetjs#2092]
I want to get all rows (except the first two (header) rows) from one sheet and append them to another sheet. Preferably, I'd like to preserve all Excel-specific information. It's easy to do by first converting to JSON, but then I lose a lot of information (like cell color, column width).

I can't figure out from the docs how to do this. I get the feeling I can either have an entire sheet, or have individual cells, but not an entire row of cells.

Is this possible?

(For my use case, I actually need to merge 8 Excel files this way, and if they have multiple sheets, merge all sheets like this. But I think I figured this out up to the sheet level. It's looking at rows where I get lost.)

**Comment by SheetJSDev** [comment]
Styles-related features are part of our [Pro builds](https://sheetjs.com/pro), but to answer the question you can copy over the cell objects directly from one worksheet object to another, ensuring you update the worksheet range to include all of the cells you want to keep.
