### ISSUE TITLE
Using SheetJS locally - with react (running live server)

### ISSUE THREAD

**Issue by wallythewebdev** [SheetJS/sheetjs#2093]
Hi there - 

I've spent a large amount of time looking for an answer and have decided to ask for some help as everything i have found has left me with more questions or contradictions.... 

I am trying to parse a .xlsx file to JSON, so it can be used in react as data (props) for components. 

However, I am failing to pare this due to the error: 

`TypeError: _fs.readFileSync is not a function`

The current code I am running that receives this is: 

```
import React, { Component } from 'react';
import './App.css';

console.log('working HERE')

let XLSX = require('xlsx');
var workbook = XLSX.readFile('/company_data.xlsx');

console.log(workbook.SheetNames[0])
```

The company_data.xlsx file is located in the src folder for React

---- 

I have heard that this is because the file is not being served on a server, but I am running react in a local server? so this shouldn't make much difference unless I'm missing something. 

Im wondering how to test or develop locally using sheetJS? 

I did try to follow the docs for react, however I really couldn't follow along with them and I have found very limited resources on how to implement sheetJS online. 

Im sorry if I have made some foolish mistake, 
I could really use some help on how to make this work. 

Please ask me any questions you might have on this topic - 

Thanks in advance, 
Wally

**Comment by SheetJSDev** [comment]
The unambiguous answer is in https://github.com/SheetJS/sheetjs#parsing-workbooks .  If you click "nodejs read a file", it says:

> `readFile` is only available in server environments. Browsers have no API for reading arbitrary files given a path, so another strategy must be used.

Actually getting the file is beyond the scope of this issue, but there are a few ways to do it.  The most common approach is to put your file in a folder with other static assets and perform a `fetch` to get the data (as an arrayBuffer).  This approach is discussed in more detail [in the `xhr` demo](https://github.com/SheetJS/sheetjs/blob/master/demos/xhr/)

**Comment by wallythewebdev** [comment]
Awesome - thank you for the help. 

Oddly I was under the impression that running localhost was running a server locally? (this is in the case of npm run start with react). 

thanks again
