### ISSUE TITLE
Improve Readme and have code examples

### ISSUE THREAD

**Issue by anthonybudd** [SheetJS/sheetjs#2094]
This library is practically unusable because I don't know where to start. The Readme is clogged full of useless information that means nothing to 99% of users and there is no copy and paste-able code snippets. I shouldn't have to read all the docs and stuff to get started.

To make this worse, when I try out the live demos I can't easily access the code? I have to either use the inspector or dig through the repo to find the demo code. For example https://sheetjs.com/demo/table.html Why isn't there a giant button linking to the source code on this page. Like why even have live demos for a JS library if you're not going to reference or display the source code?

After about 5min I just gave up, wrote this, and started looking for another library that's easier to get started with. I'm a professional web dev of 8 years, I'm not some Jr. dev fresh off a 2-week coding corse. See for a good readme: https://github.com/Ideea-inc/vipfs
https://github.com/Ideea-inc/teleport-js

**Comment by anthonybudd** [comment]
The fact that issue #817 exists proves my point....

**Comment by SheetJSDev** [comment]
PRs welcome :)

The documentation is intended to describe the hard details (API, mapping from spreadsheet concepts to SheetJS data structures), while the [demos](https://github.com/SheetJS/sheetjs/blob/master/demos) try to provide smaller examples of both usage and integration.  For example, [the Chrome / Chromium demo](https://github.com/SheetJS/sheetjs/tree/master/demos/chrome) shows the details of setting up a simple extension as well as how to invoke library functions from the relevant contexts.

If there's some specific problem you're trying to solve, raise an issue and we can discuss how to improve the documentation.

**Comment by anthonybudd** [comment]
You're just being lazy and you don't want to do any work. It's far easier for you to close this than actually fix the issue.

Your response doesn't even address my points (did you even read what I wrote?). Who cares about the "hard details", they are way too high-level to go into the Readme, most users just want to know what the npm install command is and a simple code snippet. I'm not saying you can't have both..

The chrome example you provided is also stupid. My whole issue here is no easily copy and paste-able code blocks. There is 5 code-blocks on that page, none can be copied in their entirety.

It's your repo, manage it however you want but its clear that other people are having this issue (#871, 3 years ago) and it will just put people off what looks like a good package, you've just gone out of your way to make it difficult to use IMO.

**Comment by SheetJSDev** [comment]
The tone here is wholly inappropriate for an open source project.  No one gets paid to work on the open source project, it is Apache 2.0 licensed which means we don't have a backdoor to force people to pay.  As far as we're concerned, it's a charitable effort.  If you're willing to put in the time to improve docs, or willing to pay for that to happen, great; otherwise, the complaint smacks of entitlement, the same type of entitlement that drove countless people to leave the open source community or relicense projects as proprietary.
