### ISSUE TITLE
How to set a values for autoFIlter cell? 

### ISSUE THREAD

**Issue by SpawnAtis** [SheetJS/sheetjs#2097]
Hi. Is there a way to change values for auto-filters and then apply it programmatically ?
<img width="535" alt="Screen Shot 2020-09-04 at 06 12 05" src="https://user-images.githubusercontent.com/23311140/92195475-b8f6fc80-ee75-11ea-9c52-df2bbad76d25.png">

F.e. pick "All" and apply auto-filter.  Thx

**Comment by reviewher** [comment]
closing in favor of #623 please follow up there
