### ISSUE TITLE
Generating sheets with checkbox

### ISSUE THREAD

**Issue by domoszlai** [SheetJS/sheetjs#2100]
I see that it is possible to read a value of a sheet which contains a checkbox. However, I would like to generate
a shhet that contains a checkbox. Could you please advice me how to do that?

**Comment by domoszlai** [comment]
Never mind, I see that it is shaky ground, I'll do it differently

**Comment by SheetJSDev** [comment]
To be clear, actual form checkboxes are available in our [Pro offering](https://sheetjs.com/pro)
