### ISSUE TITLE
upload to Server 

### ISSUE THREAD

**Issue by likemike90** [SheetJS/sheetjs#2101]
Hey Guys , 

sorry for maybe a stupid question but im searching for a solution wich i cant get solved . I dont know much about JS but im currently using sheetjs to convert an HTML Table to an xlsx File . By Clicking a Button i dowload it, but i want to upload the File to our Webserver ( next step would be to attached it to a mail -phpmail ) . 

How can i save the file to my webserver (/upload) ? 

thats my code : 

```

  <script>
        var wb = XLSX.utils.table_to_book(document.getElementById('covid19'), {sheet:"COVID19"});
        var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});
       


        function s2ab(s) {

                        var buf = new ArrayBuffer(s.length);
                        var view = new Uint8Array(buf);
                        for (var i=0; i<s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                        return buf;
        }
        $("#button-a").click(function(){
       
        saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), '<?php echo $xlsxfile; ?>');
        });

</script>

```

 

Thanks for your kindness to help

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/blob/master/demos/xhr/README.md#xmlhttprequest see the second codeblock.  You create a `FormData` object, add the generated file, then make a POST request to your PHP endpoint.  on the PHP side, the superglobal `$_FILES` array will have the file entries.

**Comment by likemike90** [comment]
Sorry i dont get it - i tried this 

`
// Form to send the xlsx to server 
<form method="POST" action="test.php" id="myForm"> <input type="submit" value="TEST"> TEST </input> </form>

//get the form 
var myForm = document.getElementById('myForm');

// write the FIle 
var wb = XLSX.utils.table_to_book(document.getElementById('covid19'), {sheet:"COVID19"});
var data = XLSX.write(wb, {bookType: 'xlsx', type: 'array'});

//append formdata to myForm
/* build FormData with the generated file */
var fd = new FormData(myForm );
fd.append('form', new File([data], 'sheetjs.xlsx'));

//dont know if the next lines are correct 
/* send data */
var req = new XMLHttpRequest();
req.open("POST", "/upload", true);
req.send(fd);`

but i dont get any result on test.php if ill echo my superglobal file variabel
