### ISSUE TITLE
XHR blob response cannot retrieve vba

### ISSUE THREAD

**Issue by grahamroy** [SheetJS/sheetjs#2102]
I have an excel sheet being returned as a blob for which I am using the demo at https://github.com/SheetJS/sheetjs/tree/master/demos/xhr#fetch

It gets the sheet and data back ok but the vba is missing. I am using angular and my code is:

```
    this.dataService.getTemplateFile().subscribe(async data => {

      const u8 = new Uint8Array(await data.arrayBuffer());
      const wbold: xlsx.WorkBook = xlsx.read(u8, {type: 'array', bookVBA: true });

      xlsx.writeFile(wbold, 'report.xlsx');
    });
```

**Comment by SheetJSDev** [comment]
VBA is not supported in the XLSX file format.  You need to write as XLSM and set `bookVBA: true`:

```js
      xlsx.writeFile(wbold, 'report.xlsm', {bookVBA: true});
```
