### ISSUE TITLE
creating xlsx files from xlsx sheets

### ISSUE THREAD

**Issue by yogigachinmath** [SheetJS/sheetjs#2105]
Hi,

I have xlsx file with multiple sheets, I want to create a another xlsx file with only one selected sheet with formatting,
Is there any way to do it?

**Comment by SheetJSDev** [comment]
Depends on what you are trying to do.  Styling is part of our [Pro offering](https://sheetjs.com/pro) but to merely combine sheets you can either copy objects over or just parse and add:

```js
var src = wb.Sheets["Sheet2"]; // copy from here
var dst = wb.Sheets["Sheet1"]; // copy to here
XLSX.utils.sheet_add_aoa(dst, XLSX.utils.aoa_to_sheet(src), {origin: -1}); // append data 
```
