### ISSUE TITLE
sheet_to_json not working

### ISSUE THREAD

**Issue by EthanDavis** [SheetJS/sheetjs#2106]
Hello I'm trying to convert a sheet to a json object and have ran into an issue where it just returning an empty array each time.

My sheet looks like this: 
```
{
  A1: { t: 's', v: '{"A2":{"t":"n"' },
  B1: { t: 's', v: '"v":187}' },
  C1: { t: 's', v: 'B2":{"t":"s' },
  D1: { t: 's', v: '"v":"rated"}' },
  E1: { t: 's', v: 'C2":{"t":"n' },
  F1: { t: 's', v: '"v":60}' },
  G1: { t: 's', v: 'D2":{"t":"s' },
  H1: { t: 's', v: '"v":"F"}' },
  I1: { t: 's', v: 'A3":{"t":"n' },
  J1: { t: 's', v: '"v":189}' },
  K1: { t: 's', v: 'B3":{"t":"s' },
  L1: { t: 's', v: '"v":"rated"}' },
  M1: { t: 's', v: 'C3":{"t":"n' },
  N1: { t: 's', v: '"v":90}' },
  O1: { t: 's', v: 'D3":{"t":"s' },
  P1: { t: 's', v: '"v":"M"}' },
  Q1: { t: 's', v: 'A1":{"t":"s' },
  R1: { t: 's', v: '"v":"lineId"}' },
  S1: { t: 's', v: 'B1":{"t":"s' },
  T1: { t: 's', v: '"v":"CogsRating"}' },
  U1: { t: 's', v: 'C1":{"t":"s' },
  V1: { t: 's', v: '"v":"rm"}' },
  W1: { t: 's', v: 'D1":{"t":"s' },
  X1: { t: 's', v: '"v":"gender"}' },
  Y1: { t: 's', v: '"!ref":"A1:D3"}' },
  '!ref': 'A1:Y1'
}
```

and I'm calling the sheet_to_json function like so: 
`XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]]);`

From what I can tell everything looks right but for some reason it's only returning an empty array. Any and all help is greatly appreciated!

**Comment by SheetJSDev** [comment]
The worksheet has 1 row, which is why you won't see any data (that row is interpreted as the header row).

To get back data, you can pass `header: 1` option https://docs.sheetjs.com/#json .

However, given your worksheet, it looks like you had a JSON string of a SheetJS worksheet and tried to read it (the library interpreted it as a CSV).  Check your code.  If I had to guess, you have a line like

```js
    var wb = XLSX.read(json_string);
```

Instead you want to parse that string:

```js
    var ws = JSON.parse(json_string);
    var wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
```

**Comment by EthanDavis** [comment]
Okay that makes sense. What I'm trying to do is convert a sheet object into a buffer to to act as the return for a mock of a unit test is there an easy way to do that? 
Here is the code that I had: 
```
const testSheetData = [
        {
            'lineId': 187,
            'CogsRating': "rated",
            'rm': 60,
            'gender': 'F'
        },
        {
            'lineId': 189,
            'CogsRating': "rated",
            'rm': 90,
            'gender': 'M'
        }
    ];
    const testExcelSheet = XLSX.utils.json_to_sheet(testSheetData);
    const sheetBuffer = Buffer.from(JSON.stringify(testExcelSheet));
```

Thanks again for the help

**Comment by SheetJSDev** [comment]
If you're ultimately using `XLSX.read`, then generate a valid file:

```js
    const testExcelSheet = XLSX.utils.json_to_sheet(testSheetData);

    // create a workbook
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, testExcelSheet, "Sheet1");

    // generate an XLSX file
    const sheetBuffer = XLSX.write(wb, {bookType: "xlsx", type: "buffer"});
```

You can use "csv" as bookType if you wish.

**Comment by EthanDavis** [comment]
Awesome thank you!

**Comment by rajapgit** [comment]
Hello, 
I am facing similar issue here,
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/P00127~1/AppData/Local/Temp/7/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/P00127~1/AppData/Local/Temp/7/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


zerothColumn | firstColumn | SecondColumn | thirdColumn | fourthColumn | fifthColumn | sixthColumn | eightColumn | ninethColumn | tenthColumn
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
DUMMY | FY 2024-2025 | DUMMY | DUMMY | yes | 0 | 0 | 0 | 173226.5307 | Ok
DUMMY | FY 2024-2025 | DUMMY | DUMMY | no | 0 | 0 | 0 | 0 | Ok
DUMMY | FY 2024-2025 | DUMMY | DUMMY | no | 0 | 0 | 0 | 80564 | Ok



</body>

</html>


this is the excel data, I am trying to read, I am getting empty array at XLSX.utils.sheet_to_json(worksheet),
Code:
`               const workbook = XLSX.read(data, {type: 'binary'}); 

                console.log("workbook "+JSON.stringify(workbook)); 

                const sheetName = workbook.SheetNames[0]; 

                console.log("sheetName "+sheetName); 

                const worksheet = workbook.Sheets[sheetName]; // this is an Object Type

                console.log("worksheet "+JSON.stringify(worksheet));

                const jsonData = XLSX.utils.sheet_to_json(worksheet);

                console.log(jsonData);`

till worksheet if I stringify I get :
{
  "!ref": "A1:J4",
  "A1": {
    "t": "s",
    "v": "zerothColumn",
    "r": "<t>zerothColumn</t>",
    "h": "zerothColumn",
    "w": "zerothColumn"
  },
  "B1": {
    "t": "s",
    "v": "firstColumn",
    "r": "<t>firstColumn</t>",
    "h": "firstColumn",
    "w": "firstColumn"
  },
  "C1": {
    "t": "s",
    "v": "SecondColumn",
    "r": "<t>SecondColumn</t>",
    "h": "SecondColumn",
    "w": "SecondColumn"
  },
  "D1": {
    "t": "s",
    "v": "thirdColumn",
    "r": "<t>thirdColumn</t>",
    "h": "thirdColumn",
    "w": "thirdColumn"
  },
  "E1": {
    "t": "s",
    "v": "fourthColumn",
    "r": "<t>fourthColumn</t>",
    "h": "fourthColumn",
    "w": "fourthColumn"
  },
  "F1": {
    "t": "s",
    "v": "fifthColumn",
    "r": "<t>fifthColumn</t>",
    "h": "fifthColumn",
    "w": "fifthColumn"
  },
  "G1": {
    "t": "s",
    "v": "sixthColumn",
    "r": "<t>sixthColumn</t>",
    "h": "sixthColumn",
    "w": "sixthColumn"
  },
  "H1": {
    "t": "s",
    "v": "eightColumn",
    "r": "<t>eightColumn</t>",
    "h": "eightColumn",
    "w": "eightColumn"
  },
  "I1": {
    "t": "s",
    "v": "ninethColumn",
    "r": "<t>ninethColumn</t>",
    "h": "ninethColumn",
    "w": "ninethColumn"
  },
  "J1": {
    "t": "s",
    "v": "tenthColumn",
    "r": "<t>tenthColumn</t>",
    "h": "tenthColumn",
    "w": "tenthColumn"
  },
  "A2": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "B2": {
    "t": "s",
    "v": "FY 2024-2025",
    "r": "<t>FY 2024-2025</t>",
    "h": "FY 2024-2025",
    "w": "FY 2024-2025"
  },
  "C2": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "D2": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "E2": {
    "t": "s",
    "v": "yes",
    "r": "<t>yes</t>",
    "h": "yes",
    "w": "yes"
  },
  "F2": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "G2": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "H2": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "I2": {
    "t": "n",
    "v": 173226.5306659,
    "w": "173226.5307"
  },
  "J2": {
    "t": "s",
    "v": "Ok",
    "r": "<t>Ok</t>",
    "h": "Ok",
    "w": "Ok"
  },
  "A3": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "B3": {
    "t": "s",
    "v": "FY 2024-2025",
    "r": "<t>FY 2024-2025</t>",
    "h": "FY 2024-2025",
    "w": "FY 2024-2025"
  },
  "C3": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "D3": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "E3": {
    "t": "s",
    "v": "no",
    "r": "<t>no</t>",
    "h": "no",
    "w": "no"
  },
  "F3": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "G3": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "H3": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "I3": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "J3": {
    "t": "s",
    "v": "Ok",
    "r": "<t>Ok</t>",
    "h": "Ok",
    "w": "Ok"
  },
  "A4": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "B4": {
    "t": "s",
    "v": "FY 2024-2025",
    "r": "<t>FY 2024-2025</t>",
    "h": "FY 2024-2025",
    "w": "FY 2024-2025"
  },
  "C4": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "D4": {
    "t": "s",
    "v": "DUMMY",
    "r": "<t>DUMMY</t>",
    "h": "DUMMY",
    "w": "DUMMY"
  },
  "E4": {
    "t": "s",
    "v": "no",
    "r": "<t>no</t>",
    "h": "no",
    "w": "no"
  },
  "F4": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "G4": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "H4": {
    "t": "n",
    "v": 0,
    "w": "0"
  },
  "I4": {
    "t": "n",
    "v": 80564,
    "w": "80564"
  },
  "J4": {
    "t": "s",
    "v": "Ok",
    "r": "<t>Ok</t>",
    "h": "Ok",
    "w": "Ok"
  },
  "!margins": {
    "left": 0.7,
    "right": 0.7,
    "top": 0.75,
    "bottom": 0.75,
    "header": 0.3,
    "footer": 0.3
  }
}


please help!
