### ISSUE TITLE
If we have multiple sheets in excel file how to read and display it?

### ISSUE THREAD

**Issue by Muzamil-Hussain176** [SheetJS/sheetjs#2107]
I have multiple sheets in one excel file and I want to read both sheets and display on my app but I will able to read one excel sheet only. 
please help me to solve this problem...

**Comment by SheetJSDev** [comment]
When you read in the file, you can access each worksheet based on the name.  For example, https://oss.sheetjs.com/sheetjs/ will show you CSV text for each worksheet, and all it does is loop:

```js
		workbook.SheetNames.forEach(function(sheetName) {
			var csv = X.utils.sheet_to_csv(workbook.Sheets[sheetName]);
			if(csv.length){
				result.push("SHEET: " + sheetName);
				result.push("");
				result.push(csv);
			}
		});
```

The details of app display are up to you, but you can access all of the worksheets at the same time.
