### ISSUE TITLE
Long strings getting cut off

### ISSUE THREAD

**Issue by michaloslav** [SheetJS/sheetjs#2108]
I'm using `xlsx.utils.json_to_sheet(data)` and some of the strings in `data` are really long. Those strings get cut off, eg. from 200,797 to 32,767 characters.

I don't think there's anything wrong with my code but here it is just in case. It converts a GeoJSON file to an Excel spreadsheet, the geometry field is the one getting cut off.
```
const xlsx = require('xlsx');
const jsonData = require('./parcels.json');

const data = jsonData.features.map((feat) => ({
  ...feat.properties,
  geometry: JSON.stringify(feat.geometry),
}));

const book = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(book, xlsx.utils.json_to_sheet(data), 'parcels');
xlsx.writeFile(book, './parcels.xlsx');
```

**Comment by SheetJSDev** [comment]
This is an Excel limitation.

Even though it isn't explicitly stated https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 references the 32767 character limit in a few places.

Just testing in Excel, `REPT("a",32767)` is a string but `REPT("a",32768)` is a `#VALUE!` error.  The REPT documentation also says:

> The result of the REPT function cannot be longer than 32,767 characters, or REPT returns #VALUE!.

So we're left to conclude that it is an Excel issue
