### ISSUE TITLE
Headers Grouping by merging cells related to it

### ISSUE THREAD

**Issue by manojcena** [SheetJS/sheetjs#2109]
Hi,
I am developing an application using angular and i implemented export as excel by following this link https://medium.com/@madhavmahesh/exporting-an-excel-file-in-angular-927756ac9857. I have a another requirement where we should have a header like mention and highlighted in attachment ![headers-grouping](https://user-images.githubusercontent.com/15008735/93462257-a9f75c00-f903-11ea-80c2-c7a16e67c7ca.png).  i was trying to find some documentation but i did't find any. Could you please help me to achieve this. 
Thanks in advance.

**Comment by reviewher** [comment]
It looks like cells D4:G4 and H4:K4 are merged.  You can create that effect by writing "type" to cell D4 and "batting" to cell H4 and creating merges:

```js
if(!ws["!merges"]) ws["!merges"] = [];
ws["!merges"].push(XLSX.utils.decode_range("D4:G4")); // { s: { r: 3, c: 3 }, e: { r:3, c: 6 } }
ws["!merges"].push(XLSX.utils.decode_range("H4:K4")); // { s: { r: 3, c: 7 }, e: { r:3, c: 10 } }
```
