### ISSUE TITLE
Different date formats

### ISSUE THREAD

**Issue by BanannaLopal** [SheetJS/sheetjs#2111]
How to use sheetsJS to display the date so that when there is no time, the date is displayed as 13/04/2000. And if the date contains time, it will be displayed as 13/04/2000 06:20.

In my version, the date without time is displayed as 13/04/2000 00:00.
![image](https://user-images.githubusercontent.com/49365601/93767179-49785f80-fc20-11ea-9b85-35d774a86f85.png)

**Comment by reviewher** [comment]
There is no Excel format that displays time for non-integral datecodes.  If you can reproduce the behavior in Excel, reopen the issue and we can look at the file.
