### ISSUE TITLE
Corrupted XLSM file 

### ISSUE THREAD

**Issue by leanesanity** [SheetJS/sheetjs#2115]
I have an issue when downloading the file,
what I am suppose to do is edit the content of my xlsm file and then download the file.
I also tried https://github.com/SheetJS/sheetjs/issues/217 workaround here, but it doesn't work.

My Sample Code : 

export const insertData = (file, callback) => {
  const fileReader = new FileReader();
  fileReader.onload = (event) => {
    try {
      const { result } = event.target;
      const workbook = XLSX.read(result, {
        type: 'binary',
      });
      const firstSheet = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[firstSheet];
      // modify value in D4
      worksheet.D4.v = 'NEW VALUE from NODE';

      const wopts = { bookType: 'xlsx', bookSST: true, type: 'binary' };
      const wbout = XLSX.write(workbook, wopts);
      /* generate array buffer */
      console.log(wbout);  // Weird characters are found
      /* create data URL */
      const url = URL.createObjectURL(
        new Blob([wbout], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        }),
      );
      callback(URL); // URL here is use for download
    } catch (e) {
      console.log(e);
      callback(null);
    }
  };
  fileReader.readAsBinaryString(file);
};

LOG 
![image](https://user-images.githubusercontent.com/39898232/94224099-1d145a00-ff24-11ea-9c93-5b0ac307af16.png)

**Comment by SheetJSDev** [comment]
Let's start from the top.  Can you try:

```js
export const insertData = (file, callback) => {
  const fileReader = new FileReader();
  fileReader.onload = (event) => {
    try {
      const { result } = event.target;
      const workbook = XLSX.read(result, {
        type: 'binary',
      });
      const firstSheet = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[firstSheet];
      // Log D4
      console.log(worksheet.D4);
      // modify value in D4
      worksheet.D4.v = 'NEW VALUE from NODE';

      const wopts = { bookSST: true };
      XLSX.writeFile(workbook, "out.xlsm", wopts);
      callback(true); // URL here is use for download
    } catch (e) {
      console.log(e);
      callback(null);
    }
  };
  fileReader.readAsBinaryString(file);
};
```

If this fails, can you share the original and generated file?

**Comment by leanesanity** [comment]
That code ables me to download the file.
But it seems that the formats on my file are all gone.

![image](https://user-images.githubusercontent.com/39898232/94225649-2ef7fc00-ff28-11ea-9b86-053cd4093475.png)

**Comment by leanesanity** [comment]
What I am trying to do here is just, update some values of some cells.
Retaining the same formats of the file.
Is it possible ? How to do it?
Thank you very much for the help. Really appreciated it

![image](https://user-images.githubusercontent.com/39898232/94225866-b6de0600-ff28-11ea-9deb-17298b08c7ba.png)

**Comment by SheetJSDev** [comment]
That particular work flow is something we offer as part of our [Pro offering](https://sheetjs.com/pro).

**Comment by mytrytest** [comment]
I am also getting a corrupted excel file. I am using the express JS server and trying to get from AWS MWS. API will return excel but I am not able to get a proper Excel file.

```
const XLSX = require('xlsx');
var ws = XLSX.utils.json_to_sheet(response.data);
    var wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws);

    var buf = XLSX.write(wb, {bookType:'xlsx', type:'buffer'}); // generate a nodejs buffer
    var str = XLSX.write(wb, {bookType:'xlsx', type:'binary'});
    
    XLSX.writeFile(wb, "sheetjs.xlsx");
```

**Comment by mytrytest** [comment]
I fixed the issue by write stream.

```
const dest = fs.createWriteStream('./sheetjs.xlsx');
response.body.pipe(dest).on('finish', function(){
  console.log('done');
});
```
