### ISSUE TITLE
Hidden Column is visible

### ISSUE THREAD

**Issue by appu-sm** [SheetJS/sheetjs#2117]
I have a XLS file which has few hidden columns, when i open it in sheetjs, the hidden columns are visible and there is no {hidden: true} property in [!cols]

**Comment by DaivdLei** [comment]
excuse me. do you solution? please, i have the same question...

**Comment by appu-sm** [comment]
I have started using xlsx files, for XLS files, during opening a file i automatically convert it into xlsx using php.

**Comment by SheetJSDev** [comment]
For XLS, the change is in [`bits/76_xls.js`](https://github.com/SheetJS/sheetjs/blob/master/bits/76_xls.js#L573) 

```js
						colinfo[val.e--] = { width: val.w/256, hidden: !!(val.flags & 1) };
```

We'd accept a PR with this change
