### ISSUE TITLE
SheetJs: Read and update the same xlsx file in pureJS

### ISSUE THREAD

**Issue by amitk7407** [SheetJS/sheetjs#2122]
I'm trying to read an xlsx file and update the same file without having to download a new one but I'm having difficulties to do so. I even didn't find any example online. Also, when I'm downloading a new file with updated data, cell colors are missing.

Thanks in advance

**Comment by SheetJSDev** [comment]
This particular workflow (reading file, editing data, downloading new one) is supported in our [Pro offering](https://sheetjs.com/pro)
