### ISSUE TITLE
QUESTION: Looking For Simple Example in-memory JSON exported to XLSX file.

### ISSUE THREAD

**Issue by tinjaw** [SheetJS/sheetjs#2123]
I have a JSON object obtained through a JSONata query. I want to export the result to a (simple) XLSX file on disk. Is there a (similar) example of how to do this somewhere?

**Comment by rye761** [comment]
Maybe just have a look at https://github.com/SheetJS/sheetjs/tree/master/demos/database?

**Comment by reviewher** [comment]
Assuming your JSON object is an array of simple data objects:

```js
var data = [
  { Name: "Barack Obama", Index: 44 },
  { Name: "Donald Trump", Index: 45 }
]
```

You can use `json_to_sheet` to generate a worksheet:

```js
var ws = XLSX.utils.json_to_sheet(data); // new worksheet from data

var wb = XLSX.utils.book_new(); // new workbook
XLSX.utils.book_append_sheet(wb, ws, "Sheet1"); // add worksheet to workbook
XLSX.writeFile(wb, "data.xlsx"); // export
```

The demos like the one @rye761 mentioned have more advanced use cases
