### ISSUE TITLE
Sheet to Array of Array

### ISSUE THREAD

**Issue by noam-honig** [SheetJS/sheetjs#2124]
Hi, 

I love this lib.

Today there is a sheet_to_json.

I often need a sheet_to_aoa
That will return an array of array and not an array of json objects.

Is there an option to sheet_to_json that will return that?

**Comment by SheetJSDev** [comment]
`header: 1` as described in https://docs.sheetjs.com/#json :

```js
XLSX.utils.sheet_to_json(ws, {header:1});
```

**Comment by noam-honig** [comment]
Thanks for the answer - that's what I was looking for.

Maybe there is room to make it a bit more obvious in the doc there - I've
read that part several times before I wasted time creating my own version
of sheet_to_json.

I can see now that it states that in the "header is expected to be one of"

Unfortunately when I read it the first few times - I didn't find it (that
table didn't pop out to me)

I'm not sure if it's just me or something that can be improved in the doc -
your call :)

Thanks - very cool lib

**Comment by SheetJSDev** [comment]
Docs are a work in progress.  Feel free to submit a PR or give a recommendation and we'll try to improve it!

**Comment by nickfreemandesign** [comment]
thanks for this thread, and totally agreed on documentation needing improvement. is there a contribution guide? any way to get this scaffolded up can enable developers like myself to contribute more effectively. see [this example](https://github.com/facebook/docusaurus#contributing)

**Comment by SheetJSDev** [comment]
We've moved the docs to a new site https://docs.sheetjs.com/ .  Source for the site is https://github.com/SheetJS/docs.sheetjs.com .  The `docz` subfolder is the Docusaurus-powered structure and the build sequence moves the generated site to the `docs` subfolder.

https://docs.sheetjs.com/docs/miscellany/contributing is the contribution guide, let us know if anything else should be added.
