### ISSUE TITLE
split cell into "subcells"

### ISSUE THREAD

**Issue by peppeg85** [SheetJS/sheetjs#2128]
hello, i wrote also a few time ago here: https://github.com/SheetJS/sheetjs/issues/1970
i still have this problem. in that discussion you tell me to try with rowspan, but i think i can't solve in this way. 
i tried by nesting a table inside a td, it is html valid and i have a good graphical result, but when i export the table i have the nested table rows after the row that it was nesting. have you got any suggestions?
is this the case to create an excel file with the raw data instead to create it from the html table? in this way how can i nest the cells?
thank you!

**Comment by peppeg85** [comment]
what i need to do is a table like this:

![image](https://user-images.githubusercontent.com/25436763/95219248-736f7b80-07f5-11eb-8dbe-cfb160e10f8e.png)

how can i design it? i can organize a json object or create directly in javascript, i'm reading the documentation, but i'm not understanding so mitch, if someone could help me, thank you

**Comment by SheetJSDev** [comment]
https://jsfiddle.net/rc2jhwz4/

```js
var ws = XLSX.utils.aoa_to_sheet([
	["name", "surname", "orders", "paid", "topay"],
	[, "age"],
	[, "born"],
	[, "xxxxx"]
]);
ws["!merges"] = [];
for(var i = 0; i <= 4; ++i) if(i != 1) ws["!merges"].push({s: {c: i, r: 0}, e: {c: i, r: 3}});

var data = [
	{ name: "john", surname: "doe", age: 44, born: 55, xxxxx: "xxxxx", orders: 55, paid: 2, topay: 53 },
	{ name: "john", surname: "doe", age: 66, born: 77, xxxxx: "xxxxx", orders: 55, paid: 2, topay: 53 },
	{ name: "john", surname: "doe", age: 88, born: 99, xxxxx: "xxxxx", orders: 55, paid: 2, topay: 53 },
];

data.forEach(row => {
	var old_range = XLSX.utils.decode_range(ws["!ref"]);
	XLSX.utils.sheet_add_aoa(ws, [
		[row.name, row.surname, row.orders, row.paid, row.topay],
		[, row.age],
		[, row.born],
		[, row.xxxxx]
	], {origin: -1});
	var new_range = XLSX.utils.decode_range(ws["!ref"]);
	for(var i = 0; i <= 4; ++i) if(i != 1) ws["!merges"].push({s: {c: i, r: old_range.e.r+1}, e: {c: i, r: new_range.e.r}});
	
});

var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue2128.xlsx");
```

**Comment by peppeg85** [comment]
Great! thank you!
