### ISSUE TITLE
CSV format - Cyrillic letters and header columns are getting ignored

### ISSUE THREAD

**Issue by ulantiger** [SheetJS/sheetjs#2130]
Hello there,
Thank you for your great job!

I found really strange, that from the original XLSX file when you convert it into CSV all strings and letters, which consist of Cyrillic letters, are getting removed or ignored. And also if the row after the header has missing cells, that column gets ignored as well. 

I can send an XLSX file for your reference by email.

Regards, Ulanbek

**Comment by NeeEoo** [comment]
I am going to try to find the bug.

**Comment by NeeEoo** [comment]
Nevermind too hard for me.

**Comment by SheetJSDev** [comment]
Please share a sample file, you can email to hello@sheetjs.com

**Comment by Paxton1337** [comment]
Hello
I also ran into the problem of creating a file with the .dbf extension, all Cyrillic characters in the JSON format from which I take the data are ignored, they just turn into "_"
Are there any ways to solve this problem?

**Comment by ulantiger** [comment]
Hi, 
Still waiting for the answers and bug fix. 
I believe it should be connected to utf-8 charsets. 
Let's wait. 



--
Sent from Mail.ru app for Android Friday, 06 November 2020, 03:54pm +00:00 from Gleb Rutskiy  notifications@github.com :

**Comment by SheetJSDev** [comment]
You have to explicitly pick a codepage that includes the characters you want.  The typical codepage for Cyrillic is Windows-1251 , and the option has to be specified when writing to CSV or read from DBF or writing to DBF:

```js
    XLSX.read(data, {..., codepage: 1251});
    XLSX.write(wb, {..., codepage: 1251});
```
