### ISSUE TITLE
fix x-spreadsheet demo

### ISSUE THREAD

**Issue by reviewher** [SheetJS/sheetjs#2133]
https://oss.sheetjs.com/sheetjs/x-spreadsheet.html 

> Uncaught ReferenceError: x is not defined
>    at x-spreadsheet.html:54

**Comment by Denisqo** [comment]
Hello,

I would like to work on this issue.

**Comment by reviewher** [comment]
Awesome! https://github.com/SheetJS/sheetjs/blob/gh-pages/x-spreadsheet.html the file is `x-spreadsheet.html` in the `gh-pages` branch.

The current code:

```js
var xspr = x.spreadsheet(HTMLOUT);
```

Based on https://github.com/myliang/x-spreadsheet#cdn I think the fix is just

```js
var xspr = x_spreadsheet(HTMLOUT);
```

To test this, make the change and see if you get an error in the JS console when you open the page.

**Comment by Denisqo** [comment]
I'll look into it this weekend. If you don't mind, you can assign me to this task.

**Comment by reviewher** [comment]
428d03a4692e1a96e9e6aa4488de95af397ff77c
