### ISSUE TITLE
Empty line treated by sheet_to_json

### ISSUE THREAD

**Issue by Akta3d** [SheetJS/sheetjs#2134]
When I read this file with 2 lines of data
[bugTestFile.xlsx](https://github.com/SheetJS/sheetjs/files/5349243/bugTestFile.xlsx)

```
const data = new Uint8Array(contents);
const workbook = XLSX.read(data, { type: 'array' });
const worksheet = workbook.Sheets[workbook.SheetNames[0]];

```
worksheet have worksheet.!ref = AH1048576
then I call sheet_to_json and need of lot of time to convert all these empty and unused lines
`const jsonWorksheet = XLSX.utils.sheet_to_json(worksheet);`

After deleting all unused lines with OpenOffice, the sheet_to_json work is quick
[testFile.xlsx](https://github.com/SheetJS/sheetjs/files/5349223/testFile.xlsx)

Is it possible to detect empty line during read the file ?

**Comment by SheetJSDev** [comment]
There's an option to suppress the blank rows:

```js
const jsonWorksheet = XLSX.utils.sheet_to_json(worksheet, {blankrows: false});
```

More generally, the worksheet reports that extremely large range:

```xml
  <dimension ref="A1:AH1048576"/>
```

When you open and save, OpenOffice is recalculating the dimension:

```xml
  <dimension ref="A1:AH9"/>
```

The [`update_sheet_range` snippet in the wiki](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions#updating-worksheet-range) rewrites the dimensions based on the actual cells in the sheet

**Comment by Akta3d** [comment]
Really thanks, it's exactly what I need
