### ISSUE TITLE
Not able to read excel files with cell styles 

### ISSUE THREAD

**Issue by MobackAdarshPB** [SheetJS/sheetjs#2135]
Sheetjs is unable to read files close to 30mb or above with multiple sheets with cellStyles property "true". 
{
      cellDates: true,
      cellStyles: true 
    }

It does not throw any error,the process run for infinite time.
Without cellStyles there is no issue in reading file.

Node 12.18 is runtime environment

**Comment by SheetJSDev** [comment]
If you can share the file, we can take a closer look.  It's probably too large to share directly, so post to a file sharing service and share a link.

**Comment by MobackAdarshPB** [comment]
const XLSX = require("@sheet/core"); 
const workbook = XLSX.readFile("sample.xlsx", {
    cellDates: true,
    cellStyles: true,
    type: "buffer",
  });
  const report = XLSX.writeFile(workbook, "resultWithStyles.xlsx", {
    cellStyles: true,
    type: "buffer",
    compression: true,
  });

Above is read and write code which i am using.
[https://test-bk-5.s3.amazonaws.com/sample.xlsx](url)
Link for sample file

**Comment by SheetJSDev** [comment]
If this is relating to Pro builds, send an email to support@sheetjs.com
