### ISSUE TITLE
Parsing sheets with empty cell data, result in mismatch of table heading and data

### ISSUE THREAD

**Issue by Daniel-Yonkov** [SheetJS/sheetjs#2136]
Here is an exampel of the issue, imagine this is the excel file:
| A1       | B1        |  C1      |
| --------- | --------- | --------- |
| Field 1 | Field 2 | Field 3 | 
| 1          |             |   3       |

I parse the file as a following:
```js
const workbook = XLSX.read(fileStream, {
        type: 'buffer',
        sheetStubs: true
    });
const reuslt = XLSX.utils
               .sheet_to_json(book.Sheets[book.SheetNames[0]], { defval: '' })
               .pop();
```
What i get as a `result` is the following
```json
{
    "Field 1": "1",
    "Field 2": "3",
    "Field 3": ""
}
```
Any idea on how this can be fixed? The browser examples have the same issue.

**Comment by SheetJSDev** [comment]
Can you share a sample file that triggers the issue?  If you can't share publicly, feel free to email us at hello@sheetjs.com

**Comment by DanielTerbl** [comment]
Have the same issue.

**Comment by Daniel-Yonkov** [comment]
@DanielTerbl  - See PR #2140 , it fixes the   issue. Currently it has been merged into master, but it has not yet being released. 
You could fork the repo and try to see if it fixes the issue for you, while waiting for the release.
In order to apply the changes, you would need to run `make` for the nodejs build and then `make dist` if you are using the standalone browser script.

BR,
Dany

**Comment by Daniel-Yonkov** [comment]
@SheetJSDev - Hello there, can you give us some more info regarding when there will be a new release with the applied changes?
BR, Dany

**Comment by SheetJSDev** [comment]
@Daniel-Yonkov it should have been included in the latest (0.16.9) release, can you test and confirm?

**Comment by Daniel-Yonkov** [comment]
Can confirm the issue has been fixed, thank you!

**Comment by GaneshSinghPapola** [comment]
xlsx.read(xlsFile.buffer, { sheetStubs: true, type: "buffer" })

this line is not showing empty cell data
sheetStubs : true not working.
can anyone help?

**Comment by reviewher** [comment]
Please share a sample file, what you expect to happen and what is actually happening
