### ISSUE TITLE
Edited HTML content is not exporting as XSLX, but exporting old data

### ISSUE THREAD

**Issue by ursNj** [SheetJS/sheetjs#2137]
Not getting edited values in XLSX, but getting old data.

**Comment by SheetJSDev** [comment]
Logical issue with contenteditable and attributes https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L83 .  The logic should check `o.editable` first, only writing the `t` / `v` / `z` attributes if `o.editable` is not set.  So it is something like:

```js
			sp.id = (o.id || "sjs") + "-" + coord;
			if(o.editable) w = '<span contenteditable="true">' + w + '</span>';
			else {
				sp.t = cell && cell.t || 'z';
				if(sp.t != "z") { sp.v = cell.v; if(cell.z != null) sp.z = cell.z; }
			}
```
