### ISSUE TITLE
Can't convert an external JSON file into XLSX

### ISSUE THREAD

**Issue by aanghileri** [SheetJS/sheetjs#2141]
Im trying to convert an external file into a excel file, but i can't do it properly. 
Here is my code:
` const fs = require('fs');
const XLSX = require('xlsx');

let readJson = XLSX.readFile('./esempio.json');

/* make the worksheet */
var ws = XLSX.utils.json_to_sheet(readJson);

/* add to workbook */
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet 1");

fs.writeFile("output.json", readJson, 'utf8', function (err) {
    if (err) {
        console.log("Errore durante il caricamento del file.");
        return console.log(err);
    }
 
    console.log("File Json salvato correttamente");
});`

And this is the external json file( it's located in the same folder):
`[{
    "window": {
        "title": "Sample Konfabulator Widget",
        "name": "main_window",
        "width": 500,
        "height": 500
    },
    "image": { 
        "src": "Images/Sun.png",
        "name": "sun1",
        "hOffset": 250,
        "vOffset": 250,
        "alignment": "center"
    },
    "text": {
        "data": "Click Here",
        "size": 36,
        "style": "bold",
        "name": "text1",
        "hOffset": 250,
        "vOffset": 100,
        "alignment": "center",
        "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;"
    }
}]`

I keep getting this error:

js.forEach(function (JS, R) {
           ^

TypeError: js.forEach is not a function
    at sheet_add_json (C:\Node\Excel-Json\node_modules\?[4mxlsx?[24m\xlsx.js:21379:5)
    at Object.json_to_sheet (C:\Node\Excel-Json\node_modules\?[4mxlsx?[24m\xlsx.js:21414:43)
    at Object.<anonymous> (C:\Node\Excel-Json\json_to_excel.js:7:21)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:928:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m

Can someone help me?thx

**Comment by reviewher** [comment]
```js
let readJson = XLSX.readFile('./esempio.json');
```
should be
```js
let readJson = require('./esempio.json');
```
