### ISSUE TITLE
json_to_sheet can't recognize some objects

### ISSUE THREAD

**Issue by Al3x999** [SheetJS/sheetjs#2142]
#Hello everyone.
I'm having trouble converting a json code into an excel file.

Here is the code of my js file using XLSX:

`let XLSX = require('xlsx');`

`let data = [`
   ` {
        "id": 1,
        "details": {
            "first_name": "Gary",
            "last_name": "Ortiz",
            "nicknames":[{
                "language":"italian",
                "value": "martello"},
                {"language": "inglese",
                 "value":"hammer"
                }
            ],`
         `   "email":
            [ "gortiz0@mapy.cz",
              "awilliamson1@narod.ru"
            ]
        },
        "country": "Indonesia",
        "modified": "2015-05-16",
        "vip": false
    }]`
        

`let ws = XLSX.utils.json_to_sheet(data)`

`let wb = XLSX.utils.book_new();`
`XLSX.utils.book_append_sheet(wb, ws);`

`XLSX.writeFile(wb, `"outputExcel.xlsx");`

The excel created has the "details" and the "email" columns empty, and it doesn't create the "nicknames","language","value" columns.
Am i missing something?

**Comment by SheetJSDev** [comment]
Nested objects aren't supported.  The best way to write is to use `aoa_to_sheet` and manually generate the arrays for each row:

```js
var aoa = data.map(obj => ([
  obj.id,
  obj.details.first_name,
  obj.details.last_name,
  ...
]));
```
