### ISSUE TITLE
Export Excel prints Footer on Top

### ISSUE THREAD

**Issue by ThakkarKhushbu** [SheetJS/sheetjs#2143]
Hello ,

I  am using Angular P-table (prime NG) and sheet.js to export that data.  structure is like below

```
<p-table #dt [columns]="cols" class="table" [rows]="100" [value]="result">
 // Header

<ng-template pTemplate="header">
   ...
   ...
</ng-template>
// Actual Data -- Body
<ng-template pTemplate="body" let-costevent let-rowIndex="rowIndex">
    ...
    ...
</ng-template>
// Footer
 <ng-template pTemplate="footer">

 // Grand Total
 </ng-template>

</p-table>
```
now while we export this using sheet.js , it is exporting but like below

Header
Footer
Data

and it should be like below

Header
Data 
Footer 

![image](https://user-images.githubusercontent.com/30835218/95967884-69b7ca80-0e2a-11eb-9f59-eaba29c2eede.png)

please suggest a way to resolved this 

Export code is like below
````
exportexcel(): void {
    const element = document.getElementById('docreview');
    const ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(element);
    const wb: XLSX.WorkBook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    XLSX.writeFile(wb, this.fileName);
  }
```

**Comment by SheetJSDev** [comment]
That looks like an issue with the other library.  If they are putting the footer first and using CSS to move the footer rows, then the HTML walker will see the footer first.  You should raise an issue with the other library asking how the footer rows can be written at the end.
