### ISSUE TITLE
Not getting my last row (Grand Total Column) at Last (Instead getting as a First Row) in Excel Output using SheetJS

### ISSUE THREAD

**Issue by NayanMiyatra** [SheetJS/sheetjs#2144]
![image](https://user-images.githubusercontent.com/46615086/95967452-e6967480-0e29-11eb-95eb-eccacef906ef.png)
This is the HTML Code of Last Row

![image](https://user-images.githubusercontent.com/46615086/95967560-04fc7000-0e2a-11eb-937b-7f81a6b5b2ae.png)
This is the .ts code for Excel export using SheetJS

![Screenshot (1220)](https://user-images.githubusercontent.com/46615086/95967873-67557080-0e2a-11eb-8f8a-e0b64fa218af.png)
This is How table looks like

![image](https://user-images.githubusercontent.com/46615086/95968056-a2f03a80-0e2a-11eb-8682-17e1a6c94f45.png)
This is the Excel Output

How should I get that grand total (First row) at Last

**Comment by SheetJSDev** [comment]
You need to get the actual TABLE DOM element.  Normally you would get a ref to the table, access the native element and find the first table child.  Since you've already assigned an id, you can just write

```ts
const element = document.getElementById("docreview").getElementsByTagName("TABLE")[0];
```
