### ISSUE TITLE
Partial data obtained from file upload (form object) node js

### ISSUE THREAD

**Issue by workinghuman** [SheetJS/sheetjs#2145]
Client side:    

```
     let excelInput = document.getElementById("fileToUpload");
     let excelFile = excelInput.files[0]; //get the excel file from the element
     let form = new FormData();
     form.append("excel", excelFile);
           fetch('/sendExcel', {method: "POST", body: form})
      .then((data) => {
        console.log('Success:', data);
      })
      .catch((error) => {
        console.error('Error:', error);
      });
    }

```
Server side:

```
var workbook = sheetJS.read(data, {type: 'buffer'});
console.log("workbook is", workbook);
```

Prints... `excel is { SheetNames: [ 'Sheet1' ], Sheets: { Sheet1: { A1: [Object], '!ref': 'A1' } }` which is only partial.

For comparison, using the file location instead of the actual file, `var wb = sheetJS.readFile("data.xlsx");` prints all the information as normal. I have tried using fileReader but it comes up with this error: TypeError: Cannot read property 'readAsArrayBuffer' of undefined. But the file works when using sheetJS to read the data with `type:'buffer'`. I am supposed to upload information to the server using the imported file, but I can't find a solution that works.  If anyone could give any help or hints I'd be really grateful.

**Comment by workinghuman** [comment]
It seems like you have to use formidable but it now works!

app.post('/sendExcel', function(req, res) {
    let data = req.body;
    const form = formidable({ multiples: true });

    form.parse(req, (err, fields, files) => {
      if (err) {
        next(err);
        return;
      }

      var f = files[Object.keys(files)[0]];
      var workbook = sheetJS.readFile(f.path);
      res.send(workbook);
    });

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/tree/master/demos/server#responding-to-form-uploads is what we came up with -- can you review the demo and see if it makes sense?
