### ISSUE TITLE
Using of Excel-functions (e.g. IF, VLOOKUP)

### ISSUE THREAD

**Issue by kozak-taras** [SheetJS/sheetjs#2149]
Hi,
I am trying to put a formula with **IF** function. 

The first way I went, was writing the string formula into the sheet with `.json_to_sheet.`
It works, but the result isn't calculated after opening the workbook. I have to click on the cell, then press enter and then the cell will show the result.

I found the same issue but I could not understand the solution (if it exists):
[https://github.com/SheetJS/sheetjs/issues/306](url)

The second way I went, was using of the next construction in order to generate the formula:
`ws['B1'] = {t:'n', f:"**IF(A1<0;1;5)**"};`
After opening the file the result wasn't calculated as well.

Is it generally possible to use **IF** and **VLOOKUP** functions with the SheetJS, that the cells get calculated after opening the file?

If it's possible I will be very appreciated for any advice!

Taras

**Comment by SheetJSDev** [comment]
You have to use en_US formula expressions, which means commas between arguments:

```js
var ws = XLSX.utils.aoa_to_sheet([
  [1,2,3],
  [{t:"n", f:"IF(A1<0,1,5)"}]
]);

var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

XLSX.writeFile(wb, "issue2149.xlsx");
```

https://jsfiddle.net/wcqo56bv/ live demo

**Comment by kozak-taras** [comment]
@SheetJSDev 
Thank you a lot for the quick answer :)

**Comment by heaxo** [comment]
@SheetJSDev hello，How do I set a formula for a certain cell, in other words, how do I use row and column coordinates to set a formula
