### ISSUE TITLE
Wrong reading of first cell in .fods format

### ISSUE THREAD

**Issue by fedelway** [SheetJS/sheetjs#2150]
Hello, i'm having a little issue with reading a fods format. I'm currently using SheetJS to read a xlsx file and since it is compressed it is not very "git friendly". So I tried using the OpenOffice non-compressed format .fods to read the file.

It works almost perfectly, but the first cell of the first page is wrong when using `sheet_to_json`.

Here is an example of how it parses the data (notice there is a lot of noise):
![image](https://user-images.githubusercontent.com/17912915/96458104-f087f100-11f6-11eb-89ac-6db7907a9302.png)

Here is the same exact spreadsheet but duplicated in the second sheet, and it works perfectly:
![image](https://user-images.githubusercontent.com/17912915/96458368-3a70d700-11f7-11eb-8777-b16688a8c8c8.png)

Any ideas what it could be?

**Comment by SheetJSDev** [comment]
Can you share the file?  Email hello@sheetjs.com or put the file somewhere so we can take a closer look, but from the looks of it there might be some encoding issue.

**Comment by fedelway** [comment]
Yes, sure.

I emailed you the file.

**Comment by fedelway** [comment]
Solved by #2159
