### ISSUE TITLE
there is in issue in xlsx export Date, automatically add 21 seconds to the dateTime see the demo (https://sheetjs.com/demo/writexlsx.html)

### ISSUE THREAD

**Issue by hamdiChehdi** [SheetJS/sheetjs#2152]

**Comment by hamdiChehdi** [comment]
https://sheetjs.com/demo/writexlsx.html 
it add 21 to the date 19/02/2014 15:30:21

**Comment by reviewher** [comment]
What is your current computer timezone?  If you are using a modern browser, you can run `new Intl.DateTimeFormat().resolvedOptions().timeZone` in the console

**Comment by ferjul17** [comment]
Hi, I have the same issue. In case it can help, my timezone is `Europe/Paris`.

**Comment by SheetJSDev** [comment]
SheetJS Dates are anchored to Excel's 1900 epoch.

`Europe/Paris` was UTF +00:09:21 in 1900.  It shifted to UTC +00:00:00 in 1911.

Closing in favor of https://github.com/SheetJS/sheetjs/issues/1565
