### ISSUE TITLE
HTML Table with dropdown shows all fields

### ISSUE THREAD

**Issue by likemike90** [SheetJS/sheetjs#2154]
Hello Guys,

i have a problem with exporting an HTML Table with an <input select> field in it. 

The export works well but all the fields in my select dropdown are shown , the selected one is the first like shown in the image below 

![sheetjs](https://user-images.githubusercontent.com/69216871/97092471-70251e00-1644-11eb-9224-8e5615eb0f44.png)

Is this function not supported in Sheetjs or do i miss something here ?

here is my code 👍 

`         echo "<td><form name="select_vd" id="select_vd">"; 
                            echo "<select id="select_vd">";
                            echo "<option>".$row['verdacht']."</option>";
                            echo "<option>-</option>";
                            echo "<option>0</option>";
                            echo "<option>1</option>";
                            echo "<option>2</option>";
                            echo "<option>3</option>";
                            echo "<option>4</option>";
                            echo "<option>5</option>";                                                                                  
                            echo "</select></center>";
                echo "</form>"; 
                echo "</td>";`

.......

`<script>
        var wb = XLSX.utils.table_to_book(document.getElementById('mytable'), {sheet:"Sheet JS", raw: true});
        var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});

        function s2ab(s) {

                        var buf = new ArrayBuffer(s.length);
                        var view = new Uint8Array(buf);
                        for (var i=0; i<s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                        return buf;
        }
        $("#button-a").click(function(){
        saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), 'test.xlsx');
        });

</script>
`

Thanks for your help

**Comment by SheetJSDev** [comment]
Thanks for sharing!  This is an issue with how we're pulling text from the individual TD elements.  https://jsfiddle.net/xgvp456y/ repro

**Comment by reviewher** [comment]
It looks like the same issue as #991
