### ISSUE TITLE
Tooltip for columns / cells

### ISSUE THREAD

**Issue by mvelraj** [SheetJS/sheetjs#2155]
How to add tooltip for export excel cells?

Example:Add tool tip for A2 column and add tooltip for A2Cell.

**Comment by reviewher** [comment]
Create a link on cell A2 pointing back to A2 with the desired tooltip:

```js
ws['A2'].l = { Target:"#A2", Tooltip:"Find us @ SheetJS.com!" };
```

**Comment by SaahilBallani** [comment]
How to Apply CSS to the Tooltip?
