### ISSUE TITLE
x-spreadsheet demo cannot work 

### ISSUE THREAD

**Issue by samz-github** [SheetJS/sheetjs#2158]
I try to see if https://oss.sheetjs.com/sheetjs/x-spreadsheet.html work, but it failed. Thrown exception on console as below:
> x-spreadsheet.html:54 Uncaught ReferenceError: x is not defined
>     at x-spreadsheet.html:54

**Comment by michaeltomasik** [comment]
duplicate of https://github.com/SheetJS/sheetjs/issues/2133

**Comment by reviewher** [comment]
428d03a4692e1a96e9e6aa4488de95af397ff77c
