### ISSUE TITLE
readAsArrayBuffer on IE throwing SecurityError

### ISSUE THREAD

**Issue by MatosMarcos** [SheetJS/sheetjs#2162]
While uploading a xlsx file on IE 11.11.18362.0, I faced the following error (event.target.error.name: Error Code: SecurityError).
I'm not facing this issue in the other browsers and for those browsers I'm using readAsBinaryString.

`	if (_reader.readAsBinaryString) {
	        _reader.readAsBinaryString(oFile);
	} else {
	       _reader.readAsArrayBuffer(oFile);
	  }`
In this case when we are on IE 11, it's entering the else condition.
I've tested with both large and small files, and none is working.

**Comment by SheetJSDev** [comment]
Can you reproduce this issue in our public demos https://oss.sheetjs.com/ or https://oss.sheetjs.com/sheetjs ?

**Comment by MatosMarcos** [comment]
@SheetJSDev I've found out that it was due to a security setting in the xlsx file, so unchecking the security setting did the trick and now I'm able to upload. Thank you.
