### ISSUE TITLE
XLSX.utils.json_to_sheet does not fill columns with same name

### ISSUE THREAD

**Issue by masciugo** [SheetJS/sheetjs#2163]
I need to have 2 identical columns in the sheet. In the following example the resulting 3 columns sheet has the correct header but the last column values are empty: it just has the header filled 

```

JSON.stringify(sheet, null, 2)
"{
  "fields": [
    "pubID",
    "sex",
    "sex"
  ],
  "values": [
    {
      "pubID": "P_OMGIFJHQ8U",
      "sex": "m"
    }
  ]
}"

XLSX.utils.json_to_sheet(sheet.values, {header: sheet.fields})
```

![image](https://user-images.githubusercontent.com/454321/97574333-58a2b800-19eb-11eb-958b-df9e7dcf3617.png)

**Comment by SheetJSDev** [comment]
The `header` option dictates field order when writing each object.  The object keys are scanned once and written once.

If you really need to duplicate fields, build up the desired structure as an array of arrays and use aoa_to_sheet:

```js
XLSX.utils.aoa_to_sheet([sheet.fields].concat(sheet.values.map(row => sheet.fields.map(k => row[k]))));
```

@paustint Is this the type of thing that should be included in the README?

**Comment by masciugo** [comment]
thank you for the workaround and the internals explanation. 

However, IMHO, from an API point of view the header option seems to determine exactly the header not only the order.
