### ISSUE TITLE
Read only number of rows in sheets

### ISSUE THREAD

**Issue by Raju-N** [SheetJS/sheetjs#2168]
We have scenario where user can upload excel with 300K+ rows. When I parse the workbook its taking more time to parse entire data So I need to read only sheet names and number of rows in it so that we can parse only specific sheet. Kindly help to get only  sheet names and number of rows in it alone.

**Comment by reviewher** [comment]
Option `sheetRows: 1` for `XLSX.read` or `XLSX.readFile`
