### ISSUE TITLE
Not able to read a XLSB file. Error: Unexpected record 18

### ISSUE THREAD

**Issue by leobastiani** [SheetJS/sheetjs#2172]
I'm trying to read this XLSB file attached.
I'll add the error and the code base to reproduce locally.

https://github.com/leobastiani/sheetjs-issue-2172/raw/main/wb.xlsb
https://github.com/leobastiani/sheetjs-issue-2172/

```
/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:20596
        } catch(e) { if(opts.WTF) throw e; }
                                  ^

Error: Unexpected record 18
    at ws_parse (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:14474:38)
    at recordhopper (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:3517:6)
    at parse_ws_bin (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:14262:2)
    at parse_ws (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:15558:37)
    at safe_parse_sheet (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:20570:25)
    at parse_zip (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:20727:3)
    at read_zip (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:20948:9)
    at readSync (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:21014:69)
    at Object.readFileSync (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/node_modules/xlsx/xlsx.js:21028:9)
    at Object.<anonymous> (/mnt/c/Users/Leonardo/Desktop/XLSX-issue/Node/index.js:5:17)
```

**Comment by leobastiani** [comment]
Updating `aspose-cells` to 20.9 solves the problem, although I need to run o version 17.11

**Comment by SheetJSDev** [comment]
Thanks for reporting!  The spec https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsb/30e2eaae-0b1e-4e8e-a465-e1ce5575868d does not specify a record for type 18.

This opens up in Excel 2019 so Excel clearly handles this correctly.  Assuming you still have access to the tool that made the file, can you create a worksheet that looks like

|A|B|C|
|-|-|-|
A1|B1|C1
A2|B2
A3||C3
A4|B4|123
A5|234
345|B6|C6

**Comment by leobastiani** [comment]
Sure!!
Same error :C

https://github.com/leobastiani/sheetjs-issue-2172/raw/issuecomment-724951437/wb.xlsb
https://github.com/leobastiani/sheetjs-issue-2172/tree/issuecomment-724951437

**Comment by leobastiani** [comment]
> Thanks for reporting! The spec https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsb/30e2eaae-0b1e-4e8e-a465-e1ce5575868d does not specify a record for type 18.
> 
> This opens up in Excel 2019 so Excel clearly handles this correctly. Assuming you still have access to the tool that made the file, can you create a worksheet that looks like
> 
> A	B	C
> A1	B1	C1
> A2	B2	
> A3		C3
> A4	B4	123
> A5	234	
> 345	B6	C6

Also works in Excel 2010 on my Windows 10

**Comment by leobastiani** [comment]
Just a clue for you

**Comment by leobastiani** [comment]
Just a clue for you, this is the changelog of version 20.9 in which aspose starts to generate a valid xlsb file for reading.
https://docs.aspose.com/cells/java/aspose-cells-for-java-20-9-release-notes/

Here is the same file generated in version 20.9
https://github.com/leobastiani/sheetjs-issue-2172/raw/safe-xlsb/wb.xlsb

**Comment by SheetJSDev** [comment]
This is fascinating.  Even though it isn't documented in the spec, it looks like record type 18 specifies a string cell with an implicit column index.  `BrtCellIsst` has the following layout:

    column index (4 bytes)
    style index (3 bytes)
    flags (1 byte)
    shared string table index (4 bytes)

It looks like this record is an optimization when you have data in adjacent cells:

    style index (3 bytes)
    flags (1 byte)
    shared string table index (4 bytes)

It's implied that the column index is 1 more than the previous index.


It also looks like record type 16 is the equivalent of `BrtCellReal`.


If the pattern follows, type 15 would be the equivalent for `BrtCellBool` and type 14 would be the equivalent for `BrtCellError`.  Can you test that with something like

|A|B|C|
|-|-|-|
true|true|false
true|#NUM!|#VALUE!
#NUM!|true|false

(you can replace the errors with other error types)

**Comment by leobastiani** [comment]
You might be right!!
The new error is:
```
/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:20596
        } catch(e) { if(opts.WTF) throw e; }
                                  ^

Error: Unexpected record 15
    at ws_parse (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:14474:38)
    at recordhopper (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:3517:6)
    at parse_ws_bin (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:14262:2)
    at parse_ws (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:15558:37)
    at safe_parse_sheet (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:20570:25)
    at parse_zip (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:20727:3)
    at read_zip (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:20948:9)
    at readSync (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:21014:69)
    at Object.readFileSync (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/node_modules/xlsx/xlsx.js:21028:9)
    at Object.<anonymous> (/mnt/c/Users/Leonardo/Desktop/sheetjs-issue-2172/Node/index.js:5:17)
```

https://github.com/leobastiani/sheetjs-issue-2172/raw/issuecomment-724984833/wb.xlsb

**Comment by SheetJSDev** [comment]
You exported the string `=#NUM!` and `=#VALUE!`, but that's ok we can hand-craft some samples with error values.

**Comment by leobastiani** [comment]
I'm sorry, how should it look like?
https://github.com/leobastiani/sheetjs-issue-2172/blob/0839721f544eefab64caf4b2e4a9cea411895ab6/Java/src/main/java/Generator.java#L16-L18

**Comment by SheetJSDev** [comment]
Like this: [issue2172_error_cells.xlsx](https://github.com/SheetJS/sheetjs/files/5520670/issue2172_error_cells.xlsx)

**Comment by leobastiani** [comment]
Could you try now?
https://github.com/leobastiani/sheetjs-issue-2172/raw/issuecomment-724984833/wb.xlsb

**Comment by SheetJSDev** [comment]
You generated the correct type of file this time :) Curiously it always generates the traditional `BrtCellError` cells.  So it looks like the cases we need to cover for now are strings (18), doubles (16) and booleans (15)

**Comment by leobastiani** [comment]
Thank you! But I'm sorry I won't be able to implement the functionality

**Comment by leobastiani** [comment]
I just realized you were totally right.
This package added the option to export all indexes of columns that by default became true.

https://docs.aspose.com/cells/java/aspose-cells-for-java-20-9-release-notes/
See "Adds XlsbSaveOptions.ExportAllColumnIndexes property."

Here is a repository to reproduce the error using this property
https://github.com/leobastiani/sheetjs-issue-2172/tree/export-all-column-indexes
https://github.com/leobastiani/sheetjs-issue-2172/raw/export-all-column-indexes/wb-safe.xlsb
https://github.com/leobastiani/sheetjs-issue-2172/raw/export-all-column-indexes/wb-unsafe.xlsb

Would you have any time to solve this problem? I'll be very grateful. Thank you 🤗

**Comment by leobastiani** [comment]
@SheetJSDev Just a friendly reminder here 💌

**Comment by leobastiani** [comment]
@SheetJSDev Could you please give a feedback? 🙏
Do you have any plans for it? Or would you accept a PR?

**Comment by SheetJSDev** [comment]
0.17.1 adds support for reading/writing all of the short records and defaults to writing short records.

GitHub does not accept XLSB issue attachments [so we collected notes for future reference](https://oss.sheetjs.com/notes/xlsb/)

It appears Excel has a short form for each of the main cell types.

[`brt_sst.xlsb`](https://github.com/SheetJS/notes/raw/main/xlsb_short_records/brt_sst.xlsb) includes the 5 non-string types as well as the string type using the shared string table

[`brt_str.xlsb`](https://github.com/SheetJS/notes/raw/main/xlsb_short_records/brt_str.xlsb) includes the 5 non-string types as well as the string type using the inline string form
