### ISSUE TITLE
sheet_to_json  read excel ,the date format is wrong

### ISSUE THREAD

**Issue by yikouning** [SheetJS/sheetjs#2173]
Hello, when reading excel tables using sheet_to_JSON, I found that the date-format data was changed to Numbers. When looking at the source code, I found that sheet_to_JSON called make_json_row and found a question. Please look at the picture
![微信图片_20201117135117](https://user-images.githubusercontent.com/45613555/99351672-0fec6980-28dc-11eb-9d13-860cfa9023ba.jpg)
![QQ截图20201117134647](https://user-images.githubusercontent.com/45613555/99351684-17137780-28dc-11eb-8d30-28445bd82127.png)
Why is var v = val. v ; Instead of var v = val. w
 thank you very much

**Comment by revenue-nikhil-sharma** [comment]
Use XLSX.utils.sheet_to_json(worksheet, { raw: false });

i.e. raw: false, it will format the data accordingly

**Comment by evanVerinomics** [comment]
I ran into this same issue, has anyone figured this one out?

**Comment by SheetJSDev** [comment]
In the future, note that you can link to rows in GitHub by clicking on the row number in the GH view.  For example, https://github.com/SheetJS/sheetjs/blob/master/xlsx.flow.js#L21522 is the current line.

The emitted value depends on the `raw` option.  The default is `raw: true`, which means the underlying value is returned.  [The formatted string (`w` property) is only returned if `raw` is false, logic integrated in `format_cell`](https://github.com/SheetJS/sheetjs/blob/master/xlsx.flow.js#L21535)

[`format_cell` will return the cell's `w` property if it is defined.  If it is not, then it will look for a cell format (`z` property).  The code is pretty straightforward](https://github.com/SheetJS/sheetjs/blob/master/xlsx.flow.js#L3823)

**Comment by yikouning** [comment]
Thank you very much for your reply. After I got the result, I reorganized it and the problem has been solved
