### ISSUE TITLE
Sheet names cannot exceed 31 chars

### ISSUE THREAD

**Issue by Shuo8989** [SheetJS/sheetjs#2174]
hi，my fland，this error:【Sheet names cannot exceed 31 chars】 is just in excel's worksheet，not fileName

**Comment by SheetJSDev** [comment]
You cannot create a worksheet in Excel with more than 31 characters, hence the error.  The check is performed on each worksheet name.  File name is not validated since those limits are dictated by the filesystem and we cannot determine that info.
