### ISSUE TITLE
Cannot find module 'xlsx' 

### ISSUE THREAD

**Issue by harkeshkumar3** [SheetJS/sheetjs#2175]
Am getting this while making build using jenkins on build server but i am trying this on local machine then it working fine with error 

15:07:39              "", 
15:07:39              "", 
15:07:39              "", 
15:07:39              "ERROR in src/services/excel.service.ts:2:23 - error TS2307: Cannot find module 'xlsx'.", 
15:07:39              "", 
15:07:39              "2 import * as XLSX from 'xlsx';", 
15:07:39              "                        ~~~~~~"
15:07:39          ], 

Steps use to SheetJs

install xlsx using npm install xlsx.

And import xlsx module. import * as XLSX from 'xlsx';

**Comment by SheetJSDev** [comment]
Are you sure the module is installed and added as a dependency in your package.json?  The error suggests that your build server may not be doing the install.  Please try building [the `electron` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/electron) locally and in your build setup and reopen the issue if it doesn't work
