### ISSUE TITLE
Bold is not interpreted properly while reading a cell data.

### ISSUE THREAD

**Issue by i-am-anil** [SheetJS/sheetjs#2178]
![image](https://user-images.githubusercontent.com/68899690/99628177-a5623780-2a5b-11eb-89b7-a0b690515d3a.png)

I am trying to parse a excel cell but if the initial characters are bold/italic/underline the HTML tags are not getting parsed as shown in the snapshot below (look at the text marked with red color "Some notes in bold") , they are not enclosed in <b> tag.

![image](https://user-images.githubusercontent.com/68899690/99628438-2faa9b80-2a5c-11eb-841c-34ee78b56fe0.png)

**Comment by SheetJSDev** [comment]
More detailed styling is supported in our [Pro builds](https://sheetjs.com/pro).  As for the rich text, that is the raw representation in the XLSX file.  Excel will actually set the cell's text style based on the first character, so the cell style likely is marked as bold.
