### ISSUE TITLE
Unminified full script

### ISSUE THREAD

**Issue by Miqueliu** [SheetJS/sheetjs#2182]
In `dist` directory, there is the `xlsx.full.min.js` script (that is defined as main source in Bower specifications). But... Why there is not a unminified code of this? My final project is failing because of a double minification process!

**Comment by SheetJSDev** [comment]
The build sequence runs as follows:

0) the embedded version number and CFB library are updated as appropriate

1) all of the scripts in the `bits` folder are concatenated in numeric order to produce the `xlsx.flow.js` script in the base of the repo

2) the flow comments are stripped out to produce `xlsx.js`

3) `uglifyjs` is given a few scripts that are combined to produce `xlsx.full.min.js`

That intermediate "unminified" version is not generated explicitly.  The following command should generate a rough equivalent using files in the source tree:

```bash
cat <(head -n 1 bits/00_header.js) misc/suppress_export.js jszip.js dist/cpexcel.js dist/xlsx.js
```

Your build sequence should not be failing as a result of the minified bower entrypoint.  I would dig into the error further and see if there's an option you can pass to one of the tools.

**Comment by Miqueliu** [comment]
It would be very useful if you put this among the accessible files. In this way, we only need to override the `main` property of Bower.

And even more: You can put this unminified file as the entry-point file. In fact, the [official specification of Bower about `main`](https://github.com/bower/spec/blob/master/json.md#main) clearly says: **"Do not include minified files"**. And e.g. this is how both [Bootstrap](https://github.com/twbs/bootstrap/blob/v3-dev/bower.json#L17) and [AngularJS](https://github.com/angular/bower-angular/blob/master/bower.json#L5) do.

Provisionally, I'm writing in my `bower.json`:
```
"overrides": {
  "js-xlsx": {
    "main": [
      "jszip.js",
      "dist/cpexcel.js",
      "dist/xlsx.js"
    ]
  }
}
```

(`misc` directory is not there).
