### ISSUE TITLE
Error from data in excel

### ISSUE THREAD

**Issue by jlmejia21** [SheetJS/sheetjs#2183]
I have a problem with excel, when i exported data from table html to xls, excel file show the correcta data but when i want to try reading it, it's imposible because it added another character
Example:
 01  => ?01

It's in all the cells, i see because i have to conver xls to csv otherwise i cant see it.

**Comment by jlmejia21** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20684443/100118112-855bbb00-2e43-11eb-8f46-0492edb80439.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20684443/100118116-868ce800-2e43-11eb-928d-de35db4df95b.png)

**Comment by SheetJSDev** [comment]
Is there a non-display unicode character in the original HTML table?  If you can share the original table, we can take a closer look.

**Comment by reviewher** [comment]
Please share the original table and the issue will be reopened
