### ISSUE TITLE
autofilter not working

### ISSUE THREAD

**Issue by likemike90** [SheetJS/sheetjs#2185]
Hey guys .

i have troubles to enable the autofilter option in my workbook. Ill export an HTML Table to an xlsx Document. Everythings worksfine, but i try to automate somethings like to set automatically the autofilter option. Ive readed some Posts and worked out something like this :

`
        var wb = XLSX.utils.table_to_book(document.getElementById('mytable'), {sheet:"Sheet JS"});
        var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});
        
        wb['!autofilter'] = { ref:"A2:D4" };
        

        function s2ab(s) {

                        var buf = new ArrayBuffer(s.length);
                        var view = new Uint8Array(buf);
                        for (var i=0; i<s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                        return buf;
        }
        $("#button-a").click(function(){
        saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), 'tes2t.xlsx');
        });
`

But i dont get it to work ? What do i missing here ? 

Thanks for your Time and Help

**Comment by likemike90** [comment]
anyone have a solution ?

**Comment by davemeadowcroft** [comment]
You need to add the autofilter to the worksheet, not the workbook.

**Comment by reviewher** [comment]
As @davemeadowcroft mentioned, autofilter properties apply to a worksheet object
