### ISSUE TITLE
Defined Names for Tables

### ISSUE THREAD

**Issue by firig** [SheetJS/sheetjs#2186]
I cannot find **Defined Names** for **Tables** in the import from xlsx files.
In **Workbook.Names** I can find Defined Names for single cells and for ranges of cells, but not for Tables.
Am I missing something, please?

**Comment by SheetJSDev** [comment]
The library pulls from the defined name list in the file.  Table names are not stored in that list.  Excel collects a list of the table names when you open the file, and it would complicate the export and other features if we created a synthetic entry for each table.

Our [Pro compendium](https://sheetjs.com/pro) includes support for extracting table metadata including the name.  It doesn't create fake name entries, but it exposes enough info to write the logic.  We use it in an integrity check to ensure that all defined names are valid
