### ISSUE TITLE
OOM in npm when compiling

### ISSUE THREAD

**Issue by lzio** [SheetJS/sheetjs#2187]
![image](https://user-images.githubusercontent.com/20417764/100175099-b94ce400-2f08-11eb-8368-466a026c520d.png)
Vue+Webpack:
First step: npm i xlsx
Second step: import * as XLSX from 'xlsx'
Third step:console.log(XLSX)
Result:Garbled code and out of memories,then compiling shut down

**Comment by SheetJSDev** [comment]
Did you use a project starter like create-vue-app or @vue/cli?  So that we can reproduce, which one?

**Comment by lzio** [comment]
> Did you use a project starter like create-vue-app or @vue/cli? So that we can reproduce, which one?
Yes, i used vue-cli in this project

**Comment by lzio** [comment]
![image](https://user-images.githubusercontent.com/20417764/100189885-28860080-2f28-11eb-87f5-cf09801e35bb.png)

**Comment by SheetJSDev** [comment]
```bash
$ npm i -g @vue/cli
$ vue create issue2187
### Choose "Default"
$ cd issue2187
$ npm i --save xlsx
$ sed -i.bak 's/<script>/<script>import * as XLSX from "xlsx"; console.log(XLSX)/g' src/components/HelloWorld.vue
$ npm run build
$ npm run serve
```

Cannot reproduce the crash.  If you can share a sample project, we can take a closer look.
