### ISSUE TITLE
Add addCellToSheet function to utils

### ISSUE THREAD

**Issue by raphaelschwinger** [SheetJS/sheetjs#2190]
@reviewher `s [comment](https://github.com/SheetJS/sheetjs/issues/462#issuecomment-288279673) is perfect!
Why is this function not part of the xlsx module?

_Originally posted by @hiob10hiob in https://github.com/SheetJS/sheetjs/issues/462#issuecomment-737147998_

**Comment by reviewher** [comment]
Thanks for the compliment :) `sheet_add_aoa` encapsulates the logic.  The comment will be updated to use the API function
