### ISSUE TITLE
Minification in Bower files

### ISSUE THREAD

**Issue by mvicens** [SheetJS/sheetjs#2191]
Since it seems to be that [SheetJSDev](https://github.com/SheetJSDev) [ignored me](https://github.com/SheetJS/sheetjs/issues/2182#issuecomment-733537774) and the trouble is important, I reopen [the issue](https://github.com/SheetJS/sheetjs/issues/2182).

The point is that Bower says ([about `main` property](https://github.com/bower/spec/blob/master/json.md#main)) **"Do not include minified files"** and [this library](https://github.com/SheetJS/sheetjs) precisely [does the opposite](https://github.com/SheetJS/sheetjs/blob/20212e1cc222b047d7414d21428c611508c33a67/bower.json#L4) and offers only minified useful files.

**Comment by reviewher** [comment]
27c457be99da41470d3acb0cfe28d3c96df01e82 pulled a change from an older PR, please reopen if the issue persists.
