### ISSUE TITLE
cell format as percentage

### ISSUE THREAD

**Issue by akanksha033** [SheetJS/sheetjs#2192]
Can I define the format of a cell as percentage while writing an xlxs file?

**Comment by SheetJSDev** [comment]
Yes, set the `z` field of the relevant cell to `"0%"` for integral percentage and `"0.00%"` for 2 digit decimal.  There's an example at https://github.com/SheetJS/sheetjs#number-formats :

```js
var wb = {
  SheetNames: ["Sheet1"],
  Sheets: {
    Sheet1: {
      "!ref":"A1:C1",
      A1: { t:"n", v:10000 },                    // <-- General format
      B1: { t:"n", v:10000, z: "0%" },           // <-- Builtin format
      C1: { t:"n", v:10000, z: "\"T\"\ #0.00" }  // <-- Custom format
    }
  }
}
```
