### ISSUE TITLE
Get sheet names without reading entire file

### ISSUE THREAD

**Issue by grr24** [SheetJS/sheetjs#2193]
I am trying to get only the sheet name from an uploaded file. It works fine for small excel files. But for larger files, it is taking too long and the page is not responding.

Below is my code for getting sheet names.

function Getsheets(e) {
            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.xlsx|.xls)$/;
            /*Checks whether the file is a valid excel file*/
            if (regex.test($("#excelfile").val().toLowerCase())) {
                var xlsxflag = false; /*Flag for checking whether excel is .xls format or .xlsx format*/
                if ($("#excelfile").val().toLowerCase().indexOf(".xlsx") > 0) {
                    xlsxflag = true;
                }
                /*Checks whether the browser supports HTML5*/
                if (typeof (FileReader) != "undefined") {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var data = e.target.result;
                        /*Converts the excel data in to object*/
                        if (xlsxflag) {
                            var workbook = XLSX.read(data, { type: 'binary' });
                        }
                        else {
                            var workbook = XLS.read(data, { type: 'binary' });
                        }
                        /*Gets all the sheetnames of excel in to a variable*/
                        var sheet_name_list = workbook.SheetNames;

                        BindSheetNames(sheet_name_list, '#ddlSheet');

                    }
                    if (xlsxflag) {/*If excel file is .xlsx extension than creates a Array Buffer from excel*/
                        reader.readAsArrayBuffer($("#excelfile")[0].files[0]);
                    }
                    else {
                        reader.readAsBinaryString($("#excelfile")[0].files[0]);
                    }
                }
                else {
                    alert("Sorry! Your browser does not support HTML5!");
                }
            }
            else {
                alert("Please upload a valid Excel file!");
            }
        }
 }

Is it possible to get the sheet names in the file without reading the entire file ?

Thanks

**Comment by reviewher** [comment]
`bookSheets` option https://docs.sheetjs.com/#parsing-options

>  If true, only parse enough to get the sheet names
