### ISSUE TITLE
Cannot find file [Content_Types].xml in zip     at getzipfile (xlsx.js:2928)

### ISSUE THREAD

**Issue by FBRL** [SheetJS/sheetjs#2194]
I am trying to use sheetjs **without jszip** and run into the error mentioned in the title with different excel files and different test bench configuration.

My current test bench is:
```<!DOCTYPE html>

<html>
<head>
<script src="jquery-2.1.4.js"></script>
<script lang="javascript" src="xlsx.js"></script>
</head>
<body>
<div id="navbar"><span>test rig</span></div>
<div id="wrapper">
        
        <input type="file" id="input-excel" />
</div>
<script>
        $('#input-excel').change(function(e){
                var reader = new FileReader();
                reader.readAsArrayBuffer(e.target.files[0]);
                reader.onload = function(e) {
                        var data = new Uint8Array(reader.result);
                        var wb = XLSX.read(data,{type:'array'});
                        var htmlstr = XLSX.write(wb,{sheet:"sheet no1", type:'binary',bookType:'html'});
                        $('#wrapper')[0].innerHTML += htmlstr;
                }
        });
</script>
</body>
</html>
```

When trying to read the xlsx file, the problem seems to arise in:

```
function safegetzipfile(zip, file) {
	var k = zip.FullPaths || keys(zip.files);
	var f = file.toLowerCase(), g = f.replace(/\//g,'\\');
	for(var i=0; i<k.length; ++i) {
		var n = k[i].toLowerCase();
		if(f == n || g == n) return zip.files[k[i]];
	}
	return null;
}
```

In my situation,

- the variable `zip `has a field `FullPaths` but does not contain any field '.files'

- `k` is an array containing : 

```
0: "Root Entry/"
1: "Root Entry/Sh33tJ5"
2: "Root Entry/[Content_Types].xml"
3: "Root Entry/_rels/.rels"
4: "Root Entry/xl/_rels/workbook.xml.rels"
5: "Root Entry/xl/workbook.xml"
6: "Root Entry/xl/sharedStrings.xml"
7: "Root Entry/xl/theme/theme1.xml"
8: "Root Entry/xl/styles.xml"
9: "Root Entry/xl/worksheets/sheet1.xml"
10: "Root Entry/docProps/core.xml"
11: "Root Entry/docProps/app.xml"
```

- `f` contains `[content_types].xml`

When running thru the loop:

- the condition `f == n || g == n` never comes true because it tries to compare `"[content_types].xml"` with  `"Root Entry/[Content_Types].xml"`
- even if the condition was true, it will return an error because `zip.files` does not exist and can't be returned.

I am kindly asking for help on how to solve this situation. Thanks in advance for your reply

**Comment by Manasi-ui** [comment]
I tried the above fix. I'm using xlsx version 0.17.0, React version 17.0.2. And trying to read a simple xlsx workbook on handleChange. I was getting Error: Cannot find file [Content_Types].xml in zip at getzipfile (xlsx.js:2928). So I tried the above import. However It is now giving me following error:
Uncaught Error: Cannot find file [Content_Types].xml in zip
    at ke (xlsx.full.min.js:12)
    at Ee (xlsx.full.min.js:12)
    at Rg (xlsx.full.min.js:23)
    at Ng (xlsx.full.min.js:23)
    at Object.Wg [as read] (xlsx.full.min.js:23)

**Comment by CalmHarbin** [comment]
引入xlsx.min.js，读取xlsx文件时就会有这个报错，我换成了xlsx.core.min.js或者xlsx.full.min.js都可以解决这个问题。

**Comment by CalmHarbin** [comment]
引入xlsx.min.js，读取xlsx文件时就会有这个报错，我换成了xlsx.core.min.js或者xlsx.full.min.js都可以解决这个问题。

**Comment by reviewher** [comment]
ef4aec8796c72dc891b619edcd3ef24dde4829d6 should have resolved the issue, please comment here if it still persists and we will reopen the issue
