### ISSUE TITLE
Crashes with different weird errors

### ISSUE THREAD

**Issue by Ploppz** [SheetJS/sheetjs#2200]
Reproducible test case (I hope, unless it's something wrong with my XLSX file, which I unfortunately cannot share): https://codesandbox.io/s/react-dropzone-forked-4ys9u?file=/src/index.js

NOTE: Press the text to get a file selector and select an XLSX file.
Once I select an XLSX file, for me it always causes the React app to become unresponsive until it throws some error
In my local application I got different errors...:

- a few Out of memory errors
- a React error "Should not already be working" (which apparently indicates a bug in React..)

Then in the sandbox I get a completely different error:
```
make_EE@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8234:42
make_sbcs_encode@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8259:23
encache@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8760:25
evaluate/<@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8821:3
evaluate/<@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8170:20
evaluate@https://4ys9u.csb.app/node_modules/xlsx/dist/cpexcel.js:8175:3
z@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98419
evaluate@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:110544
evaluateTranspiledModule@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:120123
c@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:110289
make_xlsx_lib@https://4ys9u.csb.app/node_modules/xlsx/xlsx.js:12:54
evaluate@https://4ys9u.csb.app/node_modules/xlsx/xlsx.js:21706:49
z@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98419
evaluate@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:110544
evaluateTranspiledModule@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:120123
c@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:110289
evaluate@https://4ys9u.csb.app/src/index.js:13:36
z@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98419
evaluate@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:110544
evaluateTranspiledModule@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:120123
evaluateModule@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:119859
e/<@https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:809668
l@https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257407
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257161
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257764
t@https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2617
```

Along with two other errors stemming from codesandbox code itself apparently but I don't think they add much at this point.

**Comment by SheetJSDev** [comment]
Can you test by dragging-and-dropping into https://oss.sheetjs.com/ ?  This skips all of the potential issues with codesandbox

**Comment by Ploppz** [comment]
Works fine there. Note that I get errors locally in my React app too, not just codesandbox. Does my code look fine?
I checked again locally and it basically always gives Out of memory errors. But the xlsx file is only 42KiB with 51 rows and 6 columns of information. I don't understand that it should be anything but a swift operation to parse this. Must be some interaction with React, but I can't tell what's wrong...

**Comment by SheetJSDev** [comment]
Browser `ReadableStream` is not currently supported.  Use `File#arrayBuffer` to grab the data:

```js
    console.log("Reading");
    let data = file.arrayBuffer();
    console.log("Parsing");
    data.then((ab) => {
      let workbook = XSLX.read(ab, { type: "array" });
      console.log("Parsed");
      // do something with workbook here
      console.log(workbook.SheetNames);
    });
```
