### ISSUE TITLE
export excel which formated as xls don't work, bookType: biff8, help!!!

### ISSUE THREAD

**Issue by anjina** [SheetJS/sheetjs#2201]
```javascript

// XLSX  version 0.16.9   node version 12.16.2

const XLSX = require('xlsx')
const workbook = {
  SheetNames: 'TEST',
  Sheets: {
    'TEST': { A1: 123, B1: '333', '!ref': 'A1:B1'}
  }
}

XLSX.writeFile(workbook, 'a.xls', {
  bookType: 'biff8',
  bookSST: false,
  type: 'binary',
});
```

this demo code above,  which export a empty excel .

**Comment by SheetJSDev** [comment]
`SheetNames` should be an array and each key in the sheet object is supposed to be a cell object https://docs.sheetjs.com/#cell-object

The correct way to represent what you want is:

```js
const XLSX = require('xlsx');

const workbook = {
  SheetNames: [
    'TEST'
  ],
  Sheets: {
    'TEST': {
      A1: { t: "n", v: 123 },
      B1: { t: "s", v: '333' },
      '!ref': 'A1:B1'
    }
  }
};

XLSX.writeFile(workbook, 'a.xls', {
  bookType: 'biff8',
  bookSST: false,
  type: 'binary',
});


```

**Comment by anjina** [comment]
> `SheetNames` should be an array and each key in the sheet object is supposed to be a cell object https://docs.sheetjs.com/#cell-object
> 
> The correct way to represent what you want is:
> 
> ```js
> const XLSX = require('xlsx');
> 
> const workbook = {
>   SheetNames: [
>     'TEST'
>   ],
>   Sheets: {
>     'TEST': {
>       A1: { t: "n", v: 123 },
>       B1: { t: "s", v: '333' },
>       '!ref': 'A1:B1'
>     }
>   }
> };
> 
> XLSX.writeFile(workbook, 'a.xls', {
>   bookType: 'biff8',
>   bookSST: false,
>   type: 'binary',
> });
> ```

thank you very much, I got it !!
