### ISSUE TITLE
set column width in json_to_sheet

### ISSUE THREAD

**Issue by peppeg85** [SheetJS/sheetjs#2202]
hello, as the title sais, how can i set an auto column with to fit the max conent of the cell?
thank you

**Comment by chriseikrem** [comment]
Highly interested in this aswell!

**Comment by ugrdursun** [comment]
I am also interested

**Comment by MezzogoriNatisoft** [comment]
Me too

**Comment by zhuiluo0987** [comment]
ws['!cols'] = [{wch: 18},{wch: 18},{wch: 18}] 以此类推。每一列的宽度

**Comment by candy4290** [comment]
> ws['!cols'] = [{wch: 18},{wch: 18},{wch: 18}] 以此类推。每一列的宽度
i use like this, but it does not work!
const sheet2 = XLSX.utils.json_to_sheet(trafficSheetData);
sheet2['!cols'] = [{wch: 18},{wch: 18},{wch: 18},{wch: 18},{wch: 18},{wch: 18}]

**Comment by reviewher** [comment]
What @zhuiluo0987 said.  You also need to write with the option `cellStyles: true`

**Comment by awaism551** [comment]
`ws['!cols'] = [{wch: 18},{wch: 18},{wch: 18}]`
thats not an auto column width which was asked in a question, its fixed length @reviewher @zhuiluo0987
