### ISSUE TITLE
UTF-8 , how to read chinese excel ?

### ISSUE THREAD

**Issue by Oscarwang666** [SheetJS/sheetjs#2203]
Hi , anyone know how do I read chinese characters from excel when using " XLSX.read()" ? 

```
var data = e.target.result;
          let readedData = XLSX.read(data, {type: 'binary',blankRows: false,cellDates: true, cellNF: false, cellText: false});
          const wsname = readedData.SheetNames[0];
          const ws = readedData.Sheets[wsname];
```

**Comment by SheetJSDev** [comment]
Can you share the original file?  Older excel formats use a different representation for chinese characters

**Comment by Oscarwang666** [comment]
@SheetJSDev Thank you for reply ! and sorry for not making my question clear

link to the excel : https://drive.google.com/file/d/1AvZWwL6u7yyN_vof-hVTi6gqGfz-bp6R/view?usp=sharing

I created the excel file on flyusing the following javascript :
```
let chiness = [ ["姓", "名", "性別", "年级", "出生年月", "监护人姓", "监护人名", "监护人邮箱", "监护人电话","国家"],
                     ["張", "三", "male", "2", "1995-11-26", "張", "爸爸", "parenet@gmail.com", "13888889999", "china"],];
                   const arrayToCsv = function (rows) {
                     let csvContent = "data:text/csv;charset=utf-8,\uFEFF" + rows.map(e => e.join(',')).join('\n')
                     let encodedUri = encodeURI(csvContent)
                     let link = document.createElement("a")
                     link.setAttribute("href", encodedUri)
                     link.setAttribute("download", "excel.csv")
                     document.body.appendChild(link)
                     link.click()
                   } 
```
I realized that i have to include "utf-8,\uFEFF" when generating the excel file so the Chinese characters will be display correctly when the user downloads and open the file. The problem for me is I can't read the Chinese character properly after they finsih editing and upload the same file to me.

Also is this a good way to generating excel ? what is the better way when dealing with older chiense format ? thank you very much !

**Comment by SheetJSDev** [comment]
https://oss.sheetjs.com/ can you check if it works here?  To test, open this page in your browser and click-drag the file into the window.

It appears to parse correctly in nodejs as well.

To be sure we're looking at the same file, can you click and drag your file into the box at https://oss.sheetjs.com/js-crc32/ ?  Below the screen you will see the computed crc32.  the downloaded file reports `29336257` (hex `01bfa2c1`)

**Comment by Oscarwang666** [comment]
it works on https://oss.sheetjs.com/ and https://oss.sheetjs.com/js-crc32

Result from https://oss.sheetjs.com/js-crc32 :
Signed    : 29336257
Unsigned  : 29336257
Hex value : 01bfa2c1

![](https://i.imgur.com/b2lEAIO.png)
![](https://i.imgur.com/oo1UNRx.png)

**Comment by SheetJSDev** [comment]
Your screenshot is showing a different checksum. Are you sure we're looking at the same file?  Just email it to dev@sheetjs.com

**Comment by Oscarwang666** [comment]
sorry for that , this is the correct one. 
![](https://i.imgur.com/g6ZYyq9.png)

**Comment by SheetJSDev** [comment]
Can you `console.log(data)` from your site and share the result (take a screenshot of the console)?  If it is working on the official demo but not in your site, it might be an integration issue.

**Comment by Oscarwang666** [comment]
There is the two versions: 
(1).  if I dont edit the file then chinese display correctlly 
![](https://i.imgur.com/fFArPXA.png)
(2). .  if i do edit the file and save it as either text/CSV or ODF 
![](https://i.imgur.com/1sh0LRq.png) 


console.log for (1)
![](https://i.imgur.com/y8BwBkm.png)

console.log for (2)
![](https://i.imgur.com/TOfr7yh.png)


I guess the problem is from the read() function not the on fly download js code.

**Comment by SheetJSDev** [comment]
If you're modifying the workbook object and saving, can you use `XLSX.writeFile`?  `XLSX.write` will not include the CSV UTF8 BOM

**Comment by Oscarwang666** [comment]
so where should i use the XLSX.writeFile ? since i was using the 
`let readedData = XLSX.read(data, {type: 'binary',blankRows: false,cellDates: true, cellNF: false, cellText: false});`

![](https://i.imgur.com/IN2bzUZ.png)

**Comment by SheetJSDev** [comment]
It's still unclear where that error message is coming from.

If you're editing the file using SheetJS, then you will be calling `write` or `writeFile` somewhere in your code.

If LibreOffice is opening the file and it looks good, but is giving you an error when you try to edit the file, it is probably a bug with LibreOffice.  Their bugtracker is https://bugs.documentfoundation.org/

**Comment by Oscarwang666** [comment]
Ok ! and i was not editing the file by SheetJS , indead , i was reading the file from SheetJS.

**Comment by Oscarwang666** [comment]
I found an airticle about this type of issue (reading chinese utd-8 from excel) but i dont quite understand whats goinig on 
https://www.jianshu.com/p/439fbc4a11a8 
they use the same website  (https://oss.sheetjs.com/sheetjs/) 
would you mind having a look ?

**Comment by SheetJSDev** [comment]
That is an unrelated issue.  When the CSV file does not contain a BOM, Excel defaults to windows CP1252 in the US (and a default codepage in other countries).  We always force 1252, and the `codepage` option lets you control the implied codepage (e.g. 936 for Simplified Chinese).

Summarizing, it looks like LibreOffice cannot handle CSV files with chinese characters.  Please raise an issue with them, and feel free to share a link and we can try to follow up

**Comment by Oscarwang666** [comment]
ok thank you so much for your help !
