### ISSUE TITLE
Can we apply styling in json_to_sheet and sheet_add_json

### ISSUE THREAD

**Issue by Anujkmrpal** [SheetJS/sheetjs#2205]
I want to apply style to my excel sheet like align center and border but didn't found any.

I am working like this.
xlsx.utils.json_to_sheet(arrayOfObject, { skipHeader: false, origin: 'A1' });

And I want something like below:'

xlsx.utils.json_to_sheet(arrayOfObject, { skipHeader: false, origin: 'A1' , align: 'center'});

Is there any way to do so

**Comment by SheetJSDev** [comment]
Cell styling is a feature of our [Pro builds](https://sheetjs.com/pro)
