### ISSUE TITLE
export excel keep table head

### ISSUE THREAD

**Issue by SilentFlute** [SheetJS/sheetjs#2207]
hello there,
i want to export excel from a json, i did it actually, but without table head, so i was wondering if u guys can help me
i const a variable:
```
      const res = [
        {
          'head1': 1,
          'head2': 2,
          'head3': 3
        },
        {
          'head1': 11,
          'head2': 22,
          'head3': 33
        }
      ]
```
and then use this lib to transform this data to workbook and generate a excel:
```
import XLSX from 'xlsx';
import moment from 'moment';

export const handleExportExcelFromJson = ({ jsonData, fileName }) => {
  const worksheet = XLSX.utils.json_to_sheet(jsonData);
  const workbook = {
    Sheets: {
      Sheet1: worksheet
    },
    SheetNames:['Sheet1']
  };
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });

  const extension = '.xlsx';

  const type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';

  const blob = new Blob([excelBuffer], { type });

  const currentTimeString = moment().format('YYYYMMDDHHmmss');

  const downloadUrl = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = downloadUrl;
  a.download = decodeURI(`${fileName}-${currentTimeString}${extension}`);
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.URL.revokeObjectURL(downloadUrl);
}
```
invoke this function:
```
handleExportExcelFromJson({ jsonData: res, fileName: 'myFile' });
```
it worked very well, i got a excel:
![image](https://user-images.githubusercontent.com/28900312/103267967-a9379100-49ed-11eb-9d4f-8b1ef910a410.png)
but without table head, if i create excel with office, it looks like this:
![image](https://user-images.githubusercontent.com/28900312/103268252-26630600-49ee-11eb-9eb6-a22880aad3ed.png)
a drop down arrow in the right, that indicates it's a table, and that cell is a table head!
and i tried to read excel file(with table head) get workbook, then use it to generate another excel directly, and new excel file still haven't table head at all, that confused me:
```
// a excel file from user
import XLSX from 'xlsx';
import moment from 'moment';

const reader = new FileReader();

reader.readAsBinaryString(file);

reader.addEventListener('load', e => {
  const res = e.target.result;

  const workbook = XLSX.read(res, { type: 'binary' });

  // just skip `XLSX.utils.json_to_sheet(jsonData)` generate workbook in `handleExportExcelFromJson`,
  // use upper workbook instead

  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });

  const extension = '.xlsx';

  const type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';

  const blob = new Blob([excelBuffer], { type });

  const currentTimeString = moment().format('YYYYMMDDHHmmss');

  const downloadUrl = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = downloadUrl;
  a.download = decodeURI(`myFile-${currentTimeString}${extension}`);
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.URL.revokeObjectURL(downloadUrl);

});
```
at the beginning, i doubt that may be the `workbook` is wrong in my code, like miss some fileds or some thing, but after i read a excel and use read `workbook` to generate anther excel directly, the new excel still haven't table head neither, i thougt may be it's not the `workbook` issue, but how? it means i can't generate a excel file with the table head?
i wish i can get some replies, thanks!

**Comment by SheetJSDev** [comment]
The depicted feature is Excel "Format as Table", which is not supported in the Community Edition but is a part of our [Pro builds](https://sheetjs.com/pro)
