### ISSUE TITLE
Missing FormControl Button

### ISSUE THREAD

**Issue by tchari** [SheetJS/sheetjs#2208]
I have an .xlsm file that contains a macro tied to a button. 

If I run the following:
```
const xlsx = require('xlsx');

const workbook = xlsx.readFile('./test.xlsm', { bookVBA: true });
xlsx.writeFile(workbook, './test_saved.xlsm');
```

and open test_saved.xlsm, the button is missing. The macro is still available but the button is gone.

Some simple steps to reproduce (in Office 2019)
1. Create a blank workbook
2. Add a button via Developer tab -> Insert. Click the button icon under Form Controls
3. Record whatever macro you want when you add the button
4. Save file as `test.xlsm`
5. Run the code above
6. Open `test_saved.xlsm`

I'd upload my `test.xlsm` if I could.

**Comment by SheetJSDev** [comment]
need to specify the option `bookVBA: true` on write:

```js
const xlsx = require('xlsx');

const workbook = xlsx.readFile('./test.xlsm', { bookVBA: true });
xlsx.writeFile(workbook, './test_saved.xlsm', { bookVBA: true });
```

**Comment by tchari** [comment]
> need to specify the option bookVBA: true on write

still does not work

**Comment by SheetJSDev** [comment]
email the file to dev@sheetjs.com

**Comment by david-siqi-liu** [comment]
hey @tchari , did you end up solving this issue?

**Comment by tchari** [comment]
No, I am using a different product/solution instead.

**Comment by SheetJSDev** [comment]
There are two types of controls in Excel:

- "ActiveX controls" are stored in the VBA blob and can be round-tripped by setting the `bookVBA` option on read and write

- "Form controls" are stored elsewhere and are currently supported in our Pro builds but not in the open source
