### ISSUE TITLE
Browser crashes with more than 200k records with 30 columns

### ISSUE THREAD

**Issue by chaksjs** [SheetJS/sheetjs#2211]
Is there any way I can select an excel file of 100MB size with almost 200k rows and 30 columns. I am using SheetJS and it show out of memory. Can anyone suggest, if anyone has tried the same?

I am using Filereader object, which is storing all the data in memory.

Below is the code snippet.
XLSX.read(data,{ type: 'array'});
Array=XLSX.utils.sheet_to_json(....);
reader.readAsArrayBuffer(file);

**Comment by chaksjs** [comment]
Bow is the code snippet.
XLSX.read(data,{ type: 'array'});
Array=XLSX.utils.sheet_to_json(....);
reader.readAsArrayBuffer(file);

**Comment by ajaychig** [comment]
Even I am looking for the same.
Below is my code snippet:

 ```
             var wb = XLSX.utils.book_new();
            const ws = XLSX.utils.json_to_sheet(data);
            XLSX.utils.book_append_sheet(wb, ws, "Sample");
            var wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'binary' });

                function s2ab(s) {
                    var buf = new ArrayBuffer(s.length);
                    var view = new Uint8Array(buf);
                    for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
                    return buf;
                  }
                   exportBlob = new Blob([s2ab(wbout)], { type: "application/octet-stream" });
                   saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), getFileName() + '.xlsx');
           }

```

Please suggest if there is any alternative or suggestion

**Comment by serv** [comment]
I've seen very similar problem where the process just hangs and never finishes. I had to say over 100,000 rows of data will be written with TSV creator rather than sheetjs.

**Comment by smile2014** [comment]
3000 row 150M

**Comment by reviewher** [comment]
Closing in favor of #61
