### ISSUE TITLE
!ref is irresponsible

### ISSUE THREAD

**Issue by chiaweilee** [SheetJS/sheetjs#2212]
We test a lot.
In some case, ['!ref'] is A1:J1 (actually not)
In another case, it's xx:D123456 (larger)

**Comment by SheetJSDev** [comment]
The `!ref` key is based on the file's self-reported range.  For XLSX it is the `<dimension>` tag.  For XLS it is the `Dimensions` record.  For XLSB it is the `BrtWsDim` record.  Many of the other formats have similar storage.

Some third party writers lean on Excel's automatic worksheet range recalculation.

If the range is wrong, it can be recalculated using the [`update_sheet_range` example](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions#updating-worksheet-range)
