### ISSUE TITLE
How to remove worksheet

### ISSUE THREAD

**Issue by vekonylaszlo** [SheetJS/sheetjs#2213]
I'm sorry if I missed something, but I can't find anything on how to remove a worksheet?
If somebody could help, i would appreciate it.

**Comment by jzav** [comment]
This approach seems to be working:
https://github.com/SheetJS/sheetjs/issues/1792

**Comment by pfouque06** [comment]
delete workbook.Sheets['your sheet name'] and XLSX.writeFile(workbook, filename) maybe ?

**Comment by SheetJSDev** [comment]
Removing from the `Sheets` object and the `SheetNames` array is sufficient for simple files.  For more advanced files, there are other structures like the workbook views that would need to be refreshed.  

https://github.com/SheetJS/sheetjs/issues/1792#issuecomment-596900842 is a starting point.
