### ISSUE TITLE
Number type conversion problem

### ISSUE THREAD

**Issue by manoger** [SheetJS/sheetjs#2221]
Hello.
Similar to issue #2214, I'm facing that numbers formatted with a comma before a dot mess with the value (Brazilian format).

### The problem:
Considering a simple csv
> T0;T1;T2
777;334.327,57;87.538.258,97

The behaviour is
* 777 turns into 777 number type (correct)
* 334.327,57      turns into 33,432,757 number type (incorrect)
* 87.538.258,97 turns into "87.538.258,97" string type (correct)

Number conversion is wrong. It just shifts decimal places ignoring my decimal separator. 
It's much better having it turned into a string than a wrong conversion.

In my project I've done a workaround to not get the workbook sheet field value by the property "v" when it's number type:
```js
let sheet = workbook.Sheets[workbook.SheetNames[i]];//given the example csv
let data=sheet[index];//at some cell (excluding the header)
if(data.t == "n") //when its number type
    row[columns[j]]=data.w; //gets the raw value
else
    row[columns[j]]=data.v; //get the converted value.
```

Please, I want to know if this behaviour will have a solution.

Thanks for your attention. I’m looking forward to your reply.

**Comment by SheetJSDev** [comment]
The issue, more broadly, is locale processing.  JavaScript and most programming languages follow the US convention of using `,` as the thousands separator and `.` as the decimal separator.  Europeans by and large flip the logic.

The larger "fix" is to add an option for locale supporting, something which is a bit tricky to handle across the browser support surface.  We do offer it as part of our [Pro offering](https://sheetjs.com/pro) as users have asked for it in the past.

As for the immediate problem, pass the option `raw: true` to `read` or `readFile`.  For example:

```js
// default behavior tries to parse value, yielding { t: 'n', w: '334.327,57', v: 334.32757 }
XLSX.read("T0;T1;T2\n777;334.327,57;87.538.258,97", {type: "string"}).Sheets.Sheet1.B2
// raw: true skips value parsing, yielding { t: 's', v: '334.327,57' }
XLSX.read("T0;T1;T2\n777;334.327,57;87.538.258,97", {type: "string", raw: true}).Sheets.Sheet1.B2
```
