### ISSUE TITLE
how to added bold to top row of Exported Sheet

### ISSUE THREAD

**Issue by surya-vamsi2310** [SheetJS/sheetjs#2223]
Hello Sheetjs 
I tried everything to make Bold the top row bold in but couldn't find a way to do so, can anyone help me out with angular code to make bold 

Thanks in advance

**Comment by julia-dizhak** [comment]
hello Sheetjs
I have the same problem

**Comment by SheetJSDev** [comment]
Text styling like bold is a feature of our [Pro builds](https://sheetjs.com/pro)
