### ISSUE TITLE
parse csv return wrong data 

### ISSUE THREAD

**Issue by steven274** [SheetJS/sheetjs#2224]
This is my CSV file data
```
S-DGF-36.2,S-DGF-36.1
S-DGF-36.2,S-DGF-36.1
```

This is my code
```
      const wb = XLSX.read(e.target.result, { type: 'binary' });
      const ws = wb.Sheets[wb.SheetNames[0]];
      const data = XLSX.utils.sheet_to_json(ws, { raw: false });
      data.forEach(data => {
        console.log(data);
      });
```

Result
![Screen Shot 2021-02-05 at 10 59 53](https://user-images.githubusercontent.com/7889676/106988063-606bb880-67a1-11eb-882c-935aba3e2210.png)

Expected:
S-DGF-36.2 not convert to date

**Comment by flaushi** [comment]
related https://github.com/SheetJS/sheetjs/issues/2196

**Comment by SheetJSDev** [comment]
This is a V8 (node/chrome) issue since it detects the value is a date:

```js
new Date("S-DGF-36.2");
// Fri Feb 01 2036 00:00:00 GMT-0500 (Eastern Standard Time)
```

If you are comfortable just dealing with text, pass the option `raw: true`:

```js
      const wb = XLSX.read(e.target.result, { type: 'binary', raw: true });
```

Closing in favor of https://github.com/SheetJS/sheetjs/issues/2196
