### ISSUE TITLE
Zip archive data, at least v1.0 to extract instead of Microsoft Excel 2007+

### ISSUE THREAD

**Issue by bastienlandry1** [SheetJS/sheetjs#2229]
Hi,

I am trying to save a file using this code:
```
var wb = xlsx.utils.book_new();
wb.SheetNames.push("Test Sheet");
let ws_data = []; 
for (let i = 0; i < 80; i++) {
    ws_data.push(["hello"]);
}
var ws = xlsx.utils.aoa_to_sheet(ws_data);
var wbout = xlsx.write(wb, {
  bookType: "xlsx",
  type: "binary",
  //compression: true,
});
```
Everything works, I manage to create the file but something strange happens; depending of the number of push in ws_data, the output is not the same type when I use the command
`file test.xlsx`
I have 2 outputs:
- Microsoft Excel 2007+ (when the number of row is low, say a hundred - but it depends of the number of columns as well)
- Zip archive data, at least v1.0 (when I have a lot of rows)

I was wondering how I could impose the first output format (since it's part of the supported output format of the documentation). It matters to me because the output with 'Zip archive data, at least v1.0' is not recognized by a third party (I have an error stating that Excel headers info is invalid)

Thank you in advance,
B.

**Comment by SheetJSDev** [comment]
Can you give an example of the second case? (a bad file and possibly some code for how to generate it)

**Comment by bastienlandry1** [comment]
Sure, here is an sample of the code I am using; I am using 
```

import { saveAs } from "file-saver";
import * as xlsx from "xlsx";

const s2ab =(s) => {
        var buf = new ArrayBuffer(s.length); //convert s to arrayBuffer
        var view = new Uint8Array(buf); //create uint8array as viewer
        for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xff; //convert to octet
        return buf;
    }
const createExample = () => {
        var wb = xlsx.utils.book_new();
       
        wb.SheetNames.push("Test Sheet");
        let ws_data = []; 
        for (let i = 0; i < 1000; i++) {
            ws_data.push(["hello"]);
        }
        var ws = xlsx.utils.aoa_to_sheet(ws_data);
        wb.Sheets["Test Sheet"] = ws;
        var wbout = xlsx.write(wb, {
            bookType: "xlsx",
            type: "binary",
        });
        saveAs(
            new Blob([s2ab(wbout)], { type: "application/octet-stream" }),
            "tests.xlsx"
        );
    };
```

**Comment by SheetJSDev** [comment]
Try using `writeFile` directly: https://jsfiddle.net/6r5mz7of/

```js
var wb = XLSX.utils.book_new();

let ws_data = []; 
for (let i = 0; i < 1000; i++) {
  ws_data.push(["hello"]);
}
var ws = XLSX.utils.aoa_to_sheet(ws_data);

XLSX.utils.book_append_sheet(wb, ws, "Test Sheet");

XLSX.writeFile(wb, "issue2229.xlsx");
```

**Comment by bastienlandry1** [comment]
I tried to do that indeed but I still have the same issue...I tried again with your snippet but the issue remains:
```
$ file issue2229.xlsx 
issue2229.xlsx: Zip archive data, at least v1.0 to extract
```

**Comment by SheetJSDev** [comment]
The generated file opens in Excel.

There are known issues with how `file` works.  Sadly their GH doesn't have the issue tracker enabled, but there were discussions in the [`file-type` JS library (see the links in the PR)](https://github.com/sindresorhus/file-type/pull/159) .

If you would like to continue this discussion with the `file` maintainers, here's our analysis:

The current [file magic logic](https://github.com/file/file/blob/master/magic/Magdir/msooxml)  looks for metadata that would be in `[Content_Types].xml`.  When we generate XLSX files, that XML file is the antepenultimate entry.  `file` is probably looking at the first N bytes of the file and the identifying strings are written after that point so it doesn't end up scanning the file.

This would also explain why you would see the desired result when you write less data.  The worksheet data appears before the content types manifest, so for smaller data the file would be `file`'s scanning range
