### ISSUE TITLE
Is there a way to set cell line-break to "automatic"?

### ISSUE THREAD

**Issue by remi-lebigre** [SheetJS/sheetjs#223]
Hello,

I'm trying to set the cell format line-break to automatic.
My cells are filled with long text and by defaut the cell size does not change.
In my worksheet, i set ['!cols'] like this:

<pre><code> sData['!cols'] = [
        {
            wpx: 400,
        },...
</code></pre>

Is there another option here to set an automatic line-break ? Or is it to be set in cell.s field ?

**Comment by SheetJSDev** [comment]
Text wrapping and other cell styling are part of our [Pro builds](https://sheetjs.com/pro)
