### ISSUE TITLE
where can i find documentation for parameters in workbook

### ISSUE THREAD

**Issue by arnold-b** [SheetJS/sheetjs#2230]
Hello, 
i just found this sample somewhere

  const worksheet = XLSX.utils.json_to_sheet(data.Records);
 	const workbook = {
		Sheets:{
			'data':worksheet
		},
		SheetNames: ['data']
	};

	const excelBuffer = XLSX.write(workbook,{bookType:'xlsx',type:'array'});

where can i find documention witch parameters are posible in the workbook structur ?

thanks

**Comment by thrnd** [comment]
https://github.com/SheetJS/sheetjs/blob/master/dist/xlsx.js#L2049

**Comment by reviewher** [comment]
README covers it: https://docs.sheetjs.com/#common-spreadsheet-format

You can also look at the typescript type definitions: https://unpkg.com/xlsx/types/index.d.ts
