### ISSUE TITLE
Update existing file

### ISSUE THREAD

**Issue by anchitjindal07** [SheetJS/sheetjs#2232]
How to update an existing file with xlsx in javascript / jquery code. I could not find any tutorial / documentation

**Comment by thrnd** [comment]
https://github.com/SheetJS/sheetjs#writing-workbooks

I think rewriting existing file is only possible in node.js enviroment

**Comment by SheetJSDev** [comment]
Reading and writing workbooks are available in environments that provide a way to read and write data.  In the web browser, you cannot use `readFile` but you can perform XHR/fetch to download files from a server, then make changes and generate a new file.  You can also read local files using a file input element (users would have to submit files) or drag-and-drop.  There are various examples including https://oss.sheetjs.com/sheetjs/ and https://oss.sheetjs.com/sheetjs/ajax.html
