### ISSUE TITLE
JSON to Sheet create many excel files

### ISSUE THREAD

**Issue by AnwarMetara** [SheetJS/sheetjs#2233]
Iam using xlsx.utils.json_to_sheet function and when I pass the array it creates EXCEL files based on the number of Keys. for example
with the below Array it creates 3 excel files with the same content.
[{"ValueDate":"17-02-20","HR sheets":null,"FeCr":null,"SiMn":null},
{"ValueDate":"18-02-20","HR sheets":null,"FeCr ":null,"SiMn":null},
{"ValueDate":"19-02-20","HR sheets":null,"FeCr":null,"SiMn":null}]

        
       if(typeof XLSX == 'undefined') XLSX = require('xlsx');

        ///* Create a worksheet */
        var ws = XLSX.utils.json_to_sheet(JSON.parse(myJsonString));

        ///* Create a new empty workbook, then add the worksheet */
        var wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "ChartData");

        ///* Generate xlsx files */
        XLSX.writeFile(wb, "T.xlsx");

Thank you

**Comment by SheetJSDev** [comment]
The code sample should be creating exactly one workbook that contains exactly one worksheet.

If you are trying to create multiple worksheets in the same workbook, you would need to generate each worksheet separately (multiple `json_to_sheet` calls with different data) and add each to the workbook (multiple `book_append_sheet` calls to the same workbook).
