### ISSUE TITLE
Error Reading Classified Workbook: ECMA-376 Encrypted file missing /EncryptionInfo

### ISSUE THREAD

**Issue by bacalfa** [SheetJS/sheetjs#2234]
I get the following error when trying to `XLSX.read` a workbook after classifying it as "technical data" and saving it with MS Excel in Office 365.

![image](https://user-images.githubusercontent.com/1297074/108565349-87aea380-72d2-11eb-965e-799746004ce5.png)

If I change the classification of the file to another type, I'm able to read it with SheetJS. Is there anything I can do to still be able to read it regardless of its classification?

Note: the classification is done by the Azure Information Protection. It somehow labels the file according to the classification selected.

**Comment by SheetJSDev** [comment]
Can you share the file?  Either attach to the github issue or email to hello@sheetjs.com

**Comment by SheetJSDev** [comment]
If you are willing to provide the Azure expertise to set up the AIP and explain how to run tests, we could investigate further.  Unfortunately we are not Azure experts.  

Comments in the MS-OFFCRYPTO spec suggest the library would have to perform network requests to interact with the Azure AD API, which is definitely not something we'd want to integrate.  For the same reason, SheetJS does not natively support the Google Sheets API or [gsheet files](https://github.com/SheetJS/sheetjs/issues/924)

**Comment by thuytrangmt98** [comment]
Hi @bacalfa, I have the same error while reading the file. Did you fix it yet?

**Comment by SheetJSDev** [comment]
@thuytrangmt98 can you share a sample file?  If you cannot do it publicly, email hello@sheetjs.com
