### ISSUE TITLE
Error Message using requirejs

### ISSUE THREAD

**Issue by berndbloedorn** [SheetJS/sheetjs#2238]
I am using sheetjs with requires and set the require configuration for sheetjs as described here. But I get an error message because sheetjs tries to load fs via require: "Error: Module name "fs" has not been loaded yet for context: _. Use require([])"

Nevertheless sheetjs is working but I needed to get rid of this message. I made a workaround by defining an empty object in the very beginning like so:

var disableRequire = {};

Then I replaced all ocurences of "typeof require" by "typeof disableRequire.require". This helps that require is never used in sheetjs. But it's of course a hack and not a proper solution.

**Comment by SheetJSDev** [comment]
[Follow the demo](https://github.com/SheetJS/sheetjs/tree/master/demos/requirejs) and use the standalone bundles:

```js
require.config({
	baseUrl: ".",
	name: "app",
	paths: {
		xlsx: "xlsx.full.min"
	}
});
```

You can also use `"xlsx.mini.min"` if you don't need XLS support
