### ISSUE TITLE
Csv with semicolon-comma wrong parsing

### ISSUE THREAD

**Issue by defusioner** [SheetJS/sheetjs#2239]
Hi, I'm trying to read a CSV file like this (`;,` delimiters):
```
A;B;C;D
1,1;2,2;3,3;4,1
1,1;2,2;3,3;4,1
1,1;2,2;3,3;4,1
```

What happens: semicolon from the first line does not become the main separator, the comma from the second line does and it breaks the file's logic.

Code that reads:
```
X.read(e.target.result, { type: 'string' })
```

Result
```
{
      A1: { t: 's', v: 'A;B;C;D' },
      A2: { t: 'n', w: '1', v: 1 },
      B2: { t: 's', v: '1;2' },
      C2: { t: 's', v: '2;3' },
      D2: { t: 's', v: '3;4' },
      E2: { t: 'n', w: '1', v: 1 },
      A3: { t: 'n', w: '1', v: 1 },
      B3: { t: 's', v: '1;2' },
      C3: { t: 's', v: '2;3' },
      D3: { t: 's', v: '3;4' },
      E3: { t: 'n', w: '1', v: 1 },
      A4: { t: 'n', w: '1', v: 1 },
      B4: { t: 's', v: '1;2' },
      C4: { t: 's', v: '2;3' },
      D4: { t: 's', v: '3;4' },
      E4: { t: 'n', w: '1', v: 1 },
      '!ref': 'A1:E4'
    }
```

I have seen your comment about standard delimiters, but normally semicolon is a basic one (https://github.com/SheetJS/sheetjs/issues/1087#issuecomment-385708628)

Probably I am doing something wrong? Thanks

**Comment by SheetJSDev** [comment]
The overarching issue is locales (in some locales, commas are treated as decimal points and semicolons are the field separators).  Excel's general backdoor for the delimiter is the `sep=` pragma.

We'd accept a PR that adds an override.  The change would be in [`bits/40_harb.js`](https://github.com/SheetJS/sheetjs/blob/master/bits/40_harb.js):

```diff
		if(str.slice(0,4) == "sep=") {
			// If the line ends in \r\n
			if(str.charCodeAt(5) == 13 && str.charCodeAt(6) == 10 ) {
				sep = str.charAt(4); str = str.slice(7);
			}
			// If line ends in \r OR \n
			else if(str.charCodeAt(5) == 13 || str.charCodeAt(5) == 10 ) {
				sep = str.charAt(4); str = str.slice(6);
			}
			else sep = guess_sep(str.slice(0,1024));
		}
+		else if(opts && opts.FS) sep = opts.FS;
		else sep = guess_sep(str.slice(0,1024));
```

and the end code would be

```js
X.read(e.target.result, { type: 'string', FS: ";" })
```

**Comment by Swastik2000** [comment]
@SheetJSDev Can I take this issue?

**Comment by defusioner** [comment]
> The overarching issue is locales (in some locales, commas are treated as decimal points and semicolons are the field separators). Excel's general backdoor for the delimiter is the `sep=` pragma.
> 
> We'd accept a PR that adds an override. The change would be in [`bits/40_harb.js`](https://github.com/SheetJS/sheetjs/blob/master/bits/40_harb.js):
> 
> ```diff
> 		if(str.slice(0,4) == "sep=") {
> 			// If the line ends in \r\n
> 			if(str.charCodeAt(5) == 13 && str.charCodeAt(6) == 10 ) {
> 				sep = str.charAt(4); str = str.slice(7);
> 			}
> 			// If line ends in \r OR \n
> 			else if(str.charCodeAt(5) == 13 || str.charCodeAt(5) == 10 ) {
> 				sep = str.charAt(4); str = str.slice(6);
> 			}
> 			else sep = guess_sep(str.slice(0,1024));
> 		}
> +		else if(opts && opts.FS) sep = opts.FS;
> 		else sep = guess_sep(str.slice(0,1024));
> ```
> 
> and the end code would be
> 
> ```js
> X.read(e.target.result, { type: 'string', FS: ";" })
> ```

We have done exactly this workaround on the code side (reading the first line and finding out the separator). I thought it could be done automatically.

**Comment by SheetJSDev** [comment]
The current behavior is consistent with Excel.

Consider the original sample file:

```
A;B;C;D
1,1;2,2;3,3;4,1
1,1;2,2;3,3;4,1
1,1;2,2;3,3;4,1
```

In the `English (United States)` regional setting, Excel will parse as if the field separator (Windows calls this "List separator") is the comma character:

<img width="329" alt="" src="https://user-images.githubusercontent.com/6070939/132998826-97747b56-3b71-41fc-8d29-476c53ba15d4.png">

If you are using a regional setting with ";" as the list separator and "," as the decimal symbol, then you will get the parse you expect.

In windows 7 these settings can be found in "Control Panel" > "Clock, Language, and Region" > "Region and Language" > "Additional Settings".  en_US has the following settings:

<img width="294" alt="" src="https://user-images.githubusercontent.com/6070939/132998897-a3fb6b56-4e4f-429f-b6f4-161a59c57aa2.png">


Note: Excel's backdoor for controlling the list separator is the aforementioned `sep=` pragma.  If you do specify it, Excel will use the separator but it won't change the decimal separator:

<img width="223" alt="" src="https://user-images.githubusercontent.com/6070939/132999018-3ef47527-7fb3-497c-af60-b854527b2445.png">

**Comment by malek227** [comment]
#malek``

**Comment by fanglee101** [comment]
[b]https://icq.im/AoLGnKtUsQZKGmUTjTA

https://t.me/chinadebitbank


This is arqidarknet from

torre,zorldcard, market pro,

I sell first hand pos data,atm datas,resellers welcome,
usable pos,atm 

bank logs,email access,password
RDP
hack bibbles
Cvv=address
eu-usa-asia


minimum order is  10pieces 

no test for new clients* consideration could be consider on basis.

[/b]


**
![photo_2021-10-06_08-41-11](https://user-images.githubusercontent.com/92568711/137447934-d3de82af-21e0-4a73-aeb0-a9ec386b6c45.jpg)
**






![photo_2021-08-15_00-27-25](https://user-images.githubusercontent.com/92568711/137446993-4725550a-41c1-41a1-9bc8-a55b90b9794c.jpg)

**Comment by SheetJSDev** [comment]
ef21e2bea29236bb983c747d7c087b886aa7fef3

**Comment by bacalfa** [comment]
Hello. What if I have a comma-separated .csv file in which some "cells" contain semi-colon separated values? Example:

```
A,B
1,a;b;c
2,d;e;f
```

The following isn't working as expected:

```
var workbook = XLSX.read(e.target.result, {type:'array', FS: ','})
var data = XLSX.utils.sheet_to_json(workbook.Sheets['Sheet1'], {raw: true, defval: ""})
```
