### ISSUE TITLE
Reading CSV exported from Google Sheets misreads accented characters

### ISSUE THREAD

**Issue by namenotrequired** [SheetJS/sheetjs#2240]
## Steps to reproduce

- Create a Google Sheet and put these data:

Unidade | Série
-- | --
São Paulo | Pré-Vestibular

- export as CSV
- run it past this code (in a `change` event listener to an `<input type="file"/>`):

```
      const f = event.target.files[0];
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = new Uint8Array(e?.target?.result);
        const workbook = XLSX.read(data, {
          codepage: 65001,
          type: 'array',
        });

        const firstSheetName = workbook.SheetNames[0];
        const firstSheet = workbook.Sheets[firstSheetName];
        console.log('firstSheet', firstSheet);
      };
      reader.readAsArrayBuffer(f);
```

## Result

The "é" becomes "Ã©" and "ã" becomes "Ã£"

<img width="363" alt="Screen Shot 2021-02-25 at 21 06 53" src="https://user-images.githubusercontent.com/3224761/109210687-76bbd180-77ad-11eb-82b1-d0160852a6ff.png">

When I use Excel instead of Google Sheets, the result is as desired. But my app needs to handle both cases.

<img width="318" alt="Screen Shot 2021-02-25 at 21 08 14" src="https://user-images.githubusercontent.com/3224761/109210821-a539ac80-77ad-11eb-9bf8-ba2fb03d2316.png">

When I use Papaparse, I have the opposite problem: CSV files from Sheets work but Excel files arrive with botched characters.

## What I tried

Based on the comments in the similar issues https://github.com/SheetJS/sheetjs/issues/912 and https://github.com/SheetJS/sheetjs/issues/1849, I tried removing the `codepage` or setting it to 65001, 1200, 860, 850, 1251 or 1252, but all work identically.

**Comment by SheetJSDev** [comment]
Can you email the actual file to hello@sheetjs.com?  I would expect CP1252 but gsheets might be doing something weird

**Comment by namenotrequired** [comment]
I emailed it! (For anyone else, [here it is](https://drive.google.com/file/d/1Iz7imTUsFqOoaWFh9EQ0xeDrWLeCA2hG/view?usp=sharing))

Unfortunately `codepage: 1252` doesn't fix the issue. I tried again to be sure.

**Comment by 101arrowz** [comment]
@namenotrequired The spreadsheet is encoded with UTF-8. The accented characters need two bytes in UTF-8 but one byte in CP1252, which is why you see two characters instead of one for those. However, both UTF-8 and CP1252 use one byte for ASCII characters because both are compatible with ASCII.

I just tried reading your file with codepage 65001, and it works, so I would suggest verifying that you've done it correctly.
![Screenshot](https://user-images.githubusercontent.com/29579245/109838083-b09c3600-7bfa-11eb-99f9-09a78173abde.png)

**Comment by reviewher** [comment]
Try opening the file in Excel:

<img width="172" alt="Screen Shot 2021-09-09 at 8 41 17 PM" src="https://user-images.githubusercontent.com/24845478/132780475-e6944b71-e996-4582-8458-cbe00ad8906e.png">

The default encoding is the system codepage.  To force UTF8 encoding, either follow @101arrowz 's example (`codepage: 65001`) or prepend the file with the UTF8 BOM
