### ISSUE TITLE
Undefined when WriteFile

### ISSUE THREAD

**Issue by gregz07** [SheetJS/sheetjs#2243]
I have this workbook

`{"opts":{"Date1904":false,"CalcPrecision":true,"RefreshAll":false,"CalcMode":1,"CalcCount":100,"CalcIter":false,"CalcDelta":0.001,"CalcSaveRecalc":true},"SheetNames":["Sheet 1"],"Sheets":{"Sheet 1":{"!margins":{"left":0.7,"right":0.7,"top":0.75,"bottom":0.75,"header":0.5,"footer":0.5},"A1":{"v":"ROW_ID","t":"s","w":"ROW_ID"},"A2":{"v":"2-1M11H05R","t":"s","w":"2-1M11H05R"},"A3":{"v":"2-1M11HVXW","t":"s","w":"2-1M11HVXW"},"A4":{"v":"2-1M11LKIS","t":"s","w":"2-1M11LKIS"},"A5":{"v":"2-1M11F3HX","t":"s","w":"2-1M11F3HX"},"A6":{"v":"2-1M11MKSS","t":"s","w":"2-1M11MKSS"},"A7":{"v":"2-1M11LKND","t":"s","w":"2-1M11LKND"},"A8":{"v":"2-1M11H06X","t":"s","w":"2-1M11H06X"},"A9":{"v":"2-1M11MKYE","t":"s","w":"2-1M11MKYE"},"A10":{"v":"2-1M11LTRV","t":"s","w":"2-1M11LTRV"},"A11":{"v":"2-1M11H9FH","t":"s","w":"2-1M11H9FH"},"A12":{"v":"2-1M11HVTV","t":"s","w":"2-1M11HVTV"},"A13":{"v":"2-1M147M7B","t":"s","w":"2-1M147M7B"},"A14":{"v":"2-1LY9Y4UH","t":"s","w":"2-1LY9Y4UH"},"A15":{"v":"2-1M114V3H","t":"s","w":"2-1M114V3H"},"A16":{"v":"2-1M147M4T","t":"s","w":"2-1M147M4T"},"A17":{"v":"2-1M147M6H","t":"s","w":"2-1M147M6H"},"A18":{"v":"1-1BYD1LLX","t":"s","w":"1-1BYD1LLX"},"A19":{"v":"1-1BYD1V6U","t":"s","w":"1-1BYD1V6U"},"A20":{"v":"1-1BYD1YPP","t":"s","w":"1-1BYD1YPP"},"A21":{"v":"1-1BYD3T3D","t":"s","w":"1-1BYD3T3D"},"!ref":"A1:A21"}},"Preamble":{"!protect":false},"Strings":[{"t":"ROW_ID","raw":"<t>ROW_ID</t>","r":"ROW_ID"},{"t":"2-1M11H05R","raw":"<t>2-1M11H05R</t>","r":"2-1M11H05R"},{"t":"2-1M11HVXW","raw":"<t>2-1M11HVXW</t>","r":"2-1M11HVXW"},{"t":"2-1M11LKIS","raw":"<t>2-1M11LKIS</t>","r":"2-1M11LKIS"},{"t":"2-1M11F3HX","raw":"<t>2-1M11F3HX</t>","r":"2-1M11F3HX"},{"t":"2-1M11MKSS","raw":"<t>2-1M11MKSS</t>","r":"2-1M11MKSS"},{"t":"2-1M11LKND","raw":"<t>2-1M11LKND</t>","r":"2-1M11LKND"},{"t":"2-1M11H06X","raw":"<t>2-1M11H06X</t>","r":"2-1M11H06X"},{"t":"2-1M11MKYE","raw":"<t>2-1M11MKYE</t>","r":"2-1M11MKYE"},{"t":"2-1M11LTRV","raw":"<t>2-1M11LTRV</t>","r":"2-1M11LTRV"},{"t":"2-1M11H9FH","raw":"<t>2-1M11H9FH</t>","r":"2-1M11H9FH"},{"t":"2-1M11HVTV","raw":"<t>2-1M11HVTV</t>","r":"2-1M11HVTV"},{"t":"2-1M147M7B","raw":"<t>2-1M147M7B</t>","r":"2-1M147M7B"},{"t":"2-1LY9Y4UH","raw":"<t>2-1LY9Y4UH</t>","r":"2-1LY9Y4UH"},{"t":"2-1M114V3H","raw":"<t>2-1M114V3H</t>","r":"2-1M114V3H"},{"t":"2-1M147M4T","raw":"<t>2-1M147M4T</t>","r":"2-1M147M4T"},{"t":"2-1M147M6H","raw":"<t>2-1M147M6H</t>","r":"2-1M147M6H"},{"t":"1-1BYD1LLX","raw":"<t>1-1BYD1LLX</t>","r":"1-1BYD1LLX"},{"t":"1-1BYD1V6U","raw":"<t>1-1BYD1V6U</t>","r":"1-1BYD1V6U"},{"t":"1-1BYD1YPP","raw":"<t>1-1BYD1YPP</t>","r":"1-1BYD1YPP"},{"t":"1-1BYD3T3D","raw":"<t>1-1BYD3T3D</t>","r":"1-1BYD3T3D"}],"SSF":{"0":"General","1":"0","2":"0.00","3":"#,##0","4":"#,##0.00","5":"\"$\"#,##0_);\\(\"$\"#,##0\\)","6":"\"$\"#,##0_);[Red]\\(\"$\"#,##0\\)","7":"\"$\"#,##0.00_);\\(\"$\"#,##0.00\\)","8":"\"$\"#,##0.00_);[Red]\\(\"$\"#,##0.00\\)","9":"0%","10":"0.00%","11":"0.00E+00","12":"# ?/?","13":"# ??/??","14":"m/d/yy","15":"d-mmm-yy","16":"d-mmm","17":"mmm-yy","18":"h:mm AM/PM","19":"h:mm:ss AM/PM","20":"h:mm","21":"h:mm:ss","22":"m/d/yy h:mm","37":"#,##0 ;(#,##0)","38":"#,##0 ;[Red](#,##0)","39":"#,##0.00;(#,##0.00)","40":"#,##0.00;[Red](#,##0.00)","41":"_(* #,##0_);_(* \\(#,##0\\);_(* \"-\"_);_(@_)","42":"_(\"$\"* #,##0_);_(\"$\"* \\(#,##0\\);_(\"$\"* \"-\"_);_(@_)","43":"_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \"-\"??_);_(@_)","44":"_(\"$\"* #,##0.00_);_(\"$\"* \\(#,##0.00\\);_(\"$\"* \"-\"??_);_(@_)","45":"mm:ss","46":"[h]:mm:ss","47":"mmss.0","48":"##0.0E+0","49":"@","56":"\"上午/下午 \"hh\
"時\"mm\"分\"ss\"秒 \""},"Metadata":{"Country":["US","US"]},"Workbook":{"Sheets":[{"Hidden":0,"name":"Sheet 1"}],"WBProps":{"date1904":false},"Views":[{}]},"Custprops":{},"Props":{}}`

If I try to write file `XLSX.writeFile(workbook, 'Teste.xlsx');` it will return undefined

Thoughts ?

Also I dunno why the JSON came badly parsed. It's on the SSF object.

**Comment by SheetJSDev** [comment]
Can't reproduce in NodeJS using the (fixed) example:

```js
var wb = {"opts":{"Date1904":false,"CalcPrecision":true,"RefreshAll":false,"CalcMode":1,"CalcCount":100,"CalcIter":false,"CalcDelta":0.001,"CalcSaveRecalc":true},"SheetNames":["Sheet 1"],"Sheets":{"Sheet 1":{"!margins":{"left":0.7,"right":0.7,"top":0.75,"bottom":0.75,"header":0.5,"footer":0.5},"A1":{"v":"ROW_ID","t":"s","w":"ROW_ID"},"A2":{"v":"2-1M11H05R","t":"s","w":"2-1M11H05R"},"A3":{"v":"2-1M11HVXW","t":"s","w":"2-1M11HVXW"},"A4":{"v":"2-1M11LKIS","t":"s","w":"2-1M11LKIS"},"A5":{"v":"2-1M11F3HX","t":"s","w":"2-1M11F3HX"},"A6":{"v":"2-1M11MKSS","t":"s","w":"2-1M11MKSS"},"A7":{"v":"2-1M11LKND","t":"s","w":"2-1M11LKND"},"A8":{"v":"2-1M11H06X","t":"s","w":"2-1M11H06X"},"A9":{"v":"2-1M11MKYE","t":"s","w":"2-1M11MKYE"},"A10":{"v":"2-1M11LTRV","t":"s","w":"2-1M11LTRV"},"A11":{"v":"2-1M11H9FH","t":"s","w":"2-1M11H9FH"},"A12":{"v":"2-1M11HVTV","t":"s","w":"2-1M11HVTV"},"A13":{"v":"2-1M147M7B","t":"s","w":"2-1M147M7B"},"A14":{"v":"2-1LY9Y4UH","t":"s","w":"2-1LY9Y4UH"},"A15":{"v":"2-1M114V3H","t":"s","w":"2-1M114V3H"},"A16":{"v":"2-1M147M4T","t":"s","w":"2-1M147M4T"},"A17":{"v":"2-1M147M6H","t":"s","w":"2-1M147M6H"},"A18":{"v":"1-1BYD1LLX","t":"s","w":"1-1BYD1LLX"},"A19":{"v":"1-1BYD1V6U","t":"s","w":"1-1BYD1V6U"},"A20":{"v":"1-1BYD1YPP","t":"s","w":"1-1BYD1YPP"},"A21":{"v":"1-1BYD3T3D","t":"s","w":"1-1BYD3T3D"},"!ref":"A1:A21"}},"Preamble":{"!protect":false},"Strings":[{"t":"ROW_ID","raw":"<t>ROW_ID</t>","r":"ROW_ID"},{"t":"2-1M11H05R","raw":"<t>2-1M11H05R</t>","r":"2-1M11H05R"},{"t":"2-1M11HVXW","raw":"<t>2-1M11HVXW</t>","r":"2-1M11HVXW"},{"t":"2-1M11LKIS","raw":"<t>2-1M11LKIS</t>","r":"2-1M11LKIS"},{"t":"2-1M11F3HX","raw":"<t>2-1M11F3HX</t>","r":"2-1M11F3HX"},{"t":"2-1M11MKSS","raw":"<t>2-1M11MKSS</t>","r":"2-1M11MKSS"},{"t":"2-1M11LKND","raw":"<t>2-1M11LKND</t>","r":"2-1M11LKND"},{"t":"2-1M11H06X","raw":"<t>2-1M11H06X</t>","r":"2-1M11H06X"},{"t":"2-1M11MKYE","raw":"<t>2-1M11MKYE</t>","r":"2-1M11MKYE"},{"t":"2-1M11LTRV","raw":"<t>2-1M11LTRV</t>","r":"2-1M11LTRV"},{"t":"2-1M11H9FH","raw":"<t>2-1M11H9FH</t>","r":"2-1M11H9FH"},{"t":"2-1M11HVTV","raw":"<t>2-1M11HVTV</t>","r":"2-1M11HVTV"},{"t":"2-1M147M7B","raw":"<t>2-1M147M7B</t>","r":"2-1M147M7B"},{"t":"2-1LY9Y4UH","raw":"<t>2-1LY9Y4UH</t>","r":"2-1LY9Y4UH"},{"t":"2-1M114V3H","raw":"<t>2-1M114V3H</t>","r":"2-1M114V3H"},{"t":"2-1M147M4T","raw":"<t>2-1M147M4T</t>","r":"2-1M147M4T"},{"t":"2-1M147M6H","raw":"<t>2-1M147M6H</t>","r":"2-1M147M6H"},{"t":"1-1BYD1LLX","raw":"<t>1-1BYD1LLX</t>","r":"1-1BYD1LLX"},{"t":"1-1BYD1V6U","raw":"<t>1-1BYD1V6U</t>","r":"1-1BYD1V6U"},{"t":"1-1BYD1YPP","raw":"<t>1-1BYD1YPP</t>","r":"1-1BYD1YPP"},{"t":"1-1BYD3T3D","raw":"<t>1-1BYD3T3D</t>","r":"1-1BYD3T3D"}],"SSF":{"0":"General","1":"0","2":"0.00","3":"#,##0","4":"#,##0.00","5":"\"$\"#,##0_);\\(\"$\"#,##0\\)","6":"\"$\"#,##0_);[Red]\\(\"$\"#,##0\\)","7":"\"$\"#,##0.00_);\\(\"$\"#,##0.00\\)","8":"\"$\"#,##0.00_);[Red]\\(\"$\"#,##0.00\\)","9":"0%","10":"0.00%","11":"0.00E+00","12":"# ?/?","13":"# ??/??","14":"m/d/yy","15":"d-mmm-yy","16":"d-mmm","17":"mmm-yy","18":"h:mm AM/PM","19":"h:mm:ss AM/PM","20":"h:mm","21":"h:mm:ss","22":"m/d/yy h:mm","37":"#,##0 ;(#,##0)","38":"#,##0 ;[Red](#,##0)","39":"#,##0.00;(#,##0.00)","40":"#,##0.00;[Red](#,##0.00)","41":"_(* #,##0_);_(* \\(#,##0\\);_(* \"-\"_);_(@_)","42":"_(\"$\"* #,##0_);_(\"$\"* \\(#,##0\\);_(\"$\"* \"-\"_);_(@_)","43":"_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \"-\"??_);_(@_)","44":"_(\"$\"* #,##0.00_);_(\"$\"* \\(#,##0.00\\);_(\"$\"* \"-\"??_);_(@_)","45":"mm:ss","46":"[h]:mm:ss","47":"mmss.0","48":"##0.0E+0","49":"@"},"Metadata":{"Country":["US","US"]},"Workbook":{"Sheets":[{"Hidden":0,"name":"Sheet 1"}],"WBProps":{"date1904":false},"Views":[{}]},"Custprops":{},"Props":{}}

var XLSX = require("xlsx");
XLSX.writeFile(wb, "out.xlsx");
```

Can you try running against the latest version and see if the problem still persists?  If so, share some more environment details and we can reopen the issue.
