### ISSUE TITLE
worksheet['!rows'] - row is undefined

### ISSUE THREAD

**Issue by wjdgusfb11** [SheetJS/sheetjs#2244]
![image](https://user-images.githubusercontent.com/23116160/109608990-0ecf0780-7b6e-11eb-9943-23594463023c.png)

124 row is undefined.
What is the reason?

Thank you.

**Comment by ThibautSF** [comment]
Does the row have any value ? If I remember well, only rows id with at least one cell not empty has a key on this object.

**Comment by wjdgusfb11** [comment]
console.log result = 
![image](https://user-images.githubusercontent.com/23116160/109890372-86b24480-7cca-11eb-8b88-b8c8b73efee9.png)

not have ht so row is undefined 


				if (opts && opts.cellStyles) {
					rowobj = {}; rowrite = false;
					if (tag.ht) { rowrite = true; rowobj.hpt = parseFloat(tag.ht); rowobj.hpx = pt2px(rowobj.hpt); }
					if (tag.hidden == "1") { rowrite = true; rowobj.hidden = true; }
					if (tag.outlineLevel != null) { rowrite = true; rowobj.level = +tag.outlineLevel; }
					if (rowrite) rows[tagr - 1] = rowobj;
				}

**Comment by wjdgusfb11** [comment]
xlsx.min.flow.js
                              
  if (opts && opts.cellStyles) {
     rowobj = {}; rowrite = false;
     **if (tag.ht) { rowrite = true; rowobj.hpt = parseFloat(tag.ht); rowobj.hpx = pt2px(rowobj.hpt); }**
     if (tag.hidden == "1") { rowrite = true; rowobj.hidden = true; }
     if (tag.outlineLevel != null) { rowrite = true; rowobj.level = +tag.outlineLevel; }
     if (rowrite) rows[tagr - 1] = rowobj;
}


------------------------------------------------------------------------------


console.log(row) -> 
![image](https://user-images.githubusercontent.com/23116160/109890791-3b4c6600-7ccb-11eb-8bc8-b45da6385656.png)

This row have not ht. so row is undefined. I don't know why, but it seems to be a matter of row. Data also existed in the row.

**Comment by SheetJSDev** [comment]
`!rows` holds row metadata like cell height.  If the height was not overridden and the row is not hidden, no object will be generated for that row.

The actual data in the row, if there are cells in the row, will be stored in the worksheet.  That has no bearing on the presence of row metadata
