### ISSUE TITLE
Encoding problem in sheet_to_html with roubles

### ISSUE THREAD

**Issue by Able1991** [SheetJS/sheetjs#2245]
Hi there

I have workbook with "₽"
If i use sheet_to_json helper i see valid symbol, sheet_to_html return â½
Code run in node v13.14.0

![image](https://user-images.githubusercontent.com/3898046/109868232-73768900-7c78-11eb-8ec5-52dbe90e7098.png)

Thanks!

**Comment by SheetJSDev** [comment]
It looks like a UTF8 error (the correct bytes are written but interpreted as a binary string rather than a UTF8 sequence).  Most likely your outer HTML is missing a charset hint like `<meta charset="utf-8">`
