### ISSUE TITLE
XLSX Generated file content is in raw form

### ISSUE THREAD

**Issue by muhammadali7768** [SheetJS/sheetjs#2246]
I am getting a xlsx file from Amazon, the attached image shows the response headers and body.

![Screenshot from 2021-03-04 13-03-21](https://user-images.githubusercontent.com/34996563/110065710-9b0d4480-7d91-11eb-8502-e69b6ff0ce53.png)

I am writing the file to desk using the following code

```
var workbook = XLSX.read(response, {type: 'array'})
XLSX.writeFile(workbook, 'out.xlsx')
```
When i open the file the content is not in readable form. Each cell has a string of 000000000. Following  is the screenshot of the file

![Screenshot from 2021-03-05 09-12-25](https://user-images.githubusercontent.com/34996563/110066475-58e50280-7d93-11eb-9251-ee8a4fe015f5.png)

**Comment by moltar** [comment]
Maybe it is gziped?

**Comment by muhammadali7768** [comment]
yes i fixed this by making axios call. I was using a plugin which returns the response as a string and there was some bytes missing i think thats why i was getting scrambled data. With the axios call now i can save the file as a zip and .xlsx both and also can return the file to the browser.
```
 return axios({
        method: 'post',
        url: url,
        data: requestParameters(action, token, sellerId, {ReportId: reportId}),
        responseType: 'stream'
      })
        .then(async response => {        
          response.data.pipe(res)       
        })
        .catch(error => {
          if (error.response) {          
            console.log(error.response.data)
             console.log(error.response.status);
             console.log(error.response.headers);
          }       
        })
```

**Comment by moltar** [comment]
Is this something we can fix in the MWS package?

**Comment by muhammadali7768** [comment]
I think yes. MWS package is working fine for flat file reports but i am getting scramble data for the report types **"_RFQD_BULK_DOWNLOAD_"** and **"_FEE_DISCOUNTS_REPORT_"** which are compressed xlsx files.

**Comment by muhammadali7768** [comment]
When i saved **"RFQD_BULK_DOWNLOAD"** and "**FEE_DISCOUNTS_REPORT"**  reports as a zip using axios. The zip file looks like this.
![Screenshot from 2021-03-19 11-20-17](https://user-images.githubusercontent.com/34996563/111739763-6a570000-88a5-11eb-968f-b9ef9b52c38d.png)

But i can save these reports directly as .xlsx files too.

**Comment by SheetJSDev** [comment]
Some APIs send back UTF8 encoded strings instead of raw binary data.  Since the ZIP format uses byte sequences that could be interpreted as unicode characters, the result will not be a valid ZIP.

Note that some services like AWS Lambda perform some UTF8 transform on the response by default, and [some server-side configuration may be needed](https://github.com/SheetJS/sheetjs/blob/master/demos/function/README.md#aws-lambda)
