### ISSUE TITLE
Sheet protect and background color cells

### ISSUE THREAD

**Issue by AndreaJacks** [SheetJS/sheetjs#2247]
Hi guys,
i have a problem with sheetJs.
I have a sheet protected but some cells are editable (with editable: true). 
I can edit these cell but can't edit the background color. 

How can I solve?

Thank you all.

**Comment by SheetJSDev** [comment]
If this is an issue related to a Pro build, please email pro@sheetjs.com

If not, the question does not make sense.  `editable: true` is only used in the context of HTML tables
