### ISSUE TITLE
How to skip first row(s) in table_to_sheet or table_to_book?

### ISSUE THREAD

**Issue by mil7** [SheetJS/sheetjs#2250]
Hi there,

Few years ago the same question had been asked and answered. https://github.com/SheetJS/sheetjs/issues/463

The solution does not work 100% for me: Changing the range afterwords does skip the content in the sheet. The sheet itself unfortunately still starts with an empty row (after downloading via `writeFile` and opening with Excel) though. Does anybody have an idea whether I can solve this with some more utility functions.

Or is this a feature request?

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/issues/352#issuecomment-456976898 `delete_rows(ws, 0, 1)` deletes the first row and shifts everything up.  It also corrects formulae, merge ranges and row metadata.
