### ISSUE TITLE
parse_ws_xml_data - parse row error

### ISSUE THREAD

**Issue by wjdgusfb11** [SheetJS/sheetjs#2251]
![image](https://user-images.githubusercontent.com/23116160/110584689-f5077300-81b2-11eb-9fb0-33c88a4c80e3.png)

There are rows in rows What is the problem?
Thank you.

**Comment by SheetJSDev** [comment]
Please update to the latest version.  If the error persists, please share a file and we can take a closer look.

The underlined fragment has a self-closing `row` element.  When "pretty-printed", line 190 looks like

```xml
  <row r="192" spans="1:125" hidden="1"/>
  <row r="193" spans="5:15" ht="15" hidden="1" customHeight="1">
    <c r="E193" s="140" t="s">
      <v>22849<
```
