### ISSUE TITLE
Special strings are prefixed with `'` in Excel

### ISSUE THREAD

**Issue by mmphego** [SheetJS/sheetjs#2252]
How do I forcibly format the quoted field as text?
i.e I do not want to prefix my values with `'` when writing special strings containing `%` and `:`.  Note this also applies to stringed digits.

See the example in the attached screenshot

![image](https://user-images.githubusercontent.com/7910856/110776740-11fe7d80-8269-11eb-8435-f6d60716d719.png)

**Comment by SheetJSDev** [comment]
You're passing the string "2%", so `aoa_to_sheet` attempts to create a text cell whose value is "2%".  To export the number 0.02 with the number format "0%" you should use the object `{ t:"n", v: 0.02, z: "0%" }`
