### ISSUE TITLE
It's not get when the first row or starting some rows are empty than  we not get the empty rows 

### ISSUE THREAD

**Issue by anildalar** [SheetJS/sheetjs#2253]
### Starting Empty rows not getting 
I have many xlsx  files, In this files  some file have starting row empty and some file have multiple starting empty rows and some file have empty rows in meddle but I get issue  in   when the file have starting rows empty 
look  i showing the one example and  my code to i try .

////code 
`let result=XLSX.utils.sheet_to_row_object_array(ws, {header:1, blankRows: false,defval: ''});`
///// file view  
[Book1.xlsx](https://github.com/SheetJS/sheetjs/files/6134757/Book1.xlsx)
`[
    [
        "country",
        "user",
        "fcode",
        "lcode",
        "mcode"
    ],
    [
        "India",
        "AIRCEL_Andhra Pradesh",
        405,
        801,
        "405801"
    ],
    [
        "India",
        "AIRCEL_Assam",
        404,
        29,
        "40429"
    ],
    [
        "India",
        "AIRCEL_Bihar",
        404,
        25,
        "40425"
    ],
    [
        "India",
        "AIRCEL_Chennai",
        404,
        41,
        "40441"
    ],
    [
        "India",
        "AIRCEL_Delhi",
        405,
        800,
        "405800"
    ],
    [
        "India",
        "AIRCEL_Gujarat",
        405,
        802,
        "405802"
    ],
    [
        "India",
        "AIRCEL_Haryana",
        405,
        807,
        "405807"
    ],
    [
        "India",
        "AIRCEL_Himachal Pradesh",
        404,
        35,
        "40435"
    ],
    [
        "India",
        "AIRCEL_Jammu & Kashmir",
        404,
        37,
        "40437"
    ],
    [
        "India",
        "AIRCEL_Karnataka",
        405,
        803,
        "405803"
    ],
    [
        "India",
        "AIRCEL_Kerala",
        405,
        809,
        "405809"
    ],
    [
        "India",
        "AIRCEL_Kolkata",
        404,
        91,
        "40491"
    ]
]`

**Comment by SheetJSDev** [comment]
It is unclear what the issue is.  Using your sample file and testing in NodeJS REPL:

```
> var XLSX = require("xlsx");
> var wb = XLSX.readFile("issue2253.xlsx");
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1, {header: 1})
[
  [ 'country', 'user', 'fcode', 'lcode', 'mcode' ],
  [ 'India', 'AIRCEL_Andhra Pradesh', 405, 801, '405801' ],
  [ 'India', 'AIRCEL_Assam', 404, 29, '40429' ],
  [ 'India', 'AIRCEL_Bihar', 404, 25, '40425' ],
  [ 'India', 'AIRCEL_Chennai', 404, 41, '40441' ],
  [ 'India', 'AIRCEL_Delhi', 405, 800, '405800' ],
  [ 'India', 'AIRCEL_Gujarat', 405, 802, '405802' ],
  [ 'India', 'AIRCEL_Haryana', 405, 807, '405807' ],
  [ 'India', 'AIRCEL_Himachal Pradesh', 404, 35, '40435' ],
  [ 'India', 'AIRCEL_Jammu & Kashmir', 404, 37, '40437' ],
  [ 'India', 'AIRCEL_Karnataka', 405, 803, '405803' ],
  [ 'India', 'AIRCEL_Kerala', 405, 809, '405809' ],
  [ 'India', 'AIRCEL_Kolkata', 404, 91, '40491' ]
]
```

The presence of the blank rows does not affect the result.  The same result shows up if you remove the `defval` option or set `blankrows: true`.  Even the standard row object form looks correct:

```js
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1)
```

<details><summary><b>Result</b> (click to show)</summary>

```js
[
  {
    country: 'India',
    user: 'AIRCEL_Andhra Pradesh',
    fcode: 405,
    lcode: 801,
    mcode: '405801'
  },
  {
    country: 'India',
    user: 'AIRCEL_Assam',
    fcode: 404,
    lcode: 29,
    mcode: '40429'
  },
  {
    country: 'India',
    user: 'AIRCEL_Bihar',
    fcode: 404,
    lcode: 25,
    mcode: '40425'
  },
  {
    country: 'India',
    user: 'AIRCEL_Chennai',
    fcode: 404,
    lcode: 41,
    mcode: '40441'
  },
  {
    country: 'India',
    user: 'AIRCEL_Delhi',
    fcode: 405,
    lcode: 800,
    mcode: '405800'
  },
  {
    country: 'India',
    user: 'AIRCEL_Gujarat',
    fcode: 405,
    lcode: 802,
    mcode: '405802'
  },
  {
    country: 'India',
    user: 'AIRCEL_Haryana',
    fcode: 405,
    lcode: 807,
    mcode: '405807'
  },
  {
    country: 'India',
    user: 'AIRCEL_Himachal Pradesh',
    fcode: 404,
    lcode: 35,
    mcode: '40435'
  },
  {
    country: 'India',
    user: 'AIRCEL_Jammu & Kashmir',
    fcode: 404,
    lcode: 37,
    mcode: '40437'
  },
  {
    country: 'India',
    user: 'AIRCEL_Karnataka',
    fcode: 405,
    lcode: 803,
    mcode: '405803'
  },
  {
    country: 'India',
    user: 'AIRCEL_Kerala',
    fcode: 405,
    lcode: 809,
    mcode: '405809'
  },
  {
    country: 'India',
    user: 'AIRCEL_Kolkata',
    fcode: 404,
    lcode: 91,
    mcode: '40491'
  }
]
```

</details>

Please share a file that shows a problem and we can reopen the issue.
