### ISSUE TITLE
sheet_to_json treats money as number instead of string. Understandable, but how would I get it to keep the $ prefix?

### ISSUE THREAD

**Issue by kewlniss** [SheetJS/sheetjs#2254]
This is a great library, thank you! I'm currently using a Vue component that is utilizing this.

My issue is that the dollar sign is stripped from the value turning it into a number instead of a string. I'm sure that is great in many cases, but in this case it needs to explicitly be a string keeping any text (like a dollar sign) in tact.

Using this [stackblitz demo](https://stackblitz.com/edit/angular-excel-read-table-ygjnnq?file=src/app/sheet.component.ts) I did an import of a csv file with the following contents:
Id,List Price,Retail Price,Wholesale Price
1,&nbsp;$35,29.95,26.25
2,"$25",18.95,17
3,$24,17.95,16.25
4,15 Bucks,11,9
5,b $20,11,9.5

The resulting imported data becomes:

Id | List Price | Retail Price | Wholesale Price
-- | -- | -- | --
1 | &nbsp;$35 | 29.95 | 26.25
2 | 25 | 18.95 | 17
3 | 24 | 17.95 | 16.25
4 | 15 Bucks | 11 | 9
5 | b $20 | 11 | 9.5

Row one has a html non breaking space &amp;nbsp; in the beginning, so in the output table it looks ok, but for my purposes the html code would actually show up, which isn't what I'm after.
Both lines 2 and 3 strip the beginning $ prefix from the "List Price" (second column).

I have control of exporting the data to CSV to begin with. I don't want to export as xlsx as it produces warnings that will scare my users.

Is there some value I can put in my csv to tell it that I really want it to be treated as a string and not a number?

Thanks again for a great library!

**Comment by SheetJSDev** [comment]
To pass a literal string and bypass parsing in CSV, wrap in `=""` e.g. `2,="$25",18.95,17`

This works because Excel treats it as a formula.  This behavior (and workaround) was used in Excel 2.0 from 1987 and still works today!

**Comment by kewlniss** [comment]
Thank you very much for this - it is exactly what I needed!
