### ISSUE TITLE
[BUG] Vulnerabilities in dependencies of sheets package

### ISSUE THREAD

**Issue by nilamsavani91** [SheetJS/sheetjs#2255]
## 🐛 Bug Report

Lib version: 4.2.0

## Issue
We conducted a dependency check scan on the code and it identified that there are many vulnerabilities in the current version o f the package. I was also having conversation with pro team for pricing & we are going to use "Pro Basic" version of the library if someone fix these vulnerabilities.

@SheetJSDev can you please fix this issue asap?

[sheetjs_dependency-check.zip](https://github.com/SheetJS/sheetjs/files/6165164/sheetjs_dependency-check.zip)

**Comment by SheetJSDev** [comment]
It looks like that process is scanning all of the package.json files, including the demos.  For example, the first "dependency" is `@firebase/util` and that is only used in the FireBase demo.  No firebase code appears in the main module dependency tree.  Other modules like `mocha` are only used in development.

Please re-run the scan against the actual dependencies.
