### ISSUE TITLE
Set different ThemeColorScheme when creating an xlsx file

### ISSUE THREAD

**Issue by andreyea** [SheetJS/sheetjs#2257]
In write_theme method:
https://github.com/SheetJS/sheetjs/blob/542636ba8f150d59bf7d460e92676b156f39d103/bits/49_theme.js

SheetsJs creates theme color scheme which corresponds to "Office 2007 - 2010" theme in Excel. However, the default selection is normally "Office". This creates an issue when moving worksheets between workbooks in Excel, because it resets colour pallet and may change colours on the worksheet.

![image](https://user-images.githubusercontent.com/22207323/111949986-c1730400-8b35-11eb-96c1-4522c6307e7e.png)

Is it possible to update or add the "Office" colour scheme to SheetJs?

Thanks!

**Comment by reviewher** [comment]
You can extract the raw theme from an existing file and pass it to a new file using the [`themeXLSX` option](https://docs.sheetjs.com/#writing-options).  To get the theme from a real file, go to https://oss.sheetjs.com/cfb-editor/#/ , drop your file, click "xl/theme/theme1.xml" then click "Export Entry".  It will download xl_theme_theme1.xml.  You want to copy the string contents of that file.
