### ISSUE TITLE
sheet_to_json (break after empty row?)

### ISSUE THREAD

**Issue by Anexsoft** [SheetJS/sheetjs#2259]
Hi there,

I want to stop reading the file after finding an empty row because sometimes my users save the Excel including all rows and columns, and the process cannot be completed because it takes too long.

For example, the excel is 6 rows but since they saved the file sheet_to_json wrongly it tries to read all the rows and columns of the excel.

I noticed that the problem is related to the property !refs into worksheet object. So I created a hack to fix that 

```
function fixWorksheetReference(worksheet) {
    // get all cells ranges
    const cellRanges = Object.keys(worksheet).filter(x => x.match(/[A-Z]+[0-9]+/g));

    // get the last one cell range
    const maxCellRange = cellRanges[cellRanges.length - 1];

    // update the reference because before of that, it could be A1:AMJ1048576
    worksheet['!ref'] = `A1:${maxCellRange}`;
}
```

👉 My hack re-calculate the range reference of the property !ref using the cells mapped into the worksheet property.

This an example of its usage.

```
const worksheet = workbook.Sheets[workbook.SheetNames[sheetNumber]];

fixWorksheetReference(worksheet);

return xlsx.utils.sheet_to_json(worksheet, { raw: true, defval: null });
```

What do you think about that?

**Comment by IpShot** [comment]
Have the same problem. The fix works.

**Comment by SheetJSDev** [comment]
[`update_sheet_range`](https://github.com/SheetJS/sheetjs/wiki/General-Utility-Functions) does something similar.

The underlying problem is that the `!ref` key uses the self-reported range, and some writers cheat by including more rows than exist in the file.  The parsers could (and probably should) rewrite the ranges.
