### ISSUE TITLE
[Browser - Angular 10] Main Thread Blocked / UI Frozen due to aoa_to_sheet method 

### ISSUE THREAD

**Issue by RaviRaaja** [SheetJS/sheetjs#2261]
I have array of array with size of 0.5 Million rows, on converting into worksheet - Browser main thread is completely utilized for processing it and UI is blocked.

UI is Frozen for 5 to10 Seconds. Suggestion on Async way to perform this conversion will be awesome!

`XLSXUtils.aoa_to_sheet(arr);`

**Comment by Akxe** [comment]
Async would not solve it on its own, but you can use sheetsJS in web worker

**Comment by reviewher** [comment]
Some of the demos show how to use web workers.  They won't lock up the main thread.
