### ISSUE TITLE
XLSX.read(data,{ type: 'array'}) ，data太大IE浏览器卡死，如何解决？

### ISSUE THREAD

**Issue by ywl459513230** [SheetJS/sheetjs#2263]

**Comment by SheetJSDev** [comment]
Share an example and we can take a closer look

**Comment by ywl459513230** [comment]
data.byteLength=19828736 
![QQ截图20210331092141](https://user-images.githubusercontent.com/46080309/113077922-b2aae200-9204-11eb-90e5-a5f302eff181.jpg)

**Comment by ywl459513230** [comment]
> 分享一个例子，我们可以仔细看看


xls文件18.9MB，data.byteLength = 19828736

![image](https://user-images.githubusercontent.com/46080309/113079591-ef2c0d00-9207-11eb-9d2f-e88a63632378.png)

**Comment by dhwang** [comment]
Stop using IE, it's a security honey pot and sink hole that creates zombie PC.

**Comment by SheetJSDev** [comment]
Without seeing the file, we cannot pinpoint the root cause.  But if you are using IE11, you can use a web worker to do the processing without locking up the browser.  Please try using a web worker and reopen the issue after testing
