### ISSUE TITLE
Question: Using SheetsJS to read a File Path excel on a File Path html

### ISSUE THREAD

**Issue by amandaIaria** [SheetJS/sheetjs#2264]
Ok, that title is a bit confusing but in essence, it's what I'm asking.

**Context**

In a project I will be working on the first prototype will be on a file server. AKA to access you'll be going to a URL of file://XXXX.html, which means the excel file call would be file://xxx.xlsx

Now after some research I realized that fetch and XMLHttpRequest will throw a CORS error due to the browser's security. (It makes sense since you don't want it to go to an important file on your system).

Thus I ran into the FileReader API, which is great BUT you would have to have the user select the file. We're trying to ease the amount alternate paths the users would be taking.

I can't have the user spin up a local node server as many won't have the privilege to run commands and we shouldn't be asking the users to do that as we might as well as stick with the original flow.

**Question**

So now for the question, is there something within the SheetJS (that I haven't seen) that can overcome this issue? That I don't need to have the user pick the file from an `input[type=file]` or run `window.showOpenFilePicker()`?

Thanks!

**Comment by SheetJSDev** [comment]
IE6-9 it is possible using a VBScript shim with `Scripting.FileSystemObject`.  That's actually how the FileReader API is shimmed: https://github.com/SheetJS/sheetjs/blob/master/shim.js#L135

For security reasons, in modern browsers that is not possible.  XHR and `fetch` are disabled for `file:///` URLs.  You cannot request files from the file system by name using standard web APIs

If there is a way to get the file data, you can call the `read` function with an `ArrayBuffer` or `Uint8Array` or binary string, so there is nothing we need to change here to make it work.
