### ISSUE TITLE
Is it possible to update an existing .xlsx file using sheetjs?

### ISSUE THREAD

**Issue by Agricolone** [SheetJS/sheetjs#2266]
Hi,
first of all, thanks for all your work!
I have question, as per the summary, related to updating an existing file.
My code currently imports a file when a button is clicked and save it onto a new file, named test.xlsx.

```
$('#xlf').change(function(e)
    {
            var reader = new FileReader();
            reader.readAsArrayBuffer(e.target.files[0]);
            reader.onload = function(e) 
            {
                    var data = new Uint8Array(reader.result);
                    var wb = XLSX.read(data,{type:'array', cellDates: true, cellStyles:true, sheetStubs:true, raw:true});
                    var sSN = wb.SheetNames[1];
                    var ws = wb.Sheets[sSN];
                   
                    // code to make some stuff and add data to the ones in the excel
                    
                    XLSX.writeFile(wb, "test.xlsx");
              }       
     });
```

Now, the fact is that creating a new file is a workaround - in my intention everything should be saved on the very same file I first imported, no matter if this would cause formatting and style to be lost.
I tried and searched a lot but wasn't able to find a solution, so I came here to ask: is there a way to do so?

Thanks again!

**Comment by SheetJSDev** [comment]
The Community Edition tries to translate all features into JS and generate new files, which allows for cool use cases like format conversion but ultimately means every feature of Excel files would have to be implemented.  So it is possible to read, modify and write files, but only the supported features will survive.

As part of our [Pro builds](https://sheetjs.com/pro) we offer a special edit build that allows you to do this.  The core idea is to keep the original file intact and surgically edit the worksheet data block.  It limits what can be changed but perfectly round-trips charts, pivottables and other features
