### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null     at tg (xlsx.full.min.js:22)     at ag (xlsx.full.min.js:22)     at Object.ng [as table_to_book] (xlsx.full.min.js:22)     at HTMLButtonElement.exportTableToExcel (script.js:23)

### ISSUE THREAD

**Issue by khldon123** [SheetJS/sheetjs#2268]
i just start using this library and got this problem

this is my code i need to convert a table to an excel file 
`
function tableToExcelFile() {

      var table = document.getElementById("#table");
      var wb = XLSX.utils.table_to_book(table, {sheet:"Customer Report"});
      var blob = new Blob([s2ab(XLSX.write(wb, {bookType:'xlsx', type:'binary'}))], {
	      type: "application/octet-stream"
	  });
      return saveAs(blob, "file.xlsx");
}
`

**Comment by shonkhor22** [comment]
How fix this error getElementsByTagName, i have also

**Comment by Aggie123** [comment]
Have this error too, any solution to this?

**Comment by bagusdk** [comment]
have this error to, any updates?

**Comment by SeniorChiefABLEUnit** [comment]
Checking after 10am ,  central

**Comment by SeniorChiefABLEUnit** [comment]
Today, 8am now

**Comment by dfsanchezdeacero** [comment]
:(

**Comment by SheetJSDev** [comment]
The original error likely was

```js
  var table = document.getElementById("#table");
```

The `#` should not be used with `getElementById` (you would need the `#` with `document.querySelector`)

Please raise a new issue with a new repro if you are encountering this problem,
