### ISSUE TITLE
how to fix parse dbf garbled? 

### ISSUE THREAD

**Issue by xxloveslife** [SheetJS/sheetjs#2275]
const str = cptable.utils.decode(936, buf);   
I used cpexcel.full.js  ,other  issus ever fixed csv , then  I got a correct string  ,but  when  I use 
const workbook = XLSX.read(str, { type: "string" });   this obj workbook   like  this  :

![image](https://user-images.githubusercontent.com/44740217/114649571-56bb7f80-9d13-11eb-8970-d72936740b1d.png)

is parse failed ?

**Comment by SheetJSDev** [comment]
Can you share the file?  If you can't do it publicly, email hello@sheetjs.com

**Comment by xxloveslife** [comment]
> Can you share the file? If you can't do it publicly, email [hello@sheetjs.com](mailto:hello@sheetjs.com)




[ty.zip](https://github.com/SheetJS/sheetjs/files/6450532/ty.zip)

**Comment by SheetJSDev** [comment]
It makes no sense to try to decode the entire DBF.  To override the embedded DBF codepage, assuming `buf` is a `Uint8Array`:

```js
var wb = XLSX.read(buf, {type: "array", codepage:936 });
```

To verify this is the fix:

```js
> XLSX.read(buf, {type: "array"}).Sheets.Sheet1.B35076
{ v: 'Íõ½à', t: 's' }

> XLSX.read(buf, {type: "array", codepage:936}).Sheets.Sheet1.B35076
{ v: '王洁', t: 's' }
```
