### ISSUE TITLE
The Saved XLSX file cannot be opened by Excel

### ISSUE THREAD

**Issue by shipherd** [SheetJS/sheetjs#2277]
Hi,

I have tried the officially way:
`/* bookType can be any supported output type */`
`var wopts = { bookType:'xlsx', bookSST:false, type:'array' };`
`var wbout = XLSX.write(workbook,wopts);`
`/* the saveAs call downloads a file on the local machine */`
`saveAs(new Blob([wbout],{type:"application/octet-stream"}), "test.xlsx");`

this way: https://stackoverflow.com/questions/55744771/sheetjs-and-filesaver-vuejs-project-running-out-of-memory
and this way:
            `wb = XLSX.utils.book_new();`
           `ws = XLSX.utils.json_to_sheet(data, {"header":colNames});`
            `XLSX.utils.book_append_sheet(wb, ws, "data");`
            `XLSX.writeFile(wb, "aaa.xlsx");`
to save as XLSX file, but none of them are wokring.
Every time I open the saved file, I get:
![image](https://user-images.githubusercontent.com/34145945/115357494-44e44b80-a1ef-11eb-9550-d77fd1ada0b1.png)

The Workbook can be output to the console correctly.
![image](https://user-images.githubusercontent.com/34145945/115357823-9bea2080-a1ef-11eb-8a18-5c7159bc2629.png)

Any suggestions?

**Comment by SheetJSDev** [comment]
Can you share the broken file?

The error is most likely coming from some other issue. The exact worksheet object you have shown can be reproduced by manually plugging the values into aoa_to_sheet.  Live demo at https://jsfiddle.net/j3a1mvd7/ :

```js
var ws = XLSX.utils.aoa_to_sheet([
	["_id", "VID", "EIMS_LOT", "LAST_EDIT_BY", "LAST_EDIT_DATE"],
	["607656964a46c634ea7bf539", "81BE413903247", "U04RG0N-1!CCBBZZZZZ", "test", "2021-04-20 13:53:44.601102"]
]);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "data");
XLSX.writeFile(wb, "aaa.xlsx");
```

**Comment by shipherd** [comment]
> Can you share the broken file?
> 
> The error is most likely coming from some other issue. The exact worksheet object you have shown can be reproduced by manually plugging the values into aoa_to_sheet. Live demo at https://jsfiddle.net/j3a1mvd7/ :
> 
> ```js
> var ws = XLSX.utils.aoa_to_sheet([
> 	["_id", "VID", "EIMS_LOT", "LAST_EDIT_BY", "LAST_EDIT_DATE"],
> 	["607656964a46c634ea7bf539", "81BE413903247", "U04RG0N-1!CCBBZZZZZ", "test", "2021-04-20 13:53:44.601102"]
> ]);
> var wb = XLSX.utils.book_new();
> XLSX.utils.book_append_sheet(wb, ws, "data");
> XLSX.writeFile(wb, "aaa.xlsx");
> ```

[aaa.xlsx](https://github.com/SheetJS/sheetjs/files/6342170/aaa.xlsx)

**Comment by shipherd** [comment]
> Can you share the broken file?
> 
> The error is most likely coming from some other issue. The exact worksheet object you have shown can be reproduced by manually plugging the values into aoa_to_sheet. Live demo at https://jsfiddle.net/j3a1mvd7/ :
> 
> ```js
> var ws = XLSX.utils.aoa_to_sheet([
> 	["_id", "VID", "EIMS_LOT", "LAST_EDIT_BY", "LAST_EDIT_DATE"],
> 	["607656964a46c634ea7bf539", "81BE413903247", "U04RG0N-1!CCBBZZZZZ", "test", "2021-04-20 13:53:44.601102"]
> ]);
> var wb = XLSX.utils.book_new();
> XLSX.utils.book_append_sheet(wb, ws, "data");
> XLSX.writeFile(wb, "aaa.xlsx");
> ```

This file is produced by using your code.
[aaa (1).xlsx](https://github.com/SheetJS/sheetjs/files/6342182/aaa.1.xlsx)

**Comment by shipherd** [comment]
I think I have located the problem, I was using 'xlsx.js' not 'xlsx.full.min.js'. What are the differences between them?

**Comment by SevHub** [comment]
@shipherd Thank you, I had exactly the same issue. Weird that this very basic functionality does not work in one version and nobody mentions it.
