### ISSUE TITLE
Reads downloaded Excel files incorrectly unless opened, then saved

### ISSUE THREAD

**Issue by rsand27** [SheetJS/sheetjs#2279]
I am receiving an Excel file from another program. When I feed that file into XLXS it doesn't read the file correctly. If I open that file and save it without doing anything else, it works fine. The first issue was just converting the sheet to JSON. I saw the !ref object had the range wrong, so I  used this solution to fix that: https://github.com/SheetJS/sheetjs/issues/1557

However, it still reads the data incorrectly when I parse the results through JavaScript. If I open and save the file, it parses correctly. My app parses correctly on any opened and saved file. 

I assume the act of saving the downloaded file does some type of update on the Excel file. The range issue didn't exist either on opened and saved files; only files downloaded and never opened. 

Maybe there are settings I need to pass through to sheet_to_json() that I'm unaware of? Any suggestions would be appreciated. Thank you.

**Comment by SheetJSDev** [comment]
Can you share the original file that is not being parsed correctly?

**Comment by rsand27** [comment]
Unfortunately I can't because of sensitive data and redacting that would cause me to save the file which would eliminate the issue.

**Comment by SheetJSDev** [comment]
Without seeing the file it is difficult to say.  Can you pass the option `WTF: true` to the `read` function and see if there is a parse error?

You can email directly to hello@sheetjs.com if that is acceptable.

**Comment by rsand27** [comment]
I tracked down the problem. The file download saved empty strings as a single space. Opening it and saving it in Excel must trim spaces. So when my code was checking if a value existed, the downloaded file's single space returned true. I added a loop to trim all values on each object in the JSON array and it solved the problem. Thanks.
