### ISSUE TITLE
Does SheetJS has a way to prevent Excel from treating strings like 2021/03 as dates

### ISSUE THREAD

**Issue by oussama-he** [SheetJS/sheetjs#2280]
I'm using the sheetjs libarary to export an html table to Excel file. The table looks like this:
```html
<table class="table table-bordered" id="data-table">
    <thead>
    <tr>
        <th>employee id</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>01</td>
        <td>2021/03</td>
    </tr>
    <tr>
        <td>02</td>
        <td>2021/04</td>
    </tr>
    </tbody>
</table>
```
The code I use to export to Excel looks like this:
```js
function exportToXLSX(type, fn, dl) {
    var elt = document.getElementById('data-table');
    var sheetName = 'sheet';

    var wb = XLSX.utils.table_to_book(elt, {sheet: sheetName});
    return dl ?
        XLSX.write(wb, {bookType:type, bookSST:true, type: 'base64'}) :
        XLSX.writeFile(wb, fn || ('SheetJSTableExport.' + (type || 'xlsx')));
}
```
The produced file looks like this:
![Screenshot at 2021-04-23 18-38-32](https://user-images.githubusercontent.com/18425315/115948700-929ad580-a4c7-11eb-947a-61c59b2b7297.png)

I would like the values of column B as they in the HTML table, I don't want to treat them as dates.

Can anyone help me to fix this unexpected behavior?

**Comment by oussama-he** [comment]
After inspecting the `wb` variable, I found that the SheetJS converts it (the string 2021/03) to a float and set formating to date
![Screenshot at 2021-04-24 09-08-59](https://user-images.githubusercontent.com/18425315/115952264-e7951680-a4dc-11eb-9926-6f770544959c.png)

So, please can anyone help me to prevent this behavior?

**Comment by SheetJSDev** [comment]
Add the attribute `t="s"` to the cells you want to force as text:

```html
        <td t="s">2021/03</td>
```

**Comment by flaushi** [comment]
https://github.com/SheetJS/sheetjs/issues/2196
