### ISSUE TITLE
[Question] Can I use this package with Fastify??

### ISSUE THREAD

**Issue by JaeWangL** [SheetJS/sheetjs#2281]
In README,
There are some examples for express, koa, hapi 
but not for fastify
Can I use this? and If can, How we use this??
Thanks guys

**Comment by SheetJSDev** [comment]
You should be able to take any of the those examples and adapt them for fastify.  For example, the [raw nodejs example](https://github.com/SheetJS/sheetjs/blob/master/demos/server/nodejs.js) can be adapted as follows:

```js
/* load fastify and enable body parsing */
const fastify = require('fastify')({logger: true});
fastify.register(require('fastify-multipart'), { attachFieldsToBody: true });

/* GET / returns an HTML string */
fastify.get('/', (req, reply) => reply.header('Content-Type', 'text/html').send(html));

/* POST / reads submitted file and exports to requested format */
fastify.post('/', async function(req, reply) {

  /* "file" is the name of the field in the HTML form*/
  const file = req.body.file;

  /* toBuffer returns a promise that resolves to a Buffer */
  const wb = XLSX.read(await file.toBuffer());

  /* for simple fields. the .value property holds the actual field value */
  var ext = (req.body.bookType?.value || "xlsx").toLowerCase();
  reply.header('Content-Disposition', 'attachment; filename="download.' + (extmap[ext] || ext) + '";');

  /* send can take a Buffer directly */
  reply.send(XLSX.write(wb, {type:"buffer", bookType:ext}));
});

/* start */
fastify.listen(PORT, (err, address) => {
  if(err) throw err;
});
```

(If you would like, you can send a PR adding this to the server demo)

**Comment by JaeWangL** [comment]
> You should be able to take any of the those examples and adapt them for fastify. For example, the [raw nodejs example](https://github.com/SheetJS/sheetjs/blob/master/demos/server/nodejs.js) can be adapted as follows:
> 
> ```js
> /* load fastify and enable body parsing */
> const fastify = require('fastify')({logger: true});
> fastify.register(require('fastify-multipart'), { attachFieldsToBody: true });
> 
> /* GET / returns an HTML string */
> fastify.get('/', (req, reply) => reply.header('Content-Type', 'text/html').send(html));
> 
> /* POST / reads submitted file and exports to requested format */
> fastify.post('/', async function(req, reply) {
> 
>   /* "file" is the name of the field in the HTML form*/
>   const file = req.body.file;
> 
>   /* toBuffer returns a promise that resolves to a Buffer */
>   const wb = XLSX.read(await file.toBuffer());
> 
>   /* for simple fields. the .value property holds the actual field value */
>   var ext = (req.body.bookType?.value || "xlsx").toLowerCase();
>   reply.header('Content-Disposition', 'attachment; filename="download.' + (extmap[ext] || ext) + '";');
> 
>   /* send can take a Buffer directly */
>   reply.send(XLSX.write(wb, {type:"buffer", bookType:ext}));
> });
> 
> /* start */
> fastify.listen(PORT, (err, address) => {
>   if(err) throw err;
> });
> ```
> 
> (If you would like, you can send a PR adding this to the server demo)

Oh!! Thanks. It works for me!!

**Comment by SheetJSDev** [comment]
A proper example, using fastify 4.5.2 with the new `@fastify/multipart` package, has been added to the docs https://docs.sheetjs.com/docs/demos/server/#fastify
