### ISSUE TITLE
failing to parse ECARTYPE.STANDARD() formula

### ISSUE THREAD

**Issue by pfouque06** [SheetJS/sheetjs#2282]
Hello,

My workbook have a cell with following formula : ECARTYPE.STANDARD() on range (standard deviation formula); i.e  '=ECARTYPE.STANDARD(B:B)'.
When the file is read and parsed by the npl libary (nodejs server) then rewritten after I update some other data cells, the mentioned cell failed to be parsed and becomes : 
'=@STDEV.S(B:B)'
the display is #NOM?
I have tried all options to read the file but none makes it.

using xslx^0.16.9 version

Can you help ?

thx

**Comment by pfouque06** [comment]
Parsing is correct..  is just English translation of formula.

**Comment by SheetJSDev** [comment]
FYI to make round-tripping work properly, pass the option `xlfn: true` when reading.  The technical name is `_xlfn.STDEV.S` but the parser strips the `_xlfn.` prefix by default.  The option tells the parser not to strip it out

**Comment by pfouque06** [comment]
I've tried to use this xlfn: true option but it is not available in the library version NPM installed !
