### ISSUE TITLE
Hi, How to delete a row base on a Cell

### ISSUE THREAD

**Issue by felix-le** [SheetJS/sheetjs#2286]
Hi there,

Thanks for your library. It is very helpful. However, could you please let me know:

- How can I delete a row base on a cell value:
- For example, I have many columns and many rows (including an "id" column. I want to delete a row base on its id in the id column.

Thanks

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/issues/352#issuecomment-456976898 defines `delete_rows`.  You can scan the id column to determine which rows to delete.
