### ISSUE TITLE
Typescript: Options with property type is not assignable to Sheet2CSVOpts

### ISSUE THREAD

**Issue by Rc85** [SheetJS/sheetjs#2288]
Using `sheet_to_csv` and trying to parse it as array, but passing `{ type: 'array' }` into second argument gives error.

```
Argument of type '{ type: string; }' is not assignable to parameter of type 'Sheet2CSVOpts'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Sheet2CSVOpts'.
```

xlsx ^0.16.9.

**Comment by SheetJSDev** [comment]
Correct, `sheet_to_csv` does not accept a type argument.  It always returns a JS string.  If there's a compelling reason to return some other structure like a `Uint8Array` or `Array` of bytes, please reply and we'll reopen the issue.  There are a few ways to achieve the effect without a library change:

A) create a fake workbook and write:

```js
var new_wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(new_wb, ws, "Sheet1");
var array = XLSX.write(new_wb, {type: "array", bookType: "csv"});
```

B) (modern browsers) use `TextEncoder#encode`:

```js
var array = new TextEncoder().encode(csv_str);
```

C) (NodeJS only) use `Buffer.from`:

```js
var buf = Buffer.from(csv_str);
```
