### ISSUE TITLE
Not able to add details to excel

### ISSUE THREAD

**Issue by NKatty** [SheetJS/sheetjs#2289]
I have a requirement where i apart from exporting table data i need to export some json data to it. but it should be as below

A                               B          C                D
id                           1906    status        draft
created date          21/4   createdby    test

Call Observation  Answer   YES  

 1.  Greeting           Yes         1
 2.  Verification       Yes        1  

But i am getting the below result after exporting to excel:

A                       B          C                D                    E                     F            G
id                      1906    status        draft        Call Observation  Answer   YES  
created date     21/4   createdby  test           1.  Greeting           Yes         1
                                                                                                                                            2.  Verification       Yes        1  

Can anyone suggest how can i achieve this. I am using below code to achieve second result

      data = [...details,...data];
        const header = Object.keys(data[0]); // columns name
        var wscols = [];

        for (var i = 0; i < header.length; i++) {
          // columns length added

          wscols.push({ wch: header[i].length + 5 });
        }
        var exportData = XLSX.utils.json_to_sheet(data);
        exportData["!cols"] = wscols;
        var range = XLSX.utils.decode_range(exportData["!ref"]);

        for (var C = range.s.r; C <= range.e.r; ++C) {

          var address = XLSX.utils.encode_col(C) + "1"; // <-- first row, column number C
          if (!exportData[address]) continue;

        var wb = XLSX.utils.book_new(); // make Workbook of Excel
        XLSX.utils.book_append_sheet(wb, exportData); // sheetAName is name of Worksheet
        XLSX.writeFile(wb, `ExportSummary_${this.observationId}.xlsx`); // name of the file is 'book.xlsx'

**Comment by SheetJSDev** [comment]
It would be easier to explain if you shared the original data as you have it structured (what is `details` and `data`?) and if you can present the desired output as a TSV or CSV (copying and pasting from Excel will give you a TSV).

For example, if you want

```csv
id,1906,status,draft
created date,21/4,createdby,test

Call Observation,Answer,YES  

1.  Greeting,Yes,1
2.  Verification,Yes,1  
```

Then generate a worksheet as follows:

```js
var ws = XLSX.utils.aoa_to_sheet([
 ["id", 1906, "status", "draft"],
 ["created data", "21/4", "createdby", "test"],
 [], // empty row
 ["Call Observation", "Answer", "YES"],
 [],
 ["1.  Greeting", "Yes", 1],
 ["2.  Verification", "Yes", 1],
]);
