### ISSUE TITLE
Updating Changelog

### ISSUE THREAD

**Issue by Mister-Hope** [SheetJS/sheetjs#2292]
A new version is released with CI failing 8 hours ago, and I can not find changelog everywhere.

If it's broken, please mark it clearly in release page, if not, please update changelog, thianks.

**Comment by SheetJSDev** [comment]
We used to use Travis CI but they decided to take away the open source offering: https://blog.travis-ci.com/2021-05-07-orgshutdown

The transition to GitHub actions is not 100% .  We've tested locally against all relevant node versions (starting from 0.8).  We also used Sauce Labs to test browsers before publishing: ![](https://camo.githubusercontent.com/fd3943851066063e253cd05bc1a8b9436b80f841af7d193c3eacb560012acea6/68747470733a2f2f73617563656c6162732e636f6d2f62726f777365722d6d61747269782f73686565746a732e737667)
