### ISSUE TITLE
get img from execl

### ISSUE THREAD

**Issue by aminhamidi** [SheetJS/sheetjs#2293]
Can we read img through this library?

**Comment by SheetJSDev** [comment]
Not with the Community Edition but we offer that in our [Pro Image](https://sheetjs.com/pro) build.

**Comment by aminhamidi** [comment]
How to get pro Edition ?

**Comment by SheetJSDev** [comment]
Send an email to pro@sheetjs.com

**Comment by aminhamidi** [comment]
Thank you
