### ISSUE TITLE
How to change numbers format for currency

### ISSUE THREAD

**Issue by jdgabriel** [SheetJS/sheetjs#2294]
How do I format a number in Accounting to display in the generated file?
![image](https://user-images.githubusercontent.com/47068314/118826083-8ec55d80-b891-11eb-9fef-e886de2ad194.png)

I want to display it in accounting format without requiring user interaction, in this way. (leave the entire file formatted correctly)
![image](https://user-images.githubusercontent.com/47068314/118826221-aac8ff00-b891-11eb-8e8a-72314d109ff3.png)

My code: 
![code](https://user-images.githubusercontent.com/47068314/118826635-07c4b500-b892-11eb-8352-82b952017022.png)

**Comment by pvallejo1985** [comment]
Good afternoon,
I think I have the same problem.

When I export a table with:
`XLSX.utils.table_to_sheet`

Then I try to format a cell, and I get it to perform multiple formats, for example:
`ws2.H2.z = '0.00%';`

Change the cell to Percentage, I can even enter custom formats, but I can't change the format to Currency.

Could you tell us how to change this format?

I have been looking for an answer via the internet and I have not found anything.

Thank you.

**Comment by GusMartins499** [comment]
> How do I format a number in Accounting to display in the generated file?
> ![image](https://user-images.githubusercontent.com/47068314/118826083-8ec55d80-b891-11eb-9fef-e886de2ad194.png)
> 
> I want to display it in accounting format without requiring user interaction, in this way. (leave the entire file formatted correctly)
> ![image](https://user-images.githubusercontent.com/47068314/118826221-aac8ff00-b891-11eb-8e8a-72314d109ff3.png)
> 
> My code:
> ![code](https://user-images.githubusercontent.com/47068314/118826635-07c4b500-b892-11eb-8352-82b952017022.png)

same issue

**Comment by SheetJSDev** [comment]
If you want Brazilian Real you can set the `z` property of the cell to `"R$ "#,##0.00`

There are specific formats that Excel thinks are "Currency" or "Accounting", and they are spelled out in [the SSF library](https://github.com/SheetJS/sheetjs/blob/master/bits/10_ssf.js#L114):

```js
//  5 -- Currency,   0 decimal, black negative
default_str[5] = default_str[63] = '"$"#,##0_);\\("$"#,##0\\)';
//  6 -- Currency,   0 decimal, red   negative
default_str[6] = default_str[64] = '"$"#,##0_);[Red]\\("$"#,##0\\)';
//  7 -- Currency,   2 decimal, black negative
default_str[7] = default_str[65] = '"$"#,##0.00_);\\("$"#,##0.00\\)';
//  8 -- Currency,   2 decimal, red   negative
default_str[8] = default_str[66] = '"$"#,##0.00_);[Red]\\("$"#,##0.00\\)';

// 41 -- Accounting, 0 decimal, No Symbol
default_str[41] = '_(* #,##0_);_(* \\(#,##0\\);_(* "-"_);_(@_)';
// 42 -- Accounting, 0 decimal, $  Symbol
default_str[42] = '_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"_);_(@_)';
// 43 -- Accounting, 2 decimal, No Symbol
default_str[43] = '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* "-"??_);_(@_)';
// 44 -- Accounting, 2 decimal, $  Symbol
default_str[44] = '_("$"* #,##0.00_);_("$"* \\(#,##0.00\\);_("$"* "-"??_);_(@_)';
```
