### ISSUE TITLE
How to ingore field when using XLSX.utils.json_to_sheet

### ISSUE THREAD

**Issue by jiatiejun** [SheetJS/sheetjs#2297]
How to ingore field when using XLSX.utils.json_to_sheet

Thanks

**Comment by reviewher** [comment]
Filter the data directly.  [Lodash `_.omit`](https://lodash.com/docs#omit) is well-suited for this:

```js
var filteredData = arr.map(x => _.omit(x, ['removeThisField', 'removeThatField']))
```
