### ISSUE TITLE
XLSX.utils.sheet_to_html - How can I create table with the same styling as excel has i.e background-color, color of cells

### ISSUE THREAD

**Issue by kedarshiv** [SheetJS/sheetjs#2298]
My excel which is uploading with colors
![excel](https://user-images.githubusercontent.com/30750407/119635791-a4a6c580-be31-11eb-99d3-2ebe4230ea9b.PNG)

HTML page is with only white background.

![image](https://user-images.githubusercontent.com/30750407/119636024-de77cc00-be31-11eb-8dd0-6b36df6e5777.png)

I want to show color also in the table.

**Comment by liuwz465501235** [comment]
我也发现这个问题了，这个是这个插件的缺陷吗？

**Comment by SheetJSDev** [comment]
Background colors and other styling are a part of our [Pro builds](https://sheetjs.com/pro)

**Comment by liuz666** [comment]
> 我也发现这个问题了，这个是这个插件的缺陷吗？

读取出来的数据转换成html，在页面渲染输出，都是没有样式的。
