### ISSUE TITLE
xlsxworker.js points to shim.js instead of dist/shim.min.js

### ISSUE THREAD

**Issue by btopro** [SheetJS/sheetjs#2299]
effectively trying to replicate the demo found here https://oss.sheetjs.com/sheetjs/ but with the latest 0.17.0 release of the library. In local usage if `importScripts('shim.js');` is instead moved to `importScripts('dist/shim.min.js');
` it works just as the demo out on the web does. PR shortly.

**Comment by sibelius** [comment]
is there a changelog for 0.17.0?

**Comment by SheetJSDev** [comment]
5a3e5d91c1bf1aff548deca292be2c95a304cb11

@sibelius https://github.com/SheetJS/sheetjs/issues/1728
