### ISSUE TITLE
How to show the exact value for date fields in excel file

### ISSUE THREAD

**Issue by 0416vidya** [SheetJS/sheetjs#2304]
We're getting the below format for a date from the XLSX package. Could anyone please help me to show the exact value for dates.
![image.png](https://images.zenhubusercontent.com/5be92b0104284b0a6d29f816/9ed6b266-3b95-4c24-954f-4dbd3269c24d)

Expected Value: 
![image.png](https://images.zenhubusercontent.com/5be92b0104284b0a6d29f816/86ee3f02-6974-4772-9544-6928cbc69a03)

**Comment by SheetJSDev** [comment]
It's very likely you are in `Asia/Kolkata`.

SheetJS date basis is the same as Excel, January 1 1900.  tz database points to a shift in the offset from `+05:21:10` to `+05:30:00` in the year 1906.

There is a known bug with V8 (the javascript engine that powers node and chrome) involving these nonstandard offsets, reported https://github.com/nodejs/node/issues/33306 and https://bugs.chromium.org/p/v8/issues/detail?id=7863 

This has the same root problem as https://github.com/SheetJS/sheetjs/issues/1565 so closing in favor of that issue.
