### ISSUE TITLE
dateNF is getting ignored for XLS file

### ISSUE THREAD

**Issue by 0416vidya** [SheetJS/sheetjs#2305]
For XLS file:
![image](https://user-images.githubusercontent.com/42372699/120306986-19757600-c2f0-11eb-8f33-bdf8b3348ba7.png)

For XLSX file:
![image](https://user-images.githubusercontent.com/42372699/120306867-f5b23000-c2ef-11eb-8b7d-de1e5abd7e77.png)

**Comment by SheetJSDev** [comment]
Can you share both files?
