### ISSUE TITLE
41 open pull requests at the time of writing, what are your plans?

### ISSUE THREAD

**Issue by KurtMar** [SheetJS/sheetjs#2307]
Hi.

First off I want to thank you for this great library. Secondly, I want to ask what your plans are concerning the 41 open pull requests? I came to see how mine is doing after 1 year and 8 months, which prompted this inquiry. Of these 41 pull requests there must be many more which are also bugs in need of fixing.

**Comment by SheetJSDev** [comment]
We've addressed about half of the outstanding issues and about half of the open PRs (down to 241 issues / 20 PRs).

With PRs, the major difficulty is in understanding the general implications of code changes.  Especially for a project of this scale and scope, non-trivial changes require careful consideration.  That means someone has to volunteer hours of time reading PRs.

With issues, many require follow-up from the users who raised the issues in the first place.  Oftentimes there are file-specific nuances that are hard to reproduce, so the issue creator generally has to share a sample file eliciting the error.  That means we may send a reply and "wait" for a response that never comes.

@coolaj86 raised issue #2344 asking about a v1.0.0 .  If we don't aggressively limit what will be released in 1.0.0, then a proper release will never happen.  PRs that add new features or functionality will most likely have to wait until after 1.0.0, and we'd rather keep them open than close them prematurely.
