### ISSUE TITLE
The Weak Encryption issue in fortify code scan

### ISSUE THREAD

**Issue by string-lzc** [SheetJS/sheetjs#2308]
![image](https://user-images.githubusercontent.com/21190253/120617931-27143280-c48d-11eb-9027-e05743522c3b.png)

After our static code scan. The call to parse_RC4Header() at xlsx.js line 8760 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

**Comment by SheetJSDev** [comment]
Excel itself uses RC4 in the older formats, hence a parser must implement the algorithm.  Newer formats use AES with varying key lengths
