### ISSUE TITLE
Multiple spaces gets trimmed

### ISSUE THREAD

**Issue by mesantiago** [SheetJS/sheetjs#2309]
When reading an excel file with a cell value that has multiple spaces.
![image](https://user-images.githubusercontent.com/5849716/120898349-0f8ba400-c65d-11eb-8541-5eea23d2a5d8.png)
The spaces gets trimmed into one space.
'test value'
Is there an option to stop it from doing so?

**Comment by SheetJSDev** [comment]
Do you have an example file?  XLS parsing will not trim interstitial whitespace.  XLSX will only do it if the spaces are literal whitespace characters and the XML is not explicitly marked with the `space="preserve"`

**Comment by SheetJSDev** [comment]
Please share a file and we can reopen the issue
