### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by MartinDawson** [SheetJS/sheetjs#2320]
This link is now broken: https://portal.sheetjs.com/xspread/

It was working recently and was very useful to see x-spreadsheet integration.

**Comment by SheetJSDev** [comment]
That was a demo of a feature in our [Pro offering](https://sheetjs.com/pro) and not intended for general use.  Our open source integration is discussed in [`demos/xspreadsheet` in the repo](https://github.com/SheetJS/sheetjs/tree/master/demos/xspreadsheet)
