### ISSUE TITLE
Type 'string' is not assignable to type '"string" | "binary" | "base64" | "buffer" | "file" | "array" | undefined'

### ISSUE THREAD

**Issue by coderchen523** [SheetJS/sheetjs#2322]
const wopts = {
      bookType: 'xlsx',
      bookSST: false, 
      type: 'binary'
    };
    const wbout = XLSX.write(workbook, wopts);
    
    
    error:Type 'string' is not assignable to type '"string" | "binary" | "base64" | "buffer" | "file" | "array" | undefined'

**Comment by coderchen523** [comment]
type: 'binary'

**Comment by Shrugsy** [comment]
Since you've got your options in an intermediate variable, typescript will widen the type of `'binary'` to `string`. You can cast `as const` to avoid widening like so:

```diff
const wopts = {
  bookType: 'xlsx',
  bookSST: false,
  type: 'binary'
- }
+ } as const;
```

**Comment by reviewher** [comment]
Alternatively cast the whole object to WritingOptions:

```typescript
import { WritingOptions } from 'xlsx';

const wopts = {
  bookType: 'xlsx',
  bookSST: false,
  type: 'binary'
} as WritingOptions;
```
