### ISSUE TITLE
Changing opened win.document Title from 'SheetJS Table Export'

### ISSUE THREAD

**Issue by mpaustin1993** [SheetJS/sheetjs#2323]
Hello,

I'm currently embedding a table from an Excel sheet into a document & opening it as a new tab in Chrome.

```
let worksheet = workbook.Sheets[workbook.SheetNames[0]];
    var win = window.open("", "", "toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,fullscreen=yes,width=" + screen.width + ",height=" + screen.height);
    win.moveTo(0, 0);
    win.document.body.innerHTML = XLSX.utils.sheet_to_html(worksheet);
```

However, since the document's <title> tag has no id, I'm having difficult changing it something other than 'SheetJS Table Export.'

![exportingHTML](https://user-images.githubusercontent.com/33846682/124023973-3a46ef00-d9b4-11eb-9da8-de9ee1eb1917.png)

Is there any way to change the document's title?

**Comment by SheetJSDev** [comment]
You can override the header:

```js
XLSX.utils.sheet_to_html(worksheet, {
  header: '<html><head><meta charset="utf-8"/><title>' + title + '</title></head><body>'
});
```

If you just want the table without any preamble or postamble:

```js
XLSX.utils.sheet_to_html(worksheet, { header: "", footer: "" });
```
