### ISSUE TITLE
Hyperlinks not included in sheet_to_html()

### ISSUE THREAD

**Issue by ohsnaplol** [SheetJS/sheetjs#2326]
If I export to a file, I can click the links no problem. If I use XLSX.utils.sheet_to_html(), the hyperlinks are not present in the HTML.

**Comment by SheetJSDev** [comment]
We'd accept a PR for this.  Change would be in the [HTML writer](https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L84).  For example:

```js
if(cell.l && (cell.l.Target||"#").charAt(0) != '#') w = '<a href="' + cell.l.Target +'">' + w + '</a>';
```

**Comment by jtheletter** [comment]
How can this work for a conversion from XLSX to JSON on the CLI?
