### ISSUE TITLE
Excel-files get to big?

### ISSUE THREAD

**Issue by Rapid1898-code** [SheetJS/sheetjs#2327]
Hello - i am using XLSX to write data to an excel- sheet -
I iterate over an array and write the data to the excel-sheet - around 45 columns like that

```
const XLSX = require('xlsx');
...
erg.forEach(function (item,index) {   
          XLSX.utils.sheet_add_aoa(ws2, [[arrColl[i]]], {origin: `A${rowNumber}`});
          XLSX.utils.sheet_add_aoa(ws2, [[arrCat[i]]], {origin: `B${rowNumber}`});
...
}
```

No i saw that the excel-sheet got really big after a short time.
Arond 130MB for 15.000 rows?

Am i doing here something wrong with the module for writing?
Or is there any reason why this excel-sheet get so big?

**Comment by SheetJSDev** [comment]
Pass the option `compression: true`.  XLSX files are zipped XML files and the underlying XML files can be really large.  The compression option enables zip DEFLATE compression (default uses STORED uncompressed blocks)

**Comment by Rapid1898-code** [comment]
Thanks - but how can i use these options while writing.

I tried it with 
`XLSX.writeFile(wb, FN, compression=true); `

but this give me an error
`TypeError: Cannot read property 'slice' of undefined`

normally the writing works fine with the following (but of course with big files)
`XLSX.writeFile(wb, FN); `

**Comment by reviewher** [comment]
```js
XLSX.writeFile(wb, FN, {compression: true});
```

**Comment by Rapid1898-code** [comment]
Thanks a lot for the fast response - with that it worked great!
