### ISSUE TITLE
date from excel is different between data.v and data.w when type is 'd'

### ISSUE THREAD

**Issue by lovedota** [SheetJS/sheetjs#2328]
Hello 
In excel my cell is 15/07/2021 my local time. When importing it is shown different, the correct value is in `data.w` and the date object returns error.

<img width="461" alt="Screen Shot 2021-07-14 at 15 02 20" src="https://user-images.githubusercontent.com/417914/125586273-7e869787-3323-490b-8c0d-5653560cfed9.png">

**Comment by SheetJSDev** [comment]
the `w` property is the formatted date.  Given the timezone and the scale of the error, it is most likely related to a NodeJS bug pertaining to dates (https://github.com/nodejs/node/issues/33306).  We can take a closer look if you share a sample file.
