### ISSUE TITLE
Get Value of Lookup function

### ISSUE THREAD

**Issue by Naragod** [SheetJS/sheetjs#2329]
Hello,

I have an XLXS file with the following columns:
```
A | B                                   | C
___________________________________________
1 | =VLOOKUP(M3,$Sheet1.A:B,2,FALSE()) | 3
.
.
.

```

I am trying to get this xlsx file as a json object. I am using the `sheet_to_json` function which almost works. It returns:

```
{A: 1, B: 0, C: 3}
```

The look up value of the previous column resolves to 2. How do I get the underlying value?

**Comment by SheetJSDev** [comment]
By default, the SheetJS library will pull the data that is stored in a file.  Setting 0 is a common technique for formulae that Excel will recalculate on open.  To do that in JS, you will need a library to read and evaluate the formula.  We offer that as part of our [Pro offering](https://sheetjs.com/pro)

Note: For XLSX, when writing a file the library will default to 0 if you don't provide a value.  This allows for writing files that will automatically refresh when opening in Excel.
