### ISSUE TITLE
How to insert a picture to the excel

### ISSUE THREAD

**Issue by nmnmtttt** [SheetJS/sheetjs#2330]
i want to add a picture to my xlsx file.
i did like this picture		
![image](https://user-images.githubusercontent.com/34001432/126621402-d5212653-2de7-4664-9910-3198de03a670.png)
but it does not work.
what should i do 
it is result 
![image](https://user-images.githubusercontent.com/34001432/126621962-daacb799-4de0-4ec6-a25d-8d0ed42a519f.png)

**Comment by henrydzung** [comment]
According to this https://github.com/SheetJS/sheetjs/issues/364.
Inserting images is only available in the paid version.

**Comment by SheetJSDev** [comment]
Inserting images is a feature of our [Pro offering](https://sheetjs.com/pro).

**Comment by mistervaibhav** [comment]
A little late to the party 🙂

You can insert images into spreadsheets using the IMAGE function, which works in both Microsoft Excel and Google Sheets.

<img width="1076" height="430" alt="Image" src="https://github.com/user-attachments/assets/01c2de93-3914-48cb-b9ac-c89b186b3eb9" />

I wasn’t able to get Base64 images working here, but using image URLs works fine and gets the job done.

Usage documentation:

Google Sheets: https://support.google.com/docs/answer/3093333?hl=en

Microsoft Excel: https://support.microsoft.com/en-us/office/image-function-7e112975-5e52-4f2a-b9da-1d913d51f5d5
