### ISSUE TITLE
Excel Protected View - t : n for both date and number cell values

### ISSUE THREAD

**Issue by svelu-ric** [SheetJS/sheetjs#2332]
Hi Team,

I am facing issue in getting the value of cell type - 'date' on reading the excel which is in protected view, 
Please see the below picture

![image](https://user-images.githubusercontent.com/71029178/126816829-a22b71cd-880b-4f16-845a-25ba0634d533.png)

Column C contains date as a value,

![image](https://user-images.githubusercontent.com/71029178/126817151-9a02ebf4-d46c-42ed-b4c5-13b08a2de4c3.png)

I am getting the below response from the xlsx,

![image](https://user-images.githubusercontent.com/71029178/126817648-9ee80627-a395-4a6d-9b09-3a0646659451.png)

```
I cant find whether the cell type is number or date

The format says 'General' for both number and date cell values. 

I see, t : n for number and date type cells
```

Please tell a way to find whether cell type is of number or date

Thanks in advance.

**Comment by SheetJSDev** [comment]
Pass the option `cellNF: true` and the cell objects will have a `z` property which represents the cell format.  Then test the format using `XLSX.SSF.is_date(cell.z)`

**Comment by svelu-ric** [comment]
> Pass the option `cellNF: true` and the cell objects will have a `z` property which represents the cell format. Then test the format using `XLSX.SSF.is_date(cell.z)`

This solves my problem. Thank you!
