### ISSUE TITLE
Trying to merge multiple sheets into one.

### ISSUE THREAD

**Issue by WLK4Tower** [SheetJS/sheetjs#2335]
Hello,

I'm trying to parse through a giant string that has multiple tables in it. 

The string might look something like: `'<table><tr><td>Table One</td></tr></table><table><tr><td>Table Two</td></tr></table>'`. This is a very simple explanation, but I can elaborate if I need to.

My question is, how can I retain the merged cells in each of these table headers/footers? I know the above example string doesn't have headers or footers...

I have tried doing something like the following:

1. Break the string into multiple strings representing each individual table
2. Use XLSX.read(tableString, {type: 'string'}) for each table string, then run each through sheet_to_json like the following:

`tableStringArray = tableStringArray.concat(XLSX.utils.sheet_to_json(XLSX.read(tableString, {type: 'string'}).Sheets['Sheet1'], {header: 1});`

When I'm done building this array, I can run the following:

`let newSheet = XLSX.utils.json_to_sheet(tableStringArray, { skipHeader: true });`
`let newWrkBook = XLSX.utils.book_new();`
`XLSX.utils.book_append_sheet(newWrkBook, newSheet, 'Report Data');`
`XLSX.writeFile(newWrkBook, reportName + '.xlsx');`

This is all well and dandy and allows me to actually combine my tables into one spreadsheet, but sheet_to_json strips out the merged cells!!! We can't have that happen.

I know I can simply write just one of the tables say tableStringArray[0], 

`XLSX.write(tableStringArray[0], { bookType: 'html', type: 'array' });`

and that will come out just fine in excel. However, it seems that there isn't a way to combine multiple tables into a single write method.

`XLSX.write(tableStringArray, { bookType: 'html', type: 'array' });` ????????

Is there another approach to getting the merged cells to actually show up in the final excel file? I have poured through the docs and cannot find anything about what I'm trying to solve. Thank you.

**Comment by reviewher** [comment]
create an HTML DIV, set the innerText to your HTML string, and use `sheet_add_dom` with the option `origin: -1` to write the table below existing data in a worksheet.  That can be used multiple times to add multiple tables.

If you want the tables in separate worksheets, use `table_to_sheet` to generate each sheet and `book_append_sheet` to add them to a shared workbook
