### ISSUE TITLE
xlsx.js doesn't support xlsx extension

### ISSUE THREAD

**Issue by archikaagarwal** [SheetJS/sheetjs#2338]
xlsx.full.min.js as the support to download file in xlsx format. But the same functionality is not available with xlsx.js ( it only supports .xls extension)

**Comment by SheetJSDev** [comment]
For static in-browser use, use `xlsx.full.min.js` or `xlsx.mini.min.js`.  They are amalgamations of the core `xlsx.min.js` script and support libraries.  In the past users had to include those support scripts separately, and some of the scripts are still shipped in bundles for backwards compatibility
