### ISSUE TITLE
XLSX package Download as Excel in Desktop App

### ISSUE THREAD

**Issue by msanli220** [SheetJS/sheetjs#2339]
I am developing a desktop app which is an Electron js App.I am having a problem with exporting excel file using xlsx package. It works properly (i can download the file and it shows in project directory folder) however, the app doesn't show directory or not giving any alerts like in google chrome because its a desktop app. So client can't understand the export button works or not. What are your solution suggestions for this situation?

Code Example:
 ```
function exportReport(e){
        e.preventDefault();
        let ws_name = "MySheet";
        if(!Lodash.isEmpty(props.dataSource)){
            let ws = XLSX.utils.json_to_sheet(props.dataSource);
            console.log(ws)
            let wb = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(wb, ws, ws_name);
            XLSX.writeFile(wb, 'out.xlsx');

        }
    }
 ```

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs/tree/master/demos/electron#reading-and-writing-files

```js
/* from app code, require('electron').remote calls back to main process */
var dialog = require('electron').remote.dialog;

/* show a file-save dialog and write the workbook */
var o = dialog.showSaveDialog();
XLSX.writeFile(workbook, o);
```

Depending on the electron version, you may need to use `dialog.showSaveDialogSync` and pass the `nodeIntegration` option.  For more info, see https://github.com/SheetJS/sheetjs/issues/1994
