### ISSUE TITLE
tool 'Text to Columns' breaks (in Excel)

### ISSUE THREAD

**Issue by AlexPilinni** [SheetJS/sheetjs#2340]
I have a table (.xlsx file).  The file is generated fine, but if I want to work with it, then this is problematic. I am guessing that the problem is in the wrong creation of the table or cells or the data types of the cells

And I want to split column cells with text by comma separator.

If i save the split result into empty table cells, then everything works fine.
But if I choose a cell with the original text for saving, with the supposed overwriting of the cell, then everything breaks, when the tool is running, it stumbles over something and Excel closes.

For example, col - Terminal 
[test.xlsx](https://github.com/SheetJS/sheetjs/files/6932247/test.xlsx)

step 0 - generate xlsx Table with SheetJS xlsx
step 1 - choose columns cells Terminals, go to tool - Text to Columns, choose delimited
![step1](https://user-images.githubusercontent.com/67575373/128207560-3ef6ad8c-7873-45c2-8a69-5702e27402a3.png)
step 2 - chose delimiters - comma
![step2](https://user-images.githubusercontent.com/67575373/128207572-539d415e-078a-4b00-b1d2-1aa395a83020.png)
step 3.1 choose cells for result and have success
![success](https://user-images.githubusercontent.com/67575373/128208108-b54b7e0c-f324-4af1-b5ca-13136e631a3e.png)
or
step 3.2 choose replacement cells and have error 
![error](https://user-images.githubusercontent.com/67575373/128208327-78bc3aca-4d8f-45b0-9d31-5cc8a1c4ebd1.png)

why? why have i error? can you help me?

**Comment by SheetJSDev** [comment]
pass the option `ignoreEC: true` on write.  Explainer:

> Due to a bug in the program, some features like "Text to Columns" will crash Excel on worksheets where error conditions are ignored. The writer will mark files to ignore the error by default. Set `ignoreEC` to `false` to suppress.

SheetJS normally sets the flag so that numbers stored as text won't be marked by Excel (cells like `{ t:"s", v:"12345" }`), so setting `ignoreEC: false` on write will cause those cells to be flagged in Green.

**Comment by AlexPilinni** [comment]
> ignoreEC: false

thanks, it helped me
