### ISSUE TITLE
More convenient for logs or bug

### ISSUE THREAD

**Issue by nivb52** [SheetJS/sheetjs#2346]
Hi
I have a pretty complex system which any table/grid in the system can be exported,
some times i get an error in the export processes : 
``` TypeError: s.t.match is not a function```
In order to debug it fast, I think it will be easy to add in the option a debug mode or log mode which be 
used in the ``` write_sst_xml ``` function, like so :
```
else {
			sitag += "<t";
			if(!s.t) s.t = "";
			if(opts.DEBUG)){				
                        	console.log(typeof s.t)
				console.log(s.t)
                        }
			if(s.t.match(straywsregex)) sitag += ' xml:space="preserve"';
			sitag += ">" + escapexml(s.t) + "</t>";
		}
```

later we can add private logger.
Do you think there is any use for this addon ?

**Comment by SheetJSDev** [comment]
You can pass the `WTF: 1` option to write or writeFile.  The docs don't currently state this (they say it for the read case) so we'll accept a PR that adds that info to the writing options table.

By default there are a bunch of try/catch blocks that suppress minor errors.  WTF mode bubbles them to the top.

If you need some deeper debugging help, `JSON.stringify` the workbook and send the JSON.  The issue should be reproducible by running `JSON.parse` and exporting the new object
