### ISSUE TITLE
Styling header or any row or cell

### ISSUE THREAD

**Issue by GusMartins499** [SheetJS/sheetjs#2348]
Hi guys, it's possible styling any cell or any row ?

Question 1: I want allow bold in all my header, i'ts possible ?
Question 2: I want put a formula at last row, i'ts possible ?

**Comment by SheetJSDev** [comment]
Styling is a feature in our [Pro offering](https://sheetjs.com/pro) while formulae are supported by setting the `f` field in the cells https://github.com/SheetJS/sheetjs#formulae
