### ISSUE TITLE
Why my formula (SUM) dosen't work ?

### ISSUE THREAD

**Issue by GusMartins499** [SheetJS/sheetjs#2351]
Hi guys, how are you ?
Somebody can help me, please ?

My code:
My data is array of arrays
I want sum all the column K and put the result in L1 or K5
```jsx
        var ws = XLSX.utils.aoa_to_sheet(data);
        var wb = XLSX.utils.book_new();
        ws['L1'] = { t:'n', f: "SUM(K3+K4)", F:"L1:L1" };
        XLSX.utils.book_append_sheet(wb, ws, "SheetJS");
        var buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', cellStyles: true });
        return response.status(201).send(buf);
```

My documtent:
![image](https://user-images.githubusercontent.com/43645525/129084874-19f4001d-865f-409c-8329-3255683c1d70.png)

**Comment by SheetJSDev** [comment]
L1 is probably outside of the original worksheet range.  You need to expand it to include the that column:

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
range.e.c = Math.max(range.e.c, XLSX.utils.decode_col("L")); // L -> 11
ws["!ref"] = XLSX.utils.encode_range(range);
```

Also you probably don't want to set `F: "L1:L1"` -- that is saying you want to create a single-cell array formula (in context, you probably want a standard formula)

**Comment by GusMartins499** [comment]
> L1 is probably outside of the original worksheet range. You need to expand it to include the that column:
> 
> ```js
> var range = XLSX.utils.decode_range(ws["!ref"]);
> range.e.c = Math.max(range.e.c, XLSX.utils.decode_col("L")); // L -> 11
> ws["!ref"] = XLSX.utils.encode_range(range);
> ```
> 
> Also you probably don't want to set `F: "L1:L1"` -- that is saying you want to create a single-cell array formula (in context, you probably want a standard formula)

I'm sorry @SheetJSDev but, i could not do it yet, can you help me again please ?

```jsx
        var ws = XLSX.utils.aoa_to_sheet(data);
        var wb = XLSX.utils.book_new();

        var range = XLSX.utils.decode_range(ws["!ref"]);
        range.e.c = Math.max(range.e.c, XLSX.utils.decode_col("L"));
        ws["!ref"] = XLSX.utils.encode_range(range);

        ws['L1'] = { t:'n', f: "SUM(K2:K5001)" };
        // ws['L1'] = { t:'n', f: "SUM(K2:K5001)", F: "L1:L1" };

        XLSX.utils.book_append_sheet(wb, ws, "SheetJS");
        var buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', cellStyles: true });
        return response.status(201).send(buf);
```

![Sem título](https://user-images.githubusercontent.com/43645525/129726678-a8c5aec4-07a6-4a85-9821-158b6d7bc57e.png)
