### ISSUE TITLE
Custom Data and Header with alias names

### ISSUE THREAD

**Issue by bindugvs** [SheetJS/sheetjs#2352]
For example...
[{a:1,b:2,c:3,d:5},{a:4,b:2,c:3,d:4}]
I need to export only 2 columns from the above data (only a,c)
How to do that ?

Also..I want to change the header from 'a' to 'A column' (something like this...)
How to do that ?

**Comment by SheetJSDev** [comment]
Reshape the data:

```js
var data = [{a:1,b:2,c:3,d:5},{a:4,b:2,c:3,d:4}]
var reshaped = data.map(row => ({A: row["a"], C: row["c"]}));
var ws = XLSX.utils.json_to_sheet(reshaped, { header: ["A", "C"]} );
```

Alternatively you can write using the old headers and then change the first row values afterwards.
