### ISSUE TITLE
how can i convert CSV charset from Shift-JIS to UTF-8

### ISSUE THREAD

**Issue by dovietvu** [SheetJS/sheetjs#2355]
Input data is a csv file with Japanese content: https://prnt.sc/1q42duv

//code
```
reader.onload = function (e) {
     var data = e.target.result;
     workbook = XLSX.read(data, { type: 'binary' })
     workbook.SheetNames.forEach(function (sheetName) {
          dataFileEx = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], { defval:"", raw: false, dateNF:'yyyy/mm/dd' })
          console.log(dataFileEx)
     })
}
```

Ouput: {åoH: "lL}Ì doda(¼Úå)", åú: "6/13/21", lL}Ì¼: "", l¼Ì: "X}zANZT[X^céÆÌ±^20ã«ðSÉô", lÞÐîïÐ¼: "", …}

how can i convert CSV charset from Shift-JIS to UTF-8? Thank you!

**Comment by reviewher** [comment]
You have to pass the appropriate codepage argument to `XLSX.read`.  Shift-JIS is 932 so it would be:

```js
     workbook = XLSX.read(data, { type: 'binary', codepage: 932 })
```

**Comment by dovietvu** [comment]
@reviewher thanks
