### ISSUE TITLE
 How to add data to the end of an already existing file?

### ISSUE THREAD

**Issue by xdarkki** [SheetJS/sheetjs#2359]
Existing File... "test.xlsx"
Example:
         A           B           
1| Names: | Reasons:
2| John      | ... 
3| Mark     | ... 
4| Dave     | ... 

Now add Names and in addition to the existing file... "test.xlsx"
         A           B           
1| Names: | Reasons:
2| John      | ... 
3| Mark     | ... 
4| Dave     | ... 
5| Josh      | ...

**Comment by SheetJSDev** [comment]
Using the community edition, you read the file, then append to the worksheet using `XLSX.utils.sheet_add_aoa` or `XLSX.utils.sheet_add_json` using the option `origin: -1`, then write.

Small demo https://jsfiddle.net/v46kgup3/ works in the web browser.  It fetches a file and adds a row:

```js
(async() => {
  const f = await fetch("https://sheetjs.com/pres.xlsx");
  const ab = await f.arrayBuffer();
  const wb = XLSX.read(ab, {type: "array"});
  const ws = wb.Sheets[wb.SheetNames[0]];
  XLSX.utils.sheet_add_aoa(ws, [["Joe Biden", 46]], {origin: -1});
  XLSX.writeFile(wb, "pres.xlsx");
})();
```

As part of our [Pro offering](https://sheetjs.com/pro) we have a special approach for editing worksheets that preserves more advanced features.
