### ISSUE TITLE
Ignore newlines when read xlsx files

### ISSUE THREAD

**Issue by dcr31000** [SheetJS/sheetjs#2360]
Hello,

I've got an issue when I read an XLSX file with some newlines in cells.

![image](https://user-images.githubusercontent.com/61591912/130035546-5b30cecf-ba90-4720-942c-a6c251dd1101.png)

After calling `XLSX.read(file, {type:'binary'});`,
SheetJS returned to me 3 lines instead of 2 because it think that \r means a new Excel line.

I would like to replace \r by " " or just ignore it.

Currently behovior:
...fax, "first line
second line", test..
...fax, test...

Expected behavior:
...fax, first line second line, test...
...fax, test, test...

Thanks for you help

**Comment by reviewher** [comment]
Please attach a sample file.  If the cell has CR characters, you should expect SheetJS to grab them

**Comment by dcr31000** [comment]
[sheetjsCrSample.xlsx](https://github.com/SheetJS/sheetjs/files/7013056/sheetjsCrSample.xlsx)

Please find attached a sample file. Thanks

**Comment by reviewher** [comment]
The conversion looks correct.  You can programmatically loop through each cell and remove the `\r` characters before exporting:

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
for(var R = range.s.r; R <= range.e.r; ++R) for(var C = range.s.c; C <= range.e.c; ++C) {
  var addr = XLSX.utils.encode_cell({r:R,c:C});
  if(!ws[addr] || ws[addr].t != "s") continue;
  ws[addr].v = ws[addr].v.replace(/\r/g, " ");
}
```

**Comment by dcr31000** [comment]
Thanks for your help but I don't understand what to do with this piece of code... I don't want to export but I want to read the sample file.
So, before the `XLSX.read(file, {type:'binary'})`, I can't loop through cells because It's not parsed yet. And after the `read` function, it's already broken.

**Comment by reviewher** [comment]
You read the workbook, then change the text:

```js
var wb = XLSX.read(file, {type:'binary'});
wb.SheetNames.map(n => wb.Sheets[n]).forEach(ws => {
  var range = XLSX.utils.decode_range(ws["!ref"]);
  for(var R = range.s.r; R <= range.e.r; ++R) for(var C = range.s.c; C <= range.e.c; ++C) {
    var addr = XLSX.utils.encode_cell({r:R,c:C});
    if(!ws[addr] || ws[addr].t != "s") continue;
    ws[addr].v = ws[addr].v.replace(/\r/g, " ");
  }
});
```
