### ISSUE TITLE
How can I set the cell format of a certain column to numbers

### ISSUE THREAD

**Issue by qzsk0921** [SheetJS/sheetjs#2361]
Hello brothers, How can I achieve the sum of the exported numbers (no need to double-click or sort the cells)

![20210819160504](https://user-images.githubusercontent.com/26791975/130031916-5326b808-435c-4c32-9e38-18f2c01beddd.png)

**Comment by reviewher** [comment]
Issue subject (setting cell format): set the `z` property of the cell object to the desired number format

Issue question (sum of exported numbers): set the `f` property of a cell to the formula you want, like `"SUM(A1:A5)"`

**Comment by qzsk0921** [comment]
thanks for the answer ! I'll try it ASAP
