### ISSUE TITLE
open link instead of download blob file

### ISSUE THREAD

**Issue by sagarjoshi786** [SheetJS/sheetjs#2362]
i am downloading excel file by using xlsx.writefile . but it redirects to another url instead of downloading excel.

redirection url contain blob:/ <identifier_id>

**Comment by reviewher** [comment]
Known issue with some browsers like iOS safari.  [Here is a very long discussion with more details](https://github.com/eligrey/FileSaver.js/issues/12).

**Comment by sagarjoshi786** [comment]
is there any workaround ?
