### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by khansrk** [SheetJS/sheetjs#2363]
import XLSX from 'xlsx';
const fs = require("fs");

function App() {
 
  const wb = XLSX.read(fs.readFileSync("cricket.xlsx"));
  const wsname = wb.SheetNames[0];
  const ws = wb.Sheets[wsname];
  const data = XLSX.utils.sheet_to_json(ws);
  console.log(data);

  return (
    <div className="App">
    </div>
  );
}

export default App;
I am getting the error that fs.readFileSync is not a function. How can I read the file ?

**Comment by SheetJSDev** [comment]
You can't use `XLSX.readFile` in the web browser.

> `readFile` is only available in server environments. Browsers have no API for reading arbitrary files given a path

You can put the file you want to read in a public folder and `fetch` it.  [Check the `xhr` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/xhr)
