### ISSUE TITLE
Export image cell from html table

### ISSUE THREAD

**Issue by osamasado** [SheetJS/sheetjs#2364]
Hello,
I have tried to export html table, that has a cell as <img> tag , to excel sheet, but it does not work, can you please help me to solv this issue?
`
var tbl = document.getElementById('data_table');
	var wb = XLSX.utils.table_to_book(tbl);
	XLSX.writeFile(wb, "SheetJS.xlsx");
`

**Comment by SheetJSDev** [comment]
General image support is a feature of our [Pro builds](https://sheetjs.com/pro)
