### ISSUE TITLE
Single quote in number formatted as text

### ISSUE THREAD

**Issue by andres-arcos** [SheetJS/sheetjs#2365]
Hi, I'm using aoa_to_sheet te create a xlsx file, but when the json field has only numbers, it appears with a leading single quote in the xlsx file. This field may content numbers or letters, so I need it to be text.
I have seen examples where the json object has numbers in text format, but those examples use table_to_sheet. Why with aoa_to_sheet is not working?

**Comment by reviewher** [comment]
`aoa_to_sheet` expects an array of arrays of values like 

```js
var aoa = [
  [ "a", "b", "c" ],
  [ 1, 2, 3 ]
];
```

If you pass strings like:

```js
var aoa = [
  [ "a", "b", "c" ],
  [ "1", "2", "3" ]
];
```

Those values are interpreted as text, not numbers, and are emitted as text values.  Excel automatically adds the leading apostrophe to indicate that the value is text.

**Comment by andres-arcos** [comment]
But in this example (https://jsfiddle.net/oq7Lo3m0/), in the json the number is within quotes, and in the excel, the leading apostrophe is not there.

**Comment by reviewher** [comment]
You can verify the cell types by using the [`TYPE` function in Excel](https://support.microsoft.com/en-us/office/type-function-45b4e688-4bc3-48b3-a105-ffa892995899).

Set F1 to the formula `TYPE("A1")` and fill across to I1 and down to I3.  You will see B2/C2/D2 return 1 (number) and the other cells return 2 (text)

**Comment by andres-arcos** [comment]
Yes, you are right. But why is that? because in the json the number is "12345" between quotes

**Comment by SheetJSDev** [comment]
There are multiple moving parts here.

`aoa_to_sheet` generates a worksheet object.  It will take a text value like `"12345"` and generate a text cell of the form `{t: "s", v: "12345"}`.  There is no attempt to interpret a string value.

`write` and `writeFile` expect numbers as the value for numeric cells (`t: "n"`).  So when you use a cell like `{t: "n", v: "12345" }` the value is interpreted as a number.  The same pattern holds true for Boolean cells (`t: "b"`), where `{t:"b", v: ""}` is interpreted as `FALSE` and `{t: "b", v: 1}` is interpreted as `TRUE`

**Comment by Ashishdeshmukh424** [comment]
@andres-arcos @SheetJSDev Hi Guys I am facing the same error, can you please guide us how to resolve it? Went through the discussion but not get the solution. Thanks
