### ISSUE TITLE
getting errorwhile using `sheet_to_json`

### ISSUE THREAD

**Issue by abuzarhamza** [SheetJS/sheetjs#2370]
hi All,

using xls sheet with 6300 row and it is throwing error

```
ake_json(aka sheet_to_json) [0x272e71c3ac91] [/var/task/node_modules/xlsx/xlsx.js:~19662] [pc=0x959667a4281](this=0x34cf5a8d7aa1 <Object map = 0x1648b1cd17d1>,sheet=0x2d3113eab9c1 <Object map = 0x28643c347b69>,opts=0x09ce1e2826f1
 <undefined>)
```

not sure what is the issue. Need input from community

node version :  `10.x`
module version:  `^0.11.6`

**Comment by reviewher** [comment]
That's a NodeJS issue.  Please upgrade to the latest version of the module and nodejs and reopen if you see the same problem
