### ISSUE TITLE
After merged column, value vanish

### ISSUE THREAD

**Issue by GusMartins499** [SheetJS/sheetjs#2371]
Hi guys, someone can help-me ?
I trying to merge cells, but, after merge a cell, the value vanish

My code:
```js

const planilhaCompleta = [...cabecalho, ...planilha];

var ws = XLSX.utils.aoa_to_sheet(planilhaCompleta);
var wb = XLSX.utils.book_new();

ws['!merges'] = [
     { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
     { s: { r: 0, c: 4 }, e: { r: 0, c: 5 } },
     { s: { r: 0, c: 6 }, e: { r: 0, c: 7 } },
]

XLSX.utils.book_append_sheet(wb, ws, 'Relatorio');

var buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', cellStyles: true, });

return response.status(201).send(buf);
```

My document before merge cell
![image](https://user-images.githubusercontent.com/43645525/131384227-6a8253ef-5bf9-4734-8f5b-3b92c32daeaa.png)

My document after merge cell
![image](https://user-images.githubusercontent.com/43645525/131383852-6d159083-16ef-4c38-9478-f0df47889664.png)

packAge.json

```json
"xlsx": "^0.17.1",
"react": "^16.12.0",
"node": "v12.20.1"
```

**Comment by reviewher** [comment]
```js
ws['!merges'] = [
     { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
     { s: { r: 0, c: 4 }, e: { r: 0, c: 5 } },
     { s: { r: 0, c: 6 }, e: { r: 0, c: 7 } },
]
```

The merged blocks are C1:D1, E1:F1, G1:H1.  The cell values used in the merge are the upper-left cell of each block, in this case C1/E1/G1 respectively.  The other cells are not used.

If you want to specify text ranges, use `decode_range`:

```js
ws['!merges'] = [
     XLSX.utils.decode_range("C1:D1"),
     XLSX.utils.decode_range("E1:F1"),
     XLSX.utils.decode_range("G1:H1"),
]
```

**Comment by GusMartins499** [comment]
> ```js
> ws['!merges'] = [
>      { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
>      { s: { r: 0, c: 4 }, e: { r: 0, c: 5 } },
>      { s: { r: 0, c: 6 }, e: { r: 0, c: 7 } },
> ]
> ```
> 
> The merged blocks are C1:D1, E1:F1, G1:H1. The cell values used in the merge are the upper-left cell of each block, in this case C1/E1/G1 respectively. The other cells are not used.
> 
> If you want to specify text ranges, use `decode_range`:
> 
> ```js
> ws['!merges'] = [
>      XLSX.utils.decode_range("C1:D1"),
>      XLSX.utils.decode_range("E1:F1"),
>      XLSX.utils.decode_range("G1:H1"),
> ]
> ```

I guess that not worked. Did i something wrong ?

My document:
![image](https://user-images.githubusercontent.com/43645525/131498202-81b3a4c1-126f-40d5-bff0-fbb86f9d16c7.png)

Code:

```jsx
const planilhaCompleta = [...cabecalho, ...planilha];

          var ws = XLSX.utils.aoa_to_sheet(planilhaCompleta);
          var wb = XLSX.utils.book_new();

          /*           const arrayMerges = [
            { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
            { s: { r: 0, c: 4 }, e: { r: 0, c: 4 } },
            { s: { r: 0, c: 5 }, e: { r: 0, c: 5 } },
            { s: { r: 0, c: 6 }, e: { r: 0, c: 6 } },
            { s: { r: 0, c: 7 }, e: { r: 0, c: 7 } },
            { s: { r: 0, c: 8 }, e: { r: 0, c: 8 } },
            { s: { r: 0, c: 9 }, e: { r: 0, c: 9 } },
            { s: { r: 0, c: 10 }, e: { r: 0, c: 10 } },
            { s: { r: 0, c: 11 }, e: { r: 0, c: 11 } },
            { s: { r: 0, c: 12 }, e: { r: 0, c: 12 } },
            { s: { r: 0, c: 13 }, e: { r: 0, c: 13 } },
            { s: { r: 0, c: 14 }, e: { r: 0, c: 14 } },
          ]; */

          /*           for (const merge of arrayMerges) {
            console.log('merge ', merge);
            ws['!merges'].push(merge);
          } */

          /*           ws['!merges'] = [
            { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
            { s: { r: 0, c: 4 }, e: { r: 0, c: 5 } },
            { s: { r: 0, c: 6 }, e: { r: 0, c: 7 } },
          ] */
          //ws['!merges'] = [];
          ws['!merges'] = [
            XLSX.utils.decode_range("C1:D1"),
            XLSX.utils.decode_range("E1:F1"),
            XLSX.utils.decode_range("G1:H1"),
          ]

          XLSX.utils.book_append_sheet(wb, ws, 'Relatorio');

          var buf = XLSX.write(wb, {
            type: 'buffer',
            bookType: 'xlsx',
            cellStyles: true,
          });
          return response.status(201).send(buf);
```

**Comment by GusMartins499** [comment]
> ```js
> ws['!merges'] = [
>      { s: { r: 0, c: 2 }, e: { r: 0, c: 3 } },
>      { s: { r: 0, c: 4 }, e: { r: 0, c: 5 } },
>      { s: { r: 0, c: 6 }, e: { r: 0, c: 7 } },
> ]
> ```
> 
> The merged blocks are C1:D1, E1:F1, G1:H1. The cell values used in the merge are the upper-left cell of each block, in this case C1/E1/G1 respectively. The other cells are not used.
> 
> If you want to specify text ranges, use `decode_range`:
> 
> ```js
> ws['!merges'] = [
>      XLSX.utils.decode_range("C1:D1"),
>      XLSX.utils.decode_range("E1:F1"),
>      XLSX.utils.decode_range("G1:H1"),
> ]
> ```

Can you help-me again please ?

**Comment by Volume3** [comment]
Hi, did you solve this problem? I have the same problem
