### ISSUE TITLE
Parsing date format issues

### ISSUE THREAD

**Issue by fengguibin1** [SheetJS/sheetjs#2372]
The data in excel is ‘’2021/08/23‘’ but parsed out ‘’Sun Aug 22 2021 23:59:17 GMT+0800 (中国标准时间)‘’
43 seconds difference in accuracy。The error occurred on Google, no problem on Firefox。version：xlsx@0.14.5  in China

**Comment by reviewher** [comment]
Same issue as https://github.com/SheetJS/sheetjs/issues/1918 and https://github.com/SheetJS/sheetjs/issues/2350 .  It is a V8 chrome + nodejs bug, see https://github.com/nodejs/node/issues/33306 and https://bugs.chromium.org/p/v8/issues/detail?id=7863 for more details.

The anchor date is the midnight of December 31 1899 / January 1 1900.  `Asia/Hong_Kong` and other asian timezones had a timezone offset that had a second component:

```
# Zone	NAME		STDOFF	RULES	FORMAT	[UNTIL]
Zone	Asia/Hong_Kong	7:36:42 -	LMT	1904 Oct 30  0:36:42
```

V8 does not properly represent these, hence the difference.

The only thing SheetJS can do is re-anchor to a date after the timezone was changed.

**Comment by fengguibin1** [comment]
Thanks my friend. So is there any good solution to this issue, besides handling it manually.

**Comment by SheetJSDev** [comment]
Moving discussion to https://github.com/SheetJS/sheetjs/issues/1565
