### ISSUE TITLE
Some strings returns INIFINITY

### ISSUE THREAD

**Issue by frantique** [SheetJS/sheetjs#2373]
Settings applied: **raw: true, rawNumbers: true**
Example of string wrong interpreted:
"3E17773446"

The whole row in CSV was:
"86","3E17773446","For sale ","5/5/2021 11:12:18 AM"

**Comment by frantique** [comment]
Thank you!

**Comment by with-shrey** [comment]
@SheetJSDev Can i take this up ?

**Comment by Swastik2000** [comment]
@SheetJSDev @reviewher 
Can I work on this issue?

**Comment by SheetJSDev** [comment]
e7346ddfbe4ae40d8193e558cc61dc7eb6ea9511
