### ISSUE TITLE
How to save the json string in the cell?

### ISSUE THREAD

**Issue by Antecer** [SheetJS/sheetjs#2374]
the json like this:
```[{"title": "xxxxx","number": 1},{"title": "xxx","number": 1}]```

but when i save it in cell, there only have  ```[{```, the other content will be lost.
I think the data is truncated by double quotes, maybe an escape is needed here?

**Comment by reviewher** [comment]
How are you generating the workbook?

**Comment by SheetJSDev** [comment]
You cannot read a raw JSON string using `XLSX.read` (Excel does not support it either).  If you want to stick it in a cell in a CSV file, use Excel's quoting rules:

```js
var json = '[{"title": "xxxxx","number": 1},{"title": "xxx","number": 1}]';
XLSX.read('"' + json.replace(/"/g, '""') + '"', {type: "string"})
```
