### ISSUE TITLE
Date getting converted while reading from CSV file

### ISSUE THREAD

**Issue by abilash-cts** [SheetJS/sheetjs#2375]
Hello,

I am trying to read CSV file that has date value. It is observed that value read from date cell is including time zone value. I have observed 2 different weird behaviors:

1. In one of the CSV file, date value of `3/29/1981` returns `Sun Mar 29 1981 00:00:00 GMT+0530 (India Standard Time)`.
2. In another CSV file, the date `2021-09-28` returns `Tue Sep 28 2021 23:59:50 GMT +0530`. 

In first scenario, reading value from cell returns `3/29/1981` which is expected. In second scenario, reading value from cell returns `09/28/2021` which is a day before.

I am still not sure what caused second CSV file to have time value (`23:59:50`) which is causing the conversion, while the first one CSV has `00:00:00` for all cells.

Is there any workaround to get correct date value. 

Thanks in advance.

Please note, the issue is not there when read from Excel file.

**Comment by SheetJSDev** [comment]
So that it can be reproduced, can you share the current timezone and the JS environment (web browser/version or nodejs version or other platform)?

**Comment by SheetJSDev** [comment]
Assuming timezone `Asia/Kolkata`, dates are anchored to the beginning of 1900.  [A 10-second change in 1906 is not correctly reflected in Chrome](https://bugs.chromium.org/p/v8/issues/detail?id=7863)

Combining with https://github.com/SheetJS/sheetjs/issues/2196
