### ISSUE TITLE
How to do the cell styling?

### ISSUE THREAD

**Issue by sathish1201** [SheetJS/sheetjs#2380]
i have used xlsx.min.js cdn to create a xlsx file. but not able to do styling. because styling code is not working.....do I need to include any specific cdn for styling.....i want to color the header columns with bgcolor based on some conditions....and i want to change the text color whan there is a negative value.

Here is my code
getJsonDataToSheet() {
				console.log(this.arr);
                const fileName = 'test.xlsx';
                var ws = XLSX.utils.json_to_sheet(this.arr);
                var wb = XLSX.utils.book_new();
                
                XLSX.utils.book_append_sheet(wb, ws, 'test');
                ws["A1"].s = {
                fill: {
                    patternType: "solid",
                    bgColor: { rgb: "FFFFAA00" }
                    }
                };
                XLSX.writeFile(wb, fileName);
                console.log('Json to sheet completed');
                this.display = 'Json to sheet completed';
			},

**Comment by SheetJSDev** [comment]
Styling is a feature of our [Pro builds](https://sheetjs.com/pro)
