### ISSUE TITLE
Header with aoa and the data with json_to_sheet

### ISSUE THREAD

**Issue by softone-as** [SheetJS/sheetjs#2381]
I try to write a header manually from the scratch using **aoa_to_sheet()**. I define the header staticly using array and then I create a worksheet with the data array to be header. (Cause i dont wanna get rid with key of object). And then i append the export data to excel using **sheet_add_json()** method. Is possible to do that things?

**Comment by reviewher** [comment]
Yes, pass the option `origin: -1`:

```js
var ws = XLSX.utils.aoa_to_sheet([
  ["Item", "Price"]
]);
XLSX.utils.sheet_add_json(ws, [
  { Item: "abc", Price: 1.23 },
  { Item: "def", Price: 4.56 },
], {origin: -1, skipHeader: true});
XLSX.utils.sheet_add_json(ws, [
  { Item: "ghi", Price: 7.89 },
], {origin: -1, skipHeader: true});
```
