### ISSUE TITLE
I have a problem with readFile

### ISSUE THREAD

**Issue by Bruno-Goudric** [SheetJS/sheetjs#2382]
Hello 

I have problem with readFile where my File have a 10000 register but this lib is not prepared for read file very large, It's correct ?
My code

`public async readData (
    filepath: string,
    sheetName: string,
    company: string
  ): Promise<IExcelVariablesDTO[]> {

    const loadedFile = xlsx.readFile(filepath)

    

    if (loadedFile) {
      const excelData = xlsx.utils.sheet_to_json<IExcelVariablesDTO>(
         loadedFile.Sheets[sheetName]
      )      
      
      const excelDataFiltered = excelData.filter(dado => dado.Empresa === company) 

      
      return excelDataFiltered
      
    } else {
      throw new NMLError('Invalid excel file')
    }
  }
`

**Comment by reviewher** [comment]
Can you share the file?

**Comment by Bruno-Goudric** [comment]
Yes, give me your e-mail, please

**Comment by SheetJSDev** [comment]
hello@sheetjs.com
