### ISSUE TITLE
Paste directly from excel into React App

### ISSUE THREAD

**Issue by johnwick1986** [SheetJS/sheetjs#2384]
Hello. I just found out this library, as I am trying to find a way to copy from any excel file and paste the content directly into a React App, without having to import the file. I'm looking into the documentation, but it is still a bit confusing. I would like to know if this is possible and, if so, what part of the documentation would be most recommend to search, in order to apply a solution for this issue.

Thanks in advance

**Comment by reviewher** [comment]
If you are copying from Excel and pasting in your web app, start from the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API).  You can get the clipboard data and parse it to recover the cell data

**Comment by johnwick1986** [comment]
Thank you for the information. I thought the library might be able to help in doing so, but I will look into the documentation, to see if I can do that task. 

Thank you so much

**Comment by johnwick1986** [comment]
I apologize, but this is still very new to me, as I'm still learning. Would it be possible for you to give me some hints or steps I should follow to achieve the task, if that isn't too much trouble, I mean?

Thanks in advance

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/getting-started/demos/clipboard
