### ISSUE TITLE
 link how not to remove "#"

### ISSUE THREAD

**Issue by zhangjingyu1024** [SheetJS/sheetjs#2385]
`ws['A1'].l = { Target: 'http://1234.com/#/name=tom&age=23' };`

Links with "#" will be removed, and the following parameters will be removed. How to make the URL complete with "#"? For example: http://1234.com/#/name=tom&age=23 ， I need help！！

**Comment by SheetJSDev** [comment]
Cannot reproduce in 0.17.1.  Run `console.log(XLSX.version)` and ensure you are on the latest version:

```js
var wb = XLSX.utils.book_new();
var ws = XLSX.utils.aoa_to_sheet([["A1"]]);
ws['A1'].l = { Target: 'http://1234.com/#/name=tom&age=23' };
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue2385.xlsx")
```

https://jsfiddle.net/xonjyr8b/

This generates a file with cell A1 linking to "http://1234.com/#/name=tom&age=23".  If you can share more details (what file format you are using?, are you somehow modifying the worksheet later?) we can reopen the issue.

**Comment by zhangjingyu1024** [comment]
In this way, the '#' in the xlsx file hyperlink has been removed. The XLS file has' # ', but will be converted to'% 23 'when jumping to the web page.The device is a Mac

**Comment by zhangjingyu1024** [comment]
n this way, the '#' in the xlsx file hyperlink has been removed. The XLS file has' # ', but will be converted to'% 23 'when jumping to the web page.The device is a Mac

**Comment by SheetJSDev** [comment]
The XLSX file looks correct: [issue2385-result.xlsx](https://github.com/SheetJS/sheetjs/files/7222118/issue2385-result.xlsx)

Open the file in Excel, right-click the cell and Edit Hyperlink.  Locally it looks like 
<img width="500" alt="issue2385-Edit-Hyperlink" src="https://user-images.githubusercontent.com/6070939/134614270-bbe779e5-3ea8-4848-918f-9df7fbd00b9d.png">

The address appears to be correct.
