### ISSUE TITLE
Corrupted zip : can't find end of central directory

### ISSUE THREAD

**Issue by hutao96** [SheetJS/sheetjs#2386]
```
Uncaught Error: Corrupted zip : can't find end of central directory
    at u.readEndOfCentral (xlsx.core.min.js:2)
    at u.load (xlsx.core.min.js:2)
    at new u (xlsx.core.min.js:2)
    at n.r.exports [as load] (xlsx.core.min.js:2)
    at new n (xlsx.core.min.js:2)
    at lp (xlsx.core.min.js:15)
    at Object.vp [as read] (xlsx.core.min.js:15)
```

when i try to read xlsx file this error appear，when  i try to read xls file it is ok
here is my code

```js
function importf(obj) {
    if(!obj.files) {
        return;
    } 
    var f = obj.files[0];
    //var fileExtension = f.name.replace(/^.*\./, '');
    var reader = new FileReader();
    reader.onload = function(e) {
        //var data = e.content;
        var data = e.target.result;
        if(rABS){
        	wb = XLSX.read(btoa(fixdata(data)), {
                type: 'base64'
            });
        } else {
            wb = XLSX.read(data, {
                type: 'binary'
            });
       	}
       	
        excelTab = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
        console.log(excelTab);
       	printData(excelTab);
    };
    if(rABS) {
       reader.readAsArrayBuffer(f);
   	} else {
       reader.readAsBinaryString(f);
    }
}
```

**Comment by SheetJSDev** [comment]
Some of the older code recommended `readAsBinaryString` but it is not really recommended in 2020.  Try with `readAsArrayBuffer` directly:

```js
function importf(obj) {
    if(!obj.files) {
        return;
    } 
    var f = obj.files[0];
    //var fileExtension = f.name.replace(/^.*\./, '');
    var reader = new FileReader();
    reader.onload = function(e) {
        var data = e.target.result;
        wb = XLSX.read(data, {
            type: 'array'
        });
       	
        excelTab = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
        console.log(excelTab);
        printData(excelTab);
    };
    reader.readAsArrayBuffer(f);
}
```

**Comment by hutao96** [comment]
i used your new code, the error disappear ,but my browser stuck ，does the data need special handling?
or using like this code?
function importf(obj) {
    if(!obj.files) {
        return;
    } 
    var f = obj.files[0];
    var reader = new FileReader();
    reader.onload = function(e) {
        var data = e.target.result;
        var fixedData = fixdata(data);
        wb = XLSX.read(btoa(fixedData), { type: 'base64' });
        excelTab = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
        console.log(excelTab);
        printData(excelTab);
    };
    reader.readAsArrayBuffer(f);
}
    function fixdata(data) { 
        var o = "",
        l = 0,
        w = 1024;
        for(; l < data.byteLength / w; ++l) o += String.fromCharCode.apply(null, new Uint8Array(data.slice(l * w, l * w + w)));
        o += String.fromCharCode.apply(null, new Uint8Array(data.slice(l * w)));
        return o;
    }

**Comment by reviewher** [comment]
Please share a sample file

**Comment by hutao96** [comment]
Thank you everyone, my problem is solved, it is the problem of the file itself。
