### ISSUE TITLE
Browser tries to open all kind of files when integrating sheetjs

### ISSUE THREAD

**Issue by PWRM** [SheetJS/sheetjs#2389]
Included sheetjs in a Joomla article. The Excel parsing works like a charm. I have a problem, and did not find any solutions on the web. When the page loads, a file is exported called: sheetjs.prn. It is saved directly into my downloads folder.
On Firefox browser, I get appr 20 files that Firefox stores as a temp file in the download folder, and prompts like it want to open. Some examples:
You have chosen to open:sheetsjs.prn
You have chosen to open:sheetsjs.rtf
You have chosen to open:sheetsjs.dbf
You have chosen to open:sheetsjs.dif

The contents of ssheetjs.prn:

1          200%      3
--
TRUE       FALSE               sheetjs
foo    bar baz       2/19/14   0.3
baz                  ‡ØÆ         3.14159
hidden
visible

Why does this happen & how can I get rid of this?

**Comment by SheetJSDev** [comment]
It sounds like you are loading [`tests/write.js`](https://github.com/SheetJS/sheetjs/blob/master/tests/write.js) in your code.  That [script tries to write 20 files](https://github.com/SheetJS/sheetjs/blob/master/tests/write.js#L175-L194) including `sheetjs.prn`, and as the script name suggests it was a test for writing a bunch of file formats :)

For browser use, you only need to load the `dist/xlsx.full.min.js` file or use a CDN like unpkg https://unpkg.com/xlsx

**Comment by PWRM** [comment]
OK, expected I needed more files than just xlsx.full.min.js. Removed everything except this one and solved. Appreciated!
