### ISSUE TITLE
Corruption of XLS file starting 0.15.2

### ISSUE THREAD

**Issue by lpatiny** [SheetJS/sheetjs#2390]
Since version 0.15.2 the attached file is not parsed correctly.

It worked correctly with 0.15.1

[TEST2.xls.zip](https://github.com/SheetJS/sheetjs/files/7178394/TEST2.xls.zip)

**Comment by SheetJSDev** [comment]
Feel free to submit a PR: https://github.com/SheetJS/sheetjs/blob/master/bits/87_read.js#L86

```diff
-		case 0x09: if(n[1] <= 0x04) return parse_xlscfb(d, o); break;
+		case 0x09: if(n[1] <= 0x08) return parse_xlscfb(d, o); break;
```

**Comment by vishaluchil** [comment]
Is it okay if I do it?

**Comment by Mikecarbon** [comment]
127
