### ISSUE TITLE
Empty array when sheetname has spaces

### ISSUE THREAD

**Issue by shamseerahammedm** [SheetJS/sheetjs#2393]
I'm trying to read exel file and its has sheetnames with spaces 

Sheet with sheet name as **'Something One'** -> does'nt read gives empty array
Sheet with sheet name as **'SomethingOne'** -> reads gives data back

is this a configuration level thing or a bug ?

```
const bufferArray = e?.target?.result;
const wb = XLSX.read( bufferArray, { type: 'array' } );
const wsname = wb.SheetNames[7];
const ws = wb.Sheets[wsname];
const data = XLSX.utils.sheet_to_json(ws, {
  defval:'',
  raw : true,
  header : ['OrderType','Time','Date','Volume','Rate','Amount']
});

console.log('data', data) -> empty array 
```

`

**Comment by SheetJSDev** [comment]
Can you share the original file?

**Comment by reviewher** [comment]
Please share the actual file and we will reopen the issue
