### ISSUE TITLE
Formatted value treated as formula

### ISSUE THREAD

**Issue by lee00678** [SheetJS/sheetjs#2397]
I'm using sheet_add_aoa to add an array of already formatted values. ["$1.23", "$1.56"]
It seems the cell value was being treated as formula instead of currency, hence when I want to apply sum on the exported excel sheet, it won't work.

Any suggestions?

**Comment by SheetJSDev** [comment]
String values are serialized as string cells.  To generate currency values, pass number cell objects with the relevant format:

```js
XLSX.utils.sheet_add_aoa(ws, [
  [ { t: "n", v: 1.23, z: "$0.00"}, { t: "n", v: 1.56, z: "$0.00"} ] 
], opts);
```
