### ISSUE TITLE
How to wrap the column text with fixed width 

### ISSUE THREAD

**Issue by jaintrai11** [SheetJS/sheetjs#2399]

**Comment by jaintrai11** [comment]
How to wrap the text with fixed width

**Comment by SheetJSDev** [comment]
Text wrapping and other styling features are included in our [Pro builds](https://sheetjs.com/pro) and may make it here after our v1.0.0 release

**Comment by akamai-dev1** [comment]
@SheetJSDev do you have a documentation page for the pro version?
