### ISSUE TITLE
(if applicable)What does this sentence mean?

### ISSUE THREAD

**Issue by etjson** [SheetJS/sheetjs#2400]
![image](https://user-images.githubusercontent.com/41315967/135006584-9c13e2df-a936-4d41-a394-02e38491c118.png)

```text
s	the style/theme of the cell (if applicable)
```

(if applicable)
What does this sentence mean? I configure the background color of the cells are invalid.

**Comment by etjson** [comment]
@SheetJSDev

**Comment by SheetJSDev** [comment]
Some of the old background color parsing logic from 2013 is still in the source.

At the time, it was apparent that a correct cross-format implementation of full Excel styling would require significant development and investigative effort, beyond the scope of a team of unpaid volunteers.  LibreOffice is effectively 36 years old (StarOffice first release was 1985, OpenOffice was effectively the open-sourcing of StarOffice tech, and LibreOffice is a fork of OpenOffice) and still does not correctly handle certain styling.

The original purpose of the library was data preservation and extraction, and most of the open source energy is devoted to data.  For example, the [SSF library](https://github.com/SheetJS/ssf) exists to make CSV writing consistent with Excel.  We do hope to reach a point where we're happy with the state of data processing (v1.0.0) after which we can revisit styling.

In the interim, we offer more detailed styling and more advanced features as part of our [Pro offering](https://sheetjs.com/pro).  Many improvements in this project stem from issues that Pro users first encounter and report.
