### ISSUE TITLE
Sheet Visibility seems to not work

### ISSUE THREAD

**Issue by snoob** [SheetJS/sheetjs#2401]
Hi.

I tried to parse a xlsx generated by Crystal Report (SAP) with 2 sheets : The first one is hidden and the second one is visible.
According to the documentation : 
- The first sheet value should be 1 or 2. The actual value is 0
- The second sheet should be 0 and the actual value is 1.

I tried with another self-made file created with MS excel with 2 sheets visibles. I have the same result the first one value is 0 and the second one is 1.
The lib seems to always assign these values. 

Did i miss something ?
Is anyone else noticed the same thing ?

Thank you for your answer

**Comment by SheetJSDev** [comment]
Can you share both files?

https://github.com/SheetJS/test_files/blob/master/sheet_visibility.xlsx?raw=true was the original test artifact (there are similar files for XLSB, XLS and other formats).  Testing with nodejs on a mac:

```
$ curl -L -o sheet_visibility.xlsx https://github.com/SheetJS/test_files/blob/master/sheet_visibility.xlsx?raw=true
$ node -pe 'require("xlsx").readFile("sheet_visibility.xlsx").Workbook.Sheets.map(x => [x.name, x.Hidden])'
[ [ 'Visible', 0 ], [ 'Hidden', 1 ], [ 'VeryHidden', 2 ] ]
```

There are 3 worksheets in the file.  To see the "Hidden" worksheet in Excel, right-click the tab bar and click "Unhide" and choose "Hidden".  To see the "VeryHidden" sheet, pull up the Visual Basic editor, then select "Sheet3 (VeryHidden)" in the objects list and change the "Visible" property to "-1 - xlSheetVisible"

**Comment by snoob** [comment]
@SheetJSDev thx for fast answer

**Comment by snoob** [comment]
[empty-file.xlsx](https://github.com/SheetJS/sheetjs/files/7247995/empty-file.xlsx)
[file-with-data.xlsx](https://github.com/SheetJS/sheetjs/files/7247996/file-with-data.xlsx)

**Comment by SheetJSDev** [comment]
Can you check if you are using the latest version of the library?  `console.log(XLSX.version)`.  The result looks correct:

```
$ node -pe 'require("xlsx").version'
0.17.2
$ curl -LO https://github.com/SheetJS/sheetjs/files/7247996/file-with-data.xlsx
$ node -pe 'require("xlsx").readFile("file-with-data.xlsx").Workbook.Sheets.map(x => [x.name, x.Hidden])'
[ [ '_com.sap.ip.bi.xl.hiddensheet', 2 ], [ 'Feuil1', 0 ] ]
$ curl -LO https://github.com/SheetJS/sheetjs/files/7247995/empty-file.xlsx
$ node -pe 'require("xlsx").readFile("empty-file.xlsx").Workbook.Sheets.map(x => [x.name, x.Hidden])'
[ [ 'Feuil1', 0 ] ]
```

`file-with-data.xlsx` has 2 worksheets, the first of which is very hidden.  `empty-file` has 1 visible worksheet.

**Comment by snoob** [comment]
My version is 0.17.0. 

I try to update thank you !

**Comment by snoob** [comment]
I updated to 0.17.2 and still have the issue :( 

```
Object.keys(workSheet.Sheets).forEach((name, hidden) => {
              console.log(name)
              console.log(hidden)
```
_com.sap.ip.bi.xl.hiddensheet
0
Feuil1
1

Which version did you use above please ?

**Comment by snoob** [comment]
Really sorry for this >.<
