### ISSUE TITLE
xlsx.utils.read different results for same numbers

### ISSUE THREAD

**Issue by clopend** [SheetJS/sheetjs#2403]
![image](https://user-images.githubusercontent.com/23031401/135248075-3b05b674-6e5b-455b-bab0-fd2f2e99ea0d.png)
![image](https://user-images.githubusercontent.com/23031401/135253482-f92b03f1-1212-49d3-9ca1-7ab5e4a2ac28.png)

**Comment by clopend** [comment]
[example.xlsx](https://github.com/SheetJS/sheetjs/files/7251193/example.xlsx)
here is the file, thanks

**Comment by SheetJSDev** [comment]
Those are the actual numbers stored in the file:

```xml
      <c r="F1" s="4">
        <v>4.0000000000000007E-4</v>
      </c>
      <c r="F2" s="6">
        <v>7.9600000000000004E-2</v>
      </c>
      <c r="F3" s="6">
        <v>4.0000000000000002E-4</v>
      </c>
```

The `w` field is the formatted text (which should look like what you see in Excel), but under the hood Excel is storing those values because 0.0004 and 0.0008 cannot exactly be represented in IEEE754 floating point

**Comment by clopend** [comment]
@SheetJSDev  Thank you for your reply.
