### ISSUE TITLE
Error: Cannot find file [Content_Types].xml in zip

### ISSUE THREAD

**Issue by emanresuwenaretne** [SheetJS/sheetjs#2407]
Error: Cannot find file [Content_Types].xml in zip Get this error.

Is there an example for generating online sheeting using JSON? Would like to know that too. Thanks.

**Comment by SheetJSDev** [comment]
That looks like a read error.  Can you share the file?

.

To write an array of data rows like `[{Item: "abc", Price: 1}, {Item: "def", Price: 2}]`, there are 3 steps:

1) convert data to a worksheet:

```js
var data = [{Item: "abc", Price: 1}, {Item: "def", Price: 2}];
var ws = XLSX.utils.json_to_sheet(data);
```

2) create a workbook with the worksheet:

```js
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
```

3) write the file:

```js
XLSX.writeFile(wb, "test.xlsx");
```

Fiddle: https://jsfiddle.net/o8vwrxs3/

**Comment by emanresuwenaretne** [comment]
Thanks. How to show XLSX on the screen? As a DIV?

**Comment by emanresuwenaretne** [comment]
Basically I am trying to do this - https://stackoverflow.com/questions/69442921/create-online-sheets-using-c-sqlserver-and-angularjs
