### ISSUE TITLE
Example to use sheetjs in AngularJS to create HTML from JSON data with multiple tabs. 

### ISSUE THREAD

**Issue by emanresuwenaretne** [SheetJS/sheetjs#2408]
I am looking to do - https://stackoverflow.com/questions/69442921/create-online-sheets-using-c-sqlserver-and-angularjs

Is there an example I can refer for this requirement? Thanks!

**Comment by reviewher** [comment]
C# and SQL Server are out of scope.  Assuming you have JSON data, you can apply the approach in the angular demo: https://github.com/SheetJS/sheetjs/tree/master/demos/angular

For each worksheet data, call `json_to_sheet` to generate worksheet objects and `book_append_sheet` to add each sheet to a common workbook before exporting

**Comment by emanresuwenaretne** [comment]
So I have to create the HTML markup as follows always? 

<tr><th>Name</th><th>Index</th></tr>
  <tr ng-repeat="row in data">
    <td>{{row.Name}}</td>
    <td>{{row.Index}}</td>
  </tr>
