### ISSUE TITLE
reading UTF-8 .csv files with special characters

### ISSUE THREAD

**Issue by florianze** [SheetJS/sheetjs#2413]
Hey there,

i working with the extendscript version of sheet.js on a script for an Adobe tool - i am trying to read/parse a .csv file that was generated from Google Spreadsheets (UTF-8 with no BOM by default, can not change that). When reading the file using readFile, the strings inside don't seem to be interpreted as expected, for example: 

`Umlaute sind: ÖÄÜ`

turns to

`Umlaute sind: ÃÃÃ`

I have tried various combinations of parsing options:
- using different types (strings, binary)
- raw both true/false
- codepage 65001

But i can not seem to get the strings over into my script properly. Unfortunately, i can not change the way google spreadsheets creates the .csv files, but it is part of the clients' workflow. 

What am i missing? Any help would be greatly appreciated. Thanks!

**Comment by reviewher** [comment]
(codepage: 65001) for CSV was fixed in 3af23c31dd563dee90c8e44071a5fde5e1caabfe and will be live in the next release
