### ISSUE TITLE
Save and load data

### ISSUE THREAD

**Issue by Albacons** [SheetJS/sheetjs#2419]
I need to save data in the spreadsheet i.e. sending them to a web API.
Then in a future access to the page I want to reload saved data into the spreadsheet.
Calling the web API is not an issue.
My problem is I don't understand how to get spreadsheet data by pushing the save button instead of pushing the xlsx for download and what to do with the same data to reload them in the spreadsheet.
I'am going crazy.
Some one may help me?
THANK YOU EVERYBODY

**Comment by SheetJSDev** [comment]
It is unclear what you are asking.  Please take a look at some of [the demos](https://github.com/SheetJS/sheetjs/tree/master/demos) for inspiration.  In general:

`XLSX.write(workbook, {type: "array", bookType: "xlsx"})` will generate an ArrayBuffer that you can pass around.  It will be the raw file, and it will not effectuate a download.

To add data into a worksheet, use `XLSX.utils.sheet_add_aoa`.  To get data from a workbook, use `XLSX.utils.sheet_to_json`.  You can find those in the documentation.
