### ISSUE TITLE
in browser, load xlsx.full.min.js via jQuery, weird error will occur ....

### ISSUE THREAD

**Issue by coollofty** [SheetJS/sheetjs#2424]
Import it by <script> tag in html, all is ok.

But if I use jQuery's getScript function to import it, then various problems arise...
First, call XLSX.writeFile will cause the current page to become blank
Second, the file will not start download
Third, I commented out the writeFile caller code, cleared the browser’s cache and started again, the browser died ....

Test in chrome(newest version) and Firefox(newest version), all the same

**Comment by coollofty** [comment]
Sorry, I used it in my project, and the project is more complicated. Sharing on the Internet is more difficult.

**Comment by SheetJSDev** [comment]
Can't reproduce.  To test, download the script:

```bash
$ mkdir js
$ cd js
$ curl -LO https://cdn.jsdelivr.net/npm/xlsx@0.17.3/dist/xlsx.full.min.js
$ cd -
```

Then write the following to `index.html`:

```html
<body>
<table id="test"><tr><td>abc</td></tr></table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
(function($) {
  $(document).ready(function() {
    $.getScript('js/xlsx.full.min.js').done(function() {
      var table = $("#test").get(0);
      var wb = XLSX.utils.table_to_book(table);
      XLSX.writeFile(wb, "issue2424.xlsx");
    }).fail(function() { console.log("error");});
  });
})(jQuery);
</script>
<b>test</b>
</body>
```

Loading the page appears to work.

If you can provide a reproducible example we can take a closer look
