### ISSUE TITLE
Modular functions

### ISSUE THREAD

**Issue by Comfuner** [SheetJS/sheetjs#243]
Hi, 

this is great work.
I really looking forward to an option to use only parsing of an excel file without writing or other. in order to reduce file size

**Comment by codingsteff** [comment]
+1

**Comment by SheetJSDev** [comment]
h/t @MikhailTatsky

Would it make more sense for dynamic codec loading (say, a separate file for each format, and the main script would house the core format detection logic and make a request for the right codec)?

**Comment by SheetJSDev** [comment]
Years later, an ESM build has been introduced.  The approach will be refined, but this direction currently separates the independent parts of parsing and writing files.
