### ISSUE TITLE
How can I verify that the columns I need are in the excel (XLSX.utils.sheet_to_json (ws))

### ISSUE THREAD

**Issue by PriscilaTapia** [SheetJS/sheetjs#2436]
I'm working with react and typescript, does anyone have any ideas, I don't know how to remove that **'object is of type 'unknow''** error since that doesn't let loops or anything work: C

thanks in advance if you tried to solve it

`import * as XLSX from "xlsx";

export default function Home() {
  const readExcel = (file: any) => {
    const promise = new Promise((resolve, reject) => {
      const fileReader = new FileReader();
      fileReader.readAsArrayBuffer(file);
      fileReader.onload = (e) => {
        const bufferArray = e.target?.result;
        const wb = XLSX.read(bufferArray, { type: "buffer" }); //obtenemos el libro de trabajo - we get the workbook
        //en caso de usar varias hojas de trabajo
        const wsname = wb.SheetNames[0]; //obtenemos el nombre de la primera hoja - we get the name of the first sheet
        const ws = wb.Sheets[wsname]; //leemos la hoja wsname - we read the wsname sheet
        const data = XLSX.utils.sheet_to_json(ws,{header:'A'} ); //generamos una matriz de objetos con los datos - we generate an array of objects with the data
  
//nombre de columnas que necesito verificar - column name I need to check
        const checkNameColums: string[] = [
          "faena",
          "cantidad",
          "actividad",
          "comentario",
          "fechaProgramacion",
          "fechaEjecucion",
          "responsable",
          "estado",
        ];
        const columsData = data[0];
//solucion mas factible, pero Object is of type 'unknown'. - Most feasible solution, but Object is of type 'unknown'.
        let missingColums = checkNameColums.filter(function(word) {
          return !columsData.includes(word); //columsData-> object is of type 'unknow'
        });
        resolve(console.log(missingColums)
)
      };
      //en caso de que el lector de archivo tenga algún error - in case the file reader has any errors
      fileReader.onerror = (error) => {
        reject(error);
      };
    });
    //ahora se obtienen los datos de la hoja de trabajo - now get the data from the worksheet
    promise.then((d) => {
      console.log(d);
    });
  };
  return (
    <div className={styles.container}>
      <input
        type="file"
        onChange={(e) => {
          const file = e?.target?.files?.[0];
          readExcel(file);
        }}
      />
    </div>
  );
}
[FALTAN COLUMNAS.xlsx](https://github.com/SheetJS/sheetjs/files/7442588/FALTAN.COLUMNAS.xlsx)
[TODAS LAS COLUMNAS.xlsx](https://github.com/SheetJS/sheetjs/files/7442589/TODAS.LAS.COLUMNAS.xlsx)
`
@SheetJSDev

**Comment by SheetJSDev** [comment]
In the TS definitions, there's a generic form of `sheet_to_json`:

```typescript
    sheet_to_json<T>(worksheet: WorkSheet, opts?: Sheet2JSONOpts): T[];
```

So you can manually specify the row type if you know what it should be in advance:

```typescript
interface DataRow {
  name: string;
  id: number;
}

const rows: DataRow[] = XLSX.utils.sheet_to_json<DataRow>(ws);
```

If you pass the option `header: "A"` you will get back rows where the first column will be stored at "A", second column at "B", etc.

If you pass the option `header: 1`, you will get back arrays of arrays.

**Comment by PriscilaTapia** [comment]
and if the columns are not in the same order in each file?
