### ISSUE TITLE
ws[!merge] hide cell content

### ISSUE THREAD

**Issue by peppeg85** [SheetJS/sheetjs#2439]
hello, sorry if i reup an issue, could anyone help me with this?
from https://github.com/SheetJS/sheetjs/issues/2435
sorry, 
i read the documentation, let's say i want to write the data row by row,
starting from your code i wrote this:
```
const data=[
     ['xx','2013/2014','2014/2015','2015/2016'],
     ['job','entry','losses','sal','entry','losses','sal','entry','losses','sal'],
     ['bar','10','5','5','3','2','1','3','2','1'],
     ['wood','10','5','5','3','2','1','3','2','1'],
     ['other','10','5','5','3','2','1','3','2','1'],
     ['other','10','5','5','3','2','1','3','2','1']
];
const ws = XLSX.utils.aoa_to_sheet(data);
ws["!merges"] = [
  XLSX.utils.decode_range("B1:D1"),
  XLSX.utils.decode_range("E1:G1"),
  XLSX.utils.decode_range("H1:J1"),
];
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue2435.xlsx")
```

i can't see 2014/2015 and 2015/2015 column header, where am i wrong? 

![image](https://user-images.githubusercontent.com/25436763/139421805-e827767f-fa09-4399-86ca-3ae706d28778.png)

thank you

_Originally posted by @peppeg85 in https://github.com/SheetJS/sheetjs/issues/2435#issuecomment-954643132_

**Comment by reviewher** [comment]
create spaces for the cells in the merge:

```js
     ['xx', '2013/2014', /* C1 */, /* D1 */, '2014/2015', /* F1 */, /* G1*/, '2015/2016'],
```

**Comment by peppeg85** [comment]
ok, thanks for your help
