### ISSUE TITLE
VM25602:14 Uncaught Unrecognized tag: null|workbook,false|worksheet,false|table,false

### ISSUE THREAD

**Issue by Breave-YY** [SheetJS/sheetjs#2440]
Data error reporting VM25602:14 Uncaught Unrecognized tag: null|workbook,false|worksheet,false|table,false

**Comment by SheetJSDev** [comment]
Can you share a sample file?

**Comment by SeniorChiefABLEUnit** [comment]
I have already , multiple times.

**Comment by SheetJSDev** [comment]
Please share a sample file and we can reopen and investigate further!
