### ISSUE TITLE
Cannot convert csv string into xlsx

### ISSUE THREAD

**Issue by cod3rshotout** [SheetJS/sheetjs#2442]
I have this csv string:

    Data,Nazione,Campionato,Numero part.,Squadra,1,X,2,Over 2.5,Tiri tot. Fatti,Tiri tot. Subiti,Tiri in porta Fatti,Tiri in porta Subiti,Media Attacchi Fatti,Media Attacchi Subiti,Media Attac. Pericolosi Fatti,Media Attac. Pericolosi Subiti,Tentativi Goal Fatti,Tentativi Goal Subiti,Goal Attesi,Possesso palla,
    ,01-11-2021 20:45,Italy,Italy Serie A,5, Bologna,1.74,3.94,5.14,1.72,16,10,5,4,108,99,42,47,11,8,-3.5,53
    ,,,,4, Cagliari,,,,,7,21,2,7,72,129,25,66,4,15,-1.5,66

So I wrote this code to convert that in xlsx:

    let ws = XLSX.read(csv, {
        type: 'string'
    });
    let wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'sheet');
    let buf = XLSX.write(wb, {
        bookType: 'xlsx',
        type: 'buffer'
    });
    let str = XLSX.write(wb, {
        bookType: 'xlsx',
        type: 'binary'
    });
    XLSX.writeFile(wb, 'test.xlsx');

When I open the generated file it says that is not valid, what I did wrong?

**Comment by reviewher** [comment]
```js
let ws = XLSX.read(csv, {
    type: 'string'
});
```

That makes a workbook object with a single worksheet named Sheet1.  Fixing that makes a valid workbook:

```js
var csv = "Data,Nazione,Campionato,Numero part.,Squadra,1,X,2,Over 2.5,Tiri tot. Fatti,Tiri tot. Subiti,Tiri in porta Fatti,Tiri in porta Subiti,Media Attacchi Fatti,Media Attacchi Subiti,Media Attac. Pericolosi Fatti,Media Attac. Pericolosi Subiti,Tentativi Goal Fatti,Tentativi Goal Subiti,Goal Attesi,Possesso palla,\n,01-11-2021 20:45,Italy,Italy Serie A,5, Bologna,1.74,3.94,5.14,1.72,16,10,5,4,108,99,42,47,11,8,-3.5,53\n,,,,4, Cagliari,,,,,7,21,2,7,72,129,25,66,4,15,-1.5,66";

let ws = XLSX.read(csv, {
    type: 'string'
}).Sheets.Sheet1;
let wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'sheet');
XLSX.writeFile(wb, 'issue2442.xlsx');
```

Live demo: https://jsfiddle.net/781aymkb/

**Comment by cod3rshotout** [comment]
@reviewher I noticed that the dates are converted in number, why?

**Comment by cod3rshotout** [comment]
Fixed using:

    let ws = XLSX.read(csv, {
                type: 'string',
                cellDates: true
            }).Sheets.Sheet1;

**Comment by SeniorChiefABLEUnit** [comment]
Awesome. You are doing great in binary with
Vanguard. HUADA-01
