### ISSUE TITLE
How best to write data for easy pasting into Excel

### ISSUE THREAD

**Issue by sscholle** [SheetJS/sheetjs#2444]
I'm trying to implement an 'Export to Clipboard' feature in my app with the below code:

```
navigator.clipboard.writeText(XLSX.utils.sheet_to_html(ws));
```

This makes it easy for the values to end up in the correct cells when Pasting (Ctrl-V) in Excel (windows app).

However, the cell sizing becomes strangely inflated (in height), and the only remedy is to 'format as text' in Excel.

pasted - directly: 
![pure-paste](https://user-images.githubusercontent.com/2486065/140282966-bb133efe-e8b1-4563-a33c-b48cbfff6ba1.png)

select: 'keep text' in the paste context menu:
![keep-text](https://user-images.githubusercontent.com/2486065/140283052-249760a1-3120-4871-9708-966d0eee4d6c.png)

### Question
is there a way to copy/paste the data so that it ends up as a 'native paste' without having to especially select 'keep as text' from the context menu (essentially skipping one step in the process)?

**Comment by sscholle** [comment]
### Answer
It appears that Excel natively respects 'tab delimited'. So to get a native 'copy/paste' format, use the following code:
```
        navigator.clipboard.writeText(XLSX.utils.sheet_to_csv(ws, { FS: "\t" }));
```

**Comment by reviewher** [comment]
You can also use `sheet_to_txt` (which uses the tab character as the field separator)

**Comment by SheetJSDev** [comment]
Demo https://docs.sheetjs.com/docs/getting-started/demos/clipboard#browser-writing-copy
