### ISSUE TITLE
preserve customUI

### ISSUE THREAD

**Issue by RScherzer** [SheetJS/sheetjs#2445]
Is it possible to preserve customUI entries in a xlsm file?

A simple read operation with bookVBA: true attribute set plus a directly following writeFile operation (also with bookVBA: true) and no modification in between preserves the macros fine, but customUI entries in the original file (e.g. having a custom menu entry with buttons for calling the macros) get lost in the new output.

Is it just a limitation of the community edition, is it definetly available in the pro version?
Or do I simply miss a flag or something?

**Comment by SeniorChiefABLEUnit** [comment]
Pro Version, up to speed, enviroment not conducive for fulfillment of
contract negotiations or signing
Closed Enviromen will not only stop the cat from the jumping in the box,
there want be a box there at all
DA-01

**Comment by SheetJSDev** [comment]
At the moment, not with the open source build.  We're aiming for a 1.0.0 release that rounds out the data preservation support, and will address more advanced features post-1.0.0

As part of our [Pro offering](https://sheetjs.com/pro), we have a special build for surgical editing of existing worksheets.

**Comment by SeniorChiefABLEUnit** [comment]
Excellent
