### ISSUE TITLE
Parsed cell value contains validation error message for an .ods file

### ISSUE THREAD

**Issue by mkoziarski** [SheetJS/sheetjs#2446]
[validation-parse-error.ods](https://github.com/SheetJS/sheetjs/files/7476444/validation-parse-error.ods)
The .ods file above has data validation defined for cell B3.
When parsed, the corresponding validation error message is returned as the value of cell A1, with the actual value of that cell appended to the end.
I've tested similar cases with .xslx files and the issue would not appear.

**Comment by SheetJSDev** [comment]
Feel free to send a PR, changes apply to [`bits/80_parseods.js`](https://github.com/SheetJS/sheetjs/blob/master/bits/80_parseods.js#L128-L129)

```diff
--- a/bits/80_parseods.js
+++ b/bits/80_parseods.js
@@ -126,6 +126,7 @@ var parse_content_xml = (function() {
                                        C+= colpeat-1;
                                } else if(Rn[1]!=='/') {
                                        ++C;
+                                       textp = ""; textpidx = 0; textR = [];
                                        colpeat = 1;
                                        var rptR = rowpeat ? R + rowpeat - 1 : R
;
                                        if(C > range.e.c) range.e.c = C;
@@ -554,7 +555,7 @@ var parse_content_xml = (function() {
        };
 })();
```
