### ISSUE TITLE
Files not edited when reading Excel files

### ISSUE THREAD

**Issue by Breave-YY** [SheetJS/sheetjs#2447]
When reading the excel file, the file that has not been edited will be reported as vm5053:14 uncaught unrecognized tag: null|workbook, false|worksheet, false|table, false

**Comment by reviewher** [comment]
Please share a sample file

**Comment by Breave-YY** [comment]
[75e2052ea253413a971f4e6ae38a4c7d.xls](https://github.com/SheetJS/sheetjs/files/7494015/75e2052ea253413a971f4e6ae38a4c7d.xls)

**Comment by Breave-YY** [comment]
If this file has not been edited, it will report an error. After editing, it will not report an error

**Comment by SheetJSDev** [comment]
There's a literal `<ss:Null/>` which does not appear in the XML2003 reference schemas.  Since Excel accepts the file, we'll accept a patch.  Add the following line to [`bits/75_xlml.js` line 474](https://github.com/SheetJS/sheetjs/blob/master/bits/75_xlml.js#L474):

```js
		case 'null' /*case 'Null'*/: break;
```

**Comment by Breave-YY** [comment]
npm install xlsx How do I modify these files

**Comment by SeniorChiefABLEUnit** [comment]
Do not fuck with that file. Period.
