### ISSUE TITLE
Read multiple Excel files with react

### ISSUE THREAD

**Issue by SalmaneOuarab** [SheetJS/sheetjs#2450]
I have an issue reading multiple excel files even when i put the "multiple" HTML tag.

This is the handleFile function :

```
handleFile(file /*:File*/) {
    /* Boilerplate to set up FileReader */
    const reader = new FileReader()
    const rABS = !!reader.readAsBinaryString
    reader.onload = e => {
      /* Parse data */
      const bstr = e.target.result
      const wb = XLSX.read(bstr, { type: rABS ? "binary" : "array" })
      /* Get first worksheet */
      const wsname = wb.SheetNames[0]
      const ws = wb.Sheets[wsname]
      /* Convert array of arrays */
      const data = XLSX.utils.sheet_to_json(ws, { header: 1 })
      /* Update state */
      this.setState({
        data: data,
        cols: make_cols(ws["!ref"]),
        // jsonDATA: this.convertToJSON(data),
      })
    }
    if (rABS) reader.readAsBinaryString(file)
    else reader.readAsArrayBuffer(file)
  }
```
the handleFile function reads only one file.

This is the JSX code : 

`<input type="file" className="form-control" id="file" accept={SheetJSFT} onChange={this.handleChange} multiple />`

I would really appreciate it you could help with that.
Thank you!

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/blob/master/demos/react/sheetjs.js#L68

Demo uses only the first `File`.  You can change it to sequentially process each File in the array.
