### ISSUE TITLE
Dependencies should be deduplicated

### ISSUE THREAD

**Issue by stof** [SheetJS/sheetjs#2451]
The usage of the `~` operator in dependency constraints rather than the semver operator (`^`) means that they are locked to the same minor version.
`xlsx` currently depends on version 1.2 of `adler-32` while its `cfb` dependency depends on version 1.3. This prevents sharing the dependency between them.

It would be great if `xlsx` could update its `adler-32` dependency to avoid that duplication

**Comment by reviewher** [comment]
This should be resolved in the latest version.
