### ISSUE TITLE
How to set specific row on !autofilter

### ISSUE THREAD

**Issue by rafifmulia** [SheetJS/sheetjs#2452]
Hi,

I want to set filter on specific row, not just on the first row, but i don't find any information in documentation: https://github.com/SheetJS/sheetjs

i just find filter by range column:
ws['!autofilter'] = { ref:"A1:D4" };

Is there function to set filter on specific row ?

**Comment by reviewher** [comment]
Change the "1": https://jsfiddle.net/s6kpfL0c/

```js
ws["!autofilter"] = { ref: "A3:B5" };
```
