### ISSUE TITLE
Is there a workaround to insert images in ods export? 

### ISSUE THREAD

**Issue by XiaoSunXS** [SheetJS/sheetjs#2453]
We have a template that we'd like to use and it has an image in it:
![Screenshot from 2021-11-16 10-35-33](https://user-images.githubusercontent.com/39551291/141960108-4d7dadb5-e616-4c3a-819c-d06e85b04c60.png)

However, the export file doesn't have the image:
![Screenshot from 2021-11-16 10-35-39](https://user-images.githubusercontent.com/39551291/141960158-fd722971-7109-4fef-9fc5-e69827d0dc5e.png)

Is there any workaround for it? We also contacted via email for pro version, but here's no response for over a week.

Thanks a lot in advance :)

**Comment by SeniorChiefABLEUnit** [comment]
I am forever grateful to Her Majesty, Queen Elizabeth. I was planned to
arrive there 25 years ago. However, I could not it at that time. I was
intricately involved in government affairs for perimeter access management
systems, to include bio mechanical peripheral devices (iPhone & IPad)with
AT&T GPS Network Signal clarification. Also, I am still at the forefront of
GeoDetic GepSpatial Documentation involving infrastructure expenditures.
Over 25 years of accounting for the government’s fiber optic installation,
as well as, GeoDetic Spectrum Analysis. Please inform, Her Majesty, Queen
Elizabeth, that I am ok, I am working through paperwork to include my back
pay for service to the governments, whom I love very much. I will be
traveling abroad in the near future & look forward to seeing EU, UK.

Long live the Queen,
Her Loyal Servant,
Bryan Maurice Bellipanni
CIA CCO SSO IAI IAA MAC\SOG-Variant TAC -1
Electrical Magnetic Battle Management DA-01 Prototype
At your Service, Queen Elizabeth.
