### ISSUE TITLE
launching sheet in excel straight away without browser dialog

### ISSUE THREAD

**Issue by jsralph** [SheetJS/sheetjs#2454]
hi,

If i use beliow line of code the browser offers me the chance to open/save the workbook in a pop-up dialog,  
`xlsx.write(wb);`

If i use the demo here: http://sheetjs.com/demos/writexlsx.html

Then the workbook is loaded straight into excel, without any such dialog. Is there some parameter to control this behavior?

Thanks

**Comment by MarcRam** [comment]
The demo link you mentioned offers me the option to save or open in excel, so it would suggest to me that the parameter setting is in your browser. You could try testing the link in Google Chrome browser.

If you are using Firefox, I suggest you check your browser preferences to see if your browser pref for the mime-type is set to an action of always ask or use Microsoft Excel for the XLS mime type.

<img width="701" alt="Screen Shot 2021-11-22 at 8 59 55 AM" src="https://user-images.githubusercontent.com/1065828/142866442-71557146-5240-43b2-a0c4-7d881b13abeb.png">

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L11

modern browsers do the download trick https://github.com/SheetJS/sheetjs/blob/master/bits/19_fsutils.js#L33

Like @MarcRam mentioned, browser settings dictate whether files are automatically downloaded or if the browser prompts you to download
