### ISSUE TITLE
In versions later than 0.16.3, the performance of exporting .xls files deteriorates severely. It takes 15 seconds to export 50,000 data records.

### ISSUE THREAD

**Issue by LaiZoekWai** [SheetJS/sheetjs#2456]
Hi, 
    I found a problem. In versions later than 0.16.3, the performance of exporting .xls files deteriorates severely. It takes 15 seconds to export 50,000 data records. In the earlier version 0.15.5, it takes only a few seconds to export 50,000 data.
    So I would like to consult the official website to see if this problem is known and if there is a solution plan? Thank you!

**Comment by reviewher** [comment]
Where are you exporting?

Using Node v16.13.0 NodeJS test script:

```js
var XLSX = require("xlsx");
var ws = XLSX.utils.aoa_to_sheet(Array.from({length:50000}, (_,i) => ([String(i), i])));
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
var tag = XLSX.version;
console.time(tag);
var out = XLSX.write(wb, {bookType: "xlsx", type: "buffer"});
console.timeEnd(tag);
```

A single export averages about 310ms consistently across the library versions 0.15.{0,3,6} 0.16.{0,3,6,9} 0.17.{0,1,2,3,4} .

More details would help reproduce the issue.
