### ISSUE TITLE
Supported format image is look ugly in dark mode of github

### ISSUE THREAD

**Issue by fncolon** [SheetJS/sheetjs#2457]
## Description

Supported format image is look ugly in dark mode of github

<img width="689" alt="Capture" src="https://user-images.githubusercontent.com/50759463/142359807-799d0d9c-dd68-4437-b92e-660f21eeba66.PNG">

## Solution

Contributor need to change the image.

**Comment by SeniorChiefABLEUnit** [comment]
It is not going to be used on GitHub.

**Comment by SheetJSDev** [comment]
Background is now solid white
