### ISSUE TITLE
I can not disable this check "Sheet names cannot exceed 31 chars"

### ISSUE THREAD

**Issue by bkmsx** [SheetJS/sheetjs#2458]
I saw there is a safe check for sheet name, but I can not disable it. Looks like a bug!

`if(n.length > 31) { if(safe) return false; throw new Error("Sheet names cannot exceed 31 chars"); }`

**Comment by reviewher** [comment]
https://support.microsoft.com/en-us/office/rename-a-worksheet-3f1f7148-ee83-404d-8ef0-9ff99fbad1f9

> **Important:  Worksheet names cannot:**
> - Be blank .
> - **Contain more than 31 characters.**
> - Contain any of the following characters: / \ ? * : [ ]
> For example, 02/17/2016 would not be a valid worksheet name, but 02-17-2016 would work fine.
> - Begin or end with an apostrophe ('), but they can be used in between text or numbers in a name.
> - Be named "History". This is a reserved word Excel uses internally.
