### ISSUE TITLE
When exporting a large file, the cell where the Chinese characters of merge are used is empty

### ISSUE THREAD

**Issue by ahxdg** [SheetJS/sheetjs#2463]
![image](https://user-images.githubusercontent.com/13444766/143432307-c3d84c14-c6a2-49ce-b090-2ef0c5b1b7e1.png)

**Comment by ahxdg** [comment]
It only appears when the file is large

**Comment by reviewher** [comment]
Can you share an example?

**Comment by reviewher** [comment]
Please share a sample file or a way to reproduce the issue and we can reopen.
