### ISSUE TITLE
xlsx.readFile 读取xlsx文件时， {type: string, raw: true } 读到的日期依然是n类型，如何变成string类型呢

### ISSUE THREAD

**Issue by zxq08** [SheetJS/sheetjs#2464]
**读取的代码**：
let workSheet = XLSX.readFile(filePath, { type:'string', raw: true })

**断点中看到的数据**：
![image](https://user-images.githubusercontent.com/46339071/144041595-d6c45ed2-ec50-4909-b566-15d1039491c7.png)

**然后是原文件**：
![image](https://user-images.githubusercontent.com/46339071/144041739-746c8490-3f7b-4e97-8028-d56a3a20abfe.png)

**Comment by zxq08** [comment]
另外值得一提的是，w值虽然是字符串，但格式也太奇怪了吧

**Comment by zxq08** [comment]
补充，csv文件使用同样的代码读取是正常的。正确返回了 2021/10/27

**Comment by reviewher** [comment]
Pass the option `cellDates: true` to `XLSX.readFile`:

```js
let workSheet = XLSX.readFile(filePath, {type:'string', raw: true, cellDates: true })
```

**Comment by zxq08** [comment]
> 将选项传递`cellDates: true`给`XLSX.readFile`：
> 
> ```js
> 让 workSheet  =  XLSX 。readFile ( filePath ,  { type : 'string' ,  raw : true ,  cellDates : true  } )
> ```

我明白您的意思~我也尝试过。但是我现在明确我的需求是拿到和Excel文件中一模一样的字符串内容，不希望我在代码中进行格式化的操作（可能会出现不可预知的异常，有特殊的日期格式，例如2021年Q4）。
感谢您的回复~
