### ISSUE TITLE
Overwrite same sheet in same workbook in loop values

### ISSUE THREAD

**Issue by devlloedy** [SheetJS/sheetjs#2466]
Hi I'm having this problem. How can I overwrite data in a sheet without creating a new excel file or an excel sheet?

I got this error: worksheet with name xxx already exist!

I want to append new data in same sheet and use the same sheet name in same excel file. Thank you

**Comment by elyse0** [comment]
I think you're looking for `XLSX.utils.sheet_add_json` or `XLSX.utils.sheet_add_aoa`

https://docs.sheetjs.com/#array-of-arrays-input

You can also check these related issues for more details: 
- https://github.com/SheetJS/sheetjs/issues/1069
- https://github.com/SheetJS/sheetjs/issues/462

**Comment by reviewher** [comment]
@elyse0 's answer is probably what you want to do.

If you want to literally replace an existing worksheet, you can manually change the object:

```js
// var wb; // workbook
// var ws; // worksheet object
// var wsname; // worksheet name

var idx = wb.SheetNames.findIndex(x => x.toLowerCase() == wsname.toLowerCase());
if(idx == -1) XLSX.utils.book_append_sheet(wb, ws, wsname);
else wb.Sheets[wb.SheetNames[idx]] = ws;
```
