### ISSUE TITLE
256 Columns max for a sheet ?

### ISSUE THREAD

**Issue by Nayir** [SheetJS/sheetjs#2468]
Hi,

I'm currently on the version `^0.17.0`

I'm having trouble with the function `writeFile` containing some sheets with more than 256 columns. The others columns are not present in the document and no error is throwing.

I didn't find any documentation on it. 

This is due to a limitation of the library ? Maybe add a warning in this case ?

**Comment by SheetJSDev** [comment]
The XLS formats cap at 256 columns.  This is a file format limitation.  [There is a table in the README](https://github.com/SheetJS/sheetjs/#file-formats) and the readme notes the limitation:

> Formats with range limits will be silently truncated

On a per-format level, a warning can be added.  Since all of the XLS formats are limited to 256 columns, the warning can be put in [`write_biff_buf`](https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L384). 

We'd accept a PR that loops through the worksheet objects, decodes the ranges of each worksheet, and warns if the ending column is beyond IV:

```js
for(var i = 0; i <= wb.SheetNames.length; ++i) {
  var ws = wb.Sheets[wb.SheetNames[i]];
  if(!ws || !ws["!ref"]) continue;
  var range = decode_range(ws["!ref"]);
  if(range.e.c > 255) { // note: 255 is IV
    console.error("Worksheet '" + wb.SheetNames[i] + "' extends beyond column IV.  Data may be lost.");
  }
}
```

**Comment by aritrakoley** [comment]
I implem

> The XLS formats cap at 256 columns. This is a file format limitation. [There is a table in the README](https://github.com/SheetJS/sheetjs/#file-formats) and the readme notes the limitation:
> 
> > Formats with range limits will be silently truncated
> 
> On a per-format level, a warning can be added. Since all of the XLS formats are limited to 256 columns, the warning can be put in [`write_biff_buf`](https://github.com/SheetJS/sheetjs/blob/master/bits/78_writebiff.js#L384).
> 
> We'd accept a PR that loops through the worksheet objects, decodes the ranges of each worksheet, and warns if the ending column is beyond IV:
> 
> ```js
> for(var i = 0; i <= wb.SheetNames.length; ++i) {
>   var ws = wb.Sheets[wb.SheetNames[i]];
>   if(!ws || !ws["!ref"]) continue;
>   var range = decode_range(ws["!ref"]);
>   if(range.e.c > 255) { // note: 255 is IV
>     console.error("Worksheet '" + wb.SheetNames[i] + "' extends beyond column IV.  Data may be lost.");
>   }
> }
> ```

I implemented the above code in the way mentioned. When I run make (on windows 10), I can see that the following files are modified:
78_writebiff.js
xlsx.js
xlsx.flow.js

To make a pull request, should I push all 3 files or just 78_writebiff.js?
If neither of the minified js files are modified, am I running make properly?

( I'm new to open source contributions so any help would be appreciated. Thank you. )

**Comment by SheetJSDev** [comment]
Pushed in 0.17.5
