### ISSUE TITLE
Reading xls file is returning html tags using library xlsx

### ISSUE THREAD

**Issue by abdullahstella** [SheetJS/sheetjs#2469]
I am using xlsx library of nodejs for reading xls file. According to the document the library supports xls file format. On reading I am getting html tags along with it. I can remove the html tags using regex or replace function but does the library give support to do that as I couldn't find it in the documentation?

Excel File format: Microsoft Excel 97-2003 Worksheet (.xls)

The demo link provided in their documentation https://oss.sheetjs.com/sheetjs/ works but when I try to do the same with my code it doesn't give the desired result.

```
let xlsx = require('xlsx');
let fs = require('fs');

let workBookData = xlsx.readFile('data.xls'); // parses a file
console.log(workBookData);

```
Here is an image of the result I am getting.

![stack](https://user-images.githubusercontent.com/75425367/144640998-1e67548d-f232-483e-97e0-9ce56093155c.PNG)

**Comment by reviewher** [comment]
Can you share the file?

**Comment by abdullahstella** [comment]
Attached please find.
________________________________

**Comment by abdullahstella** [comment]
> Can you share the file?

[Report_Billings.xls](https://github.com/SheetJS/sheetjs/files/7654620/Report_Billings.xls)

**Comment by SheetJSDev** [comment]
Cannot reproduce with the latest version of the library and NodeJS LTS:

```bash
$ md5sum Report_Billings.xls 
5103c7ab4790083ce102ae86634a19a5  Report_Billings.xls
$ node --version
v16.13.1
$ node -pe 'require("xlsx").version'
0.17.4
$ node -pe 'require("xlsx").readFile("Report_Billings.xls").Sheets.Sheet1.A1'
{ v: 'Statement No.', t: 's', w: 'Statement No.' }
```

Are you absolutely sure you attached the same file?  If you can't share it publicly, feel free to email it directly to oss@sheetjs.com and we can look at it further

**Comment by abdullahstella** [comment]
> Cannot reproduce with the latest version of the library and NodeJS LTS:
> 
> ```shell
> $ md5sum Report_Billings.xls 
> 5103c7ab4790083ce102ae86634a19a5  Report_Billings.xls
> $ node --version
> v16.13.1
> $ node -pe 'require("xlsx").version'
> 0.17.4
> $ node -pe 'require("xlsx").readFile("Report_Billings.xls").Sheets.Sheet1.A1'
> { v: 'Statement No.', t: 's', w: 'Statement No.' }
> ```
> 
> Are you absolutely sure you attached the same file? If you can't share it publicly, feel free to email it directly to [oss@sheetjs.com](mailto:oss@sheetjs.com) and we can look at it further

Forwarded, please have a look, and suggesr.

**Comment by SheetJSDev** [comment]
Thanks for sharing!  The actual file was an HTML file renamed to XLS

The opening tag had inline styles with a semicolon:

```html
<table cellspacing="0" rules="all" border="1" style="border-collapse:collapse;">
```

This tripped up the check in https://github.com/SheetJS/sheetjs/blob/master/bits/75_xlml.js#L185

We'd accept a PR that ignores characters within double quotes:

```diff
--- a/bits/75_xlml.js
+++ b/bits/75_xlml.js
@@ -183,6 +183,7 @@ function parse_xlml_xml(d, _opts)/*:Workbook*/ {
                else str = utf8read(str);
        }
        var opening = str.slice(0, 1024).toLowerCase(), ishtml = false;
+       opening = opening.replace(/".*?"/g, "");
        if((opening.indexOf(">") & 1023) > Math.min((opening.indexOf(",") & 1023), (opening.indexOf(";")&1023))) { var _o = dup(opts); _o.type = "string"; return PRN.to_workbook(str, _o); }
        if(opening.indexOf("<?xml") == -1) ["html", "table", "head", "meta", "script", "style", "div"].forEach(function(tag) { if(opening.indexOf("<" + tag) >= 0) ishtml = true; });
        if(ishtml) return HTML_.to_workbook(str, opts);
```

**Comment by ZaheerUdDeen** [comment]
@SheetJSDev Hi, Was facing the same issue, have made a PR following your suggestions, I am curios to know when npm package will be updated accordingly.

**Comment by SheetJSDev** [comment]
30c03a2e5341ec808c299c72dbd9da4fb414b874

**Comment by ZaheerUdDeen** [comment]
@SheetJSDev When we will expect npm package to be updated for this change.
