### ISSUE TITLE
Weird -52 seconds offset in Chrome when parsing dates

### ISSUE THREAD

**Issue by Kaiido** [SheetJS/sheetjs#2471]
Sheet-js seems to have an issue in Chrome while parsing some cells as Date objects.

I attach a minimal spreadsheet that does reproduce the issue, and you can see it live in this jsfiddle: https://jsfiddle.net/7968yxrL/
In Chrome this fiddle will output `"11/21/2021, 11:59:08 PM"`, while in Firefox it will output `"11/22/2021, 12:00:00 AM"` (the expected result).  

The cell "raw" value is `44522` and in both Firefox and Chrome doing 

```js
const date = new Date(1900, 00, 01);
date.setDate(44522 - 1);
```
will correctly generate a 11/22/2021, 12:00:00 AM Date object, so there must be something going on in the way the Date object is created in sheet-js.  

[single-cell.xlsx](https://github.com/SheetJS/sheetjs/files/7674576/single-cell.xlsx)

**Comment by SheetJSDev** [comment]
The immediate issue is a V8 bug surrounding the sub-minute timezone offsets. https://bugs.chromium.org/p/v8/issues/detail?id=7863 is still unresolved.  But there are ways to mitigate the effects.

Dates are anchored to the 1900 epoch.  Based on the 2021b tz database, the last TZ to change the universal time offset to be an integral number of minutes was `Africa/Monrovia` in 1972.  That means reanchoring to September 5 2021 (date code 44444) will be correct for most common date codes at the expense of older dates.  This is an "easy" change.

The other problem, which will require some more serious work, is the DST issue.  Basically, Excel's date model assumes each calendar day is exactly 86400 seconds.  This breaks on DST days: JS treats "spring forward" days as 23 * 3600 seconds and "fall back" days as 25 * 3600 seconds.  There will need to be a consistent solution for how to handle datecodes that don't have a JS date representation and JS dates that don't have an Excel datecode.

Closing in favor of https://github.com/SheetJS/sheetjs/issues/1212

**Comment by Kaiido** [comment]
Tanks fo the quick handling, and sorry to bother here again, I'm not sure if I should have moved that to #1212.  

I have to workaround this issue for our clients, and I'm trying to understand why the `getTimezoneOffset()` is even needed.  
If I get it correctly, using e.g the "Africa/Monrovia" TZ a date before 1972 would be parsed using GMT-0044  while a date after 1972 would be parsed using GMT+0000, is that correct?

Is this the only use for this `getTimezoneOffset()` in `datenum()`?  

If so, I guess that for us using the code in my first comment would be largely sufficient as most of our users have dates from less than a decade, and that having dates offset because the user's TZ did actually offset at this date doesn't sound terribly wrong to me anyway. Does that sound right to you? (I'm talking about implementing the workaround myself, not about changes you would have to do on sheet-js.)
