### ISSUE TITLE
Table header values converting into datetime (chrome browser only)

### ISSUE THREAD

**Issue by ashok13ask** [SheetJS/sheetjs#2472]
I have a table header cell with the string "**CGST / SGST : 0.5 %**" , When i download the xls from this table that cell value automatically converted into "**05/01/2000 00:00:10**", But it's happening only on chrome browser, it's working fine in firefox

Table cells

![image](https://user-images.githubusercontent.com/55733163/145341266-09e6dd45-9db8-479f-b4c8-8beade87c836.png)

Xls after downlod
![image](https://user-images.githubusercontent.com/55733163/145341444-38806c28-3a17-4d12-beef-7a89e223c05d.png)

**Comment by SheetJSDev** [comment]
Same as https://github.com/SheetJS/sheetjs/issues/2196 -- this is an issue with Chrome date parsing.  You can verify this by running `new Date("CGST / SGST : 0.5 %")` in your console.  Chrome generates the date May 01 2000, while FF returns an Invalid Date
