### ISSUE TITLE
Auto-downloading using `writeFile` no response on Chrome iOS

### ISSUE THREAD

**Issue by zstbsqx** [SheetJS/sheetjs#2473]
Device: iPhone12
iOS Version: 15.1.1
Chrome Version: 96.0.4664.53

```
const trigger() => {
    const wb = ...;
    XLSX.writeFile(wb);
}
```

No response from chrome on iOS.

**Comment by SheetJSDev** [comment]
This is a known bug in chrome for iOS:

Chrome Bug Tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1252380

Webkit Bug Tracker with more context: https://bugs.webkit.org/show_bug.cgi?id=167341#c68
