### ISSUE TITLE
 uncaught typeerror cannot read property of undefined (reading CENTRAL DIRECTORY END')

### ISSUE THREAD

**Issue by psuresh41** [SheetJS/sheetjs#2475]
function ExportToTable() {
            $('#loading').show();
            var regex = /^([a-zA-Z0-9\s_\\.\-:])+(.xlsx|.xls)$/;
            if (regex.test($("#excelfile").val().toLowerCase())) {
                var xlsxflag = false;
                if ($("#excelfile").val().toLowerCase().indexOf(".xlsx") > 0) {
                    xlsxflag = true;
                }
                if (typeof (FileReader) != "undefined") {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var data = e.target.result;
                        if (xlsxflag) {
                            **var workbook = XLSX.read(data, { type: 'binary' });** // In this line it showing the error 
                        }
                        else {
                            var workbook = XLS.read(data, { type: 'binary' });
                        }
                        var sheet_name_list = workbook.SheetNames;
                        var cnt = 0;

**Comment by reviewher** [comment]
The code snippet is truncated.  How are you using the `reader`?  If you are calling `readAsText`, the binary characters may be mangled
