### ISSUE TITLE
html to xlsx export format problem in column

### ISSUE THREAD

**Issue by djaenz** [SheetJS/sheetjs#2479]
when i export html <table> data to xlsx i cant say that column should be formatted as text. my problem is, i have telephon number with 0 at first and its exported in excel to:

4,94335E+12 instead of for example 4949640501410

i tried in <td> tag: `<td data-t="s" data-v="00001234">00001234</td>`

and i tried

` <td style="mso-number-format:\@;">`

both not works :(

i use this script:

https://redstapler.co/sheetjs-tutorial-html-table-to-excel/

**Comment by reviewher** [comment]
Make sure you are using the latest version of the library: https://unpkg.com/xlsx/dist/xlsx.full.min.js will serve the latest version on NPM. 

Small demo https://jsfiddle.net/5fqkgs9d/
