### ISSUE TITLE
BOM character leaking into A1 when using CSV

### ISSUE THREAD

**Issue by hugoaboud** [SheetJS/sheetjs#2480]
I've found a bug while parsing .csv files with UTF-8 BOM encoding.

NodeJS: v16.9.1
SheetJS: 0.17.4

**How to Reproduce**

*I'm currently using the lib with the patch discussed at [this issue](https://github.com/SheetJS/sheetjs/issues/2476). It's required so accented characters don't break during the parse.*

- Created a CSV file with the following data:

```
CÓDIGO;DESCRIÇÃO;VALOR
000; Test; 1000
000; Test; 1000.42
000; Test; 1,000.42
```

- The file was saved at 4 formats: `.csv utf8`, `.csv utf8bom`, from `VSCode`, and `.xls` and `.xlsx`, from `OpenOffice Calc`.

- The following snippet was used to inspect the contents of the `A1` cell from the main sheet:

```javascript
let workbook = XLSX.readFile(filename, { codepage: 65001 });
console.dir(workbook,{depth:null});

let sheet = workbook.Sheets.list || workbook.Sheets['Sheet1'];
let cell = sheet['A1'];
console.log(cell);
console.log(cell.v.trim().split(''));
console.log(cell.v.trim().split('').map((_,i) => cell.v.charCodeAt(i)));
```

- The results were:
![bom-extra-byte](https://user-images.githubusercontent.com/2349393/146992496-eb90cf7b-36e2-466a-82c9-8a03dc8aea7d.png)

Apparently the extra BOM byte leaks into the A1 cell, so that `cell.v !== 'CÓDIGO'`.
Since the character is not printed, it breaks things unexpectedly and it took me a while to identify. 

**Temporary Workaround** 

After the file is read, I'm using the following workaround:
```javascript
if (a1_cell.charCodeAt(0) > 255) a1_cell = a1_cell.slice(1);
```

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/commit/92d8a38ef62bdaee55a5d5d109ca22515fe215be
