### ISSUE TITLE
use 'table_to_book' to export a group table, but the downloaded excel is not grouped 

### ISSUE THREAD

**Issue by hayabusa2009** [SheetJS/sheetjs#2482]
Hi, I use below code to export a **group table**:
`const wb = XLSX.utils.table_to_book(elt);`
`XLSX.writeFile(wb, groupTable.csv);`

but the downloaded excel is not grouped, could you give me some advice, thx.

**Comment by SheetJSDev** [comment]
The CSV output format does not support grouping and there is no pragma to get Excel to group rows in the CSV file.
