### ISSUE TITLE
Date fomat not correct view

### ISSUE THREAD

**Issue by motoroller1983** [SheetJS/sheetjs#2483]
Date fomat not correct view except Mozilla
for example
30.11.2021 - in excel correct view (d-m-Y)
next one record in original 01.12.2021 (d-m-Y)
in excel view like 12.01.2021  0:00:16, script change month and day places and add time

WHY?????

**Comment by reviewher** [comment]
V8 bug https://bugs.chromium.org/p/v8/issues/detail?id=7863

Follow #1212 for updates
