### ISSUE TITLE
How to create nested table with header? 

### ISSUE THREAD

**Issue by Parasbuda** [SheetJS/sheetjs#2484]
Hey i want to export my data into excel file which may be either csv or xlsx. The table should be nested table i.e. first of all the headers of 1st table then only one row of data related to that 1st table then nested table's header and all the data in nested table then total of nested table like this and at the end total of main table. And i also want heading related to company date and time of report ganeration, type of report at the beginning?

**Comment by reviewher** [comment]
You can use `sheet_add_aoa` or `sheet_add_json` with the option `origin: -1` to programmatically add separate tables to a worksheet one at a time
