### ISSUE TITLE
[bug] Row info about visibility is missing

### ISSUE THREAD

**Issue by ybelenko** [SheetJS/sheetjs#2486]
I'm trying to migrate from [PHPOffice/PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) to this package. PhpSpreadsheet works fine with my xlsx file, while sheetjs gives no info about hidden rows. It's really important since my script needs to ignore hidden cells.

Mentioned file has been sent to email from the Contributing doc.

Package version: `"xlsx": "^0.17.4".`

**Comment by SheetJSDev** [comment]
Pass the option `cellStyles: true` to read, then the `!rows` property of the worksheet object will be populated.  Each object corresponds to a row.  The `hidden` property of each row will be set to `true` if hidden.

**Comment by ybelenko** [comment]
Thanks, @SheetJSDev, it solves my problem.

It's not so obvious that row/column visibility stored in styles props and that it switched off by default. You should mention it in the main documentation. I was searching for an answer over there, but didn't find anything, so I've submitted an issue.

**Comment by reviewher** [comment]
Feel free to submit a PR and change [`docbits/54_shobject.md`](https://github.com/SheetJS/sheetjs/blob/master/docbits/54_shobject.md)

**Comment by ybelenko** [comment]
Oh, I'm flattered. Seems like you didn't notice that I'm not native english speaker. I'm not the right person to write official docs if you have someone from USA/UK.

**Comment by azeez1776** [comment]
@reviewher @ybelenko  Can I work on the documentation issue and submit a PR
