### ISSUE TITLE
SheetJS does not work with array columns when exporting json_to_sheet

### ISSUE THREAD

**Issue by arnonrdp** [SheetJS/sheetjs#2487]
I'm using `json_to_sheet` and I'm exporting a sheet with no problems.
However, I noticed that some columns were completely blank.
When investigating, I noticed that the columns without content are precisely those that have arrays.

Here is the code to reproduce the error:
```ts
public jsonExample() {
  return [
    {
      name: 'John',
      age: 30,
      cars: ['Ford', 'BMW', 'Fiat']
    },
    {
      name: 'Jane',
      age: 32,
      cars: ['Fiat', 'VW']
    }
  ];
}

public exportExcel() {
  let workbook = XLSX.utils.book_new();
  let ws = XLSX.utils.json_to_sheet(this.jsonExample());
  XLSX.utils.book_append_sheet(workbook, ws, 'Json Example');
  XLSX.writeFile(workbook, "Sheet 1");
}
```

When you do this, the exported spreadsheet displays only the name and age columns.
The cars column displays only the header, not the content.

Can this really be considered a bug or is there something I should be doing differently?

**Comment by SheetJSDev** [comment]
The `json_to_sheet` utility function is extremely simplistic and does not try to handle column mappings of nested objects and arrays.

It is probably best to manually project to an array of arrays and use `aoa_to_sheet` to generate the worksheet:

```js
let ws = XLSX.utils.aoa_to_sheet(
  [
    ["Name", "Age", "Cars"] // Header row
  ].concat(this.jsonExample().map(
    ({name, age, cars}) => ([name, age, ...cars])) // [name, age, car[0], car[1], ... ]
  )
)
```

If you do not know the columns ahead of time and need a dynamic solution, the [`database` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/database#objects-kv-and-schema-less-databases) has an example of mapping a complex JS object into worksheets.

**Comment by arnonrdp** [comment]
The way you wrote, the result is:

<img width="313" alt="Captura de Tela 2022-01-12 às 13 56 00" src="https://user-images.githubusercontent.com/26576201/149185795-3e6dd1d4-c162-4cca-98c4-c47f6b5bb043.png">

[Sheet 1.xlsx](https://github.com/SheetJS/sheetjs/files/7856347/Sheet.1.xlsx)

I'm talking about having all the items in the array inside the same cell, one in each row.

**Comment by gauravbharat** [comment]
I had a similar issue with XLSX (v0.18.5) and converting array column values to JSON string before passing the rows to XLSX.utils.json_to_sheet worked for me - 
```

public jsonExample() {
  return [
    {
      name: 'John',
      age: 30,
      cars: JSON.stringify(['Ford', 'BMW', 'Fiat'])
    },
    {
      name: 'Jane',
      age: 32,
      cars: JSON.stringify(['Fiat', 'VW'])
    }
  ];
}
...
XLSX.utils.json_to_sheet(this.jsonExample());
...
```
