### ISSUE TITLE
XLSX modify existing sheet and save it

### ISSUE THREAD

**Issue by kflore16** [SheetJS/sheetjs#2488]
Suppose my excel sheet looks like:
(1 first row)
| A1 data| A2 data|
| -------------|---------------|

(2 the rest)
| B1 data     |   B2 data |      B3 data     |
| -----| ----- | -----|
|C1 data | C2 data | C3 data|

where (1) contains metadata
with (1) on top of (2); I want to parse the entire sheet but only work with (2) as a JSON with row B as headers, modify some data, then save the entire sheet with the same format. Whats the best approach?
I know 
``` javascript
const data = reader.utils.sheet_to_json(FILE.Sheets[sheetname], {range:1})
``` 
returns only the dataset in (2) as a json but I'm not quite sure what to do to apply the modified (2) unto the original sheet.
I've also correctly modified and saved it properly by parsing the entire sheet without the range option but its very ugly because the empty cell A3 is replaced with `__EMPTY` object keys in JSON.

**Comment by reviewher** [comment]
For the specific question, `sheet_add_json` is the operation to put data back.  To ensure correct header order:

```js
const header = [];
const data = reader.utils.sheet_to_json(FILE.Sheets[sheetname], {range:1, header})
// ... modify dataset
reader.utils.sheet_add_json(FILE.Sheets[sheetname], new_data, { skipHeader: true, origin: 2, header });
```
