### ISSUE TITLE
If a workbook cell has an IFERROR formula, what does value_if_error need to be so blankrows: false works?

### ISSUE THREAD

**Issue by b-hexsoul** [SheetJS/sheetjs#2490]
I have a workbook with formula in Col A 

```
=IFERROR(INDEX('Data Validation'!$D$2:$D$475,MATCH('Compensation Input Form'!C16,JobTitle,FALSE)),#N/A)
```

When this is parsed, the first row that contains #N/A becomes 

```
{t: 'e', v: 42, f: "IFERROR(INDEX('Data Validation'!$D$2:$D$475,MATCH(…mpensation Input Form'!C44,JobTitle,FALSE)),#N/A)", w: '#N/A'}
```

It shows t: 'e' great! but **why is v: 42?** How do I force it to be 0 which appears to be the only way v === null in make_json_row.

**Comment by SheetJSDev** [comment]
the `t: 'e'` part is saying that's an error cell.  The interpretation of `v` is listed in https://github.com/SheetJS/sheetjs#data-types.  Click on "Error values and interpretation (click to show)" to see the table:

|  Value | Error Meaning   |
| -----: | :-------------- |
| `0x00` | `#NULL!`        |
| `0x07` | `#DIV/0!`       |
| `0x0F` | `#VALUE!`       |
| `0x17` | `#REF!`         |
| `0x1D` | `#NAME?`        |
| `0x24` | `#NUM!`         |
| `0x2A` | `#N/A`          |
| `0x2B` | `#GETTING_DATA` |

In this case, 42 is `0x2a` which corresponds to the `#N/A` value.

To work around for now, you can make your Excel expression return the `#NULL!` error (which corresponds to 0)
