### ISSUE TITLE
Iraqdata

### ISSUE THREAD

**Issue by SUHAD2022ALI** [SheetJS/sheetjs#2492]
https://github.com/SheetJS/sheetjs/blob/e3c5eac99c3b2be6929adfca455c1be87fab792b/xlsx.js#L4087

**Comment by SheetJSDev** [comment]
The `CountryEnum` corresponds to the [`MS-XLS Country` record](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/440b4cc6-215f-439a-af5b-f1b666c1af78).  According to the official documentation:

> 964 Iraq

The code snippet is

```js
0x03C4: "IQ", // Iraq
```

The value `0x03C4` is 964.  The string `IQ` is the [ISO-3166 Alpha-2 code](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) for Iraq.

**Comment by dr-suhadalishaheed** [comment]
#
hi
https://github.com/SheetJS/sheetjs/issues/2492#
