### ISSUE TITLE
Not able to Increase Column width

### ISSUE THREAD

**Issue by das-devi** [SheetJS/sheetjs#2495]
Hi Team,

I am trying to increase the column width in the generated excel file, but my changes are not getting reflected in the final generated excel file. Can you please help me am I missing something here?.

Here is the code snippet 

 const worksheet: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(tableData);
        const wscols: any = [];
        for (const key in colWidths) {
            if ((colWidths as any)[key])
                wscols.push({
                  //  wpx: 50,
                      width: 50,
                 //   wch: 50,
                });
        }
        worksheet['!cols'] = wscols;

        console.log("worksheet['!cols'] ", worksheet['!cols']);
        const workbook: XLSX.WorkBook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, fileName);
        XLSX.writeFile(workbook, fileName + `.csv`);

Tried with all 3 possible properties like wpx, wch and width with different values but still no effect.

![xl_widths](https://user-images.githubusercontent.com/36114359/149880673-5169fcf4-c5d6-4a7b-83a9-f470c0a49858.png)

**Comment by SheetJSDev** [comment]
CSV does not support widths, use a format like XLSX:

```js
const worksheet = XLSX.utils.aoa_to_sheet([
  ["wpx","width","wch"]
]);
worksheet['!cols'] = [
  {wpx: 50},
  {width: 50},
  {wch: 50}
];

const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");
XLSX.writeFile(workbook, "issue2495.xlsx");
```

https://jsfiddle.net/5j9y2nbd/
