### ISSUE TITLE
Add Nuxt support

### ISSUE THREAD

**Issue by Rednas83** [SheetJS/sheetjs#2496]
Are there plans for supporting nuxt/ssr?

**Proposal:**
* Parse on compile level with ssr to make it available staticly. I think most users probably only read from excel anyways.

**Workaround:**
* Parse on server level [dynamic]
* Manually convert to csv/json and parse with `Nuxt content` [static]

**Comment by Jonham** [comment]
I'm familiar with both Sheet.js and Nuxt.js.
I'd like to trying create an extension fullfill your target.

**Comment by reviewher** [comment]
In theory, a [custom parser for `@nuxt/content`](https://content.nuxtjs.org/configuration#extendparser):

```js
// nuxt.config.js

const XLSX = require("xlsx");

const parseXLSX = buf => {
  const wb = XLSX.read(file);
  return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
};

// in Config:

{
  extendParser: {
    '.xlsx': parseXLSX,
    '.xls': parseXLSX,
    // ... other extensions
  }
}
```

The problem is `@nuxt/content` does the UTF8 conversion before passing to the parsers.  [Left a comment in the related issue on their tracker](https://github.com/nuxt/content/issues/1002#issuecomment-1017906254).

**Comment by reviewher** [comment]
Please direct feedback to https://github.com/nuxt/content/issues/1007 .  This issue can be reopened if need be.

**Comment by reviewher** [comment]
This works without patching `@nuxt/content`.  The example pulls every worksheet using `sheet_to_json`:

```js
// nuxt.config.js
import { readFile, utils } from 'xlsx';

const parseXLSX = (file, { path }) => {
  const wb = readFile(path);
  const o = wb.SheetNames.map(name => ({ name, data: utils.sheet_to_json(wb.Sheets[name])}));
  return { data: o };
}

export default {
// ...
  content: {
    extendParser: {
      ".xlsx": parseXLSX
      // put other extensions here
    }
  },
// ...
```

Sample template:

```vue
<template>
<div>
  <div v-for="item in data.data" v-bind:key="item.name">
    <h2>{{ item.name }}</h2>
    <pre>{{ item }}</pre>
  </div>
</div>
</template>

<script>
export default {
  async asyncData ({$content}) {
    return {
      data: await $content('blob').fetch()
    };
  }
}
</script>
```

**Comment by SheetJSDev** [comment]
This works surprisingly well.  Small video from the [Nuxt demo](https://github.com/SheetJS/sheetjs/tree/master/demos/vue) showing hot reload with nuxt and `@nuxt/content`:

https://user-images.githubusercontent.com/6070939/157599532-e3978b11-c4be-4873-a2a3-e02e68ad0c3b.mp4
