### ISSUE TITLE
Format date cell with format of 'yyyy-mm-dd hh:mm:ss'

### ISSUE THREAD

**Issue by DVC15** [SheetJS/sheetjs#2497]
Hi everyone, I try to format a date column into a custom format, this is my code:
`  const ws = xlsx.utils.json_to_sheet(records, {
    cellDates: true,
    dateNF: 'yyyy-mm-dd hh:mm:ss',
  });`
But the date column became string and therefore can't be sorted, has anyone encountered this issue? Any help will be appreciated.
Thanks.

**Comment by reviewher** [comment]
Make sure you are actually passing a date object:

```js
xlsx.utils.json_to_sheet([
  {a:new Date(2021,0,19)} // value is a date object -> cell is date
], {cellDates: true, dateNF: 'yyyy-mm-dd hh:mm:ss'});
xlsx.utils.json_to_sheet([
  {a:new Date(2021,0,19).toISOString()} // value is a string -> cell is string irrespective of cellDates
], {cellDates: true, dateNF: 'yyyy-mm-dd hh:mm:ss'})
```
