### ISSUE TITLE
0.17.3 breaks CSV parsing when leading space

### ISSUE THREAD

**Issue by Kaarel** [SheetJS/sheetjs#2498]
In 0.17.2 the following code

```
var wb = xlsx.read(Buffer.from(' Col1,Col2'));
console.log(JSON.stringify(wb));
```

prints

`{"SheetNames":["Sheet1"],"Sheets":{"Sheet1":{"A1":{"t":"s","v":" Col1"},"B1":{"t":"s","v":"Col2"},"!ref":"A1:B1"}}}`

in 0.17.3 and 0.17.5 the same code prints

`{"SheetNames":["Sheet1"],"Sheets":{"Sheet1":{"A1":{"t":"s","v":"\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0002"},"!ref":"A1"}}}`

Note when I remove the leading space before 'Col1' the output is as expected.

**Comment by steviegalluscio** [comment]
I will take a look at this. I was able to replicate it with node js and with client side js in the browser, reading as a buffer. Currently debugging it.

**Comment by reviewher** [comment]
Same as https://github.com/SheetJS/sheetjs/issues/2476

**Comment by Kaarel** [comment]
After `npm install xlsx@0.18.2` I can see that `node_modules` contains the code from commit https://github.com/SheetJS/sheetjs/commit/92d8a38ef62bdaee55a5d5d109ca22515fe215be mentioned in the issue https://github.com/SheetJS/sheetjs/issues/2476#issuecomment-1032173023.

However the following vanilla node app fails

```
var wb = require('xlsx').read(Buffer.from(' Col1,Col2'));
require('assert/strict').deepEqual(
    JSON.stringify(wb),
    '{"SheetNames":["Sheet1"],"Sheets":{"Sheet1":{"A1":{"t":"s","v":" Col1"},"B1":{"t":"s","v":"Col2"},"!ref":"A1:B1"}}}',
);
```

after `npm install xlsx@0.17.2` the same node app runs without errors.

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/blob/master/bits/87_read.js#L44-L45

```diff
--- a/bits/87_read.js
+++ b/bits/87_read.js
@@ -43,6 +43,7 @@ function read_plaintext_raw(data/*:RawData*/, o/*:ParseOpts*/)/*:Workbook*/ {
                default: throw new Error("Unrecognized type " + o.type);
        }
        if(bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF) str = utf8read(str);
+       o.type = "binary";
        return read_plaintext(str, o);
 }
```

**Comment by SheetJSDev** [comment]
@Kaarel the example appears to work in 0.18.3.  Please test further and let us know if it looks good.

**Comment by Kaarel** [comment]
I can confirm 0.18.3 fixes the issue. Thanks!
