### ISSUE TITLE
Corrupt XLSX export

### ISSUE THREAD

**Issue by reviewher** [SheetJS/sheetjs#2499]
Hello, Iam trying to export as xlsx format. but i'm getting corrupted file. but if i change file extension into csv, then it's works.
Can anyone help on this
```ts
  const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet(partsViewModel.productParts());
    XLSX.utils.book_append_sheet(wb, ws, 'Parts');
    const productName = applicationState.productDetailsWithComponents()?.productDetails[0]?.modelSetProductName;
    XLSX.writeFile(wb, `${productName}.xlsx`);
```

_Originally posted by @rashiq-ahmd in https://github.com/SheetJS/sheetjs/issues/817#issuecomment-1016292276_

**Comment by reviewher** [comment]
@rashiq-ahmd can you share the generated file?

**Comment by reviewher** [comment]
@rashiq-ahmd please share a sample of the corrupted file and the issue can be reopened

**Comment by a7md0** [comment]
I am facing similar behavior, I have attached the file. Is there any method to determine the issue here?

[corrupted file.xlsx](https://github.com/SheetJS/sheetjs/files/8031833/corrupted.file.xlsx)

**Comment by reviewher** [comment]
Use one of the browser scripts:

"full":

```html
 <script
  src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.0/xlsx.full.min.js"
  integrity="sha512-T4di+1nz8qzzDhR2VAexSzImVjUEp3Sr4q8uGj/udkI6+V/zkGj/LVCv7cHIF8q7w+pESrsp0S6LuR5kRW3jMA==" 
  crossorigin="anonymous"
  referrerpolicy="no-referrer"></script>
```

"mini":

```html
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.0/xlsx.mini.min.js"
  integrity="sha512-kHUAzFN7ucRNW5Gq/61lqtdki6+PXjfmQGZ5rdDi7BsTJvweJIIx0RETDvlV6v5jRHmtarTccmvySLZPULsAvw==" 
  crossorigin="anonymous"
  referrerpolicy="no-referrer"></script>
```
