### ISSUE TITLE
Not able to set Column format as  number

### ISSUE THREAD

**Issue by das-devi** [SheetJS/sheetjs#2500]
Hi Team,

Can you please give an example how to set the format of a cell value to number, I see it is by default General.
I am trying to set its type is number, but it is not working. Here is my code example.

const worksheet: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(tableData);
const wscols = [];
for (const key in colWidths) {
	if ((colWidths as any)[key]) wscols.push({ wch: (colWidths as any)[key] });
}
worksheet['!cols'] = wscols;
**worksheet.A1 = { t: 'n' };**

/* generate workbook and add the worksheet */
const workbook: XLSX.WorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, fileName);

/* save to file */
let todaysDate = new Date().toLocaleDateString().replace(/\//g, '-');
XLSX.writeFile(workbook, fileName + `.xlsx`);

![image](https://user-images.githubusercontent.com/36114359/150385585-83490fde-e6c2-4963-9876-4c243df9a2b0.png)

**Comment by das-devi** [comment]
Hi Everyone, does any one came across this issue?.

**Comment by reviewher** [comment]
```js
worksheet.A1 = { t: 'n', z: "0" };
```

See https://docs.sheetjs.com/#number-formats for more info
