### ISSUE TITLE
sheetjs-xlsx not working with Angular 13

### ISSUE THREAD

**Issue by MoezMed** [SheetJS/sheetjs#2507]
![image](https://user-images.githubusercontent.com/70268991/151005370-e3119263-a1e5-447f-a431-41c4db529119.png)

Please help asap?
Thanks

**Comment by reviewher** [comment]
Please update to the latest version and try again.  That particular line and variable are not in the current source

**Comment by Coooi** [comment]
I'm using version 0.18.5 and it doesn't work on Angular 13 and 14.

**Comment by Coooi** [comment]
I'm facing the same error on Angular 13 and 14.
"xlsx": "^0.18.5",
