### ISSUE TITLE
I changed comma to Θ in sheet_to_csv

### ISSUE THREAD

**Issue by ekremtinas** [SheetJS/sheetjs#2510]
function sheet_to_csv(sheet, opts) {
	var out = [];
	var o = opts == null ? {} : opts;
	if(sheet == null || sheet["!ref"] == null) return "";
	var r = safe_decode_range(sheet["!ref"]);
	// ---   // var FS = o.FS !== undefined ? o.FS : ",", fs = FS.charCodeAt(0);
	// +++ // var FS = o.FS !== undefined ? o.FS : "Θ", fs = FS.charCodeAt(0);
	var RS = o.RS !== undefined ? o.RS : "\n", rs = RS.charCodeAt(0);
	var endregex = new RegExp((FS=="|" ? "\\|" : FS)+"+$");
	var row = "", cols = [];
	o.dense = Array.isArray(sheet);
	var colinfo = o.skipHidden && sheet["!cols"] || [];
	var rowinfo = o.skipHidden && sheet["!rows"] || [];
	for(var C = r.s.c; C <= r.e.c; ++C) if (!((colinfo[C]||{}).hidden)) cols[C] = encode_col(C);
	for(var R = r.s.r; R <= r.e.r; ++R) {
		if ((rowinfo[R]||{}).hidden) continue;
		row = make_csv_row(sheet, r, R, cols, fs, rs, FS, o);
		if(row == null) { continue; }
		if(o.strip) row = row.replace(endregex,"");
		out.push(row + RS);
	}
	delete o.dense;
	return out.join("");
}

Greetings , I found one issue in this function, if xls or xlsx document has include comma in cell,this function is spliting comma inside cells so this is not working properly. I changed comma to Θ inside upper code.You can use this solution.

**Comment by reviewher** [comment]
If you really want to use `Θ` you can pass the option `FS: "Θ"` to `XLSX.write` or `XLSX.utils.sheet_to_csv`
