### ISSUE TITLE
Error Message: Uncaught (in promise) invalid stored block lengths

### ISSUE THREAD

**Issue by BrianSHenderson** [SheetJS/sheetjs#2513]
I've written some code for processing uploaded files using NextJS and Node14.   When running locally all works well however when I deploy to Vercel I receive the error message:
```
Uncaught (in promise) invalid stored block lengths
``` 
Its still Node14 when deployed and happens in Chrome.

Any ideas?

**Comment by SheetJSDev** [comment]
That error suggests some sort of corruption in the bytes.  Azure and AWS automatically do some UTF8 conversion which causes issues with XLSX files.  https://github.com/SheetJS/sheetjs/tree/master/demos/function#aws-lambda discusses the workaround of adding "Binary Media Types".  Vercel may require a similar setting.

**Comment by reviewher** [comment]
Please verify the actual file data is correct with a checksum.  If the data is what you expect and the original file opens properly in Excel, please share the file and the issue will be reopened.

**Comment by h4ckm03d** [comment]
having same issue when deploy using using pm2. processing xlsx no error on localhost but got same error when in server

**Comment by reviewher** [comment]
@h4ckm03d probably some network issue. AWS [needs some binary setting](https://github.com/SheetJS/sheetjs/tree/master/demos/function#aws-lambda)

**Comment by h4ckm03d** [comment]
@reviewher the problem is not network issue, it caused by `swcMinify` is true on `next.config.js`. After I disabled `swcMinify` then rebuild. everything run normally.

**Comment by reviewher** [comment]
That sounds like a potential bug with swc? https://github.com/swc-project/swc/issues
