### ISSUE TITLE
Zip multiple excel files before download

### ISSUE THREAD

**Issue by CarlosMaranje** [SheetJS/sheetjs#2514]
Hello, I'm using sheetsJs to generate a report containing more than 800 files. Everything works as expected. However, a download dialog is prompted for each file downloaded. I solved this quickly by changing my browser's behaviour. But not every user might be capable of doing this and they finish by clicking 800+ times the "download" button if the browser does not crash before. 

**My question is:** Is there a way to generate the excel files, zip them and then download the zip containing the files, using sheetsJs or sheetsJs combined with anything else? This will only prompt a single dialog for the zip, and that's more than fine.

Thanks in advance..

**Comment by reviewher** [comment]
Use `XLSX.write` to generate each file data and use [`fflate`](https://github.com/101arrowz/fflate) or [`cfb`](https://github.com/sheetjs/js-cfb) to generate a ZIP file that contains those files
