### ISSUE TITLE
Block certain cells in sheetJS Excel

### ISSUE THREAD

**Issue by gauravr7** [SheetJS/sheetjs#2518]
How can we lock certain cells in excel by using SheetJs ws['!protect']

There is a Worksheet Protection Details section which has some keys but there usage is not clear from the documentation.

https://github.com/SheetJS/sheetjs/blob/master/README.md

If somebody has used it or have any idea please help me.

**Comment by SheetJSDev** [comment]
Those settings are the worksheet-level protection settings.  Cell-level protection is unfortunately tied to cell styling.

We don't know when that will be added to the Community Edition but it will be after a "1.0.0" release.  In the interim, we do offer it in our [Pro compendium](https://sheetjs.com/pro)
