### ISSUE TITLE
Cell starting from middle with uneditable whitespace on top

### ISSUE THREAD

**Issue by cmgchess** [SheetJS/sheetjs#2520]
Hello 👋

I ran into an issue and couldn't find a reason myself or on the internet. The issue was I'm setting a `hpx` and `wpx` and in the result the values in my cell start from the middle of the cell and not from the top of the cell. Also I cannot type anything or bring cursor in that empty space.
My values coming from a JSON response have bullet points and new lines. Initially when I open the sheet the bullet point values are shown next to each other instead of new lines. But when I double click on the cell the bullet points get into  new lines. 
eg cell  `C53: {t: 's', v: '• value1\r\n• value2\r\n• value3'}`
I don't know if that also affects the issue for getting empty spaces.

![image](https://user-images.githubusercontent.com/61736812/153591933-ddfcb7c0-5f16-45ed-a1e7-b25efc4fe4d5.png)

This is how the implementation is done
```javascript
              var wb = XLSX.utils.book_new();
              var ws = XLSX.utils.json_to_sheet(result, {
                header: _.chain(result).first().keys().value()
              });

              var range = XLSX.utils.decode_range(ws['!ref']);
              var noRows = range.e.r; 
              var noCols = range.e.c; 
              var wsrows= Array(noRows).fill({hpx: 50})
              var wscols= Array(noCols).fill({wpx: 100})

              ws['!rows'] = wsrows;
              ws['!cols'] = wscols;
              console.log(ws)
              XLSX.utils.book_append_sheet(wb, ws, 'mysheet');
              XLSX.writeFile(wb, 'myfile.xlsx', {
                bookType: 'xlsx'
              });
```

If there are any extra configurations I have to do I'm not aware. Help is much appreciated.

**Comment by SheetJSDev** [comment]
Unfortunately it requires setting the wrap text styling property of the cell.  Styling is currently a feature in our [Pro Compendium](https://sheetjs.com/pro) and may eventually be brought into the open source build after the v1 release.
