### ISSUE TITLE
Cannot open exported xlsx file containing Japanese character

### ISSUE THREAD

**Issue by duchm12** [SheetJS/sheetjs#2522]
Hi, thanks for this amazing library. 

Issue: I am using to SheetJS export array of arrays with each element is a Japanese characters to xlsx file. So far, I have tried with xlsb file working fine but when I tried to export it to xlsx file and open it, excel reports an error in XML parsing. Here are my code:  
![image](https://user-images.githubusercontent.com/99295405/153986178-50967072-c2c6-4f38-9ac1-a197692061f2.png)

I tried switching array of arrays contains only Latin characters worked, or one row and Latin character and one row Japanese characters also worked. But 2 rows of Japanese characters next to each other make the output file error.

This is the output I wants look like this
![image](https://user-images.githubusercontent.com/99295405/153987173-7aa06eb0-21dd-4261-b89c-1511487b00d3.png)

Hope you could give me some insight, thanks.

**Comment by reviewher** [comment]
Are you using the latest version?  `console.log(XLSX.version)` when you do the export.

If you are using the latest version (0.18.1) can you share the data or the broken XLSX file?

**Comment by duchm12** [comment]
Hi,
`console.log(XLSX.version`) showing that I am using 0.18.1

**Comment by reviewher** [comment]
Can you share the broken file?  You can click-drag the file into the github issue box ("Attach files by dragging & dropping, selecting or pasting them.")

**Comment by duchm12** [comment]
I upload the file, but saddly I can not open it because file showing error below:

**Comment by duchm12** [comment]
When opening a file, I got error like this:
![image](https://user-images.githubusercontent.com/99295405/153989234-df6d8628-28ba-41e8-9f27-75d142bf7a23.png)

For more information, here is my array of arrays object:
![image](https://user-images.githubusercontent.com/99295405/153989345-4380f886-3321-4bb1-be30-1815aea10bce.png)

**Comment by reviewher** [comment]
The resulting XML looks truncated (sheet1.xml ends with `></`).  Instead of manually doing all this, can you try forcing a download using `writeFile`? 

```js
XLSX.writeFile(workbook, `${fileName}.xlsx`)
```

This will create the file (like `XLSX.write`) and also attempt a download (like you are trying to do with the URL)

**Comment by duchm12** [comment]
Hi,
I have tested with `XLSX.writeFile(workbook, `${fileName}.xlsx`)`, unfortunately, it did not work well for me. When open the output file, I got:
![image](https://user-images.githubusercontent.com/99295405/153991148-66443566-f2d0-4740-a5ed-fe36cc8ff434.png)

**Comment by duchm12** [comment]
Sorry for my hasty reply, I sent wrong image output above.  When opening the file using `writeFile`. I encountered with:
![image](https://user-images.githubusercontent.com/99295405/153991839-1fe38e6b-30f1-46d4-9076-fc022d4aaf71.png)

**Comment by SheetJSDev** [comment]
This is probably the same issue reported in #2521 , but by pure coincidence it did not trigger an invalid file for @lanchengkai .  There is a truncation in the utf8 encoding and we'll rush an update.

**Comment by duchm12** [comment]
Hi,
I tried to look at  the output xlsx file as .xml document using zip tool, found that in sheet1.xml missing 3 closing tags as below:
![image](https://user-images.githubusercontent.com/99295405/153998838-9406835f-efb4-42e4-a6ec-32fa96c3a1b9.png)
I modified (add closing tags to sheet1.xml) and reopened the file output. The file open without any error. Does this have any relation to how the `XLSX.write()` works or am I missing any step?

**Comment by SheetJSDev** [comment]
Here is a compressed [xlsx.full.min.js.zip](https://github.com/SheetJS/sheetjs/files/8066106/xlsx.full.min.js.zip) with what is believed to be a fix.  Can you try by extracting, then using this as your `xlsx.full.min.js` in your page?

**Comment by duchm12** [comment]
I'm using Vue 2 framework for my web application, does 'xlsx.full.min.js' install with the 'xlsx' npm package?

**Comment by SheetJSDev** [comment]
No worries, can you try replacing the dependency with [`xlsx-issue2522@0.18.1`](https://www.npmjs.com/package/xlsx-issue2522)?

**Comment by duchm12** [comment]
Hi,
Thanks for the quick action. The new package `[xlsx-issue2522@0.18.1](https://www.npmjs.com/package/xlsx-issue2522)` works as expected. Is `xlsx-issue2552` temporary fix or will you incorporate it in the main `xlsx` package?

**Comment by SheetJSDev** [comment]
It will be, just want to be sure we identified the root cause first.

**Comment by duchm12** [comment]
May I ask when is the next stable release?

**Comment by SheetJSDev** [comment]
30 minutes-ish

**Comment by duchm12** [comment]
Glad to hear it. That's all for now. Thanks for your swift and amazing support!

**Comment by SheetJSDev** [comment]
The node/deno tests passed (sauce labs grid will refresh momentarily, but it passed IE10/11 and Chrome and iOS Safari tests).  The module has been published to npm (xlsx@0.18.2) and the tag has been pushed, it may take a few minutes for the registry to reload.  Please verify, and sincere apologies for the issue in the first place.
