### ISSUE TITLE
The exported data is missing

### ISSUE THREAD

**Issue by ITEr-TSG** [SheetJS/sheetjs#2523]
Can you take a look for me? Why is there 31 exported excle data missing in the array？
[missdata.zip](https://github.com/SheetJS/sheetjs/files/8067074/missdata.zip)

**Comment by reviewher** [comment]
Please test against 0.18.2 (just released) -- this looks like the same issue as #2522 and #2521

**Comment by ITEr-TSG** [comment]
It's normal now. Thank you very muchヽ(✿ﾟ▽ﾟ)ノ
