### ISSUE TITLE
utf 8 encode problems

### ISSUE THREAD

**Issue by ekremtinas** [SheetJS/sheetjs#2524]
I'm using sheet_to_csv and read functions but  problem with dutch letters. for example "è".Please help me. :(

**Comment by reviewher** [comment]
If you are reading a file first, can you share the original file and a code snippet?  (basically, how can the issue be reproduced?)

**Comment by ekremtinas** [comment]
Actually I asked if "read()" or "sheet_to_csv()" functions has utf8 option

**Comment by ekremtinas** [comment]
```
const readFile=(file)=> {
    var f = file;
    var name = f.name;
    const reader = new FileReader();
    reader.onload = (evt) => {
      const bstr = evt.target.result;
      let wb = XLSX.read(bstr, { type: "binary" });
      /* Get first worksheet */
      const wsname = wb.SheetNames[0];
      const ws = wb.Sheets[wsname];
      /* Convert array of arrays */
      let data = XLSX.utils.sheet_to_csv(ws, { header: 1 });

      let jsonData=convertToJson(data);
}
```
[https://we.tl/t-awzoEZ5TIx](url)

**Comment by reviewher** [comment]
The attachment is an ODS.

Opening the file in ODS shows "ë" characters ("\u00EB").  That same thing is shown in oss.sheetjs.com (notice cell D4)

<img width="1011" alt="Screen Shot 2022-02-15 at 12 55 59 PM" src="https://user-images.githubusercontent.com/24845478/154120807-4f23a2b6-c972-4b1b-9aca-35cec0c0356f.png">

https://oss.sheetjs.com/sheetjs/ also shows the same code.  ODS should be using UTF8 under the hood, which means there really shouldn't be any difference.  If you are seeing a difference, please update to the latest version (0.18.2) and test again.  If it is still a problem, please share the version of LibreOffice and a sample text so we can either reproduce or raise an issue with LO
