### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by blueiceprj** [SheetJS/sheetjs#2526]
Angular 13 - xlsx

Version : 0.18.2

Module not found: Error: Can't resolve './dist/cpexcel.js' in '....../node_modules/xlsx/dist'

**Comment by blueiceprj** [comment]
I am using "xlsx.mini.min.js" to export data. In 0.18.0 version everything works fine.

**Comment by SheetJSDev** [comment]
0.18.1 flipped from CJS to ESM.  You should be using the import directly without an override.

Irrespective of best practices, it should work with the mini build. How are you doing the webpack override?

**Comment by SheetJSDev** [comment]
@blueiceprj @kingyue737 just pushed a commit with a few fixes to remove some node globals and manually suppress the require statements.  If you have control over the override, can you manually download [the `xlsx.mini.min.js` script from the repo](https://raw.githubusercontent.com/SheetJS/sheetjs/master/dist/xlsx.mini.min.js) and adjust the webpack config to use this?  If it works, we can publish a new release with the changes
