### ISSUE TITLE
issue on getting header names using sheetRows

### ISSUE THREAD

**Issue by arushigupta31** [SheetJS/sheetjs#2531]
Hi, I am trying to get the headers (i.e. first row ) from the excel sheet which has 5 columns and 2 rows using
    XLSX.read(fileName, { sheetRows: 1 });

but the result i am getting is {
    "SheetNames": [
        "Sheet1"
    ],
    "Sheets": {
        "Sheet1": {
            "A1": {
                "t": "s",
                "v": "JÛz{l￾z\u0004®´¡yëuåË/"
            },
            "!ref": "A1"
        }
    }
}
What can be the reason for it ? And how can i resolve it and get the headers?

**Comment by Reidond** [comment]
hi, can you send sample file or repo to reproduce error?

**Comment by SheetJSDev** [comment]
Without a `type` option, `XLSX.read` assumes strings are the spreadsheet bytes encoded in Base64.

Based on the variable name you are probably trying to read a file.  In Deno or Node, use `XLSX.readFile`.  In the browser, you need to somehow get the data into the browser (e.g. `fetch`).  The ["Parsing Workbooks" examples](https://github.com/SheetJS/sheetjs#parsing-workbooks) covers a number of common scenarios for data acquisition

**Comment by arushigupta31** [comment]
> hi, can you send sample file or repo to reproduce error?
[sample - Sheet1.csv](https://github.com/SheetJS/sheetjs/files/8129746/sample.-.Sheet1.csv)
Hi you can use this sample file and use XLSX.read(fileName, { sheetRows: 1 }); which i did for reading headers.
