### ISSUE TITLE
create a xlsx from json of 500 MBs

### ISSUE THREAD

**Issue by wilberever100** [SheetJS/sheetjs#2532]
I was trying to create a xlsx file from a json of 500MBs, but is not working, it keeps working without response. This works for 250MBs file.

I tried with the commented part  dividing in two blocks the json file, and not getting response again

`const convertJsonToExcel = () => {
    
    var arr=bigJson['titulo']

    // arr2=arr.slice(arr.length/2, arr.length-1)
    // arr=arr.slice(0, arr.length/2)
    // arr3=arr.slice(0, 1)

    console.log(typeof(bigJson))

    const workSheet = XLSX.utils.json_to_sheet(arr);

    //XLSX.utils.sheet_add_json(workSheet,arr2,{origin: -1});

    const workBook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workBook, workSheet, "students")
    XLSX.writeFile(workBook, "studentsData.xlsx")

}`

What could be a good strategy to create a xlsx file with huge size  250MBs to 750 MBs aprox

**Comment by reviewher** [comment]
How many rows / columns are in the worksheet?

**Comment by reviewher** [comment]
Similar to #77 .  Please follow up there with some metrics and we can take a closer look.
