### ISSUE TITLE
upload .xls document, error

### ISSUE THREAD

**Issue by mixuerr** [SheetJS/sheetjs#2533]
When i upload a .xls document, error:  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'decode'), why？
![LQBPJwKRog](https://user-images.githubusercontent.com/53210385/155669986-6041fa6a-5366-4ac8-9319-c0d9c8799e46.png)
![tEbDdog7Ks](https://user-images.githubusercontent.com/53210385/155670021-050537d8-f41f-4ed4-abcc-70f130e3fbb9.png)

**Comment by reviewher** [comment]
Probably a webpack issue.  Are you overriding the xlsx import?

**Comment by reviewher** [comment]
Please check against the latest version (0.18.3).  If the problem still persists, we can reopen the issue.
