### ISSUE TITLE
HTML Table to xlsx decimal configuration

### ISSUE THREAD

**Issue by Xt-Man** [SheetJS/sheetjs#2535]
Hi, my HTML table has numbers like 7.690,00 the "." separate thousands and "," is the decimal separator
In excel this number appears 7,69 (, decimal)
How can i configure the thousands and decimal separators of my country?
I'm using like this
`function ExportToExcel(type, fn, dl) {
	var elt = document.getElementById('tbl_exporttable_to_xls');
	var wb = XLSX.utils.table_to_book(elt, { sheet: "DRE" });
	return dl ?
		XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }):
		XLSX.writeFile(wb, fn || ('DRE.' + (type || 'xlsx')));
}`

 Thank's for help

**Comment by SheetJSDev** [comment]
The thousands separator and decimal separator are determined by the system locale in Excel.  When writing a number format, the en-US form will be translated by Excel.

For safe transmission of data, add the `data-t`, `data-v` and `data-z` attributes:

```html
<td data-t="n" data-v="7690.00" data-z="#,##0.00">7.690,00</td>
```

https://jsfiddle.net/8jghruLv/ live demo:

**HTML**

```html
<table id="tbl_exporttable_to_xls">
  <tr>
    <th>Raw</th><th>Attr</th>
  </tr>
  <tr>
    <td>7.690,00</td>
    <td data-t="n" data-v="7690.00" data-z="#,##0.00">7.690,00</td>
  </tr>
</table>
```

**JS**

```js
var elt = document.getElementById('tbl_exporttable_to_xls');
var wb = XLSX.utils.table_to_book(elt, { sheet: "DRE" }); 
XLSX.writeFile(wb, "issue2535.xlsx");
```
