### ISSUE TITLE
FileReader.readAsBinaryString return binary,  xlsx read it  error , Uncaught TypeError: Cannot read properties of undefined (reading 'read')

### ISSUE THREAD

**Issue by alanOO7** [SheetJS/sheetjs#2541]
uploadChange(file){
        let reader = new FileReader()
        reader.onload = ev => {
            console.log("ev.target.result")
            console.log(ev.target.result)
            let dataBinary=ev.target.result
            console.log(dataBinary)
            let workBook = xlsx.read(dataBinary, {type: 'binary'})
            let workSheet = workBook.Sheets[workBook.SheetNames[0]]
            const data = xlsx.utils.sheet_to_json(workSheet)
            console.log(data) 
      }
    console.log(file)
    reader.readAsBinaryString(file)   //return Binary 
    console.log(reader)

read excel to json         
 Uncaught TypeError: Cannot read properties of undefined (reading 'read')

**Comment by reviewher** [comment]
It looks like the error stems from `xlsx` being undefined.  If you are using the browser builds, the global is `XLSX` (capital letters).  If you are using `require`, make sure you are using the correct case.  If you are using `import xlsx from 'xlsx'`, try the glob form `import * as xlsx from 'xlsx'`

**Comment by alanOO7** [comment]
thanks!
