### ISSUE TITLE
Error: Invalid HTML: could not find <table>

### ISSUE THREAD

**Issue by arladmin** [SheetJS/sheetjs#2543]
```
//  index.js

const XLSX = require("xlsx");
const workbook = XLSX.readFile("test.html");
```
I am running into this error unexpectedly.
Can't figure out the reason why.

The html does have proper ```<table>``` tags for the only table in the file.

**Comment by reviewher** [comment]
Can you share the contents of test.html?

**Comment by arladmin** [comment]
> Can you share the contents of test.html?

PFA
[test.zip](https://github.com/SheetJS/sheetjs/files/8191842/test.zip)

**Comment by SheetJSDev** [comment]
Feel free to send a PR.  The change applies to [`bits/79.html.js`](https://github.com/SheetJS/sheetjs/blob/master/bits/79_html.js#L62):

```diff
diff --git a/bits/79_html.js b/bits/79_html.js
@@ -59,7 +59,7 @@ var HTML_ = (function() {
                return ws;
        }
        function html_to_book(str/*:string*/, opts)/*:Workbook*/ {
-               var mtch = str.match(/<table.*?>[\s\S]*?<\/table>/gi);
+               var mtch = str.match(/<table[\s\S]*?>[\s\S]*?<\/table>/gi);
                if(!mtch || mtch.length == 0) throw new Error("Invalid HTML: could not find <table>");
                if(mtch.length == 1) return sheet_to_workbook(html_to_sheet(mtch[0], opts), opts);
                var wb = utils.book_new();
```

(the TABLE open tag was split across multiple lines in the example file)

**Comment by reviewher** [comment]
a32b30414b3a1da61ba6d6b847a473f54481815a
