### ISSUE TITLE
How to custom the display column heard name

### ISSUE THREAD

**Issue by mansai** [SheetJS/sheetjs#2545]
![image](https://user-images.githubusercontent.com/3213405/156975328-ba06d39c-468b-4728-9c81-3d5be92c957a.png)

**Comment by reviewher** [comment]
Can you share a sample file with that effect?

**Comment by SheetJSDev** [comment]
In general this is not possible.  Newer versions of Excel may replace the labels if you are in a Table and the header row is not visible, but it is definitely not possible on row 1.
