### ISSUE TITLE
Import excel with wrong decimal value

### ISSUE THREAD

**Issue by pvaritta** [SheetJS/sheetjs#2546]
I had imported the excel file with the values below
![image](https://user-images.githubusercontent.com/18564575/157159165-3d783894-0b9d-42d0-8152-42e71d6a53fd.png)
 
 After  I import this value, I found that the decimal of value has changed from **102.717452969 to 102.71745296899999** as the screenshot below with red box
 
 
![image](https://user-images.githubusercontent.com/18564575/157159329-96076645-9941-41dc-ad90-fa6e90ea9e2e.png)

Here's my code 
![image](https://user-images.githubusercontent.com/18564575/157159528-3af1d6ae-418e-4906-b15b-51908d37da10.png)

after log the workbook and jsonData properties  the value has been changed as I mention before.

**My question is, why the value has changed or I miss something and make the value changed?**

**Comment by SheetJSDev** [comment]
For Excel XLS/XLSX/XLSB files, the `v` value is the actual value stored in the file and the `w` is the formatted number that you will see in the cell.  For numeric cells, the value is an IEEE754 double.

If you want to see a clearer example, the attached file set A1=0.1, A2=0.2, A3=A1+A2: [issue2546.xlsx](https://github.com/SheetJS/sheetjs/files/8202476/issue2546.xlsx)

If you try to read it in SheetJS you will get

<img width="398" alt="issue2546" src="https://user-images.githubusercontent.com/6070939/157160707-a3eb15d4-f169-4b99-94a8-b5c6fa94139f.png">

That `0.30000000000000004` is not a mistake -- it is the same value you would get by running `0.1+0.2` in your JS REPL.
