### ISSUE TITLE
How to get specific rows using xlsx

### ISSUE THREAD

**Issue by Rajitha75** [SheetJS/sheetjs#2549]
I have found a code where we can get first 'n' rows of an excel as below

      let workbook = XLSX.readFile('./files/uploaded_files/RA/' + filedata[j].DocName, {sheetRows: 10})
      const wsname = workbook.SheetNames[0];
      const ws = workbook.Sheets[wsname];

But, How can I get specific rows like mth row to nth row (eg 101 to 200 rows)?

**Comment by reviewher** [comment]
duplicate of #475
