### ISSUE TITLE
Xlsx files from gsheets are not parsed in the same way as ones from mac and windows spreadsheets

### ISSUE THREAD

**Issue by defusioner** [SheetJS/sheetjs#2571]
As comes from the title, we have a strange behavior on the parsing side.

Mac and Windows work great, but gsheet converts to strangely high numbers.

- gSheets latest version as of 21/09/2020
- Windows 10 with latest excel
- Mac with the latest Catalina Numbers

Tell me please if you need more info.

Here are images and files:

![original](https://user-images.githubusercontent.com/7025961/93782151-85182700-fc2a-11ea-8286-4b5acb3b3bc7.png)

![gsheet](https://user-images.githubusercontent.com/7025961/93781272-7da44e00-fc29-11ea-9a4b-3c4d2072c354.png)
![mac](https://user-images.githubusercontent.com/7025961/93781317-8bf26a00-fc29-11ea-89f4-84dc7535f8df.png)
![windows](https://user-images.githubusercontent.com/7025961/93781414-a593b180-fc29-11ea-8fe1-f3d6febf9479.png)

[Cryotherapy.gsheet.xlsx](https://github.com/SheetJS/sheetjs/files/5256068/Cryotherapy.gsheet.xlsx)
[Cryotherapy.mac.xlsx](https://github.com/SheetJS/sheetjs/files/5256069/Cryotherapy.mac.xlsx)
[Cryotherapy.windows.xlsx](https://github.com/SheetJS/sheetjs/files/5256070/Cryotherapy.windows.xlsx)

**Comment by reviewher** [comment]
Commit e0fc89246aff858ac1de8950a1e3b1dd8c3e6c65 fixes this specific format.
