### ISSUE TITLE
BigInt formatting not working

### ISSUE THREAD

**Issue by clement911** [SheetJS/sheetjs#2602]
`ssf.format('000', 1)` returns '001'
`ssf.format('000', 1n)` returns '1' instead of '001'

More info on BigInt can be found here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by SheetJSDev** [comment]
This is not planned, at least not until Excel decides to support big numbers.  For the last 35 years of Excel, the set of valid numbers is a subset of finite normal IEEE754 doubles, which is covered by the JS number type.  If Excel adds a big integer or decimal128 or other extended numeric type, we'll revisit.
