### ISSUE TITLE
vue3 vite2使用报错： does not provide an export named 'default'

### ISSUE THREAD

**Issue by hb2013** [SheetJS/sheetjs#2605]
SyntaxError: The requested module '/node_modules/.vite/xlsx.js?t=1646880501094&v=ac5f7de7' does not provide an export named 'default'

**Comment by SheetJSDev** [comment]
Use
 
```js
import * as XLSX from 'xlsx'
```

or "named imports":

```js
import { utils, writeFileXLSX } from 'xlsx';
```

**Comment by mengandxa** [comment]
> Use
> 
> ```js
> import * as XLSX from 'xlsx'
> ```
> 
> or "named imports":
> 
> ```js
> import { utils, writeFileXLSX } from 'xlsx';
> ```

good
