### ISSUE TITLE
How to add dropdown list to an column while writing into other column, so that user can simply select from dropdown.

### ISSUE THREAD

**Issue by gokinasaiajay** [SheetJS/sheetjs#2606]
I have an requirement, to download employee details in XL format where I write employee ID, name and download XL file. 
user need to provide 
type of employee = ["part Time", "Full Time"].
for the user Can we format the column(employee type)  give dropdown list.

**Comment by SheetJSDev** [comment]
In Excel that would be implemented as a "List Data Validation", which is not currently supported in the open source build.  It will be added sometime after core data interchange issues are addressed.  If this is something you need in the short term, we do offer it as part of our [Pro offering](https://sheetjs.com/pro)

**Comment by gokinasaiajay** [comment]
can we increase the width of the cell in community version then ?
If yes where is the feature avialable ?

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/sheetjs#row-and-column-properties currently its a column-level manual setting.  https://github.com/SheetJS/sheetjs/issues/1473  discusses the automatic width problem

**Comment by mayank5dawra** [comment]
We are planning to use pro version. So can you please provide the demo or the code snippet for list validations in excel.
