### ISSUE TITLE
How to change that, it didn't remove all colours and pictures?

### ISSUE THREAD

**Issue by xdarkki** [SheetJS/sheetjs#2608]
**It shouldn't change the colours etc. or that it keep it
How can I reuse old settings from file?**

Code:
```
var XLSX = require('xlsx');

var workbook = XLSX.readFile('SRG blacklist.xlsx', {cellDates:true, cellStyles:true, bookVBA:true });

const worksheet = workbook.Sheets["Blacklist"];

const data = XLSX.utils.sheet_to_json(worksheet);

function delete_ws(wb, wsname) {
    const sidx = wb.SheetNames.indexOf(wsname);
    if(sidx == -1) throw `cannot find ${wsname} in workbook`;
    
    // remove from workbook
    wb.SheetNames.splice(sidx,1);
    delete wb.Sheets[wsname];
  
    // update other structures
    if(wb.Workbook) {
      if(wb.Workbook.Views) wb.Workbook.Views.splice(sidx, 1);
      if(wb.Workbook.Names) {
        const names = wb.Workbook.Names;
        for(let j = names.length - 1; j >= 0; --j) {
          if(names[j].Sheet == sidx) names = names.splice(j,1);
          else if(names[j].Sheet > sidx) --names[j].Sheet;
        }
      }
    }
}
delete_ws(workbook, "Blacklist");
XLSX.utils.book_append_sheet(workbook, worksheet, "Blacklist");
XLSX.writeFile(workbook, "test.xlsx");
```

Result:
![Screenshot_276](https://user-images.githubusercontent.com/61346219/158071330-5db9d19b-661e-451f-ad42-193bffb002c6.png)

View:
![Screenshot_277](https://user-images.githubusercontent.com/61346219/158071337-8b6b0fa9-d902-429a-bf09-6e2c5a9bc0e8.png)

**Comment by SheetJSDev** [comment]
Metadata like "Format as Table" tables, styling, and images are not currently supported in the Community Edition.  The main short-term focus is correctness in data interchange (reliably reading data from spreadsheets and generating exports that accurately reflect the desired data).  [As part of our Pro offering](https://sheetjs.com/pro) we offer more advanced metadata support.
