### ISSUE TITLE
While reading long number in excel it is converting to exponential format

### ISSUE THREAD

**Issue by gokinasaiajay** [SheetJS/sheetjs#2610]
While entering long number in excel it is converting to exponential format (it is fine, behind data is still long number).
But, while reading data in typescript. it is just reading exponential number, and data after some digit are lost and zero is appended.

**Comment by reviewher** [comment]
The cell `v` property has the original numeric value and the `w` is the formatted text.  Share some code and we can advise on how to get the values

**Comment by gokinasaiajay** [comment]
I have - 12345678901234 in excel. 
var workbook = XLSX.read(inputBuffer, { type:"binary", cellDates: true });
var worksheet = workbook.Sheets[workbook.SheetNames[0]];
var array = XLSX.utils.sheet_to_json(worksheet, {raw: true});

particular cell is read as (worksheet) :
{ t : 'n', w:'1.23457E+13' v:12345700000000 }

**Comment by SheetJSDev** [comment]
That is definitely unexpected, can you share the file?  If you can't do it publicly, you can email hello@sheetjs.com

**Comment by gokinasaiajay** [comment]
Shared details via mail.

**Comment by gokinasaiajay** [comment]
these is some issue in the excel. while uploading the fresh excel with data. then data is getting read properly.
please share the excel If you can with dev.

**Comment by yongkyunlee** [comment]
It happened when I was using .csv file, but it was okay for .xlsx file.

**Comment by Nagaraj172004** [comment]
if ur using **sheet_to_json** method or function use in body raw: true :

this.importData= XLSXSample.utils.sheet_to_json(wb.Sheets[sheet_name_list[0]], { raw: true,});
