### ISSUE TITLE
csv file with cyrrilic symbols parses wrong (encoding) 

### ISSUE THREAD

**Issue by Bobrovskih** [SheetJS/sheetjs#2613]
https://oss.sheetjs.com/sheetjs/
file in attachment
[файл.csv](https://github.com/SheetJS/sheetjs/files/8252662/default.csv)
<img width="580" alt="Снимок экрана 2022-03-15 в 14 20 28" src="https://user-images.githubusercontent.com/34475297/158367020-3b81c7ff-2ec4-4ea5-9810-579b871eba70.png">

I want to see result like this: 
<img width="379" alt="Снимок экрана 2022-03-15 в 14 20 55" src="https://user-images.githubusercontent.com/34475297/158367109-dc8c639c-a085-4e35-a847-5251d4a6f5c7.png">

How to fix this? 
It also parses ok, if i use manual `new TextReader().decode(str);` without sheetjs

**Comment by SheetJSDev** [comment]
Actually, the demo should have an option to select codepage.

To keep it simple:

- add a UTF8 checkbox [after Web Workers setting](https://github.com/SheetJS/sheetjs/blob/master/index.html#L43)
- [when reading, check the value](https://github.com/SheetJS/sheetjs/blob/master/index.html#L145)
- when workers are not used, [the option should be added to the options object](https://github.com/SheetJS/sheetjs/blob/master/index.html#L168)
- when workers are used, [the option needs to be sent to the worker](https://github.com/SheetJS/sheetjs/blob/master/index.html#L157) and [the worker needs to pass it along to the read function](https://github.com/SheetJS/sheetjs/blob/master/xlsxworker.flow.js#L13)

**Comment by dkostochko** [comment]
Please, use the option `codepage` when you call the method `readFile` 
`xlsx.readFile("./test/data/" + name, { codepage: "65001", cellStyles: true });`

**Comment by SheetJSDev** [comment]
https://oss.sheetjs.com/sheetjs/ updated demo
