### ISSUE TITLE
json_to_sheet cannot handle large json data

### ISSUE THREAD

**Issue by anandmuthu1978** [SheetJS/sheetjs#2615]
Hi Experts,

I am using the utility json_to_sheet to convert a large json array to sheet. Details are as below.
JSON data = 100K rows with 120 columns. So roughly about 10 - 11 million cells.
 
I have tried to convert this dataset directly one shot but the browser tab just freezes without any error. I have tried to reduce the memory consumption by adding the data by single rows using sheet_add_json. However, this still fails. There is no error displayed that identifies the issue and I am just assuming its memory. Chrome task manager shows high CPU usage and about 1.3 gb memory footprint but the system has sufficient memory to handle that. 

Anyway, to improve the way to convert this or any other way to handle the large dataset using sheetjs. Hope you can shed some light into the matter.

Thanks.
Anand Muthu

**Comment by SheetJSDev** [comment]
Pass the option `dense: true` to `json_to_sheet`.  We hope to change the default at some point.

**Comment by anandmuthu1978** [comment]
Unfortunately, this didnt seem to work.

**Comment by devdiegovieira** [comment]
I have the same problem
