### ISSUE TITLE
What changed in 0.18.3 and 0.18.4

### ISSUE THREAD

**Issue by sandrooco** [SheetJS/sheetjs#2618]
I saw that there are two new versions - they don't have any changelog though. I'd love to update but am a bit hesitant because I don't know what happens...
Is there somewhere a summary for this?

**Comment by SheetJSDev** [comment]
The goal of this 0.18.x series is for the ESM build to play nice with tree-shaking/bundling as well as Deno and NodeJS.  For example, 0.18.1 introduced `writeFileXLSX` which writes only XLSX files.  Comparing bundle sizes in the last few releases:

[v0.18.1: 314kB -> 105 kB minified](https://bundle.js.org/?q=xlsx@0.18.1&treeshake=[{+writeFileXLSX+}])


[v0.18.3: 280kB -> 95.7 kB minified](https://bundle.js.org/?q=xlsx@0.18.3&treeshake=[{+writeFileXLSX+}])

[v0.18.4: 138kB -> 44.9 kB minified](https://bundle.js.org/?q=xlsx@0.18.3&treeshake=[{+writeFileXLSX+}])


Most of the changes are "under the hood" and did not necessarily merit an entry in the CHANGELOG.  The changes which do have an observable impact:

v0.18.3:

- Eliminate all references to `require` and `process` in the browser standalone builds to address a [bug in create-react-app](https://github.com/facebook/create-react-app/issues/11756)
- Improve performance when exporting files with many links (#2537)
- XLSX / XLSB dynamic array formulae import and export
- Deno avoid unnecessary conversion from `Uint8Array` to binary string and back

v0.18.4:

- Properly terminate NodeJS streams (#1779)
- CSV omit trailing record separator
- HTML import correctly skip cells whose content is empty after trimming (#1621)
- DBF preserve column types on import and use when applicable on export (#1888)
- `sheet_to_json` new option `skipHidden` to skip hidden rows and columns
- XLSX / XLSB threaded comments import and export (#2542)
