### ISSUE TITLE
Trying to return xlsx content resulting in un openable file

### ISSUE THREAD

**Issue by Godrules500** [SheetJS/sheetjs#2619]
I am working with a rest api and cannot save the file. Because of this I am needing to convert JSON to an excel file content, but when I do this, I am getting an error saying that it cannot open the file.

Code:
```
const book = XLSX.utils.book_new();
const sheet = XLSX.utils.aoa_to_sheet([
    ["a", "b", "c"],
    [1, 2, 3]
]);
XLSX.utils.book_append_sheet(book, sheet, "test");

// Method 1 : failed to open the saved file
const content = XLSX.write(book, { type: 'binary', bookType: 'xlsx', bookSST: false });
return content;
```

The response I am getting is:
PK         ÒsÉ-  -     xl/_rels/workbook.xml.rels PK         Ý¨G       xl/theme/theme1.xml PK           õ¸L  L  
   xl/styles.xml PK         ôéÃéX  X     xl/worksheets/sheet1.xml PK         â¨Mj@  @     xl/workbook.xml PK         gµm~L  L     _rels/.rels PK         $§ç0  0     docProps/app.xml PK         R«ïÏZ  Z     docProps/core.xml PK         íª=       [Content_Types].xml PK           ÒsÉ-  -                   xl/_rels/workbook.xml.relsPK           Ý¨G                 e  xl/theme/theme1.xmlPK             õ¸L  L  
             0   xl/styles.xmlPK           ôéÃéX  X               §$  xl/worksheets/sheet1.xmlPK           â¨Mj@  @               5'  xl/workbook.xmlPK           gµm~L  L               ¢(  _rels/.relsPK           $§ç0  0               +  docProps/app.xmlPK           R«ïÏZ  Z               u-  docProps/core.xmlPK           íª=                 þ.  [Content_Types].xmlPK    	 	 >  Á6

**Comment by SheetJSDev** [comment]
You're facing some intermediate process or library that is interpreting the body as UTF8.  AWS Lambda and other function hosts do this by default.  There are two workarounds: either send Base64 and decode on the receiver side OR check with your provider.  https://github.com/SheetJS/sheetjs/tree/master/demos/function#aws-lambda has instructions for AWS
