### ISSUE TITLE
About xlsx.extendscript.js

### ISSUE THREAD

**Issue by jlzyyds** [SheetJS/sheetjs#2629]
I include the file "xlsx.extendscript.js" in a After effects script file (.jsx), when executing the script will encounter an error:

code:
![1648389245861](https://user-images.githubusercontent.com/99283952/160284927-83ae307a-2e5b-4ec8-ba17-5fb8bb4ca5d0.jpg)

Syntax Error:
Unterminated string constant <= line:5620 column:9 file: /Users/xxx/aeproject/script/smscript/node_modules/xlsx/dist/xlsx.extendscript.js.

![1648388326137](https://user-images.githubusercontent.com/99283952/160284554-bf3cc447-6f59-4e9d-860a-6901ded30c53.jpg)

The After Effects version is 2020 for MAC
VSCode version is 1.65.2 

Thank you for your help ！

**Comment by SheetJSDev** [comment]
Does the same issue show up when using the ExtendScript toolkit directly (https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit) ?

**Comment by jlzyyds** [comment]
> Does the same issue show up when using the ExtendScript toolkit directly (https://github.com/Adobe-CEP/CEP-Resources/tree/master/ExtendScript-Toolkit) ?

The tool is only available in 32-bit version and is officially no longer supported or maintained.
That ExtendScript Toolkit will not run on macOS 10.15 Catalina or above, My Mac OS version is 12.2.1.
Most people currently use the VSCode ExtendScript Debugger plugin.

**Comment by SheetJSDev** [comment]
It may be expecting a UTF8 BOM, can you try adding it in?  In the shell:

```bash
cat <(printf '\xEF\xBB\xBF') node_modules/xlsx/dist/xlsx.extendscript.js > xlsx.extendscript.js
```

This will create a new file that you can import.

**Comment by jlzyyds** [comment]
Thanks for your reply.
The number of error lines changed after UTF8 BOM was added.
![1648406825261](https://user-images.githubusercontent.com/99283952/160296047-63c8dd73-1945-4b6f-a4f5-84db5cb3d86f.jpg)

**Comment by SheetJSDev** [comment]
ESBuild bug https://github.com/evanw/esbuild/issues/2136 , in the meanwhile we'll refactor that line

**Comment by SheetJSDev** [comment]
@jlzyyds unfortunately esbuild is not going to fix the bug, so the line was reworked and the updated build appears to work correctly back to ESTK 3.5.  Please test against https://raw.githubusercontent.com/SheetJS/sheetjs/master/dist/xlsx.extendscript.js .  Download with curl:

```bash
curl -LO https://raw.githubusercontent.com/SheetJS/sheetjs/master/dist/xlsx.extendscript.js
```

**Comment by jlzyyds** [comment]
@SheetJSDev appreciate your help!
it works fine now.

Thank you very much.
