### ISSUE TITLE
CSV to XLSX?

### ISSUE THREAD

**Issue by wsdt** [SheetJS/sheetjs#2631]
Any chance to convert a valid CSV with ';' to XLSX?

**Comment by reviewher** [comment]
If you are asking about `;` as a delimiter, it is automatically detected: https://github.com/SheetJS/sheetjs/blob/master/bits/40_harb.js#L846-L884 

For known CSV files that happen to have semicolons, either wrap them in quotes or pass `FS: ","` to read.  The `sep=","` pragma also works

**Comment by wsdt** [comment]
No it was rather a general question, haven't found documentation nor a method matching to the enquiry in the interface on how to convert a csv-string to a Excel spreadsheet.

**Comment by reviewher** [comment]
ezpz:

```js
var wb = XLSX.read(csv_string, { type: "string" });
XLSX.writeFile(wb, "csv.xlsx");
```

**Comment by wsdt** [comment]
Great thank you! But we want to return the Spreadsheet from an API, but I think I saw a type property somewhere with Binary etc.

**Comment by reviewher** [comment]
```js
var bstr = XLSX.write(wb, { bookType: "xlsx", type: "binary" }); // binary string
```

https://github.com/SheetJS/sheetjs#output-type it can also make `Buffer` in NodeJS or `Uint8Array`

**Comment by wsdt** [comment]
thx!
