### ISSUE TITLE
How to set cell as text type?

### ISSUE THREAD

**Issue by 905868332** [SheetJS/sheetjs#2633]
In order to prevent DDE attack, how to set cell as text type?
![image](https://user-images.githubusercontent.com/29794128/160581488-0f3718ee-30e2-40d3-a41c-1a4a7dfab5c5.png)
![image](https://user-images.githubusercontent.com/29794128/160581489-2688b90f-70c6-44bb-96bf-3d7802ee68eb.png)

**Comment by Juanryhn** [comment]
I have same problem

**Comment by Juanryhn** [comment]
but in my case I can't write percent like 2% it comes to 0,02. I dont know what is wrong with this

**Comment by SheetJSDev** [comment]
@905868332 need more detail (what export format? how are you reading data?).

@Juanryhn 2% is the cell `{ t: "n", v: 0.02, z: "0%" }`.  If you are generating programmatically you can set the cell number format.

**Comment by Juanryhn** [comment]
I solve it with option table_to_sheet `raw = true`

`const ws = XLSX.utils.table_to_sheet(document.getElementById('tableBMForExcel'), { raw: true });`

**Comment by SheetJSDev** [comment]
Import: For most formats, there is a distinct representation for string values.  The string `=1+2` can be distinguished from the formula `=1+2`.  For CSV, by default `=1+2` is stored as a numeric cell with a formula (`{ t: "n", f: "1+2" }`).  Passing the option `raw: true` treats all values as text:

```js
> XLSX.read("=1+2,=3+4", {type: "string"}).Sheets.Sheet1
{
  A1: { t: 'n', f: '1+2' },
  B1: { t: 'n', f: '3+4' },
  '!ref': 'A1:B1'
}
> XLSX.read("=1+2,=3+4", {type: "string", raw: true}).Sheets.Sheet1
{
  A1: { t: 's', v: '=1+2' },
  B1: { t: 's', v: '=3+4' },
  '!ref': 'A1:B1'
}

```

Export: For most formats, passing a literal string value will generate text (e.g. `{ t: "s", v: "=1+2" }` will be preserved)  For CSV, the behavior is identical to Excel by default (both the formula `=1+2` and the text `=1+2` will be mapped to the value `=1+2`).  Passing the option `forceQuotes: true` to `sheet_to_csv` will force quotes around each value:

```js
> var ws = XLSX.read("=1+2,=3+4", {type: "string", raw: true}).Sheets.Sheet1
> XLSX.utils.sheet_to_csv(ws)
'=1+2,=3+4'
> XLSX.utils.sheet_to_csv(ws, {forceQuotes: true})
'"=1+2","=3+4"'
```
