### ISSUE TITLE
How to use the style/theme properties

### ISSUE THREAD

**Issue by Figumari** [SheetJS/sheetjs#2637]
I'm trying to set some cells font in a worksheet as bold or in a different color. However, I couldn't find something regarding this in the documentation. Can someone help me please?

```js
XLSX.utils.sheet_add_json(
  skWS,
  [
    {
      dateTimeNow: {
        t: "d",
        v: this.getDateTimeNow(),
        z: "dd.mm.yyyy hh:mm:ss",
      },
    },
  ],
  {
    origin: "AD2",
    skipHeader: true,
  }
);
```

What should I do with the style/theme property:

```js
XLSX.utils.sheet_add_json(
  skWS,
  [
    {
      dateTimeNow: {
        t: "d",
        v: this.getDateTimeNow(),
        z: "dd.mm.yyyy hh:mm:ss",
        s: "STYLE/THEME"
      },
    },
  ],
  {
    origin: "AD2",
    skipHeader: true,
  }
);
```

**Comment by SheetJSDev** [comment]
The main focus of this project is data preservation.  We currently offer styling support as part of our [Pro offering](https://sheetjs.com/pro) and eventually hope to address it here after the 1.0.0 release
