### ISSUE TITLE
Already defined formula on a column of sheet not working

### ISSUE THREAD

**Issue by abhi31AI** [SheetJS/sheetjs#2642]
Already defined formula on a column of sheet not working on the change of the respective dependency.

I have a sheet in which whenever value changes in one of the columns, that should reflect in the column of another sheet where the formula of that computation is there which does this.

But, it's not happening using the xlsx package. Any solutions?

**Comment by SheetJSDev** [comment]
If you are asking about reading and exporting formulae, the file-format support is described in https://github.com/SheetJS/sheetjs#formulae -- you should be able to read and write in a number of formats.  If you can share an example, we can take a closer look.

If you are asking about updating the workbook after changing a value (based on the formula structure), this is something we currently consider "out of scope" for this file library.  We offer [a paid component for refreshing workbooks and performing calculations](https://sheetjs.com/pro)
