### ISSUE TITLE
Cell style problem

### ISSUE THREAD

**Issue by netollie** [SheetJS/sheetjs#2645]
Hi,
I am using SheetJs and trying to rewrite xlsx files but it can't export cell styles(color, border, etc...).
The following code is the usage to extract data from spreadsheet bytes:
```javascript
var workbook = XLSX.read(data, {
  type: binary,
  cellStyles: true
});
console.log(workbook["Sheet1"]["A1"].s);
//{
//  ...
//  fgColor: {
//    rgb: "FFFFFF00"
//  }
//}
```
There is the official document: cell styles are specified by a style object that roughly parallels the OpenXML structure. The style object has five top-level attributes: `fill`,  `font`, `numFmt`, `alignment`, `border` 
So this structure may be correct:
```javascript
{
  ...
  border: {
    ... 
  },
  fill: {
    ...
    fgColor: {
      rgb: "FFFFFF00"
    }
  }
}
```

**Comment by SheetJSDev** [comment]
You are probably thinking of one of the forks like https://github.com/protobi/js-xlsx/

The main focus of this project is data preservation.  We currently offer styling support as part of our [Pro offering](https://sheetjs.com/pro) and eventually hope to address it here after the 1.0.0 release
