### ISSUE TITLE
Read Range of Rows from sheet

### ISSUE THREAD

**Issue by shaileshkachhara89** [SheetJS/sheetjs#2646]
I want to read rows from 5 to 50 from excel.
is that possible?

**Comment by reviewher** [comment]
`sheetRows: 50`

**Comment by shaileshkachhara89** [comment]
No it will start from 1st rows, I want rows from 5 to 50.

**Comment by shaileshkachhara89** [comment]
I didn't need first 4 rows.

**Comment by aalimovs** [comment]
@reviewher found this thread via search. Same question as @shaileshkachhara89, dow do you skip e.g. first 3 rows?

I have a spreadsheet where data with headers start with row 4, before that it's unstructured data that I want to skip.

![image](https://user-images.githubusercontent.com/6516539/183139746-10be2211-b75d-4deb-aee0-f0d63b69820f.png)

**Comment by SheetJSDev** [comment]
When there are header rows in the data, it is preferable to make the specific utility functions skip rows.  For example, if you are using `sheet_to_json`, pass the [`range` option](https://docs.sheetjs.com/docs/api/utilities#array-output):

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
range.s.r = 4; // start on SheetJS Row 4 = Excel Row 5
var aoo = XLSX.utils.sheet_to_json(ws, { range: XLSX.utils.encode_range(range) });
```
