### ISSUE TITLE
json_to_sheet slow and very large after download

### ISSUE THREAD

**Issue by anandmuthu1978** [SheetJS/sheetjs#2647]
Hello

I tried using json_to_sheet to convert to a workbook. The volume is 100k records with 100 columns ( this fails with out of memory and freezes ). With data 100k with 50 columns I am able to proceed. However the size of the file is huge about 200MB. When I copy this data to another excel - same set of data I get about 21MB. I dont see any difference in data and the formatting looks the same.  I think this is contributing to the large memory consumption. All the JSON data are in string format.

Currently i am splitting the json array to smaller chunks to process but it hits a limit and the chrome tab freezes. Memory heap usage shows nearly 1gb for 80K records with 100 columns. At this point, the tab freezes. 

The setting already includes dense, raw as suggested on a previous issue raised but didnt solve the problem.

Any ideas or hints ?

Hope you can help. 

Thanks in advance.
Anand Muthu

**Comment by reviewher** [comment]
`compression: true` forces DEFLATE compression smaller file size

#77 please leave a comment with the number of rows and columns when the tab freeze
