### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by adnan-sahin** [SheetJS/sheetjs#2650]
Hi,
I installed xlsx package in vue 3.
Is this package is supported in vue 3?
When I tried to use it, I got error. You can see below.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/6214217/162400735-6809ee7d-2dba-4fc7-9123-c602a30767b2.png">

**Comment by SheetJSDev** [comment]
Change the import to `import * as XLSX from "xlsx"`.  You can also used destructured imports like `import { utils, writeFileXLSX } from "xlsx"`

**Comment by adnan-sahin** [comment]
Thank you so much. It works :)
