### ISSUE TITLE
Is it possible to export an Excel with data and charts/graphs in the same worksheet?

### ISSUE THREAD

**Issue by cmgchess** [SheetJS/sheetjs#2651]
would something like this be possible with SheetJS
A mix of text and charts in the same worksheet

![image](https://user-images.githubusercontent.com/61736812/162588978-da8475a5-ecd9-4880-80cf-b2819f2f859c.png)

**Comment by SheetJSDev** [comment]
The current focus of the open source project is data interchange (importing data from spreadsheet files and exporting files that can be used in other spreadsheet applications).  For the moment, we do offer this as part of our [Pro offering](https://sheetjs.com/pro).  We do hope to make it open source, but the timeline is unclear.
