### ISSUE TITLE
By sheet_to_json function I am not able to read 10 lakh records. Any solution for that.

### ISSUE THREAD

**Issue by shaileshkachhara89** [SheetJS/sheetjs#2652]
How to read large excel file and show data in form of table using JavaScript or react.

**Comment by SheetJSDev** [comment]
The current fundamental constraint is the string size, which has varied over the years.  For hundreds of millions of cells we'd need a different approach.  Please leave a comment in https://github.com/SheetJS/sheetjs/issues/61 with a size estimate (number of columns/rows, how many cells are filled)
