### ISSUE TITLE
existing styling is lost

### ISSUE THREAD

**Issue by Elefantor** [SheetJS/sheetjs#2653]
1. read an existing xlsx (XLSX.read) which has one sheet that contains a text with bold text in A1
2. add for value in A2 (XLSX.utils.sheet_add_aoa)
3. write sheet (XLSX.write), download and open -> A1 is no longer bold

Can the styling in A1 be kept?

**Comment by SheetJSDev** [comment]
The current development focus is data correctness (reading and writing actual data).  We do plan on addressing styling at some point after the 1.0.0 release.

In the interim, we offer this as part of our [Pro Basic offering](https://sheetjs.com/pro)
