### ISSUE TITLE
[BUG]Office and wps height inconsistency.

### ISSUE THREAD

**Issue by WumaCoder** [SheetJS/sheetjs#2654]
## screenshot
Office:
![origin_img_v2_997b9ec1-4aac-4f5e-a107-2ce8486f9bag](https://user-images.githubusercontent.com/39021696/163156900-1fdcaa78-e68f-4f11-8221-ed93281ec4e8.png)

WPS:
![origin_img_v2_7626e3db-538b-47aa-adb5-a7b2f7dc4a5g](https://user-images.githubusercontent.com/39021696/163156945-17affb8a-0a6f-4ee0-9689-a32620acdd77.png)

## Code

```js
sheet.addImage(img, {
                      tl: {
                        col: col + 0.02,
                        row: row + 1.02,
                      } as any,
                      ext: {
                        width: 100,
                        height: rowHeight + 20,
                      },
                      editAs: 'oneCell',
                    });
```

**Comment by SheetJSDev** [comment]
You probably meant to raise the issue elsewhere (not this repo), but it wouldn't be surprising if WPS had a different internal PPI from Excel.
