### ISSUE TITLE
[BUG] Newly created sheet is not visible when opening workbook

### ISSUE THREAD

**Issue by hungdao-testing** [SheetJS/sheetjs#2655]
Precondition:
- Local disk has an excel file with a few of sheets.

Expected result:
-  when I open the excel file by LibreOffice, the existing sheet called "SheetJS" updates new data

Actual result:
 I don't see the sheet "SheetJS" update new data although there is no error when running

Steps:

```ts
export function updateExcelWith(json: any) {
  const workbook = xlsx.readFile(pathFile);
  const mySheet = workbook.Sheets["SheetJS"];
  
  xlsx.utils.book_append_sheet(workbook, mySheet)


}
```

**Comment by SheetJSDev** [comment]
LibreOffice bug https://bugs.documentfoundation.org/show_bug.cgi?id=144819
