### ISSUE TITLE
xtos throws TypeError when first rows have no columns

### ISSUE THREAD

**Issue by M15terHyde** [SheetJS/sheetjs#2656]
In file sheetjs/demos/xspreadsheet/xlsxspread.js function xtos line 137 will throw an error on minCoord.r when the spreadsheet passed in has the first couple rows empty (no columns) and below these empty rows has real data.
This is caused by xtos line 81 setting minCoord and maxCoord so their initial value is undefined then line 82 runs a forEach loop on all the columns in that row. The values of minCoord and maxCoord should be set in the forEach loop. However, if there are no columns in that row minCoord and maxCoord's values are never set and so calling minCoord.r on line 137 fails and produces an error.

**Comment by SheetJSDev** [comment]
This can be simplified by anchoring the starting point to A1.  If it works please feel free to send a PR

```diff
@@ -74,28 +74,18 @@ function xtos(sdata) {
   sdata.forEach(function (xws) {
     var ws = {};
     var rowobj = xws.rows;
+    var minCoord = { r: 0, c: 0 }, maxCoord = { r: 0, c: 0 };
     for (var ri = 0; ri < rowobj.len; ++ri) {
       var row = rowobj[ri];
       if (!row) continue;
 
-      var minCoord, maxCoord;
       Object.keys(row.cells).forEach(function (k) {
         var idx = +k;
         if (isNaN(idx)) return;
 
         var lastRef = XLSX.utils.encode_cell({ r: ri, c: idx });
-        if (minCoord == null) {
-          minCoord = { r: ri, c: idx };
-        } else {
-          if (ri < minCoord.r) minCoord.r = ri;
-          if (idx < minCoord.c) minCoord.c = idx;
-        }
-        if (maxCoord == undefined) {
-          maxCoord = { r: ri, c: idx };
-        } else {
-          if (ri > maxCoord.r) maxCoord.r = ri;
-          if (idx > maxCoord.c) maxCoord.c = idx;
-        }
+        if (ri > maxCoord.r) maxCoord.r = ri;
+        if (idx > maxCoord.c) maxCoord.c = idx;
 
         var cellText = row.cells[k].text, type = "s";
         if (!cellText) {
@@ -127,12 +117,11 @@ function xtos(sdata) {
           });
         }
       });
-
-      ws["!ref"] = XLSX.utils.encode_range({
-        s: { r: minCoord.r, c: minCoord.c },
-        e: { r: maxCoord.r, c: maxCoord.c }
-      });
     }
+    ws["!ref"] = minCoord ? XLSX.utils.encode_range({
+      s: minCoord,
+      e: maxCoord
+    }) : "A1";
 
     XLSX.utils.book_append_sheet(out, ws, xws.name);
   });
```

**Comment by M15terHyde** [comment]
This is approximately what I did to fix it on my local machine but I can't submit a PR because of my employer's policy on outside work. I would have to get it approved first.

**Comment by SheetJSDev** [comment]
Updated the public demo https://oss.sheetjs.com/sheetjs/x-spreadsheet.html
