### ISSUE TITLE
No hidden attribute in row properties

### ISSUE THREAD

**Issue by dkostochko** [SheetJS/sheetjs#2658]
Hi!

I tried parse xslx file and got incorrect row properties. There is no attribute "hidden" for hidden rows.

Environment:
sheetjs ver. 0.18.5
xslx file created in LibreOffice with hidden rows (file: https://disk.yandex.by/d/nNDGAN25xFjVCw)

Actual result:
`sheet['!rows'] =>
[
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 42.5, "hpx": 42.5, "level": 0 },
  { "hpt": 40.25, "hpx": 40.25, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  null,
  null,
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 }
] `

Actual result:
`sheet['!rows'] =>
[
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 42.5, "hpx": 42.5, "level": 0 },
  { "hpt": 40.25, "hpx": 40.25, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  null,
  null,
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0 },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0, hidden: true },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0, hidden: true },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0, hidden: true },
  { "hpt": 12.8, "hpx": 12.800000000000002, "level": 0, hidden: true }
] `

I did small investigation and found that
for columns value of attribute "hidden" is parsed via function `parsexmlbool` 
`if(coll.hidden) coll.hidden = parsexmlbool(coll.hidden);` 
but for rows value isn't parsed, only compared with string "1"
`if(tag.hidden == "1") { rowrite = true; rowobj.hidden = true; }` 
LibreOffice produces xslx with value "true" for row attribute "hidden" instead "1".

**Comment by SheetJSDev** [comment]
Good catch!  We'd accept a PR that replaces those "1" or "true" checks with a call to `parsexmlbool`.
