### ISSUE TITLE
Cannot open exported xlsx file containing Special character

### ISSUE THREAD

**Issue by kachaj7** [SheetJS/sheetjs#2660]
Hi,

wenn value of a cell contains \uffff  I get the error mentioned in title.

The special char means invalid character https://charbase.com/ffff-unicode-invalid-character

**Comment by reviewher** [comment]
FWIW "\uFFFF" may not be valid in Excel:

<img width="339" alt="issue2660" src="https://user-images.githubusercontent.com/24845478/164774236-07c295e9-6347-4256-943f-e7e45de9bec3.png">

**Comment by kachaj7** [comment]
I saved the value in Excel 2007 (yes, I know, is old), then I can reopen the file (probably is encoded).
When I save the value in LibreOffice, save as xlsx and open with Excel, I get the exception like in tittle.

So question is, should such character be catched inside Sheetjs and throw an exception?

**Comment by SheetJSDev** [comment]
Thanks for reporting!  Small test https://jsfiddle.net/c9xkpL86/ appears to elicit the error in XLSX:

```js
var ws = XLSX.utils.aoa_to_sheet([["\uffff"]]);
var wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue2660.xlsb");
XLSX.writeFile(wb, "issue2660.xls");
XLSX.writeFile(wb, "issue2660.xlsx");
```

https://github.com/SheetJS/sheetjs/blob/master/bits/22_xmlutils.js#L63 `charegex` needs to be updated to reflect the spec: https://www.w3.org/TR/REC-xml/#charsets

Valid XML 1.0 characters include

```
#x9 \| #xA \| #xD \| [#x20-#xD7FF] \| [#xE000-#xFFFD] \| [#x10000-#x10FFFF]
```

Changing the RegExp to `/[\u0000-\u0008\u000b-\u001f\uFFFE-\uFFFF]/g` would fix the immediate issue -- feel free to send a PR.  It should eventually also check for the unpaired surrogate case like `(String.fromCodePoint(55296) + String.fromCodePoint(0x1f363) + "abc")`

**Comment by SheetJSDev** [comment]
Testing against HEAD in NodeJS:

```js
var XLSX = require("./");
var ws = XLSX.utils.aoa_to_sheet([["\uffff"]]);
var wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
XLSX.writeFile(wb, "issue2660.xlsx");
```

Generated file looks correct: [issue2660.xlsx](https://github.com/SheetJS/sheetjs/files/8553338/issue2660.xlsx)

**Comment by SheetJSDev** [comment]
@kachaj7 in trying to reproduce the issue, we came across a few issues in LO unicode handling.  https://bugs.documentfoundation.org/show_bug.cgi?id=148812 (reproduction with UNICODE led to a bad defined name).  How were you testing the files in LibreOffice?  They probably would appreciate a bug report :)
