### ISSUE TITLE
Option to change styles of gridlines based on frozen cell?

### ISSUE THREAD

**Issue by aailyin** [SheetJS/sheetjs#2661]
Hey there,
Is it possible to change the style of borders that are added if I configure `!freeze` ref, for example, `worksheet['!freeze'] = 'B2'`? All my borders are black, but two lines (top of row 2 and right of column 1) are gray after adding this frozen cell. It looks bad.
I use SheetJS Pro, no info in README. Thanks for any help!

**Comment by SheetJSDev** [comment]
Please send an email to pro@sheetjs.com with a screenshot
