### ISSUE TITLE
Editar estilo em um texto dentro de uma célula

### ISSUE THREAD

**Issue by thalesantana** [SheetJS/sheetjs#2664]
How I can style just one word in a cell?(it's possible?) like that: 
![image](https://user-images.githubusercontent.com/72896088/165185996-4c03b09f-d2f3-4c7e-bd3f-90b9168838ed.png)

when I apply style it gives in entire cell.
 ws[reference].s.font = {
      strike: true
};
![image](https://user-images.githubusercontent.com/72896088/165186341-3c8bd7e5-eba3-4c12-8220-4e05f0b0243a.png)

**Comment by SheetJSDev** [comment]
This is a feature of our [Pro offering](https://sheetjs.com/pro)
