### ISSUE TITLE
uglify error

### ISSUE THREAD

**Issue by HineShen** [SheetJS/sheetjs#2665]
v1.8.0+ xlsx.mjs里包含es6语法，导致在忽略node_module编译的项目中会压缩报错，请问有什么解决方案么

**Comment by SheetJSDev** [comment]
Can you share a sample project?

If you are upgrading, change

```js
import XLSX from 'xlsx';
```

to

```js
import * as XLSX from 'xlsx';
```

If you want to use the standalone browser script, you can import `xlsx/dist/xlsx.full.min.js` directly

**Comment by HineShen** [comment]
> Can you share a sample project?
> 
> If you are upgrading, change
> 
> ```js
> import XLSX from 'xlsx';
> ```
> 
> to
> 
> ```js
> import * as XLSX from 'xlsx';
> ```
> 
> If you want to use the standalone browser script, you can import `xlsx/dist/xlsx.full.min.js` directly

![image](https://user-images.githubusercontent.com/22253605/165251276-dd7f04b0-8f6d-42ff-8c22-7286343a7777.png)
按照上述的改动，打包完成之后还是这样的

**Comment by SheetJSDev** [comment]
Try importing the script directly:

```js
import * as XLSX from 'xlsx/dist/xlsx.full.min.js';
```
