### ISSUE TITLE
How to add a blank row in the table?

### ISSUE THREAD

**Issue by dotrungit** [SheetJS/sheetjs#2668]
I render a table with data of the form:
`[{ name: 'foo' , age: 12}, { name: 'bar' , age: 15}]`

How to add two blank row in start of the table?
like this
![image](https://user-images.githubusercontent.com/35027476/165685206-b156835a-012b-4864-960b-9a6022f2de33.png)

**Comment by SheetJSDev** [comment]
Pass the `origin` option to `json_to_sheet`:

```js
const data = [{ name: 'foo' , age: 12}, { name: 'bar' , age: 15}];
const wb = XLSX.utils.json_to_sheet(data, { origin: 2 }); // start in cell A3
const wb = XLSX.utils.json_to_sheet(data, { origin: 2, header: ["name", "age"] }); // start in cell A3 and enforce header order
```
