### ISSUE TITLE
[Question] Can `sheet_to_json` output link target ?

### ISSUE THREAD

**Issue by ajboni** [SheetJS/sheetjs#2671]
My excel files have formatted hyperlinks cell. I want the value to be the target but instead I get the title of the formatted link. Im using default `sheet_to_json` (raw = true)

**Comment by SheetJSDev** [comment]
Not currently.  Please drop a comment in https://github.com/SheetJS/sheetjs/issues/1370 explaining how you would handle cells without links (that issue is about exporting formulae but it's all under the category of "exporting other data in `sheet_to_json`)

**Comment by ajboni** [comment]
Thanks! Without knowing the internals, If we identify a cell as a link, shouldn't we be exporting the actual 'value' (url) instead of the 'label' (title)?. In both cases they are just strings... right? 
Unless we don't really know the cell 'type' when exporting...
