### ISSUE TITLE
File name with special characters

### ISSUE THREAD

**Issue by rafbgarcia** [SheetJS/sheetjs#2672]
I'm trying to write a filename with a date format `format("MM/DD HH:MMa")` but the generated file name is `05_02 11 05am`.

Notice the `/` and `:` are getting replaced/removed.

Is it not possible to save a file with these characters?

Thanks

**Comment by SheetJSDev** [comment]
Out of our control: https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-download

> The attribute may have a value; the value, if any, specifies the default filename that the author recommends for use in labeling the resource in a local file system. There are no restrictions on allowed values, but authors are cautioned that **most file systems have limitations with regard to what punctuation is supported in filenames, and user agents are likely to adjust filenames accordingly.**

It wouldn't be surprising if browsers sanitize both `/` and `:` since both are related to folder separators: `/` is typical on UNIX systems while `:` was used in pre-BSD macOS
