### ISSUE TITLE
XLSX.utils.table_to_sheet 导出时间有问题

### ISSUE THREAD

**Issue by xaozhi** [SheetJS/sheetjs#2675]
导出时间相差43,秒

**Comment by SheetJSDev** [comment]
Same as https://github.com/SheetJS/sheetjs/issues/2644 -- please leave a comment in that issue with your current timezone:

```js
console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)
```

**Comment by ruitalia** [comment]
Atlantic/Azores

**Comment by SheetJSDev** [comment]
Please leave comments in issue #2644
