### ISSUE TITLE
xlsx.mini

### ISSUE THREAD

**Issue by nathanBrenner** [SheetJS/sheetjs#2678]
Version 0.17.5 had an xlsx.mini so you could import into a react component like
```
import {
  type ParsingOptions,
  type CellObject as Cell,
  type WorkSheet,
  type CellAddress,
  type WorkBook,
  read,
  utils,
} from 'xlsx/xlsx.mini';
```

What happened to that stuff from version 0.18.x?

**Comment by SheetJSDev** [comment]
The mini files were created to work around a code size problem (a large part of the full script size is the codepage dependency).  The standalone script still lives in `dist/xlsx.mini.min.js`

In the 0.18.x series, the library officially enabled the ESM build (`module` field in package.json points to the file).  This approach obviates the `xlsx.mini.js` file and simplifies the resolution.

You should be able to replace the import with:

```js
import {
  type ParsingOptions,
  type CellObject as Cell,
  type WorkSheet,
  type CellAddress,
  type WorkBook,
  read,
  utils,
} from 'xlsx';
```

.

The equivalent of the "mini" standalone build is now

```js
import * as XLSX from 'xlsx'
```

and the equivalent of the "full" standalone build is now

```js
import * as XLSX from 'xlsx';
import * as cptable from 'xlsx/dist/cpexcel.full.mjs';
XLSX.set_cptable(cptable);
```
