### ISSUE TITLE
formula entering in wrong cell

### ISSUE THREAD

**Issue by nikhilatkan** [SheetJS/sheetjs#2680]
I was trying to add formula SUM(G2:H2) which will result to I2, but the result goes to I3 and the header column is automatically becoming "8".

Before
<img width="648" alt="previousTable" src="https://user-images.githubusercontent.com/61219392/167901513-2f50f68f-b0bb-477d-bbed-0b845d977a00.PNG">

let worksheets = {};
for (const sheetName of workbook.SheetNames) {
  worksheets[sheetName] = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]);
}

XLSX.utils.sheet_set_array_formula(worksheets.Sheet1, "I2", "SUM(G2:H2)", 1);

After the formula
<img width="524" alt="afterSum" src="https://user-images.githubusercontent.com/61219392/167901426-aea17a45-66f1-46f2-9b4a-839c4d7b8f59.PNG">

**Comment by nikhilatkan** [comment]
But with formula XLSX.utils.sheet_set_array_formula(worksheets.Sheet1, "I2", "SUM(G2:H2)");
It is giving same output by displaying the result at I3 only.

**Comment by nikhilatkan** [comment]
The file was created manually.
attaching the file.
[file-example.xlsx](https://github.com/SheetJS/sheetjs/files/8672194/file-example.xlsx)

**Comment by SheetJSDev** [comment]
still can't reproduce: https://jsfiddle.net/v258e9kd/

The `b64` string is the base64-encoding of the attachment.

```js
var wb = XLSX.read(b64, {type:"base64"});
var ws = wb.Sheets[wb.SheetNames[0]];
XLSX.utils.sheet_set_array_formula(ws, "I2", "SUM(G2:H2)");
XLSX.utils.sheet_set_array_formula(ws, "I5", "SUM(G2:H2)", 1);

var range = XLSX.utils.decode_range(ws["!ref"]);
range.e.c = 8; // include "I"
ws["!ref"] = XLSX.utils.encode_range(range);

XLSX.writeFile(wb, "issue2680.xlsx");
```

<img width="600" alt="issue2680" src="https://user-images.githubusercontent.com/6070939/167911975-03c1f3d0-6a58-44ec-b080-b90b3d709d50.png">

Please confirm you are using the latest version (0.18.7) with

```js
console.log(XLSX.version)
```

If not, you can get the latest version from https://cdn.sheetjs.com/

**Comment by nikhilatkan** [comment]
@SheetJSDev 
How is b64 calculated in this.

**Comment by SheetJSDev** [comment]
The file has the following md5 sum:

```js
$ md5 file-example.xlsx 
MD5 (file-example.xlsx) = 813d290f75b093ef768a83a87d416ff5
```

The b64 string was taken using macos `base64` tool:

```
$ base64 file-example.xlsx
```

You should be able to generate it in Windows XP / 7 / 10 using `certutil`:

```powershell
> certutil -encode file-example.xlsx file-example.b64
```

**Comment by nikhilatkan** [comment]
@SheetJSDev Thanks, My problem is solved.

**Comment by SheetJSDev** [comment]
Yes it's doable, there are a number of approaches in https://docs.sheetjs.com/docs/solutions/input
