### ISSUE TITLE
CreatedDate and Excel 2016

### ISSUE THREAD

**Issue by nbaroiller** [SheetJS/sheetjs#2681]
I encounter an issue in Excel 2016 which regularly throws a warning saying something in the lines of "We found a problem with some content in..".

This warning shows up only when I set the `CreatedDate` prop. I know that a similar issue has already been adressed (https://github.com/SheetJS/sheetjs/issues/2189) but I am already using `new Date()` as suggested by @SheetJSDev.

I took a look at the core.xml file before and after file recovery, and noticed that the ISO string was only 20 characters long after Excel recovered the file, while `new Date()` generates a 24 characters long date. Constraining it to 20 characters with `new Date().toISOString().split('.')[0]+"Z"` did not change anything though.

The only notable difference before and after file recovery is the `xsi:type` attribute :

``` xml
<dcterms:created>2022-05-12T10:21:49Z</dcterms:created>
```

gets corrected to :

```xml
<dcterms:created xsi:type="dcterms:W3CDTF">2022-05-12T10:21:49Z</dcterms:created>
```

I'm quite at a loss here and don't really know what to do to get rid of this warning (except, of course, not providing the creation date, but I need it).

**Comment by SheetJSDev** [comment]
Does the generated file from https://jsfiddle.net/jot943mz/ work?

**Comment by SheetJSDev** [comment]
Writing the `xsi:type` attribute has always been a part of the write logic.  It was introduced more than 8 years ago (d15b81e0e9ee61ed720d16f4e25b34d951275ff4).  The file from the fiddle also has the attribute.

In our local testing, the generated file from from the fiddle in the older issue works in Excel 2007 / 2010 / 2013 / 2016 / 2019 for Windows and 2011 / 2016 for Mac.

The Excel 2016 Windows version is 16.0.11001.20097 (32 bits).

It's entirely possible a patch update to Excel 2016 broke backwards compatibility.  If you can share both the incorrect file and the repaired file that does work, we can investigate further.
