### ISSUE TITLE
UI gets stuck when parsing an XLSX File(~28MB)

### ISSUE THREAD

**Issue by RiteshBM** [SheetJS/sheetjs#2684]
I'm using this piece of code to parse an Excel File (XLXS)(~28MB)
```
        const fileReader = new FileReader();
        
        fileReader.readAsBinaryString(file);
        

        fileReader.onerror = (error) => {
            reject(error)
        };
    
        fileReader.onload = (e) => {      
            const bufferedArray = e.target.result;  
            
            const wb = XLSX.read(bufferedArray, { type: 'buffer' });
            const parsedCsvFilesPromises = convertToCsv(wb)
        }
```

The issue is that it blocks the entire UI, this piece of code is triggered inside `React.useEffect`.
I'm using React 17.
XLSX.read blocks for about ~10s

**Comment by SheetJSDev** [comment]
To prevent browser lockup (see https://sheet.js.org/ for an example) you should push the work into a Web Worker.

**Comment by RiteshBM** [comment]
Is there some sample to show how to do this?

**Comment by SheetJSDev** [comment]
Check [the "Web Workers" demo in the docs](https://docs.sheetjs.com/docs/demos/worker/)
