### ISSUE TITLE
Microsoft Excel 97-2003 Version Turkish UTF-8 Problem

### ISSUE THREAD

**Issue by miktatty** [SheetJS/sheetjs#2686]
Hi, i need help for UTF-8 encoding, when i try "Microsoft Excel 97-2003 Version" its error but if i change it in excel and save its working. what the problem? i need read "Microsoft Excel 97-2003 Version"

so i need this:
<img src="https://resmim.net/cdn/2022/05/17/kXPmD.jpg">

but sheetjs reading this:
<img src="https://resmim.net/cdn/2022/05/17/kXnYI.jpg">

file is: [http://easyupload.io/cq5kys](http://easyupload.io/cq5kys)

**Comment by miktatty** [comment]
i use codepage etc. but sheetjs reading  when i change type in excel but i need read directly this file.

**Comment by SheetJSDev** [comment]
The download site is not working.

GitHub directly supports XLS uploads.  You can drag and drop the file into the reply box.

**Comment by miktatty** [comment]
[İdeal kondİsyon.xls](https://github.com/SheetJS/sheetjs/files/8725075/Ideal.kondIsyon.xls)

**Comment by miktatty** [comment]
> The download site is not working.
> 
> GitHub directly supports XLS uploads. You can drag and drop the file into the reply box.

[İdeal kondİsyon.xls](https://github.com/SheetJS/sheetjs/files/8727437/deal.kondIsyon.xls)

**Comment by SheetJSDev** [comment]
Can you check if the same issue shows up in the web demo https://oss.sheetjs.com/ ?

Excel 2019:

<img width="268" alt="issue2686xl" src="https://user-images.githubusercontent.com/6070939/169259948-2aeab12a-6156-4fad-a35e-9b48aaf331b4.png">

https://oss.sheetjs.com (use the file input element to select the file):

<img width="553" alt="issue2686s5s" src="https://user-images.githubusercontent.com/6070939/169260050-812c9bab-5f12-4c0b-af77-32e1cfbdf60e.png">

**Comment by miktatty** [comment]
> Can you check if the same issue shows up in the web demo https://oss.sheetjs.com/ ?
> 
> Excel 2019:
> 
> <img alt="issue2686xl" width="268" src="https://user-images.githubusercontent.com/6070939/169259948-2aeab12a-6156-4fad-a35e-9b48aaf331b4.png">
> 
> https://oss.sheetjs.com (use the file input element to select the file):
> 
> <img alt="issue2686s5s" width="553" src="https://user-images.githubusercontent.com/6070939/169260050-812c9bab-5f12-4c0b-af77-32e1cfbdf60e.png">

its working with both Excel 2016 and oss but my project not same... could you send JavaScript code for this?

**Comment by SheetJSDev** [comment]
Simple HTML table: (change the variable `URL` to the name of the file and place it in the same folder as the HTML file)

```html
<body>
<script src="https://cdn.sheetjs.com/xlsx-0.18.7/package/dist/xlsx.full.min.js"></script>
<script>
(async() => {
	const URL = "deal.kondIsyon.xls";
	const ab = await (await fetch(URL)).arrayBuffer();
	const wb = XLSX.read(ab);
	const ws = wb.Sheets[wb.SheetNames[0]];
	document.write(XLSX.utils.sheet_to_html(ws));
})();
</script>
</body>
```

**Comment by miktatty** [comment]
> Simple HTML table: (change the variable `URL` to the name of the file and place it in the same folder as the HTML file)
> 
> ```
> <body>
> <script src="https://cdn.sheetjs.com/xlsx-0.18.7/package/dist/xlsx.full.min.js"></script>
> <script>
> (async() => {
> 	const URL = "deal.kondIsyon.xls";
> 	const ab = await (await fetch(URL)).arrayBuffer();
> 	const wb = XLSX.read(ab);
> 	const ws = wb.Sheets[wb.SheetNames[0]];
> 	document.write(XLSX.utils.sheet_to_html(ws));
> })();
> </script>
> </body>
> ```
I need react code my codes written react, and here:

            reader.onload = (e) => {
                const data = e.target.result;
                const workbook = xlsx.read(data, { type: "array" });
                const sheetName = workbook.SheetNames[0];
                const worksheet = workbook.Sheets[sheetName];
                const json = xlsx.utils.sheet_to_json(worksheet);
                console.log("🚀 ~ file: ExamObservation.js ~ line 50 ~ ExamObservation ~ json", json)
                setResultList(json);
            };
            reader.readAsArrayBuffer(excelFile);

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/installation/frameworks pay attention to the instructions under "XLS Codepage support".  After the switch to ESM, this step is required to load the codepages

**Comment by miktatty** [comment]
> https://docs.sheetjs.com/docs/installation/frameworks pay attention to the instructions under "XLS Codepage support". After the switch to ESM, this step is required to load the codepages

i understand but i dont know where i write
`set_cptable(cptable);`
could you send code for this example?

**Comment by SheetJSDev** [comment]
Do a clean install first:

```
npm rm xlsx
npm install --save https://cdn.sheetjs.com/xlsx-0.18.7/xlsx-0.18.7.tgz
```

Then look in your code for the import.

Glob import:

```js
import * as xlsx from 'xlsx';
import * as cptable from 'xlsx/dist/cpexcel.full.mjs';
xlsx.set_cptable(cptable);
```

Named import:

```js
import { read, utils, set_cptable } from 'xlsx';
import * as cptable from 'xlsx/dist/cpexcel.full.mjs';
set_cptable(cptable); 
```
