### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Sakura0408** [SheetJS/sheetjs#2692]
![image](https://user-images.githubusercontent.com/42940527/169780592-7e4b0db5-6930-48d5-82a2-76318b879575.png)
![image](https://user-images.githubusercontent.com/42940527/169780654-982d30ba-c53d-4416-ac4b-989d717bcf93.png)
I have a problem with Vue component. How can I fix this?

**Comment by SheetJSDev** [comment]
Can you share the webpack config?  It would be helpful if you could share a sample project with the issue

**Comment by Sakura0408** [comment]
> Can you share the webpack config? It would be helpful if you could share a sample project with the issue

There is a sample project.
https://github.com/Sakura0408/sample-xlsx.git

open localhost:8080, click v-report, vue will render v-report-attr component, at the same time, the console will report an error

**Comment by Sakura0408** [comment]
Notice: Sorry, The above solution is invalid. Here is the correct solution. I will be using Chinese, sorry for my poor English.

出现此问题的原因是项目根目录的.env以及.env.[enviroment]文件导致。
如果你的.env或者.env.[enviroment]文件中有这样一段代码，请删除它。
VUE_CLI_BABEL_TRANSPILE_MODULES = true
它的作用是使Vue的路由懒加载。

然后安装babel-plugin-dynamic-import-node插件，并在babel.config.js文件中进行如下配置即可解决。
`
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  env: {
    // 这里的development是与你的.env.[enviroment]文件名中的enviroment对应的。
    // 比如你的文件名为.env.dev，那么此处的development应该被替换为dev
    development: {
      plugins: ['dynamic-import-node']
    }
  }
}
`
你问我为什么这样做可以解决这个问题？
对不起，我也不知道。我只是轮流删除了一些文件来确定是哪些文件导致的该问题，然后使用搜索引擎解决了。：）

**Comment by Sakura0408** [comment]
Notice:
如果使用了eslint，还需要在.eslintrc.js配置文件中进行如下配置。
`
module.exports = {
  env: {
    amd: true
  }
}
`
