### ISSUE TITLE
Is there a way to filter out data from the excel while reading the file and then converting it to JSON format ?

### ISSUE THREAD

**Issue by HarshitaVishwakarma** [SheetJS/sheetjs#2697]
The excel sheet I am trying to import has a column called "status" which can have the value true/false. I want to import only the rows that have the status true, is there a way to achieve this by filtering out the data while reading the excel and then converting it to JSON?

**Comment by SheetJSDev** [comment]
No, as filtering out rows during parsing has other complex effects on worksheet metadata (it would effectively be the same as deleting rows from the worksheet).  The easier and recommended approach is to filter after using `sheet_to_json`
