### ISSUE TITLE
Jasmine Unit Test fails for writeFile when simply upgrading sheetjs to 0.18.5

### ISSUE THREAD

**Issue by CodeMonkey1959** [SheetJS/sheetjs#2698]
unit test passes on sheetjs 0.17.0

it('should export to excel', fakeAsync(() => {
		// Arrange
		fixture.detectChanges();
		component.dataTableContainer = fixture.debugElement.queryAll(By.css('.data-table-container'))[0];
		spyOn(xlsx.utils, 'table_to_sheet').and.returnValue(<xlsx.WorkSheet>{});
		spyOn(xlsx.utils, 'book_new').and.returnValue(<xlsx.WorkBook>{});
		spyOn(xlsx.utils, 'book_append_sheet').and.callFake(() => { });
		spyOn(xlsx, 'writeFile').and.returnValue(true);  <--- point of failure on 0.18.5
		
		// Act
		component.exportToExcel();
		tick();

		// Assert
		expect(xlsx.utils.table_to_sheet).toHaveBeenCalled();
		expect(xlsx.utils.book_new).toHaveBeenCalled();
		expect(xlsx.utils.book_append_sheet).toHaveBeenCalled();
		expect(xlsx.writeFile).toHaveBeenCalled();
}));

jasmine unit test failure:
Error: <spyOn> : writeFile is not declared writable or has no setter

What changed that writeFile is no longer declared writable or has no setter?

**Comment by SheetJSDev** [comment]
0.17.0 defaulted to the standalone builds.  0.18.5 enables the browser ESM build (`"type": "module"` in package.json) so it might be some ESM-related issue with spying on the glob import.  Comments like https://github.com/jasmine/jasmine/issues/1817#issuecomment-629464909 and https://jasmine.github.io/pages/faq.html#module-spy suggest a structural issue outside of our (and even possibly Jasmine's) control.
