### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression flags (at xlsx.full.min.js:10:10712)

### ISSUE THREAD

**Issue by hyfbeetle** [SheetJS/sheetjs#2700]
used in asp.net page,  maybe encode problem?  .cs and .aspx pages translated to utf-8, still occure. any suggestion, thanks very much.

**Comment by SheetJSDev** [comment]
Verify you have a UTF-8 meta tag in your HEAD:

```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

If so, then check if you see the same error in https://oss.sheetjs.com/ .  If you do, please share your browser info (e.g. Chrome 102) and library version (search for the string `version="0` in `xlsx.full.min.js`) so we can try to reproduce

**Comment by SheetJSDev** [comment]
For ASPX you need

```xml
    <%@ Page RequestEncoding="utf-8" ResponseEncoding="utf-8" %>
```

See https://docs.microsoft.com/en-us/previous-versions/39d1w2xf(v=vs.140) for more info
