### ISSUE TITLE
ability to search in docs

### ISSUE THREAD

**Issue by gentunian** [SheetJS/sheetjs#2701]
The new docs page, sadly, is not that useful as the full HTML old-style page. When used to search for a particular topic, finding it in the old docs was super-fast.

For example, now I went through all sections just to find `decode_range()` reference (and was not that useful as it's only named but no more than that, unless I didn't find the place where it elaborates about it).

It would be nice to have for the docs page as this library is complex and has tons of fetatures.

**Comment by SheetJSDev** [comment]
The docs are a work in progress and feedback is the first step in improvement :)

**Why we reorganized the docs**

We liked the old README.  However it was met with much public and private criticism over the years.  GitHub markdown preview only supports 4 levels of linkable headers and we probably need 6 or 7 for the level of detail involved.  We worked around the problem with lots of details-summary blocks, but those cannot be searched without expanding every block.  That ultimately hid really useful information.

Users have requested a doc structure with more pagination and bookmarks for easy digestion.  They have also requested more "soft documentation" that discusses various use cases and approaches.

The new structure provides sidebar links for easy topic traversal, reduces the need for hiding topics behind detail-summary blocks, draws attention to the parts that are hidden, adds a few "levels", and allows for interactive demos.  

https://docs.sheetjs.com/docs/csf/features/formulae#localization providing an interactive function name translator is not possible with the old README style.  Putting the translator in the docs saves users the struggle of trying to translate function names to the English equivalent

We will look into adding search to the documentation site.

**`decode_range`**

On the matter of `decode_range`, the original docs just mentioned that functions like `encode_range` and `decode_range` exist.  It never actually detailed the function arguments or behaviors.

The old docs used the phrase `decode_range` in 3 places:

- listed in the Utilities (now https://docs.sheetjs.com/docs/interface#utilities )
- mentioned in a details-summary block "Why are random text files valid?" (now https://docs.sheetjs.com/docs/api/parse-options#guessing-file-type)
- in a code sample for creating gap row, hidden in a details-summary block (now https://docs.sheetjs.com/docs/api/utilities#html-table-input)

We will look into describing the basic utility functions in more detail.

**Comment by SheetJSDev** [comment]
Search has been added

https://docs.sheetjs.com/docs/csf/general#a1-utilities more details

**Comment by gentunian** [comment]
I know comments like: "awesome", "thanks", and any other grateful thing should be outside netiquette and use reactions for it. But sometimes it's nice to recognize people work and in this case I think it's nice to say that this was quickly taken and considered. This makes community to be strong. Congratulations.
