### ISSUE TITLE
Generate Live Demo crashes Excel for Mac with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by vgkids** [SheetJS/sheetjs#2703]
Using the **Generate Live Demo** button on the [Complete Example](https://docs.sheetjs.com/docs/example) page downloads a file that crashes Excel for Mac.

**Tested in** 

- Safari 14.1.2
- Firefox 100.0.2 (64-bit)
- Chrome  101.0.4951.54 (Official Build) (x86_64)

**Microsoft Crash Report**
```
Microsoft Error Reporting log version: 2.0

Error Signature:
Exception: EXC_BAD_ACCESS
ExceptionEnumString: 1
Exception Code: KERN_INVALID_ADDRESS (0x0000000000000038)
Date/Time: 2022-06-01 17:37:39 +0000
Application Name: Microsoft Excel
Application Bundle ID: com.microsoft.Excel
Application Signature: XCEL
Application Bitness: x64
Application Version: 16.37.0.20051002
Crashed Module Name: Microsoft Excel
Crashed Module Version: 16.37.0.200510
Crashed Module Offset: 0x00000000014cbab2
Blame Module Name: Microsoft Excel
Blame Module Version: 16.37.0.200510
UnsymbolicatedChecksum: A699EB3EE97B59DD163EB03C62ECBC76
Blame Module Offset: 0x00000000014cbab2
StackHash: 8d7c6d11486ffc39-dm_1_main
Application LCID: 1033
Extra app info: Reg=en Loc=0x0409
Build Type: Release
Crashed thread Stack Pointer: 0x_00007ffee5a7f430
Crashed thread: 0

...
...

Operating System Information
Operating System: Mac OS X 10.16 (Build 20G165)
CPU: Intel x86, Logical CPU Count: 8, Frequency: 2300 MHz
Physical Memory: 8192 MB
Device_model: MacBookPro15,2
Screen: 2560.000000 x 1440.000000, bitsPerPixel = 24, frame = 0.000000, 0.000000, 2560.000000, 1440.000000
Screen: 1440.000000 x 900.000000, bitsPerPixel = 24, frame = 2560.000000, -51.000000, 1440.000000, 900.000000
CrashedApp_Virtual_Memory_Size_MB: 5626.136
CrashedApp_Resident_Memory_Size_MB: 222.0937
ErrorReportingDeviceUUID: 0B11CEDA-7F57-56C1-B108-A2635D4A3256
ErrorReportingUUID: 78EA2A47-F1F6-494A-BCC6-DC4C65F20E52
ULS UUID: E60D5613-45EF-451C-B425-A3FD0BA02816
CrashedLogSessionId: E60D5613-45EF-451C-B425-A3FD0BA02816
TimeFromLaunch: 0 hours, 0 minutes, 13 seconds
CrashedSessionDuration: 13
Total errors on this client: 6

Microsoft Application Information:
Audience: Production
AudienceGroup: Production
AudienceChannel: CC
```

**Comment by SheetJSDev** [comment]
The export worked as expected on 16.61.

After rolling back to "Version 16.37 (20051002)" something very weird happened.  Using the live demo to generate a file once, it crashed Excel the first time.  After that, https://sheetjs.com/demos/table testing the XLSB demo worked.  Then going back to https://docs.sheetjs.com/docs/example the new exports "just worked".  Can you see if that sequence generates a file that will open?

None of this is affecting the latest version (16.61).  We could try to biject but this really seems like a case of Excel "moving fast and breaking things".

As for the demo, we'll change it to generate an XLSX file

**Comment by SheetJSDev** [comment]
The demo has updated to use XLSX.

As this appears to be an issue with an Excel patch version, and does not affect the latest version of Excel 365 or the latest version of Excel 2016 for Mac, it's almost certainly an Excel regression that was fixed.  If there are more reports we can revisit this.
