### ISSUE TITLE
WorkSheets does not return [!row] property

### ISSUE THREAD

**Issue by abhijeetrai5** [SheetJS/sheetjs#2708]
(https://stackblitz.com/edit/angular-import-excel-q1qfvg?file=app/app.component.ts)
For few excel sheet on const ws: XLSX.WorkSheet = wb.Sheets[wsname]; worksheets does not have !row property even though passing parsing option cellStyles:true, with help of which we can extract group level/outline for each row.
Attached a file for which workSheet does not return !row property.
[Project Sheet.xlsx](https://github.com/SheetJS/sheetjs/files/8869528/Project.Sheet.xlsx)

**Comment by SheetJSDev** [comment]
None of the rows have custom heights or outline levels, so no objects are created.  Try setting an outline level to a row and testing again.

**Comment by abhijeetrai5** [comment]
So you meant only sheets having row level set will have [!row] object returned?. I have tested it with few files without outline level set [!row] was having level set 1 for all the rows. this got me confused.
