### ISSUE TITLE
How do i select which row will be exported from a table?

### ISSUE THREAD

**Issue by VPMoreira** [SheetJS/sheetjs#2711]
I'm trying to get the rows based on my checkbox value.

**Comment by SheetJSDev** [comment]
By default all rows are exported.  Depending on the target, there are a few ways to specify regions:

1) You can modify the `"!ref"` field of each worksheet.  It will affect how every utility function and exporter processes the data.

2) Some methods like [`sheet_to_json`](https://docs.sheetjs.com/docs/api/utilities#array-output) take a `range` parameter to override the range.

If you have a more specific example (starting point, ending point), more specific advice can be provided.
