### ISSUE TITLE
No way to close the file

### ISSUE THREAD

**Issue by blindxfish** [SheetJS/sheetjs#2713]
I am collecting data from a folder full of excel files. Opening them one by one using a queue but still getting EMFILE: too many open files. In fs we have the close() but there is clear way to close the used file. I think it shall be a XLSX.close(filename) or similar function to release from the memory.

**Comment by blindxfish** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/17624413/173527175-9c91e12d-ed5e-4c89-9a8e-065d4d84f675.png">

**Comment by blindxfish** [comment]
Solved my issue by writing with  fs.appendFileSync() after every call of the XLSX method, so in this way the data is written to the file before I start to parse the next one, so it gets closed. But still would be a nice feature to have access to close

**Comment by SheetJSDev** [comment]
You can perform all of the operations manually:

`var wb = XLSX.readFile(filename, options);` is equivalent to
```js
var file = fs.readFileSync(filename);
var wb = XLSX.read(file, options);
```

`XLSX.writeFile(wb, filename);` is equivalent to
```js
var buf = XLSX.write(wb, {type: "buffer", bookType: path.extname(filename).slice(1)});
fs.writeFileSync(filename, buf);
```
