### ISSUE TITLE
Unable to read dbf file.

### ISSUE THREAD

**Issue by arshdoda** [SheetJS/sheetjs#2714]
I am using the following code to read dbf file. It shows the content in console but wb sheetnames and sheets are empty.
```
import * as XLSX from "xlsx";
const reader = new FileReader();
const rABS = !!reader.readAsBinaryString;
if (rABS) reader.readAsBinaryString(v);
else reader.readAsArrayBuffer(v);
reader.onload = ({ target: { result } }) => {
  console.log(result);
  let opt = [];
  const wb = XLSX.read(result, {
    type: rABS ? "binary" : "array",
    codepage: 936,
  });
  console.log(wb);
  const wsname = wb.SheetNames[0];
  const ws = wb.Sheets[wsname];
  getHeaderRow(ws).forEach((c) => {
    console.log(c)
  });
};
```
![Screenshot from 2022-06-14 18-34-06](https://user-images.githubusercontent.com/11732646/173583975-256e37d7-83d8-4819-b9ba-c255e907d171.png)

**Comment by SheetJSDev** [comment]
Can you share the file?

**Comment by SheetJSDev** [comment]
If you are using >= 0.18.1 and overriding codepage, you need to load the codepage library : https://docs.sheetjs.com/docs/installation/frameworks

```js
import * as XLSX from 'xlsx';
import * as cptable from 'xlsx/dist/cpexcel.full.mjs';
XLSX.set_cptable(cptable);
```

(before that version, the standalone dist build was used)

You can verify that the parsing does work by testing against https://oss.sheetjs.com/
