### ISSUE TITLE
Trying to set a border around a range of cells

### ISSUE THREAD

**Issue by rchancey** [SheetJS/sheetjs#2715]
I am trying to set a border and background around a range of cells. .. something like this:

    var range = XLSX.utils.decode_range("A0:C1");
  
    range.s = {
        fill: {
            patternType: "solid",
            fgColor: { rgb: "228B22" },
        }
    };
but it's not working.

I can set this on a single cell fine, but the range is not working.

Any ideas or a way to manipulate a range of cells?

Any help would be much appreciated!

**Comment by Rohan-telesoft** [comment]
please send me that single cell style code snippet
