### ISSUE TITLE
Export of simple json to xlsx file causes error in EXCEL

### ISSUE THREAD

**Issue by lemonbob** [SheetJS/sheetjs#2720]
When exporting a simple JSON to xlsx, EXCEL throws the following error and claims to need to repair file.
![excel_error](https://user-images.githubusercontent.com/43204197/174056721-18bd90b1-8145-4702-9058-5b85788b40ef.jpg)

On repairing the file, EXCEL report the following error in its log

```<repairedRecord>Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)</repairedRecord>```

The JSON  file exported is a very simple test file - see below

[
{series name: 'Compliance/Legal', x: '0.5', y: '0.5', value: '1'},
{series name: 'People', x: '4.5', y: '3.5', value: '1'},
{series name: 'Brexit', x: '0.5', y: '4.5', value: '1'},
{series name: 'Business Plan', x: '0.5', y: '4.5', value: '2'}
]

code used to create the file is as follows:

let workSheet = $XLSX.utils.json_to_sheet(data, {header: ['series name', 'x', 'y', 'value']});
let wb = $XLSX.utils.book_new();
$XLSX.utils.book_append_sheet(wb, workSheet, fileName);
$XLSX.writeFile(wb, fileName, {bookType: 'xlsx'});

Please advise.

**Comment by SheetJSDev** [comment]
You gave everything except for the part causing problems :/

The error message suggests that the worksheet name may be causing issues.  What is `fileName` and can you share the bad file?

To be sure this is not a normal occurrence, here's an example using your exact data: https://jsfiddle.net/gb2hakmd/

```js
const fileName = "issue2720.xlsx";

const data = [
{'series name': 'Compliance/Legal', x: '0.5', y: '0.5', value: '1'},
{'series name': 'People', x: '4.5', y: '3.5', value: '1'},
{'series name': 'Brexit', x: '0.5', y: '4.5', value: '1'},
{'series name': 'Business Plan', x: '0.5', y: '4.5', value: '2'}
];

let workSheet = XLSX.utils.json_to_sheet(data, {header: ['series name', 'x', 'y', 'value']});
let wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, workSheet, fileName);
XLSX.writeFile(wb, fileName, {bookType: 'xlsx'});
```

**Comment by lemonbob** [comment]
Hi, yes, no problem. Attached is the file and the fileName is: `RiskThemes_ Bubble Chart.xlsx`.

[RiskThemes_ Bubble Chart.xlsx](https://github.com/SheetJS/sheetjs/files/8935241/RiskThemes_.Bubble.Chart.xlsx)

I tried exporting with a fileName of `test.xlsx` and you are correct, it is fine, but I don't see anything wrong with the filename - it seems perfectly valid to me? Any ideas?

`RiskThemes_ Bubble Chart.xlsx`

**Comment by backfromexile** [comment]
Hey there, I just had the same problem, but managed to find a fix.
In my case one of the sheet names had a colon `:` in the name which Excel apparently does not like.
I removed the colon and the shown error message disappared.

@SheetJSDev could validation of the sheet names be possible?

**Comment by SheetJSDev** [comment]
That was added in 0.18.10.  Discussion continued in #2722
