### ISSUE TITLE
How to get typings when using cdn?

### ISSUE THREAD

**Issue by Gildedter** [SheetJS/sheetjs#2721]
I followed the instructions [here](https://docs.sheetjs.com/docs/installation/standalone) // I'm using `xlsx.full.min.js`, but I'm getting this error:
```
Untyped function calls may not accept type arguments.ts(2347)
```
I tried looking for typings via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), since I didn't see any npm package for the [official typings](https://github.com/SheetJS/sheetjs/tree/master/types), should I just download it directly? Would that be allowed license wise?

**Comment by SheetJSDev** [comment]
For projects using yarn/pnpm/npm (like create-react-app or webpack-based projects), the tarballs should be used https://docs.sheetjs.com/docs/installation/frameworks

If you are making a simple site that expects typescript types, https://cdn.sheetjs.com/xlsx-0.18.9/package/types/index.d.ts is the latest type defs (you can vendor the types as well as the standalone script)

If neither approach applies, share a sample project
