### ISSUE TITLE
read from buffer generates unexpected values

### ISSUE THREAD

**Issue by nina-alpakas** [SheetJS/sheetjs#2723]
So I have have created a graphql API using nest.js for uploading csvs and reading the values. It works as expected in 99.9% of cases, but a .csv file which contains certain values with the less than sign "<" is returning unexpected results

My code is as follows:

```ts
import { Args, Mutation } from '@nestjs/graphql';
import { FileUpload } from 'graphql-upload';

@Mutation(() => ResponseDto)
async uploadProductsFromCSV(
  @Args('file', {type: () => GraphQLUpload}) file: FileUpload): Promise<ResponseDto> {
  const { createReadStream } = file;

  const stream = createReadStream();
  const chunks = [];

  for await (const chunk of stream) {
    chunks.push(chunk);
  }

  const buffer = Buffer.concat(chunks);

  const { SheetNames, Sheets } = XLSX.read(buffer, { type: 'buffer' });

  const sheet = Sheets[SheetNames[0]]);
  console.log(sheet)
  
  ...
}
```

When I upload a .csv file with data that looks like this -
variable1 | variable2 | variable3
--- | --- | ---
<0.1 | <0.2 | <0.3

The resulting sheet looks like this - 
```
{
  A1: { t: 's', v: 'variable1', w: 'variable1' },
  B1: { t: 's', v: 'variable2', w: 'variable2' },
  C1: { t: 's', v: 'variable3', w: 'variable3' },
  A2: { t: 's', v: '<0.1' },
  B2: { t: 'n', v: 36557, w: '2/1/00' },
  C2: { t: 'n', v: 44810, w: '9/6/22' },
}
```

As you can see `variable1` has correctly been read as `<0.1` but for some reasons the other values are converted to unexpected numbers/dates. Can you explain to me why this is happening and how I can prevent it ? I've been scratching my head with this for a few hours now and haven't found any help in the documentation so any help is much appreciated !

Thank you

**Comment by SheetJSDev** [comment]
NodeJS thinks those are dates:

```js
> new Date("<0.1")
2000-01-01T05:00:00.000Z
> new Date("<0.2")
2000-02-01T05:00:00.000Z
> new Date("<0.3")
2000-03-01T05:00:00.000Z
```

This is a V8 (NodeJS + Chrome JS engine) bug, as evidenced with

```js
> new Date("This is most assuredly not a date 1")
Mon Jan 01 2001 00:00:00 GMT-0500 (Eastern Standard Time)
```

There are some attempts to correct for the bug, but they are clearly not complete.

It *might* be sufficient to remove https://github.com/SheetJS/sheetjs/blob/master/bits/20_jsutils.js#L188 as that is what is permits "<0.2" but not "<0.1"

**Comment by SheetJSDev** [comment]
This will go live in the next release:

```js
/* 0.18.9 */
> XLSX.read("x,y,z\n<0.1,<0.2,<0.3", {type: "binary"}).Sheets.Sheet1
{
  A1: { t: 's', v: 'x' },
  B1: { t: 's', v: 'y' },
  C1: { t: 's', v: 'z' },
  A2: { t: 's', v: '<0.1' },
  B2: { t: 'n', v: 36557, w: '2/1/00' },
  C2: { t: 'n', v: 36586, w: '3/1/00' },
  '!ref': 'A1:C2'
}

/* HEAD */
> XLSX.read("x,y,z\n<0.1,<0.2,<0.3", {type: "binary"}).Sheets.Sheet1
{
  A1: { t: 's', v: 'x' },
  B1: { t: 's', v: 'y' },
  C1: { t: 's', v: 'z' },
  A2: { t: 's', v: '<0.1' },
  B2: { t: 's', v: '<0.2' },
  C2: { t: 's', v: '<0.3' },
  '!ref': 'A1:C2'
}

```
