### ISSUE TITLE
How to add style for cells and space or another blank row for each concat tables?

### ISSUE THREAD

**Issue by Ragearino** [SheetJS/sheetjs#2724]
hiddenTable();
	hiddenTable2();
	var oID = document.getElementById("txtOpportunityID").innerHTML;
	let today = new Date().toISOString().slice(0, 10);
	let tbl1 = document.getElementById("extractTable");
	let tbl2 = document.getElementById("corepursuitTable");
	let tbl3 = document.getElementById("requirementsTable");
	let tbl4 = document.getElementById("subprocessTable");
	let tbl5 = document.getElementById("extractTable2");
	let worksheet_tmp1 = XLSX.utils.table_to_sheet(tbl1);
	let worksheet_tmp2 = XLSX.utils.table_to_sheet(tbl2);
	let worksheet_tmp3 = XLSX.utils.table_to_sheet(tbl3);
	let worksheet_tmp4 = XLSX.utils.table_to_sheet(tbl4);
	let worksheet_tmp5 = XLSX.utils.table_to_sheet(tbl5);
	   
	let a = XLSX.utils.sheet_to_json(worksheet_tmp1, { header: 1 })
	let b = XLSX.utils.sheet_to_json(worksheet_tmp2, { header: 1 })
	let c = XLSX.utils.sheet_to_json(worksheet_tmp3, { header: 1 })
	let d = XLSX.utils.sheet_to_json(worksheet_tmp4, { header: 1 })
	let e = XLSX.utils.sheet_to_json(worksheet_tmp5, { header: 1 })
	   
	a = a.concat(['']).concat(b,).concat(c).concat(d).concat(e)
	let worksheet = XLSX.utils.json_to_sheet(a, { skipHeader: true })
	
	const new_workbook = XLSX.utils.book_new()
	XLSX.utils.book_append_sheet(new_workbook, worksheet, "OPC_" + oID + "_" + today)
	XLSX.writeFile(new_workbook, "OPC_" + oID + "_" + today + '.xls')

**Comment by SheetJSDev** [comment]
This envisioned case (pulling from tables and adding gap rows in-between) is demonstrated in https://docs.sheetjs.com/docs/api/utilities#html-table-input (search for "MultiTable" to find the live codeblock).

We do not currently support styling in the Community Edition, but there is definitely a plan to add support at some point.  Until then, it and a bevy of advanced features are part of our Pro offering.
