### ISSUE TITLE
XLSX.read always read sheetname as sheet1

### ISSUE THREAD

**Issue by consciousnessdev** [SheetJS/sheetjs#2725]
I have problem when run XLSX.read its always return sheet name as Sheet1, even though the sheet name has been changed to 'data',
![image](https://user-images.githubusercontent.com/30996656/175294618-343f5275-26ef-48bb-a484-622356cb75f8.png)

Maybe can help with below clues:
- my laptop use linux xubuntu 20.04 x64 with latest Google Chrome version, before opened by WPS Spreadsheet / Libre Calc it keeps read sheet name as sheet1, 
- before read by XLSX, i did converted file object to base64, then read file with syntax:
`const workbook = XLSX.read(convertFileToBase64, { type: 'base64' });`

**Comment by consciousnessdev** [comment]
Solved.

Caused by File Object must Converted to Binary String, then set XLSX.read type to binary

**Comment by robhoff-laerdal** [comment]
@consciousnessdev How did you convert your file to a binary string? I am having the same issue.

**Comment by consciousnessdev** [comment]
> @consciousnessdev How did you convert your file to a binary string? I am having the same issue.
With this Code @robhoff-laerdal 
```
const fileObjectToBinary = fileObj => new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsBinaryString(fileObj);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
});
```

Hope its help you :)
