### ISSUE TITLE
how to add new json or aoa to existing file from the first empty cell

### ISSUE THREAD

**Issue by Md-Mal** [SheetJS/sheetjs#2726]
im trying to write new data to existing xlsx file that find the first empty cell and then write at that cell. I already tried using origin which need manually put the cell number. If there any solution that can automatic find the first empty cell?

**Comment by SheetJSDev** [comment]
As described [in the docs](https://docs.sheetjs.com/docs/api/utilities#array-of-arrays-input), passing an origin of `-1` will "Append to bottom of worksheet starting on first column".  There's an example:

```
XXX| A | B | C | D | E | F | G |
---+---+---+---+---+---+---+---+
 1 | S | h | e | e | t | J | S |
 2 | 1 | 2 |   |   | 5 | 6 | 7 |
 3 | 2 | 3 |   |   | 6 | 7 | 8 |
 4 | 3 | 4 |   |   | 7 | 8 | 9 |
 5 | 4 | 5 | 6 | 7 | 8 | 9 | 0 |
```

This worksheet can be built up in the order `A1:G1`, `A2:B4`, `E2:G4`, `A5:G5` (take a look at how the last row is added):

```js
/* Initial row */
var ws = XLSX.utils.aoa_to_sheet([ "SheetJS".split("") ]);

/* Write data starting at A2 */
XLSX.utils.sheet_add_aoa(ws, [[1,2], [2,3], [3,4]], {origin: "A2"});

/* Write data starting at E2 */
XLSX.utils.sheet_add_aoa(ws, [[5,6,7], [6,7,8], [7,8,9]], {origin:{r:1, c:4}});

/* Append row */
XLSX.utils.sheet_add_aoa(ws, [[4,5,6,7,8,9,0]], {origin: -1});
```
