### ISSUE TITLE
Payload too large 

### ISSUE THREAD

**Issue by ErkanKabil** [SheetJS/sheetjs#2728]
I try create excel file for my data. But its get this error. Data length is 4300. its sats "Payload too large"

![image](https://user-images.githubusercontent.com/58916013/177164065-e502ecff-cc21-4d02-be53-e6a84a485534.png)

**Comment by SheetJSDev** [comment]
That is an issue with Fastify, see https://www.fastify.io/docs/latest/Reference/Server/#bodylimit for more details

**Comment by SheetJSDev** [comment]
A note, with the proper resolution, has been added to the docs https://docs.sheetjs.com/docs/demos/server/#fastify
