### ISSUE TITLE
数据过大卡死问题

### ISSUE THREAD

**Issue by yufengaotianya** [SheetJS/sheetjs#2732]
您好！我这边测试写入js数组数据100000*100的数组，使用XLSX.utils.aoa_to_sheet函数的时候卡死；
测试代码如下：
![image](https://user-images.githubusercontent.com/33416518/177297812-d29cdb83-82f3-4028-a66a-502f99cf4d13.png)

请问最大数据限额是多少呢，我该如何判断呢

**Comment by SheetJSDev** [comment]
JavaScript engine bug: https://bugs.chromium.org/p/v8/issues/detail?id=6696

Try

```js
let worksheet = XLSX.utils.aoa_to_sheet(allRowDataList, {dense: true});
```

**Comment by yufengaotianya** [comment]
非常感谢；问题解决了！
