### ISSUE TITLE
Windows 11 export xlsx file

### ISSUE THREAD

**Issue by Akil-saiyed** [SheetJS/sheetjs#2733]
In some windows 11 systems .xlsx files are not exporting and chrome got stuck , can you please let me know  how can i fix that and i am using react implementation

**Comment by SheetJSDev** [comment]
Windows 11 Chrome should be using the standard HTML5 download trick.  Can you check the console to see if there are any errors?

https://jsfiddle.net/8jfrh47z/ is a small demo of the relevant code path:

```js
var u8 = new TextEncoder().encode("Hello World!");
var blob = new Blob([u8], { type: "application/octet-stream" });
var url = URL.createObjectURL(blob);
var a = document.createElement("a");
a.download = "HelloWorld.txt";
a.href = url;
document.body.appendChild(a);
a.click();
```

**Comment by SheetJSDev** [comment]
https://app.saucelabs.com/tests/a2fa4a9657244c08b7a8e18bd3817889#1 sauce labs test on windows 11 + chrome 103.  Video shows 6 exports including XLSX.

If you can share a demo or some way to reproduce, we can take a closer look.
