### ISSUE TITLE
elementui中使用 xlsx报错

### ISSUE THREAD

**Issue by wjzxc123** [SheetJS/sheetjs#2735]
例如:
`<el-table
                            id="settlement_table"
                            :data="settlement_data"
                            height="calc(100vh - 100px)"
                            border
                            style="width: 100%">...</el-table>`
使用方式：
` var wb = XLSX.utils.table_to_book(document.querySelector("#settlement_table"));`

报错：
`Uncaught Unsupported origin when DIV is not a TABLE`

现在不支持elementui了吗？
非常期待你的回复

**Comment by SheetJSDev** [comment]
You should export the state `settlement_table` object array:

```js
var ws = XLSX.utils.json_to_sheet(settlement_table)
```

If you really want to export from the DOM TABLE:

```js
var wb = XLSX.utils.table_to_book(document.querySelector("#settlement_table").getElementsByTagName("TABLE")[0]);
```

**Comment by wjzxc123** [comment]
非常感谢您的回复，问题已解决，愿您开心每一天

**Comment by hellolex** [comment]
> You should export the state `settlement_table` object array:
> 
> ```js
> var ws = XLSX.utils.json_to_sheet(settlement_table)
> ```
> 
> If you really want to export from the DOM TABLE:
> 
> ```js
> var wb = XLSX.utils.table_to_book(document.querySelector("#settlement_table").getElementsByTagName("TABLE")[0]);
> ```

The first solution is that the table header cannot be exported because the data is only the data body
The second method can only export the table header, because the element-ui table is actually composed of multiple tables dom. The header is one, the data body is one, and the footer is one

table_ to_ Book of previous version  can directly convert element-ui table to excel for export:
XLSX.utils.table_to_book($el.querySelector('.el-table'))

**Comment by SheetJSDev** [comment]
@hellolex  The old behavior is equivalent to:

```js
// elt is a reference to the DOM element
var elt = document.querySelector("#settlement_table");

// create new workbook
var wb = XLSX.utils.book_new();
// get all table children
var children = elt.getElementsByTagName("TABLE");
// loop
for(var i = 0; i < children.length; ++i) {
  // create worksheet
  var ws = XLSX.utils.table_to_sheet(children[i]);
  // append
  XLSX.utils.book_append_sheet(wb, ws, "Sheet" + (i+1));
}
```

If a proper Element UI demo is of interest, please raise an issue in our docs repo https://git.sheetjs.com/sheetjs/docs.sheetjs.com/issues
