### ISSUE TITLE
Use json_to_sheet to save custom formula

### ISSUE THREAD

**Issue by tqdo** [SheetJS/sheetjs#2736]
The question is similar to this [one](https://github.com/SheetJS/sheetjs/issues/2017). Basically I would like to use json_to_sheet to export formula. The solution in the link above works fine for formulas which contain only built-in formulas. However, if the formulas contain a custom function, then the export file will be like this `=@CustomFunction(...`. Is there any way to get rid of the "@" in the exported file?

**Comment by SheetJSDev** [comment]
Excel "moved fast and broke things".

`@` is the implicit intersection operator and will be shown when certain types of custom functions are used in a normal formula.  Mark it as a dynamic array formula.  Docs: https://docs.sheetjs.com/docs/csf/features/formulae#dynamic-array-formulae

**Comment by tqdo** [comment]
Thanks. The `@` is gone but now the formula is wrapped in `{` and `}`. Is there anyway to remove those brackets as well?

**Comment by tqdo** [comment]
thanks. turns out the problem was my `xlsx` is not up to date. Upgrading the library removes the `{` and `}`. However, for some reasons, Excel does not automatically evaluate the custom function. I need to go to each cell and press Enter, then Excel would run the custom function. Do you happen to know how to fix that? Thanks in advance
