### ISSUE TITLE
sheet[cell].s.font property invalid？

### ISSUE THREAD

**Issue by Shurangan** [SheetJS/sheetjs#2738]
Example：
    
 
    const sheet = XLSX.utils.json_to_sheet([{test:666}]);    
    sheet.A1.s.font = {
      sz: 18,
      bold: true,
      font: '#ff0000'
    };
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, sheet, '666.xlsx');
    XLSX.writeFile(wb, '666.xlsx');

    

   problem：  sheet.A1.s.font property invalid.

   version：0.18.9

**Comment by t-mangoe** [comment]
It appears that the features related to style are only available in the PRO version.
If you are using the Community version, you may not be able to specify a style.

**Comment by SheetJSDev** [comment]
There is a plan to revisit styling support, but the current focus of the open source project is data extraction and preservation.  Until then, it and a bevy of advanced features are part of our Pro offering.
