### ISSUE TITLE
How to Move Column?

### ISSUE THREAD

**Issue by PleaseIceAmericano** [SheetJS/sheetjs#2741]
![4](https://user-images.githubusercontent.com/99066882/178712277-dddbec83-e302-44c9-bfab-8e06d972c911.png)
![3](https://user-images.githubusercontent.com/99066882/178712302-153585fe-38ca-4fe4-90c3-6ada4a991d1e.png)

I am very grateful that I have recently learned about SheetJS and have been using it well.

I inquire like this because there is a problem in the process of putting several tables in Excel.

In the second picture, I want to send the column with County to the front to make Excel like the first picture.

I'm inquiring with the script I wrote, so please tell me how.

Best Regard.

let tbl1 = document.getElementById("report-table1")
		let tbl2 = document.getElementById("report-table2")
		let tbl3 = document.getElementById("report-table3")
		let tbl4 = document.getElementById("report-table4")
		let tbl5 = document.getElementById("report-table5")

		let worksheet_tbl1 = XLSX.utils.table_to_sheet(tbl1);
		let worksheet_tbl2 = XLSX.utils.table_to_sheet(tbl2);
		let worksheet_tbl3 = XLSX.utils.table_to_sheet(tbl3);
		let worksheet_tbl4 = XLSX.utils.table_to_sheet(tbl4);
		let worksheet_tbl5 = XLSX.utils.table_to_sheet(tbl5);

		let sheet_main
		let sheet1 = XLSX.utils.sheet_to_json(worksheet_tbl1, { header: 1 })
		let sheet2 = XLSX.utils.sheet_to_json(worksheet_tbl2, { header: 1 })
		let sheet3 = XLSX.utils.sheet_to_json(worksheet_tbl3, { header: 1 })
		let sheet4 = XLSX.utils.sheet_to_json(worksheet_tbl4, { header: 1 })
		let sheet5 = XLSX.utils.sheet_to_json(worksheet_tbl5, { header: 1 })

		sheet_main = sheet1.concat(['']).concat(sheet2.concat([''])).concat(sheet3.concat([''])).concat(sheet4.concat([''])).concat(sheet5.concat(['']))

		let worksheet = XLSX.utils.json_to_sheet(sheet_main, {skipHeader: true })

		const new_workbook = XLSX.utils.book_new()
		XLSX.utils.book_append_sheet(new_workbook, worksheet, "Test Report")
		XLSX.writeFile(new_workbook, 'Test Report.xlsx')

**Comment by PleaseIceAmericano** [comment]
Plz Somebody Help!!!!

**Comment by SheetJSDev** [comment]
Try using `aoa_to_sheet` when building the sheet:

```js
	let worksheet = XLSX.utils.aoa_to_sheet(sheet_main)
```

If there is still a large gap, inspect `sheet_main` and the actual table to be sure that the gap isn't in the original table.  If there is no gap, please share the original HTML and we can reopen and investigate.

**Comment by PleaseIceAmericano** [comment]
If I use aoa_to_sheet, I get a message that I can't find the function, is it a function that I can use at a cost?

**Comment by PleaseIceAmericano** [comment]
Thanks!!!

**Comment by SheetJSDev** [comment]
There's a better way to do this with `sheet_add_dom`, see https://docs.sheetjs.com/docs/api/utilities#html-table-input for more details.

But for the code as originally written, https://jsfiddle.net/neptd8kj/ is a live example:

**HTML**

```html
<table id="report-table1">
  <tr><td>Table1A1</td><td>Table1B1</td></tr>
  <tr><td>Table1A2</td><td>Table1B2</td></tr>
</table>
<table id="report-table2">
  <tr><td>Table2A1</td><td>Table2B1</td></tr>
  <tr><td>Table2A2</td><td>Table2B2</td></tr>
</table>
<table id="report-table3">
  <tr><td>Table3A1</td><td>Table3B1</td></tr>
  <tr><td>Table3A2</td><td>Table3B2</td></tr>
</table>
<table id="report-table4">
  <tr><td>Table4A1</td><td>Table4B1</td></tr>
  <tr><td>Table4A2</td><td>Table4B2</td></tr>
</table>
<table id="report-table5">
  <tr><td>Table5A1</td><td>Table5B1</td></tr>
  <tr><td>Table5A2</td><td>Table5B2</td></tr>
</table>
```

**JS**

```js
let worksheet_tbl5 = XLSX.utils.table_to_sheet(tbl5);

let sheet_main
let sheet1 = XLSX.utils.sheet_to_json(worksheet_tbl1, { header: 1 })
let sheet2 = XLSX.utils.sheet_to_json(worksheet_tbl2, { header: 1 })
let sheet3 = XLSX.utils.sheet_to_json(worksheet_tbl3, { header: 1 })
let sheet4 = XLSX.utils.sheet_to_json(worksheet_tbl4, { header: 1 })
let sheet5 = XLSX.utils.sheet_to_json(worksheet_tbl5, { header: 1 })

sheet_main = sheet1.concat(['']).concat(sheet2.concat([''])).concat(sheet3.concat([''])).concat(sheet4.concat([''])).concat(sheet5.concat(['']))

let worksheet = XLSX.utils.aoa_to_sheet(sheet_main)

const new_workbook = XLSX.utils.book_new()
XLSX.utils.book_append_sheet(new_workbook, worksheet, "Test Report")
XLSX.writeFile(new_workbook, 'Test Report.xlsx')
```

**Comment by PleaseIceAmericano** [comment]
OK, I'll try that
Thanks to you, my cord length is reduced by 1/100.
