### ISSUE TITLE
How can i format numbers with writeFile options?

### ISSUE THREAD

**Issue by matheustanaka** [SheetJS/sheetjs#2746]
I'm trying to format number values to currency, I would like to know if is it possible to do that with writeFile() ?

My code: 
![image](https://user-images.githubusercontent.com/59452094/179818756-27da449f-bc5d-4114-a715-56910a05b14e.png)

What I need: 
![image](https://user-images.githubusercontent.com/59452094/179818884-5d585aa6-d95a-4263-9e59-83021a33cae2.png)

**Comment by SheetJSDev** [comment]
Loop and set the `z` property to "#,##0.00" (notice it uses the en-US form -- Excel will automatically use the local settings):

```js
const range = xlsx.utils.decode_range(newWorkSheet["!ref"]);
for(var R = 1; R <= range.e.r; ++R) {
  const cell = newWorkSheet["I" + (R+1)];
  if(cell) cell.z = "#,##0.00";
}
```

**Comment by matheustanaka** [comment]
@SheetJSDev should i pass range in writeFile?
