### ISSUE TITLE
Not working on Angular 13 and 14 - xlsx latest version

### ISSUE THREAD

**Issue by Coooi** [SheetJS/sheetjs#2747]
![image](https://user-images.githubusercontent.com/3846028/180155296-8dc4c8fc-c4a1-4ac3-a1d1-2aceba628391.png)

I'm having the same problem as from
https://github.com/SheetJS/sheetjs/issues/2507

Angular 13 and 14
"xlsx": "^0.18.5",

**Comment by SheetJSDev** [comment]
The [angular2 demo](https://github.com/SheetJS/sheetjs/blob/master/demos/angular2) appears to work correctly for angular 13. To test, you can run:

```bash
git clone https://github.com/SheetJS/sheetjs
cd sheetjs/demos/angular2
make ng13
```

To verify it is running, run `npm start`, open a web browser and go to http://localhost:4200/

Please test against our demo.  If it works, then you are likely encountering a bug with Angular's tooling.  If our demo is failing, please let us know and we can investigate further.

PS: https://docs.sheetjs.com/docs/installation/frameworks follow the instructions to get the latest version.

**Comment by Coooi** [comment]
@SheetJSDev  please reopen this issue as it's not working on Angular 13+

Versions:
"sheetjs-style": "^0.15.8",
"xlsx": "^0.18.5",

![image](https://user-images.githubusercontent.com/3846028/231410162-4d00938c-bc93-4063-85cf-01bb79ac32c0.png)

![image](https://user-images.githubusercontent.com/3846028/231410684-a554c44b-b7a9-4830-838e-0a940003f1f9.png)

**Comment by Coooi** [comment]
The issue was that we were using writeFile method from sheetsjs-style

`import { writeFile } from 'sheetjs-style';`

but there's no error when importing it from 'xlsx' directly:

`import { writeFile } from 'xlsx';`
