### ISSUE TITLE
Bundled (rollup) xlsx in ESM environment raises Cannot access file error 

### ISSUE THREAD

**Issue by ClementValot** [SheetJS/sheetjs#2748]
# Code to reproduce 

`package.json`
```
{
  "name": "xlsx-esm-rollup",
  "type": "module",
  "scripts": {
    "bundle": "rollup --config",
    "run-main": "node main.js",
    "run-bundle": "node bundle.js"
  },
  "dependencies": {
    "node-xlsx": "^0.21.0"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^22.0.1",
    "@rollup/plugin-node-resolve": "^13.3.0",
    "rollup": "^2.77.0"
  }
}
```

`rollup.config.js`
```import commonjs from '@rollup/plugin-commonjs';
import nodeResolve from "@rollup/plugin-node-resolve";


export default {
    input: 'main.js',
    output: {
        file: 'bundle.js',
        format: 'es',
    },
    plugins: [
        nodeResolve(),
        commonjs()
    ],
};
```

`main.js`
```
import xlsx from "node-xlsx";

const myParsedFile = xlsx.parse("myFile.xlsx")
console.log(myParsedFile.toString()) 
```

```
yarn install
yarn bundle 
yarn run-bundle
``` 
=>
`Error: Cannot access file myFile.xlsx`

# What happened 

xlsx method read_binary makes use of fs.readFileSync if it finds node:fs. 
```
function read_binary(path) {
		if(typeof _fs !== 'undefined') return _fs.readFileSync(path);
		// $FlowIgnore
		if(typeof $ !== 'undefined' && typeof File !== 'undefined' && typeof Folder !== 'undefined') try { // extendscript
			// $FlowIgnore
			var infile = File(path); infile.open("r"); infile.encoding = "binary";
			var data = infile.read(); infile.close();
			return data;
		} catch(e) { if(!e.message || !e.message.match(/onstruct/)) throw e; }
		throw new Error("Cannot access file " + path);
	}
```

and _fs is fetched as a conditional and not as a top-level import 
```
	var _fs;
	if(typeof commonjsRequire !== 'undefined') try { _fs = require('fs'); } catch(e) {}
```
Which means bundling tools don't convert it when outputing ESM code. (Reminder: "import" must be top-level in ESM environments)
Hence, when ran in an ESM environment, _fs is not found (`ReferenceError: require is not defined
`) and the interpreter goes straight to throwing the Cannot access file error 

Haven't found a smart fix for that :(

**Comment by SheetJSDev** [comment]
`node-xlsx` is https://github.com/mgcrea/node-xlsx

Depending on the target:

"browser": `fs` does not work in the browser and there is no way to implement it with current web APIs.  [There are techniques for allowing users to "upload" data with File Input elements or dragging and dropping files.](https://docs.sheetjs.com/docs/solutions/input) 

"node":

For ESM, the `fs` dependency is not pulled.  [It can be manually overridden, as explained in the docs](https://docs.sheetjs.com/docs/installation/nodejs#esm-import)

```js
import * as XLSX from 'xlsx/xlsx.mjs';

/* load 'fs' for readFile and writeFile support */
import * as fs from 'fs';
XLSX.set_fs(fs);
```

But this is probably not usable if `node-xlsx` is hiding the `XLSX` library.  In that case, you can manually perform the read from your code:

```js
import xlsx from "node-xlsx";
import { readFileSync } from "fs";

const myParsedFile = xlsx.parse(readFileSync("myFile.xlsx"))
console.log(myParsedFile.toString()) 
```
