### ISSUE TITLE
How to update the same file by modifying xtos 

### ISSUE THREAD

**Issue by H-Tambourou** [SheetJS/sheetjs#2751]
` const xtos = (sdata) => {
     var out = utils.book_new();
     sdata.forEach(function(xws) {
       var aoa : any = [[]];
       var rowobj = xws.rows;
       for (var ri = 0; ri < rowobj.len; ++ri) {
         var row = rowobj[ri];
         if (!row) continue;
         aoa[ri] = [];
         /* eslint-disable no-loop-func */
         Object.keys(row.cells).forEach(function(k) {
           var idx = +k;
           if (isNaN(idx)) return;
           aoa[ri][idx] = row.cells[k].text;
         });
       }
       var ws = utils.aoa_to_sheet(aoa);
       utils.book_append_sheet(out, ws, xws.name);
     });
     return out;
  }`
how would i update the same file with data from the xspreadsheet ? I know i have to use sheet_add_aoa but dont know how to modify xtos accordingly

**Comment by SheetJSDev** [comment]
There are 3 general approaches:

1) use `xtos` to generate the worksheets, then use `sheet_add_aoa` to fill data:

```js
const new_wb = xtos(sdata);
new_wb.SheetNames.forEach(name => {
  if(!old_wb.SheetNames.includes(name)) return XLSX.utils.book_append_sheet(old_wb, new_wb.Sheets[name], name);
  const aoa = XLSX.utils.sheet_to_json(new_wb.Sheets[name], {header: 1});
  XLSX.utils.sheet_add_aoa(old_wb.Sheets[name], aoa, { origin: "A1" });
});

```

Note that this approach will use merge cells and other metadata

2) use `xtos` to generate the worksheets, then just replace it in the old workbook:

```js
const new_wb = xtos(sdata);
new_wb.SheetNames.forEach(name => {
  if(!old_wb.SheetNames.includes(name)) old_wb.SheetNames.push(name);
  old_wb.Sheets[name] = new_wb.Sheets[name];
});
```

This wipes out all of the worksheets that are in both the original and new workbook.

3) Bind to the x-spreadsheet `cell-edited` event and apply the change to the workbook every event (see https://github.com/myliang/x-spreadsheet#bind-events for more details).

In theory this is the best approach, but certain actions like inserting and deleting columns do not currently appear to have an event (see https://github.com/myliang/x-spreadsheet/issues/555 )
