### ISSUE TITLE
I want to export the link of the picture to excel, but I can't find a suitable method, can you support it?

### ISSUE THREAD

**Issue by chengmings** [SheetJS/sheetjs#2755]

**Comment by SheetJSDev** [comment]
Images are not currently supported in the Community Edition.  We hope to make it available after the 1.0.0 release.  Until then, we offer it as part of our [Pro compendium](https://sheetjs.com/pro)

**Comment by chengmings** [comment]
> Hello, when will the 1.0 version be launched? Do you need to contact the pro version by email?
