### ISSUE TITLE
React native and Expo - Multiplataform

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SheetJS/sheetjs#2758]
![image](https://user-images.githubusercontent.com/9791364/182985216-efa6f68d-34e1-4a49-9f2e-7ba959bf8942.png)
`  const pickDocument = async (e) => {
    
    try {
      
        let result = await DocumentPicker.getDocumentAsync({copyToCacheDirectory: false, type: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']});  
        console.log(result)
        let content = result.uri.split(',')[1];
        console.log("content",content)
        console.log("uri", result.uri)
      
       //const fileXLS = await FileSystem.readFile(result.uri)
      //const workbook = await XLSX.read(content, {type: 'base64'}) WEB
      //const fileXLS = await XLSX.readFile(result.uri, {})
      const workbook = await XLSX.read(result.uri)
      console.log("workbook",workbook)
      const sheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[sheetName];
      console.log(worksheet)
      const json = XLSX.utils.sheet_to_json(worksheet, {header: 'A1'});
       console.log(json)
      //setItemsInventario({data: json, count: json.length, name: result.name});
       
    } catch (error) {
      console.error(error)
    }
    
  };`

not read file

**Comment by SheetJSDev** [comment]
You need to get the data from the URI using [`FileSystem.readAsStringAsync`](https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemreadasstringasyncfileuri-options)


Starting from `console.log("uri", result.uri)`:

```js
const uri = result.uri;
const b64 = await FileSystem.readAsStringAsync(uri, { encoding: FileSystem.EncodingType.Base64 });
const workbook = XLSX.read(b64, {type: "base64"});
```

Note that `XLSX.read` is synchronous and no `await` is needed for that step.

We'll add an example of React Native + Expo to the docs

**Comment by luizcarlospedrosogomes** [comment]
![image](https://user-images.githubusercontent.com/9791364/183230330-fe2d2f8e-709d-4525-a9b2-a2a1bacde659.png)

**Comment by SheetJSDev** [comment]
At this point, the bug is entirely with Expo.  Raised an issue, please continue the discussion with https://github.com/expo/expo/issues/18534 OR consider dropping Expo and using the raw React Native libraries.  As described [in the documentation](https://docs.sheetjs.com/docs/solutions/input#example-local-file) the library has been tested with `react-native-file-access` and `react-native-fs`

**Comment by luizcarlospedrosogomes** [comment]
` const pickDocument = async (e) => {
    
    try {
      
      let result = await DocumentPicker.getDocumentAsync({copyToCacheDirectory: false, type: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']});  
      let content = result.uri.split(',')[1];
      let workbook = null;
      if (content){
        workbook = await XLSX.read(content, {type: 'base64'});
      }else{
        const uri = FileSystem.documentDirectory+result.name;
        await FileSystem.copyAsync({
          from: result.uri,
          to: uri
        })
        const b64 = await FileSystem.readAsStringAsync(uri, { encoding: FileSystem.EncodingType.Base64 });
        workbook = XLSX.read(b64, {type: "base64"});
      }
      const sheetName = workbook.SheetNames[0];
      const worksheet = workbook.Sheets[sheetName];
      const json = XLSX.utils.sheet_to_json(worksheet, {header: 'A1'});
      setItemsInventario({data: json, count: json.length, name: result.name});
       
    } catch (error) {
      console.error(error)
    }
    
  };`

this code working. thanks

**Comment by brentvatne** [comment]
@luizcarlospedrosogomes - if you just set `copyToCacheDirectory: true` then you don't need to write any of the code for copying to the document directory

notice in the docs for expo-document-picker:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/90494/183231226-d6021709-c5d5-48ee-877e-062ed1cac613.png">

**Comment by SheetJSDev** [comment]
There are new `expo-file-system` snippets in the docs for [importing](https://docs.sheetjs.com/docs/solutions/input#example-local-file) and [exporting](https://docs.sheetjs.com/docs/solutions/output/#example-local-file).  The import snippet has a note that includes the error message and the `DocumentPicker` solution.
