### ISSUE TITLE
The file name of the exported file not orignal headers but random code

### ISSUE THREAD

**Issue by EilyYa** [SheetJS/sheetjs#2759]
In Linux system, Chrome, after I download the file, the filename will be random code like the picture show. 
In other condition, not only the name, the suffix('.xlsx') is missing. If I add the '.xlsx' to the file, then it can open normally.

![image](https://user-images.githubusercontent.com/101782044/183031052-317b99be-2bb0-4fe7-806e-9ccacf7b9680.png)

**Comment by SheetJSDev** [comment]
Can you reproduce the issue using the live demo in https://docs.sheetjs.com/docs/#export-an-html-table-to-excel-xlsx ?  Click the "Export XLSX!" button.  It should create a file `SheetJSTable.xlsx`

**Comment by EilyYa** [comment]
everything goes well in my computer,  the random code is happened in other computer which is not at hand. But I try to find why the bug happens in limited resources. So could you give me some tips/thought to find it?

**Comment by EilyYa** [comment]
only the name is random text， the document content is correct

**Comment by SheetJSDev** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=373182#c64

> I'm guessing that the web page and the download are on different origins. We no longer honor the download attribute suggested filename for cross origin requests. Clicking on the link still initiates a download. But the the filename is only derived from factors solely dependent on the server (e.g. Content-Disposition header in the response and the URL).

The download logic depends on the browser APIs, so the best recommendations are:

A) raise an issue in the chromium bug tracker.

B) consider doing the export on the server side.

**Comment by EilyYa** [comment]
the filename is provided by frontend, I also think it may be a bug of the chrome.  Thank you for helping
