### ISSUE TITLE
Getting error, cannot access "stream.readable" when trying to upgrade node version of a project that uses xlsx package

### ISSUE THREAD

**Issue by gvg356** [SheetJS/sheetjs#2765]
The error is: uncaught error: module "stream" has been externalized for browser compatibility. cannot access "stream.readable" in client code.

**Comment by SheetJSDev** [comment]
https://github.com/vitejs/vite/issues/5963 suggests Vite is at fault.

Over the years, a number of settings have been added to `package.json` to satiate Webpack.  Vite has its own required settings .  After adding import maps #2744 (thanks @BrianHung ) Vite understands the library.

We tested 0.18.10 in a small Vite project https://docs.sheetjs.com/docs/getting-started/demos/bundler#vite , so upgrading is the recommended option.

**Comment by maxrks** [comment]
Install packages:

```
"stream-browserify": "^3.0.0",
"util-ex": "^2.1.0",

```
set resolve alias in vite.config

```
const alias: Record<string, string> = {
...
  vm: "vm-browserify",
  util: "util-ex"
};


resolve: {
      alias
    },
```
