### ISSUE TITLE
Zooming disabled

### ISSUE THREAD

**Issue by Adebayojosephine** [SheetJS/sheetjs#2768]
I tried to analyze your website using Lighthouse and I realized out that [user-scalable="no"] is used in the <meta name="viewport"> element which is problematic for users with low vision who rely on screen magnification to properly see the contents of a web page. I'd like to fix this.

![Screenshot (1)](https://user-images.githubusercontent.com/68714280/184637191-1f9941ac-cfec-4bf3-95e6-308721e912f1.png)

**Comment by SheetJSDev** [comment]
At some point the entire site will be rewritten.  For now, that meta attribute was removed.
