### ISSUE TITLE
Wrong quantity of columns and rows

### ISSUE THREAD

**Issue by billcunha** [SheetJS/sheetjs#2769]
Hi!
I'm using the `aoa_to_sheet` util with a tiny array 2x2, but I'm receiving a sheet with 5 columns and 10 rows. To test, I use the [`Complete Example`](https://docs.sheetjs.com/docs/example#clean-up-workbook) , exactly same code, and faced the same issue.
How I can solve this?
Thanks :)

**Comment by SheetJSDev** [comment]
The number of rows and columns are determined by the size of the data and the specified `origin` parameter.  If you can share the data (`console.log(aoa)`) and the actual call that generates the worksheet, we can take a closer look.
