### ISSUE TITLE
表格的样式没有保留啊

### ISSUE THREAD

**Issue by FaintWind** [SheetJS/sheetjs#2775]
没有哪位大佬，能优化下，让导入导出的样式能保留住。。。

**Comment by SheetJSDev** [comment]
Styling is not currently supported.  We expect to add styling after data reading and writing.

In the interim, https://sheetjs.com/pro

**Comment by FaintWind** [comment]
Thanks

**Comment by ArmedBone** [comment]
bro,look this https://www.npmjs.com/package/xlsx-js-style?activeTab=readme

**Comment by changbb** [comment]
你最后怎么解决的
