### ISSUE TITLE
The generated xlsx document fails to be sorted in data - > excel 2016

### ISSUE THREAD

**Issue by fengluoX** [SheetJS/sheetjs#2778]
https://codesandbox.io/s/wild-sunset-plbs8i?file=/src/App.tsx
Use Excel data - > column - > separator symbol - > other，input '.' , click finish, excel will be stuck and forced to close

**Comment by fengluoX** [comment]
I am normal in Excel 2019. Is it incompatible with the old version

**Comment by SheetJSDev** [comment]
Testing that file in Excel 2016 (the version before 365) and in Excel 2007 (the first version to support XLSX), we can't reproduce the issue.  What version of Excel are you using and do you see the same issue if you create a file manually?  If you can create a file by hand with the same content and text to columns doesn't freeze, please share the file.

Here's a replay from excel 2016:

https://user-images.githubusercontent.com/6070939/187982736-0b9185dc-d1aa-48fe-87c1-fd08b9c2563b.mov

**Comment by SheetJSDev** [comment]
If you can share the affected Excel version we can take a closer look and reopen the issue.
