### ISSUE TITLE
Per column date format possible?

### ISSUE THREAD

**Issue by dalisoft** [SheetJS/sheetjs#2780]
Hello and thanks for nice library.

It is possible different format dates for per column? Like this?

| User | Date_1 | Date_2 |
|-|-|-|
| User 1 | dd-mm-yyyy | mm-dd-yyyy |
| User 2 | dd-mm-yyyy | mm-dd-yyyy |

**Comment by SheetJSDev** [comment]
You can set formats on a cell level:

```js
var range = XLSX.utils.decode_range(ws["!ref"]);
for(var R = 1; R <= range.e.r; ++R) {
  if(ws["B" + (R+1)]) ws["B" + (R+1)].z = "dd-mm-yyyy";
  if(ws["C" + (R+1)]) ws["C" + (R+1)].z = "mm-dd-yyyy";
}
```

**Comment by dalisoft** [comment]
@SheetJSDev Thank you, it worked
