### ISSUE TITLE
Support for Excel Wrap Text

### ISSUE THREAD

**Issue by jamesderrick** [SheetJS/sheetjs#2786]
Is there any existing functionality to enable Wrap Text to an entire workbook, sheet or just some select columns?
I'm currently using the json_to_sheet function and have a few columns that'd benefit by having Excel's Wrap Text enabled by default.
If it is possible, an example would be much appreciated
If not then some advice on how I might add this functionality would also be great

**Comment by SheetJSDev** [comment]
Not currently.  Wrap Text is a cell style, and we do not plan to address styling in the Community Edition until we are reasonably happy with the state of data processing.

Until then, it and a bevy of advanced features are part of our Pro offering.
