### ISSUE TITLE
How to set classification (Unrestricted, Restricted, Confidential, Strictly Confidential)

### ISSUE THREAD

**Issue by Nikhilrj22** [SheetJS/sheetjs#2787]
Hi,

I have one requirement where I need to classify the document based on the data, I am exploring using this library how to set the excel with confidential type.

Any help would be appreciated.

Thanks
Nikhil

**Comment by SheetJSDev** [comment]
You're describing "Sensitivity Labels".  https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide starting point.

The whole feature is cloud-based and relies on Azure services.  There are no plans to add network requests to the library, so general support is out of the question.

According to the specs, it might suffice to set the Sensitivity property of the workbook to a specific GUID:

- Create a file with the desired setting (and if you can share it, that would be appreciated :)
- Go to https://jsfiddle.net/kna9L73j/ and use the file input element to select your file.  The props in the file will be displayed.  It runs in your browser (no data leaves your machine)
- If there is a "Sensitivity" key, copy the value into your worksheet before writing.  Assuming `wb` is your workbook:

```js
if(!wb.Props) wb.Props = {};
wb.Props.Sensitivity = "GUID_FROM_TEST_FILE"
// XLSX.writeFile ...
```

Please try that and let us know if it works.  If it does, we can update the docs.

**Comment by Nikhilrj22** [comment]
Thanks for your response. 

Currently I am giving 

wb.Custprops.Sensitivity = "Confidential";

with this setting, downloaded file is always opening in protected mode. I need to set this as confidential.

Could you please help me, what GUID I should set to make the file as Confidential.

Thanks
Nikhil

**Comment by SheetJSDev** [comment]
According to the documentation, sensitivity labels requires Azure as well as specific enterprise versions of Excel (it is disabled in our instances).  So the best we can realistically do without requiring network access is to pull properties from existing files and use them in new ones.
 
**Create a new file in Excel** with the Confidential sensitivity.  Then you can share it here OR use https://jsfiddle.net/vocLhaek/ (this version prints all of the normal properties and custom properties)

According to the spec, there may be a Sensitivity property which may be a GUID.

**Comment by SheetJSDev** [comment]
If you can share a sample file, we can take a closer look and reopen the issue.
