### ISSUE TITLE
Is there an xlsx method which could convert all numbers stored as text to numbers.

### ISSUE THREAD

**Issue by jithinb68** [SheetJS/sheetjs#2792]
Currently its in xlsx format. Numbers stored as strings. Numbers stored as strings prevents it from computations be done on it. Is there a way to achieve ? Found some details in this issue - https://github.com/SheetJS/sheetjs/issues/1166, I assume we can't do this keeping the format in xlsx. But wanted to know if we could convert the xlsx to some other format like ( csv ) and do the parsing and convert back to xlsx

<img width="612" alt="image" src="https://user-images.githubusercontent.com/65081177/190321182-488157e1-9e8a-42bc-8375-34f5bc12f25d.png">

**Comment by SheetJSDev** [comment]
If the original file had strings then SheetJS will store strings.  If the original file had numbers, SheetJS will store numbers.

If you want to effectively re-parse, you should be able to write each worksheet to CSV and re-parse:

```js
const new_workbook = XLSX.utils.book_new();
workbook.SheetNames.forEach(name => {
  const csv = XLSX.utils.sheet_to_csv(workbook.Sheets[name]);
  const wb = XLSX.read(csv, {type: "string"});
  XLSX.utils.book_append_sheet(new_worksheet, wb.Sheets.Sheet1, name);
});
```
