### ISSUE TITLE
The cells are pictures?

### ISSUE THREAD

**Issue by tangwentao2020514** [SheetJS/sheetjs#2794]
May I ask how to handle the cell is a picture?

**Comment by SheetJSDev** [comment]
Arbitrary pictures in cells are not currently supported.  The main focus is correctly reading and writing data from spreadsheets, leading up to v1.0.  We expect to address images after styling (so likely in the v2-v3 range).

In the interim, [SheetJS Pro](https://sheetjs.com/pro) offers some solutions.
