### ISSUE TITLE
Error appears in bower js-xlsx#~0.11.5

### ISSUE THREAD

**Issue by slfan1989** [SheetJS/sheetjs#2800]
This happens when compiling the project, I found that all tags are gone.

[INFO] bower js-xlsx#~0.11.5                 ENORESTARGET No tag found that was able to satisfy ~0.11.5
[INFO] 
[INFO] Additional error details:
[INFO] No versions found in https://github.com/SheetJS/js-xlsx.git

**Comment by SheetJSDev** [comment]
Sincere apologies for the disruption.  We pushed the tags from a clone on another machine -- please let us know if it is working

**Comment by slfan1989** [comment]
> Sincere apologies for the disruption. We pushed the tags from a clone on another machine -- please let us know if it is working

Thank you very much for your answer.

**Comment by SheetJSDev** [comment]
Both `npx bower install js-xlsx` and `npx bower install js-xlsx#~0.11.5` appear to work locally:

```
% npx bower install js-xlsx#~0.11.5
bower not-cached    https://github.com/SheetJS/js-xlsx.git#~0.11.5
bower resolve       https://github.com/SheetJS/js-xlsx.git#~0.11.5
bower download      https://github.com/SheetJS/js-xlsx/archive/v0.11.19.tar.gz
bower extract       js-xlsx#~0.11.5 archive.tar.gz
bower invalid-meta  for:/var/folders/n5/ds0gdqyj6fj1n_njgj9lbw1c0000gn/T/sheetjs/bower/8d63ef64e2b12f5b0d8616fa7e1b8597-38020-cfB5JW/bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower resolved      https://github.com/SheetJS/js-xlsx.git#0.11.19
bower install       js-xlsx#0.11.19
```

Please test again with your build sequence and reopen the issue if it still occurs.

**Comment by slfan1989** [comment]
> Both `npx bower install js-xlsx` and `npx bower install js-xlsx#~0.11.5` appear to work locally:
> 
> ```
> % npx bower install js-xlsx#~0.11.5
> bower not-cached    https://github.com/SheetJS/js-xlsx.git#~0.11.5
> bower resolve       https://github.com/SheetJS/js-xlsx.git#~0.11.5
> bower download      https://github.com/SheetJS/js-xlsx/archive/v0.11.19.tar.gz
> bower extract       js-xlsx#~0.11.5 archive.tar.gz
> bower invalid-meta  for:/var/folders/n5/ds0gdqyj6fj1n_njgj9lbw1c0000gn/T/sheetjs/bower/8d63ef64e2b12f5b0d8616fa7e1b8597-38020-cfB5JW/bower.json
> bower invalid-meta  The "main" field cannot contain minified files
> bower resolved      https://github.com/SheetJS/js-xlsx.git#0.11.19
> bower install       js-xlsx#0.11.19
> 
> js-xlsx#0.11.19 bower_components/js-xlsx
> ```
> 
> Please test again with your build sequence and reopen the issue if you are still seeing build problems.

Thanks for the quick fix.
