### ISSUE TITLE
Wrong filename when download file

### ISSUE THREAD

**Issue by thunerfisch** [SheetJS/sheetjs#2806]
Hello,
I have a problem with the download name of a file. I use following code to trigger the download of an excel file:
XLSX.writeFile(wb, fileNameWithExt);
But for some users the function don't uses the paramater fileNameWithExt it uses a random GUID:
![image](https://user-images.githubusercontent.com/25151737/195341200-34a06746-b0a4-4ffe-a5ff-41819e4863bf.png)
How i can fix this problem? Is there something i can check? fileNameWithExt is set to the correct filename.

**Comment by SheetJSDev** [comment]
See https://github.com/SheetJS/sheetjs/issues/2759
