### ISSUE TITLE
No option to change delimiter when writing CSV

### ISSUE THREAD

**Issue by MasterMT9** [SheetJS/sheetjs#2817]
As of now, there is no option to deviate from the standard CSV-Format. Im trying to parse XLSX to CSV.
As I work with CSVs that use semicolons as the delimiter and have some values that contain commas I cant just mass replace them. Would be quite helpful to have the option to change delimiters when exporting.

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/docs/api/utilities#delimiter-separated-output `FS` controls the field separator.

In the future, please use our modern issue tracker https://git.sheetjs.com/sheetjs/sheetjs/issues
