### ISSUE TITLE
Issue with custom formats containing '"' (Literal Text)

### ISSUE THREAD

**Issue by ericyanush** [SheetJS/sheetjs#29]
I began testing your awesome library against a set of excel files that I am working with for a project, and found that I had a few that would case the browser to hang.

The custom format string is: "$"#,##0.00;("$"#,##0.00)

The problem seems to be in eval_fmt() in case '"'.

The script gets caught in the for loop in there infinitely, with the index var getting incremented far beyond the length of the fmt string, until the browser has deemed the script is hung and kills it.

**Comment by jayeshanandani** [comment]
@SheetJSDev : I can still experience the same. I have a custom date format but some cells didnt had that format and had `'` sign in front of them and it got stuck in infinite loop.
