### ISSUE TITLE
Page breaks

### ISSUE THREAD

**Issue by ashleyschuett** [SheetJS/sheetjs#320]
Hey I'm looking to force a page breaks for printing in the excel sheet, is there a way to do that with js-xlsx?

**Comment by santiagovazquez** [comment]
Same thing here, anyone ?

**Comment by chamnap** [comment]
Anyone please?

**Comment by SheetJSDev** [comment]
Page breaks and general print settings are a feature of our [Pro builds](https://sheetjs.com/pro).  It may be added here at some point.
