### ISSUE TITLE
Error: Corrupted zip : can't find end of central directory

### ISSUE THREAD

**Issue by remotevision** [SheetJS/sheetjs#35]
**EDIT**: if you encounter this issue, confirm you are using the latest version and that you are using the correct input type!  See https://github.com/sheetjs/sheetjs#input-type

For example, using a `FileReader` with `readAsArrayBuffer` will call the load event where the result is an `ArrayBuffer`, so `type` should be `"array"`

If data is received through an XHR or fetch, verify that the source data is not UTF8-encoded.  Some platforms like AWS Gateway API do this automatically [and require an override as explained in the `function` demo](https://github.com/SheetJS/sheetjs/tree/master/demos/function#aws-lambda)

--

I am trying to use this library to parse a base64 encoded .xslx file on the server using node.js. I have also removing the base64 header info and loading the data into a binary buffer, but I get the same error.

Here is my function to parse the file:

```
var parseFile = function(data){
  var xlsx = XLSX.read(data, {type: 'base64'});
  var sheet_name_list = xlsx.SheetNames;
  xlsx.SheetNames.forEach(function(y) {
    for (z in xlsx.Sheets[y]) {
      if(z[0] === '!') continue;
      console.log(y + "!" + z + "=" + JSON.stringify(xlsx.Sheets[y][z].v));
    }
  });
};
```

However, when I try to parse the data, I get the following error. 

```
Error: Corrupted zip : can't find end of central directory
        at Object.ZipEntries.readEndOfCentral (/Users/.../node_modules/xlsx/jszip.js:2087:27)
        at Object.ZipEntries.load (/Users/.../node_modules/xlsx/jszip.js:2104:18)
        at Object.ZipEntries (/Users/.../node_modules/xlsx/jszip.js:2010:18)
        at Object.JSZip.load (/Users/.../node_modules/xlsx/jszip.js:2115:22)
        at Object.JSZip (/Users/.../node_modules/xlsx/jszip.js:5:14)
        at Object.readSync [as read] (/Users/.../node_modules/xlsx/xlsx.js:940:24)
        at parseFile (/Users/.../routes/tickets.js:35:19)
```

any thoughts as to why this might be happening? When I load my file into your demo site, it parses it to json just fine.

**Comment by cristiandley** [comment]
Im having the same issue trying to parse a .xls file. It Promt

```bash
Error: Corrupted zip : can't find end of central directory
```

I download the file from a website made on .net (aspx)

**Comment by fitnr** [comment]
I'm getting this with xlsx@0.7.12 in node versions 0.12.4 and 4.2.1: `Error: Corrupted zip : can't find end of central directory`

The file I'm getting the error with is here: http://www1.nyc.gov/assets/finance/downloads/pdf/rolling_sales/neighborhood_sales/staten_island_sales_prices.xls

The file is binary, and works fine in Excel.

**Comment by stasyaner** [comment]
I'm getting this with xlsx with dates

**Comment by Raghavendra22g** [comment]
Hi I was also facing similar issue, while importing .xlsx file "Error: Corrupted zip : can't find end of central directory" .. I tried following which solved the issue. ''result'' is the file input and truncate the format. 
 var data = result.toString().replace("data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,", "");
            data = data.toString().replace("data:text/xlsx;base64,", "");
          $window.xlsx(data);  // call the library now..

Since I used excel-builder.js to generate the file. I modified some part xlsx.js library to element styling.

Its working for me well .
Thank You

**Comment by shankararul** [comment]
anybody has a proper fix for this ? Any chance we could reopen this ticket ?

**Comment by cicerohen** [comment]
@shankararul I'm having the same problem.

**Comment by shankararul** [comment]
Hey @cicerohen, i kind of figured out a workaround in this error - http://stackoverflow.com/a/36261090/786326 (Hope it helps)

**Comment by cicerohen** [comment]
@shankarul  this error occurred for me why in my function I tried execute readFile(filePath) before the readStream(filePath) end.

**Comment by Mwaiwathu** [comment]
I have a similar issue but with parsing docx... Passing the same path by one method ie a string creates the error whilst using another drag drop API  works weird

**Comment by SheetJSDev** [comment]
The input type has to match the specified type, as explained in the [input type table](https://github.com/sheetjs/js-xlsx#input-type).

**Comment by FlyerJay** [comment]
i have got the same issue ,Corrupted zip : can't find end of central directory 
im sure this file can open with ms excel

**Comment by SheetJSDev** [comment]
@FlyerJay if you can reproduce the issue [in the live demo](http://oss.sheetjs.com/js-xlsx/) then it's a bug in the parsing logic and we would love to see an offending file.  You can email it to us or attach to a reply here.

If you cannot reproduce the issue in the demo, then there's an issue in your integration code and we would need to see a code snippet to advise further.

**Comment by FlyerJay** [comment]
[error.xlsx](https://github.com/SheetJS/js-xlsx/files/939994/error.xlsx)

**Comment by SheetJSDev** [comment]
@FlyerJay http://oss.sheetjs.com/js-xlsx/ reads the file: 

<img width="711" alt="screen shot 2017-04-20 at 00 01 02" src="https://cloud.githubusercontent.com/assets/6070939/25213177/c91d6bde-255c-11e7-921b-dd3609ef9f50.png">

This is the full output: https://hastebin.com/zopiresadu.http

My guess is that you are either using an older version or your integration code is not correct.  Can you check if the version is 0.9.11? `console.log(XLSX.version)` somewhere in your code

**Comment by FlyerJay** [comment]
thank you！！i know where the problem is

**Comment by jeevanhr7** [comment]
i am also facing the same issue

**Comment by bennettluo** [comment]
@SheetJSDev Hey, I still have the same issue while reading extremely large excel **(over than 20Mb, xlsx)**, I tried to use node stream to handle each chunk because it cannot figure out the sheet results by using **XLSX.readFile** directly, but it doens't work for that. Could you give me some advices?

**Comment by PedramMarandi** [comment]
After 6 years there is no solution to this problem 👯 
I'm facing with the same issue, I'm trying to read Buffer but I  get the below exception 

```Error: Corrupted zip : can't find end of central directory",
            "    at ZipEntries.readEndOfCentral (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/jszip.js:2281:19)",
            "    at ZipEntries.load (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/jszip.js:2343:14)",
            "    at new ZipEntries (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/jszip.js:2167:14)",
            "    at JSZipSync.module.exports [as load] (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/jszip.js:580:18)",
            "    at new JSZipSync (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/jszip.js:527:14)",
            "    at read_zip (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/xlsx.js:20267:24)",
            "    at Object.readSync [as read] (/Users/pedromarandi/projects/replenishment/node_modules/xlsx/xlsx.js:20335:69)",
            "    at read (/Users/pedromarandi/projects/replenishment/src/lib/sheetUtils.js:23:15)",
            "    at _callee$ (/Users/pedromarandi/projects/replenishment/src/lib/validations/validatePurchaseOrderFile.js:28:21)",
            "    at tryCatch (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)",
            "    at Generator.invoke [as _invoke] (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)",
            "    at Generator.prototype.(anonymous function) [as next] (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)",
            "    at asyncGeneratorStep (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)",
            "    at _next (/Users/pedromarandi/projects/replenishment/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"```

**Comment by hlynurl** [comment]
I am having this problem. I cannot read any excel files from buffers anymore.

**Comment by SheetJSDev** [comment]
@PedramMarandi @hlynurl at this point it's most likely a corruption issue somewhere else.  To check:
- Write the buffer to file and see if you can open it in Excel
- actually log Buffer.isBuffer(data) and confirm you are dealing with a buffer

**Comment by hlynurl** [comment]
@SheetJSDev thank you for your advice. 

I have confirmed I am dealing with a buffer. This is not something that happened while writing new code. This is all of a sudden happening in my codebase which worked fine before on the exact same files. I even have an app in production working fine which was deployed from my last commit but if I clear all changes and revert back to that commit this still happens.

 - I suspect this has something to do with .DS_Store files on my mac so I have tried to delete them but this is still happening. 
 - I have tried to remove all node modules and re-install few times.
- ... do you have any other ideas?

**Comment by mwangiKibui** [comment]
i solved mine by changing the editor

**Comment by bertrandmartel** [comment]
For me I had the same error when the input file was protected by a password

**Comment by hutao96** [comment]
can not work with xlsx,  just xls can be use
Error: Corrupted zip : can't find end of central directory
    at u.readEndOfCentral (xlsx.core.min.js:2)
    at u.load (xlsx.core.min.js:2)
    at new u (xlsx.core.min.js:2)
    at n.r.exports [as load] (xlsx.core.min.js:2)
    at new n (xlsx.core.min.js:2)

**Comment by SheetJSDev** [comment]
@hutao96 please raise a new issue and include some details like the actual read call and how the data is obtained
