### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by ghost** [SheetJS/sheetjs#40]
I have a rather big spreadsheet. 1MB with almost 15,000 rows.

Importing it will give me this "Maximum call stack size exceeded" error.
I tried and noticed that the error no longer occurs when the rows are reduced to 1,000.

Is there a solution? :)

**Comment by tjvg91** [comment]
Hi guys.

I get the same error but i don't quite understand the solution. This is my code:

```
reader.onload = function(e) {
            var data = e.target.result;
            var wb = XLSX.read(data, {type: 'base64'});
        };
        reader.readAsArrayBuffer(f);
```

Please help. Thanks

**Comment by tjvg91** [comment]
Correction:
```
reader.onload = function(e) {
            var data = e.target.result;
            var arr = String.fromCharCode.apply(null, new Uint8array(res));
            var wb = XLSX.read(arr, {type: 'base64'});
        };
        reader.readAsArrayBuffer(f);
```
