### ISSUE TITLE
How to Write the Xlsx template

### ISSUE THREAD

**Issue by jeevanhr7** [SheetJS/sheetjs#428]
I have the simple Template I want to start to Write the data from the 3 rd Column.any body help me on this
`var testingworkbook =  XLSX.readFile('./app/testingTemplate.xlsx',{cellStyles:true});
var workSheet1 = sheet_from_array_of_arrays(potencySheetData);
var workSheet2 = sheet_from_array_of_arrays(contaminantSheetData);`
I want to start to Write the data  from the 3rd row of the Template.

XLSX.writeFile(testingworkbook , 'Testdata.xlsx',{bookSST:true});

**Comment by David-Turbert** [comment]
this can help you https://gist.github.com/SheetJSDev/88a3ca3533adf389d13c

**Comment by SheetJSDev** [comment]
Under the hood, SheetJS tries to understand file format details.  For writing data to a template, ideally the library would surgically edit the file data blocks without disrupting anything else.  We offer this as part of our ["Pro Edit" build](https://sheetjs.com/pro).  It may eventually be added here after the v1.0.0 release
