### ISSUE TITLE
Excel named cell ?

### ISSUE THREAD

**Issue by ghost** [SheetJS/sheetjs#444]
Is it possible to get an Excel named cell ?

Currently, to access to cell A1, we use :
worksheet['A1']

In my case, I want to access to a cell which has a name as 'myNamedCell' as :
worksheet['myNamedCell']

But it does not work. It returns undefined.

Is there another way to get a named cell ?

**Comment by SheetJSDev** [comment]
Defined names are extracted, [as explained in the docs](https://docs.sheetjs.com/#defined-names)

You can walk that array to find the range for a given defined name, then walk the worksheet to get the individual cells

**Comment by amirhosseinlookcle** [comment]
Hi
How can I walk the worksheet with the format given in the object of defined names; the "ref" is written this way "Ref: 'Sheet1!$E$3:$E$5'" and I do not know how to convert it to a format to be read and even how to read it.
Thanks
