### ISSUE TITLE
Read/Write indents in a cell with text

### ISSUE THREAD

**Issue by scottnc27603** [SheetJS/sheetjs#450]
I have some text value cells that are using the indent feature to imply parenting for nodes.  Is there a way to read and write the indentations?  This is an absolute must for being able to use this library.  If this isn't a current feature, could someone point me to the code so that I might add this feature.  I tried adding the 'cellStyles' option for the read, but that didn't change the cell's 's' value.

Thanks,
Scott

**Comment by scottnc27603** [comment]
I found the function that is dropping the indent values.  It's in parse_cellXfs under the alignment tag.  If I add this feature then will you guys accept a PR?  I'm still not sure about the writing out of the xlsx files, but at least I could fix the reading.

**Comment by SheetJSDev** [comment]
If you have a sample file we can take a look and figure out the best approach.

**Comment by TimMurnaghan** [comment]
Any update on this? I too have to read a sheet using indenting to show parents.

**Comment by davidgbarbero** [comment]
Any update on this? I'm trying to indent the cells from an html table. Is that possible? Thanks in advance

**Comment by mebassett** [comment]
Any update on this?  We are also running into this.

**Comment by SheetJSDev** [comment]
Cell indents and other cell styling features are covered in our [Pro builds](https://sheetjs.com/pro).  We cannot say when they will be merged here, but it will be after v1.0.0
