### ISSUE TITLE
Is there a way to use Excel's 'Protect Worksheet' and/or 'Protect Workbook' options?

### ISSUE THREAD

**Issue by jeevanjose** [SheetJS/sheetjs#457]
Hey,

Thanks for the awesome work on this library.

I was wondering if you could password protect worksheets and/or workbooks with this library. Or if there was an alternate way which could stop users from being able to modify the structural integrity of an xlsx document?

**Comment by AlexanderKozhevin** [comment]
👍

**Comment by SheetJSDev** [comment]
The protect worksheet options are exposed in the worksheet `!protect` key, as explained in https://github.com/sheetjs/js-xlsx#worksheet-object .

The protect workbook option is not currently read or saved.  However, if you are feeling adventurous, it's not difficult to add in!

The workbook protection info is stored in a workbookProtection tag.  On the write side, it should be placed [in the position of the workbookProtection comment](https://github.com/SheetJS/js-xlsx/blob/master/bits/72_wbxml.js#L168).

To stop users from modifying the structure of the workbook, it would suffice to add something like:

```js
o[o.length] = writextag('workbookProtection', null, {lockStructure:"1", workbookPassword:crypto_CreatePasswordVerifier_Method1(password).toString(16).toUpperCase()});
```

where `password` is the password string.

If you would like to send a PR, consider adding a `!protect` key to the workbook similar to the sheet object.

**Comment by SheetJSDev** [comment]
[Protect Worksheet is documented](https://github.com/SheetJS/sheetjs#worksheet-object) while [Protect Workbook will require a Pro build](https://sheetjs.com/pro)
