### ISSUE TITLE
How Can I Lock Cells in the excel

### ISSUE THREAD

**Issue by anil-talla** [SheetJS/sheetjs#483]
Hi,

I need to lock cell first row and first column of the excel.  Can I achieve this. Is there any way to lock the cell.

**Comment by CodeMorrow** [comment]
Any upadte on this issue?

**Comment by tanvi-inttra** [comment]
any update on this issue?

**Comment by daggett206** [comment]
ping

**Comment by tanakorn-mint** [comment]
Has it been any update?

**Comment by jalleng** [comment]
Any update on this?

**Comment by ebra100** [comment]
did u know it ?

**Comment by nakshay** [comment]
I need this feature, is it added yet?

**Comment by SheetJSDev** [comment]
Cell protection and other styling are part of our [Pro builds](https://sheetjs.com/pro)
