### ISSUE TITLE
Blank cells are ignored.

### ISSUE THREAD

**Issue by ghost** [SheetJS/sheetjs#50]
Blank cells in rows ['value1', ' ', 'value3'] are parsed into an object that does not recognize the blank cell: { A1: {}, C1: {} }

Is this the intended behavior? 

If it is, it would be nice to have an option that would include blank cells in the output from .readFile().Sheets.

If it is not, is there a way to read blank cells as well?

Thanks

**Comment by hmnshmshr** [comment]
Solution 1 .Condition "if(h===undefined)continue;"  in  "xlsx.core.min.js" comment it out.

 or do it properly...  

Solution 2 . By passing Condition extra param while running this XLSX.utils.sheet_to_json(wb.Sheets[name] , {blankCell : false}). add a condition on line no. 19150   "if(defval === undefined && blankCell) continue;" in file xlsx.js etc..

**Comment by ashishdutta007** [comment]
I tried with XLSX.utils.sheet_to_json(wb.Sheets[name] , {blankCell : false}) but i am still getting blank values for the empty cell

**Comment by hmnshmshr** [comment]
Solution 1 .Condition "if(h===undefined)continue;" in "xlsx.core.min.js"
comment it out.
 add a condition on line no. 19150 "if(defval === undefined && blankCell)
continue;" in file xlsx.js etc..

Himanshu Mishra
Aiims Jodhpur

**Comment by UI5Training** [comment]
Hi,

Did any of you able to find its solution?
I am facing the same problem.

**Comment by YesicaMacias14** [comment]
Hi, did any one know some way to insert that data into a table?. The issue is I already catch the info from my excel file but I want to see it on my web side and insert them on a table in my database.

**Comment by GaneshSinghPapola** [comment]
anyone find  the solution?

**Comment by backstab319** [comment]
> anyone find the solution?

You can use the defval: "" option while reading a doc, and it will work.

`
xlsx.utils.sheet_to_json(
      workbook.Sheets[workbook.SheetNames[0]], {
        defval: ""
      });
`
Like this, hope it helps.
