### ISSUE TITLE
hyperlink

### ISSUE THREAD

**Issue by sysarchitect** [SheetJS/sheetjs#55]
Hello,

When parsing hyperlink cell, is returns cell text but not URL itself if URL is the property of link.
Is it possible to determine if cell contains URL as property and return true link?

Thank you.

**Comment by gangadharjannu** [comment]
Do we need to pass any additional parameters while parsing `hyperlinks` in a column ? I'm using `XLSX.utils.sheets_to_json(workbook_sheet,{header:1});`

**Comment by jtheletter** [comment]
> @sysarchitect to clarify, the url (if a link is generated) is at `cell.l.Target` . The tooltip text is available at `cell.l.tooltip`.

How do we access the cell’s hyperlink when converting spreadsheets to json in the cli?
