### ISSUE TITLE
XLSM workbook password protection does not work

### ISSUE THREAD

**Issue by rmaddikunta** [SheetJS/sheetjs#57]
Hi,

I thought its a great find for me reading the specs and a few samples. However, when I try dropping a XLSM file it does not work and not even show if there is any problem in processing the file. I have protected sheets, and macros in the file. 

Thanks,
Ramana.

**Comment by AnujaDeshpande** [comment]
Hello, 
I need to read the XLSB file where sheets are password protected to secure some formulas, How to use this password parsing options. Please guide me.

I am  also facing the Firefox memory issue, where it is showing as script is taking long time to execute. Is there any way to resolve this issue.
Thanks in advance.
