### ISSUE TITLE
In windows, line breaking not work.

### ISSUE THREAD

**Issue by shikelong** [SheetJS/sheetjs#689]
I insert \r\n in cell value. But The line breaking only work after I click the edit input or double click the cell.

How to mark line breaking work in windows ?

```javascript

const wbout = XLSX.write(workbook, {bookType: 'xlsx', bookSST: true, type: 'binary'});
  const wblob = new Blob([s2ab(wbout)], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});

```

![gif](https://user-images.githubusercontent.com/4499997/27113724-3cf31c92-50f1-11e7-9691-c4d691145c58.gif)

**Comment by NemoAlex** [comment]
Why closed? I met the same issue.
Did you figured out?

**Comment by shikelong** [comment]
@NemoAlex 

refer: https://github.com/protobi/js-xlsx/issues/73

**Comment by mdissel** [comment]
Any progress on this issue?

**Comment by SheetJSDev** [comment]
Forcing a line break to properly render requires setting a style flag which is currently only supported in our [Pro builds](https://sheetjs.com/pro)
