### ISSUE TITLE
Read the specified sheet from the file

### ISSUE THREAD

**Issue by xxScorpion** [SheetJS/sheetjs#704]
I can read only the list of sheet names. How can I load data from this sheet only by not loading the entire file?

**Comment by SheetJSDev** [comment]
Currently there is no such option (you have to read the entire book), but that would be a nice feature if you knew in advance what sheet you wanted.

Out of curiosity, what would happen if the workbook didn't have the specified sheet?  Throw an error? Return an empty workbook?

**Comment by xxScorpion** [comment]
An empty book will also be arranged.
I planned two passes.
1.Get list of available worksheets
2.If there is a need, then download ...

**Comment by reviewher** [comment]
[`sheets` option](https://docs.sheetjs.com/) can take one or more indices or names:

```typescript
    /** If specified, only parse the specified sheets or sheet names */
    sheets?: number | string | Array<number | string>;
```
