### ISSUE TITLE
table_to_book parsing currency as date

### ISSUE THREAD

**Issue by vhfmag** [SheetJS/sheetjs#788]
Hello,

I'm currently working on a dashboard where all data tables have a download button, and I'm using `utils.table_to_book` for that. So I was testing around when I noticed that, for some reason, the string 'R$45,05' (pt-br for US$45.05) is consistently parsed as the date 5/1/2045 (May 1st, 2045 - more specifically, there's the cell object: `{t: "n", v: 53083, z: "m/d/yy"}`). Any thoughts or workarounds?

Thanks in advance!

**Comment by reviewher** [comment]
There's currently no support for the `pt_BR` or any other locale (other than `en_US`).  The immediate workaround is setting the option `raw:true` which will disable all value parsing.

**Comment by SheetJSDev** [comment]
This is due to V8 (node/chrome) date parsing flexibility.  Closing in favor of https://github.com/SheetJS/sheetjs/issues/2196
