### ISSUE TITLE
Required All cells read-only except one column in Excel.

### ISSUE THREAD

**Issue by rajeshnbhat** [SheetJS/sheetjs#805]
We are generating an excel sheet using SheetJS JavaScript API of which all cells are read-only except for one columns. So we want that while a user downloads it the excel file should be editable only for one column rest all cells should be read-only.

So kindly suggest some solution for us.

Technology Stack – Angular 4 with SheetJS as plugin.

**Comment by SheetJSDev** [comment]
Cell protection is a form of styling which we offer in our [Pro builds](https://sheetjs.com/pro)
