### ISSUE TITLE
Improve documentation regarding !ref

### ISSUE THREAD

**Issue by lszhu** [SheetJS/sheetjs#82]
when I create a sheet with 49 columns, it can only fill the first 20000 rows.
this is the code:

```
var xlsx = require('xlsx');
var workbook = xlsx.readFile('template.xlsx');

var alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
var sheet = workbook.Sheets[workbook.SheetNames[0]];
//console.log(sheet.A1.v);
console.log(new Date());
for (var i = 2; i < 100000; i++) {
    for (var j = 0; j < 26; j++) {
        var str = Math.floor(Math.random() * 1E+10).toString();
        str += Math.floor(Math.random() * 1E+10).toString();
        sheet[alpha[j] + i] = {v: str, t: 's'};
    }
    for (; j < 49; j++) {
        var str = Math.floor(Math.random() * 1E+10).toString();
        str += Math.floor(Math.random() * 1E+10).toString();
        sheet['A' + alpha[j - 26] + i] = {v: str, t: 's'};
    }
}
xlsx.writeFile(workbook, 'rand.xlsx');
console.log(new Date());
```

**Comment by vikash52** [comment]
I am trying to convert html table to xls and its getting converted to xsl successfully. However, I am facing issues with formula. Formula in the html table is not visible in xsl file, I just see a value at the place of formula.

Refering this example https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js , it doesn't have any implementation for cell formula in xlsx spreadsheet I tried using cell.f = "=SUM(A1+B1)" for the cell C1 and cell.v as the summation value which was 3. But i didn't succeed. With the exported file, when opened in MS excel, the cell contained just the data and when selected, didn't show any formula which i assigned in f(x) field.

Can someone post me a example which actually uses the functions/property '.f' and 'cellFormula'
Will be very helpful. I just need a working example with static values.

**Comment by aboodh95** [comment]
@vikash52  did you solve the issue or find a way to solve it

**Comment by Crusader4Christ** [comment]
@SheetJSDev
Sorry, but I can't understand this line:
`sheet['!ref'] = "A1:AW100000"; // <-- i added this line to force it to write all of the cells
`
How did you get last range "AW100000"?

**Comment by reviewher** [comment]
@Crusader4Christ AW100000 is the cell in the 49th column and 100000th row:

```js
> XLSX.utils.decode_range("A1:AW100000")
{ s: { c: 0, r: 0 }, e: { c: 48, r: 99999 } }
```

The original case from @lszhu used 100k rows and 49 columns, but since the original file specified a range of 20000 cells the rest were omitted.

The range needs to be changed since the writer won't include cells outside of the worksheet's range.  The wiki includes some examples of how to update the range: https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions

**Comment by Crusader4Christ** [comment]
@reviewher So, if I need to work with OO Calc xlsx bigger than 65536 rows I should use `update_sheet_range(ws)` from  https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions?

**Comment by reviewher** [comment]
@Crusader4Christ if you don't know the bottom-right address, `update_sheet_range(ws)` scans all of the addresses and fixes the worksheet.  That is not the most efficient approach but it works in general

If you do know that address, `add_to_sheet(ws, bottom_right_cell_address)` is more efficient:

```js
var nrows = 100000;
var ncols = 49;
var bottom_right_cell_address = XLSX.utils.encode_cell({r:nrows-1, c:ncols-1});
add_to_sheet(ws, bottom_right_cell_address);
```
