### ISSUE TITLE
Single instance of Quotation marks in a TSV format

### ISSUE THREAD

**Issue by zgriesinger** [SheetJS/sheetjs#825]
Hello! First I just wanted to thank you for this library, it is hugely powerful.

My issue: I am reading in a tab separated value file that is quite large, approximately 400,000 rows. In this tab separated value file I have a line that is as follows:
`text in col 1 \t text in col 2 \t this field is 4" \t text in col 3 \n`

If you look at the third column field it uses a single instance of a quotation mark to specify inches, and as far as I know the way that XLSX.js interprets this is to continue on, ignoring tabs, until you hit another quotation. In this case the next quotation is on the next line in the same column. Is there anyway to specify XLSX.js to just ignore the quotation specification? 

I think I can circumvent it by replacing the quotation with a specialized string and then replacing it again after I create and parse the outputted workbook.

Any help would be greatly appreciated!

**Comment by SheetJSDev** [comment]
The "correct" way to serialize a single `"` is to wrap the entire field in double quotes and double up where you expect the quotes to appear.  For example, the cell `this field is 4"` is technically supposed to be

```
"this field is 4"""
                ^^---- the pair is interpreted as a literal "
```

If you have control over the data source, the best approach is to fix the data source.

What's interesting in your case is the wildly different treatment of two seemingly similar files.  For example, adding a double-quote after the last tab in the first line:

```
text in col 1\ttext in col 2\tthis field is 4"\t"text in col 3
text in col 1\ttext in col 2\tthis field is 4"\ttext in col 3
```

Excel treats that file as if it had 5 columns and 1 row:

<img width="475" alt="" src="https://user-images.githubusercontent.com/6070939/30985709-18b0d588-a45f-11e7-918e-f37e127a9240.png">

Brass tacks: it's a bug, your stop-gap measure is how I would approach it too :)

**Comment by zgriesinger** [comment]
That's what I was afraid of. Thanks for the response. I'll just find a way to work around it.

Have a good one.

**Comment by SheetJSDev** [comment]
7a00f3986db482f3d9419485b9de82d11d4d9402
