### ISSUE TITLE
error of CRLF

### ISSUE THREAD

**Issue by trarck** [SheetJS/sheetjs#827]
The escapexml function parse "\r\n" to "_x000D_\n".
If I open the excel file with Microsoft Excel,then save it. "_x000D_\n" will be "_x000D_\r\n".
Then I read excel file use js-xlsx,the unescapexml parse "_x000D_\r\n" to "\r\r\n".

**Comment by SheetJSDev** [comment]
@trarck can you share some code to reproduce the issue?  Also, are you running in a web browser or nodejs or some other platform?

**Comment by SheetJSDev** [comment]
Format-specific escaping has been implemented on XLSX / SpreadsheetML / ODS.  Please reopen if this error persists.
