### ISSUE TITLE
Support for Older Browsers (IE8)

### ISSUE THREAD

**Issue by wintersm** [SheetJS/sheetjs#88]
I have been at it for a full day now with no luck, so I am turning to you(all) for help.

I am a mechanical engineer with an interest in coding.  I am trying to parse data from an excel spreadsheet.  Right now I don't think I care if it is XLS, XLSX, or XLSM.  My roadblock appears to be my browser.  I am working with IE8, running server-side Javascript.

Up until now, I was working with an excel file that automatically generated CSV files at Save, and I was using Javascript to parse the CSV files using XMLHttpRequest().  It seems you have eliminated the need to create extra CSV files.

So, to my point, I believe the fault is fully with me, but I was hoping you could help get my code working.  I recognize that IE8 does not support Uint8Array and I need some sort of workaround.  From what I can tell, you have already resolved this and I am just not implementing it correctly.  I think I need to be working with the Base64 format . . . but I have no idea how to do that.  As I understand it, jszip.js will do that for me and I just have to figure out how to do that.  I thought I read that the shim resolved this issue, but I still get (Uint8Array is underfined). 

Thanks for any help! 

Here is my code, which is really **your** code with paths to your libraries:

``` HTML
<doctype html>
<html>
<head>
</head>
<script lang="javascript" src="Include/shim.js"></script>
<script lang="javascript" src="https://github.com/SheetJS/js-xlsx/dist/xlsx.core.min.js"></script>

    <script>

    /* set up XMLHttpRequest */
    var url = "test.xlsx";
    var oReq = new XMLHttpRequest();
    oReq.open("GET", url, true);
        oReq.responseType = "arraybuffer";

    oReq.onreadystatechange = function(e) {
        var arraybuffer = oReq.response;

        /* convert data to binary string */
        var data = new Uint8Array(arraybuffer);
        var arr = new Array();
        for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
        var bstr = arr.join("");

        /* Call XLS */
        var workbook = XLS.read(bstr, {type:"binary"});

        /* DO SOMETHING WITH workbook HERE */
    }

    oReq.send();

    </script>
<body>
</body>
</html>
```

**Comment by coffeescriptdev** [comment]
Hi,
i am using sheetjs to convert excel files to json. Its working fine in chrome and firefox but not in ie8. Could any one help me in fixing this issue?
