### ISSUE TITLE
One column per row CSV file read as binary parsed into multiple columns

### ISSUE THREAD

**Issue by andreikun** [SheetJS/sheetjs#884]
Hello,

I am experiencing this weird issue when i try to upload locally a csv file using FileReader than use:

`let XSLX = require("xlsx"); let workbook = XLSX.read(data, {type : "binary"});`

So for a CSV like:

John Will Do
Will Smith Jon

with no comma separation there, which means only one column per row i get multiple columns if i inspect workbook object and i've got in some cases even more columns. From what i see the columns get parsed after 10 chars.

Any idea? Anyone got this weird error ?

**Comment by SheetJSDev** [comment]
Long story short: there's a really really old spreadsheet format known as ["Lotus Formatted Text" (extension PRN)](https://support.office.com/en-ie/article/Save-a-workbook-to-text-format-txt-or-csv-3E9A9D6C-70DA-4255-AA28-FCACF1F081E6). You'll find it in Excel 2016 for Windows as one of the possible output formats.  The default behavior, [as discussed in the docs](https://docs.sheetjs.com/#guessing-file-type), is to attempt PRN interpretation if there are no commas or tabs or semicolons in the first 1024 characters, but it's probably better to disable PRN guessing altogether

**Comment by andreikun** [comment]
So the library breaks the name into multiple columns due to this PRN interpretation?

In my case i created this CSV file either by saving it from Excel or with a plain text and rename it to CSV. Actually some clients reported that to me and I need an explanation and a fix for them as this is a really important use case. Should we ask that they need to create .xlsx files in this case? Seems to work saved as xlsx.

**Comment by bighandsam** [comment]
@SheetJSDev is it possible to disable PRN guessing using `read_opts` or something similar?

Some background: I deal with only CSV files and if I come across a file with only one column, is it possible to force xlsx.read(...) to process with CSV (as opposed to PRN)?

**Comment by SheetJSDev** [comment]
PRN parsing was disabled for this general case
