### ISSUE TITLE
Empty Sheets property with big Excel file (50MB)

### ISSUE THREAD

**Issue by devniel** [SheetJS/sheetjs#910]
Hello,

I'm trying to parse a xlsx file whose size is around 50MB, but the "Sheets" property returned when using the XLSX.readFile method is empty ({}).

Please, help me 😅

Thanks

**Comment by devnieL** [comment]
(in the meantime, I solved it by using https://github.com/ffalt/xlsx-extract)

**Comment by reviewher** [comment]
Closing in favor of #61
