### ISSUE TITLE
Pre formatting column names 

### ISSUE THREAD

**Issue by chathuraa** [SheetJS/sheetjs#94]
Hi,

Thanks for this great lib. Is it possible to pre format column names? ie. remove line breaks, spaces make camelcase. If not, where should i look in the source to implement this?

Thanks,
Chat.

**Comment by smatthews1999** [comment]
Thanks!  This is also exactly what I need.  In my case I am importing spreadsheets where the creators can name headers whatever they want, as long as they are positioned in the correct order.  This lets me replace their headers with my own and deal with them in a uniform manner.

**Comment by mkay581** [comment]
I second this feature! It is slated to be included in an upcoming version?
