### ISSUE TITLE
parsing ISO 8601 fails for first day of year e.g. "2018-01-01T00:00:00.000Z"

### ISSUE THREAD

**Issue by dominikg** [SheetJS/sheetjs#959]
var book = XLSX.read('date,no date\n"2018-01-02T00:00:00.000Z","2018-01-01T00:00:00.000Z"\n',{type: 'string',cellDates:true})

book.Sheets.Sheet1 is
{
  "A1": {
    "t": "s",
    "v": "date"
  },
  "B1": {
    "t": "s",
    "v": "no date"
  },
  "A2": {
    "t": "d",
    "v": "2018-01-02T00:00:00.000Z",
    "w": "1/2/18"
  },
  "B2": {
    "t": "s",
    "v": "2018-01-01T00:00:00.000Z"
  },
  "!ref": "A1:B2"
}
sheetjs v 0.11.17
browser: chrome 63 (mac),

**Comment by dominikg** [comment]
This happens because the [fuzzydate function](https://github.com/SheetJS/js-xlsx/blob/edf7150ca803190afaca515064b8ab387b94d336/bits/20_jsutils.js#L122) validates parsed dates that are parsed as the january first or any day of 2001 more strictly.

In these cases the unparsed string has to contain a 3 letter month substring or must only consist of characters 0-9-:,/\.,

```
function fuzzydate(s/*:string*/)/*:Date*/ {
	var o = new Date(s), n = new Date(NaN);
	var y = o.getYear(), m = o.getMonth(), d = o.getDate();
	if(isNaN(d)) return n;
	if(y < 0 || y > 8099) return n;
	if((m > 0 || d > 1) && y != 101) return o;
	if(s.toLowerCase().match(/jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec/)) return o;
	if(s.match(/[^-0-9:,\/\\]/)) return n;
	return o;
}
```

One possible fix for this without touching the general logic would be to allow T and Z in this regex: `if(s.match(/[^-0-9:,\/\\]/)) return n;`

Sidenote:
I think that trying to weed out false positives from the very lenient Date constructor like this is like playing a game of whack-a-mole.

A proper fix could be an option to supply column type information to the read call, include a set of default parsers for frequently used types and another option to define custom column-types/parsers.

**Comment by alecat88** [comment]
Just overwrite the logic with `function fuzzydate(s/*:string*/)/*:Date*/ {
	var o = new Date(s), n = new Date(NaN);
	var y = o.getYear(), m = o.getMonth(), d = o.getDate();
	if(isNaN(d)) return n;
	if(y < 0 || y > 8099) return n;
	if((m > 0 || d > 1) && y != 101) return o;
	if(s.toLowerCase().match(/jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec/)) return o;
	**if (d === 1 && m ===0) return o;**
	if(s.match(/[^-0-9:,\/\\]/)) return n;
	return o;
}`

**Comment by JerryDoubleU** [comment]
I'm experiencing the same issue.

**Comment by kgjersda** [comment]
Still a problem in master branch.

**Comment by FlavioRodr** [comment]
wouldn't it be fair to always allow valid ISO8601 formats?
My dates which contain 2001 always fail, despite being valid ISO8601 dates

Besides, Date.prototype.getYear() is deprecated

**Comment by FlavioRodr** [comment]
> Unfortunately Excel does not understand `2018-01-01T00:00:00.000Z` to be a date, entered manually or in a CSV file. To test, try the following CSV
> 
> ```
> String,=TYPE(C1),="2018-01-01T00:00:00.000Z"
> Date,=TYPE(C2),2018-01-01T00:00:00.000Z
> ```
> 
> <img alt="issue959" width="269" src="https://user-images.githubusercontent.com/6070939/148997210-95bea9c7-daf0-4737-ad6a-ee0e7b4ffaef.png">
> 
> Excel will show B1 = 2 and B2 = 2. [The return value 2 means Excel thinks the cell is a text cell](https://support.microsoft.com/en-us/office/type-function-45b4e688-4bc3-48b3-a105-ffa892995899)
> 
> You can manually enter an ISO8601 string in the formula bar and see the same result.

Actually I'm not facing the issue when seeing data in excel. The issue happens in XLSX.read('csv string', { cellDates: true })
If I debug the workbook produced from it, the "type" for any date which year is 2001 fails to reconize as date, and defaults to string

https://github.com/SheetJS/sheetjs/blob/0ddeba4fc358394438e3651910bce3b3ef29578a/xlsx.mjs#L2933

why does fuzzydate check for 'y != 101'?

**Comment by reviewher** [comment]
Grouping into #1300 

@FlavioRodr 

```js
new Date("This is not a Date 1")
// Mon Jan 01 2001 00:00:00 GMT-0500 (Eastern Standard Time)
```

Most of Chrome's bad date parsing is 2001, for which

```js
new Date("This is not a Date 1").getYear()
// 101
```
