### ISSUE TITLE
bug with GBP sign and Dollar sign

### ISSUE THREAD

**Issue by AviAkGlobal** [SheetJS/sheetjs#975]
I've got an Excel sheet with GBP values ( for example: 100£ ) in a cell and what I'm getting after reading is 100£$. The cell formatting in this case is [$-en-US,1]"£"0.00;("£"0.00) .

Also, working with 100£-like values with brackets, such as ( ), will end up with invalid value, for example, the following value -13168.76 with formatting [$-en-US,1]"£"0.00;("£"0.00) will result in the following value after reading the file with (1316£8.76). 

I believe it happens with other signs as well - but with $ everything works as expected.

**Comment by abhishek0196** [comment]
[stackblitz](https://stackblitz.com/edit/angular-excel-read-table-ygjnnq?file=src/app/sheet.component.ts) on this demo I tried with GBP sign that worked perfectly, I think this issue needs to be closed. @SheetJSDev

**Comment by SheetJSDev** [comment]
@AviAkGlobal please reopen if the issue persists
