### ISSUE TITLE
Set document header for Excel in Page Layout

### ISSUE THREAD

**Issue by hauteville86** [SheetJS/sheetjs#997]
Hello,

I'm not sure whether this issue has been already implemented, but I've tried to find some information about the possibility of setting your own document header in Page Layout and so far my efforts are rather fruitless.

Is it possible to create your own headers and footers by using SheetJS?

By document header I mean the following structure from the xl/worksheets/Sheet.xml file (which you can get by unzipping the .xlsx file) :

`<headerFooter>
    <oddHeader></oddHeader>
    <oddFooter></oddFooter>
</headerFooter>
`

I will appreciate every suggestion and definitely post the correct answer once I  have found it.

**Comment by hauteville86** [comment]
Ok, I've made it by adding a custom function inside  write_ws_xml function at 12284 before the following line: 
`if(o.length>2) { o[o.length] = ('</worksheet>'); o[1]=o[1].replace("/>",">"); }`

Nevertheless it would be great to see this feature available in standard in the nearest future.

**Comment by pedrobrost** [comment]
@hauteville86 could you tell us a little more about your solution? I'm trying to accomplish this and it would be really helpful :)

**Comment by hauteville86** [comment]
@pedrobrost 
Sure.You can actually unzip an xlsx file yourself and in the resulted folder structure find the following file:
xl/worksheets/{nameOfTheSheet}.xml, which is an XML representation of the sheet you are working on. You can open it with any text editor and have a look at the details of the XML implementation. 

The document header has following structure:
`<headerFooter> <oddHeader></oddHeader> <oddFooter></oddFooter> </headerFooter>`
and it is probably missing in your current XML file. Normally it stands just before the closing </worksheet> tag. The content of the file is created within the write_ws_xml() function and the above structure with attributes related to your problem should be added as a string to the o[] array (since this array holds all the content of the XML structure) before the last line of the write_ws_xml() function.
A string should have more or less the following structure:
`"<headerFooter> <oddHeader>" + headerText + "</oddHeader> <oddFooter>" + footerText + "</oddFooter> </headerFooter>"`
The line number of the file js-xlsx.js has unfortunately changed after the last update and now it's 13365.

**Comment by pedrobrost** [comment]
It worked! Now I'll see how to fork this and use it in my app (I've never do it before)

Thank you!!

**Comment by SheetJSDev** [comment]
General print settings are a feature of our [Pro builds](https://sheetjs.com/pro).  For simple text `headerFooter` suffices, but for more advanced settings you also need to generate a drawing.
